/**
 * @file Permisos internos sobre la PLATAFORMA.
 * @business Esta pieza controla quién puede operar Atlas y deja evidencia de cada asignación de privilegios.
 * @system enumera los permisos internos de este grupo.
 */
import { permission, type InternalPermissionSeed } from './internal-rbac.permission-builder.js';

/**
 * Lo que se opera del propio sistema: el catálogo de endpoints y tablas, la salud de la red y de
 * las herramientas, los artefactos del Motor y las suites de calidad y de stress.
 */
export const PLATFORM_PERMISSION_SEEDS: readonly InternalPermissionSeed[] = [
  permission({
    code: 'auth.internal.me.read',
    module: 'auth',
    resource: 'internal_session',
    action: 'read',
    description: 'Consultar perfil, roles y permisos efectivos propios.',
    riskLevel: 'LOW',
  }),
  permission({
    code: 'systems.dashboard.read',
    module: 'systems',
    resource: 'dashboard',
    action: 'read',
    description: 'Consultar dashboard técnico del portal interno.',
  }),
  permission({
    code: 'systems.endpoints.read',
    module: 'systems',
    resource: 'endpoint_catalog',
    action: 'read',
    description: 'Consultar catálogo de endpoints.',
  }),
  permission({
    code: 'systems.endpoints.execute',
    module: 'systems',
    resource: 'endpoint_catalog',
    action: 'execute',
    description: 'Ejecutar endpoint controlado desde QA.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.flows.read',
    module: 'systems',
    resource: 'flow_catalog',
    action: 'read',
    description: 'Consultar Flujos: el mapa derivado del código de pantallas, endpoints, permisos y hallazgos.',
  }),
  permission({
    code: 'systems.flows.analyze',
    module: 'systems',
    resource: 'flow_catalog',
    action: 'analyze',
    description: 'Cargar o regenerar el catálogo de Flujos desde el artefacto derivado.',
  }),
  permission({
    code: 'systems.flows.review',
    module: 'systems',
    resource: 'flow_catalog',
    action: 'review',
    description: 'Confirmar o descartar hallazgos y conexiones inferidas de Flujos.',
  }),
  permission({
    code: 'systems.endpoints.discover',
    module: 'systems',
    resource: 'endpoint_catalog',
    action: 'discover',
    description: 'Descubrir endpoints y actualizar revisión.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.endpoints.catalogSeedRefresh',
    module: 'systems',
    resource: 'endpoint_catalog',
    action: 'seed_refresh',
    description: 'Refrescar catálogo técnico desde seed.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.dataEntities.read',
    module: 'systems',
    resource: 'data_entity',
    action: 'read',
    description: 'Consultar entidades y tablas catalogadas.',
  }),
  permission({
    code: 'systems.dataEntities.updateMetadata',
    module: 'systems',
    resource: 'data_entity',
    action: 'update_metadata',
    description: 'Actualizar metadata técnica.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.reviewQueue.read',
    module: 'systems',
    resource: 'review_queue',
    action: 'read',
    description: 'Consultar cola de revisión.',
  }),
  permission({
    code: 'systems.reviewQueue.resolve',
    module: 'systems',
    resource: 'review_queue',
    action: 'resolve',
    description: 'Resolver elementos de revisión.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.tools.read',
    module: 'systems',
    resource: 'tool_catalog',
    action: 'read',
    description: 'Consultar herramientas internas.',
  }),
  permission({
    code: 'systems.network.read',
    module: 'systems',
    resource: 'network_health',
    action: 'read',
    description: 'Consultar la salud de la RED de bloques del ecosistema.',
  }),
  permission({
    code: 'systems.network.federate',
    module: 'systems',
    resource: 'block_catalog',
    action: 'federate',
    description: 'Refederar el catálogo de un bloque del ecosistema.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.decisionEngine.artifacts.read',
    module: 'systems',
    resource: 'decision_artifact',
    action: 'read',
    description: 'Consultar los artefactos ACTIVOS del motor de decisión.',
  }),
  permission({
    code: 'systems.tools.health.read',
    module: 'systems',
    resource: 'tool_health',
    action: 'read',
    description: 'Consultar salud de herramientas internas.',
  }),
  permission({
    code: 'systems.tools.inferRequirements',
    module: 'systems',
    resource: 'tool_requirements',
    action: 'infer',
    description: 'Inferir requisitos de herramientas.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.qa.read',
    module: 'systems',
    resource: 'qa_suite',
    action: 'read',
    description: 'Consultar suites y corridas QA.',
  }),
  permission({
    code: 'systems.qa.execute',
    module: 'systems',
    resource: 'qa_run',
    action: 'execute',
    description: 'Ejecutar suites QA controladas.',
    riskLevel: 'HIGH',
    requiresReason: true,
  }),
  permission({
    code: 'systems.stress.read',
    module: 'systems',
    resource: 'stress_profile',
    action: 'read',
    description: 'Consultar perfiles y corridas stress.',
  }),
  permission({
    code: 'systems.stress.execute',
    module: 'systems',
    resource: 'stress_run',
    action: 'execute',
    description: 'Ejecutar stress controlado.',
    riskLevel: 'CRITICAL',
    requiresReason: true,
  }),
];
