/**
 * @file Catálogo de recetas: el expediente que el comercio completa con su propia sesión.
 * @business Esta pieza es el tramo del comercio: alta del partner, representante con su poder,
 *   registro, perfil, contacto verificado con el código real, sucursal, caja y los dos QR de cobro.
 * @system los pasos los ejecuta `merchant_user`; el poder y los QR son bytes reales subidos a la URL
 *   firmada, y el QR lleva un código legible (fixture `payment_qr`) porque el backend lo decodifica.
 */
import type { RecipeStep } from '../domain/journey-recipe.types.js';
import { SYNTHETIC_UPLOAD_BYTES } from '../fixtures/synthetic-upload.js';

const p = (suffix: string) => `/partner-onboarding/{{resources.partnerId}}${suffix}`;

const DOSSIER: RecipeStep[] = [
  {
    stepKey: 'partner.start',
    workflowStepCode: 'partner.start',
    method: 'POST',
    path: '/partner-onboarding/start',
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: {
      legalName: 'Comercio Sintético {{persona.lastName}} {{persona.personaKey}} SRL',
      tradeName: 'QA {{persona.lastName}} {{persona.personaKey}}',
      taxId: { $ref: 'persona.documentNumber' },
      contactEmail: { $ref: 'persona.email' },
      contactPhone: { $ref: 'persona.phone' },
    },
    expect: { status: [200, 201], assertions: [{ kind: 'equals', path: 'data.onboardingStatus', expected: 'draft' }] },
    extract: [{ to: 'resources.partnerId', from: 'response.data.partnerId', required: true }],
  },
  {
    stepKey: 'partner.mine',
    workflowStepCode: 'partner.mine',
    method: 'GET',
    path: '/partner-onboarding/mine',
    actor: 'merchant_user',
    expect: { status: [200] },
  },
  // El poder se sube ANTES de declarar al representante: declararlo sin poder no lo acredita.
  {
    stepKey: 'partner.documents_upload_url',
    workflowStepCode: 'partner.documents_upload_url',
    method: 'POST',
    path: p('/documents/upload-url'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: { documentKind: 'power-of-attorney', contentType: 'image/jpeg', sizeBytes: SYNTHETIC_UPLOAD_BYTES },
    expect: { status: [200, 201], assertions: [{ kind: 'type', path: 'data.uploadUrl', type: 'string' }] },
    extract: [
      { to: 'resources.poaUrl', from: 'response.data.uploadUrl', required: true },
      { to: 'resources.poaKey', from: 'response.data.storageKey', required: true },
    ],
  },
  {
    stepKey: 'partner.upload_power_of_attorney',
    method: 'PUT',
    path: '(almacenamiento QA)',
    actor: 'anonymous',
    upload: { urlFrom: 'resources.poaUrl', image: 'identity_front', extractSha256To: 'resources.poaSha256' },
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.legal_representative',
    workflowStepCode: 'partner.legal_representative',
    method: 'POST',
    path: p('/legal-representative'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: {
      fullName: '{{persona.firstName}} {{persona.lastName}}',
      documentType: 'ci',
      documentNumber: { $ref: 'persona.documentNumber' },
      powerOfAttorneyKey: { $ref: 'resources.poaKey' },
    },
    expect: { status: [200, 201] },
  },
  {
    stepKey: 'partner.commercial_registry',
    workflowStepCode: 'partner.commercial_registry',
    method: 'POST',
    path: p('/commercial-registry'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: { commercialRegistry: 'FUNDEMPRESA-QA-{{persona.documentNumber}}' },
    expect: { status: [200, 201] },
  },
  {
    stepKey: 'partner.commercial_profile',
    workflowStepCode: 'partner.commercial_profile',
    method: 'PATCH',
    path: p('/commercial-profile'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: { tradeName: 'Tienda QA {{persona.personaKey}}', contactPhone: { $ref: 'persona.phone' } },
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.contact_request',
    workflowStepCode: 'partner.contact_request',
    method: 'POST',
    path: p('/contact-verification/request'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: {},
    expect: { status: [200, 202] },
  },
  {
    stepKey: 'partner.contact_code',
    method: 'GET',
    path: '(buzón QA)',
    actor: 'anonymous',
    otp: { channel: 'email', toFrom: 'persona.email', extractTo: 'session.otp.partner' },
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.contact_submit',
    workflowStepCode: 'partner.contact_submit',
    method: 'POST',
    path: p('/contact-verification/submit'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: { code: { $ref: 'session.otp.partner' } },
    expect: { status: [200, 201] },
  },
];

const NETWORK: RecipeStep[] = [
  {
    stepKey: 'partner.branch_create',
    workflowStepCode: 'partner.branch_create',
    method: 'POST',
    path: p('/branches'),
    actor: 'merchant_user',
    dependsOn: ['partner.start'],
    idempotency: 'per_operation',
    body: {
      branchCode: 'CENTRAL-{{persona.personaKey}}',
      name: 'Sucursal central',
      addressLine: 'Av. Sintética 100',
      city: { $ref: 'persona.city' },
    },
    expect: { status: [200, 201] },
    extract: [{ to: 'resources.branchId', from: 'response.data.branchId', required: true }],
  },
  {
    stepKey: 'partner.branches',
    workflowStepCode: 'partner.branches',
    method: 'GET',
    path: p('/branches'),
    actor: 'merchant_user',
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.branch_update',
    workflowStepCode: 'partner.branch_update',
    method: 'PATCH',
    path: p('/branches/{{resources.branchId}}'),
    actor: 'merchant_user',
    dependsOn: ['partner.branch_create'],
    idempotency: 'per_operation',
    body: { erpBranchId: 'ERP-QA-{{persona.personaKey}}' },
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.pos_create',
    workflowStepCode: 'partner.pos_create',
    method: 'POST',
    path: p('/branches/{{resources.branchId}}/pos-terminals'),
    actor: 'merchant_user',
    dependsOn: ['partner.branch_create'],
    idempotency: 'per_operation',
    body: { terminalSerial: 'QA-{{run.nonce}}-{{persona.personaKey}}', terminalAlias: 'Caja 1' },
    expect: { status: [200, 201] },
    extract: [{ to: 'resources.terminalId', from: 'response.data.terminalId', required: true }],
  },
  {
    stepKey: 'partner.pos_list',
    workflowStepCode: 'partner.pos_list',
    method: 'GET',
    path: p('/pos-terminals'),
    actor: 'merchant_user',
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.pos_update',
    workflowStepCode: 'partner.pos_update',
    method: 'PATCH',
    path: p('/pos-terminals/{{resources.terminalId}}'),
    actor: 'merchant_user',
    dependsOn: ['partner.pos_create'],
    idempotency: 'per_operation',
    body: { status: 'active' },
    expect: { status: [200] },
  },
];

const FILES: RecipeStep[] = [
  {
    stepKey: 'partner.qr_upload_url',
    workflowStepCode: 'partner.qr_upload_url',
    method: 'POST',
    path: p('/qr-codes/upload-url'),
    actor: 'merchant_user',
    dependsOn: ['partner.branch_create'],
    idempotency: 'per_operation',
    body: { qrKind: 'business', contentType: 'image/jpeg', sizeBytes: SYNTHETIC_UPLOAD_BYTES },
    expect: { status: [200, 201], assertions: [{ kind: 'type', path: 'data.uploadUrl', type: 'string' }] },
    extract: [
      { to: 'resources.qrUrl', from: 'response.data.uploadUrl', required: true },
      { to: 'resources.qrKey', from: 'response.data.storageKey', required: true },
    ],
  },
  {
    stepKey: 'partner.upload_qr',
    method: 'PUT',
    path: '(almacenamiento QA)',
    actor: 'anonymous',
    upload: { urlFrom: 'resources.qrUrl', image: 'payment_qr', extractSha256To: 'resources.qrSha256' },
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.qr_create',
    workflowStepCode: 'partner.qr_create',
    method: 'POST',
    path: p('/qr-codes'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: { qrKind: 'business', branchId: { $ref: 'resources.branchId' }, storageKey: { $ref: 'resources.qrKey' } },
    expect: { status: [200, 201] },
    extract: [{ to: 'resources.qrId', from: 'response.data.qrId', required: true }],
  },
  {
    stepKey: 'partner.qr_list',
    workflowStepCode: 'partner.qr_list',
    method: 'GET',
    path: p('/qr-codes'),
    actor: 'merchant_user',
    expect: { status: [200] },
  },
  // El QR bancario de cobro es el de la empresa: sin sucursal. Sin él el expediente no se envía.
  {
    stepKey: 'partner.bank_qr_upload_url',
    method: 'POST',
    path: p('/qr-codes/upload-url'),
    actor: 'merchant_user',
    dependsOn: ['partner.start'],
    idempotency: 'per_operation',
    body: { qrKind: 'bank', contentType: 'image/jpeg', sizeBytes: SYNTHETIC_UPLOAD_BYTES },
    expect: { status: [200, 201], assertions: [{ kind: 'type', path: 'data.uploadUrl', type: 'string' }] },
    extract: [
      { to: 'resources.bankQrUrl', from: 'response.data.uploadUrl', required: true },
      { to: 'resources.bankQrKey', from: 'response.data.storageKey', required: true },
    ],
  },
  {
    stepKey: 'partner.upload_bank_qr',
    method: 'PUT',
    path: '(almacenamiento QA)',
    actor: 'anonymous',
    upload: { urlFrom: 'resources.bankQrUrl', image: 'payment_qr', extractSha256To: 'resources.bankQrSha256' },
    expect: { status: [200] },
  },
  {
    stepKey: 'partner.bank_qr_create',
    method: 'POST',
    path: p('/qr-codes'),
    actor: 'merchant_user',
    idempotency: 'per_operation',
    body: { qrKind: 'bank', storageKey: { $ref: 'resources.bankQrKey' }, bankInstitutionCode: 'BNB', accountNumberMasked: '****0000' },
    expect: { status: [200, 201] },
    extract: [{ to: 'resources.bankQrId', from: 'response.data.qrId', required: true }],
  },
];

export const PARTNER_DOSSIER_STEPS: RecipeStep[] = [...DOSSIER, ...NETWORK, ...FILES];
