/**
 * Árbol REAL del recorrido estándar de Atlas: registro -> onboarding -> revisión -> habilitación ->
 * crédito, expresado como etapas, subetapas, pasos, dependencias y transiciones.
 *
 * Cada `routePath` de este archivo corresponde a un endpoint que EXISTE hoy en `src/modules/`. No se
 * inventó ninguno: el informe de consistencia (`GET /operations/workflows/:code/consistency`) compara
 * esta definición contra las rutas que el proceso tiene montadas y marca como error cualquier paso
 * que no exista. Los roles son los del decorador `@Roles(...)` de cada handler; los estados son los
 * de `customer-lifecycle.constants.ts`; los códigos de bloqueo, los de
 * `customer-eligibility.constants.ts`. Esa es la trazabilidad que hace útil al catálogo: si alguna
 * de esas tres fuentes cambia y este archivo no, el informe lo dice.
 *
 * Las reglas de completitud (`completionRule`) NO reimplementan el cálculo de avance: nombran la
 * sección, el estado o los bloqueadores que ya produce `CustomerEligibilityService`. Una etapa sin
 * señal automática se declara `manual` y se reporta como `not_applicable`, en vez de fingir que el
 * sistema sabe si un analista ya la resolvió.
 */

import { CUSTOMER_LIFECYCLE_STATUSES } from '../../modules/customers/customer-lifecycle.constants.js';

export type WorkflowStepSeed = {
  stepCode: string;
  name: string;
  description: string;
  httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  routePath: string;
  executionOrder: number;
  isMandatory?: boolean;
  isRepeatable?: boolean;
  requiresIdempotencyKey?: boolean;
  requiresAuth?: boolean;
  isFlowEntry?: boolean;
  isFlowExit?: boolean;
  allowedRoles: string[];
  requiredStates?: string[];
  resultingStates?: string[];
  inputContract?: Record<string, unknown>;
  outputContract?: Record<string, unknown>;
  validationRules?: string[];
  possibleErrors?: string[];
  retryStrategy?: Record<string, unknown>;
  producesEvents?: string[];
  consumesEvents?: string[];
  successCriteria?: Record<string, unknown>;
  failureCriteria?: Record<string, unknown>;
};

export type WorkflowStageSeed = {
  stageCode: string;
  name: string;
  description: string;
  moduleCode: string;
  actorType: 'customer' | 'internal_user' | 'system' | 'external_provider';
  displayOrder: number;
  isOptional?: boolean;
  isEntryStage?: boolean;
  isTerminalStage?: boolean;
  allowedRoles?: string[];
  requiredStates?: string[];
  resultingStates?: string[];
  completionRule: Record<string, unknown>;
  steps: WorkflowStepSeed[];
  subStages?: WorkflowStageSeed[];
};

export type WorkflowDependencySeed = {
  stepCode: string;
  dependsOnStepCode: string;
  dependencyType: 'requires_completion' | 'requires_data' | 'soft';
  description: string;
};

export type WorkflowTransitionSeed = {
  transitionCode: string;
  fromStepCode: string | null;
  toStepCode: string | null;
  conditionType: 'always' | 'on_success' | 'on_error' | 'on_state' | 'conditional';
  conditionExpression?: Record<string, unknown>;
  description: string;
  displayOrder: number;
  isDefaultPath?: boolean;
};

export type WorkflowSeed = {
  workflowCode: string;
  version: string;
  name: string;
  description: string;
  processType: string;
  ownerDomain: string;
  status: string;
  isDefault: boolean;
  entryStageCode: string;
  terminalStageCodes: string[];
  successCriteria: Record<string, unknown>;
  failureCriteria: Record<string, unknown>;
  metadata: Record<string, unknown>;
  stages: WorkflowStageSeed[];
  dependencies: WorkflowDependencySeed[];
  transitions: WorkflowTransitionSeed[];
};

const CUSTOMER_AND_INTERNAL = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const CUSTOMER_AND_INTERNAL_FULL = [
  'customer',
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'fraud_analyst',
  'admin',
  'platform_admin',
];
const SESSION_ROLES = [...CUSTOMER_AND_INTERNAL_FULL, 'system'];
const CREDIT_OPS_ROLES = ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const KYC_DECISION_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'];

/** Retry por defecto de los comandos idempotentes: la clave permite reintentar sin duplicar efecto. */
const IDEMPOTENT_RETRY = { strategy: 'client_retry_with_idempotency_key', maxAttempts: 3, backoff: 'exponential' };
/** Las lecturas se reintentan sin riesgo; los comandos sin clave de idempotencia, no. */
const READ_RETRY = { strategy: 'safe_retry', maxAttempts: 3, backoff: 'exponential' };
const NO_RETRY = { strategy: 'no_retry', reason: 'Comando no idempotente: reintentar puede duplicar el efecto.' };

const registration: WorkflowStageSeed = {
  stageCode: 'registration',
  name: 'Registro y acceso',
  description: 'Crea el cliente, sus credenciales y el flujo de onboarding, y obtiene el token con el que se recorre el resto del proceso.',
  moduleCode: 'customer_onboarding',
  actorType: 'customer',
  displayOrder: 10,
  isEntryStage: true,
  allowedRoles: [],
  requiredStates: [],
  resultingStates: ['registered'],
  completionRule: { type: 'no_blockers', blockerCodes: ['NO_CREDENTIALS'] },
  steps: [
    {
      stepCode: 'registration.consent_documents',
      name: 'Consultar los documentos legales vigentes',
      description:
        'Versión publicada y vigente de los textos que el cliente debe aceptar. Es público a propósito: se muestra antes de registrarse.',
      httpMethod: 'GET',
      routePath: '/consent-documents/active',
      executionOrder: 10,
      isMandatory: false,
      isRepeatable: true,
      requiresAuth: false,
      allowedRoles: [],
      outputContract: { documents: 'ConsentDocumentDto[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'registration.start',
      name: 'Iniciar el onboarding',
      description: 'Crea cliente, credenciales y flujo de onboarding de forma idempotente. Punto de entrada del recorrido completo.',
      httpMethod: 'POST',
      routePath: '/customer-onboarding/start',
      executionOrder: 20,
      requiresIdempotencyKey: true,
      requiresAuth: false,
      isFlowEntry: true,
      allowedRoles: [],
      resultingStates: ['registered'],
      inputContract: { identifier: 'string', channel: 'phone|email', password: 'string', deviceFingerprint: 'string?' },
      outputContract: { customerId: 'string', onboardingFlowId: 'string' },
      validationRules: ['startOnboardingSchema (Zod)', 'Identificador único por tenant (índice parcial de email/teléfono)'],
      possibleErrors: ['409 CUSTOMER_ALREADY_EXISTS', '422 INVALID_IDENTIFIER', '429 THROTTLED'],
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['customer.registered'],
      successCriteria: { statusCodes: [201], indicator: 'customerId presente' },
      failureCriteria: { statusCodes: [409, 422] },
    },
    {
      stepCode: 'registration.login',
      name: 'Autenticarse',
      description: 'Devuelve el access token con el que se autorizan todos los pasos siguientes.',
      httpMethod: 'POST',
      routePath: '/auth/login',
      executionOrder: 30,
      requiresAuth: false,
      allowedRoles: [],
      inputContract: { identifier: 'string', password: 'string' },
      outputContract: { accessToken: 'string', refreshToken: 'string', mfaRequired: 'boolean' },
      possibleErrors: ['401 INVALID_CREDENTIALS', '429 THROTTLED'],
      retryStrategy: NO_RETRY,
      producesEvents: ['auth.login_succeeded', 'auth.login_failed'],
      successCriteria: { statusCodes: [200] },
      failureCriteria: { statusCodes: [401, 429] },
    },
    {
      stepCode: 'registration.mfa',
      name: 'Completar el segundo factor',
      description: 'Solo si el login respondió `mfaRequired`. Canjea el desafío por un token de sesión completo.',
      httpMethod: 'POST',
      routePath: '/auth/mfa',
      executionOrder: 40,
      isMandatory: false,
      allowedRoles: [],
      inputContract: { challengeId: 'string', code: 'string' },
      possibleErrors: ['401 INVALID_MFA_CODE', '410 MFA_CHALLENGE_EXPIRED'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'registration.login_pin',
      name: 'Autenticarse con PIN',
      description: 'Alternativa de acceso para clientes que configuraron PIN. Sustituye a `registration.login`, no lo complementa.',
      httpMethod: 'POST',
      routePath: '/auth/login/pin',
      executionOrder: 45,
      isMandatory: false,
      requiresAuth: false,
      allowedRoles: [],
      possibleErrors: ['401 INVALID_PIN', '429 THROTTLED'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'registration.me',
      name: 'Consultar el actor autenticado',
      description: 'Identidad y rol del token vigente. La app la usa para decidir qué recorrido mostrar.',
      httpMethod: 'GET',
      routePath: '/auth/me',
      executionOrder: 50,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: [],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'registration.refresh',
      name: 'Renovar el token de acceso',
      description: 'Mantiene viva la sesión durante un recorrido largo sin obligar a volver a autenticarse.',
      httpMethod: 'POST',
      routePath: '/auth/refresh',
      executionOrder: 60,
      isMandatory: false,
      isRepeatable: true,
      requiresAuth: false,
      allowedRoles: [],
      possibleErrors: ['401 INVALID_REFRESH_TOKEN', '401 TOKEN_REVOKED'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'registration.logout',
      name: 'Cerrar la sesión de acceso',
      description: 'Revoca el refresh token. Es el cierre del recorrido de acceso, no del proceso de negocio.',
      httpMethod: 'POST',
      routePath: '/auth/logout',
      executionOrder: 70,
      isMandatory: false,
      requiresAuth: false,
      allowedRoles: [],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200, 204] },
    },
  ],
};

const sessionBootstrap: WorkflowStageSeed = {
  stageCode: 'session_bootstrap',
  name: 'Sesión y telemetría',
  description:
    'Abre la sesión observada y alimenta las señales anti-fraude. Es opcional para completar el trámite, pero su ausencia empobrece la evaluación de riesgo.',
  moduleCode: 'sessions',
  actorType: 'customer',
  displayOrder: 20,
  isOptional: true,
  allowedRoles: SESSION_ROLES,
  requiredStates: ['registered', 'onboarding_in_progress', 'observed', 'active'],
  completionRule: { type: 'manual' },
  steps: [
    {
      stepCode: 'session.start',
      name: 'Abrir sesión',
      description: 'Registra dispositivo, GPS y contexto de la sesión del cliente.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/sessions/start',
      executionOrder: 10,
      requiresIdempotencyKey: true,
      isMandatory: false,
      allowedRoles: SESSION_ROLES,
      outputContract: { sessionId: 'string' },
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['session.started'],
      successCriteria: { statusCodes: [201] },
    },
    {
      stepCode: 'session.heartbeat',
      name: 'Mantener viva la sesión',
      description: 'Latido periódico con la posición y el estado del dispositivo.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/sessions/:sessionId/heartbeat',
      executionOrder: 20,
      isMandatory: false,
      isRepeatable: true,
      requiresIdempotencyKey: true,
      allowedRoles: SESSION_ROLES,
      retryStrategy: IDEMPOTENT_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'session.telemetry',
      name: 'Enviar telemetría de comportamiento',
      description: 'Lote validado y acotado de señales de interacción y dispositivo.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/telemetry/batch',
      executionOrder: 30,
      isMandatory: false,
      isRepeatable: true,
      requiresIdempotencyKey: true,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      retryStrategy: IDEMPOTENT_RETRY,
      successCriteria: { statusCodes: [202, 200] },
    },
    {
      stepCode: 'session.state',
      name: 'Consultar el estado de la sesión',
      description: 'Sesión vigente del cliente, si la hay.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/session-state',
      executionOrder: 40,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: SESSION_ROLES,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'session.end',
      name: 'Cerrar sesión',
      description: 'Cierre explícito. Sin él, la sesión caduca por el job de expiración.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/sessions/:sessionId/end',
      executionOrder: 50,
      isMandatory: false,
      requiresIdempotencyKey: true,
      allowedRoles: SESSION_ROLES,
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['session.ended'],
      successCriteria: { statusCodes: [200] },
    },
  ],
};

const dataCapture: WorkflowStageSeed = {
  stageCode: 'data_capture',
  name: 'Captura de datos y evidencia (KYC)',
  description:
    'Las seis secciones obligatorias del onboarding más los consentimientos. Cada subetapa se da por cerrada con la MISMA regla que decide la habilitación crediticia.',
  moduleCode: 'customer_onboarding',
  actorType: 'customer',
  displayOrder: 30,
  allowedRoles: CUSTOMER_AND_INTERNAL,
  requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
  resultingStates: ['onboarding_in_progress'],
  completionRule: {
    type: 'no_blockers',
    blockerCodes: [
      'CONTACT_NOT_VERIFIED',
      'PROFILE_INCOMPLETE',
      'FINANCIAL_PROFILE_INCOMPLETE',
      'ADDRESS_MISSING',
      'IDENTITY_DOCUMENT_MISSING',
      'IDENTITY_DOCUMENT_EXPIRED',
      'REFERENCES_INSUFFICIENT',
      'CONSENT_MISSING',
    ],
  },
  steps: [
    {
      stepCode: 'onboarding.status',
      name: 'Consultar el avance del onboarding',
      description: 'Secciones, porcentaje, `canSubmit`, `nextStep` y bloqueadores. Es el punto de reanudación del proceso.',
      httpMethod: 'GET',
      routePath: '/customer-onboarding/:customerId/status',
      executionOrder: 10,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      retryStrategy: READ_RETRY,
      outputContract: { sections: 'OnboardingSection[]', nextStep: 'string', blockers: 'EligibilityBlocker[]' },
      successCriteria: { statusCodes: [200] },
    },
  ],
  subStages: [
    {
      stageCode: 'contact_verification',
      name: 'Verificación de contacto',
      description: 'Alta del método de contacto y verificación por código de un solo uso. Solo se almacena el hash del código.',
      moduleCode: 'customer_onboarding',
      actorType: 'customer',
      displayOrder: 10,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      resultingStates: ['onboarding_in_progress'],
      completionRule: { type: 'onboarding_section', sectionCode: 'contact_verification' },
      steps: [
        {
          stepCode: 'contact.add_method',
          name: 'Registrar un método de contacto',
          description: 'Teléfono o correo sobre el que se hará la verificación.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/contact-methods',
          executionOrder: 10,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          inputContract: { contactType: 'phone|email', value: 'string', isPrimary: 'boolean?' },
          possibleErrors: ['409 CONTACT_ALREADY_REGISTERED', '422 INVALID_CONTACT_VALUE'],
          retryStrategy: NO_RETRY,
          successCriteria: { statusCodes: [201] },
        },
        {
          stepCode: 'contact.request_code',
          name: 'Solicitar el código de verificación',
          description: 'Emite un código real por el canal configurado, con cooldown por destino.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/contact-verification/request',
          executionOrder: 20,
          isRepeatable: true,
          requiresIdempotencyKey: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          possibleErrors: ['429 VERIFICATION_COOLDOWN_ACTIVE', '404 CONTACT_METHOD_NOT_FOUND'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['contact.verification_requested'],
          successCriteria: { statusCodes: [202, 200] },
        },
        {
          stepCode: 'contact.submit_code',
          name: 'Enviar el código recibido',
          description: 'Valida TTL, número de intentos y consumo único. No existe código de bypass.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/contact-verification/submit',
          executionOrder: 30,
          requiresIdempotencyKey: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          inputContract: { contactMethodId: 'string', code: 'string' },
          resultingStates: ['onboarding_in_progress'],
          possibleErrors: ['410 VERIFICATION_CODE_EXPIRED', '422 INVALID_VERIFICATION_CODE', '429 TOO_MANY_ATTEMPTS'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['contact.verified'],
          successCriteria: { statusCodes: [200], indicator: 'sección contact_verification completada' },
          failureCriteria: { statusCodes: [410, 422, 429] },
        },
      ],
    },
    {
      stageCode: 'personal_data',
      name: 'Datos personales',
      description: 'Nombre, apellido y fecha de nacimiento. La edad se valida contra el rango operable.',
      moduleCode: 'customer_onboarding',
      actorType: 'customer',
      displayOrder: 20,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: { type: 'onboarding_section', sectionCode: 'personal_data' },
      steps: [
        {
          stepCode: 'profile.update',
          name: 'Guardar el perfil personal',
          description: 'Autoguardado parcial: valida formato, no obligatoriedad. La completitud se exige al enviar el paquete.',
          httpMethod: 'PATCH',
          routePath: '/customer-onboarding/:customerId/profile',
          executionOrder: 10,
          isRepeatable: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          inputContract: { firstName: 'string?', lastName: 'string?', birthDate: 'YYYY-MM-DD?' },
          validationRules: ['Edad entre 18 y 100 años (MINIMUM/MAXIMUM_CUSTOMER_AGE_YEARS)'],
          possibleErrors: ['422 INVALID_BIRTH_DATE'],
          retryStrategy: NO_RETRY,
          successCriteria: { statusCodes: [200] },
        },
      ],
    },
    {
      stageCode: 'financial_profile',
      name: 'Perfil económico',
      description: 'Los seis atributos económicos obligatorios, persistidos en el modelo EAV versionado de atributos del cliente.',
      moduleCode: 'customer_onboarding',
      actorType: 'customer',
      displayOrder: 30,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: { type: 'onboarding_section', sectionCode: 'financial_profile' },
      steps: [
        {
          stepCode: 'financial.update',
          name: 'Guardar el perfil económico',
          description: 'Situación laboral, antigüedad, ingresos, egresos, actividad económica y origen de fondos.',
          httpMethod: 'PUT',
          routePath: '/customer-onboarding/:customerId/financial-profile',
          executionOrder: 10,
          isRepeatable: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          inputContract: {
            employmentStatus: 'enum',
            employmentSeniorityMonths: 'number',
            monthlyIncomeDeclared: 'number',
            monthlyExpensesDeclared: 'number',
            economicActivityCode: 'string',
            sourceOfFunds: 'enum',
          },
          possibleErrors: ['422 ATTRIBUTE_CATALOG_NOT_SEEDED', '422 INVALID_ATTRIBUTE_VALUE'],
          retryStrategy: NO_RETRY,
          successCriteria: { statusCodes: [200] },
        },
      ],
    },
    {
      stageCode: 'address',
      name: 'Domicilio',
      description: 'Dirección declarada con su observación GPS asociada.',
      moduleCode: 'customer_onboarding',
      actorType: 'customer',
      displayOrder: 40,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: { type: 'onboarding_section', sectionCode: 'address' },
      steps: [
        {
          stepCode: 'address.package',
          name: 'Registrar el domicilio',
          description: 'Alta o reemplazo de la dirección vigente, versionada, con la evidencia de geolocalización.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/address-package',
          executionOrder: 10,
          requiresIdempotencyKey: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          possibleErrors: ['422 INVALID_ADDRESS_PACKAGE'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['customer.address_registered'],
          successCriteria: { statusCodes: [201, 200] },
        },
      ],
    },
    {
      stageCode: 'identity_documents',
      name: 'Documentos de identidad',
      description: 'Carga del documento y verificación de identidad contra el proveedor configurado.',
      moduleCode: 'customer_onboarding',
      actorType: 'customer',
      displayOrder: 50,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: { type: 'onboarding_section', sectionCode: 'identity_documents' },
      steps: [
        {
          stepCode: 'identity.upload_url',
          name: 'Obtener URL firmada de carga',
          description: 'URL temporal para subir el archivo al almacenamiento sin que pase por el backend.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/documents/upload-url',
          executionOrder: 10,
          isMandatory: false,
          isRepeatable: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          outputContract: { uploadUrl: 'string', objectKey: 'string', expiresAt: 'ISO-8601' },
          retryStrategy: READ_RETRY,
          successCriteria: { statusCodes: [201, 200] },
        },
        {
          stepCode: 'identity.package',
          name: 'Registrar el documento de identidad',
          description: 'Tipo, número, vigencia y referencia a la evidencia cargada.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/identity-package',
          executionOrder: 20,
          requiresIdempotencyKey: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          possibleErrors: ['409 IDENTITY_DOCUMENT_ALREADY_REGISTERED', '422 IDENTITY_DOCUMENT_EXPIRED'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['customer.identity_document_registered'],
          successCriteria: { statusCodes: [201, 200] },
        },
        {
          stepCode: 'identity.verification',
          name: 'Verificar la identidad',
          description: 'Contrasta el documento contra el proveedor de identidad y deja el intento registrado, favorable o no.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/identity-verification',
          executionOrder: 30,
          requiresIdempotencyKey: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          possibleErrors: ['422 IDENTITY_VERIFICATION_FAILED', '503 PROVIDER_UNAVAILABLE'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['customer.identity_verification_attempted'],
          successCriteria: { statusCodes: [200], indicator: "result = 'verified'" },
          failureCriteria: { statusCodes: [422, 503] },
        },
      ],
    },
    {
      stageCode: 'reference_contacts',
      name: 'Referencias personales',
      description: 'Mínimo dos referencias personales; el máximo aceptado son cinco.',
      moduleCode: 'customer_onboarding',
      actorType: 'customer',
      displayOrder: 60,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: { type: 'onboarding_section', sectionCode: 'reference_contacts' },
      steps: [
        {
          stepCode: 'references.add',
          name: 'Agregar una referencia',
          description: 'Contacto de referencia con su relación declarada.',
          httpMethod: 'POST',
          routePath: '/customer-onboarding/:customerId/reference-contacts',
          executionOrder: 10,
          isRepeatable: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          validationRules: ['Mínimo 2 y máximo 5 referencias (REQUIRED/MAXIMUM_REFERENCE_CONTACTS)'],
          possibleErrors: ['422 TOO_MANY_REFERENCE_CONTACTS'],
          retryStrategy: NO_RETRY,
          successCriteria: { statusCodes: [201] },
        },
        {
          stepCode: 'references.list',
          name: 'Listar las referencias cargadas',
          description: 'Referencias vigentes del cliente.',
          httpMethod: 'GET',
          routePath: '/customer-onboarding/:customerId/reference-contacts',
          executionOrder: 20,
          isMandatory: false,
          isRepeatable: true,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          retryStrategy: READ_RETRY,
          successCriteria: { statusCodes: [200] },
        },
        {
          stepCode: 'references.remove',
          name: 'Eliminar una referencia',
          description: 'Corrección de una referencia cargada por error.',
          httpMethod: 'DELETE',
          routePath: '/customer-onboarding/:customerId/reference-contacts/:referenceId',
          executionOrder: 30,
          isMandatory: false,
          allowedRoles: CUSTOMER_AND_INTERNAL,
          possibleErrors: ['404 REFERENCE_CONTACT_NOT_FOUND'],
          retryStrategy: NO_RETRY,
          successCriteria: { statusCodes: [200, 204] },
        },
      ],
    },
    {
      stageCode: 'privacy_consents',
      name: 'Consentimientos de privacidad',
      description: 'Decisiones del titular sobre cada finalidad de tratamiento, contra la versión legal vigente.',
      moduleCode: 'customer_privacy',
      actorType: 'customer',
      displayOrder: 70,
      allowedRoles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: { type: 'no_blockers', blockerCodes: ['CONSENT_MISSING'] },
      steps: [
        {
          stepCode: 'consents.decisions',
          name: 'Registrar las decisiones de consentimiento',
          description: 'Otorga o revoca consentimientos contra el documento publicado vigente, dejando el evento inmutable.',
          httpMethod: 'POST',
          routePath: '/customers/:customerId/privacy/consent-decisions',
          executionOrder: 10,
          isRepeatable: true,
          requiresIdempotencyKey: true,
          allowedRoles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
          possibleErrors: ['404 CONSENT_DOCUMENT_NOT_FOUND', '422 CONSENT_DOCUMENT_NOT_PUBLISHED'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['privacy.consent_recorded'],
          successCriteria: { statusCodes: [201, 200] },
        },
        {
          stepCode: 'consents.data_subject_request',
          name: 'Ejercer un derecho del titular',
          description: 'Acceso, rectificación, portabilidad o supresión. No forma parte del camino feliz, pero sí del proceso.',
          httpMethod: 'POST',
          routePath: '/customers/:customerId/privacy/data-subject-requests',
          executionOrder: 20,
          isMandatory: false,
          requiresIdempotencyKey: true,
          allowedRoles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['privacy.data_subject_request_created'],
          successCriteria: { statusCodes: [201] },
        },
      ],
    },
  ],
};

const externalEvidence: WorkflowStageSeed = {
  stageCode: 'external_evidence',
  name: 'Evidencia externa',
  description:
    'Consulta controlada a proveedores externos (identidad, buró, telco, huella digital) con consentimiento, costo y resiliencia. Enriquece la decisión sin ser obligatoria para completar el trámite.',
  moduleCode: 'external_data',
  actorType: 'system',
  displayOrder: 40,
  isOptional: true,
  allowedRoles: SESSION_ROLES,
  requiredStates: ['onboarding_in_progress', 'under_review', 'observed'],
  completionRule: { type: 'manual' },
  steps: [
    {
      stepCode: 'external.consent',
      name: 'Registrar el consentimiento de consulta externa',
      description: 'Sin consentimiento vigente, la ejecución de la consulta se rechaza.',
      httpMethod: 'POST',
      routePath: '/external-data/consents',
      executionOrder: 10,
      isMandatory: false,
      allowedRoles: SESSION_ROLES,
      retryStrategy: NO_RETRY,
      producesEvents: ['external_data.consent_granted'],
      successCriteria: { statusCodes: [201] },
    },
    {
      stepCode: 'external.preview',
      name: 'Previsualizar costo y elegibilidad de la consulta',
      description: 'Devuelve costo estimado, política aplicable y si la consulta puede ejecutarse, sin ejecutarla.',
      httpMethod: 'POST',
      routePath: '/external-data/requests/preview',
      executionOrder: 20,
      isMandatory: false,
      allowedRoles: SESSION_ROLES,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'external.request',
      name: 'Ejecutar la consulta externa',
      description: 'Ejecuta contra el proveedor con caché, circuit breaker y auditoría de la respuesta.',
      httpMethod: 'POST',
      routePath: '/external-data/requests',
      executionOrder: 30,
      isMandatory: false,
      requiresIdempotencyKey: true,
      allowedRoles: SESSION_ROLES,
      possibleErrors: ['403 EXTERNAL_DATA_CONSENT_MISSING', '503 PROVIDER_UNAVAILABLE', '429 PROVIDER_RATE_LIMITED'],
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['external_data.request_completed'],
      successCriteria: { statusCodes: [200, 202] },
      failureCriteria: { statusCodes: [403, 429, 503] },
    },
    {
      stepCode: 'external.features',
      name: 'Consultar las variables derivadas',
      description: 'Variables construidas a partir de las respuestas externas, listas para el motor de riesgo.',
      httpMethod: 'GET',
      routePath: '/external-data/users/:customerId/features',
      executionOrder: 40,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: SESSION_ROLES,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
  ],
};

const submission: WorkflowStageSeed = {
  stageCode: 'submission',
  name: 'Envío a revisión',
  description:
    'Verifica la completitud del paquete y mueve al cliente a `under_review` con su evento de historial en la misma transacción.',
  moduleCode: 'customer_onboarding',
  actorType: 'customer',
  displayOrder: 50,
  allowedRoles: CUSTOMER_AND_INTERNAL,
  requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
  resultingStates: ['under_review'],
  completionRule: { type: 'lifecycle_status', statuses: ['under_review', 'active', 'suspended', 'rejected'] },
  steps: [
    {
      stepCode: 'onboarding.submit',
      name: 'Enviar el paquete a revisión',
      description:
        'Reevalúa la completitud en el servidor; si falta algo responde `ONBOARDING_INCOMPLETE` con las secciones pendientes y no cambia nada.',
      httpMethod: 'POST',
      routePath: '/customer-onboarding/:customerId/submit',
      executionOrder: 10,
      requiresIdempotencyKey: true,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      resultingStates: ['under_review'],
      outputContract: { lifecycleStatus: 'string', eligible: 'boolean', blockers: 'EligibilityBlocker[]', nextStep: 'string' },
      possibleErrors: ['422 ONBOARDING_INCOMPLETE', '422 ONBOARDING_ALREADY_SUBMITTED'],
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['customer_onboarding.submitted', 'customer.status_changed'],
      successCriteria: { statusCodes: [200], indicator: "lifecycleStatus = 'under_review'" },
      failureCriteria: { statusCodes: [422] },
    },
    {
      stepCode: 'onboarding.observations',
      name: 'Consultar las observaciones abiertas',
      description: 'Qué le están pidiendo al cliente, en su lenguaje. Es el camino de vuelta desde `observed`.',
      httpMethod: 'GET',
      routePath: '/customer-onboarding/:customerId/observations',
      executionOrder: 20,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['observed', 'under_review'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
  ],
};

const riskAssessment: WorkflowStageSeed = {
  stageCode: 'risk_assessment',
  name: 'Evaluación de riesgo',
  description: 'Calcula el score con la política vigente y deja la corrida explicable. Su recomendación es condición de la habilitación.',
  moduleCode: 'risk',
  actorType: 'system',
  displayOrder: 60,
  allowedRoles: ['customer', 'internal_operator', 'risk_analyst', 'system', 'admin', 'platform_admin'],
  requiredStates: ['onboarding_in_progress', 'under_review', 'observed', 'active'],
  completionRule: { type: 'no_blockers', blockerCodes: ['RISK_NOT_APPROVED', 'RISK_ASSESSMENT_STALE'] },
  steps: [
    {
      stepCode: 'risk.create_assessment',
      name: 'Ejecutar la evaluación de riesgo',
      description: 'Corre el ruleset activo y persiste corrida, reglas disparadas y contribuciones de cada variable.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/risk-assessments',
      executionOrder: 10,
      requiresIdempotencyKey: true,
      allowedRoles: ['customer', 'internal_operator', 'risk_analyst', 'system', 'admin', 'platform_admin'],
      outputContract: { riskAssessmentRunId: 'string', recommendedAction: 'string', modelCode: 'string', rulesetVersion: 'string' },
      possibleErrors: ['422 RISK_RULESET_NOT_ACTIVE'],
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['risk.assessment_completed'],
      successCriteria: { statusCodes: [201], indicator: "recommendedAction = 'approved_for_next_step'" },
    },
    {
      stepCode: 'risk.detail',
      name: 'Consultar la corrida de riesgo',
      description: 'Detalle de la corrida para operaciones.',
      httpMethod: 'GET',
      routePath: '/operations/risk-assessments/:riskAssessmentRunId',
      executionOrder: 20,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'risk.explanation',
      name: 'Consultar la explicación del score',
      description: 'Reglas disparadas y contribución de cada variable. Es lo que hace defendible una decisión adversa.',
      httpMethod: 'GET',
      routePath: '/operations/risk-assessments/:riskAssessmentRunId/explanation',
      executionOrder: 30,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
  ],
};

const backOfficeReview: WorkflowStageSeed = {
  stageCode: 'back_office_review',
  name: 'Revisión de operaciones',
  description:
    'Decisiones humanas sobre identidad, cumplimiento, observaciones y fraude. Sin señal automática de cierre: la resuelve un analista.',
  moduleCode: 'operations',
  actorType: 'internal_user',
  displayOrder: 70,
  allowedRoles: KYC_DECISION_ROLES,
  requiredStates: ['under_review', 'observed'],
  completionRule: { type: 'manual' },
  steps: [
    {
      stepCode: 'ops.work_queue',
      name: 'Consultar la cola de trabajo',
      description: 'Casos pendientes de intervención humana, priorizados.',
      httpMethod: 'GET',
      routePath: '/operations/work-queue',
      executionOrder: 10,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: KYC_DECISION_ROLES,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'ops.investigation_summary',
      name: 'Consultar el resumen de investigación del cliente',
      description: 'Vista consolidada de identidad, riesgo, dispositivos y casos abiertos del cliente.',
      httpMethod: 'GET',
      routePath: '/operations/customers/:customerId/investigation-summary',
      executionOrder: 20,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: KYC_DECISION_ROLES,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
  ],
  subStages: [
    {
      stageCode: 'identity_decision',
      name: 'Decisión de identidad',
      description: 'Un analista acepta o rechaza la verificación de identidad y su evidencia.',
      moduleCode: 'operations',
      actorType: 'internal_user',
      displayOrder: 10,
      allowedRoles: KYC_DECISION_ROLES,
      requiredStates: ['under_review', 'observed'],
      completionRule: { type: 'no_blockers', blockerCodes: ['IDENTITY_NOT_VERIFIED', 'EVIDENCE_PENDING_REVIEW'] },
      steps: [
        {
          stepCode: 'ops.identity_decision',
          name: 'Decidir la verificación de identidad',
          description: 'Registra la decisión y su motivo; el resultado alimenta la regla de habilitación.',
          httpMethod: 'POST',
          routePath: '/operations/customers/:customerId/identity-verification/decision',
          executionOrder: 10,
          allowedRoles: KYC_DECISION_ROLES,
          requiredStates: ['under_review', 'observed'],
          possibleErrors: ['404 CUSTOMER_NOT_FOUND', '422 INVALID_DECISION'],
          retryStrategy: NO_RETRY,
          producesEvents: ['customer.identity_decision_recorded'],
          successCriteria: { statusCodes: [200] },
        },
      ],
    },
    {
      stageCode: 'compliance_screening',
      name: 'Cribado de cumplimiento',
      description: 'Contraste contra listas de vigilancia y resolución de coincidencias.',
      moduleCode: 'operations',
      actorType: 'internal_user',
      displayOrder: 20,
      allowedRoles: ['compliance_analyst', 'risk_analyst', 'admin', 'platform_admin', 'system'],
      requiredStates: ['under_review', 'observed'],
      completionRule: { type: 'no_blockers', blockerCodes: ['COMPLIANCE_MATCH_PENDING'] },
      steps: [
        {
          stepCode: 'ops.compliance_screening',
          name: 'Ejecutar el cribado',
          description: 'Genera coincidencias contra listas; cada coincidencia bloquea la habilitación hasta resolverse.',
          httpMethod: 'POST',
          routePath: '/operations/customers/:customerId/compliance/screening',
          executionOrder: 10,
          allowedRoles: ['compliance_analyst', 'risk_analyst', 'admin', 'platform_admin', 'system'],
          retryStrategy: NO_RETRY,
          producesEvents: ['compliance.screening_completed'],
          successCriteria: { statusCodes: [200, 201] },
        },
        {
          stepCode: 'ops.compliance_clear',
          name: 'Resolver las coincidencias',
          description: 'Un analista de cumplimiento descarta o confirma cada coincidencia, con motivo registrado.',
          httpMethod: 'POST',
          routePath: '/operations/customers/:customerId/compliance/clear-matches',
          executionOrder: 20,
          isMandatory: false,
          allowedRoles: ['compliance_analyst', 'admin', 'platform_admin'],
          retryStrategy: NO_RETRY,
          producesEvents: ['compliance.matches_cleared'],
          successCriteria: { statusCodes: [200] },
        },
      ],
    },
    {
      stageCode: 'manual_review',
      name: 'Revisión manual',
      description: 'Casos abiertos por reglas o por observaciones de calidad de datos.',
      moduleCode: 'operations',
      actorType: 'internal_user',
      displayOrder: 30,
      isOptional: true,
      allowedRoles: KYC_DECISION_ROLES,
      requiredStates: ['under_review', 'observed'],
      completionRule: { type: 'no_blockers', blockerCodes: ['OPEN_OBSERVATIONS'] },
      steps: [
        {
          stepCode: 'ops.manual_cases',
          name: 'Listar casos de revisión manual',
          description: 'Casos abiertos con su prioridad y motivo.',
          httpMethod: 'GET',
          routePath: '/operations/manual-review-cases',
          executionOrder: 10,
          isMandatory: false,
          isRepeatable: true,
          allowedRoles: KYC_DECISION_ROLES,
          retryStrategy: READ_RETRY,
          successCriteria: { statusCodes: [200] },
        },
        {
          stepCode: 'ops.manual_decision',
          name: 'Decidir un caso de revisión manual',
          description: 'Aprobar, rechazar o pedir más información. Pedir información deja al cliente en `observed`.',
          httpMethod: 'POST',
          routePath: '/operations/manual-review-cases/:caseId/decision',
          executionOrder: 20,
          requiresIdempotencyKey: true,
          allowedRoles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          resultingStates: ['observed', 'under_review'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['manual_review.case_decided'],
          successCriteria: { statusCodes: [200] },
        },
      ],
    },
    {
      stageCode: 'fraud_review',
      name: 'Revisión de fraude',
      description: 'Casos de fraude abiertos. Un caso abierto bloquea la habilitación mientras dure.',
      moduleCode: 'operations',
      actorType: 'internal_user',
      displayOrder: 40,
      isOptional: true,
      allowedRoles: ['fraud_analyst', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
      requiredStates: ['under_review', 'observed', 'active'],
      completionRule: { type: 'no_blockers', blockerCodes: ['FRAUD_CASE_OPEN'] },
      steps: [
        {
          stepCode: 'ops.fraud_cases',
          name: 'Listar casos de fraude',
          description: 'Casos de fraude con su estado y prioridad.',
          httpMethod: 'GET',
          routePath: '/operations/fraud-cases',
          executionOrder: 10,
          isMandatory: false,
          isRepeatable: true,
          allowedRoles: ['fraud_analyst', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          retryStrategy: READ_RETRY,
          successCriteria: { statusCodes: [200] },
        },
        {
          stepCode: 'ops.fraud_decision',
          name: 'Decidir un caso de fraude',
          description: 'Confirma o descarta el fraude; confirmar bloquea al cliente.',
          httpMethod: 'POST',
          routePath: '/operations/fraud-cases/:caseId/decision',
          executionOrder: 20,
          isMandatory: false,
          requiresIdempotencyKey: true,
          allowedRoles: ['fraud_analyst', 'admin', 'platform_admin'],
          resultingStates: ['blocked', 'under_review'],
          retryStrategy: IDEMPOTENT_RETRY,
          producesEvents: ['fraud.case_decided'],
          successCriteria: { statusCodes: [200] },
        },
      ],
    },
  ],
};

const eligibility: WorkflowStageSeed = {
  stageCode: 'eligibility',
  name: 'Habilitación crediticia',
  description:
    'Única puerta de entrada al crédito. Evalúa la regla vigente, deja evidencia y promueve a `active` cuando lo único que faltaba era el estado.',
  moduleCode: 'customers',
  actorType: 'system',
  displayOrder: 80,
  allowedRoles: CUSTOMER_AND_INTERNAL_FULL,
  requiredStates: ['under_review', 'observed', 'active', 'suspended'],
  resultingStates: ['active'],
  completionRule: { type: 'lifecycle_status', statuses: ['active'] },
  steps: [
    {
      stepCode: 'eligibility.get',
      name: 'Evaluar y consultar la habilitación',
      description:
        'Calcula la regla, persiste la evaluación como evidencia con su versión y devuelve bloqueadores, secciones y siguiente paso.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/eligibility',
      executionOrder: 10,
      isRepeatable: true,
      allowedRoles: CUSTOMER_AND_INTERNAL_FULL,
      requiredStates: ['registered', 'onboarding_in_progress', 'under_review', 'observed', 'active', 'suspended'],
      resultingStates: ['active'],
      outputContract: {
        eligible: 'boolean',
        blockers: 'EligibilityBlocker[]',
        sections: 'OnboardingSection[]',
        completionPercentage: 'number',
        nextStep: 'string',
        ruleVersion: 'string',
      },
      possibleErrors: ['403 FORBIDDEN_OTHER_CUSTOMER', '404 CUSTOMER_NOT_FOUND'],
      retryStrategy: READ_RETRY,
      producesEvents: ['customer.eligibility_evaluated'],
      successCriteria: { statusCodes: [200], indicator: 'eligible = true' },
    },
    {
      stepCode: 'ops.eligibility_decision',
      name: 'Decidir la habilitación (operaciones)',
      description: 'Aprueba, rechaza, observa, suspende o reincorpora. Aprobar con bloqueadores se registra como excepción autorizada.',
      httpMethod: 'POST',
      routePath: '/operations/customers/:customerId/eligibility/decision',
      executionOrder: 20,
      isMandatory: false,
      allowedRoles: KYC_DECISION_ROLES,
      requiredStates: ['under_review', 'observed', 'active', 'suspended', 'rejected', 'blocked'],
      resultingStates: ['active', 'observed', 'rejected', 'suspended', 'under_review'],
      possibleErrors: ['422 INVALID_STATUS_TRANSITION', '404 CUSTOMER_NOT_FOUND'],
      retryStrategy: NO_RETRY,
      producesEvents: ['customer.status_changed', 'customer.eligibility_decided'],
      successCriteria: { statusCodes: [200] },
      failureCriteria: { statusCodes: [422] },
    },
    {
      stepCode: 'customer.me',
      name: 'Consultar el resumen del cliente',
      description: 'Perfil, contactos, onboarding y elegibilidad en una sola lectura para la pantalla principal de la app.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/me',
      executionOrder: 30,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
  ],
};

const creditCatalog: WorkflowStageSeed = {
  stageCode: 'credit_catalog',
  name: 'Catálogo de productos crediticios',
  description:
    'Prerrequisito operativo del crédito: sin al menos un producto activo, ningún cliente habilitado puede solicitar nada. El catálogo es dato de negocio, no código.',
  moduleCode: 'credit',
  actorType: 'internal_user',
  displayOrder: 5,
  isOptional: true,
  allowedRoles: CREDIT_OPS_ROLES,
  requiredStates: [],
  completionRule: { type: 'manual' },
  steps: [
    {
      stepCode: 'ops.credit_products_list',
      name: 'Listar los productos del tenant',
      description: 'Catálogo completo para administración, incluidos borradores y retirados.',
      httpMethod: 'GET',
      routePath: '/operations/credit/products',
      executionOrder: 10,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: CREDIT_OPS_ROLES,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'ops.credit_product_create',
      name: 'Crear un producto crediticio',
      description: 'Nace en `draft`: activarlo es una decisión aparte y auditable.',
      httpMethod: 'POST',
      routePath: '/operations/credit/products',
      executionOrder: 20,
      isMandatory: false,
      allowedRoles: CREDIT_OPS_ROLES,
      possibleErrors: ['409 CREDIT_PRODUCT_CODE_ALREADY_EXISTS', '422 INVALID_PRODUCT_RANGES'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [201] },
    },
    {
      stepCode: 'ops.credit_product_status',
      name: 'Cambiar el estado de un producto',
      description: 'Activar, suspender o retirar. Solo los activos son ofrecibles.',
      httpMethod: 'PATCH',
      routePath: '/operations/credit/products/:productId/status',
      executionOrder: 30,
      isMandatory: false,
      allowedRoles: CREDIT_OPS_ROLES,
      possibleErrors: ['404 CREDIT_PRODUCT_NOT_FOUND', '422 INVALID_PRODUCT_STATUS_TRANSITION'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    },
  ],
};

const creditApplication: WorkflowStageSeed = {
  stageCode: 'credit_application',
  name: 'Solicitud de crédito',
  description: 'El cliente habilitado elige producto, monto y plazo. El servidor reevalúa la elegibilidad antes de escribir nada.',
  moduleCode: 'credit',
  actorType: 'customer',
  displayOrder: 90,
  allowedRoles: CUSTOMER_AND_INTERNAL,
  requiredStates: ['active'],
  completionRule: { type: 'manual' },
  steps: [
    {
      stepCode: 'credit.list_products',
      name: 'Listar los productos disponibles para el cliente',
      description: '`canApply` refleja la elegibilidad real, de modo que el catálogo y la puerta de entrada no puedan discrepar.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/credit-products',
      executionOrder: 10,
      isRepeatable: true,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['active'],
      outputContract: { products: 'CreditProductDto[]', canApply: 'boolean', blockers: 'EligibilityBlocker[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'credit.create_application',
      name: 'Crear la solicitud de crédito',
      description:
        'Revalida elegibilidad, rangos de monto y plazo, y congela el snapshot de la evaluación que la autorizó. Un cliente no puede tener dos solicitudes vivas.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/credit-applications',
      executionOrder: 20,
      requiresIdempotencyKey: true,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      requiredStates: ['active'],
      inputContract: { creditProductId: 'string', requestedAmount: 'number', requestedTermMonths: 'number', purposeCode: 'string?' },
      outputContract: { applicationCode: 'string', status: 'submitted' },
      possibleErrors: [
        '404 CREDIT_PRODUCT_NOT_FOUND',
        '409 CREDIT_APPLICATION_ALREADY_OPEN',
        '422 CUSTOMER_NOT_ELIGIBLE',
        '422 REQUESTED_AMOUNT_OUT_OF_RANGE',
        '422 REQUESTED_TERM_OUT_OF_RANGE',
      ],
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['credit.application_submitted'],
      successCriteria: { statusCodes: [201] },
      failureCriteria: { statusCodes: [409, 422] },
    },
    {
      stepCode: 'credit.list_applications',
      name: 'Listar las solicitudes del cliente',
      description: 'Historial de solicitudes, más recientes primero.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/credit-applications',
      executionOrder: 30,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: CUSTOMER_AND_INTERNAL,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
  ],
};

const creditDecision: WorkflowStageSeed = {
  stageCode: 'credit_decision',
  name: 'Decisión de crédito',
  description: 'Cierre del recorrido: operaciones aprueba o rechaza la solicitud y el evento queda en el historial inmutable.',
  moduleCode: 'operations',
  actorType: 'internal_user',
  displayOrder: 100,
  isTerminalStage: true,
  allowedRoles: CREDIT_OPS_ROLES,
  requiredStates: ['active'],
  completionRule: { type: 'manual' },
  steps: [
    {
      stepCode: 'ops.credit_application_detail',
      name: 'Consultar la solicitud',
      description: 'Detalle con la evidencia de elegibilidad congelada al momento de solicitar.',
      httpMethod: 'GET',
      routePath: '/operations/credit/applications/:applicationId',
      executionOrder: 10,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: CREDIT_OPS_ROLES,
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    },
    {
      stepCode: 'ops.credit_decision',
      name: 'Decidir la solicitud',
      description: 'Aprueba o rechaza con motivo. Genera el evento de la solicitud y cierra el recorrido.',
      httpMethod: 'POST',
      routePath: '/operations/credit/applications/:applicationId/decision',
      executionOrder: 20,
      isFlowExit: true,
      allowedRoles: CREDIT_OPS_ROLES,
      possibleErrors: ['404 CREDIT_APPLICATION_NOT_FOUND', '422 INVALID_APPLICATION_STATUS_TRANSITION'],
      retryStrategy: NO_RETRY,
      producesEvents: ['credit.application_decided'],
      successCriteria: { statusCodes: [200], indicator: "status = 'approved' | 'rejected'" },
      failureCriteria: { statusCodes: [422] },
    },
  ],
};

export const CUSTOMER_CREDIT_WORKFLOW: WorkflowSeed = {
  workflowCode: 'customer_credit_journey',
  version: 'v1',
  name: 'Recorrido estándar del cliente hasta la decisión de crédito',
  description:
    'Árbol real de endpoints del proceso de Atlas: registro, captura KYC, evidencia externa, envío a revisión, evaluación de riesgo, ' +
    'decisiones de operaciones, habilitación crediticia, solicitud y decisión final. Cada paso corresponde a un endpoint implementado.',
  processType: 'customer_journey',
  ownerDomain: 'customer_lifecycle',
  status: 'active',
  isDefault: true,
  entryStageCode: 'registration',
  terminalStageCodes: ['credit_decision'],
  successCriteria: {
    indicator: "credit_applications.status = 'approved'",
    description: 'El recorrido termina bien cuando una solicitud del cliente queda aprobada.',
  },
  failureCriteria: {
    indicator: "customers.lifecycle_status IN ('rejected','blocked','closed') OR credit_applications.status = 'rejected'",
    description: 'Rechazo de habilitación, bloqueo por fraude/cumplimiento o rechazo de la solicitud.',
  },
  metadata: {
    lifecycleStatuses: [...CUSTOMER_LIFECYCLE_STATUSES],
    eligibilityRuleVersion: 'eligibility-v1',
    documentation: 'docs/endpoints/workflow-catalog.md',
  },
  stages: [
    creditCatalog,
    registration,
    sessionBootstrap,
    dataCapture,
    externalEvidence,
    submission,
    riskAssessment,
    backOfficeReview,
    eligibility,
    creditApplication,
    creditDecision,
  ],
  dependencies: [
    {
      stepCode: 'registration.login',
      dependsOnStepCode: 'registration.start',
      dependencyType: 'requires_completion',
      description: 'No hay credenciales que autenticar antes de crear el cliente.',
    },
    {
      stepCode: 'contact.request_code',
      dependsOnStepCode: 'contact.add_method',
      dependencyType: 'requires_completion',
      description: 'El código se envía al método de contacto registrado.',
    },
    {
      stepCode: 'contact.submit_code',
      dependsOnStepCode: 'contact.request_code',
      dependencyType: 'requires_completion',
      description: 'Sin código emitido no hay nada que validar.',
    },
    {
      stepCode: 'identity.package',
      dependsOnStepCode: 'identity.upload_url',
      dependencyType: 'requires_data',
      description: 'El registro del documento referencia el objeto cargado con la URL firmada.',
    },
    {
      stepCode: 'identity.verification',
      dependsOnStepCode: 'identity.package',
      dependencyType: 'requires_completion',
      description: 'La verificación contrasta el documento ya registrado.',
    },
    {
      stepCode: 'onboarding.submit',
      dependsOnStepCode: 'contact.submit_code',
      dependencyType: 'requires_completion',
      description: 'Sección `contact_verification` obligatoria para enviar el paquete.',
    },
    {
      stepCode: 'onboarding.submit',
      dependsOnStepCode: 'profile.update',
      dependencyType: 'requires_completion',
      description: 'Sección `personal_data` obligatoria para enviar el paquete.',
    },
    {
      stepCode: 'onboarding.submit',
      dependsOnStepCode: 'financial.update',
      dependencyType: 'requires_completion',
      description: 'Sección `financial_profile` obligatoria para enviar el paquete.',
    },
    {
      stepCode: 'onboarding.submit',
      dependsOnStepCode: 'address.package',
      dependencyType: 'requires_completion',
      description: 'Sección `address` obligatoria para enviar el paquete.',
    },
    {
      stepCode: 'onboarding.submit',
      dependsOnStepCode: 'identity.package',
      dependencyType: 'requires_completion',
      description: 'Sección `identity_documents` obligatoria para enviar el paquete.',
    },
    {
      stepCode: 'onboarding.submit',
      dependsOnStepCode: 'references.add',
      dependencyType: 'requires_completion',
      description: 'Sección `reference_contacts` obligatoria para enviar el paquete.',
    },
    {
      stepCode: 'onboarding.submit',
      dependsOnStepCode: 'consents.decisions',
      dependencyType: 'requires_completion',
      description: 'Los consentimientos requeridos bloquean la habilitación mientras falten.',
    },
    {
      stepCode: 'risk.create_assessment',
      dependsOnStepCode: 'onboarding.submit',
      dependencyType: 'requires_data',
      description: 'La evaluación de riesgo se apoya en el paquete completo enviado a revisión.',
    },
    {
      stepCode: 'eligibility.get',
      dependsOnStepCode: 'risk.create_assessment',
      dependencyType: 'requires_data',
      description: 'Sin una corrida de riesgo favorable y vigente, la habilitación queda bloqueada.',
    },
    {
      stepCode: 'credit.create_application',
      dependsOnStepCode: 'eligibility.get',
      dependencyType: 'requires_completion',
      description: 'Solo un cliente habilitado puede abrir una solicitud.',
    },
    {
      stepCode: 'credit.create_application',
      dependsOnStepCode: 'credit.list_products',
      dependencyType: 'requires_data',
      description: 'La solicitud referencia un producto vigente del catálogo.',
    },
    {
      stepCode: 'credit.create_application',
      dependsOnStepCode: 'ops.credit_product_status',
      dependencyType: 'soft',
      description: 'Sin al menos un producto activo no hay nada que solicitar.',
    },
    {
      stepCode: 'ops.credit_decision',
      dependsOnStepCode: 'credit.create_application',
      dependencyType: 'requires_completion',
      description: 'No hay decisión sin solicitud.',
    },
  ],
  transitions: [
    {
      transitionCode: 'entry.start',
      fromStepCode: null,
      toStepCode: 'registration.start',
      conditionType: 'always',
      description: 'Entrada del flujo: el recorrido empieza registrando al cliente.',
      displayOrder: 10,
      isDefaultPath: true,
    },
    {
      transitionCode: 'start.to_login',
      fromStepCode: 'registration.start',
      toStepCode: 'registration.login',
      conditionType: 'on_success',
      description: 'Con el cliente creado se obtiene el token de acceso.',
      displayOrder: 20,
      isDefaultPath: true,
    },
    {
      transitionCode: 'login.to_mfa',
      fromStepCode: 'registration.login',
      toStepCode: 'registration.mfa',
      conditionType: 'conditional',
      conditionExpression: { field: 'mfaRequired', equals: true },
      description: 'Solo si el login exigió segundo factor.',
      displayOrder: 30,
    },
    {
      transitionCode: 'start.to_login_pin',
      fromStepCode: 'registration.start',
      toStepCode: 'registration.login_pin',
      conditionType: 'conditional',
      conditionExpression: { customerHasPin: true },
      description: 'Camino alternativo de acceso para clientes con PIN configurado.',
      displayOrder: 25,
    },
    {
      transitionCode: 'login_pin.to_contact_method',
      fromStepCode: 'registration.login_pin',
      toStepCode: 'contact.add_method',
      conditionType: 'on_success',
      description: 'Autenticado por PIN, el recorrido continúa igual que con contraseña.',
      displayOrder: 45,
    },
    {
      transitionCode: 'login.to_contact_method',
      fromStepCode: 'registration.login',
      toStepCode: 'contact.add_method',
      conditionType: 'on_success',
      description: 'Autenticado, el cliente empieza la captura de datos por la verificación de contacto.',
      displayOrder: 40,
      isDefaultPath: true,
    },
    {
      transitionCode: 'contact_method.to_request',
      fromStepCode: 'contact.add_method',
      toStepCode: 'contact.request_code',
      conditionType: 'on_success',
      description: 'Registrado el método, se pide el código.',
      displayOrder: 50,
      isDefaultPath: true,
    },
    {
      transitionCode: 'request.to_submit',
      fromStepCode: 'contact.request_code',
      toStepCode: 'contact.submit_code',
      conditionType: 'on_success',
      description: 'Emitido el código, el cliente lo envía.',
      displayOrder: 60,
      isDefaultPath: true,
    },
    {
      transitionCode: 'submit_code.to_profile',
      fromStepCode: 'contact.submit_code',
      toStepCode: 'profile.update',
      conditionType: 'on_success',
      description: 'Contacto verificado: sigue el perfil personal.',
      displayOrder: 70,
      isDefaultPath: true,
    },
    {
      transitionCode: 'profile.to_financial',
      fromStepCode: 'profile.update',
      toStepCode: 'financial.update',
      conditionType: 'on_success',
      description: 'Perfil guardado: sigue el perfil económico.',
      displayOrder: 80,
      isDefaultPath: true,
    },
    {
      transitionCode: 'financial.to_address',
      fromStepCode: 'financial.update',
      toStepCode: 'address.package',
      conditionType: 'on_success',
      description: 'Perfil económico guardado: sigue el domicilio.',
      displayOrder: 90,
      isDefaultPath: true,
    },
    {
      transitionCode: 'address.to_identity_upload',
      fromStepCode: 'address.package',
      toStepCode: 'identity.upload_url',
      conditionType: 'on_success',
      description: 'Domicilio registrado: sigue la carga del documento de identidad.',
      displayOrder: 100,
      isDefaultPath: true,
    },
    {
      transitionCode: 'identity_upload.to_identity_package',
      fromStepCode: 'identity.upload_url',
      toStepCode: 'identity.package',
      conditionType: 'on_success',
      description: 'Con el archivo cargado se registra el documento.',
      displayOrder: 110,
      isDefaultPath: true,
    },
    {
      transitionCode: 'identity_package.to_verification',
      fromStepCode: 'identity.package',
      toStepCode: 'identity.verification',
      conditionType: 'on_success',
      description: 'Documento registrado: se verifica contra el proveedor.',
      displayOrder: 120,
      isDefaultPath: true,
    },
    {
      transitionCode: 'identity_verification.to_references',
      fromStepCode: 'identity.verification',
      toStepCode: 'references.add',
      conditionType: 'on_success',
      description: 'Identidad verificada: siguen las referencias personales.',
      displayOrder: 130,
      isDefaultPath: true,
    },
    {
      transitionCode: 'identity_verification.to_external_request',
      fromStepCode: 'identity.verification',
      toStepCode: 'external.request',
      conditionType: 'on_error',
      conditionExpression: { errorCodes: ['IDENTITY_VERIFICATION_FAILED', 'PROVIDER_UNAVAILABLE'] },
      description: 'Si el proveedor de identidad falla, se recurre a evidencia externa complementaria.',
      displayOrder: 140,
    },
    {
      transitionCode: 'references.to_consents',
      fromStepCode: 'references.add',
      toStepCode: 'consents.decisions',
      conditionType: 'on_success',
      description: 'Referencias cargadas: quedan los consentimientos.',
      displayOrder: 150,
      isDefaultPath: true,
    },
    {
      transitionCode: 'consents.to_submit',
      fromStepCode: 'consents.decisions',
      toStepCode: 'onboarding.submit',
      conditionType: 'on_success',
      description: 'Paquete completo: se envía a revisión.',
      displayOrder: 160,
      isDefaultPath: true,
    },
    {
      transitionCode: 'submit.to_risk',
      fromStepCode: 'onboarding.submit',
      toStepCode: 'risk.create_assessment',
      conditionType: 'on_state',
      conditionExpression: { lifecycleStatus: 'under_review' },
      description: 'En revisión: se ejecuta la evaluación de riesgo.',
      displayOrder: 170,
      isDefaultPath: true,
    },
    {
      transitionCode: 'submit.to_observations',
      fromStepCode: 'onboarding.submit',
      toStepCode: 'onboarding.observations',
      conditionType: 'on_error',
      conditionExpression: { errorCodes: ['ONBOARDING_INCOMPLETE'] },
      description: 'Paquete incompleto: el cliente consulta qué le falta y vuelve a la captura.',
      displayOrder: 180,
    },
    {
      transitionCode: 'risk.to_identity_decision',
      fromStepCode: 'risk.create_assessment',
      toStepCode: 'ops.identity_decision',
      conditionType: 'on_success',
      description: 'Con el riesgo evaluado, operaciones decide sobre la identidad.',
      displayOrder: 190,
      isDefaultPath: true,
    },
    {
      transitionCode: 'identity_decision.to_screening',
      fromStepCode: 'ops.identity_decision',
      toStepCode: 'ops.compliance_screening',
      conditionType: 'on_success',
      description: 'Identidad resuelta: se ejecuta el cribado de cumplimiento.',
      displayOrder: 200,
      isDefaultPath: true,
    },
    {
      transitionCode: 'screening.to_clear',
      fromStepCode: 'ops.compliance_screening',
      toStepCode: 'ops.compliance_clear',
      conditionType: 'conditional',
      conditionExpression: { blockerCodes: ['COMPLIANCE_MATCH_PENDING'] },
      description: 'Si hubo coincidencias, hay que resolverlas antes de continuar.',
      displayOrder: 210,
    },
    {
      transitionCode: 'screening.to_eligibility',
      fromStepCode: 'ops.compliance_screening',
      toStepCode: 'eligibility.get',
      conditionType: 'on_success',
      description: 'Sin coincidencias pendientes: se evalúa la habilitación.',
      displayOrder: 220,
      isDefaultPath: true,
    },
    {
      transitionCode: 'clear.to_eligibility',
      fromStepCode: 'ops.compliance_clear',
      toStepCode: 'eligibility.get',
      conditionType: 'on_success',
      description: 'Resueltas las coincidencias, se evalúa la habilitación.',
      displayOrder: 230,
    },
    {
      transitionCode: 'manual_decision.to_observations',
      fromStepCode: 'ops.manual_decision',
      toStepCode: 'onboarding.observations',
      conditionType: 'on_state',
      conditionExpression: { lifecycleStatus: 'observed' },
      description: 'Si el analista pide más información, el cliente vuelve al circuito de observaciones.',
      displayOrder: 240,
    },
    {
      transitionCode: 'fraud_decision.to_eligibility',
      fromStepCode: 'ops.fraud_decision',
      toStepCode: 'eligibility.get',
      conditionType: 'on_state',
      conditionExpression: { lifecycleStatus: 'under_review' },
      description: 'Descartado el fraude, el cliente vuelve a evaluarse.',
      displayOrder: 250,
    },
    {
      transitionCode: 'eligibility.to_products',
      fromStepCode: 'eligibility.get',
      toStepCode: 'credit.list_products',
      conditionType: 'on_state',
      conditionExpression: { lifecycleStatus: 'active', eligible: true },
      description: 'Cliente habilitado: puede ver los productos que puede solicitar.',
      displayOrder: 260,
      isDefaultPath: true,
    },
    {
      transitionCode: 'eligibility.to_decision',
      fromStepCode: 'eligibility.get',
      toStepCode: 'ops.eligibility_decision',
      conditionType: 'conditional',
      conditionExpression: { eligible: false },
      description: 'Con bloqueadores vigentes, la habilitación pasa por una decisión humana.',
      displayOrder: 270,
    },
    {
      transitionCode: 'eligibility_decision.to_eligibility',
      fromStepCode: 'ops.eligibility_decision',
      toStepCode: 'eligibility.get',
      conditionType: 'on_success',
      description: 'Aplicada la decisión, se reevalúa para dejar la evidencia actualizada.',
      displayOrder: 280,
    },
    {
      transitionCode: 'products.to_application',
      fromStepCode: 'credit.list_products',
      toStepCode: 'credit.create_application',
      conditionType: 'on_success',
      description: 'Elegido el producto, se crea la solicitud.',
      displayOrder: 290,
      isDefaultPath: true,
    },
    {
      transitionCode: 'application.to_decision',
      fromStepCode: 'credit.create_application',
      toStepCode: 'ops.credit_decision',
      conditionType: 'on_success',
      description: 'La solicitud entra en la cola de decisión de operaciones.',
      displayOrder: 300,
      isDefaultPath: true,
    },
    {
      transitionCode: 'exit.decision',
      fromStepCode: 'ops.credit_decision',
      toStepCode: null,
      conditionType: 'always',
      description: 'Salida del flujo: la solicitud queda aprobada o rechazada.',
      displayOrder: 310,
      isDefaultPath: true,
    },
  ],
};
