/**
 * Recorrido REAL desde que el usuario queda logueado hasta que la primera pantalla está pintada.
 *
 * Es el tramo que suele estar sin documentar y es el que más llamadas encadena: abrir sesión,
 * resolver quién es, decidir si va a la pantalla principal o a terminar su onboarding, y traer los
 * datos que esa pantalla muestra. Cada `routePath` existe hoy en `src/modules/`; el informe de
 * consistencia marca como error cualquiera que no exista.
 */

import type { WorkflowSeed, WorkflowStageSeed, WorkflowStepSeed } from './customer-credit-workflow.seed-data.js';

const CUSTOMER_ROLES = ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'];
const SESSION_ROLES = [
  'customer',
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'fraud_analyst',
  'admin',
  'platform_admin',
  'system',
];

const READ_RETRY = { strategy: 'safe_retry', maxAttempts: 3, backoff: 'exponential' };
const IDEMPOTENT_RETRY = { strategy: 'client_retry_with_idempotency_key', maxAttempts: 3, backoff: 'exponential' };
const NO_RETRY = { strategy: 'no_retry', reason: 'Comando no idempotente: reintentar puede duplicar el efecto.' };

function step(seed: WorkflowStepSeed): WorkflowStepSeed {
  return seed;
}

const sessionBootstrap: WorkflowStageSeed = {
  stageCode: 'first_screen_session',
  name: 'Apertura de sesión',
  description: 'Abre la sesión de negocio (distinta del token): es la que sostiene la trazabilidad de todo lo que el usuario haga.',
  moduleCode: 'sessions',
  actorType: 'customer',
  displayOrder: 10,
  isEntryStage: true,
  allowedRoles: SESSION_ROLES,
  completionRule: { type: 'manual' },
  steps: [
    step({
      stepCode: 'first_screen.session_start',
      name: 'Abrir la sesión',
      description: 'Registra dispositivo, canal y contexto. Devuelve el sessionId que acompaña al resto de llamadas.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/sessions/start',
      executionOrder: 10,
      isFlowEntry: true,
      requiresIdempotencyKey: true,
      allowedRoles: SESSION_ROLES,
      inputContract: { deviceId: 'string', channel: 'mobile_app | web', appVersion: 'string' },
      outputContract: { sessionId: 'string', startedAt: 'ISO-8601' },
      possibleErrors: ['401 TOKEN_EXPIRED', '409 SESSION_ALREADY_OPEN'],
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['session.started'],
      successCriteria: { statusCodes: [200, 201] },
    }),
    step({
      stepCode: 'first_screen.session_state',
      name: 'Consultar el estado de la sesión',
      description: 'Confirma que la sesión sigue viva y trae el contexto que la pantalla necesita para decidir qué mostrar.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/session-state',
      executionOrder: 20,
      allowedRoles: SESSION_ROLES,
      outputContract: { sessionId: 'string', status: 'active | expired', lastSeenAt: 'ISO-8601' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.session_heartbeat',
      name: 'Mantener viva la sesión',
      description: 'Latido periódico mientras la pantalla está abierta. Sin él, la sesión caduca y el trabajo se pierde.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/sessions/:sessionId/heartbeat',
      executionOrder: 30,
      isMandatory: false,
      isRepeatable: true,
      allowedRoles: SESSION_ROLES,
      possibleErrors: ['404 SESSION_NOT_FOUND', '410 SESSION_EXPIRED'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200, 204] },
    }),
  ],
};

const identityContext: WorkflowStageSeed = {
  stageCode: 'first_screen_identity',
  name: 'Identidad y perfil',
  description: 'Quién es el usuario y qué puede hacer. Determina el saludo, el menú y los permisos de la pantalla.',
  moduleCode: 'customers',
  actorType: 'customer',
  displayOrder: 20,
  completionRule: { type: 'manual' },
  steps: [
    step({
      stepCode: 'first_screen.auth_me',
      name: 'Confirmar el actor autenticado',
      description: 'Rol, tenant y customerId del token. Es lo que decide qué app se pinta.',
      httpMethod: 'GET',
      routePath: '/auth/me',
      executionOrder: 10,
      allowedRoles: [],
      outputContract: { sub: 'string', role: 'string', tenantId: 'string', customerId: 'string' },
      possibleErrors: ['401 TOKEN_EXPIRED'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.customer_me',
      name: 'Traer el perfil del cliente',
      description: 'Nombre, estado del ciclo de vida y datos de cabecera que la pantalla muestra.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/me',
      executionOrder: 20,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { customerId: 'string', fullName: 'string', lifecycleStatus: 'string' },
      possibleErrors: ['403 CUSTOMER_ACCESS_DENIED', '404 CUSTOMER_NOT_FOUND'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.token_refresh',
      name: 'Renovar el token de acceso',
      description: 'Rama de excepción: si el token venció durante el arranque, se renueva y se reintenta sin echar al usuario.',
      httpMethod: 'POST',
      routePath: '/auth/refresh',
      executionOrder: 30,
      isMandatory: false,
      requiresAuth: false,
      allowedRoles: [],
      inputContract: { refreshToken: 'string' },
      possibleErrors: ['401 REFRESH_TOKEN_INVALID'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
  ],
};

const onboardingGate: WorkflowStageSeed = {
  stageCode: 'first_screen_gate',
  name: 'Compuerta de onboarding',
  description: 'La bifurcación que decide la primera pantalla: expediente completo va a inicio; incompleto va a terminar el alta.',
  moduleCode: 'customer_onboarding',
  actorType: 'system',
  displayOrder: 30,
  completionRule: { type: 'lifecycle_status', statuses: ['active', 'under_review'] },
  steps: [
    step({
      stepCode: 'first_screen.onboarding_status',
      name: 'Consultar el avance del onboarding',
      description: 'Secciones completas, porcentaje y próximo paso. Es la fuente de la decisión, no una heurística del cliente.',
      httpMethod: 'GET',
      routePath: '/customer-onboarding/:customerId/status',
      executionOrder: 10,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { status: 'string', completionPercentage: 'number', nextStep: 'string', sections: 'SectionStatus[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.observations',
      name: 'Consultar las observaciones abiertas',
      description: 'Si el back office devolvió el expediente, aquí está QUÉ hay que corregir: es lo que la pantalla debe mostrar primero.',
      httpMethod: 'GET',
      routePath: '/customer-onboarding/:customerId/observations',
      executionOrder: 20,
      isMandatory: false,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { observations: 'Observation[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.eligibility',
      name: 'Consultar la elegibilidad',
      description: 'Qué tiene habilitado el cliente y qué bloqueadores le quedan. Decide qué acciones se pintan activas.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/eligibility',
      executionOrder: 30,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { eligible: 'boolean', blockers: 'BlockerCode[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
  ],
};

const homeData: WorkflowStageSeed = {
  stageCode: 'first_screen_home',
  name: 'Datos de la primera pantalla',
  description: 'Lo que se pinta: productos disponibles, solicitudes en curso y avisos. Con esto la pantalla ya es útil.',
  moduleCode: 'credit',
  actorType: 'customer',
  displayOrder: 40,
  isTerminalStage: true,
  completionRule: { type: 'manual' },
  steps: [
    step({
      stepCode: 'first_screen.credit_products',
      name: 'Listar los productos disponibles',
      description: 'Catálogo vigente para ese cliente: es el cuerpo de la pantalla principal.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/credit-products',
      executionOrder: 10,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { products: 'CreditProductDto[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.credit_applications',
      name: 'Listar las solicitudes en curso',
      description: 'Si el cliente ya pidió algo, la pantalla muestra su estado en vez del catálogo vacío.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/credit-applications',
      executionOrder: 20,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { applications: 'CreditApplicationDto[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.unread_count',
      name: 'Contar las notificaciones sin leer',
      description: 'El punto rojo de la campana. Se pide siempre porque es barato y cambia a menudo.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/notifications/unread-count',
      executionOrder: 30,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { unreadCount: 'number' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.notifications',
      name: 'Listar las notificaciones',
      description: 'El detalle de los avisos, ya con la pantalla pintada.',
      httpMethod: 'GET',
      routePath: '/customers/:customerId/notifications',
      executionOrder: 40,
      isMandatory: false,
      allowedRoles: CUSTOMER_ROLES,
      outputContract: { items: 'NotificationDto[]', total: 'number' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'first_screen.device_token',
      name: 'Registrar el token de notificaciones push',
      description: 'Registra el dispositivo para avisos push. Opcional: sólo si el usuario dio permiso.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/device-tokens',
      executionOrder: 50,
      isMandatory: false,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { token: 'string', platform: 'ios | android' },
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200, 201] },
    }),
    step({
      stepCode: 'first_screen.telemetry',
      name: 'Enviar la telemetría de la pantalla',
      description: 'Cierra el recorrido: reporta que la pantalla se pintó y cuánto tardó.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/telemetry/batch',
      executionOrder: 60,
      isMandatory: false,
      isFlowExit: true,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { events: '[{ name, occurredAt, payload }]' },
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200, 202] },
    }),
  ],
};

export const POST_LOGIN_FIRST_SCREEN_WORKFLOW: WorkflowSeed = {
  workflowCode: 'post_login_first_screen',
  version: 'v1',
  name: 'De la sesión iniciada a la primera pantalla',
  description:
    'El arranque de la app, llamada por llamada: abrir sesión, resolver identidad y perfil, decidir por la compuerta de onboarding si va a inicio o a completar el alta, y traer los datos que la pantalla principal muestra.',
  processType: 'customer_journey',
  ownerDomain: 'sessions',
  status: 'active',
  isDefault: true,
  entryStageCode: 'first_screen_session',
  terminalStageCodes: ['first_screen_home'],
  successCriteria: { description: 'Sesión abierta, identidad resuelta y pantalla principal con sus datos.' },
  failureCriteria: { description: 'La sesión no abre, el token no renueva o el expediente incompleto desvía al onboarding.' },
  metadata: { audience: 'app_movil', maintainer: 'sessions' },
  stages: [sessionBootstrap, identityContext, onboardingGate, homeData],
  dependencies: [
    {
      stepCode: 'first_screen.session_state',
      dependsOnStepCode: 'first_screen.session_start',
      dependencyType: 'requires_data',
      description: 'Necesita el sessionId que devuelve la apertura.',
    },
    {
      stepCode: 'first_screen.session_heartbeat',
      dependsOnStepCode: 'first_screen.session_start',
      dependencyType: 'requires_data',
      description: 'El latido va contra un sessionId concreto.',
    },
    {
      stepCode: 'first_screen.customer_me',
      dependsOnStepCode: 'first_screen.auth_me',
      dependencyType: 'requires_data',
      description: 'El customerId sale del token resuelto.',
    },
    {
      stepCode: 'first_screen.onboarding_status',
      dependsOnStepCode: 'first_screen.customer_me',
      dependencyType: 'requires_data',
      description: 'Se consulta el avance del cliente identificado.',
    },
    {
      stepCode: 'first_screen.credit_products',
      dependsOnStepCode: 'first_screen.eligibility',
      dependencyType: 'requires_completion',
      description: 'El catálogo se filtra por lo que el cliente tiene habilitado.',
    },
    {
      stepCode: 'first_screen.telemetry',
      dependsOnStepCode: 'first_screen.credit_products',
      dependencyType: 'soft',
      description: 'Se reporta cuando la pantalla ya tiene contenido.',
    },
  ],
  transitions: [
    {
      transitionCode: 'first_screen.entry',
      fromStepCode: null,
      toStepCode: 'first_screen.session_start',
      conditionType: 'always',
      description: 'Entrada: con el token en la mano, la app abre su sesión de negocio.',
      displayOrder: 10,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.start_to_state',
      fromStepCode: 'first_screen.session_start',
      toStepCode: 'first_screen.session_state',
      conditionType: 'on_success',
      description: 'Abierta la sesión, se lee su estado.',
      displayOrder: 20,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.state_to_heartbeat',
      fromStepCode: 'first_screen.session_state',
      toStepCode: 'first_screen.session_heartbeat',
      conditionType: 'conditional',
      conditionExpression: { screenVisible: true },
      description: 'Mientras la pantalla esté abierta, se late.',
      displayOrder: 25,
    },
    {
      transitionCode: 'first_screen.state_to_me',
      fromStepCode: 'first_screen.session_state',
      toStepCode: 'first_screen.auth_me',
      conditionType: 'on_success',
      description: 'Sesión viva: se resuelve quién es el usuario.',
      displayOrder: 30,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.me_to_refresh',
      fromStepCode: 'first_screen.auth_me',
      toStepCode: 'first_screen.token_refresh',
      conditionType: 'on_error',
      description: 'Token vencido durante el arranque: se renueva en vez de echar al usuario.',
      displayOrder: 35,
    },
    {
      transitionCode: 'first_screen.refresh_to_me',
      fromStepCode: 'first_screen.token_refresh',
      toStepCode: 'first_screen.auth_me',
      conditionType: 'on_success',
      description: 'Renovado el token, se reintenta la identidad.',
      displayOrder: 36,
    },
    {
      transitionCode: 'first_screen.me_to_profile',
      fromStepCode: 'first_screen.auth_me',
      toStepCode: 'first_screen.customer_me',
      conditionType: 'on_success',
      description: 'Con el customerId se trae el perfil de cabecera.',
      displayOrder: 40,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.profile_to_status',
      fromStepCode: 'first_screen.customer_me',
      toStepCode: 'first_screen.onboarding_status',
      conditionType: 'on_success',
      description: 'Compuerta: se mira el avance del expediente.',
      displayOrder: 50,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.status_to_observations',
      fromStepCode: 'first_screen.onboarding_status',
      toStepCode: 'first_screen.observations',
      conditionType: 'on_state',
      conditionExpression: { lifecycleStatus: ['registered', 'in_progress', 'observed'] },
      description: 'Expediente incompleto o devuelto: la primera pantalla es la de corregir.',
      displayOrder: 60,
    },
    {
      transitionCode: 'first_screen.status_to_eligibility',
      fromStepCode: 'first_screen.onboarding_status',
      toStepCode: 'first_screen.eligibility',
      conditionType: 'on_state',
      conditionExpression: { lifecycleStatus: ['active', 'under_review'] },
      description: 'Expediente completo: se resuelve qué tiene habilitado.',
      displayOrder: 70,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.eligibility_to_products',
      fromStepCode: 'first_screen.eligibility',
      toStepCode: 'first_screen.credit_products',
      conditionType: 'on_success',
      description: 'Se pinta el catálogo filtrado por su elegibilidad.',
      displayOrder: 80,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.products_to_applications',
      fromStepCode: 'first_screen.credit_products',
      toStepCode: 'first_screen.credit_applications',
      conditionType: 'on_success',
      description: 'Y las solicitudes que ya tenga en curso.',
      displayOrder: 90,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.applications_to_unread',
      fromStepCode: 'first_screen.credit_applications',
      toStepCode: 'first_screen.unread_count',
      conditionType: 'on_success',
      description: 'El contador de la campana.',
      displayOrder: 100,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.unread_to_list',
      fromStepCode: 'first_screen.unread_count',
      toStepCode: 'first_screen.notifications',
      conditionType: 'conditional',
      conditionExpression: { unreadCount: '> 0' },
      description: 'Si hay avisos, se trae el detalle.',
      displayOrder: 110,
    },
    {
      transitionCode: 'first_screen.unread_to_device',
      fromStepCode: 'first_screen.unread_count',
      toStepCode: 'first_screen.device_token',
      conditionType: 'conditional',
      conditionExpression: { pushPermissionGranted: true },
      description: 'Si el usuario dio permiso, se registra el dispositivo para push.',
      displayOrder: 120,
    },
    {
      transitionCode: 'first_screen.to_telemetry',
      fromStepCode: 'first_screen.unread_count',
      toStepCode: 'first_screen.telemetry',
      conditionType: 'on_success',
      description: 'Pantalla pintada: se reporta la telemetría de arranque.',
      displayOrder: 130,
      isDefaultPath: true,
    },
    {
      transitionCode: 'first_screen.exit',
      fromStepCode: 'first_screen.telemetry',
      toStepCode: null,
      conditionType: 'always',
      description: 'Salida: el usuario ya está en la primera pantalla, operativa.',
      displayOrder: 140,
      isDefaultPath: true,
    },
  ],
};
