/**
 * Recorrido REAL de alta de cuenta: desde que el usuario abre la app por primera vez hasta que
 * queda con sesión iniciada. Responde la pregunta "¿qué endpoints toca un usuario para crearse una
 * cuenta y llegar a estar logueado?" sin que nadie tenga que leer seis controladores.
 *
 * Cada `routePath` corresponde a un endpoint montado hoy en `src/modules/`; el informe de
 * consistencia (`GET /operations/workflows/:code/consistency`) marca como error cualquiera que no
 * exista. Los endpoints de `auth` son `@Public()` salvo `provision-credentials` (admin) y `/auth/me`
 * (requiere token), y así se declaran aquí.
 */

import type { WorkflowSeed, WorkflowStageSeed, WorkflowStepSeed } from './customer-credit-workflow.seed-data.js';

const PUBLIC_ROLES: string[] = [];
const CUSTOMER_ROLES = ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'];
const ADMIN_ROLES = ['admin', 'platform_admin'];

const IDEMPOTENT_RETRY = { strategy: 'client_retry_with_idempotency_key', maxAttempts: 3, backoff: 'exponential' };
const READ_RETRY = { strategy: 'safe_retry', maxAttempts: 3, backoff: 'exponential' };
const NO_RETRY = { strategy: 'no_retry', reason: 'Comando no idempotente: reintentar puede duplicar el efecto.' };

function step(seed: WorkflowStepSeed): WorkflowStepSeed {
  return seed;
}

const legalPreview: WorkflowStageSeed = {
  stageCode: 'signup_legal_preview',
  name: 'Textos legales vigentes',
  description: 'La app muestra los términos y la política de privacidad ANTES de pedir un solo dato. Es público a propósito.',
  moduleCode: 'consents',
  actorType: 'customer',
  displayOrder: 10,
  isEntryStage: true,
  completionRule: { type: 'manual' },
  steps: [
    step({
      stepCode: 'signup.consent_documents',
      name: 'Consultar los documentos legales vigentes',
      description: 'Devuelve la versión publicada de cada documento. La versión que se muestre es la que después hay que aceptar.',
      httpMethod: 'GET',
      routePath: '/consent-documents/active',
      executionOrder: 10,
      requiresAuth: false,
      isFlowEntry: true,
      allowedRoles: PUBLIC_ROLES,
      outputContract: { documents: 'ConsentDocumentDto[]' },
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
  ],
};

const accountCreation: WorkflowStageSeed = {
  stageCode: 'signup_account_creation',
  name: 'Creación de la cuenta',
  description: 'Crea el cliente y su expediente de onboarding. A partir de aquí existe un customerId al que colgar todo lo demás.',
  moduleCode: 'customer_onboarding',
  actorType: 'customer',
  displayOrder: 20,
  resultingStates: ['registered'],
  completionRule: { type: 'no_blockers', blockerCodes: ['NO_CREDENTIALS'] },
  steps: [
    step({
      stepCode: 'signup.start',
      name: 'Iniciar el alta',
      description: 'Crea el cliente en estado registrado y abre su onboarding. Devuelve el customerId que usan todos los pasos siguientes.',
      httpMethod: 'POST',
      routePath: '/customer-onboarding/start',
      executionOrder: 10,
      requiresAuth: false,
      requiresIdempotencyKey: true,
      allowedRoles: PUBLIC_ROLES,
      resultingStates: ['registered'],
      inputContract: { channel: 'mobile_app | web', documentNumber: 'string', email: 'string', phone: 'string' },
      outputContract: { customerId: 'string', onboardingId: 'string', status: 'registered' },
      validationRules: ['Documento y correo con formato válido', 'No puede existir otro cliente activo con el mismo documento'],
      possibleErrors: ['409 CUSTOMER_ALREADY_EXISTS', '422 VALIDATION_ERROR'],
      retryStrategy: IDEMPOTENT_RETRY,
      producesEvents: ['customer.registered'],
      successCriteria: { statusCodes: [201] },
    }),
  ],
};

const credentialProvisioning: WorkflowStageSeed = {
  stageCode: 'signup_credentials',
  name: 'Provisión de credenciales',
  description: 'Alta de la credencial de acceso. No la ejecuta el cliente: es una operación de administración.',
  moduleCode: 'auth',
  actorType: 'internal_user',
  displayOrder: 30,
  isOptional: true,
  allowedRoles: ADMIN_ROLES,
  completionRule: { type: 'no_blockers', blockerCodes: ['NO_CREDENTIALS'] },
  steps: [
    step({
      stepCode: 'signup.provision_credentials',
      name: 'Provisionar credenciales de acceso',
      description: 'Crea o repone la credencial del cliente. Requiere un token de administración: no es un endpoint de la app.',
      httpMethod: 'POST',
      routePath: '/auth/provision-credentials',
      executionOrder: 10,
      isMandatory: false,
      allowedRoles: ADMIN_ROLES,
      inputContract: { customerId: 'string', password: 'string (temporal)' },
      outputContract: { provisioned: 'boolean' },
      possibleErrors: ['403 ROLE_NOT_AUTHORIZED', '404 CUSTOMER_NOT_FOUND'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200, 201] },
    }),
  ],
};

const phoneTrust: WorkflowStageSeed = {
  stageCode: 'signup_phone_trust',
  name: 'Confianza del teléfono (WhatsApp)',
  description: 'Verificación alternativa del teléfono con el proveedor externo. Opcional: refuerza la confianza del contacto.',
  moduleCode: 'external_data',
  actorType: 'external_provider',
  displayOrder: 10,
  isOptional: true,
  completionRule: { type: 'manual' },
  steps: [
    step({
      stepCode: 'signup.whatsapp_start',
      name: 'Enviar el código por WhatsApp',
      description: 'Pide al proveedor que envíe el código de verificación al número declarado.',
      httpMethod: 'POST',
      routePath: '/whatsapp/verification/start',
      executionOrder: 10,
      isMandatory: false,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { customerId: 'string', phone: 'string' },
      possibleErrors: ['424 PROVIDER_UNAVAILABLE', '429 RATE_LIMITED'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200, 202] },
    }),
    step({
      stepCode: 'signup.whatsapp_confirm',
      name: 'Confirmar el código de WhatsApp',
      description: 'Valida el código recibido y marca el teléfono como verificado por el proveedor.',
      httpMethod: 'POST',
      routePath: '/whatsapp/verification/confirm',
      executionOrder: 20,
      isMandatory: false,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { customerId: 'string', code: 'string' },
      possibleErrors: ['422 INVALID_CODE'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
  ],
};

const contactVerification: WorkflowStageSeed = {
  stageCode: 'signup_contact_verification',
  name: 'Verificación de contacto',
  description: 'Registra correo y teléfono y comprueba que son del usuario con un código de un solo uso.',
  moduleCode: 'customer_onboarding',
  actorType: 'customer',
  displayOrder: 40,
  completionRule: { type: 'onboarding_section', sectionCode: 'contact_verification' },
  steps: [
    step({
      stepCode: 'signup.contact_methods',
      name: 'Registrar los medios de contacto',
      description: 'Declara el correo y el teléfono del cliente sobre los que se hará la verificación.',
      httpMethod: 'POST',
      routePath: '/customer-onboarding/:customerId/contact-methods',
      executionOrder: 10,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { email: 'string', phone: 'string' },
      possibleErrors: ['409 CONTACT_ALREADY_VERIFIED', '422 VALIDATION_ERROR'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200, 201] },
    }),
    step({
      stepCode: 'signup.contact_request',
      name: 'Solicitar el código de verificación',
      description: 'Dispara el envío del código al medio elegido. Tiene límite de reintentos por ventana de tiempo.',
      httpMethod: 'POST',
      routePath: '/customer-onboarding/:customerId/contact-verification/request',
      executionOrder: 20,
      isRepeatable: true,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { channel: 'email | sms' },
      possibleErrors: ['429 TOO_MANY_REQUESTS'],
      retryStrategy: NO_RETRY,
      producesEvents: ['customer.contact_verification_requested'],
      successCriteria: { statusCodes: [200, 202] },
    }),
    step({
      stepCode: 'signup.contact_submit',
      name: 'Enviar el código recibido',
      description: 'Valida el código. Con esto la sección de contacto queda completa y deja de bloquear el avance.',
      httpMethod: 'POST',
      routePath: '/customer-onboarding/:customerId/contact-verification/submit',
      executionOrder: 30,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { channel: 'email | sms', code: 'string' },
      possibleErrors: ['410 CODE_EXPIRED', '422 INVALID_CODE'],
      retryStrategy: NO_RETRY,
      producesEvents: ['customer.contact_verified'],
      successCriteria: { statusCodes: [200] },
    }),
  ],
  subStages: [phoneTrust],
};

const privacyConsents: WorkflowStageSeed = {
  stageCode: 'signup_privacy_consents',
  name: 'Consentimientos de privacidad',
  description: 'Registra la aceptación de los documentos que se mostraron al principio. Sin esto el expediente queda bloqueado.',
  moduleCode: 'customer_privacy',
  actorType: 'customer',
  displayOrder: 50,
  completionRule: { type: 'no_blockers', blockerCodes: ['CONSENT_MISSING'] },
  steps: [
    step({
      stepCode: 'signup.consent_decisions',
      name: 'Registrar las decisiones de consentimiento',
      description: 'Acepta o rechaza cada documento, con la versión exacta que se mostró.',
      httpMethod: 'POST',
      routePath: '/customers/:customerId/privacy/consent-decisions',
      executionOrder: 10,
      allowedRoles: CUSTOMER_ROLES,
      inputContract: { decisions: '[{ documentCode, version, accepted }]' },
      possibleErrors: ['409 CONSENT_VERSION_OUTDATED', '422 VALIDATION_ERROR'],
      retryStrategy: NO_RETRY,
      producesEvents: ['customer.consents_recorded'],
      successCriteria: { statusCodes: [200, 201] },
    }),
  ],
};

const firstLogin: WorkflowStageSeed = {
  stageCode: 'signup_first_login',
  name: 'Primera sesión iniciada',
  description: 'El objetivo del recorrido: el usuario obtiene su token y la app confirma quién es.',
  moduleCode: 'auth',
  actorType: 'customer',
  displayOrder: 60,
  isTerminalStage: true,
  completionRule: { type: 'no_blockers', blockerCodes: ['NO_CREDENTIALS'] },
  steps: [
    step({
      stepCode: 'signup.login',
      name: 'Autenticarse con usuario y contraseña',
      description: 'Devuelve el token de acceso, o indica que hace falta un segundo factor.',
      httpMethod: 'POST',
      routePath: '/auth/login',
      executionOrder: 10,
      requiresAuth: false,
      allowedRoles: PUBLIC_ROLES,
      inputContract: { username: 'string', password: 'string', deviceId: 'string' },
      outputContract: { accessToken: 'string', refreshToken: 'string', mfaRequired: 'boolean' },
      possibleErrors: ['401 INVALID_CREDENTIALS', '423 ACCOUNT_LOCKED', '429 TOO_MANY_ATTEMPTS'],
      retryStrategy: NO_RETRY,
      producesEvents: ['auth.login_succeeded', 'auth.login_failed'],
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'signup.mfa',
      name: 'Completar el segundo factor',
      description: 'Sólo cuando el login lo pide. Canjea el desafío por el token definitivo.',
      httpMethod: 'POST',
      routePath: '/auth/mfa',
      executionOrder: 20,
      isMandatory: false,
      requiresAuth: false,
      allowedRoles: PUBLIC_ROLES,
      inputContract: { challengeId: 'string', code: 'string' },
      outputContract: { accessToken: 'string', refreshToken: 'string' },
      possibleErrors: ['401 INVALID_MFA_CODE', '410 CHALLENGE_EXPIRED'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'signup.login_pin',
      name: 'Autenticarse con PIN',
      description: 'Camino alternativo para el dispositivo ya registrado: evita teclear la contraseña en cada apertura.',
      httpMethod: 'POST',
      routePath: '/auth/login/pin',
      executionOrder: 30,
      isMandatory: false,
      requiresAuth: false,
      allowedRoles: PUBLIC_ROLES,
      inputContract: { customerId: 'string', pin: 'string', deviceId: 'string' },
      possibleErrors: ['401 INVALID_PIN', '409 DEVICE_NOT_ENROLLED'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
    step({
      stepCode: 'signup.me',
      name: 'Confirmar el actor autenticado',
      description: 'Cierra el recorrido: con el token en la mano, la app confirma identidad, rol y tenant.',
      httpMethod: 'GET',
      routePath: '/auth/me',
      executionOrder: 40,
      isFlowExit: true,
      allowedRoles: PUBLIC_ROLES,
      outputContract: { sub: 'string', role: 'string', tenantId: 'string', customerId: 'string' },
      possibleErrors: ['401 TOKEN_EXPIRED'],
      retryStrategy: READ_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
  ],
};

const credentialRecovery: WorkflowStageSeed = {
  stageCode: 'signup_recovery',
  name: 'Recuperación de acceso',
  description: 'Rama de excepción: el usuario no logra entrar y restablece su contraseña antes de reintentar.',
  moduleCode: 'auth',
  actorType: 'customer',
  displayOrder: 70,
  isOptional: true,
  completionRule: { type: 'manual' },
  steps: [
    step({
      stepCode: 'signup.password_reset_request',
      name: 'Pedir el restablecimiento de contraseña',
      description: 'Envía el enlace o código de restablecimiento al medio verificado.',
      httpMethod: 'POST',
      routePath: '/auth/password-reset/request',
      executionOrder: 10,
      isMandatory: false,
      requiresAuth: false,
      allowedRoles: PUBLIC_ROLES,
      inputContract: { username: 'string' },
      possibleErrors: ['429 TOO_MANY_REQUESTS'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200, 202] },
    }),
    step({
      stepCode: 'signup.password_reset_confirm',
      name: 'Confirmar la nueva contraseña',
      description: 'Canjea el código por una contraseña nueva y devuelve al usuario al login.',
      httpMethod: 'POST',
      routePath: '/auth/password-reset/confirm',
      executionOrder: 20,
      isMandatory: false,
      requiresAuth: false,
      allowedRoles: PUBLIC_ROLES,
      inputContract: { token: 'string', newPassword: 'string' },
      possibleErrors: ['410 RESET_TOKEN_EXPIRED', '422 WEAK_PASSWORD'],
      retryStrategy: NO_RETRY,
      successCriteria: { statusCodes: [200] },
    }),
  ],
};

export const SIGNUP_TO_LOGIN_WORKFLOW: WorkflowSeed = {
  workflowCode: 'account_signup_to_login',
  version: 'v1',
  name: 'Alta de cuenta: de la primera pantalla a la sesión iniciada',
  description:
    'Qué endpoints recorre un usuario para crearse una cuenta y quedar logueado: textos legales, alta, verificación de contacto, consentimientos y login (con su segundo factor y su recuperación de acceso).',
  processType: 'customer_journey',
  ownerDomain: 'customer_onboarding',
  status: 'active',
  isDefault: true,
  entryStageCode: 'signup_legal_preview',
  terminalStageCodes: ['signup_first_login'],
  successCriteria: { description: 'El cliente existe, tiene contacto verificado y una sesión iniciada con token vigente.' },
  failureCriteria: { description: 'El alta queda sin credenciales, sin contacto verificado o el login se bloquea por intentos.' },
  metadata: { audience: 'app_movil', maintainer: 'customer_onboarding' },
  stages: [legalPreview, accountCreation, credentialProvisioning, contactVerification, privacyConsents, firstLogin, credentialRecovery],
  dependencies: [
    {
      stepCode: 'signup.contact_methods',
      dependsOnStepCode: 'signup.start',
      dependencyType: 'requires_data',
      description: 'Sin customerId no hay a quién colgarle el contacto.',
    },
    {
      stepCode: 'signup.contact_request',
      dependsOnStepCode: 'signup.contact_methods',
      dependencyType: 'requires_completion',
      description: 'No se puede pedir código para un medio que no está declarado.',
    },
    {
      stepCode: 'signup.contact_submit',
      dependsOnStepCode: 'signup.contact_request',
      dependencyType: 'requires_completion',
      description: 'El código a validar lo emite la solicitud anterior.',
    },
    {
      stepCode: 'signup.consent_decisions',
      dependsOnStepCode: 'signup.consent_documents',
      dependencyType: 'requires_data',
      description: 'Se acepta la versión exacta que se mostró.',
    },
    {
      stepCode: 'signup.login',
      dependsOnStepCode: 'signup.provision_credentials',
      dependencyType: 'soft',
      description: 'Sin credencial provisionada el login responde 401.',
    },
    {
      stepCode: 'signup.whatsapp_confirm',
      dependsOnStepCode: 'signup.whatsapp_start',
      dependencyType: 'requires_completion',
      description: 'El código a confirmar lo envía el paso anterior.',
    },
    {
      stepCode: 'signup.me',
      dependsOnStepCode: 'signup.login',
      dependencyType: 'requires_data',
      description: 'Necesita el token que devuelve el login.',
    },
  ],
  transitions: [
    {
      transitionCode: 'signup.entry',
      fromStepCode: null,
      toStepCode: 'signup.consent_documents',
      conditionType: 'always',
      description: 'Entrada: la app muestra los textos legales antes de pedir datos.',
      displayOrder: 10,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.docs_to_start',
      fromStepCode: 'signup.consent_documents',
      toStepCode: 'signup.start',
      conditionType: 'on_success',
      description: 'Con los textos a la vista, el usuario inicia el alta.',
      displayOrder: 20,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.start_to_contact',
      fromStepCode: 'signup.start',
      toStepCode: 'signup.contact_methods',
      conditionType: 'on_success',
      description: 'Creado el cliente, se declaran sus medios de contacto.',
      displayOrder: 30,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.start_to_credentials',
      fromStepCode: 'signup.start',
      toStepCode: 'signup.provision_credentials',
      conditionType: 'conditional',
      conditionExpression: { credentialsProvisionedByOperator: true },
      description: 'Alta asistida: un operador provisiona la credencial.',
      displayOrder: 35,
    },
    {
      transitionCode: 'signup.contact_to_request',
      fromStepCode: 'signup.contact_methods',
      toStepCode: 'signup.contact_request',
      conditionType: 'on_success',
      description: 'Declarado el medio, se pide el código.',
      displayOrder: 40,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.request_to_submit',
      fromStepCode: 'signup.contact_request',
      toStepCode: 'signup.contact_submit',
      conditionType: 'on_success',
      description: 'El usuario introduce el código recibido.',
      displayOrder: 50,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.request_to_whatsapp',
      fromStepCode: 'signup.contact_request',
      toStepCode: 'signup.whatsapp_start',
      conditionType: 'conditional',
      conditionExpression: { channel: 'whatsapp' },
      description: 'Verificación alternativa por WhatsApp.',
      displayOrder: 55,
    },
    {
      transitionCode: 'signup.whatsapp_flow',
      fromStepCode: 'signup.whatsapp_start',
      toStepCode: 'signup.whatsapp_confirm',
      conditionType: 'on_success',
      description: 'Enviado el código, el usuario lo confirma.',
      displayOrder: 56,
    },
    {
      transitionCode: 'signup.submit_retry',
      fromStepCode: 'signup.contact_submit',
      toStepCode: 'signup.contact_request',
      conditionType: 'on_error',
      description: 'Código vencido o incorrecto: se vuelve a pedir.',
      displayOrder: 60,
    },
    {
      transitionCode: 'signup.submit_to_consents',
      fromStepCode: 'signup.contact_submit',
      toStepCode: 'signup.consent_decisions',
      conditionType: 'on_success',
      description: 'Contacto verificado: se registran los consentimientos.',
      displayOrder: 70,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.consents_to_login',
      fromStepCode: 'signup.consent_decisions',
      toStepCode: 'signup.login',
      conditionType: 'on_success',
      description: 'Con el expediente abierto, el usuario inicia sesión.',
      displayOrder: 80,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.login_to_mfa',
      fromStepCode: 'signup.login',
      toStepCode: 'signup.mfa',
      conditionType: 'conditional',
      conditionExpression: { mfaRequired: true },
      description: 'El login pidió segundo factor.',
      displayOrder: 90,
    },
    {
      transitionCode: 'signup.login_to_me',
      fromStepCode: 'signup.login',
      toStepCode: 'signup.me',
      conditionType: 'on_success',
      description: 'Sin segundo factor pendiente, la app confirma la identidad.',
      displayOrder: 100,
      isDefaultPath: true,
    },
    {
      transitionCode: 'signup.mfa_to_me',
      fromStepCode: 'signup.mfa',
      toStepCode: 'signup.me',
      conditionType: 'on_success',
      description: 'Superado el segundo factor, se confirma la identidad.',
      displayOrder: 110,
    },
    {
      transitionCode: 'signup.pin_to_me',
      fromStepCode: 'signup.login_pin',
      toStepCode: 'signup.me',
      conditionType: 'on_success',
      description: 'Acceso por PIN en dispositivo ya registrado.',
      displayOrder: 120,
    },
    {
      transitionCode: 'signup.login_to_recovery',
      fromStepCode: 'signup.login',
      toStepCode: 'signup.password_reset_request',
      conditionType: 'on_error',
      description: 'Credenciales inválidas o cuenta bloqueada: recuperación de acceso.',
      displayOrder: 130,
    },
    {
      transitionCode: 'signup.recovery_flow',
      fromStepCode: 'signup.password_reset_request',
      toStepCode: 'signup.password_reset_confirm',
      conditionType: 'on_success',
      description: 'Con el código en el correo, se fija la contraseña nueva.',
      displayOrder: 140,
    },
    {
      transitionCode: 'signup.recovery_to_login',
      fromStepCode: 'signup.password_reset_confirm',
      toStepCode: 'signup.login',
      conditionType: 'on_success',
      description: 'Restablecida la contraseña, el usuario vuelve al login.',
      displayOrder: 150,
    },
    {
      transitionCode: 'signup.exit',
      fromStepCode: 'signup.me',
      toStepCode: null,
      conditionType: 'always',
      description: 'Salida: la sesión está iniciada y la app puede continuar.',
      displayOrder: 160,
      isDefaultPath: true,
    },
  ],
};
