/**
 * @file Definiciones de negocio: qué evento existe, qué se observa de una persona y qué artefacto decide.
 * @business Esta pieza preserva la fuente de verdad y la evidencia histórica que soportan decisiones y cumplimiento.
 * @system define seeders para evolucionar, mapear, sembrar o consultar PostgreSQL de forma controlada.
 */
import { ID_INTERNOS } from './equipo.seed-data.js';
import { TENANT_DEMO, type DominioSembrado } from './tipos.js';

/** Bloque: 990001–990099 eventos · 990100–990199 observaciones · 990200–990299 artefactos. */
const T = TENANT_DEMO;
const F = '2026-04-01T00:00:00Z';

interface EventoSemilla {
  readonly id: number;
  readonly code: string;
  readonly nombre: string;
  readonly familia: string;
  readonly paquete: string;
  readonly tablas: readonly string[];
  readonly esquema: Record<string, string>;
  readonly dimension: string | null;
  readonly clase: string;
  readonly volumen: boolean;
  readonly equipo: string;
  readonly dominio: string;
}

const EVENTOS: EventoSemilla[] = [
  {
    id: 990001,
    code: 'customer.registered',
    nombre: 'Una persona se registró',
    familia: 'ciclo_de_vida',
    paquete: 'customer',
    tablas: ['customer.customers', 'customer.customer_status_events'],
    esquema: { customerId: 'bigint', canal: 'string', fecha: 'timestamp' },
    dimension: null,
    clase: 'PII_INDIRECTA',
    volumen: false,
    equipo: 'Producto',
    dominio: 'CUSTOMER',
  },
  {
    id: 990002,
    code: 'identity.verification_failed',
    nombre: 'La verificación de identidad no pasó',
    familia: 'identidad',
    paquete: 'identity',
    tablas: ['customer.identity_verification_attempts'],
    esquema: { customerId: 'bigint', motivo: 'string', confianza: 'number' },
    dimension: 'fraude',
    clase: 'BIOMETRICO',
    volumen: false,
    equipo: 'Seguridad',
    dominio: 'IDENTITY',
  },
  {
    id: 990003,
    code: 'credit.application_decided',
    nombre: 'Se decidió una solicitud de crédito',
    familia: 'credito',
    paquete: 'credit',
    tablas: ['credit.credit_applications', 'credit.credit_application_events'],
    esquema: { applicationId: 'bigint', desenlace: 'string', motivo: 'string', artefacto: 'string' },
    dimension: 'credito',
    clase: 'FINANCIERO',
    volumen: false,
    equipo: 'Riesgo',
    dominio: 'CREDIT',
  },
  {
    id: 990004,
    code: 'loan.disbursed',
    nombre: 'Se desembolsó un préstamo',
    familia: 'credito',
    paquete: 'credit',
    tablas: ['credit.loans', 'credit.loan_events'],
    esquema: { loanId: 'bigint', capital: 'number', plazo: 'integer' },
    dimension: 'credito',
    clase: 'FINANCIERO',
    volumen: false,
    equipo: 'Riesgo',
    dominio: 'CREDIT',
  },
  {
    id: 990005,
    code: 'loan.payment_applied',
    nombre: 'Se imputó un pago',
    familia: 'credito',
    paquete: 'credit',
    tablas: ['credit.loan_payments', 'credit.loan_payment_allocations'],
    esquema: { paymentId: 'bigint', monto: 'number', medio: 'string' },
    dimension: 'credito',
    clase: 'FINANCIERO',
    volumen: true,
    equipo: 'Operaciones',
    dominio: 'CREDIT',
  },
  {
    id: 990006,
    code: 'loan.installment_overdue',
    nombre: 'Una cuota venció sin pago',
    familia: 'mora',
    paquete: 'credit',
    tablas: ['credit.loan_installments', 'credit.loans'],
    esquema: { installmentId: 'bigint', diasAtraso: 'integer' },
    dimension: 'credito',
    clase: 'FINANCIERO',
    volumen: true,
    equipo: 'Cobranza',
    dominio: 'CREDIT',
  },
  {
    id: 990007,
    code: 'partner.onboarding_decided',
    nombre: 'Se decidió el alta de un comercio',
    familia: 'comercios',
    paquete: 'partner',
    tablas: ['partner.partner_profiles'],
    esquema: { partnerProfileId: 'bigint', desenlace: 'string', motivo: 'string' },
    dimension: null,
    clase: 'PUBLICO',
    volumen: false,
    equipo: 'Comercios',
    dominio: 'PARTNER',
  },
  {
    id: 990008,
    code: 'support.case_opened',
    nombre: 'Se abrió un caso de soporte',
    familia: 'soporte',
    paquete: 'support',
    tablas: ['support.support_cases', 'support.support_case_events'],
    esquema: { caseId: 'bigint', categoria: 'string', prioridad: 'string' },
    dimension: null,
    clase: 'PII_INDIRECTA',
    volumen: true,
    equipo: 'Soporte',
    dominio: 'SUPPORT',
  },
  {
    id: 990009,
    code: 'fraud.case_opened',
    nombre: 'Se abrió un caso de fraude',
    familia: 'fraude',
    paquete: 'fraud',
    tablas: ['case_management.fraud_cases'],
    esquema: { fraudCaseId: 'bigint', patron: 'string', severidad: 'string' },
    dimension: 'fraude',
    clase: 'PII_DIRECTA',
    volumen: false,
    equipo: 'Seguridad',
    dominio: 'FRAUD',
  },
  {
    id: 990010,
    code: 'privacy.request_received',
    nombre: 'Entró una solicitud sobre datos personales',
    familia: 'privacidad',
    paquete: 'privacy',
    tablas: ['privacy.data_subject_requests'],
    esquema: { requestId: 'bigint', tipo: 'string', vence: 'timestamp' },
    dimension: null,
    clase: 'PII_DIRECTA',
    volumen: false,
    equipo: 'Cumplimiento',
    dominio: 'PRIVACY',
  },
];

const eventos = EVENTOS.map((e) => ({
  _id: e.id,
  event_code: e.code,
  event_name: e.nombre,
  event_family: e.familia,
  source_package: e.paquete,
  target_tables_json: e.tablas,
  expected_payload_schema_json: e.esquema,
  risk_dimension: e.dimension,
  build_phase: 'produccion',
  data_classification_code: e.clase,
  is_high_volume: e.volumen,
  is_active: true,
  owner_team: e.equipo,
  domain_code: e.dominio,
  review_status: 'APPROVED',
  _created_at: F,
  _updated_at: F,
}));

interface ObservacionSemilla {
  readonly id: number;
  readonly code: string;
  readonly nombre: string;
  readonly tipo: string;
  readonly grupo: string;
  readonly etapa: string;
  readonly clase: string;
  readonly dimension: string | null;
  readonly consentimiento: boolean;
  readonly credito: boolean;
  readonly fraude: boolean;
  readonly legal: string;
  readonly prohibida?: string;
  readonly equidad: boolean;
  readonly equipo: string;
}

const OBSERVACIONES: ObservacionSemilla[] = [
  {
    id: 990101,
    code: 'ingreso_declarado',
    nombre: 'Ingreso mensual declarado',
    tipo: 'number',
    grupo: 'declarado',
    etapa: 'alta',
    clase: 'FINANCIERO',
    dimension: 'capacidad',
    consentimiento: false,
    credito: true,
    fraude: false,
    legal: 'approved',
    equidad: false,
    equipo: 'Riesgo',
  },
  {
    id: 990102,
    code: 'ocupacion',
    nombre: 'Ocupación declarada',
    tipo: 'string',
    grupo: 'declarado',
    etapa: 'alta',
    clase: 'PII_INDIRECTA',
    dimension: 'capacidad',
    consentimiento: false,
    credito: true,
    fraude: false,
    legal: 'approved',
    equidad: true,
    equipo: 'Riesgo',
  },
  {
    id: 990103,
    code: 'antiguedad_laboral_meses',
    nombre: 'Antigüedad en el empleo',
    tipo: 'integer',
    grupo: 'declarado',
    etapa: 'alta',
    clase: 'PII_INDIRECTA',
    dimension: 'estabilidad',
    consentimiento: false,
    credito: true,
    fraude: false,
    legal: 'approved',
    equidad: false,
    equipo: 'Riesgo',
  },
  {
    id: 990104,
    code: 'historial_pago_interno',
    nombre: 'Comportamiento de pago dentro de la red',
    tipo: 'object',
    grupo: 'interno',
    etapa: 'continua',
    clase: 'FINANCIERO',
    dimension: 'credito',
    consentimiento: false,
    credito: true,
    fraude: false,
    legal: 'approved',
    equidad: false,
    equipo: 'Riesgo',
  },
  {
    id: 990105,
    code: 'ingreso_extracto',
    nombre: 'Ingreso comprobado en extracto bancario',
    tipo: 'number',
    grupo: 'documental',
    etapa: 'evaluacion',
    clase: 'FINANCIERO',
    dimension: 'capacidad',
    consentimiento: true,
    credito: true,
    fraude: false,
    legal: 'approved',
    equidad: false,
    equipo: 'Riesgo',
  },
  {
    id: 990106,
    code: 'similitud_rostro_documento',
    nombre: 'Coincidencia entre la selfie y el documento',
    tipo: 'number',
    grupo: 'biometrico',
    etapa: 'alta',
    clase: 'BIOMETRICO',
    dimension: 'fraude',
    consentimiento: true,
    credito: false,
    fraude: true,
    legal: 'approved',
    equidad: true,
    equipo: 'Seguridad',
  },
  {
    id: 990107,
    code: 'dispositivo_compartido',
    nombre: 'El dispositivo aparece en varias cuentas',
    tipo: 'boolean',
    grupo: 'telemetria',
    etapa: 'continua',
    clase: 'OPERACIONAL',
    dimension: 'fraude',
    consentimiento: false,
    credito: false,
    fraude: true,
    legal: 'approved',
    equidad: false,
    equipo: 'Seguridad',
  },
  {
    id: 990108,
    code: 'ubicacion_domicilio',
    nombre: 'Coordenadas del domicilio declarado',
    tipo: 'object',
    grupo: 'telemetria',
    etapa: 'alta',
    clase: 'PII_INDIRECTA',
    dimension: 'cobrabilidad',
    consentimiento: true,
    credito: false,
    fraude: false,
    legal: 'approved',
    equidad: true,
    equipo: 'Operaciones',
  },
  {
    id: 990109,
    code: 'contactos_agenda',
    nombre: 'Contactos de la agenda del teléfono',
    tipo: 'object',
    grupo: 'telemetria',
    etapa: 'alta',
    clase: 'PII_DIRECTA',
    dimension: null,
    consentimiento: true,
    credito: false,
    fraude: false,
    legal: 'prohibited',
    prohibida: 'USO_DESPROPORCIONADO',
    equidad: true,
    equipo: 'Cumplimiento',
  },
  {
    id: 990110,
    code: 'genero_declarado',
    nombre: 'Género declarado',
    tipo: 'string',
    grupo: 'declarado',
    etapa: 'alta',
    clase: 'PII_INDIRECTA',
    dimension: null,
    consentimiento: false,
    credito: false,
    fraude: false,
    legal: 'prohibited',
    prohibida: 'CATEGORIA_PROTEGIDA',
    equidad: true,
    equipo: 'Cumplimiento',
  },
  {
    id: 990111,
    code: 'edad',
    nombre: 'Edad de la persona',
    tipo: 'integer',
    grupo: 'declarado',
    etapa: 'alta',
    clase: 'PII_INDIRECTA',
    dimension: null,
    consentimiento: false,
    credito: false,
    fraude: false,
    legal: 'restricted',
    prohibida: 'SOLO_ELEGIBILIDAD_LEGAL',
    equidad: true,
    equipo: 'Cumplimiento',
  },
  {
    id: 990112,
    code: 'zona_domicilio',
    nombre: 'Zona del domicilio',
    tipo: 'string',
    grupo: 'declarado',
    etapa: 'alta',
    clase: 'PII_INDIRECTA',
    dimension: 'cobrabilidad',
    consentimiento: false,
    credito: false,
    fraude: false,
    legal: 'restricted',
    prohibida: 'RIESGO_DE_PROXY_GEOGRAFICO',
    equidad: true,
    equipo: 'Cumplimiento',
  },
];

const observaciones = OBSERVACIONES.map((o) => ({
  _id: o.id,
  observation_code: o.code,
  observation_name: o.nombre,
  data_type: o.tipo,
  source_group: o.grupo,
  expected_availability_stage: o.etapa,
  build_phase: 'produccion',
  data_classification_code: o.clase,
  risk_dimension: o.dimension,
  requires_consent: o.consentimiento,
  allowed_for_credit_decision: o.credito,
  allowed_for_fraud_decision: o.fraude,
  legal_review_status: o.legal,
  prohibited_reason_code: o.prohibida ?? null,
  fairness_review_required: o.equidad,
  is_active: true,
  owner_team: o.equipo,
  domain_code: o.grupo === 'biometrico' ? 'IDENTITY' : o.grupo === 'telemetria' ? 'TELEMETRY' : 'CUSTOMER',
  review_status: 'APPROVED',
  _created_at: F,
  _updated_at: F,
}));

const ARTEFACTOS = [
  {
    _id: 990201,
    decision_type: 'CREDIT_LIMIT',
    artifact_code: 'credit-limit',
    pinned_version: '2026.2',
    workflow_stage: 'onboarding',
    description: 'Calcula el límite y la cuota máxima que sostiene el ingreso de la persona.',
    consumer_endpoints: 'POST /api/v1/customers/:id/eligibility · POST /api/v1/credit/applications',
    notes: 'Fijado a 2026.2 porque 2026.3 cambia la definición de ingreso disponible y hay que recalibrar antes de soltarlo.',
  },
  {
    _id: 990202,
    decision_type: 'CREDIT_APPLICATION',
    artifact_code: 'credit-scoring',
    pinned_version: '2026.3',
    workflow_stage: 'solicitud',
    description: 'Decide una solicitud concreta: aprobar, ajustar el monto o rechazar, siempre con motivo comunicable.',
    consumer_endpoints: 'POST /api/v1/credit/applications/:id/decide',
    notes: null,
  },
  {
    _id: 990203,
    decision_type: 'IDENTITY_VERIFICATION',
    artifact_code: 'identity-verification',
    pinned_version: '2026.4',
    workflow_stage: 'alta',
    description: 'Contesta si el documento es auténtico, si el rostro es el mismo y si los datos coinciden.',
    consumer_endpoints: 'POST /api/v1/identity/verify',
    notes: 'Tres preguntas separadas a propósito: un «no» de cada una lleva a un camino distinto.',
  },
  {
    _id: 990204,
    decision_type: 'PARTNER_ONBOARDING',
    artifact_code: 'partner-onboarding',
    pinned_version: '2026.2',
    workflow_stage: 'alta_comercio',
    description: 'Aprueba, rechaza o manda a revisión humana el alta de un comercio.',
    consumer_endpoints: 'POST /api/v1/partners/:id/submit',
    notes: null,
  },
  {
    _id: 990205,
    decision_type: 'FRAUD_SCREENING',
    artifact_code: 'fraud-screening',
    pinned_version: null,
    workflow_stage: 'continua',
    description: 'Vigila patrones de fraude sobre la actividad ya ocurrida.',
    consumer_endpoints: 'worker: fraud-screening',
    notes: 'Sin versión fijada: sigue la última publicada, porque aquí llegar tarde cuesta más que un cambio inesperado.',
  },
];

const artefactos = ARTEFACTOS.map((a) => ({
  ...a,
  _tenant_id: T,
  environment_code: 'dev',
  changed_by_internal_user_id: ID_INTERNOS.riesgo,
  _created_at: F,
  _updated_at: F,
}));

export const DEFINICIONES: DominioSembrado = {
  nombre: 'definiciones',
  descripcion:
    'Diez eventos de dominio, doce observaciones (cuatro de ellas prohibidas o restringidas con su motivo) y cinco artefactos de decisión.',
  bloques: [
    { tabla: 'catalog.event_definitions', filas: eventos },
    { tabla: 'catalog.observation_definitions', filas: observaciones },
    { tabla: 'catalog.decision_artifact_bindings', filas: artefactos, conflicto: ['_tenant_id', 'decision_type'] },
  ],
};
