/**
 * @file Catálogos de contexto: el ecosistema que el portal usa para clasificar personas y comercios.
 * @business Esta pieza preserva la fuente de verdad y la evidencia histórica que soportan decisiones y cumplimiento.
 * @system define seeders para evolucionar, mapear, sembrar o consultar PostgreSQL de forma controlada.
 */
import type { DominioSembrado } from './tipos.js';

/**
 * Bloque de identificadores de este dominio (todos dentro del rango reservado 900000+):
 *
 *   900001–900099  fuentes            900100–900199  catálogos
 *   900200–900299  versiones          900300–900999  ítems
 *   901000–901199  alias              901200–901399  mapeos de riesgo
 *   901400–901499  trabajos de ingesta 901500–901699 ítems en revisión y decisiones
 */
const AHORA = '2026-09-10T14:00:00Z';

const FUENTES = [
  {
    _id: 900001,
    source_code: 'INE_BO',
    source_name: 'Instituto Nacional de Estadística de Bolivia',
    source_type: 'organismo_publico',
    reliability_score: 0.95,
    refresh_frequency: 'anual',
    notes:
      'Clasificador nacional de ocupaciones y actividad económica. Es la referencia con la que se concilian las ocupaciones declaradas por el cliente en el alta.',
    is_active: true,
  },
  {
    _id: 900002,
    source_code: 'ASFI',
    source_name: 'Autoridad de Supervisión del Sistema Financiero',
    source_type: 'regulador',
    reliability_score: 0.99,
    refresh_frequency: 'mensual',
    notes:
      'Registro de entidades financieras autorizadas a operar en Bolivia. Una entidad que no figure aquí no puede aparecer como acreedor en un extracto aceptado.',
    is_active: true,
  },
  {
    _id: 900003,
    source_code: 'SIN',
    source_name: 'Servicio de Impuestos Nacionales',
    source_type: 'organismo_publico',
    reliability_score: 0.92,
    refresh_frequency: 'trimestral',
    notes: 'Actividades económicas registradas por NIT. Sirve para contrastar el rubro que declara un comercio al afiliarse.',
    is_active: true,
  },
  {
    _id: 900004,
    source_code: 'ATLAS_CURADURIA',
    source_name: 'Curaduría del equipo de operaciones de Atlas',
    source_type: 'interna',
    reliability_score: 0.88,
    refresh_frequency: 'continua',
    notes:
      'Lo que el equipo añade a mano cuando la realidad del mercado no cabe en el clasificador oficial: oficios informales, rubros mixtos, zonas que el municipio aún no numeró.',
    is_active: true,
  },
  {
    _id: 900005,
    source_code: 'MOTOR_SEMANTICO',
    source_name: 'Clasificador semántico del Motor de decisiones',
    source_type: 'modelo',
    reliability_score: 0.81,
    refresh_frequency: 'continua',
    notes:
      'Propone candidatos a partir del texto libre que escribe el cliente. Nunca entra directo al catálogo: pasa por la bandeja de revisión y lo aprueba una persona.',
    is_active: true,
  },
  {
    _id: 900006,
    source_code: 'COMERCIOS_AFILIADOS',
    source_name: 'Declaraciones de los propios comercios afiliados',
    source_type: 'declarada',
    reliability_score: 0.65,
    refresh_frequency: 'continua',
    notes: 'Lo que el comercio dice de sí mismo al afiliarse. Fiabilidad baja a propósito: se usa como pista, no como prueba.',
    is_active: true,
  },
];

const CATALOGOS = [
  {
    _id: 900101,
    catalog_code: 'OCUPACIONES',
    catalog_name: 'Ocupaciones e ingresos declarados',
    domain: 'customer',
    description:
      'Cómo se gana la vida quien pide el crédito, con el rango de ingreso típico y la estabilidad esperada de cada oficio. Es la entrada principal para estimar capacidad de pago cuando no hay extracto bancario.',
    owner_team: 'Riesgo',
    is_active: true,
  },
  {
    _id: 900102,
    catalog_code: 'RUBROS_COMERCIO',
    catalog_name: 'Rubros de comercio afiliado',
    domain: 'partner',
    description:
      'A qué se dedica cada comercio de la red. Define el ticket promedio esperado, el riesgo de devolución y qué productos de crédito se le pueden habilitar.',
    owner_team: 'Comercios',
    is_active: true,
  },
  {
    _id: 900103,
    catalog_code: 'ENTIDADES_FINANCIERAS',
    catalog_name: 'Entidades financieras supervisadas por ASFI',
    domain: 'credit',
    description:
      'Bancos, cooperativas y entidades de vivienda autorizadas en Bolivia. Se usa para reconocer al acreedor que aparece en un extracto y para leer el endeudamiento declarado.',
    owner_team: 'Riesgo',
    is_active: true,
  },
  {
    _id: 900104,
    catalog_code: 'DESTINOS_CREDITO',
    catalog_name: 'Destinos declarados del crédito',
    domain: 'credit',
    description:
      'Para qué dice el cliente que quiere el dinero. No se toma como verdad: se contrasta con el comercio donde termina gastándose y las diferencias alimentan el monitoreo.',
    owner_team: 'Riesgo',
    is_active: true,
  },
  {
    _id: 900105,
    catalog_code: 'ZONAS_COBERTURA',
    catalog_name: 'Zonas de cobertura urbana',
    domain: 'operations',
    description:
      'Las zonas donde Atlas opera hoy, con su nivel de cobertura de comercios y de cobranza en terreno. Manda en qué dirección se puede entregar y dónde se puede visitar a un cliente en mora.',
    owner_team: 'Operaciones',
    is_active: true,
  },
  {
    _id: 900106,
    catalog_code: 'MOTIVOS_RECHAZO',
    catalog_name: 'Motivos de rechazo comunicables',
    domain: 'risk',
    description:
      'El texto exacto que puede leer un cliente cuando se le niega un crédito. Cada motivo está redactado para ser comprensible y defendible ante un reclamo; los códigos internos del modelo no salen nunca de aquí.',
    owner_team: 'Cumplimiento',
    is_active: true,
  },
];

const VERSIONES = [
  {
    _id: 900201,
    catalog_id: 900101,
    version_code: '2026.2',
    status: 'published',
    valid_from: '2026-07-01',
    valid_until: null,
    created_by_type: 'RISK_ANALYST',
    approved_by_type: 'RISK_MANAGER',
    approved_at: '2026-06-28T16:20:00Z',
    notes:
      'Se separó «comerciante» en minorista y mayorista: mezclados daban una capacidad de pago promedio que no describía a ninguno de los dos.',
  },
  {
    _id: 900202,
    catalog_id: 900101,
    version_code: '2026.3',
    status: 'draft',
    valid_from: '2026-10-01',
    valid_until: null,
    created_by_type: 'RISK_ANALYST',
    approved_by_type: null,
    approved_at: null,
    notes: 'Borrador para incorporar los oficios de plataformas de reparto, que hoy caen en «otros» y ya son el 4 % de las altas.',
  },
  {
    _id: 900203,
    catalog_id: 900102,
    version_code: '2026.1',
    status: 'published',
    valid_from: '2026-03-01',
    valid_until: null,
    created_by_type: 'MERCHANT_OPERATIONS',
    approved_by_type: 'OPERATIONS_MANAGER',
    approved_at: '2026-02-26T11:00:00Z',
    notes: 'Primer corte con los rubros que de verdad aparecen en la red, no los del clasificador fiscal.',
  },
  {
    _id: 900204,
    catalog_id: 900102,
    version_code: '2026.2',
    status: 'pending_approval',
    valid_from: '2026-10-01',
    valid_until: null,
    created_by_type: 'MERCHANT_OPERATIONS',
    approved_by_type: null,
    approved_at: null,
    notes: 'Añade farmacia y veterinaria como rubros propios. Esperando la firma de Operaciones.',
  },
  {
    _id: 900205,
    catalog_id: 900103,
    version_code: '2026.1',
    status: 'published',
    valid_from: '2026-01-15',
    valid_until: null,
    created_by_type: 'RISK_MANAGER',
    approved_by_type: 'COMPLIANCE_MANAGER',
    approved_at: '2026-01-14T09:30:00Z',
    notes: 'Copiado del registro público de ASFI y conciliado con los nombres que imprimen los extractos.',
  },
  {
    _id: 900206,
    catalog_id: 900104,
    version_code: '2026.1',
    status: 'published',
    valid_from: '2026-02-01',
    valid_until: null,
    created_by_type: 'RISK_ANALYST',
    approved_by_type: 'RISK_MANAGER',
    approved_at: '2026-01-30T15:45:00Z',
    notes: null,
  },
  {
    _id: 900207,
    catalog_id: 900104,
    version_code: '2025.4',
    status: 'retired',
    valid_from: '2025-10-01',
    valid_until: '2026-01-31',
    created_by_type: 'RISK_ANALYST',
    approved_by_type: 'RISK_MANAGER',
    approved_at: '2025-09-29T12:00:00Z',
    notes: 'Retirada al publicarse 2026.1. Se conserva porque hay créditos vivos que se decidieron con ella.',
  },
  {
    _id: 900208,
    catalog_id: 900105,
    version_code: '2026.2',
    status: 'published',
    valid_from: '2026-08-01',
    valid_until: null,
    created_by_type: 'OPERATIONS_ANALYST',
    approved_by_type: 'OPERATIONS_MANAGER',
    approved_at: '2026-07-30T10:15:00Z',
    notes: 'Se sumó El Alto sur tras abrir los tres primeros comercios de la zona.',
  },
  {
    _id: 900209,
    catalog_id: 900106,
    version_code: '2026.1',
    status: 'published',
    valid_from: '2026-04-01',
    valid_until: null,
    created_by_type: 'COMPLIANCE_ANALYST',
    approved_by_type: 'COMPLIANCE_MANAGER',
    approved_at: '2026-03-28T17:00:00Z',
    notes: 'Redacción revisada con Legal: cada motivo se entiende sin conocer el modelo y no revela su lógica interna.',
  },
];

interface ItemSemilla {
  readonly id: number;
  readonly version: number;
  readonly code: string;
  readonly name: string;
  readonly type: string;
  readonly fuente: number;
  readonly confianza: number;
  readonly atributos: Record<string, unknown>;
}

const ITEMS: ItemSemilla[] = [
  // --- Ocupaciones (versión publicada 2026.2) ---
  {
    id: 900301,
    version: 900201,
    code: 'COMERCIANTE_MINORISTA',
    name: 'Comerciante minorista',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.93,
    atributos: {
      ingresoMensualTipicoBob: [2500, 6000],
      estabilidad: 'media',
      estacionalidad: 'alta en diciembre y en el mes de la feria',
      verificacion: 'declaracion + observacion de ventas por QR',
    },
  },
  {
    id: 900302,
    version: 900201,
    code: 'COMERCIANTE_MAYORISTA',
    name: 'Comerciante mayorista',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.9,
    atributos: {
      ingresoMensualTipicoBob: [8000, 25000],
      estabilidad: 'media-alta',
      estacionalidad: 'baja',
      verificacion: 'factura y movimiento bancario',
    },
  },
  {
    id: 900303,
    version: 900201,
    code: 'TRANSPORTISTA',
    name: 'Transportista',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.89,
    atributos: {
      ingresoMensualTipicoBob: [3000, 9000],
      estabilidad: 'media',
      riesgoParticular: 'ingreso ligado al precio del combustible y a paros del sector',
    },
  },
  {
    id: 900304,
    version: 900201,
    code: 'DOCENTE',
    name: 'Docente',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.97,
    atributos: {
      ingresoMensualTipicoBob: [4200, 8500],
      estabilidad: 'alta',
      verificacion: 'boleta de pago; el sector público paga el mismo día cada mes',
    },
  },
  {
    id: 900305,
    version: 900201,
    code: 'EMPLEADO_PUBLICO',
    name: 'Empleado público',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.98,
    atributos: { ingresoMensualTipicoBob: [4000, 12000], estabilidad: 'alta', verificacion: 'boleta de pago y antigüedad' },
  },
  {
    id: 900306,
    version: 900201,
    code: 'EMPLEADO_PRIVADO',
    name: 'Empleado en empresa privada',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.95,
    atributos: { ingresoMensualTipicoBob: [3500, 14000], estabilidad: 'media-alta', verificacion: 'boleta de pago y aportes a la gestora' },
  },
  {
    id: 900307,
    version: 900201,
    code: 'OFICIO_INDEPENDIENTE',
    name: 'Oficio independiente (albañil, gasfitero, costurera)',
    type: 'ocupacion',
    fuente: 900004,
    confianza: 0.72,
    atributos: {
      ingresoMensualTipicoBob: [2000, 7000],
      estabilidad: 'baja',
      verificacion: 'sin respaldo documental; se apoya en el histórico de pagos en la red',
    },
  },
  {
    id: 900308,
    version: 900201,
    code: 'AGRICULTOR',
    name: 'Agricultor o productor',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.84,
    atributos: {
      ingresoMensualTipicoBob: [1800, 9000],
      estabilidad: 'baja',
      estacionalidad: 'concentrada en cosecha; la cuota mensual plana no le sirve',
    },
  },
  {
    id: 900309,
    version: 900201,
    code: 'ESTUDIANTE_CON_INGRESO',
    name: 'Estudiante con ingreso propio',
    type: 'ocupacion',
    fuente: 900004,
    confianza: 0.7,
    atributos: { ingresoMensualTipicoBob: [800, 2500], estabilidad: 'baja', limiteSugeridoBob: 1500 },
  },
  {
    id: 900310,
    version: 900201,
    code: 'JUBILADO',
    name: 'Jubilado o rentista',
    type: 'ocupacion',
    fuente: 900001,
    confianza: 0.96,
    atributos: { ingresoMensualTipicoBob: [2200, 5500], estabilidad: 'muy alta', verificacion: 'renta de la gestora, fecha de cobro fija' },
  },

  // --- Rubros de comercio (versión publicada 2026.1) ---
  {
    id: 900321,
    version: 900203,
    code: 'ABARROTES',
    name: 'Abarrotes y tienda de barrio',
    type: 'rubro',
    fuente: 900003,
    confianza: 0.94,
    atributos: { ticketPromedioBob: 45, frecuenciaCompra: 'diaria', devoluciones: 'muy bajas', creditoHabilitado: ['consumo_corto'] },
  },
  {
    id: 900322,
    version: 900203,
    code: 'ELECTRODOMESTICOS',
    name: 'Electrodomésticos y línea blanca',
    type: 'rubro',
    fuente: 900003,
    confianza: 0.96,
    atributos: {
      ticketPromedioBob: 2400,
      frecuenciaCompra: 'esporádica',
      devoluciones: 'medias',
      creditoHabilitado: ['cuotas_6', 'cuotas_12'],
    },
  },
  {
    id: 900323,
    version: 900203,
    code: 'FERRETERIA',
    name: 'Ferretería y materiales de construcción',
    type: 'rubro',
    fuente: 900003,
    confianza: 0.93,
    atributos: { ticketPromedioBob: 620, frecuenciaCompra: 'mensual', devoluciones: 'bajas', creditoHabilitado: ['cuotas_3', 'cuotas_6'] },
  },
  {
    id: 900324,
    version: 900203,
    code: 'RESTAURANTE',
    name: 'Restaurante y comida preparada',
    type: 'rubro',
    fuente: 900003,
    confianza: 0.91,
    atributos: { ticketPromedioBob: 70, frecuenciaCompra: 'semanal', devoluciones: 'nulas', creditoHabilitado: ['consumo_corto'] },
  },
  {
    id: 900325,
    version: 900203,
    code: 'ROPA_CALZADO',
    name: 'Ropa y calzado',
    type: 'rubro',
    fuente: 900003,
    confianza: 0.9,
    atributos: { ticketPromedioBob: 280, frecuenciaCompra: 'mensual', devoluciones: 'altas', creditoHabilitado: ['cuotas_3'] },
  },
  {
    id: 900326,
    version: 900203,
    code: 'TECNOLOGIA',
    name: 'Tecnología y telefonía',
    type: 'rubro',
    fuente: 900003,
    confianza: 0.95,
    atributos: {
      ticketPromedioBob: 1800,
      frecuenciaCompra: 'esporádica',
      devoluciones: 'medias',
      creditoHabilitado: ['cuotas_6', 'cuotas_12'],
      alertaFraude: 'rubro preferido para el desvío de crédito a reventa',
    },
  },
  {
    id: 900327,
    version: 900203,
    code: 'SALUD_OPTICA',
    name: 'Salud, óptica y laboratorio',
    type: 'rubro',
    fuente: 900003,
    confianza: 0.92,
    atributos: {
      ticketPromedioBob: 450,
      frecuenciaCompra: 'esporádica',
      devoluciones: 'nulas',
      creditoHabilitado: ['cuotas_3', 'cuotas_6'],
    },
  },
  {
    id: 900328,
    version: 900203,
    code: 'SERVICIOS_MOVILIDAD',
    name: 'Repuestos y servicios de movilidad',
    type: 'rubro',
    fuente: 900006,
    confianza: 0.78,
    atributos: { ticketPromedioBob: 900, frecuenciaCompra: 'esporádica', devoluciones: 'bajas', creditoHabilitado: ['cuotas_6'] },
  },

  // --- Entidades financieras (versión publicada 2026.1) ---
  {
    id: 900341,
    version: 900205,
    code: 'BNB',
    name: 'Banco Nacional de Bolivia S.A.',
    type: 'entidad_financiera',
    fuente: 900002,
    confianza: 0.99,
    atributos: { tipo: 'banco_multiple', reportaACentral: true, nombresEnExtracto: ['BNB', 'BANCO NACIONAL DE BOLIVIA'] },
  },
  {
    id: 900342,
    version: 900205,
    code: 'BMSC',
    name: 'Banco Mercantil Santa Cruz S.A.',
    type: 'entidad_financiera',
    fuente: 900002,
    confianza: 0.99,
    atributos: { tipo: 'banco_multiple', reportaACentral: true, nombresEnExtracto: ['BMSC', 'MERCANTIL SANTA CRUZ'] },
  },
  {
    id: 900343,
    version: 900205,
    code: 'BUN',
    name: 'Banco Unión S.A.',
    type: 'entidad_financiera',
    fuente: 900002,
    confianza: 0.99,
    atributos: { tipo: 'banco_multiple', reportaACentral: true, nombresEnExtracto: ['BANCO UNION', 'BUN'] },
  },
  {
    id: 900344,
    version: 900205,
    code: 'BCP_BO',
    name: 'Banco de Crédito de Bolivia S.A.',
    type: 'entidad_financiera',
    fuente: 900002,
    confianza: 0.99,
    atributos: { tipo: 'banco_multiple', reportaACentral: true, nombresEnExtracto: ['BCP', 'BANCO DE CREDITO'] },
  },
  {
    id: 900345,
    version: 900205,
    code: 'BANCO_FIE',
    name: 'Banco FIE S.A.',
    type: 'entidad_financiera',
    fuente: 900002,
    confianza: 0.98,
    atributos: { tipo: 'banco_pyme', reportaACentral: true, nombresEnExtracto: ['BANCO FIE', 'FIE'] },
  },
  {
    id: 900346,
    version: 900205,
    code: 'BANCO_SOL',
    name: 'Banco Solidario S.A.',
    type: 'entidad_financiera',
    fuente: 900002,
    confianza: 0.98,
    atributos: { tipo: 'banco_pyme', reportaACentral: true, nombresEnExtracto: ['BANCOSOL', 'BANCO SOLIDARIO'] },
  },
  {
    id: 900347,
    version: 900205,
    code: 'COOP_JESUS_NAZARENO',
    name: 'Cooperativa Jesús Nazareno Ltda.',
    type: 'entidad_financiera',
    fuente: 900002,
    confianza: 0.95,
    atributos: { tipo: 'cooperativa', reportaACentral: true, nombresEnExtracto: ['COOP JESUS NAZARENO', 'CJN'] },
  },

  // --- Destinos del crédito (versión publicada 2026.1) ---
  {
    id: 900361,
    version: 900206,
    code: 'ELECTRODOMESTICO_HOGAR',
    name: 'Electrodoméstico para el hogar',
    type: 'destino',
    fuente: 900004,
    confianza: 0.9,
    atributos: { rubrosCoherentes: ['ELECTRODOMESTICOS'], montoTipicoBob: [1500, 6000] },
  },
  {
    id: 900362,
    version: 900206,
    code: 'MEJORA_VIVIENDA',
    name: 'Mejora o ampliación de vivienda',
    type: 'destino',
    fuente: 900004,
    confianza: 0.88,
    atributos: { rubrosCoherentes: ['FERRETERIA'], montoTipicoBob: [2000, 15000] },
  },
  {
    id: 900363,
    version: 900206,
    code: 'CAPITAL_TRABAJO',
    name: 'Capital de trabajo para el negocio',
    type: 'destino',
    fuente: 900004,
    confianza: 0.86,
    atributos: { rubrosCoherentes: ['ABARROTES', 'ROPA_CALZADO'], montoTipicoBob: [1000, 20000] },
  },
  {
    id: 900364,
    version: 900206,
    code: 'SALUD',
    name: 'Gasto de salud',
    type: 'destino',
    fuente: 900004,
    confianza: 0.93,
    atributos: {
      rubrosCoherentes: ['SALUD_OPTICA'],
      montoTipicoBob: [500, 8000],
      trato: 'no se usa para encarecer: un gasto de salud no es una señal de riesgo',
    },
  },
  {
    id: 900365,
    version: 900206,
    code: 'EDUCACION',
    name: 'Educación propia o de un familiar',
    type: 'destino',
    fuente: 900004,
    confianza: 0.94,
    atributos: { montoTipicoBob: [800, 9000], estacionalidad: 'febrero y agosto' },
  },
  {
    id: 900366,
    version: 900206,
    code: 'TELEFONO',
    name: 'Teléfono o equipo tecnológico',
    type: 'destino',
    fuente: 900004,
    confianza: 0.85,
    atributos: {
      rubrosCoherentes: ['TECNOLOGIA'],
      montoTipicoBob: [900, 5000],
      alertaFraude: 'el desvío a reventa se ve cuando el mismo cliente repite el destino en menos de 90 días',
    },
  },

  // --- Zonas de cobertura (versión publicada 2026.2) ---
  {
    id: 900381,
    version: 900208,
    code: 'SCZ_CENTRO',
    name: 'Santa Cruz · primer y segundo anillo',
    type: 'zona',
    fuente: 900004,
    confianza: 0.97,
    atributos: { comerciosActivos: 41, cobranzaEnTerreno: true, entregaADomicilio: true },
  },
  {
    id: 900382,
    version: 900208,
    code: 'SCZ_NORTE',
    name: 'Santa Cruz · norte (Equipetrol, Urubó)',
    type: 'zona',
    fuente: 900004,
    confianza: 0.95,
    atributos: { comerciosActivos: 23, cobranzaEnTerreno: true, entregaADomicilio: true },
  },
  {
    id: 900383,
    version: 900208,
    code: 'SCZ_PLAN3000',
    name: 'Santa Cruz · Plan 3000 y Villa Primero de Mayo',
    type: 'zona',
    fuente: 900004,
    confianza: 0.92,
    atributos: {
      comerciosActivos: 18,
      cobranzaEnTerreno: true,
      entregaADomicilio: false,
      nota: 'direcciones sin numeración oficial: se georreferencia con el punto que marca el cliente',
    },
  },
  {
    id: 900384,
    version: 900208,
    code: 'LPZ_CENTRO',
    name: 'La Paz · centro y Sopocachi',
    type: 'zona',
    fuente: 900004,
    confianza: 0.96,
    atributos: { comerciosActivos: 27, cobranzaEnTerreno: true, entregaADomicilio: true },
  },
  {
    id: 900385,
    version: 900208,
    code: 'ELALTO_SUR',
    name: 'El Alto · zona sur',
    type: 'zona',
    fuente: 900004,
    confianza: 0.83,
    atributos: {
      comerciosActivos: 3,
      cobranzaEnTerreno: false,
      entregaADomicilio: false,
      nota: 'zona abierta en agosto de 2026; sin histórico propio, hereda los topes de El Alto centro',
    },
  },
  {
    id: 900386,
    version: 900208,
    code: 'CBBA_CENTRO',
    name: 'Cochabamba · centro y Cala Cala',
    type: 'zona',
    fuente: 900004,
    confianza: 0.94,
    atributos: { comerciosActivos: 19, cobranzaEnTerreno: true, entregaADomicilio: true },
  },

  // --- Motivos de rechazo (versión publicada 2026.1) ---
  {
    id: 900391,
    version: 900209,
    code: 'CAPACIDAD_INSUFICIENTE',
    name: 'La cuota no cabe en el ingreso comprobado',
    type: 'motivo_rechazo',
    fuente: 900004,
    confianza: 0.99,
    atributos: {
      textoAlCliente:
        'Con el ingreso que pudimos verificar, esta cuota superaría lo que consideramos pagable sin apretarte. Podés volver a intentarlo con un monto menor o un plazo más largo.',
      accionSugerida: 'ofrecer monto menor',
    },
  },
  {
    id: 900392,
    version: 900209,
    code: 'IDENTIDAD_NO_VERIFICADA',
    name: 'No se pudo verificar la identidad',
    type: 'motivo_rechazo',
    fuente: 900004,
    confianza: 0.99,
    atributos: {
      textoAlCliente:
        'No pudimos confirmar que el documento y la selfie correspondan a la misma persona. Podés reintentar con mejor luz o acercarte a un comercio de la red.',
      accionSugerida: 'reintentar captura',
    },
  },
  {
    id: 900393,
    version: 900209,
    code: 'DEUDA_VIGENTE_ALTA',
    name: 'Endeudamiento vigente demasiado alto',
    type: 'motivo_rechazo',
    fuente: 900004,
    confianza: 0.98,
    atributos: {
      textoAlCliente:
        'Hoy tenés compromisos de pago que, sumados a este crédito, dejarían muy poco margen. Cuando bajen, volvé a intentarlo.',
      accionSugerida: 'reintentar en 60 días',
    },
  },
  {
    id: 900394,
    version: 900209,
    code: 'MORA_INTERNA',
    name: 'Mora vigente con Atlas',
    type: 'motivo_rechazo',
    fuente: 900004,
    confianza: 0.99,
    atributos: {
      textoAlCliente: 'Tenés una cuota pendiente con nosotros. Al regularizarla se habilita otra vez tu línea.',
      accionSugerida: 'derivar a cobranza',
    },
  },
  {
    id: 900395,
    version: 900209,
    code: 'DOCUMENTO_INCONSISTENTE',
    name: 'El documento presentado no es consistente',
    type: 'motivo_rechazo',
    fuente: 900004,
    confianza: 0.97,
    atributos: {
      textoAlCliente:
        'El documento que subiste no pasó nuestras comprobaciones. Si creés que hay un error, escribinos y lo revisa una persona.',
      accionSugerida: 'derivar a revisión humana',
      requiereRevisionHumana: true,
    },
  },
];

const ALIAS = [
  {
    _id: 901001,
    context_item_id: 900301,
    alias_value: 'vendedora de mercado',
    alias_type: 'coloquial',
    normalized_alias: 'vendedora de mercado',
    confidence_score: 0.88,
  },
  {
    _id: 901002,
    context_item_id: 900301,
    alias_value: 'tengo un puesto',
    alias_type: 'texto_libre',
    normalized_alias: 'tengo un puesto',
    confidence_score: 0.74,
  },
  {
    _id: 901003,
    context_item_id: 900303,
    alias_value: 'chofer de micro',
    alias_type: 'coloquial',
    normalized_alias: 'chofer de micro',
    confidence_score: 0.91,
  },
  {
    _id: 901004,
    context_item_id: 900303,
    alias_value: 'taxista',
    alias_type: 'coloquial',
    normalized_alias: 'taxista',
    confidence_score: 0.93,
  },
  {
    _id: 901005,
    context_item_id: 900307,
    alias_value: 'maestro albañil',
    alias_type: 'coloquial',
    normalized_alias: 'maestro albanil',
    confidence_score: 0.9,
  },
  {
    _id: 901006,
    context_item_id: 900307,
    alias_value: 'hago trabajos por mi cuenta',
    alias_type: 'texto_libre',
    normalized_alias: 'hago trabajos por mi cuenta',
    confidence_score: 0.66,
  },
  {
    _id: 901007,
    context_item_id: 900321,
    alias_value: 'tiendita',
    alias_type: 'coloquial',
    normalized_alias: 'tiendita',
    confidence_score: 0.87,
  },
  {
    _id: 901008,
    context_item_id: 900326,
    alias_value: 'celulares',
    alias_type: 'coloquial',
    normalized_alias: 'celulares',
    confidence_score: 0.95,
  },
  {
    _id: 901009,
    context_item_id: 900341,
    alias_value: 'BNB S.A.',
    alias_type: 'razon_social',
    normalized_alias: 'bnb sa',
    confidence_score: 0.99,
  },
  {
    _id: 901010,
    context_item_id: 900346,
    alias_value: 'BancoSol',
    alias_type: 'marca',
    normalized_alias: 'bancosol',
    confidence_score: 0.99,
  },
];

const MAPEOS_RIESGO = [
  {
    _id: 901201,
    context_item_id: 900301,
    risk_dimension: 'estabilidad_ingreso',
    risk_band: 'media',
    score_points_suggested: 0,
    reason_code: 'ING_VARIABLE',
    explanation:
      'El ingreso existe y es comprobable por las ventas de la red, pero varía mes a mes. No penaliza; sólo impide tratar el ingreso declarado como fijo.',
    model_usage: 'feature',
    valid_from: '2026-07-01',
    valid_until: null,
    allowed_for_direct_adverse_credit_action: false,
    requires_calibration: false,
  },
  {
    _id: 901202,
    context_item_id: 900307,
    risk_dimension: 'estabilidad_ingreso',
    risk_band: 'baja',
    score_points_suggested: -8,
    reason_code: 'ING_SIN_RESPALDO',
    explanation:
      'Oficio independiente sin documento que respalde el ingreso. Resta puntos, pero nunca es motivo único de rechazo: se compensa con historial de pagos en la red.',
    model_usage: 'feature',
    valid_from: '2026-07-01',
    valid_until: null,
    allowed_for_direct_adverse_credit_action: false,
    requires_calibration: true,
  },
  {
    _id: 901203,
    context_item_id: 900305,
    risk_dimension: 'estabilidad_ingreso',
    risk_band: 'alta',
    score_points_suggested: 12,
    reason_code: 'ING_FIJO_VERIFICABLE',
    explanation: 'Sueldo público con fecha de pago fija y boleta verificable: es el perfil de ingreso más predecible de la cartera.',
    model_usage: 'feature',
    valid_from: '2026-07-01',
    valid_until: null,
    allowed_for_direct_adverse_credit_action: false,
    requires_calibration: false,
  },
  {
    _id: 901204,
    context_item_id: 900308,
    risk_dimension: 'calce_de_cuota',
    risk_band: 'baja',
    score_points_suggested: 0,
    reason_code: 'ING_ESTACIONAL',
    explanation:
      'El ingreso llega concentrado en cosecha. No baja el puntaje: cambia el producto, que debe ofrecer cuota estacional en vez de mensual plana.',
    model_usage: 'regla_de_producto',
    valid_from: '2026-07-01',
    valid_until: null,
    allowed_for_direct_adverse_credit_action: false,
    requires_calibration: true,
  },
  {
    _id: 901205,
    context_item_id: 900326,
    risk_dimension: 'riesgo_de_desvio',
    risk_band: 'media',
    score_points_suggested: -5,
    reason_code: 'RUBRO_REVENTA',
    explanation:
      'Rubro con historial de compras que terminan en reventa. Sólo se activa cuando el mismo cliente repite el rubro en menos de 90 días.',
    model_usage: 'regla_de_monitoreo',
    valid_from: '2026-03-01',
    valid_until: null,
    allowed_for_direct_adverse_credit_action: false,
    requires_calibration: true,
  },
  {
    _id: 901206,
    context_item_id: 900385,
    risk_dimension: 'cobrabilidad',
    risk_band: 'baja',
    score_points_suggested: -6,
    reason_code: 'ZONA_SIN_HISTORICO',
    explanation:
      'Zona recién abierta, sin cobranza en terreno ni histórico propio. El descuento es temporal: se revisa al cumplir seis meses de operación.',
    model_usage: 'feature',
    valid_from: '2026-08-01',
    valid_until: '2027-02-01',
    allowed_for_direct_adverse_credit_action: false,
    requires_calibration: true,
  },
];

const TRABAJOS_INGESTA = [
  {
    _id: 901401,
    job_code: 'ING-2026-09-001',
    source_type: 'modelo',
    source_name: 'Clasificador semántico del Motor',
    triggered_by_type: 'RISK_ANALYST',
    status: 'completed',
    started_at: '2026-09-08T09:00:00Z',
    finished_at: '2026-09-08T09:04:12Z',
    summary_json: {
      textosAnalizados: 1840,
      candidatosPropuestos: 6,
      yaExistentes: 1834,
      nota: 'Salida de una semana de texto libre del campo «¿a qué te dedicás?» del alta.',
    },
  },
  {
    _id: 901402,
    job_code: 'ING-2026-09-002',
    source_type: 'archivo',
    source_name: 'Padrón de actividades del SIN (corte agosto)',
    triggered_by_type: 'MERCHANT_OPERATIONS',
    status: 'completed',
    started_at: '2026-09-09T15:30:00Z',
    finished_at: '2026-09-09T15:31:40Z',
    summary_json: { filasLeidas: 412, candidatosPropuestos: 2, descartadosPorDuplicado: 410 },
  },
];

const ITEMS_EN_REVISION = [
  {
    _id: 901501,
    catalog_id: 900101,
    ingestion_job_id: 901401,
    proposed_item_code: 'REPARTIDOR_APP',
    proposed_item_name: 'Repartidor de aplicación',
    proposed_attributes_json: {
      ingresoMensualTipicoBob: [1800, 4500],
      estabilidad: 'baja',
      evidencia: '217 personas se describieron así en una semana',
    },
    ai_suggested: true,
    review_status: 'pending_review',
    review_notes: null,
    created_by_type: 'MOTOR_SEMANTICO',
  },
  {
    _id: 901502,
    catalog_id: 900101,
    ingestion_job_id: 901401,
    proposed_item_code: 'CREADOR_CONTENIDO',
    proposed_item_name: 'Creador de contenido',
    proposed_attributes_json: { ingresoMensualTipicoBob: [600, 12000], estabilidad: 'muy baja', evidencia: '31 menciones' },
    ai_suggested: true,
    review_status: 'pending_review',
    review_notes: null,
    created_by_type: 'MOTOR_SEMANTICO',
  },
  {
    _id: 901503,
    catalog_id: 900102,
    ingestion_job_id: 901402,
    proposed_item_code: 'FARMACIA',
    proposed_item_name: 'Farmacia',
    proposed_attributes_json: { ticketPromedioBob: 120, frecuenciaCompra: 'quincenal', devoluciones: 'nulas' },
    ai_suggested: false,
    review_status: 'approved',
    review_notes: 'Aprobado: ya son 7 comercios y hoy caen todos en «salud y óptica», que mezcla cosas distintas.',
    created_by_type: 'MERCHANT_OPERATIONS',
  },
  {
    _id: 901504,
    catalog_id: 900102,
    ingestion_job_id: 901402,
    proposed_item_code: 'VETERINARIA',
    proposed_item_name: 'Veterinaria y alimento para mascotas',
    proposed_attributes_json: { ticketPromedioBob: 180, frecuenciaCompra: 'mensual', devoluciones: 'bajas' },
    ai_suggested: false,
    review_status: 'pending_review',
    review_notes: null,
    created_by_type: 'MERCHANT_OPERATIONS',
  },
  {
    _id: 901505,
    catalog_id: 900101,
    ingestion_job_id: 901401,
    proposed_item_code: 'INFLUENCER_VENTAS',
    proposed_item_name: 'Ventas por redes sociales',
    proposed_attributes_json: { evidencia: '4 menciones' },
    ai_suggested: true,
    review_status: 'rejected',
    review_notes: 'Rechazado: con cuatro menciones no hay cómo estimar ingreso, y se solapa con comerciante minorista.',
    created_by_type: 'MOTOR_SEMANTICO',
  },
];

const DECISIONES = [
  {
    _id: 901601,
    staging_item_id: 901503,
    catalog_version_id: 900204,
    event_type: 'approve',
    decided_at: '2026-09-09T16:05:00Z',
    decision_reason: 'Rubro con volumen suficiente y comportamiento de compra propio; entra en la versión 2026.2 que está en firma.',
  },
  {
    _id: 901602,
    staging_item_id: 901505,
    catalog_version_id: 900202,
    event_type: 'reject',
    decided_at: '2026-09-08T10:20:00Z',
    decision_reason: 'Muestra insuficiente y solapamiento con COMERCIANTE_MINORISTA. Se revisa de nuevo si supera las 50 menciones.',
  },
];

export const ECOSISTEMA: DominioSembrado = {
  nombre: 'ecosistema',
  descripcion: 'Catálogos de contexto: ocupaciones, rubros, entidades financieras, destinos, zonas y motivos de rechazo.',
  bloques: [
    { tabla: 'catalog.context_sources', filas: FUENTES.map((f) => ({ ...f, _created_at: AHORA, _updated_at: AHORA })) },
    { tabla: 'catalog.context_catalogs', filas: CATALOGOS.map((c) => ({ ...c, _created_at: AHORA, _updated_at: AHORA })) },
    {
      tabla: 'catalog.context_catalog_versions',
      filas: VERSIONES.map((v) => ({
        ...v,
        created_by_platform_user_id: null,
        approved_by_platform_user_id: null,
        _created_at: AHORA,
      })),
    },
    {
      tabla: 'catalog.context_items',
      filas: ITEMS.map((i) => ({
        _id: i.id,
        catalog_version_id: i.version,
        item_code: i.code,
        item_name: i.name,
        item_type: i.type,
        attributes_json: i.atributos,
        source_id: i.fuente,
        confidence_score: i.confianza,
        is_active: true,
        _created_at: AHORA,
        _updated_at: AHORA,
      })),
    },
    { tabla: 'catalog.context_item_aliases', filas: ALIAS.map((a) => ({ ...a, _created_at: AHORA })) },
    { tabla: 'catalog.context_risk_mappings', filas: MAPEOS_RIESGO.map((m) => ({ ...m, _created_at: AHORA })) },
    {
      tabla: 'catalog.context_ingestion_jobs',
      filas: TRABAJOS_INGESTA.map((t) => ({ ...t, triggered_by_platform_user_id: null, _created_at: AHORA })),
    },
    {
      tabla: 'catalog.context_staging_items',
      filas: ITEMS_EN_REVISION.map((i) => ({ ...i, created_by_platform_user_id: null, _created_at: AHORA, _updated_at: AHORA })),
    },
    {
      tabla: 'catalog.context_approval_events',
      filas: DECISIONES.map((d) => ({ ...d, decided_by_platform_user_id: null, _created_at: AHORA })),
    },
  ],
};
