/**
 * @file Contratos de la siembra demostrativa del repositorio.
 * @business Esta pieza documenta el recorrido COMPLETO del cliente, endpoint por endpoint.
 * @system define seeders para evolucionar, mapear, sembrar o consultar PostgreSQL de forma controlada.
 */
import type { FlujoDeclarado } from './workflow-catalog-flujos.js';

/**
 * El recorrido del cliente de punta a punta: 21 etapas, 70 endpoints reales.
 *
 * ## Por qué hacía falta
 *
 * El catálogo tenía tres flujos y entre los tres sumaban 49 pasos: el alta, la primera pantalla y
 * un recorrido de crédito que saltaba del registro a la decisión. Lo que quedaba SIN documentar era
 * casi todo lo que el cliente hace de verdad — la captura de domicilio, el perfil financiero, el
 * extracto bancario, las referencias, la encuesta, el paquete de identidad, la revisión del
 * operador, la calificación de riesgo, la línea de crédito, el calendario de pagos, el aviso de
 * pago con su comprobante, las notificaciones, las preferencias, y el ejercicio de derechos sobre
 * los datos personales.
 *
 * Que no estuviera documentado no es un problema de papeles: el catálogo es lo que consume el
 * tablero de flujos del portal y lo que un motor de QA usa para saber qué recorrer. Un flujo que no
 * está aquí no se prueba, no se mide y no aparece cuando alguien pregunta "¿qué hace el cliente?".
 *
 * ## Cómo se armó
 *
 * Cada ruta de aquí abajo se tomó del inventario que publica la aplicación CORRIENDO —las 536 rutas
 * que Nest mapea al arrancar— y no de la documentación previa. El motivo es concreto: el
 * `input_contract_json` del flujo de alta que ya existía decía `{email, phone, channel,
 * documentNumber}` y el Zod real exige `{customer, password, consents, device}` más una cabecera
 * `X-Idempotency-Key` que nadie mencionaba. Un contrato documentado que no coincide con el vigente
 * es peor que no tenerlo: hace perder una tarde a quien confíe en él.
 *
 * ## Lo que este flujo NO afirma
 *
 * Que un cliente recorra las 21 etapas en orden. Muchas son opcionales o dependen de su producto y
 * de su estado, y así están marcadas (`optional`). Lo que afirma es que ÉSTOS son los endpoints del
 * recorrido y en qué momento aparecen. El avance real de una persona lo sigue derivando
 * `CustomerEligibilityService`; este catálogo no lo reimplementa.
 */
export const FLUJO_CLIENTE_COMPLETO: FlujoDeclarado = {
  code: 'customer_full_lifecycle',
  version: 'v1',
  name: 'Ciclo de vida completo del cliente',
  description:
    'Todo lo que un cliente recorre en Atlas, de la primera pantalla al cierre: textos legales, alta, ' +
    'verificación de contacto, identidad, domicilio, perfil financiero, referencias, encuesta, consentimientos, ' +
    'evidencia externa, envío a revisión, decisión del operador, riesgo, elegibilidad, solicitud y decisión de ' +
    'crédito, línea, préstamos y calendario, avisos de pago con comprobante, notificaciones y derechos sobre ' +
    'sus datos personales.',
  processType: 'customer_journey',
  ownerDomain: 'customer_lifecycle',
  success:
    'El cliente queda activo con su expediente completo, su elegibilidad resuelta y —si su producto lo ' +
    'permite— una solicitud de crédito con decisión y una línea vigente.',
  failure:
    'El expediente queda incompleto, la revisión lo rechaza o lo bloquea, el riesgo lo deja fuera de ' +
    'elegibilidad, o la solicitud se rechaza.',
  metadata: { audience: 'app_movil', maintainer: 'customer_lifecycle', inventarioDeRutas: 'derivado de la app corriendo el 21-sep-2026' },
  stages: [
    {
      code: 'legal_preview',
      name: 'Textos legales y capacidades',
      description: 'Lo que la app consulta ANTES de pedir un solo dato: qué se va a consentir y por qué canal se puede verificar.',
      module: 'consents',
      actor: 'customer',
      entry: true,
      steps: [
        {
          code: 'lifecycle.consent_documents',
          name: 'Consentimientos vigentes',
          description: 'Catálogo de documentos de consentimiento activos con su versión. Público: se lee antes de existir como cliente.',
          method: 'GET',
          path: '/consent-documents/active',
          auth: false,
          output: { documentCode: 'string', versionCode: 'string', bodyMarkdown: 'string' },
        },
        {
          code: 'lifecycle.verification_channels',
          name: 'Canales de verificación disponibles',
          description: 'Por dónde se puede verificar el contacto en este despliegue. Evita ofrecer un canal apagado.',
          method: 'GET',
          path: '/customer-onboarding/verification-channels',
          auth: false,
        },
        {
          code: 'lifecycle.survey_catalog',
          name: 'Catálogo de la encuesta de consumo',
          description: 'Preguntas y opciones válidas. Se lee antes para que la app no invente respuestas.',
          method: 'GET',
          path: '/customer-onboarding/consumer-survey/catalog',
          auth: false,
          optional: true,
        },
      ],
    },
    {
      code: 'account_creation',
      name: 'Alta de la cuenta',
      description: 'Crea el cliente, sus credenciales y su primera sesión en una sola transacción.',
      module: 'customer_onboarding',
      actor: 'customer',
      resultingStates: ['registered'],
      steps: [
        {
          code: 'lifecycle.signup',
          name: 'Iniciar el alta',
          description:
            'Crea el cliente en estado registrado, fija su PIN, registra los consentimientos otorgados y da de alta el dispositivo. Devuelve el customerId y la sesión.',
          method: 'POST',
          path: '/customer-onboarding/start',
          auth: false,
          idempotencyKey: true,
          resultingStates: ['registered'],
          // Contrato REAL (`startOnboardingSchema`), no el de la documentación previa.
          input: {
            customer: '{ phone?, email?, firstName?, lastName?, birthDate? } — al menos teléfono o correo',
            password: 'string de 4 dígitos (PIN), rechaza secuencias y repeticiones',
            consents: '[{ consentDocumentId, purposeCode, granted }] — al menos uno',
            device: '{ deviceFingerprintHash (32-128), fingerprintVersion, channel: mobile_app|web_app }',
            permissions: '[{ permissionCode, granted }] — opcional',
          },
          output: {
            customerId: 'string',
            customerCode: 'string',
            lifecycleStatus: 'registered',
            nextStep: 'string',
            tokens: '{ accessToken, refreshToken }',
          },
          errors: ['409 CUSTOMER_ALREADY_EXISTS', '422 VALIDATION_ERROR', '429 RATE_LIMIT_EXCEEDED (10/min por IP)'],
          events: ['customer.registered'],
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.login',
          name: 'Iniciar sesión',
          description:
            'Login del cliente con su identificador y su PIN. Limitado a 10 intentos por minuto y por IP contra la fuerza bruta.',
          method: 'POST',
          path: '/auth/login',
          auth: false,
          input: { actorType: 'customer', identifier: 'correo o teléfono', password: 'PIN' },
          output: { accessToken: 'string', refreshToken: 'string' },
          errors: ['401 INVALID_CREDENTIALS', '423 ACCOUNT_LOCKED', '429 RATE_LIMIT_EXCEEDED'],
        },
        {
          code: 'lifecycle.auth_me',
          name: 'Identidad de la sesión',
          description: 'Quién es el portador del token. Es el oráculo de que la sesión pertenece a ESTA persona y no a otra.',
          method: 'GET',
          path: '/auth/me',
          output: { actorType: 'customer', customerId: 'string', tenantId: 'string' },
        },
        {
          code: 'lifecycle.session_start',
          name: 'Abrir sesión de app',
          description: 'Sesión de aplicación, distinta del token: es la que el heartbeat mantiene viva y la que el operador ve.',
          method: 'POST',
          path: '/customers/:customerId/sessions/start',
          output: { sessionId: 'string', status: 'active' },
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'contact_verification',
      name: 'Verificación de contacto',
      description: 'Alta del método de contacto y confirmación por código de un solo uso. Sólo se guarda el hash del código.',
      module: 'customer_onboarding',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.contact_methods',
          name: 'Registrar método de contacto',
          description: 'Da de alta el teléfono o el correo por el que se va a verificar.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-methods',
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.contact_request',
          name: 'Pedir el código',
          description: 'Emite el código de un solo uso por el canal elegido. Tiene enfriamiento por destino además del límite por IP.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-verification/request',
          errors: ['409 VERIFICATION_RATE_LIMITED'],
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.contact_submit',
          name: 'Confirmar el código',
          description: 'Comprueba el código contra su hash y marca el contacto como verificado.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-verification/submit',
          errors: ['400 INVALID_CODE', '410 CODE_EXPIRED', '429 TOO_MANY_ATTEMPTS'],
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.whatsapp_start',
          name: 'Verificación por WhatsApp — envío',
          description: 'Canal alternativo. Que exista este par no significa que el OTP del backend esté emulado: son cosas distintas.',
          method: 'POST',
          path: '/whatsapp/verification/start',
          optional: true,
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.whatsapp_confirm',
          name: 'Verificación por WhatsApp — confirmación',
          description: 'Confirma el código recibido por WhatsApp.',
          method: 'POST',
          path: '/whatsapp/verification/confirm',
          optional: true,
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'identity_capture',
      name: 'Identidad y documentos',
      description: 'Cédula, selfie y su verificación. Es el bloque con más dato personal del recorrido.',
      module: 'customer_onboarding',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.documents_upload_url',
          name: 'URL firmada para subir documentos',
          description: 'El archivo NO pasa por la API: se sube al almacenamiento con una URL de un solo uso.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/documents/upload-url',
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.identity_package',
          name: 'Paquete de identidad',
          description: 'Documento, extensión, complemento y las imágenes ya subidas, en una sola entrega.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-package',
          idempotencyKey: true,
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.identity_verification',
          name: 'Verificar identidad',
          description: 'Dispara la verificación del documento. Su resultado puede derivar a revisión manual.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-verification',
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.evidence_documents',
          name: 'Documentos de evidencia del expediente',
          description: 'Qué quedó guardado y con qué estado. Es la lectura que el cliente ve de su propio expediente.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/evidence-documents',
          optional: true,
        },
      ],
    },
    {
      code: 'address_capture',
      name: 'Domicilio y geolocalización',
      description: 'Dirección declarada, su posición y las señales de ubicación que la respaldan.',
      module: 'customer_onboarding',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.address_package',
          name: 'Paquete de domicilio',
          description: 'Dirección, referencias y coordenadas declaradas.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/address-package',
          idempotencyKey: true,
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.location_pings',
          name: 'Señales de ubicación',
          description: 'Posiciones capturadas por la app. Sustentan la coherencia del domicilio declarado.',
          method: 'POST',
          path: '/customers/:customerId/location-pings',
          optional: true,
          repeatable: true,
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.address_book',
          name: 'Libreta de direcciones',
          description: 'Direcciones adicionales del cliente: entrega, trabajo.',
          method: 'POST',
          path: '/customers/:customerId/address-book',
          optional: true,
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'financial_profile',
      name: 'Perfil financiero',
      description: 'Ingresos, gastos y capacidad declarada, más el extracto bancario que los respalda.',
      module: 'customer_onboarding',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.financial_profile',
          name: 'Declarar perfil financiero',
          description: 'Ingresos, egresos, dependientes y situación laboral. Entra en la evaluación de capacidad de pago.',
          method: 'PUT',
          path: '/customer-onboarding/:customerId/financial-profile',
        },
        {
          code: 'lifecycle.bank_statement',
          name: 'Subir extracto bancario',
          description: 'Documento que respalda lo declarado. Lo revisa un trabajo de fondo, no el request.',
          method: 'POST',
          path: '/customers/:customerId/bank-statements',
          optional: true,
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.bank_statement_latest',
          name: 'Estado del último extracto',
          description: 'En qué quedó la revisión del extracto. Es el estado que la app muestra al cliente.',
          method: 'GET',
          path: '/customers/:customerId/bank-statements/latest',
          optional: true,
        },
      ],
    },
    {
      code: 'social_capture',
      name: 'Referencias y red de contactos',
      description: 'Personas que responden por el cliente y la instantánea de su libreta, con su consentimiento.',
      module: 'customer_onboarding',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.reference_contacts_add',
          name: 'Agregar referencia',
          description: 'Contacto que responde por el cliente. Es una entidad independiente, no una copia del titular.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/reference-contacts',
          repeatable: true,
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.reference_contacts_list',
          name: 'Referencias registradas',
          description: 'Lo que el expediente tiene hoy. Permite al cliente corregir antes de enviar.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/reference-contacts',
        },
        {
          code: 'lifecycle.contacts_snapshot',
          name: 'Instantánea de la libreta',
          description:
            'Captura de la agenda del dispositivo. Requiere el consentimiento `device_address_book` otorgado: sin él, esta entrega se rechaza.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contacts-snapshot',
          optional: true,
          errors: ['403 CONSENT_REQUIRED'],
          successStatus: [200, 201, 202],
        },
      ],
    },
    {
      code: 'consumer_survey',
      name: 'Encuesta de consumo',
      description: 'Hábitos de gasto declarados. Alimentan la segmentación y la oferta.',
      module: 'customer_onboarding',
      actor: 'customer',
      optional: true,
      steps: [
        {
          code: 'lifecycle.survey_get',
          name: 'Respuestas actuales',
          description: 'Lo que el cliente ya respondió, para poder continuar donde lo dejó.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/consumer-survey',
          optional: true,
        },
        {
          code: 'lifecycle.survey_put',
          name: 'Guardar respuestas',
          description: 'Entrega las respuestas contra el catálogo leído al principio.',
          method: 'PUT',
          path: '/customer-onboarding/:customerId/consumer-survey',
          optional: true,
        },
      ],
    },
    {
      code: 'consents_and_privacy',
      name: 'Consentimientos y privacidad',
      description: 'Decisiones del cliente sobre el uso de sus datos, por propósito y por versión del texto.',
      module: 'customer_privacy',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.consent_decisions',
          name: 'Decidir sobre consentimientos',
          description: 'Otorga o revoca por propósito. Revocar afecta a las consultas POSTERIORES, no borra lo ya observado.',
          method: 'POST',
          path: '/customers/:customerId/privacy/consent-decisions',
          repeatable: true,
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.external_consent',
          name: 'Consentimiento para evidencia externa',
          description: 'Autorización específica para consultar a un proveedor. Sin ella, la política bloquea la consulta ANTES de llamar.',
          method: 'POST',
          path: '/external-data/consents',
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'external_evidence',
      name: 'Evidencia externa',
      description: 'Consulta a proveedores: primero el costo, después la consulta, después las features derivadas.',
      module: 'external_data',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.external_preview',
          name: 'Vista previa de costo',
          description:
            'Cuánto costaría y si la política lo permite. Por contrato NO ejecuta al proveedor: el journal del emulador no debe registrar nada por este paso.',
          method: 'POST',
          path: '/external-data/requests/preview',
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.external_request',
          name: 'Consultar al proveedor',
          description:
            'La consulta real. Su estado de ejecución y el veredicto del proveedor viajan por separado: un MOCKED no es un veredicto.',
          method: 'POST',
          path: '/external-data/requests',
          idempotencyKey: true,
          errors: ['403 CONSENT_REQUIRED', '402 BLOCKED_BY_COST_POLICY', '503 PROVIDER_UNAVAILABLE'],
          events: ['external.request.completed'],
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.external_features',
          name: 'Features derivadas',
          description: 'Lo que el motor de riesgo va a leer. Es la salida normalizada, no la respuesta cruda del proveedor.',
          method: 'GET',
          path: '/external-data/users/:customerId/features',
        },
        {
          code: 'lifecycle.external_observations',
          name: 'Observaciones registradas',
          description: 'Evidencia por observación, con su confianza y si pide revisión manual.',
          method: 'GET',
          path: '/external-data/users/:customerId/observations',
          optional: true,
        },
      ],
    },
    {
      code: 'submission',
      name: 'Envío a revisión',
      description: 'El cliente da por completo su expediente y lo entrega.',
      module: 'customer_onboarding',
      actor: 'customer',
      resultingStates: ['under_review'],
      steps: [
        {
          code: 'lifecycle.submit',
          name: 'Enviar el expediente',
          description: 'Cierra la captura y encola la revisión. Rechaza si quedan bloqueadores obligatorios.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/submit',
          idempotencyKey: true,
          resultingStates: ['under_review'],
          errors: ['409 ONBOARDING_INCOMPLETE'],
          events: ['onboarding.submitted'],
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.status',
          name: 'Estado del onboarding',
          description: 'Dónde va el expediente y qué falta. Es la pantalla de espera del cliente.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/status',
          repeatable: true,
        },
        {
          code: 'lifecycle.observations',
          name: 'Observaciones al cliente',
          description: 'Lo que el operador pidió corregir. Es la vuelta del ciclo, no un estado final.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/observations',
        },
        {
          code: 'lifecycle.workflow_progress',
          name: 'Avance sobre el catálogo de flujos',
          description: 'El avance del cliente derivado de ESTE catálogo. Cierra el círculo: lo documentado es lo que se mide.',
          method: 'GET',
          path: '/customers/:customerId/workflow-progress',
        },
      ],
    },
    {
      code: 'operator_review',
      name: 'Revisión del operador',
      description: 'Un actor DISTINTO del cliente resuelve identidad, cumplimiento y habilitación. Su token no es el del cliente.',
      module: 'operations',
      actor: 'internal_user',
      roles: ['internal_operator', 'compliance_analyst', 'risk_analyst', 'admin'],
      steps: [
        {
          code: 'lifecycle.review_queue',
          name: 'Cola de verificación de contacto pendiente',
          description: 'Lo que el operador tiene por resolver.',
          method: 'GET',
          path: '/operations/customers/pending-contact-verification',
        },
        {
          code: 'lifecycle.identity_decision',
          name: 'Decidir sobre la identidad',
          description: 'Aprueba, rechaza o pide corrección sobre el paquete de identidad.',
          method: 'POST',
          path: '/operations/customers/:customerId/identity-verification/decision',
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.compliance_screening',
          name: 'Tamizaje de cumplimiento',
          description: 'Comprueba al cliente contra listas. Una coincidencia deriva, no rechaza sola.',
          method: 'POST',
          path: '/operations/customers/:customerId/compliance/screening',
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.compliance_clear',
          name: 'Resolver coincidencias',
          description: 'El analista descarta o confirma cada coincidencia, con su motivo.',
          method: 'POST',
          path: '/operations/customers/:customerId/compliance/clear-matches',
          optional: true,
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.investigation_summary',
          name: 'Resumen de investigación',
          description: 'Todo lo que se sabe del cliente en una lectura, para decidir con contexto.',
          method: 'GET',
          path: '/operations/customers/:customerId/investigation-summary',
          optional: true,
        },
        {
          code: 'lifecycle.eligibility_decision',
          name: 'Decidir la habilitación',
          description: 'Habilita al cliente o lo deja observado. Es lo que mueve el estado del ciclo de vida.',
          method: 'POST',
          path: '/operations/customers/:customerId/eligibility/decision',
          resultingStates: ['active', 'observed', 'rejected'],
          events: ['customer.eligibility.decided'],
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'risk_assessment',
      name: 'Riesgo y calificación',
      description: 'Evaluación de riesgo y calificación crediticia con las reglas y la política vigentes.',
      module: 'risk',
      actor: 'system',
      steps: [
        {
          code: 'lifecycle.risk_assessment',
          name: 'Evaluar riesgo',
          description: 'Corre las reglas sobre las features disponibles. El resultado es del backend, no del proveedor.',
          method: 'POST',
          path: '/customers/:customerId/risk-assessments',
          events: ['risk.assessed'],
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.credit_rating_run',
          name: 'Calificar al cliente',
          description: 'Asigna la calificación crediticia con la versión de política vigente.',
          method: 'POST',
          path: '/operations/credit-rating/customers/:customerId/rate',
          roles: ['risk_analyst', 'admin', 'system'],
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.credit_rating_read',
          name: 'Calificación del cliente',
          description: 'La calificación que el cliente ve, con su vigencia.',
          method: 'GET',
          path: '/customers/:customerId/credit-rating',
        },
      ],
    },
    {
      code: 'eligibility',
      name: 'Elegibilidad y oferta',
      description: 'Si el cliente puede pedir crédito y qué productos le corresponden.',
      module: 'credit',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.eligibility',
          name: 'Veredicto de elegibilidad',
          description: 'Elegible o no, y por qué. Un no elegible trae sus bloqueadores; sin ellos, la respuesta está incompleta.',
          method: 'GET',
          path: '/customers/:customerId/eligibility',
          output: { eligible: 'boolean', blockers: '[{ code, detail }]', ruleVersion: 'string' },
        },
        {
          code: 'lifecycle.credit_products',
          name: 'Productos disponibles',
          description:
            'Catálogo filtrado por elegibilidad. Tiene que coincidir con el paso anterior: dos lecturas que se contradicen son un defecto.',
          method: 'GET',
          path: '/customers/:customerId/credit-products',
        },
      ],
    },
    {
      code: 'credit_application',
      name: 'Solicitud de crédito',
      description: 'El cliente pide, dentro de las condiciones que el producto permite.',
      module: 'credit',
      actor: 'customer',
      steps: [
        {
          code: 'lifecycle.credit_apply',
          name: 'Solicitar crédito',
          description:
            'Crea la solicitud. Un rechazo por no elegible es el comportamiento CORRECTO: exigir un 201 aquí sería exigirle al backend que apruebe a quien no corresponde.',
          method: 'POST',
          path: '/customers/:customerId/credit-applications',
          idempotencyKey: true,
          input: {
            productId: 'string decimal positivo',
            requestedAmount: 'number > 0 y <= 99.999.999',
            requestedTermMonths: 'entero 1..360',
            purposeCode: 'string',
          },
          errors: ['403 NOT_ELIGIBLE', '409 APPLICATION_ALREADY_OPEN', '422 VALIDATION_ERROR'],
          events: ['credit.application.created'],
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.credit_applications',
          name: 'Solicitudes del cliente',
          description: 'Verifica el EFECTO: una solicitud creada tiene que aparecer aquí. Un 201 cuyo recurso no aparece es un fallo.',
          method: 'GET',
          path: '/customers/:customerId/credit-applications',
        },
      ],
    },
    {
      code: 'credit_decision',
      name: 'Decisión de crédito',
      description: 'Un operador autorizado decide. El cliente no decide su propio crédito.',
      module: 'operations',
      actor: 'internal_user',
      roles: ['internal_operator', 'risk_analyst', 'admin'],
      steps: [
        {
          code: 'lifecycle.application_detail',
          name: 'Detalle de la solicitud',
          description: 'Lo que el operador lee antes de decidir.',
          method: 'GET',
          path: '/operations/credit/applications/:applicationId',
        },
        {
          code: 'lifecycle.credit_decision',
          name: 'Decidir la solicitud',
          description:
            'Aprueba, rechaza o pide más información. `reject` y `request_more_information` exigen notas: son ramas válidas del proceso, no fallos.',
          method: 'POST',
          path: '/operations/credit/applications/:applicationId/decision',
          input: { decision: 'approve | reject | request_more_information', notes: 'obligatorio salvo en approve' },
          events: ['credit.application.decided'],
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'credit_line',
      name: 'Línea de crédito',
      description: 'El cupo vigente del cliente y su historia.',
      module: 'credit',
      actor: 'customer',
      optional: true,
      steps: [
        {
          code: 'lifecycle.credit_line',
          name: 'Línea vigente',
          description: 'Cupo, disponible y vigencia.',
          method: 'GET',
          path: '/customers/:customerId/credit-line',
          optional: true,
        },
        {
          code: 'lifecycle.credit_line_history',
          name: 'Historia de la línea',
          description: 'Cada movimiento del cupo con su motivo. Es la auditoría que el cliente puede leer.',
          method: 'GET',
          path: '/customers/:customerId/credit-line/history',
          optional: true,
        },
      ],
    },
    {
      code: 'loan_servicing',
      name: 'Préstamos y calendario',
      description: 'Lo que el cliente debe, cuándo y en qué lo gasta.',
      module: 'loans',
      actor: 'customer',
      optional: true,
      steps: [
        {
          code: 'lifecycle.loans',
          name: 'Préstamos del cliente',
          description: 'Cartera vigente con su estado de mora.',
          method: 'GET',
          path: '/customers/:customerId/loans',
          optional: true,
        },
        {
          code: 'lifecycle.payment_calendar',
          name: 'Calendario de pagos',
          description: 'Cuotas, vencimientos y lo que ya está pagado.',
          method: 'GET',
          path: '/customers/:customerId/payment-calendar',
          optional: true,
        },
        {
          code: 'lifecycle.spending_by_category',
          name: 'Gasto por categoría',
          description: 'En qué gastó, agrupado. Alimenta la pantalla de finanzas personales.',
          method: 'GET',
          path: '/customers/:customerId/spending-by-category',
          optional: true,
        },
      ],
    },
    {
      code: 'payment_claims',
      name: 'Avisos de pago',
      description: 'El cliente avisa que pagó y adjunta el comprobante. Avisar no es haber pagado: lo verifica el otro lado.',
      module: 'loan_payment_claims',
      actor: 'customer',
      optional: true,
      steps: [
        {
          code: 'lifecycle.payment_instructions',
          name: 'Instrucciones de pago de la cuota',
          description: 'A dónde y cuánto pagar para ESA cuota.',
          method: 'GET',
          path: '/mobile/customers/:customerId/payment-claims/instructions/:installmentId',
          optional: true,
        },
        {
          code: 'lifecycle.payment_claim',
          name: 'Avisar el pago',
          description: 'Declara el pago con su referencia. Queda PENDIENTE hasta que alguien lo verifica.',
          method: 'POST',
          path: '/mobile/customers/:customerId/payment-claims',
          optional: true,
          idempotencyKey: true,
          events: ['payment.claim.created'],
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.payment_proof',
          name: 'Adjuntar comprobante',
          description: 'La imagen del comprobante, por URL firmada. Es lo que el verificador mira.',
          method: 'POST',
          path: '/mobile/customers/:customerId/payment-claims/proof-tickets',
          optional: true,
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'engagement',
      name: 'Notificaciones y telemetría',
      description: 'Cómo la app se mantiene al día y qué reporta de vuelta.',
      module: 'notifications',
      actor: 'customer',
      optional: true,
      steps: [
        {
          code: 'lifecycle.device_token',
          name: 'Registrar el dispositivo para avisos',
          description: 'Token de notificación push de ESTE dispositivo.',
          method: 'POST',
          path: '/customers/:customerId/device-tokens',
          optional: true,
          successStatus: [200, 201],
        },
        {
          code: 'lifecycle.notification_preferences',
          name: 'Preferencias de aviso',
          description: 'Por qué canal quiere que le avisen y de qué.',
          method: 'PATCH',
          path: '/customers/:customerId/notification-preferences',
          optional: true,
        },
        {
          code: 'lifecycle.unread_count',
          name: 'Avisos sin leer',
          description: 'El número del globo. Es la lectura más frecuente de toda la app.',
          method: 'GET',
          path: '/customers/:customerId/notifications/unread-count',
          repeatable: true,
        },
        {
          code: 'lifecycle.notifications',
          name: 'Bandeja de avisos',
          description: 'Los avisos del cliente, paginados.',
          method: 'GET',
          path: '/customers/:customerId/notifications',
        },
        {
          code: 'lifecycle.notification_read',
          name: 'Marcar como leído',
          description: 'Cierra el aviso para este cliente.',
          method: 'POST',
          path: '/customers/:customerId/notifications/:notificationId/read',
          optional: true,
          successStatus: [200, 201, 204],
        },
        {
          code: 'lifecycle.telemetry',
          name: 'Telemetría de uso',
          description: 'Eventos de interacción por lotes. No lleva dato personal.',
          method: 'POST',
          path: '/customers/:customerId/telemetry/batch',
          optional: true,
          repeatable: true,
          successStatus: [200, 201, 202, 204],
        },
        {
          code: 'lifecycle.session_heartbeat',
          name: 'Latido de sesión',
          description: 'Mantiene viva la sesión de app. Sin él, expira por inactividad.',
          method: 'POST',
          path: '/customers/:customerId/sessions/:sessionId/heartbeat',
          optional: true,
          repeatable: true,
          successStatus: [200, 201, 204],
        },
      ],
    },
    {
      code: 'privacy_exit',
      name: 'Derechos y cierre',
      description: 'Lo que el cliente puede exigir sobre sus datos, y cómo cierra.',
      module: 'customer_privacy',
      actor: 'customer',
      terminal: true,
      steps: [
        {
          code: 'lifecycle.data_subject_request',
          name: 'Ejercer derechos sobre los datos',
          description:
            'Acceso, rectificación, portabilidad o supresión. Es un derecho, no una preferencia: tiene plazo y deja rastro de auditoría.',
          method: 'POST',
          path: '/customers/:customerId/privacy/data-subject-requests',
          optional: true,
          events: ['privacy.data_subject_request.created'],
          successStatus: [200, 201, 202],
        },
        {
          code: 'lifecycle.session_end',
          name: 'Cerrar la sesión de app',
          description: 'Termina la sesión y deja su hora de cierre en el expediente.',
          method: 'POST',
          path: '/customers/:customerId/sessions/:sessionId/end',
          optional: true,
          successStatus: [200, 201, 204],
        },
        {
          code: 'lifecycle.logout',
          name: 'Cerrar sesión',
          description: 'Invalida el refresh token. Con `allDevices`, todos los de esa persona.',
          method: 'POST',
          path: '/auth/logout',
          auth: false,
          input: { refreshToken: 'string', allDevices: 'boolean opcional' },
          successStatus: [200, 201, 204],
        },
      ],
    },
  ],
};
