/**
 * @file Catálogo de referencia que hasta ahora sólo existía en la base de siembra externa.
 * @business Esta pieza preserva la fuente de verdad y la evidencia histórica que soportan decisiones y cumplimiento.
 * @system define seeders para evolucionar, mapear, sembrar o consultar PostgreSQL de forma controlada.
 */
import { refA, type DominioSembrado } from './tipos.js';

/**
 * Estas 340 filas NO son datos de demostración: son el CATÁLOGO con el que el backend funciona.
 *
 * Vivían sólo en la base `seed_atlas` del servidor de desarrollo: una instalación limpia arrancaba
 * sin plantillas de contrato, sin proveedores, sin flujos y sin política de retención, y ninguna
 * pantalla decía por qué estaba vacía.
 *
 * **Ni un solo identificador literal, ni como clave ni como referencia.** Las filas se exportaron
 * de una base concreta, y en cualquier otra las mismas filas existen con OTRO `_id`. Dos
 * despliegues seguidos murieron por esto el 2026-09-17:
 *
 * 1. «duplicate key value violates unique constraint ux_app_content_entries_key» — el upsert por
 *    `_id` insertaba una fila nueva que chocaba contra la clave natural de la que ya estaba.
 * 2. «violates foreign key constraint fk_data_providers_default_retention_policy_id» — la columna
 *    apuntaba al identificador que esa política tenía en la base de origen, y no existe aquí.
 *
 * Por eso cada bloque reconcilia por su clave NATURAL y **toda columna que apunte a otra fila se
 * resuelve con `refA`** por esa misma clave. Lo que no tiene clave natural con la que resolverse
 * —quién publicó un documento de consentimiento— va a NULO antes que a una clave foránea rota: el
 * documento sigue completo sin ese metadato.
 *
 * El ORDEN de los bloques importa y por eso está escrito, no ordenado alfabéticamente: retención y
 * propósitos van primero porque los proveedores y las definiciones de features apuntan ahí.
 *
 * Tres tablas que parecían faltar **no están aquí a propósito**: `messaging.notification_templates`,
 * `risk.rating_policy_versions` y `risk.rating_policy_bands` las instala una MIGRACIÓN —están
 * incluso en la base de TEST sin ninguna siembra—, así que sembrarlas duplicaría.
 *
 * Ninguna contiene datos personales: son configuración, plantillas y definiciones.
 */
export const REFERENCIA: DominioSembrado = {
  nombre: 'referencia',
  descripcion: 'Catálogo de referencia del backend: retención, proveedores, contenido, features, flujos y herramientas.',
  bloques: [
    {
      tabla: 'privacy.retention_policies',
      fundamental: true,
      conflicto: ['policy_code'],
      filas: [
        {
          policy_code: 'external-provider-evidence-1825d',
          applies_to: 'external_provider_evidence',
          retention_days: 1825,
          post_retention_action: 'anonymize',
          legal_basis: 'kyc_aml_record_keeping',
          description:
            'Retención por defecto de la evidencia devuelta por proveedores externos (identidad, buró, telco, banca). Periodo pendiente de confirmación legal por jurisdicción: ATLAS-DATA-001.',
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
        },
        {
          policy_code: 'risk-model-inputs-730d',
          applies_to: 'risk_features_and_score_inputs',
          retention_days: 730,
          post_retention_action: 'aggregate_then_delete',
          legal_basis: 'risk_management_and_model_monitoring',
          description:
            'Features, observaciones y señales usadas para scoring y auditoría de modelo. Periodo pendiente de confirmación legal: ATLAS-DATA-001.',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
        },
        {
          policy_code: 'support_general',
          applies_to: 'support_case',
          retention_days: 1095,
          post_retention_action: 'archive',
          legal_basis: 'Gestión de servicio ISO/IEC 20000-1',
          description: 'Casos de soporte ordinarios: consultas, guía de uso e incidencias técnicas resueltas.',
          is_active: false,
          _created_at: '2026-08-31T11:41:23.286918+00:00',
          _updated_at: null,
        },
        {
          policy_code: 'support_complaint',
          applies_to: 'support_case',
          retention_days: 2555,
          post_retention_action: 'archive',
          legal_basis: 'ISO 10002 y normativa de defensa del consumidor',
          description: 'Reclamos formales, incluida su investigación y la respuesta emitida.',
          is_active: false,
          _created_at: '2026-08-31T11:41:23.28725+00:00',
          _updated_at: null,
        },
        {
          policy_code: 'support_security_incident',
          applies_to: 'support_case',
          retention_days: 2555,
          post_retention_action: 'archive',
          legal_basis: 'ISO/IEC 27035 y política de incidentes',
          description: 'Incidentes de seguridad y reportes de fraude, con su evidencia asociada.',
          is_active: false,
          _created_at: '2026-08-31T11:41:23.287554+00:00',
          _updated_at: null,
        },
        {
          policy_code: 'support_privacy_request',
          applies_to: 'support_case',
          retention_days: 1825,
          post_retention_action: 'archive',
          legal_basis: 'Prueba de atención de derechos del titular',
          description: 'Solicitudes sobre datos personales y la respuesta dada a cada una.',
          is_active: false,
          _created_at: '2026-08-31T11:41:23.287831+00:00',
          _updated_at: null,
        },
        {
          policy_code: 'support_financial_evidence',
          applies_to: 'support_case',
          retention_days: 3650,
          post_retention_action: 'archive',
          legal_basis: 'Conservación de documentación financiera',
          description: 'Casos con comprobantes de pago y conciliación como evidencia.',
          is_active: false,
          _created_at: '2026-08-31T11:41:23.288125+00:00',
          _updated_at: null,
        },
      ],
    },
    {
      tabla: 'privacy.privacy_processing_purposes',
      fundamental: true,
      conflicto: ['purpose_code'],
      filas: [
        {
          purpose_code: 'risk_fraud_assessment',
          purpose_name: 'Evaluación de riesgo y fraude',
          legal_basis: 'explicit_consent',
          description: 'Permite probar consentimientos mínimos para señales de usuario, dispositivo y comportamiento.',
          requires_explicit_consent: true,
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
        },
      ],
    },
    {
      tabla: 'privacy.consent_documents',
      fundamental: true,
      filas: [
        {
          _id: 1,
          _tenant_id: 1,
          document_code: 'privacy-policy-dev',
          version_code: 'v1-dev',
          language: 'es',
          effective_from: '2026-01-01',
          effective_until: null,
          content_url: 'https://atlas.test/legal/privacy-policy-dev',
          content_hash: 'dev_seed_hash_000000000000000000000000000000000000000000000000000001',
          requires_explicit_action: true,
          published_by_internal_user_id: null,
          published_at: '2026-01-01T00:00:00+00:00',
          status: 'published',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          title: null,
          summary: null,
          body_md: null,
        },
        {
          _id: 2,
          _tenant_id: 1,
          document_code: 'device_address_book',
          version_code: 'v1',
          language: 'es',
          effective_from: '2026-09-04',
          effective_until: null,
          content_url: null,
          content_hash: null,
          requires_explicit_action: false,
          published_by_internal_user_id: null,
          published_at: null,
          status: 'published',
          _created_at: '2026-09-05T04:46:22.634865+00:00',
          _updated_at: null,
          title: 'Tus contactos',
          summary: 'Nos autorizas a guardar los contactos de tu teléfono para verificar tu identidad y contactarte. Es opcional.',
          body_md:
            '## Qué autorizas\n\nQue Atlas lea la agenda de tu teléfono y guarde la ficha de cada contacto —nombre, teléfonos,\ncorreos, empresa y cumpleaños— en nuestros servidores, cifrada.\n\n## Para qué la usamos\n\n- Verificar que las referencias que declaras son personas con las que realmente hablas.\n- Detectar solicitudes coordinadas: varias cuentas distintas que se avalan entre sí.\n- Localizarte a ti, a través de tus referencias, si perdemos contacto contigo.\n\n## Qué NO hacemos\n\nNo escribimos a tus contactos, no les ofrecemos productos y no vendemos ni cedemos su\ninformación a terceros.\n\n## Tus contactos son terceros\n\nLas personas de tu agenda no nos autorizaron nada. Por eso guardamos su información cifrada,\ncon el mismo tratamiento que la tuya, y la borramos cuando retiras este permiso.\n\n## Puedes retirarlo cuando quieras\n\nDesde «Privacidad» en la app. Al retirarlo dejamos de sincronizar tu agenda y borramos la que\ntengamos guardada. No afecta a tu línea de crédito ni a las condiciones de tus cuotas.\n\n## Aviso\n\nEsta es una versión genérica en revisión legal.',
        },
        {
          _id: 3,
          _tenant_id: 1,
          document_code: 'location_tracking',
          version_code: 'v1',
          language: 'es',
          effective_from: '2026-09-04',
          effective_until: null,
          content_url: null,
          content_hash: null,
          requires_explicit_action: false,
          published_by_internal_user_id: null,
          published_at: null,
          status: 'published',
          _created_at: '2026-09-05T04:46:22.639761+00:00',
          _updated_at: null,
          title: 'Tu ubicación',
          summary: 'Nos autorizas a registrar tu ubicación periódicamente para prevenir fraude. Es opcional.',
          body_md:
            '## Qué autorizas\n\nQue Atlas registre la ubicación de tu teléfono cada cierto tiempo mientras usas la app y, si\nconcedes el permiso «Siempre», también cuando la app está cerrada.\n\n## Para qué la usamos\n\n- Comprobar que el domicilio que declaras es donde realmente estás.\n- Detectar si alguien usa tu cuenta desde otro lugar.\n- Detectar ubicaciones simuladas, que es la señal más común de una solicitud fraudulenta.\n\n## Qué NO hacemos\n\nNo compartimos tu ubicación con comercios ni con terceros, y no la usamos para publicidad.\n\n## Puedes retirarlo cuando quieras\n\nDesde «Privacidad» en la app, o quitando el permiso desde los ajustes de tu teléfono. Al\nretirarlo dejamos de registrar posiciones nuevas. No afecta a tu línea de crédito ni a las\ncondiciones de tus cuotas.\n\n## Aviso\n\nEsta es una versión genérica en revisión legal.',
        },
      ],
    },
    {
      tabla: 'integrations.data_providers',
      fundamental: true,
      conflicto: ['provider_code'],
      filas: [
        {
          provider_code: 'SEGIP',
          provider_name: 'SEGIP / CGIP Identity Verification',
          provider_type: 'identity',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'IDENTITY',
          provider_status: 'ACTIVE',
          default_mode: 'mock_local',
          requires_consent: true,
          requires_manual_approval: false,
          is_costly: false,
          description: 'Provider base para validación de identidad. CGIP queda como alias operativo, proveedor oficial SEGIP.',
        },
        {
          provider_code: 'INFOCENTER',
          provider_name: 'InfoCenter Credit Bureau',
          provider_type: 'credit_bureau',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'CREDIT_BUREAU',
          provider_status: 'ACTIVE',
          default_mode: 'mock_local',
          requires_consent: true,
          requires_manual_approval: true,
          is_costly: true,
          description: 'Provider caro. Bloqueado por política salvo revisión manual, incremento de línea o fraude.',
        },
        {
          provider_code: 'QR_GENERIC',
          provider_name: 'QR Generic Payment Provider',
          provider_type: 'payments',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'PAYMENTS',
          provider_status: 'MOCK_ONLY',
          default_mode: 'mock_local',
          requires_consent: false,
          requires_manual_approval: false,
          is_costly: false,
          description: 'Provider contractual para fase 2 QR. No es integración real bancaria.',
        },
        {
          provider_code: 'BANKING_GENERIC',
          provider_name: 'Banking Generic Provider',
          provider_type: 'banking',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'BANKING',
          provider_status: 'MOCK_ONLY',
          default_mode: 'mock_local',
          requires_consent: true,
          requires_manual_approval: false,
          is_costly: false,
          description: 'Provider contractual para fase 2 banca general. Los bancos concretos serán mini providers posteriores.',
        },
        {
          provider_code: 'TELCO_GENERIC',
          provider_name: 'Telco Generic Trust Provider',
          provider_type: 'telco',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'TELCO',
          provider_status: 'MOCK_ONLY',
          default_mode: 'mock_local',
          requires_consent: true,
          requires_manual_approval: false,
          is_costly: false,
          description: 'Provider contractual para fase 3 telefonía: antigüedad, actividad y SIM swap si existe API/contrato.',
        },
        {
          provider_code: 'FACEBOOK_META',
          provider_name: 'Facebook / Meta OAuth Trust Provider',
          provider_type: 'social',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'SOCIAL',
          provider_status: 'MOCK_ONLY',
          default_mode: 'mock_local',
          requires_consent: true,
          requires_manual_approval: false,
          is_costly: false,
          description: 'Provider voluntario por OAuth/API oficial. No scraping, no contraseñas, no antigüedad inventada.',
        },
        {
          provider_code: 'WHATSAPP_GENERIC',
          provider_name: 'WhatsApp Generic Contactability Provider',
          provider_type: 'messaging',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'MESSAGING',
          provider_status: 'MOCK_ONLY',
          default_mode: 'mock_local',
          requires_consent: true,
          requires_manual_approval: false,
          is_costly: false,
          description: 'Provider contractual para OTP/contactabilidad. No leer chats ni guardar contactos.',
        },
        {
          provider_code: 'DIGITAL_TRUST_GENERIC',
          provider_name: 'Digital Trust Generic Provider',
          provider_type: 'digital_trust',
          reliability_score: 90.0,
          supports_retro_data: false,
          default_retention_policy_id: refA('privacy.retention_policies', { policy_code: 'external-provider-evidence-1825d' }),
          is_active: true,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          provider_category: 'DIGITAL_TRUST',
          provider_status: 'MOCK_ONLY',
          default_mode: 'mock_local',
          requires_consent: true,
          requires_manual_approval: false,
          is_costly: false,
          description: 'Provider contractual para reputación digital, identidad sintética, email/IP/device risk.',
        },
      ],
    },
    {
      tabla: 'integrations.external_provider_cost_policies',
      fundamental: true,
      conflicto: ['provider_id', 'query_type'],
      filas: [
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'SEGIP' }),
          query_type: 'IDENTITY_VERIFICATION',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'LOW',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['ONBOARDING', 'CREDIT_APPLICATION', 'MANUAL_REVIEW'],
          requires_manual_approval: false,
          requires_admin_role: false,
          block_by_default: false,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 86400,
          feature_ttl_seconds: 604800,
          retry_max_attempts: 1,
          retry_backoff_seconds: 30,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'INFOCENTER' }),
          query_type: 'CREDIT_REPORT',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'HIGH',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['MANUAL_REVIEW', 'LIMIT_INCREASE', 'FRAUD_REVIEW'],
          requires_manual_approval: true,
          requires_admin_role: true,
          block_by_default: true,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 2592000,
          feature_ttl_seconds: 2592000,
          retry_max_attempts: 0,
          retry_backoff_seconds: 0,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'INFOCENTER' }),
          query_type: 'CREDIT_SCORE',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'HIGH',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['MANUAL_REVIEW', 'LIMIT_INCREASE', 'FRAUD_REVIEW'],
          requires_manual_approval: true,
          requires_admin_role: true,
          block_by_default: true,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 2592000,
          feature_ttl_seconds: 2592000,
          retry_max_attempts: 0,
          retry_backoff_seconds: 0,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'QR_GENERIC' }),
          query_type: 'PAYMENT_VERIFICATION',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'LOW',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['PAYMENT_RECONCILIATION', 'CREDIT_APPLICATION'],
          requires_manual_approval: false,
          requires_admin_role: false,
          block_by_default: false,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 0,
          feature_ttl_seconds: 86400,
          retry_max_attempts: 1,
          retry_backoff_seconds: 15,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'BANKING_GENERIC' }),
          query_type: 'BANK_TRANSFER_VERIFICATION',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'LOW',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['PAYMENT_RECONCILIATION'],
          requires_manual_approval: false,
          requires_admin_role: false,
          block_by_default: false,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 0,
          feature_ttl_seconds: 86400,
          retry_max_attempts: 1,
          retry_backoff_seconds: 15,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'TELCO_GENERIC' }),
          query_type: 'PHONE_TRUST_CHECK',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'MEDIUM',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['ONBOARDING', 'FRAUD_REVIEW', 'MANUAL_REVIEW'],
          requires_manual_approval: false,
          requires_admin_role: false,
          block_by_default: false,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 604800,
          feature_ttl_seconds: 604800,
          retry_max_attempts: 1,
          retry_backoff_seconds: 30,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'FACEBOOK_META' }),
          query_type: 'SOCIAL_TRUST_CHECK',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'FREE',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['ONBOARDING', 'MANUAL_REVIEW'],
          requires_manual_approval: false,
          requires_admin_role: false,
          block_by_default: false,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 604800,
          feature_ttl_seconds: 604800,
          retry_max_attempts: 0,
          retry_backoff_seconds: 0,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'WHATSAPP_GENERIC' }),
          query_type: 'WHATSAPP_OTP_VERIFICATION',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'LOW',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['ONBOARDING', 'CONTACTABILITY'],
          requires_manual_approval: false,
          requires_admin_role: false,
          block_by_default: false,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 0,
          feature_ttl_seconds: 86400,
          retry_max_attempts: 0,
          retry_backoff_seconds: 0,
        },
        {
          provider_id: refA('integrations.data_providers', { provider_code: 'DIGITAL_TRUST_GENERIC' }),
          query_type: 'DIGITAL_TRUST_CHECK',
          unit_cost_amount: 0.0,
          currency: 'BOB',
          cost_tier: 'HIGH',
          max_queries_per_user_per_day: 1,
          max_queries_per_user_per_month: 2,
          max_queries_global_per_day: 100,
          allowed_decision_stages_json: ['MANUAL_REVIEW', 'FRAUD_REVIEW'],
          requires_manual_approval: true,
          requires_admin_role: true,
          block_by_default: true,
          active: true,
          active_from: '2026-01-01T00:00:00+00:00',
          active_to: null,
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-01-01T00:00:00+00:00',
          cache_ttl_seconds: 604800,
          feature_ttl_seconds: 604800,
          retry_max_attempts: 0,
          retry_backoff_seconds: 0,
        },
      ],
    },
    {
      tabla: 'catalog.catalog_entries',
      fundamental: true,
      conflicto: ['catalog_code', 'catalog_version', 'entry_code'],
      filas: [
        {
          catalog_code: 'risk_bands',
          catalog_version: 1,
          entry_code: 'risk_band_excellent',
          entry_name: 'Excelente',
          entry_attributes: { mdr_pct: 0, risk_level: 'low', score_range: { max: 100, min: 80 } },
          is_active: true,
          is_immutable_after_use: true,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'risk_bands',
          catalog_version: 1,
          entry_code: 'risk_band_good',
          entry_name: 'Bueno',
          entry_attributes: { mdr_pct: 0.5, risk_level: 'medium', score_range: { max: 79, min: 60 } },
          is_active: true,
          is_immutable_after_use: true,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'risk_bands',
          catalog_version: 1,
          entry_code: 'risk_band_fair',
          entry_name: 'Regular',
          entry_attributes: { mdr_pct: 1, risk_level: 'medium_high', score_range: { max: 59, min: 40 } },
          is_active: true,
          is_immutable_after_use: true,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'risk_bands',
          catalog_version: 1,
          entry_code: 'risk_band_poor',
          entry_name: 'Bajo',
          entry_attributes: { mdr_pct: 2.5, risk_level: 'high', score_range: { max: 39, min: 0 } },
          is_active: true,
          is_immutable_after_use: true,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'income_brackets',
          catalog_version: 1,
          entry_code: 'income_0_500',
          entry_name: 'Menos de 500 BOB',
          entry_attributes: { range_max: 500, range_min: 0, income_band: 'very_low', risk_band_default: 'poor' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'income_brackets',
          catalog_version: 1,
          entry_code: 'income_500_1000',
          entry_name: '500 a 1000 BOB',
          entry_attributes: { range_max: 1000, range_min: 500, income_band: 'low', risk_band_default: 'fair' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'income_brackets',
          catalog_version: 1,
          entry_code: 'income_1000_3000',
          entry_name: '1000 a 3000 BOB',
          entry_attributes: { range_max: 3000, range_min: 1000, income_band: 'medium', risk_band_default: 'good' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'income_brackets',
          catalog_version: 1,
          entry_code: 'income_3000_plus',
          entry_name: '3000+ BOB',
          entry_attributes: { range_max: 999999, range_min: 3000, income_band: 'high', risk_band_default: 'excellent' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'city_zones_scz',
          catalog_version: 1,
          entry_code: 'scz_centro',
          entry_name: 'Centro',
          entry_attributes: { lat_approx: -17.7833, lng_approx: -63.1821, risk_segment: 'urban_core', commerce_density: 'high' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'city_zones_scz',
          catalog_version: 1,
          entry_code: 'scz_sur',
          entry_name: 'Sur',
          entry_attributes: { lat_approx: -17.8333, lng_approx: -63.1821, risk_segment: 'suburban', commerce_density: 'medium' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'city_zones_scz',
          catalog_version: 1,
          entry_code: 'scz_norte',
          entry_name: 'Norte',
          entry_attributes: { lat_approx: -17.75, lng_approx: -63.1821, risk_segment: 'suburban', commerce_density: 'medium' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
        {
          catalog_code: 'city_zones_scz',
          catalog_version: 1,
          entry_code: 'scz_este',
          entry_name: 'Este',
          entry_attributes: { lat_approx: -17.7833, lng_approx: -63.15, risk_segment: 'urban_growth', commerce_density: 'low' },
          is_active: true,
          is_immutable_after_use: false,
          usage_count: 0,
          created_by_platform_user_id: null,
          created_at: '2026-01-02T03:00:00+00:00',
          superseded_by_version_id: null,
          _created_at: '2026-01-02T03:00:00+00:00',
          _updated_at: '2026-01-02T03:00:00+00:00',
        },
      ],
    },
    {
      tabla: 'catalog.attribute_definitions',
      fundamental: true,
      conflicto: ['attribute_code'],
      filas: [
        {
          attribute_code: 'employment_status',
          attribute_name: 'Situación laboral declarada',
          entity_scope: 'customer',
          data_type: 'text',
          risk_dimension: 'capacity',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'internal',
          requires_consent: true,
          is_sensitive: false,
          is_model_candidate: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: true,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'employer_name',
          attribute_name: 'Empleador declarado',
          entity_scope: 'customer',
          data_type: 'text',
          risk_dimension: 'capacity',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'sensitive_financial',
          requires_consent: true,
          is_sensitive: true,
          is_model_candidate: false,
          allowed_for_credit_decision: false,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'employment_seniority_months',
          attribute_name: 'Antigüedad laboral en meses',
          entity_scope: 'customer',
          data_type: 'number',
          risk_dimension: 'stability',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'internal',
          requires_consent: true,
          is_sensitive: false,
          is_model_candidate: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: true,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'monthly_income_declared',
          attribute_name: 'Ingreso mensual declarado',
          entity_scope: 'customer',
          data_type: 'number',
          risk_dimension: 'capacity',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'sensitive_financial',
          requires_consent: true,
          is_sensitive: true,
          is_model_candidate: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: true,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'other_monthly_income',
          attribute_name: 'Otros ingresos mensuales declarados',
          entity_scope: 'customer',
          data_type: 'number',
          risk_dimension: 'capacity',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'sensitive_financial',
          requires_consent: true,
          is_sensitive: true,
          is_model_candidate: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: true,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'monthly_expenses_declared',
          attribute_name: 'Egresos mensuales declarados',
          entity_scope: 'customer',
          data_type: 'number',
          risk_dimension: 'capacity',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'sensitive_financial',
          requires_consent: true,
          is_sensitive: true,
          is_model_candidate: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: true,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'economic_activity_code',
          attribute_name: 'Actividad económica declarada',
          entity_scope: 'customer',
          data_type: 'text',
          risk_dimension: 'profile',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'internal',
          requires_consent: true,
          is_sensitive: false,
          is_model_candidate: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: true,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'economic_activity_other',
          attribute_name: 'Actividad económica declarada (texto libre de «Otra actividad»)',
          entity_scope: 'customer',
          data_type: 'text',
          risk_dimension: 'profile',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'internal',
          requires_consent: true,
          is_sensitive: false,
          is_model_candidate: false,
          allowed_for_credit_decision: false,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: true,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
        {
          attribute_code: 'source_of_funds',
          attribute_name: 'Origen de fondos declarado',
          entity_scope: 'customer',
          data_type: 'text',
          risk_dimension: 'compliance',
          source_type: 'customer_declared',
          availability_stage: 'onboarding',
          build_phase: 'phase_1',
          data_classification_code: 'sensitive_financial',
          requires_consent: true,
          is_sensitive: true,
          is_model_candidate: false,
          allowed_for_credit_decision: false,
          allowed_for_fraud_decision: false,
          legal_review_status: 'pending_review',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: null,
          is_active: true,
          _created_at: '2026-07-28T00:00:00+00:00',
          _updated_at: '2026-07-28T00:00:00+00:00',
          owner_team: 'risk',
          domain_code: 'customer_financial_profile',
          review_status: 'approved',
        },
      ],
    },
    {
      tabla: 'catalog.app_content_entries',
      fundamental: true,
      conflicto: ['_tenant_id', 'surface', 'content_key', 'locale'],
      predicado: '_deleted = false',
      filas: [
        {
          _tenant_id: 1,
          surface: 'legal',
          content_key: 'permisos.cabecera',
          locale: 'es-BO',
          title: 'Dos permisos, y para qué',
          subtitle:
            'Atlas presta dinero sin pedirte garantías. Estas dos señales son parte de lo que nos permite hacerlo. Puedes decir que no y abrir tu cuenta igual.',
          body_md: null,
          bullets_json: null,
          metadata_json: { eyebrow: 'Antes de empezar' },
          action_kind: null,
          action_label: null,
          action_value: null,
          display_order: 10,
          is_active: true,
          published_at: '2026-09-05T04:46:22.641964+00:00',
          updated_by_internal_user_id: null,
          _created_at: '2026-09-05T04:46:22.641964+00:00',
          _updated_at: '2026-09-05T04:46:22.641964+00:00',
          _deleted: false,
        },
        {
          _tenant_id: 1,
          surface: 'legal',
          content_key: 'permisos.ubicacion',
          locale: 'es-BO',
          title: 'Tu ubicación',
          subtitle: null,
          body_md: 'No la compartimos con los comercios ni la usamos para publicidad.',
          bullets_json: [
            { text: 'Comprobar que el domicilio que declaras es donde realmente estás.' },
            { text: 'Avisarte si alguien usa tu cuenta desde otro lugar.' },
            { text: 'Detectar ubicaciones simuladas, la señal más común de una solicitud falsa.' },
          ],
          metadata_json: null,
          action_kind: null,
          action_label: null,
          action_value: null,
          display_order: 20,
          is_active: true,
          published_at: '2026-09-05T04:46:22.644241+00:00',
          updated_by_internal_user_id: null,
          _created_at: '2026-09-05T04:46:22.644241+00:00',
          _updated_at: '2026-09-05T04:46:22.644241+00:00',
          _deleted: false,
        },
        {
          _tenant_id: 1,
          surface: 'legal',
          content_key: 'permisos.contactos',
          locale: 'es-BO',
          title: 'Tus contactos',
          subtitle: null,
          body_md: 'No les escribimos, no les ofrecemos nada y no vendemos su información.',
          bullets_json: [
            { text: 'Verificar que las referencias que das son personas con las que hablas.' },
            { text: 'Detectar varias cuentas distintas que se avalan entre sí.' },
            { text: 'Poder ubicarte a través de tus referencias si perdemos contacto contigo.' },
          ],
          metadata_json: null,
          action_kind: null,
          action_label: null,
          action_value: null,
          display_order: 30,
          is_active: true,
          published_at: '2026-09-05T04:46:22.64451+00:00',
          updated_by_internal_user_id: null,
          _created_at: '2026-09-05T04:46:22.64451+00:00',
          _updated_at: '2026-09-05T04:46:22.64451+00:00',
          _deleted: false,
        },
        {
          _tenant_id: 1,
          surface: 'legal',
          content_key: 'permisos.aviso',
          locale: 'es-BO',
          title: null,
          subtitle: null,
          body_md:
            'Tu teléfono te va a preguntar por cada permiso. Si eliges «Siempre» en la ubicación, también la registramos con la app cerrada; si eliges «Mientras uso la app», solo mientras la tienes abierta. Puedes cambiarlo cuando quieras desde «Privacidad» o desde los ajustes de tu teléfono.',
          bullets_json: null,
          metadata_json: null,
          action_kind: null,
          action_label: null,
          action_value: null,
          display_order: 40,
          is_active: true,
          published_at: '2026-09-05T04:46:22.644748+00:00',
          updated_by_internal_user_id: null,
          _created_at: '2026-09-05T04:46:22.644748+00:00',
          _updated_at: '2026-09-05T04:46:22.644748+00:00',
          _deleted: false,
        },
        {
          _tenant_id: 1,
          surface: 'legal',
          content_key: 'permisos.siempre',
          locale: 'es-BO',
          title: '¿También con la app cerrada?',
          subtitle: 'Ya puedes seguir. Esto solo añade una señal más, y puedes decir que no sin que cambie nada de tu cuenta.',
          body_md:
            'Registramos tu ubicación cada cierto tiempo aunque no tengas la app abierta. Sirve para lo mismo: comprobar tu domicilio y detectar si alguien usa tu cuenta desde otro lugar.',
          bullets_json: null,
          metadata_json: { eyebrow: 'Un paso más, opcional' },
          action_kind: null,
          action_label: null,
          action_value: null,
          display_order: 50,
          is_active: true,
          published_at: '2026-09-05T04:46:22.644976+00:00',
          updated_by_internal_user_id: null,
          _created_at: '2026-09-05T04:46:22.644976+00:00',
          _updated_at: '2026-09-05T04:46:22.644976+00:00',
          _deleted: false,
        },
      ],
    },
    {
      tabla: 'risk.feature_definitions',
      fundamental: true,
      conflicto: ['feature_code'],
      filas: [
        {
          feature_code: 'feat_verified_net_income_monthly_bob',
          feature_name: 'Ingreso neto mensual verificado (BOB)',
          feature_family: 'affordability',
          risk_dimension: 'capacity',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_essential_expenses_monthly_bob',
          feature_name: 'Gastos esenciales mensuales declarados/verificados (BOB)',
          feature_family: 'affordability',
          risk_dimension: 'capacity',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_existing_debt_service_monthly_bob',
          feature_name: 'Servicio mensual de deuda existente (BOB)',
          feature_family: 'affordability',
          risk_dimension: 'capacity',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_bnpl_active_loan_count',
          feature_name: 'Operaciones BNPL activas conocidas',
          feature_family: 'exposure',
          risk_dimension: 'indebtedness',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_bnpl_provider_count_90d',
          feature_name: 'Proveedores BNPL observados en 90 días',
          feature_family: 'exposure',
          risk_dimension: 'indebtedness',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_bnpl_monthly_installment_bob',
          feature_name: 'Nueva carga mensual BNPL propuesta (BOB)',
          feature_family: 'affordability',
          risk_dimension: 'capacity',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_residual_income_after_credit_bob',
          feature_name: 'Ingreso residual después de gastos y deudas (BOB)',
          feature_family: 'affordability',
          risk_dimension: 'capacity',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_total_debt_service_ratio',
          feature_name: 'Cuota total de deuda sobre ingreso neto',
          feature_family: 'affordability',
          risk_dimension: 'capacity',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_recent_payment_failures_30d',
          feature_name: 'Intentos de cobro fallidos en 30 días',
          feature_family: 'repayment',
          risk_dimension: 'financial_difficulty',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_financial_hardship_active',
          feature_name: 'Dificultad financiera o reprogramación activa',
          feature_family: 'forbearance',
          risk_dimension: 'financial_difficulty',
          data_type: 'boolean',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_refund_dispute_open',
          feature_name: 'Devolución o disputa de compra abierta',
          feature_family: 'consumer_protection',
          risk_dimension: 'servicing',
          data_type: 'boolean',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
        {
          feature_code: 'feat_merchant_refund_rate_90d',
          feature_name: 'Tasa de devoluciones del comercio en 90 días',
          feature_family: 'merchant',
          risk_dimension: 'merchant_risk',
          data_type: 'number',
          availability_tier: 'production_baseline',
          build_phase: 'MVP',
          data_classification_code: 'RISK_SENSITIVE',
          calculation_kind: 'deterministic_or_verified_source',
          default_missing_strategy: 'manual_review_if_missing',
          is_model_input: false,
          is_policy_rule_input: true,
          is_sensitive: true,
          allowed_for_credit_decision: true,
          allowed_for_fraud_decision: false,
          legal_review_status: 'requires_local_compliance_validation',
          prohibited_reason_code: null,
          fairness_review_required: false,
          retention_policy_id: refA('privacy.retention_policies', { policy_code: 'risk-model-inputs-730d' }),
          owner_team: 'risk',
          is_active: true,
          _created_at: '2026-07-11T00:00:00+00:00',
          _updated_at: '2026-07-11T00:00:00+00:00',
          domain_code: null,
          review_status: 'NEEDS_REVIEW',
        },
      ],
    },
    /*
     * C-7 (2026-09-25): aquí se sembraba un modelo (`atlas_bnpl_application_score`), un ruleset
     * (`atlas_mvp_onboarding_ruleset`) y siete reglas con `assessment_type: 'onboarding_credit'`, un
     * valor que NO existe en el enum de evaluación (`onboarding_initial`, `behavior_update`,
     * `manual_recheck`, `fraud_recheck`), y con condiciones sobre features `feat_*` que ningún código
     * produce. `findActiveRuleset` filtra por tipo de evaluación, así que jamás casaba: un escalón
     * intermedio de la cadena MOTOR → ruleset → heurística que parecía existir y no podía decidir
     * nada. Se borra en vez de «arreglarle» el tipo: sus reglas hablan de un contrato de features que
     * no existe, y darle un tipo válido lo habría hecho casar con reglas sin datos.
     */
    {
      tabla: 'platform_ops.system_tool_catalog',
      fundamental: true,
      conflicto: ['code'],
      filas: [
        {
          code: 'DECISION_ENGINE',
          name: 'ATLAS Decision Engine',
          type: 'DECISION_SERVICE',
          provider: 'ATLAS',
          purpose: 'Motor de políticas versionadas que decide crédito, riesgo y fraude.',
          required_env_vars: ['DECISION_ENGINE_HEALTH_BASE_URL'],
          has_sandbox: true,
          healthcheck_route: '/health',
          requires_credentials: true,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'Riesgo y Decisión',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.08404+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'ERP_BACKEND',
          name: 'ATLAS ERP Backend',
          type: 'BUSINESS_SERVICE',
          provider: 'ATLAS',
          purpose: 'Backend de administración, inventario y facturación del ecosistema.',
          required_env_vars: ['ERP_BACKEND_BASE_URL'],
          has_sandbox: true,
          healthcheck_route: '/api/v1/health',
          requires_credentials: false,
          is_critical: false,
          status: 'ACTIVE',
          owner_team: 'Plataforma ERP',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.090492+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'POSTGRES',
          name: 'PostgreSQL',
          type: 'DATABASE',
          provider: null,
          purpose: 'Base transaccional principal de Atlas.',
          required_env_vars: ['DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER', 'DB_PASSWORD'],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: true,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.091693+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'SEQUELIZE',
          name: 'Sequelize ORM',
          type: 'DATABASE_ORM',
          provider: null,
          purpose: 'ORM y registro de modelos del backend.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.093262+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'REDIS',
          name: 'Redis',
          type: 'CACHE',
          provider: null,
          purpose: 'Cache distribuida y base para rate limit/token cache.',
          required_env_vars: ['REDIS_URL'],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.09441+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'NEST_THROTTLER_REDIS',
          name: 'Nest Throttler Redis Storage',
          type: 'RATE_LIMIT',
          provider: null,
          purpose: 'Rate limiting distribuido por Redis.',
          required_env_vars: ['REDIS_URL'],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.095696+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'JWT',
          name: 'JSON Web Tokens',
          type: 'AUTH',
          provider: null,
          purpose: 'Autenticación de usuarios y sesiones.',
          required_env_vars: ['JWT_ACCESS_TOKEN_SECRET'],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: true,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.09685+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'ARGON2',
          name: 'Argon2',
          type: 'CRYPTO',
          provider: null,
          purpose: 'Hash seguro de contraseñas.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.09789+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'ZOD',
          name: 'Zod',
          type: 'VALIDATION',
          provider: null,
          purpose: 'Validación de DTOs y contratos de entrada.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.098893+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'OUTBOX_EVENTS_DB',
          name: 'Outbox DB-backed',
          type: 'OUTBOX',
          provider: null,
          purpose: 'Eventos y jobs internos persistidos en base de datos.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.09993+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'IDEMPOTENCY_KEYS_DB',
          name: 'Idempotency Keys DB',
          type: 'IDEMPOTENCY',
          provider: null,
          purpose: 'Control de idempotencia para comandos críticos.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.100818+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'OPERATIONAL_AUDIT_LOGS',
          name: 'Operational Audit Logs',
          type: 'OBSERVABILITY',
          provider: null,
          purpose: 'Auditoría operacional compatible con el backend actual.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.10185+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'SYSTEM_ACTION_LOGS',
          name: 'System Action Logs',
          type: 'OBSERVABILITY',
          provider: null,
          purpose: 'Auditoría HTTP enriquecida por request, endpoint y correlación.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: true,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.103083+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'ARCHIVO_LOG_MONGO_SYNC',
          name: 'Archivo.log → MongoDB Sync',
          type: 'OBSERVABILITY',
          provider: 'mongodb',
          purpose:
            'ArchivoLogMongoSyncService: único proceso del backend que corre por su cuenta (setInterval en onApplicationBootstrap, cada LOG_SYNC_INTERVAL_MS) — copia los bytes nuevos de Archivo.log (escrito por AppFileLogger) a una colección MongoDB append-only, sin intervención HTTP.',
          required_env_vars: ['MONGO_DB_URL_CONNECTION'],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'ACTIVE',
          owner_team: 'backend',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.104391+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: true,
        },
        {
          code: 'JEST',
          name: 'Jest',
          type: 'TESTING',
          provider: null,
          purpose: 'Pruebas unitarias y de integración del repositorio.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.105604+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'SMOKE_SCRIPTS',
          name: 'Smoke scripts',
          type: 'TESTING',
          provider: null,
          purpose: 'Pruebas smoke existentes en scripts/smoke.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.106686+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'OPENAPI_SWAGGER',
          name: 'Swagger/OpenAPI',
          type: 'OBSERVABILITY',
          provider: null,
          purpose: 'Contrato de documentación técnica de la API.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'ACTIVE',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.107719+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'SEGIP_CGIP',
          name: 'SEGIP/CGIP',
          type: 'EXTERNAL_PROVIDER',
          provider: null,
          purpose: 'Validación externa de identidad cuando exista contrato.',
          required_env_vars: ['SEGIP_BASE_URL', 'SEGIP_API_KEY'],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: true,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.108674+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'INFOCENTER',
          name: 'InfoCenter',
          type: 'EXTERNAL_PROVIDER',
          provider: null,
          purpose: 'Buró crediticio costoso y gobernado por política.',
          required_env_vars: ['INFOCENTER_BASE_URL', 'INFOCENTER_API_KEY'],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: true,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.109652+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'QR_GENERIC',
          name: 'QR Generic Provider',
          type: 'EXTERNAL_PROVIDER',
          provider: null,
          purpose: 'Proveedor contractual para validación de QR en fase posterior.',
          required_env_vars: [],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.110589+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'BANKING_GENERIC',
          name: 'Banking Generic Provider',
          type: 'EXTERNAL_PROVIDER',
          provider: null,
          purpose: 'Proveedor contractual para validación bancaria futura.',
          required_env_vars: [],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.111909+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'TELCO_GENERIC',
          name: 'Telco Generic Provider',
          type: 'EXTERNAL_PROVIDER',
          provider: null,
          purpose: 'Proveedor contractual para señales telco futuras.',
          required_env_vars: [],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.113707+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'FACEBOOK_META',
          name: 'Facebook/Meta OAuth',
          type: 'EXTERNAL_PROVIDER',
          provider: null,
          purpose: 'Proveedor social voluntario mediante OAuth/API oficial.',
          required_env_vars: [],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.115199+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'WHATSAPP_GENERIC',
          name: 'WhatsApp Generic',
          type: 'NOTIFICATION',
          provider: null,
          purpose: 'Proveedor contractual para contacto y comunicación WhatsApp.',
          required_env_vars: [],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.116473+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'DIGITAL_TRUST_GENERIC',
          name: 'Digital Trust Generic',
          type: 'EXTERNAL_PROVIDER',
          provider: null,
          purpose: 'Reputación digital, identidad sintética y señales email/IP/device.',
          required_env_vars: [],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.117571+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'BULLMQ',
          name: 'BullMQ',
          type: 'QUEUE',
          provider: null,
          purpose: 'Colas Redis futuras; actualmente no instalado y catalogado como planificado.',
          required_env_vars: ['REDIS_URL'],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.118736+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'AWS_SQS',
          name: 'AWS SQS',
          type: 'QUEUE',
          provider: null,
          purpose: 'Alternativa futura de colas administradas.',
          required_env_vars: [],
          has_sandbox: false,
          healthcheck_route: null,
          requires_credentials: false,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.120165+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
        {
          code: 'S3_OR_OBJECT_STORAGE',
          name: 'S3/Object Storage',
          type: 'STORAGE',
          provider: null,
          purpose: 'Almacenamiento futuro de evidencias, KYC y comprobantes.',
          required_env_vars: ['AWS_REGION', 'AWS_S3_BUCKET'],
          has_sandbox: true,
          healthcheck_route: null,
          requires_credentials: true,
          is_critical: false,
          status: 'PLANNED',
          owner_team: 'systems',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.121606+00:00',
          description: null,
          business_value: null,
          technical_usage: null,
          audit_notes: null,
          failure_risks: null,
          is_worker: false,
        },
      ],
    },
    {
      tabla: 'platform_ops.system_stress_profiles',
      fundamental: true,
      conflicto: ['code'],
      // El catálogo de endpoints lo llena un descubrimiento que necesita la API corriendo; en una
      // base recién migrada está vacío y estos perfiles no tienen a qué apuntar. Se omiten y se
      // dice cuántas, en vez de tumbar la siembra entera por un bloque accesorio.
      omitirFilaSiNoResuelve: true,
      filas: [
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'GET',
            full_path: '/api/v1/health',
          }),
          code: 'STRESS_HEALTH',
          name: 'Healthcheck concurrente',
          target_rps: 80,
          duration_seconds: 60,
          concurrency: 40,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 400,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.126221+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'POST',
            full_path: '/api/v1/auth/login',
          }),
          code: 'STRESS_AUTH_LOGIN',
          name: 'Login externo bajo carga controlada',
          target_rps: 25,
          duration_seconds: 60,
          concurrency: 20,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 900,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.130088+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'POST',
            full_path: '/api/v1/internal/auth/login',
          }),
          code: 'STRESS_INTERNAL_AUTH_LOGIN',
          name: 'Login panel interno bajo carga',
          target_rps: 20,
          duration_seconds: 60,
          concurrency: 15,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 900,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.131673+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'POST',
            full_path: '/api/v1/customer-onboarding/start',
          }),
          code: 'STRESS_CUSTOMER_ONBOARDING_START',
          name: 'Onboarding start bajo carga',
          target_rps: 10,
          duration_seconds: 60,
          concurrency: 10,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 1500,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.133002+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'POST',
            full_path: '/api/v1/customers/:customerId/risk-assessments',
          }),
          code: 'STRESS_CUSTOMERS_BY_CUSTOMERID_RISK_ASSESSMENTS',
          name: 'Risk assessment sintético',
          target_rps: 5,
          duration_seconds: 60,
          concurrency: 5,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 1800,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.134665+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'GET',
            full_path: '/api/v1/operations/work-queue',
          }),
          code: 'STRESS_OPERATIONS_WORK_QUEUE',
          name: 'Work queue lectura concurrente',
          target_rps: 30,
          duration_seconds: 60,
          concurrency: 20,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 900,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.136301+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'GET',
            full_path: '/api/v1/systems/endpoints',
          }),
          code: 'STRESS_SYSTEMS_ENDPOINTS',
          name: 'Catálogo endpoints lectura concurrente',
          target_rps: 35,
          duration_seconds: 60,
          concurrency: 20,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 900,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.137887+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'GET',
            full_path: '/api/v1/systems/data-entities',
          }),
          code: 'STRESS_SYSTEMS_DATA_ENTITIES',
          name: 'Catálogo entidades lectura concurrente',
          target_rps: 25,
          duration_seconds: 60,
          concurrency: 15,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 1000,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.1396+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'GET',
            full_path: '/api/v1/operations/catalogs',
          }),
          code: 'STRESS_OPERATIONS_CATALOGS',
          name: 'Catálogos negocio lectura concurrente',
          target_rps: 25,
          duration_seconds: 60,
          concurrency: 15,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 1000,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.141582+00:00',
        },
        {
          endpoint_id: refA('platform_ops.system_endpoint_catalog', {
            system_code: 'ATLAS_BACKEND',
            method: 'GET',
            full_path: '/api/v1/external-data/providers/health',
          }),
          code: 'STRESS_EXTERNAL_DATA_PROVIDERS_HEALTH',
          name: 'Salud proveedores lectura concurrente',
          target_rps: 20,
          duration_seconds: 60,
          concurrency: 10,
          environment_scope: ['LOCAL', 'STAGING'],
          max_error_rate: 0.02,
          max_p95_ms: 1000,
          is_enabled: true,
          requires_approval: true,
          status: 'ACTIVE',
          notes: 'Perfil semilla seguro; requiere aprobación antes de ejecutar carga real.',
          created_by: 'system_seed',
          updated_by: 'system_seed',
          _created_at: '2026-01-01T00:00:00+00:00',
          _updated_at: '2026-09-18T01:16:20.143267+00:00',
        },
      ],
    },
    // Los procesos (`workflow_*`) ya no se siembran: se declaran en código
    // (`src/modules/workflow-catalog/definitions/`) y los vuelca la migración `sync-workflow-catalog-N`,
    // también en bases sin siembra demo. Ver plan de procesos 2026-09-26, T1.2.
  ],
};
