/**
 * @file Las suites de prueba del portal y sus pasos, que hasta ahora sólo existían en una base.
 * @business Esta pieza preserva la fuente de verdad y la evidencia histórica que soportan decisiones y cumplimiento.
 * @system define seeders para evolucionar, mapear, sembrar o consultar PostgreSQL de forma controlada.
 */
import type { FilaSembrada } from './tipos.js';

/**
 * Seis suites y veintisiete pasos, trasladados del conjunto publicado al repositorio.
 *
 * Vivían sólo en la base de siembra: una instalación limpia se quedaba sin una sola suite y la
 * consola de QA del portal aparecía vacía sin que nada lo explicara. Se reconcilian por su `code`,
 * así que en una base que ya las tiene esto no duplica nada — las actualiza.
 */
export const SUITES_DE_PRUEBA: readonly FilaSembrada[] = [
  {
    code: 'SMOKE_CORE_READINESS',
    name: 'Smoke base del backend',
    description: 'Valida que el backend, catálogos y cliente demo estén listos para arrancar pruebas manuales del portal.',
    module: 'core',
    suite_type: 'SMOKE',
    execution_mode: 'SYNC_OR_JOB',
    environment_scope: ['LOCAL', 'STAGING', 'PRODUCTION_READONLY'],
    is_enabled: true,
    requires_seed_data: true,
    is_safe_for_production: true,
    requires_destructive_permission: false,
    created_by: 'system_seed',
  },
  {
    code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    name: 'Portal administrativo de sistemas',
    description: 'Cubre las vistas base: dashboard, endpoints, herramientas, entidades, review queue, suites y perfiles de stress.',
    module: 'systems',
    suite_type: 'REGRESSION',
    execution_mode: 'SYNC_OR_JOB',
    environment_scope: ['LOCAL', 'STAGING'],
    is_enabled: true,
    requires_seed_data: true,
    is_safe_for_production: false,
    requires_destructive_permission: false,
    created_by: 'system_seed',
  },
  {
    code: 'OPERATIONS_WORK_QUEUE_READINESS',
    name: 'Operaciones y casos demo',
    description: 'Valida cola operativa, revisión manual, fraude, auditoría y calidad de datos con registros semilla.',
    module: 'operations',
    suite_type: 'REGRESSION',
    execution_mode: 'SYNC_OR_JOB',
    environment_scope: ['LOCAL', 'STAGING'],
    is_enabled: true,
    requires_seed_data: true,
    is_safe_for_production: false,
    requires_destructive_permission: false,
    created_by: 'system_seed',
  },
  {
    code: 'CATALOG_RISK_GOVERNANCE_READINESS',
    name: 'Catálogos, riesgo y gobierno',
    description: 'Valida que existan catálogos, definiciones, políticas de riesgo y políticas de gobierno para poblar el portal.',
    module: 'catalog_management',
    suite_type: 'REGRESSION',
    execution_mode: 'SYNC_OR_JOB',
    environment_scope: ['LOCAL', 'STAGING'],
    is_enabled: true,
    requires_seed_data: true,
    is_safe_for_production: false,
    requires_destructive_permission: false,
    created_by: 'system_seed',
  },
  {
    code: 'EXTERNAL_PROVIDERS_READINESS',
    name: 'Proveedores externos y mocks',
    description: 'Valida proveedores Bolivia/mock, health, readiness y auditorías de idempotencia/retención/sanitización.',
    module: 'external_data',
    suite_type: 'INTEGRATION',
    execution_mode: 'SYNC_OR_JOB',
    environment_scope: ['LOCAL', 'STAGING'],
    is_enabled: true,
    requires_seed_data: true,
    is_safe_for_production: false,
    requires_destructive_permission: false,
    created_by: 'system_seed',
  },
  {
    code: 'NOTIFICATIONS_READINESS',
    name: 'Notificaciones operaciones/cliente',
    description: 'Valida plantillas, mensajes y preferencias con datos semilla.',
    module: 'notifications',
    suite_type: 'REGRESSION',
    execution_mode: 'SYNC_OR_JOB',
    environment_scope: ['LOCAL', 'STAGING'],
    is_enabled: true,
    requires_seed_data: true,
    is_safe_for_production: false,
    requires_destructive_permission: false,
    created_by: 'system_seed',
  },
];

/** Cada paso dice a qué suite pertenece por CÓDIGO; el escritor resuelve el identificador. */
export const PASOS_DE_PRUEBA: readonly (FilaSembrada & { suite_code: string })[] = [
  {
    suite_code: 'SMOKE_CORE_READINESS',
    step_order: 1,
    name: 'Health',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/health',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'SMOKE_CORE_READINESS',
    step_order: 2,
    name: 'Consentimientos activos',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/consent-documents/active?language=es',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'SMOKE_CORE_READINESS',
    step_order: 3,
    name: 'Cliente demo',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/customers/1/me',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    step_order: 1,
    name: 'Dashboard sistemas',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/systems/dashboard',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    step_order: 2,
    name: 'Catálogo endpoints',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/systems/endpoints?page=1&limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    step_order: 3,
    name: 'Catálogo entidades',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/systems/data-entities?page=1&limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    step_order: 4,
    name: 'Catálogo herramientas',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/systems/tools?page=1&limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    step_order: 5,
    name: 'Cola de revisión',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/systems/review-queue',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    step_order: 6,
    name: 'Suites de prueba',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/systems/test-suites',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'PORTAL_ADMIN_SYSTEMS_READINESS',
    step_order: 7,
    name: 'Perfiles stress',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/systems/stress-profiles',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'OPERATIONS_WORK_QUEUE_READINESS',
    step_order: 1,
    name: 'Work queue',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/work-queue?queue=all&page=1&limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'OPERATIONS_WORK_QUEUE_READINESS',
    step_order: 2,
    name: 'Casos manuales',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/manual-review-cases?limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'OPERATIONS_WORK_QUEUE_READINESS',
    step_order: 3,
    name: 'Casos fraude',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/fraud-cases?limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'OPERATIONS_WORK_QUEUE_READINESS',
    step_order: 4,
    name: 'Resumen investigación',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/customers/1/investigation-summary',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'OPERATIONS_WORK_QUEUE_READINESS',
    step_order: 5,
    name: 'Calidad de datos',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/data-quality/issues?page=1&limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'CATALOG_RISK_GOVERNANCE_READINESS',
    step_order: 1,
    name: 'Catálogos',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/catalogs',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'CATALOG_RISK_GOVERNANCE_READINESS',
    step_order: 2,
    name: 'Definiciones',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/definitions?type=all&status=all',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'CATALOG_RISK_GOVERNANCE_READINESS',
    step_order: 3,
    name: 'Risk policy',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/risk-policy/current',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'CATALOG_RISK_GOVERNANCE_READINESS',
    step_order: 4,
    name: 'Gobierno datos',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/data-governance/policies',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'EXTERNAL_PROVIDERS_READINESS',
    step_order: 1,
    name: 'Lista proveedores',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/external-data',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'EXTERNAL_PROVIDERS_READINESS',
    step_order: 2,
    name: 'Health proveedores',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/external-data/providers/health',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'EXTERNAL_PROVIDERS_READINESS',
    step_order: 3,
    name: 'Readiness',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/external-data/readiness',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'EXTERNAL_PROVIDERS_READINESS',
    step_order: 4,
    name: 'Quality audit',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/external-data/quality-audit',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'NOTIFICATIONS_READINESS',
    step_order: 1,
    name: 'Plantillas',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/notifications/templates',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'NOTIFICATIONS_READINESS',
    step_order: 2,
    name: 'Mensajes',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/notifications/messages?page=1&limit=20',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'NOTIFICATIONS_READINESS',
    step_order: 3,
    name: 'Preferencias cliente',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/operations/notifications/preferences/1',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
  {
    suite_code: 'NOTIFICATIONS_READINESS',
    step_order: 4,
    name: 'Notificaciones cliente',
    input_mode: 'DEFAULT',
    method: 'GET',
    path_template: '/api/v1/customers/1/notifications',
    default_headers: {
      'x-tenant-id': '1',
      authorization: 'Bearer {{accessToken}}',
    },
    default_payload: {},
    config_schema: {},
    extractors: {},
    assertions: {
      statusIn: [200],
    },
    continue_on_failure: false,
    cleanup_required: false,
  },
];
