/**
 * @file Datos del dominio: nombres y apellidos de las personas sintéticas QA.
 * @business Esta pieza hace que una corrida de cien personas no parezca diez clones: nombres y
 *   apellidos reales y frecuentes en Bolivia, sin que ninguna combinación identifique a nadie (el
 *   documento, el correo y el teléfono salen de rangos que no se emiten).
 * @system listas congeladas: cambiarlas cambia personas, así que va con `PERSONA_GENERATOR_VERSION`.
 */

/**
 * Nombres de pila comunes en Bolivia, separados por sexo: el sexo se sortea primero y el nombre se
 * saca de SU lista, así que nunca sale una «Mariela» con sexo M. Incluye nombres compuestos, que
 * son la norma en el padrón y ejercitan los campos con espacio.
 */
export const NOMBRES_F = [
  'Ana',
  'Carla',
  'Mariela',
  'Fabiola',
  'Rosa',
  'Noelia',
  'María',
  'Juana',
  'Lucía',
  'Patricia',
  'Gabriela',
  'Daniela',
  'Silvia',
  'Verónica',
  'Ximena',
  'Paola',
  'Claudia',
  'Wara',
  'Sonia',
  'Elizabeth',
  'Carmen',
  'Luz',
  'Roxana',
  'Ruth',
  'Miriam',
  'Jhoselin',
  'Nayra',
  'Teresa',
  'Beatriz',
  'Andrea',
  'Valeria',
  'Micaela',
  'María René',
  'Ana Belén',
  'Julia',
  'Norma',
  'Mónica',
  'Inés',
] as const;
export const NOMBRES_M = [
  'Luis',
  'Jorge',
  'Ramiro',
  'Diego',
  'Iván',
  'Marco',
  'Juan',
  'Carlos',
  'José',
  'Mario',
  'Freddy',
  'Wilson',
  'Edwin',
  'Fernando',
  'Rodrigo',
  'Álvaro',
  'Gonzalo',
  'Víctor',
  'René',
  'Hugo',
  'Óscar',
  'Mauricio',
  'Pablo',
  'Sergio',
  'Javier',
  'Grover',
  'Limbert',
  'Wilmer',
  'Rubén',
  'Franz',
  'Rolando',
  'Nelson',
  'Juan Carlos',
  'José Luis',
  'Miguel Ángel',
  'Alejandro',
  'Daniel',
  'Eduardo',
] as const;

/** Apellidos frecuentes del padrón boliviano: aimaras, quechuas y castellanos. */
export const APELLIDOS = [
  'Quispe',
  'Mamani',
  'Chávez',
  'Rojas',
  'Vargas',
  'Condori',
  'Salazar',
  'Terceros',
  'Flores',
  'Arce',
  'Choque',
  'Huanca',
  'Limachi',
  'Ticona',
  'Apaza',
  'Callisaya',
  'Poma',
  'Colque',
  'Cruz',
  'Gutiérrez',
  'Fernández',
  'López',
  'Mendoza',
  'Gonzales',
  'Rodríguez',
  'Pérez',
  'García',
  'Guzmán',
  'Torrez',
  'Suárez',
  'Justiniano',
  'Áñez',
  'Paz',
  'Soliz',
  'Villarroel',
  'Montaño',
  'Zurita',
  'Aguilar',
  'Castro',
  'Ortiz',
  'Ramos',
  'Medina',
  'Morales',
  'Pinto',
  'Velasco',
  'Siles',
  'Ríos',
  'Zeballos',
  'Nina',
  'Yujra',
  'Laura',
  'Copa',
  'Alanoca',
  'Tarqui',
  'Calle',
  'Blanco',
  'Méndez',
  'Vaca',
  'Coca',
  'Céspedes',
  'Durán',
  'Herrera',
  'Machaca',
  'Sirpa',
] as const;
