/**
 * @file Modelos de la PLATAFORMA: catálogo del sistema, flujos y acceso interno.
 * @business Esta pieza preserva la fuente de verdad y la evidencia histórica que soportan decisiones y cumplimiento.
 * @system enumera los modelos que Sequelize registra para este grupo.
 */
import {
  SystemJobRunModel,
  AuthCredentialModel,
  AuthRefreshTokenModel,
  AuthOneTimeCodeModel,
  AppContentEntryModel,
  SystemEndpointCatalogModel,
  SystemBlockFederationStateModel,
  SystemToolCatalogModel,
  SystemEndpointToolRequirementModel,
  SystemDataEntityCatalogModel,
  SystemEndpointDataEntityImpactModel,
  SystemEndpointFieldImpactModel,
  SystemTestSuiteModel,
  SystemTestStepModel,
  SystemTestRunModel,
  SystemTestStepRunModel,
  DataNotebookQueryHistoryModel,
  DataNotebookDocumentModel,
  SystemActionLogModel,
  SystemStressProfileModel,
  SystemFlowCatalogModel,
  SystemScreenCatalogModel,
  SystemFlowFindingModel,
  SystemFlowImportModel,
  SystemDomainCatalogModel,
  SystemEndpointPayloadContractModel,
  SystemDataFieldCatalogModel,
  SystemDataRelationshipCatalogModel,
  SystemOperationalRuleCatalogModel,
  SystemCatalogReviewEventModel,
  WorkflowDefinitionModel,
  WorkflowStageModel,
  WorkflowStepModel,
  WorkflowStepDependencyModel,
  WorkflowTransitionModel,
  ExpedienteModel,
  ExpedienteNodoModel,
  ExpedienteConcesionModel,
  ExpedienteActividadModel,
  ExpedienteTicketSubidaModel,
} from './models/index.js';

/**
 * La otra mitad: el catálogo de systems-ops y su federación, la bitácora de acciones, las
 * definiciones de flujo y el RBAC interno. Es lo que describe al propio sistema, frente a
 * `business-models.ts`, que describe a sus clientes.
 */
// AT-018: los modelos de Mensajería viven en su propio registro (notification-models.ts); no se duplican aquí.
export const PLATFORM_MODELS = [
  SystemJobRunModel,
  AuthCredentialModel,
  AuthRefreshTokenModel,
  AuthOneTimeCodeModel,
  AppContentEntryModel,
  SystemEndpointCatalogModel,
  SystemBlockFederationStateModel,
  SystemToolCatalogModel,
  SystemEndpointToolRequirementModel,
  SystemDataEntityCatalogModel,
  SystemEndpointDataEntityImpactModel,
  SystemEndpointFieldImpactModel,
  SystemTestSuiteModel,
  SystemTestStepModel,
  SystemTestRunModel,
  SystemTestStepRunModel,
  DataNotebookQueryHistoryModel,
  DataNotebookDocumentModel,
  SystemActionLogModel,
  SystemStressProfileModel,
  SystemFlowCatalogModel,
  SystemScreenCatalogModel,
  SystemFlowFindingModel,
  SystemFlowImportModel,
  SystemDomainCatalogModel,
  SystemEndpointPayloadContractModel,
  SystemDataFieldCatalogModel,
  SystemDataRelationshipCatalogModel,
  SystemOperationalRuleCatalogModel,
  SystemCatalogReviewEventModel,
  WorkflowDefinitionModel,
  WorkflowStageModel,
  WorkflowStepModel,
  WorkflowStepDependencyModel,
  WorkflowTransitionModel,
  ExpedienteModel,
  ExpedienteNodoModel,
  ExpedienteConcesionModel,
  ExpedienteActividadModel,
  ExpedienteTicketSubidaModel,
];
