export type TableBusinessMetadata = {
  className: string;
  tableName: string;
  domainCode: string;
  stereotypes?: string | null;
  priority?: string | null;
  whatIs?: string | null;
  whatDoes?: string | null;
  relationships?: string | null;
};
export type DomainBusinessMetadata = {
  domainCode: string;
  domainName: string;
  dataNature: string;
  description: string;
  businessDefinition: string;
  technicalScope: string;
  ownerTeam: string;
  regulatoryNotes: string;
  exampleTables: string[];
  decisionUseCases: string[];
  auditRelevance: string;
};
export type LogicalRelationshipMetadata = {
  sourceClass: string;
  targetClass: string;
  sourceTable: string;
  targetTable: string;
  relationshipType: string;
  businessReason: string;
  technicalReason: string;
  auditUsage: string;
  analysisUsage: string;
  decisionUsage: string;
  cardinality?: string;
  optionality?: string;
};
export const TABLE_BUSINESS_METADATA: TableBusinessMetadata[] = [
  {
    className: 'Tenant',
    stereotypes: 'platform-root',
    priority: 'MVP',
    whatIs: 'Raiz de multitenencia de la plataforma.',
    whatDoes:
      'Define cada entidad operativa o ambiente comercial que usa Atlas. Permite separar datos, reglas, configuraciones y auditoria por tenant o pais.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'tenants',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'PlatformUser',
    stereotypes: 'platform-root',
    priority: 'Fase 1',
    whatIs: 'Usuario administrador de plataforma.',
    whatDoes:
      'Representa usuarios globales de Atlas que pueden operar configuraciones cross-tenant, catalogos compartidos o gobierno corporativo.',
    relationships: 'sale a OperationalAuditLog (platform_actions); sale a DataChangeLog (platform_changes).',
    tableName: 'platform_users',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'InternalUser',
    stereotypes: 'core',
    priority: 'MVP',
    whatIs: 'Usuario interno del tenant.',
    whatDoes: 'Gestiona personal operativo de cada tenant: analistas, compliance, soporte, operaciones, riesgo y administradores locales.',
    relationships: 'sale a DataChangeLog (changes); sale a OperationalAuditLog (actions).',
    tableName: 'internal_users',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'RetentionPolicy',
    stereotypes: 'catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Catalogo de politicas de retencion.',
    whatDoes:
      'Centraliza cuanto tiempo se conserva cada tipo de dato y que accion se aplica al vencimiento: anonimizar, borrar, archivar o retener por obligacion legal.',
    relationships:
      'sale a DataProviderResponse (applies_to); sale a EvidenceDocument (applies_to); sale a ObservationDefinition (applies_to); sale a AttributeDefinition (applies_to); sale a FeatureDefinition (applies_to); sale a SensitiveFieldRule (retention).',
    tableName: 'retention_policies',
    domainCode: 'PRIVACIDAD',
  },
  {
    className: 'DataProvider',
    stereotypes: 'catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Catalogo de proveedores externos.',
    whatDoes: 'Registra servicios externos como KYC, buró, reputacion IP, validacion documental, telecom u otros enriquecimientos.',
    relationships: 'sale a DataProviderRequest (receives).',
    tableName: 'data_providers',
    domainCode: 'PROVEEDORES',
  },
  {
    className: 'DataProviderRequest',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Bitacora de consultas a proveedores.',
    whatDoes: 'Guarda cada llamada saliente a un proveedor externo para trazabilidad, idempotencia, costos, latencia y auditoria.',
    relationships: 'recibe de DataProvider (receives).',
    tableName: 'data_provider_requests',
    domainCode: 'PROVEEDORES',
  },
  {
    className: 'DataProviderResponse',
    stereotypes: 'append-only, privacy',
    priority: 'MVP',
    whatIs: 'Respuesta de proveedor externo.',
    whatDoes:
      'Conserva la respuesta cruda o redactada segun politica de privacidad. Es clave para reconstruir por que se aprobo, rechazo o escalo una decision.',
    relationships: 'recibe de RetentionPolicy (applies_to).',
    tableName: 'data_provider_responses',
    domainCode: 'PROVEEDORES',
  },
  {
    className: 'Customer',
    stereotypes: 'core, privacy',
    priority: 'MVP',
    whatIs: 'Entidad central del cliente.',
    whatDoes:
      'Representa la cuenta base del consumidor sin meterle datos pesados. Guarda identificadores estables y contacto primario protegido.',
    relationships:
      'sale a DataSubjectRequest (privacy_requests); sale a EvidenceDocument (provides); sale a CustomerActivitySummary (activity_projection); sale a RiskAssessmentRun (assessed_when_known); sale a FraudCase (fraud_cases); sale a WatchlistMatch (watchlist_hits).',
    tableName: 'customers',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'CustomerStatusEvent',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Historial de cambios de estado del cliente.',
    whatDoes: 'Registra cada paso del ciclo de vida del cliente, por ejemplo pending_kyc, active, blocked o closed_by_user.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'customer_status_events',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'CustomerProfileVersion',
    stereotypes: 'versioned, append-only',
    priority: 'MVP',
    whatIs: 'Version historica del perfil personal.',
    whatDoes:
      'Guarda nombres, fecha de nacimiento, idioma y preferencias como version, no como dato sobrescrito. Permite reconstruir el perfil al momento de una decision.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'customer_profile_versions',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'CustomerIdentityDocument',
    stereotypes: 'versioned, append-only, privacy',
    priority: 'MVP',
    whatIs: 'Documento de identidad versionado.',
    whatDoes: 'Modela CI, pasaporte u otro documento, con numero cifrado y hash. Conecta OCR, evidencias y estado de verificacion KYC.',
    relationships: 'sale a IdentityVerificationAttempt (verified_by); sale a EvidenceDocument (front_back).',
    tableName: 'customer_identity_documents',
    domainCode: 'IDENTIDAD_KYC',
  },
  {
    className: 'IdentityVerificationAttempt',
    stereotypes: 'append-only, privacy',
    priority: 'MVP',
    whatIs: 'Intento de verificacion de identidad.',
    whatDoes: 'Registra cada intento KYC: liveness, match de selfie, forense documental, proveedor usado, resultado y razones.',
    relationships: 'sale a EvidenceDocument (selfie); recibe de CustomerIdentityDocument (verified_by).',
    tableName: 'identity_verification_attempts',
    domainCode: 'IDENTIDAD_KYC',
  },
  {
    className: 'CustomerContactMethod',
    stereotypes: 'core, privacy',
    priority: 'MVP',
    whatIs: 'Metodos de contacto del cliente.',
    whatDoes: 'Almacena telefonos, emails u otros canales de contacto con privacidad por diseno, estado de verificacion y fuente.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'customer_contact_methods',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'ContactVerificationAttempt',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Intentos de verificacion de contacto.',
    whatDoes: 'Documenta OTP, validacion por proveedor, confirmacion de email o verificacion manual de cada canal.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'contact_verification_attempts',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'CustomerAddress',
    stereotypes: 'core',
    priority: 'MVP',
    whatIs: 'Direccion logica del cliente.',
    whatDoes:
      'Agrupa las versiones de una direccion de domicilio, trabajo, facturacion u otra. El contenido se guarda en CustomerAddressVersion.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'customer_addresses',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'CustomerAddressVersion',
    stereotypes: 'versioned, append-only',
    priority: 'MVP',
    whatIs: 'Version del texto de direccion.',
    whatDoes: 'Mantiene cada cambio de direccion, zona, ciudad, prueba documental y verificacion sin perder historico.',
    relationships: 'sale a AddressGpsObservation (gps_checks); sale a EvidenceDocument (proof).',
    tableName: 'customer_address_versions',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'AddressGpsObservation',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Observacion GPS contra direccion declarada.',
    whatDoes:
      'Registra coordenadas y distancia al domicilio declarado para validar consistencia geografica y detectar fraude o datos falsos.',
    relationships: 'recibe de CustomerAddressVersion (gps_checks).',
    tableName: 'address_gps_observations',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'CustomerReferenceContact',
    stereotypes: 'core, privacy',
    priority: 'MVP',
    whatIs: 'Contacto de referencia.',
    whatDoes: 'Guarda un contacto secundario para contactabilidad y recuperabilidad, sin convertirlo automaticamente en garante legal.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'customer_reference_contacts',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'PrivacyProcessingPurpose',
    stereotypes: 'catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Catalogo de finalidades de tratamiento.',
    whatDoes: 'Define para que se procesa cada dato: KYC, antifraude, scoring, marketing, notificaciones, soporte, etc.',
    relationships: 'sale a CustomerConsent (purpose).',
    tableName: 'privacy_processing_purposes',
    domainCode: 'PRIVACIDAD',
  },
  {
    className: 'ConsentDocument',
    stereotypes: 'versioned',
    priority: 'MVP',
    whatIs: 'Version legal de un documento de consentimiento.',
    whatDoes: 'Representa terminos, politica de privacidad, autorizacion de buró u otros textos legales publicados por version e idioma.',
    relationships: 'recibe de CustomerConsent (references_version).',
    tableName: 'consent_documents',
    domainCode: 'IDENTIDAD_KYC',
  },
  {
    className: 'CustomerConsent',
    stereotypes: 'versioned',
    priority: 'MVP',
    whatIs: 'Consentimiento vigente o historico del cliente.',
    whatDoes: 'Registra si el cliente otorgo o revoco un consentimiento especifico, con evidencia de canal, IP, dispositivo y sesion.',
    relationships:
      'sale a ConsentDocument (references_version); recibe de PrivacyProcessingPurpose (purpose); recibe de OnDeviceComputationRun (authorized_by).',
    tableName: 'customer_consents',
    domainCode: 'PRIVACIDAD',
  },
  {
    className: 'ConsentEvent',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Evento de consentimiento.',
    whatDoes: 'Bitacora inmutable de acciones sobre consentimiento: otorgado, revocado, renovado, expirado o actualizado.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'consent_events',
    domainCode: 'PRIVACIDAD',
  },
  {
    className: 'DataClassificationPolicy',
    stereotypes: 'catalog, platform-shared, privacy',
    priority: 'MVP',
    whatIs: 'Politica de clasificacion de datos.',
    whatDoes: 'Clasifica datos por sensibilidad y define almacenamiento permitido: plano, cifrado, hash, redactado o no almacenado.',
    relationships: 'sale a SensitiveFieldRule (protects).',
    tableName: 'data_classification_policies',
    domainCode: 'PRIVACIDAD',
  },
  {
    className: 'SensitiveFieldRule',
    stereotypes: 'catalog, platform-shared, privacy',
    priority: 'MVP',
    whatIs: 'Regla por campo sensible.',
    whatDoes:
      'Traduce la politica de privacidad a campos concretos de tablas: como se almacena, como se busca, como se enmascara y quien accede.',
    relationships: 'recibe de DataClassificationPolicy (protects); recibe de RetentionPolicy (retention).',
    tableName: 'sensitive_field_rules',
    domainCode: 'PRIVACIDAD',
  },
  {
    className: 'DataSubjectRequest',
    stereotypes: 'case, privacy',
    priority: 'MVP',
    whatIs: 'Solicitud del titular de datos.',
    whatDoes: 'Gestiona solicitudes de acceso, rectificacion, eliminacion, oposicion o portabilidad de datos personales.',
    relationships: 'recibe de Customer (privacy_requests).',
    tableName: 'data_subject_requests',
    domainCode: 'PRIVACIDAD',
  },
  {
    className: 'EvidenceDocument',
    stereotypes: 'core, privacy',
    priority: 'MVP',
    whatIs: 'Archivo de evidencia.',
    whatDoes:
      'Representa documentos, fotos, selfies, comprobantes o archivos subidos a almacenamiento seguro, sin guardar binarios en la base.',
    relationships:
      'recibe de RetentionPolicy (applies_to); recibe de Customer (provides); recibe de CustomerIdentityDocument (front_back); recibe de CustomerAddressVersion (proof); recibe de IdentityVerificationAttempt (selfie).',
    tableName: 'evidence_documents',
    domainCode: 'IDENTIDAD_KYC',
  },
  {
    className: 'EvidenceExtraction',
    stereotypes: 'append-only, privacy',
    priority: 'MVP',
    whatIs: 'Extraccion automatizada de evidencia.',
    whatDoes:
      'Guarda OCR, lectura de campos, metadatos o resultados de IA extraidos desde un archivo, con confianza y version de extractor.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'evidence_extractions',
    domainCode: 'IDENTIDAD_KYC',
  },
  {
    className: 'EvidenceReview',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Revision humana de evidencia.',
    whatDoes: 'Registra correcciones, aprobaciones o rechazos de documentos revisados manualmente.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'evidence_reviews',
    domainCode: 'IDENTIDAD_KYC',
  },
  {
    className: 'GlobalDeviceFingerprint',
    stereotypes: 'platform-shared',
    priority: 'Fase 1',
    whatIs: 'Huella global de dispositivo.',
    whatDoes: 'Permite detectar reutilizacion de un mismo dispositivo entre tenants o paises, sin depender solo del cliente local.',
    relationships: 'sale a Device (tenant_instances).',
    tableName: 'global_device_fingerprints',
    domainCode: 'DISPOSITIVO',
  },
  {
    className: 'Device',
    stereotypes: 'core',
    priority: 'MVP',
    whatIs: 'Dispositivo observado dentro del tenant.',
    whatDoes: 'Representa un telefono o navegador identificado por fingerprint dentro de un tenant. Es base para antifraude y confianza.',
    relationships:
      'sale a CustomerSession (used_in); sale a RiskAssessmentRun (assessed_device); sale a FraudCase (linked_device); sale a WatchlistMatch (device_hits); recibe de GlobalDeviceFingerprint (tenant_instances); recibe de OnDeviceComputationRun (computed_on); recibe de FeatureComputationRun (optional_subject).',
    tableName: 'devices',
    domainCode: 'DISPOSITIVO',
  },
  {
    className: 'CustomerDeviceLink',
    stereotypes: 'core',
    priority: 'MVP',
    whatIs: 'Relacion cliente-dispositivo.',
    whatDoes: 'Indica que cliente uso que dispositivo, si es primario, el nivel de confianza y sesiones donde se observo.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'customer_device_links',
    domainCode: 'DISPOSITIVO',
  },
  {
    className: 'DeviceSnapshot',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Foto tecnica del dispositivo.',
    whatDoes: 'Congela marca, modelo, sistema operativo, valor estimado, root, emulador o VPN al momento de una sesion o decision.',
    relationships: 'sale a FeatureLineageLink (source).',
    tableName: 'device_snapshots',
    domainCode: 'DISPOSITIVO',
  },
  {
    className: 'DeviceRiskEvent',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Evento de riesgo del dispositivo.',
    whatDoes: 'Registra cambios de riesgo por el dispositivo: marcado sospechoso, rehabilitado, asociado a fraude o bloqueado.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'device_risk_events',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'SimObservation',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Observacion de SIM y linea telefonica.',
    whatDoes: 'Captura carrier, tipo de SIM, cantidad de chips, antiguedad de linea y posible SIM swap para señales antifraude.',
    relationships: 'sale a FeatureLineageLink (source).',
    tableName: 'sim_observations',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'CustomerSession',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Sesion del cliente.',
    whatDoes: 'Registra una sesion de app o web con canal, dispositivo, IP, GPS y metodo de autenticacion.',
    relationships:
      'sale a OnboardingFlow (starts); sale a RiskAssessmentRun (assessed_session); recibe de Device (used_in); recibe de FeatureComputationRun (optional_subject).',
    tableName: 'customer_sessions',
    domainCode: 'SESION_AUTH',
  },
  {
    className: 'AuthEvent',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Evento de autenticacion.',
    whatDoes: 'Guarda logins, fallos, OTPs, intentos y resultados para seguridad y deteccion de abuso.',
    relationships: 'sale a FeatureLineageLink (source).',
    tableName: 'auth_events',
    domainCode: 'SESION_AUTH',
  },
  {
    className: 'IpReputationObservation',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Reputacion de IP.',
    whatDoes: 'Registra si la IP parece VPN, proxy, TOR, pais, ciudad y puntaje de reputacion.',
    relationships: 'sale a FeatureLineageLink (source).',
    tableName: 'ip_reputation_observations',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'CustomerActionLog',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Bitacora de acciones del cliente.',
    whatDoes: 'Evento generico de comportamiento en pantallas, clicks o acciones relevantes, util para auditoria y analitica.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'customer_action_logs',
    domainCode: 'AUDITORIA',
  },
  {
    className: 'CustomerActivitySummary',
    stereotypes: 'projection',
    priority: 'Fase 1',
    whatIs: 'Proyeccion de actividad del cliente.',
    whatDoes:
      'Cache reconstruible con resumen de sesiones, dispositivos, logins fallidos, cambios de dispositivo y estado de riesgo actual.',
    relationships: 'recibe de Customer (activity_projection).',
    tableName: 'customer_activity_summaries',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'OnboardingFlow',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Flujo de registro u originacion.',
    whatDoes: 'Representa un intento completo o incompleto de onboarding, incluso si todavia no existe Customer.',
    relationships:
      'sale a OnboardingBehaviorSummary (summary); sale a RiskAssessmentRun (assessed_flow); recibe de CustomerSession (starts); recibe de OnDeviceComputationRun (during); recibe de FeatureComputationRun (optional_subject).',
    tableName: 'onboarding_flows',
    domainCode: 'ONBOARDING',
  },
  {
    className: 'OnboardingStepEvent',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Evento por paso del onboarding.',
    whatDoes: 'Mide inicio, final, duracion, errores y payload por pantalla o paso del formulario.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'onboarding_step_events',
    domainCode: 'ONBOARDING',
  },
  {
    className: 'FormFieldInteractionEvent',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Interaccion con campos del formulario.',
    whatDoes: 'Captura comportamiento por campo: copy-paste, correcciones, tiempo de foco y errores. Es util para fraude y UX.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'form_field_interaction_events',
    domainCode: 'ONBOARDING',
  },
  {
    className: 'PermissionEvent',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Respuesta a permisos del dispositivo.',
    whatDoes: 'Registra si el usuario concedio ubicacion, camara, contactos, notificaciones u otros permisos.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'permission_events',
    domainCode: 'ONBOARDING',
  },
  {
    className: 'OnboardingBehaviorSummary',
    stereotypes: 'append-only, derived',
    priority: 'MVP',
    whatIs: 'Resumen derivado del comportamiento de onboarding.',
    whatDoes: 'Convierte eventos de pantalla y campos en variables como tasa de error, copy-paste de CI, cluster y probabilidad de bot.',
    relationships: 'sale a FeatureLineageLink (source); recibe de OnboardingFlow (summary).',
    tableName: 'onboarding_behavior_summaries',
    domainCode: 'ONBOARDING',
  },
  {
    className: 'OnDeviceComputationRun',
    stereotypes: 'append-only, privacy',
    priority: 'Fase 1',
    whatIs: 'Ejecucion de calculo on-device.',
    whatDoes: 'Registra que algoritmo corrio en el celular para generar metricas privadas sin subir datos crudos como contactos.',
    relationships: 'sale a CustomerConsent (authorized_by); sale a Device (computed_on); sale a OnboardingFlow (during).',
    tableName: 'on_device_computation_runs',
    domainCode: 'DISPOSITIVO',
  },
  {
    className: 'OnDeviceMetricValue',
    stereotypes: 'append-only, privacy',
    priority: 'Fase 1',
    whatIs: 'Valor de metrica calculada on-device.',
    whatDoes: 'Guarda resultados agregados como scores de contactos o señales locales, no la fuente cruda.',
    relationships: 'sale a FeatureLineageLink (source).',
    tableName: 'on_device_metric_values',
    domainCode: 'DISPOSITIVO',
  },
  {
    className: 'ContextSource',
    stereotypes: 'catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Fuente de contexto externo.',
    whatDoes: 'Catalogo de origenes de informacion contextual: mapas, zonas, listas sectoriales, datos publicos o proveedores.',
    relationships: 'sale a ContextItem (supports).',
    tableName: 'context_sources',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextCatalog',
    stereotypes: 'catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Catalogo contextual.',
    whatDoes: 'Agrupa elementos de contexto como zonas, rubros, carriers, categorias de comercio o clasificaciones de riesgo.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'context_catalogs',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextCatalogVersion',
    stereotypes: 'versioned, catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Version de catalogo contextual.',
    whatDoes: 'Permite actualizar catalogos sin perder que version estaba vigente cuando se genero una decision.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'context_catalog_versions',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextItem',
    stereotypes: 'catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Elemento de catalogo contextual.',
    whatDoes: 'Item concreto dentro de un catalogo: una zona, una categoria, un carrier, un tipo de producto o un sector.',
    relationships: 'sale a CustomerContextEnrichment (optional_match); recibe de ContextSource (supports).',
    tableName: 'context_items',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextItemAlias',
    stereotypes: 'catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Alias de elemento contextual.',
    whatDoes: 'Mapea variaciones de nombres o codigos hacia un item canonico, por ejemplo barrios escritos de formas distintas.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'context_item_aliases',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextRiskMapping',
    stereotypes: 'catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Mapeo de contexto a riesgo.',
    whatDoes: 'Asocia un item contextual a una dimension de riesgo, banda, puntos sugeridos y explicacion.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'context_risk_mappings',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextStagingItem',
    stereotypes: 'catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Propuesta pendiente de item contextual.',
    whatDoes: 'Zona o categoria sugerida por ingestion, IA o analista antes de ser aprobada al catalogo oficial.',
    relationships: 'sale a ContextApprovalEvent (review_history); recibe de ContextIngestionJob (proposes).',
    tableName: 'context_staging_items',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextApprovalEvent',
    stereotypes: 'append-only, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Evento de aprobacion contextual.',
    whatDoes: 'Registra aprobacion, rechazo o modificacion de propuestas de catalogo contextual.',
    relationships: 'recibe de ContextStagingItem (review_history).',
    tableName: 'context_approval_events',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ContextIngestionJob',
    stereotypes: 'append-only, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Trabajo de ingestion de contexto.',
    whatDoes: 'Bitacora de cargas o actualizaciones de datos contextuales desde fuentes externas o internas.',
    relationships: 'sale a ContextStagingItem (proposes).',
    tableName: 'context_ingestion_jobs',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ObservationDefinition',
    stereotypes: 'catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Definicion de observacion.',
    whatDoes: 'Catalogo de señales observables crudas o semi-crudas que se pueden capturar, con gobierno legal y de privacidad.',
    relationships: 'sale a CustomerObservation (defines); recibe de RetentionPolicy (applies_to).',
    tableName: 'observation_definitions',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'EventDefinition',
    stereotypes: 'catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Definicion de evento.',
    whatDoes: 'Define eventos esperados, familia, payload y tablas destino para mantener consistencia del tracking.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'event_definitions',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'CustomerObservation',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Observacion del cliente.',
    whatDoes: 'Evento observado sobre el cliente, sesion, dispositivo u onboarding. Es materia prima para atributos y features.',
    relationships:
      'sale a CustomerContextEnrichment (interpreted_as); sale a FeatureLineageLink (source); recibe de ObservationDefinition (defines).',
    tableName: 'customer_observations',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'AttributeDefinition',
    stereotypes: 'catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Definicion de atributo.',
    whatDoes: 'Catalogo de atributos derivados o normalizados, con reglas de uso crediticio, fraude y fairness.',
    relationships: 'sale a CustomerAttributeValue (defines); recibe de RetentionPolicy (applies_to).',
    tableName: 'attribute_definitions',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'CustomerAttributeValue',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Valor de atributo del cliente.',
    whatDoes: 'Guarda un atributo calculado o asignado a un cliente con periodo de validez y confianza.',
    relationships: 'recibe de AttributeDefinition (defines).',
    tableName: 'customer_attribute_values',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'CustomerContextEnrichment',
    stereotypes: 'append-only',
    priority: 'Fase 1',
    whatIs: 'Enriquecimiento contextual del cliente.',
    whatDoes: 'Asocia una observacion o cliente con un item contextual, por ejemplo zona, carrier, segmento o categoria.',
    relationships:
      'sale a FeatureLineageLink (source); recibe de CustomerObservation (interpreted_as); recibe de ContextItem (optional_match).',
    tableName: 'customer_context_enrichments',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'FeatureDefinition',
    stereotypes: 'catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Definicion de feature.',
    whatDoes: 'Catalogo formal de variables que pueden alimentar scoring, fraude, segmentacion o monitoreo.',
    relationships: 'sale a FeatureValue (defines); recibe de RetentionPolicy (applies_to).',
    tableName: 'feature_definitions',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'FeatureComputationRun',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Ejecucion de calculo de features.',
    whatDoes: 'Bitacora de proceso batch o real-time que calcula features para clientes, dispositivos, sesiones o flujos.',
    relationships: 'sale a CustomerSession (optional_subject); sale a OnboardingFlow (optional_subject); sale a Device (optional_subject).',
    tableName: 'feature_computation_runs',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'FeatureValue',
    stereotypes: 'append-only, derived',
    priority: 'MVP',
    whatIs: 'Valor calculado de una feature.',
    whatDoes: 'Resultado de una feature para una entidad y ventana temporal. Debe ser reproducible o trazable.',
    relationships: 'recibe de FeatureDefinition (defines); recibe de FeatureSnapshot (built_from).',
    tableName: 'feature_values',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'FeatureLineageLink',
    stereotypes: 'append-only',
    priority: 'Fase 1',
    whatIs: 'Linaje de feature.',
    whatDoes: 'Conecta un feature value con sus fuentes: observaciones, eventos, device snapshots, ondevice metrics, etc.',
    relationships:
      'recibe de CustomerObservation (source); recibe de CustomerContextEnrichment (source); recibe de OnboardingBehaviorSummary (source); recibe de OnDeviceMetricValue (source); recibe de DeviceSnapshot (source); recibe de SimObservation (source); recibe de IpReputationObservation (source); recibe de AuthEvent (source).',
    tableName: 'feature_lineage_links',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'FeatureSnapshot',
    stereotypes: 'snapshot',
    priority: 'MVP',
    whatIs: 'Snapshot de features para decision.',
    whatDoes: 'Congela los feature values usados en una evaluacion. Es indispensable para auditoria y entrenamiento posterior.',
    relationships: 'sale a FeatureValue (built_from); sale a RiskAssessmentRun (input_to); recibe de RiskAssessmentRun (may_freeze).',
    tableName: 'feature_snapshots',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskModelVersion',
    stereotypes: 'versioned, catalog, platform-shared',
    priority: 'Fase 1',
    whatIs: 'Version de modelo de riesgo.',
    whatDoes: 'Controla modelos estadisticos o ML por version, estado, objetivo y metrica.',
    relationships: 'sale a RiskAssessmentRun (model_used).',
    tableName: 'risk_model_versions',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskRulesetVersion',
    stereotypes: 'versioned, catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Version de reglas de riesgo.',
    whatDoes: 'Agrupa reglas de politica y antifraude desplegadas en una fecha determinada.',
    relationships: 'sale a RiskAssessmentRun (ruleset_used).',
    tableName: 'risk_ruleset_versions',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskPolicyRule',
    stereotypes: 'versioned, catalog, platform-shared',
    priority: 'MVP',
    whatIs: 'Regla de politica de riesgo.',
    whatDoes: 'Define reglas deterministicas: hard stops, reduccion de limite, revision manual, banderas o ajustes.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'risk_policy_rules',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskAssessmentRun',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Corrida de evaluacion de riesgo.',
    whatDoes: 'Ejecucion del motor contra un sujeto flexible: customer, session, onboarding_flow, device o checkout_context.',
    relationships:
      'sale a FeatureSnapshot (may_freeze); sale a RiskAssessmentContext (decision_context); sale a RiskAssessmentResult (produces); sale a ManualReviewCase (may_open); recibe de RiskModelVersion (model_used); recibe de RiskRulesetVersion (ruleset_used); recibe de FeatureSnapshot (input_to); recibe de Customer (assessed_when_known).',
    tableName: 'risk_assessment_runs',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskAssessmentContext',
    stereotypes: 'snapshot',
    priority: 'MVP',
    whatIs: 'Contexto POS/checkout congelado.',
    whatDoes: 'Snapshot neutral de datos de compra y comercio usados por el motor sin modelar credito, pagos ni cuotas.',
    relationships: 'recibe de RiskAssessmentRun (decision_context).',
    tableName: 'risk_assessment_contexts',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskRuleFired',
    stereotypes: 'append-only',
    priority: 'MVP',
    whatIs: 'Regla disparada.',
    whatDoes: 'Registra cada regla activada durante una evaluacion, con input, resultado, severidad y accion.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'risk_rules_fired',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskFeatureContribution',
    stereotypes: 'append-only',
    priority: 'Fase 1',
    whatIs: 'Contribucion de feature al score.',
    whatDoes: 'Explica cuanto aporto una feature a un score o decision, util para interpretabilidad y auditoria.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'risk_feature_contributions',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'RiskAssessmentResult',
    stereotypes: 'snapshot',
    priority: 'MVP',
    whatIs: 'Resultado final de riesgo.',
    whatDoes: 'Congela decision, puntajes, banda, nivel de confianza, razones principales, overrides y expiracion.',
    relationships: 'recibe de RiskAssessmentRun (produces).',
    tableName: 'risk_assessment_results',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'ManualReviewCase',
    stereotypes: 'case',
    priority: 'Fase 1',
    whatIs: 'Caso de revision manual.',
    whatDoes: 'Gestiona revisiones humanas de KYC, fraude, inconsistencia, data quality o decisiones borderline.',
    relationships:
      'sale a FraudCase (escalated_to); recibe de RiskAssessmentRun (may_open); recibe de FraudCase (reviewed_via); recibe de WatchlistMatch (may_open).',
    tableName: 'manual_review_cases',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'ManualReviewEvent',
    stereotypes: 'append-only',
    priority: 'Fase 1',
    whatIs: 'Evento de revision manual.',
    whatDoes: 'Historial operativo de cambios, comentarios, asignaciones y decisiones dentro de un caso.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'manual_review_events',
    domainCode: 'PLATAFORMA',
  },
  {
    className: 'FraudCase',
    stereotypes: 'case',
    priority: 'Fase 1',
    whatIs: 'Caso de fraude.',
    whatDoes: 'Agrupa evidencia, decision, severidad, perdida estimada, estado y vinculacion con cliente o dispositivo.',
    relationships:
      'sale a ManualReviewCase (reviewed_via); recibe de ManualReviewCase (escalated_to); recibe de Customer (fraud_cases); recibe de Device (linked_device); recibe de WatchlistMatch (may_open).',
    tableName: 'fraud_cases',
    domainCode: 'FRAUDE',
  },
  {
    className: 'FraudCaseEvent',
    stereotypes: 'append-only',
    priority: 'Fase 1',
    whatIs: 'Evento de caso de fraude.',
    whatDoes: 'Bitacora de acciones sobre un caso de fraude: abierto, investigado, confirmado, descartado o cerrado.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'fraud_case_events',
    domainCode: 'FRAUDE',
  },
  {
    className: 'WatchlistEntry',
    stereotypes: 'core, privacy',
    priority: 'Fase 1',
    whatIs: 'Entrada de lista de vigilancia.',
    whatDoes: 'Entidad bloqueada, observada o marcada por riesgo, con alcance global, pais o tenant y valores protegidos por hash.',
    relationships: 'sale a WatchlistMatch (matches).',
    tableName: 'watchlist_entries',
    domainCode: 'FRAUDE',
  },
  {
    className: 'WatchlistMatch',
    stereotypes: 'append-only, privacy',
    priority: 'Fase 1',
    whatIs: 'Coincidencia contra watchlist.',
    whatDoes: 'Registra que un cliente, dispositivo, telefono, documento u otro valor hizo match contra una entrada vigilada.',
    relationships:
      'sale a ManualReviewCase (may_open); sale a FraudCase (may_open); recibe de WatchlistEntry (matches); recibe de Customer (watchlist_hits); recibe de Device (device_hits).',
    tableName: 'watchlist_matches',
    domainCode: 'FRAUDE',
  },
  {
    className: 'DataChangeLog',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Auditoria de cambios de datos.',
    whatDoes: 'Registra cambios operativos sobre tablas criticas, quien los hizo, antes/despues y motivo.',
    relationships: 'recibe de InternalUser (changes); recibe de PlatformUser (platform_changes).',
    tableName: 'data_change_logs',
    domainCode: 'AUDITORIA',
  },
  {
    className: 'OperationalAuditLog',
    stereotypes: 'append-only, event',
    priority: 'MVP',
    whatIs: 'Auditoria de acciones operativas.',
    whatDoes: 'Bitacora de acciones de usuarios internos o plataforma: login admin, aprobaciones, overrides, descargas, revisiones.',
    relationships: 'recibe de InternalUser (actions); recibe de PlatformUser (platform_actions).',
    tableName: 'operational_audit_logs',
    domainCode: 'AUDITORIA',
  },
  {
    className: 'RiskSignalSeed',
    stereotypes: 'catalog, platform-shared, roadmap',
    priority: null,
    whatIs: 'Semilla de señal de riesgo. Prioridad sugerida: Fase 1',
    whatDoes: 'Catalogo de ideas o variables candidatas para futuras features, reglas o investigaciones de riesgo.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'risk_signal_seeds',
    domainCode: 'RIESGO_CREDITO',
  },
  {
    className: 'DataQualityRule',
    stereotypes: 'catalog, platform-shared, quality',
    priority: 'Fase 1',
    whatIs: 'Regla de calidad de datos.',
    whatDoes: 'Define validaciones de completitud, consistencia, rango, duplicidad y frescura.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'data_quality_rules',
    domainCode: 'CALIDAD_DATOS',
  },
  {
    className: 'DataQualityIssue',
    stereotypes: 'append-only, quality',
    priority: 'Fase 1',
    whatIs: 'Hallazgo de calidad de datos.',
    whatDoes: 'Registra incumplimientos de reglas de calidad con severidad, entidad afectada y estado de resolucion.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'data_quality_issues',
    domainCode: 'CALIDAD_DATOS',
  },
  {
    className: 'SchemaConstraintNote',
    stereotypes: 'catalog, platform-shared, quality',
    priority: 'Fase 1',
    whatIs: 'Nota de restriccion de schema.',
    whatDoes: 'Documenta restricciones, checks e indices que deben implementarse en SQL aunque PlantUML no los exprese totalmente.',
    relationships:
      'Relación lógica no expresada como FK física en el diagrama; se gobierna mediante endpoints, servicios de dominio y system_data_relationship_catalog cuando aplica.',
    tableName: 'schema_constraint_notes',
    domainCode: 'CALIDAD_DATOS',
  },
] as const;
export const LOGICAL_RELATIONSHIP_METADATA: LogicalRelationshipMetadata[] = [
  {
    sourceClass: 'Customer',
    targetClass: 'CustomerProfileVersion',
    sourceTable: 'customers',
    targetTable: 'customer_profile_versions',
    relationshipType: 'CURRENT_AND_HISTORICAL_PROFILE',
    cardinality: '1:N',
    optionality: 'REQUIRED_AFTER_PROFILE_CAPTURE',
    businessReason:
      'El cliente debe poder cambiar perfil sin perder el estado exacto usado en una aprobación, rechazo, soporte o revisión.',
    technicalReason:
      'customers.current_profile_version_id funciona como proyección rápida y customer_profile_versions conserva versiones append-only para reconstrucción histórica.',
    auditUsage: 'Permite demostrar qué nombre, edad, idioma o preferencia estaban vigentes cuando se tomó una decisión.',
    analysisUsage: 'Permite cohortes por perfil al momento de captura sin mezclar datos actualizados posteriormente.',
    decisionUsage: 'Soporta KYC, elegibilidad, segmentación y revisión manual sin sobrescribir evidencia histórica.',
  },
  {
    sourceClass: 'Customer',
    targetClass: 'CustomerConsent',
    sourceTable: 'customers',
    targetTable: 'customer_consents',
    relationshipType: 'PRIVACY_AUTHORIZATION',
    cardinality: '1:N',
    optionality: 'REQUIRED_BEFORE_SENSITIVE_PROCESSING',
    businessReason: 'Ningún procesamiento sensible, proveedor externo o scoring debe ejecutarse sin base legal o consentimiento trazable.',
    technicalReason: 'El consentimiento enlaza cliente, documento legal, finalidad, canal, IP, sesión y dispositivo.',
    auditUsage: 'Permite probar cuándo, cómo y bajo qué versión legal se autorizó el tratamiento.',
    analysisUsage: 'Permite medir aceptación, revocación y fricción por canal o versión de documento.',
    decisionUsage: 'Bloquea o habilita KYC, buró, marketing, scoring y procesamiento on-device según finalidad.',
  },
  {
    sourceClass: 'CustomerIdentityDocument',
    targetClass: 'IdentityVerificationAttempt',
    sourceTable: 'customer_identity_documents',
    targetTable: 'identity_verification_attempts',
    relationshipType: 'KYC_VERIFICATION_HISTORY',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_APPROVAL',
    businessReason:
      'La identidad no se considera confiable por existir un documento; debe existir evidencia de intentos, proveedor, resultado y razones.',
    technicalReason: 'Cada intento KYC conserva scores, evidencias, request de proveedor y resultado final asociado al documento.',
    auditUsage: 'Permite explicar por qué una identidad fue aprobada, rechazada o escalada a revisión manual.',
    analysisUsage: 'Permite medir tasa de éxito KYC, falsos positivos, desempeño de proveedores y fricción.',
    decisionUsage: 'Alimenta decisión de activación, bloqueo preventivo, revisión manual o reintento.',
  },
  {
    sourceClass: 'Customer',
    targetClass: 'CustomerContactMethod',
    sourceTable: 'customers',
    targetTable: 'customer_contact_methods',
    relationshipType: 'CONTACTABILITY',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_NOTIFICATIONS_AND_COLLECTIONS',
    businessReason:
      'La operación necesita canales verificables para notificar, cobrar, dar soporte y recuperar contacto sin exponer PII completa.',
    technicalReason: 'Los valores se guardan con hash/cifrado/last_4 y estados de verificación por canal.',
    auditUsage: 'Permite demostrar qué canal se usó, si estaba verificado y con qué fuente antes de una notificación o gestión.',
    analysisUsage: 'Permite medir contactabilidad por canal, dominio de email, fuente y estado.',
    decisionUsage: 'Influye en notificación, cobranza, recuperación de cuenta, fraude y calidad de perfil.',
  },
  {
    sourceClass: 'CustomerAddressVersion',
    targetClass: 'AddressGpsObservation',
    sourceTable: 'customer_address_versions',
    targetTable: 'address_gps_observations',
    relationshipType: 'ADDRESS_GEO_CONSISTENCY',
    cardinality: '1:N',
    optionality: 'OPTIONAL_BUT_AUDIT_RELEVANT',
    businessReason:
      'La dirección declarada puede ser falsa o incompleta; la señal GPS permite validar consistencia sin depender solo del texto.',
    technicalReason: 'La observación GPS enlaza versión de dirección, sesión, distancia, precisión y score de match.',
    auditUsage: 'Permite explicar por qué una dirección fue considerada confiable, dudosa o inconsistente.',
    analysisUsage: 'Permite segmentar riesgo por zonas, precisión de GPS, distancia declarada y calidad de domicilio.',
    decisionUsage: 'Puede alimentar fraude, capacidad logística, revisión manual y reglas geográficas.',
  },
  {
    sourceClass: 'Device',
    targetClass: 'CustomerSession',
    sourceTable: 'devices',
    targetTable: 'customer_sessions',
    relationshipType: 'DEVICE_SESSION_USAGE',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_DIGITAL_RISK',
    businessReason: 'Una sesión sin dispositivo limita la detección de abuso, multi-cuenta, emuladores y comportamiento anómalo.',
    technicalReason: 'CustomerSession referencia device_id y congela IP/GPS/user_agent para unir acceso, navegación y riesgo.',
    auditUsage: 'Permite reconstruir desde qué dispositivo y sesión se ejecutó una acción crítica.',
    analysisUsage: 'Permite medir reutilización, actividad por canal, comportamiento anómalo y estabilidad de dispositivo.',
    decisionUsage: 'Alimenta autenticación, antifraude, revisión manual y confianza de dispositivo.',
  },
  {
    sourceClass: 'Device',
    targetClass: 'DeviceSnapshot',
    sourceTable: 'devices',
    targetTable: 'device_snapshots',
    relationshipType: 'DEVICE_TECHNICAL_SNAPSHOT',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_REPRODUCIBLE_RISK',
    businessReason: 'El estado del dispositivo cambia; para auditar una decisión se necesita la foto técnica exacta del momento.',
    technicalReason: 'El snapshot guarda marca, modelo, sistema, app, root, emulador, VPN y tier sin sobrescribir el device base.',
    auditUsage: 'Permite explicar qué señales técnicas existían cuando se evaluó la sesión o el cliente.',
    analysisUsage: 'Permite comparar mora, fraude o fricción por tipo de dispositivo y versión de app.',
    decisionUsage: 'Puede activar reglas de riesgo por root, emulador, VPN, device tier o versión vulnerable.',
  },
  {
    sourceClass: 'CustomerSession',
    targetClass: 'OnboardingFlow',
    sourceTable: 'customer_sessions',
    targetTable: 'onboarding_flows',
    relationshipType: 'SESSION_STARTS_ONBOARDING',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_ONBOARDING_ANALYTICS',
    businessReason: 'El onboarding debe poder leerse como un flujo completo, no como eventos sueltos sin sesión.',
    technicalReason: 'OnboardingFlow conecta sesión, canal, dispositivo, pasos, permisos y resultado final.',
    auditUsage: 'Permite reconstruir qué ocurrió desde el inicio hasta abandono, aprobación o escalamiento.',
    analysisUsage: 'Permite funnel de conversión, tiempos, abandono por paso y fricción de permisos.',
    decisionUsage: 'Permite mejorar UX, ajustar reglas antifraude tempranas y priorizar soporte.',
  },
  {
    sourceClass: 'ObservationDefinition',
    targetClass: 'CustomerObservation',
    sourceTable: 'observation_definitions',
    targetTable: 'customer_observations',
    relationshipType: 'OBSERVATION_DEFINITION_VALUE',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_GOVERNED_SIGNALS',
    businessReason: 'Las observaciones crudas solo sirven si están definidas, versionadas y gobernadas.',
    technicalReason: 'CustomerObservation referencia una definición que establece tipo, unidad, retención, uso permitido y sensibilidad.',
    auditUsage: 'Permite explicar qué significa cada observación usada por riesgo o fraude.',
    analysisUsage: 'Permite construir variables consistentes y comparables entre clientes, sesiones y ventanas.',
    decisionUsage: 'Alimenta reglas, features, revisión manual y monitoreo de calidad.',
  },
  {
    sourceClass: 'FeatureDefinition',
    targetClass: 'FeatureValue',
    sourceTable: 'feature_definitions',
    targetTable: 'feature_values',
    relationshipType: 'FEATURE_DEFINITION_VALUE',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_SCORING',
    businessReason: 'Una feature sin definición no es defendible para scoring ni auditoría internacional.',
    technicalReason: 'FeatureValue debe conectar valor, sujeto, ventana, tipo, versión y definición.',
    auditUsage: 'Permite explicar qué variable entró al score, su significado y su versión.',
    analysisUsage: 'Permite monitorear estabilidad poblacional, drift, predictive power y calidad.',
    decisionUsage: 'Alimenta score, reglas, estrategias de aprobación, revisión y límites.',
  },
  {
    sourceClass: 'FeatureSnapshot',
    targetClass: 'RiskAssessmentRun',
    sourceTable: 'feature_snapshots',
    targetTable: 'risk_assessment_runs',
    relationshipType: 'RISK_INPUT_FREEZE',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_DECISION_REPRODUCTION',
    businessReason: 'Cada decisión de riesgo debe congelar qué sabía el sistema para evitar discusiones posteriores por datos cambiados.',
    technicalReason: 'RiskAssessmentRun referencia snapshot, modelo, ruleset, contexto y resultado.',
    auditUsage: 'Permite reproducir aprobación, rechazo, límite o revisión con los mismos insumos.',
    analysisUsage: 'Permite backtesting, vintage analysis, monitoreo de drift y validación de performance.',
    decisionUsage: 'Sostiene decisiones crediticias, antifraude y capacidad de pago explicables.',
  },
  {
    sourceClass: 'RiskAssessmentRun',
    targetClass: 'RiskAssessmentResult',
    sourceTable: 'risk_assessment_runs',
    targetTable: 'risk_assessment_results',
    relationshipType: 'RISK_RUN_RESULT',
    cardinality: '1:1',
    optionality: 'REQUIRED_AFTER_RISK_RUN',
    businessReason: 'Una corrida de riesgo sin resultado no permite operar ni auditar la decisión.',
    technicalReason: 'El resultado separa la ejecución del motor del dictamen final y sus razones.',
    auditUsage: 'Permite ver score, decisión, bandas, razones, política y resultado final.',
    analysisUsage: 'Permite medir aprobación, rechazo, revisión manual, distribución de scores y performance.',
    decisionUsage: 'Determina línea, bloqueo, revisión, condiciones o rechazo.',
  },
  {
    sourceClass: 'RiskAssessmentRun',
    targetClass: 'RiskRuleFired',
    sourceTable: 'risk_assessment_runs',
    targetTable: 'risk_rules_fired',
    relationshipType: 'RISK_RULE_EXPLANATION',
    cardinality: '1:N',
    optionality: 'REQUIRED_WHEN_RULES_FIRE',
    businessReason: 'Si una regla intervino en una decisión debe quedar trazada para explicar y gobernar el override.',
    technicalReason: 'RiskRuleFired almacena regla, versión, severidad, input y efecto sobre la decisión.',
    auditUsage: 'Permite responder qué regla cambió la decisión y por qué.',
    analysisUsage: 'Permite medir reglas demasiado agresivas, falsas alertas y estabilidad por segmento.',
    decisionUsage: 'Soporta overrides, revisión manual, calibración de reglas y gobierno de fraude.',
  },
  {
    sourceClass: 'RiskAssessmentRun',
    targetClass: 'ManualReviewCase',
    sourceTable: 'risk_assessment_runs',
    targetTable: 'manual_review_cases',
    relationshipType: 'RISK_ESCALATION_CASE',
    cardinality: '1:N',
    optionality: 'WHEN_DECISION_NEEDS_HUMAN_REVIEW',
    businessReason: 'Las decisiones ambiguas o de alto impacto deben escalarse con evidencia, SLA y responsable.',
    technicalReason: 'ManualReviewCase conserva cola, prioridad, motivo, asignación y resolución asociada a riesgo/fraude.',
    auditUsage: 'Permite demostrar que un humano revisó con evidencia suficiente y registró resolución.',
    analysisUsage: 'Permite medir carga operativa, tiempos de resolución, motivos y calidad de escalamiento.',
    decisionUsage: 'Permite aprobar, rechazar, bloquear, solicitar evidencia o abrir caso de fraude.',
  },
  {
    sourceClass: 'FraudCase',
    targetClass: 'FraudCaseEvent',
    sourceTable: 'fraud_cases',
    targetTable: 'fraud_case_events',
    relationshipType: 'FRAUD_CASE_TIMELINE',
    cardinality: '1:N',
    optionality: 'REQUIRED_FOR_FRAUD_OPERATIONS',
    businessReason: 'Un caso de fraude necesita línea de tiempo completa para investigación, defensa y mejora de reglas.',
    technicalReason: 'FraudCaseEvent conserva cambios de estado, evidencia, actor, motivo y fecha.',
    auditUsage: 'Permite reconstruir investigación, decisiones y traspasos de responsabilidad.',
    analysisUsage: 'Permite identificar modus operandi, tiempos, severidad y efectividad de controles.',
    decisionUsage: 'Soporta bloqueo, watchlist, revisión manual, recuperación o descarte de fraude.',
  },
  {
    sourceClass: 'WatchlistEntry',
    targetClass: 'WatchlistMatch',
    sourceTable: 'watchlist_entries',
    targetTable: 'watchlist_matches',
    relationshipType: 'WATCHLIST_MATCH_EVIDENCE',
    cardinality: '1:N',
    optionality: 'WHEN_MATCH_OCCURS',
    businessReason: 'Un match sin entrada de lista no es defendible ni accionable.',
    technicalReason: 'WatchlistMatch enlaza entidad evaluada, tipo de valor, score de coincidencia y entrada vigilada.',
    auditUsage: 'Permite explicar qué lista disparó alerta y con qué nivel de confianza.',
    analysisUsage: 'Permite medir precisión de listas, falsos positivos y recurrencia de entidades.',
    decisionUsage: 'Puede abrir revisión, bloquear, marcar dispositivo o crear caso de fraude.',
  },
  {
    sourceClass: 'DataProvider',
    targetClass: 'DataProviderRequest',
    sourceTable: 'data_providers',
    targetTable: 'data_provider_requests',
    relationshipType: 'EXTERNAL_REQUEST_TRACE',
    cardinality: '1:N',
    optionality: 'WHEN_PROVIDER_IS_CALLED',
    businessReason: 'Cada consulta externa tiene costo, latencia, consentimiento y riesgo legal; no puede quedar solo en logs.',
    technicalReason: 'La request guarda proveedor, idempotency_key, hash de payload, estado y timestamps.',
    auditUsage: 'Permite demostrar qué proveedor fue consultado, cuándo y bajo qué autorización.',
    analysisUsage: 'Permite medir costo, fallos, latencia, confiabilidad y dependencia por proveedor.',
    decisionUsage: 'Soporta retry, fallback, revisión manual y selección de proveedor.',
  },
  {
    sourceClass: 'DataProviderRequest',
    targetClass: 'DataProviderResponse',
    sourceTable: 'data_provider_requests',
    targetTable: 'data_provider_responses',
    relationshipType: 'EXTERNAL_RESPONSE_TRACE',
    cardinality: '1:1',
    optionality: 'WHEN_PROVIDER_RESPONDS',
    businessReason: 'La decisión puede depender de una respuesta externa; debe poder auditarse sin exponer datos crudos innecesarios.',
    technicalReason: 'La response conserva payload redactado, hash, estrategia de almacenamiento y política de retención.',
    auditUsage: 'Permite reconstruir qué devolvió el proveedor y si el backend lo normalizó correctamente.',
    analysisUsage: 'Permite medir calidad de proveedor, tasa de datos faltantes y consistencia de normalización.',
    decisionUsage: 'Alimenta KYC, scoring, fraude, contactabilidad y revisión manual.',
  },
  {
    sourceClass: 'DataQualityRule',
    targetClass: 'DataQualityIssue',
    sourceTable: 'data_quality_rules',
    targetTable: 'data_quality_issues',
    relationshipType: 'QUALITY_RULE_FINDING',
    cardinality: '1:N',
    optionality: 'WHEN_RULE_FAILS',
    businessReason: 'Una regla de calidad sin hallazgos no permite gestionar deuda de datos; un hallazgo sin regla no es gobernable.',
    technicalReason: 'El issue referencia la regla, entidad afectada, severidad, estado y resolución.',
    auditUsage: 'Permite demostrar que los problemas de datos fueron detectados, asignados y resueltos.',
    analysisUsage: 'Permite medir salud del dato por tabla, dominio, severidad y tendencia.',
    decisionUsage: 'Puede bloquear release, pausar modelo, exigir limpieza o abrir revisión.',
  },
] as const;
export const DOMAIN_BUSINESS_METADATA: DomainBusinessMetadata[] = [
  {
    domainCode: 'PLATAFORMA',
    domainName: 'Plataforma, tenancy y administración interna',
    dataNature: 'OPERACIONAL',
    description:
      'Gobierna tenants, usuarios internos, configuración compartida, fases de construcción y recursos transversales del backend.',
    businessDefinition:
      'Define la estructura institucional sobre la que se opera Atlas: país, tenant, usuarios con privilegios, responsabilidades y configuración base. Es la capa que permite escalar de Bolivia a otros mercados sin mezclar datos ni reglas.',
    technicalScope:
      'Tablas raíz, usuarios globales/locales, permisos, fases, proveedores base y catálogos compartidos. Debe tener aislamiento por tenant, trazabilidad de cambios y baja tolerancia a datos huérfanos.',
    ownerTeam: 'systems-governance',
    regulatoryNotes: 'Debe permitir residencia/segregación por país, auditoría de administradores y separación de funciones.',
    exampleTables: ['tenants', 'platform_users', 'internal_users', 'implementation_phases', 'entity_build_scopes'],
    decisionUseCases: ['habilitar tenant/país', 'asignar roles', 'separar operación por mercado', 'priorizar roadmap técnico'],
    auditRelevance: 'Permite probar quién podía operar qué, bajo qué tenant y con qué configuración activa al momento de una decisión.',
  },
  {
    domainCode: 'IDENTIDAD_KYC',
    domainName: 'Identidad, perfil y KYC',
    dataNature: 'IDENTIDAD',
    description: 'Gestiona cliente, perfil versionado, documentos, intentos KYC, contactos, direcciones y evidencias de identidad.',
    businessDefinition:
      'Permite saber si una persona es quien dice ser, si puede contactarse y si su identidad es suficientemente confiable para ofrecer BNPL/crédito de consumo.',
    technicalScope:
      'Datos personales minimizados con hash/cifrado/last_4, versiones append-only, evidencias, scores de proveedor, direcciones y contactos verificados.',
    ownerTeam: 'risk-compliance-operations',
    regulatoryNotes: 'Debe aplicar minimización, consentimiento, retención, acceso restringido y auditoría de descifrado.',
    exampleTables: [
      'customers',
      'customer_profile_versions',
      'customer_identity_documents',
      'identity_verification_attempts',
      'customer_contact_methods',
      'customer_address_versions',
    ],
    decisionUseCases: ['aprobar onboarding', 'bloquear identidad dudosa', 'solicitar evidencia adicional', 'priorizar revisión manual'],
    auditRelevance: 'Reconstruye qué identidad, documento, evidencia, canal y proveedor sostuvieron una aprobación o rechazo.',
  },
  {
    domainCode: 'PRIVACIDAD',
    domainName: 'Privacidad, consentimiento y derechos del titular',
    dataNature: 'LEGAL_PRIVACIDAD',
    description:
      'Controla finalidades, consentimiento, versiones legales, clasificación, reglas de campo sensible y solicitudes del titular.',
    businessDefinition:
      'Evita que Atlas use datos sin autorización o fuera de finalidad. Sin este dominio, el riesgo legal escala más rápido que el producto.',
    technicalScope:
      'Documentos versionados, propósito de tratamiento, eventos de consentimiento, políticas de clasificación, retención y masking por campo.',
    ownerTeam: 'compliance-data-governance',
    regulatoryNotes:
      'Preparado para adaptar reglas por país: consentimiento explícito, oposición, eliminación, portabilidad y retención legal.',
    exampleTables: [
      'privacy_processing_purposes',
      'consent_documents',
      'customer_consents',
      'consent_events',
      'data_classification_policies',
      'sensitive_field_rules',
      'data_subject_requests',
    ],
    decisionUseCases: ['habilitar buró/KYC', 'bloquear marketing', 'responder solicitud del titular', 'definir masking y retención'],
    auditRelevance: 'Demuestra cuándo, cómo, desde qué sesión y bajo qué documento se autorizó o revocó un tratamiento.',
  },
  {
    domainCode: 'DISPOSITIVO',
    domainName: 'Device intelligence, SIM, IP y sesión técnica',
    dataNature: 'FRAUDE',
    description: 'Captura señales técnicas de dispositivo, SIM, IP, sesión, emulador, VPN, root y consistencia geográfica.',
    businessDefinition: 'Reduce fraude temprano y abuso multi-cuenta antes de que exista suficiente historial crediticio.',
    technicalScope:
      'Fingerprints globales/locales, snapshots append-only, sesiones, eventos de autenticación, reputación IP, SIM y actividad agregada.',
    ownerTeam: 'fraud-risk-engineering',
    regulatoryNotes: 'Tratar IP, GPS, user-agent y fingerprint como datos sensibles; documentar finalidad antifraude y retención.',
    exampleTables: [
      'global_device_fingerprints',
      'devices',
      'customer_device_links',
      'device_snapshots',
      'sim_observations',
      'customer_sessions',
      'auth_events',
      'ip_reputation_observations',
    ],
    decisionUseCases: ['detectar emulador/root/VPN', 'bloquear multi-cuenta', 'elevar fricción KYC', 'abrir revisión manual'],
    auditRelevance: 'Permite demostrar desde qué dispositivo, IP y sesión se originó una acción o decisión de riesgo.',
  },
  {
    domainCode: 'ONBOARDING',
    domainName: 'Onboarding y comportamiento de formulario',
    dataNature: 'CONVERSION_RIESGO',
    description: 'Documenta flujo de registro, pasos, interacción con campos, permisos y resumen conductual.',
    businessDefinition:
      'Conecta crecimiento, UX y fraude: el modo en que un usuario completa formularios puede indicar fricción legítima o comportamiento sospechoso.',
    technicalScope: 'Eventos append-only de pasos, permisos, interacciones y resúmenes por flujo; enlazado a sesión y dispositivo.',
    ownerTeam: 'product-risk-analytics',
    regulatoryNotes: 'No almacenar texto sensible innecesario de campos; preferir métricas y eventos normalizados.',
    exampleTables: [
      'onboarding_flows',
      'onboarding_step_events',
      'form_field_interaction_events',
      'permission_events',
      'onboarding_behavior_summaries',
    ],
    decisionUseCases: ['mejorar conversión', 'detectar bots o patrones anómalos', 'priorizar soporte', 'ajustar fricción de KYC'],
    auditRelevance: 'Permite reconstruir el recorrido que llevó a abandono, aprobación, rechazo o escalamiento.',
  },
  {
    domainCode: 'RIESGO_CREDITO',
    domainName: 'Riesgo crediticio, observaciones y score',
    dataNature: 'RIESGO',
    description: 'Abarca observaciones, atributos, feature store, reglas, modelos, corridas y resultados de evaluación.',
    businessDefinition:
      'Sostiene la decisión principal de Atlas: si se asigna línea, cuánto riesgo tomar, cuándo revisar y cómo explicar una decisión crediticia.',
    technicalScope:
      'Definiciones gobernadas, valores, linaje, snapshots, versiones de modelos/reglas, contribuciones y resultados reproducibles.',
    ownerTeam: 'credit-risk-analytics',
    regulatoryNotes: 'Variables de scoring deben ser explicables, revisables, con finalidad válida y control de sesgo/uso permitido.',
    exampleTables: [
      'observation_definitions',
      'customer_observations',
      'attribute_definitions',
      'customer_attribute_values',
      'feature_definitions',
      'feature_values',
      'feature_snapshots',
      'risk_assessment_runs',
      'risk_assessment_results',
    ],
    decisionUseCases: [
      'aprobar/rechazar',
      'definir límite',
      'abrir revisión manual',
      'ajustar política de riesgo',
      'monitorear performance',
    ],
    auditRelevance: 'Permite reproducir qué sabía el sistema y qué reglas/modelo usó en cada decisión.',
  },
  {
    domainCode: 'CAPACIDAD_PAGO',
    domainName: 'Capacidad de pago y affordability',
    dataNature: 'CAPACIDAD',
    description:
      'Agrupa señales para estimar habilidad real de pago: estabilidad, comportamiento, contexto, límites, pagos y features derivadas.',
    businessDefinition: 'Evita prestar más de lo que el cliente puede sostener y ayuda a calibrar líneas responsables para BNPL.',
    technicalScope:
      'Features y atributos calculados, contexto de empleo/ingreso cuando exista, comportamiento de pago y señales indirectas documentadas.',
    ownerTeam: 'credit-risk-analytics',
    regulatoryNotes: 'Evitar proxies discriminatorios y exigir justificación de negocio para cada variable usada.',
    exampleTables: [
      'feature_definitions',
      'feature_values',
      'customer_attribute_values',
      'context_risk_mappings',
      'risk_feature_contributions',
    ],
    decisionUseCases: ['calcular límite', 'reducir mora', 'ajustar cuotas futuras', 'monitorear vintage y cohortes'],
    auditRelevance: 'Permite explicar por qué una línea fue asignada, reducida, incrementada o bloqueada por capacidad.',
  },
  {
    domainCode: 'FRAUDE',
    domainName: 'Fraude, revisión manual y watchlists',
    dataNature: 'FRAUDE',
    description: 'Gestiona casos, eventos, listas de vigilancia, matches, revisión humana y escalamiento.',
    businessDefinition:
      'Protege a Atlas y comercios contra identidad falsa, abuso de dispositivos, listas internas/externas y patrones coordinados.',
    technicalScope: 'Casos append-only, timelines, watchlists hasheadas, matches con score, vínculos a cliente/dispositivo y revisiones.',
    ownerTeam: 'fraud-operations',
    regulatoryNotes: 'Requiere trazabilidad estricta de listas, motivos, resolución y evidencia para evitar bloqueos arbitrarios.',
    exampleTables: [
      'manual_review_cases',
      'manual_review_events',
      'fraud_cases',
      'fraud_case_events',
      'watchlist_entries',
      'watchlist_matches',
    ],
    decisionUseCases: [
      'bloquear preventivamente',
      'abrir caso',
      'cerrar falso positivo',
      'actualizar reglas/listas',
      'escalar investigación',
    ],
    auditRelevance: 'Reconstruye el ciclo completo de alerta, investigación, evidencia, actor y resolución.',
  },
  {
    domainCode: 'PROVEEDORES',
    domainName: 'Proveedores externos y enriquecimiento',
    dataNature: 'INTEGRACION',
    description: 'Orquesta proveedores de KYC, buró, reputación IP, telco, OCR, QR/bancos y otros enriquecimientos.',
    businessDefinition:
      'Controla dependencia, costo, confiabilidad y evidencia de cada fuente externa usada por riesgo, fraude u operación.',
    technicalScope: 'Catálogo de proveedores, requests, responses, payload redactado, hashes, idempotencia, salud, latencia y retención.',
    ownerTeam: 'integrations-risk-ops',
    regulatoryNotes: 'Cada proveedor debe tener finalidad, contrato, retención, control de datos sensibles y monitoreo de SLA/costos.',
    exampleTables: ['data_providers', 'data_provider_requests', 'data_provider_responses', 'provider_health_logs'],
    decisionUseCases: [
      'seleccionar proveedor',
      'aplicar retry/fallback',
      'auditar costo por consulta',
      'explicar decisión basada en externo',
    ],
    auditRelevance: 'Demuestra qué proveedor se llamó, qué respondió, cómo se normalizó y qué decisión usó la respuesta.',
  },
  {
    domainCode: 'EVIDENCIAS',
    domainName: 'Evidencias documentales y extracciones',
    dataNature: 'EVIDENCIA',
    description: 'Representa documentos, selfies, comprobantes, OCR, IA/extracción y revisión humana de archivos.',
    businessDefinition: 'Sostiene KYC, soporte, revisión manual y disputas sin guardar binarios pesados en la base transaccional.',
    technicalScope: 'Referencias a object storage, hash de archivo, MIME, tamaño, extracción redactada, score de confianza y revisión.',
    ownerTeam: 'compliance-operations',
    regulatoryNotes: 'Requiere retención definida, cifrado en storage, control de acceso y minimización de payload extraído.',
    exampleTables: ['evidence_documents', 'evidence_extractions', 'evidence_reviews'],
    decisionUseCases: ['aprobar KYC', 'rechazar documento', 'pedir nueva evidencia', 'resolver disputa'],
    auditRelevance: 'Permite probar qué archivo y extracción respaldaron una decisión sin exponer binarios innecesariamente.',
  },
  {
    domainCode: 'CONTEXTO_RIESGO',
    domainName: 'Base contextual de riesgo',
    dataNature: 'CONTEXTO',
    description: 'Catálogos de contexto: zonas, rubros, aliases, staging, aprobaciones, fuentes e ingestion jobs.',
    businessDefinition: 'Permite enriquecer decisiones con contexto territorial, comercial o sectorial gobernado y versionado.',
    technicalScope: 'Fuentes, catálogos, versiones, items, aliases, mapeos de riesgo, staging, aprobaciones e ingestion.',
    ownerTeam: 'risk-data-governance',
    regulatoryNotes: 'Fuentes públicas/privadas deben tener confiabilidad, fecha de actualización y aprobación antes de impactar scoring.',
    exampleTables: [
      'context_sources',
      'context_catalogs',
      'context_catalog_versions',
      'context_items',
      'context_item_aliases',
      'context_risk_mappings',
      'context_ingestion_jobs',
    ],
    decisionUseCases: ['ajustar riesgo por zona/rubro', 'normalizar aliases', 'aprobar nuevos catálogos', 'monitorear drift contextual'],
    auditRelevance: 'Permite demostrar qué versión de catálogo contextual afectó una evaluación.',
  },
  {
    domainCode: 'CALIDAD_DATOS',
    domainName: 'Calidad de datos y constraints',
    dataNature: 'GOBIERNO_DATOS',
    description: 'Reglas, issues y notas de constraints para mantener datos completos, consistentes, frescos y confiables.',
    businessDefinition: 'Un motor de riesgo internacional no escala si sus datos no son medibles, gobernados y corregibles.',
    technicalScope: 'Reglas de completitud/rango/consistencia/frescura, hallazgos, severidad, estado y notas de constraints/índices.',
    ownerTeam: 'data-governance',
    regulatoryNotes: 'Se debe poder pausar modelos o releases si una regla crítica de calidad falla.',
    exampleTables: ['data_quality_rules', 'data_quality_issues', 'schema_constraint_notes'],
    decisionUseCases: ['bloquear release', 'pausar feature/modelo', 'priorizar limpieza', 'medir salud por dominio'],
    auditRelevance: 'Demuestra que Atlas detecta y corrige problemas de datos antes de usarlos en decisiones sensibles.',
  },
  {
    domainCode: 'AUDITORIA',
    domainName: 'Auditoría operacional y cambios de datos',
    dataNature: 'AUDITORIA',
    description: 'Registra acciones, cambios, actores, payload saneado, antes/después y correlación de requests.',
    businessDefinition: 'Permite operar con confianza, responder incidentes, cumplir revisiones y detectar abuso interno.',
    technicalScope: 'Logs append-only, data change logs, operational audit logs, system action logs, request_id y actor_id.',
    ownerTeam: 'security-compliance-systems',
    regulatoryNotes: 'Debe protegerse contra edición/borrado no autorizado y conservarse según obligación legal.',
    exampleTables: ['data_change_logs', 'operational_audit_logs', 'system_action_logs'],
    decisionUseCases: ['investigar incidente', 'auditar override', 'detectar abuso interno', 'reconstruir request'],
    auditRelevance: 'Es la capa que permite probar quién hizo qué, cuándo, desde dónde y con qué impacto.',
  },
  {
    domainCode: 'COMUNICACIONES',
    domainName: 'Comunicaciones y notificaciones',
    dataNature: 'OPERACIONAL',
    description: 'Plantillas, preferencias, tokens, mensajes, entregas, webhooks y outbox de comunicación.',
    businessDefinition: 'Asegura contacto oportuno para onboarding, cuotas, soporte, cobranza y eventos críticos.',
    technicalScope: 'Templates versionados, preferencias, tokens cifrados/hasheados, delivery attempts, provider callbacks y outbox.',
    ownerTeam: 'operations-communications',
    regulatoryNotes: 'Debe respetar consentimiento, opt-out, finalidad y evidencia de entrega.',
    exampleTables: [
      'notification_templates',
      'user_notification_preferences',
      'device_tokens',
      'notification_messages',
      'notification_deliveries',
      'outbox_events',
    ],
    decisionUseCases: ['enviar recordatorio', 'bloquear canal revocado', 'medir entregabilidad', 'activar fallback'],
    auditRelevance: 'Permite demostrar qué mensaje se envió, por qué canal, con qué proveedor y resultado.',
  },
  {
    domainCode: 'SISTEMAS_QA',
    domainName: 'Sistemas, catálogo, QA, stress y gobierno técnico',
    dataNature: 'GOBIERNO_TECNICO',
    description: 'Catálogo interno de endpoints, tablas, campos, relaciones, reglas, herramientas, pruebas y stress profiles.',
    businessDefinition:
      'Convierte el backend en una plataforma gobernable: cada endpoint debe explicar propósito, payload, impacto, riesgo y evidencia de prueba.',
    technicalScope: 'Metadata de endpoints/campos/relaciones, herramientas, test suites, runs, stress profiles y action logs.',
    ownerTeam: 'systems-qa-governance',
    regulatoryNotes: 'Crítico para escalar internacionalmente, certificar cambios y evitar dependencias de conocimiento tribal.',
    exampleTables: [
      'system_endpoint_catalog',
      'system_data_entity_catalog',
      'system_data_field_catalog',
      'system_data_relationship_catalog',
      'system_operational_rule_catalog',
      'system_test_suites',
      'system_stress_profiles',
    ],
    decisionUseCases: ['autorizar release', 'ver impacto de endpoint', 'probar stress', 'auditar cambios técnicos'],
    auditRelevance: 'Permite demostrar cobertura de metadata, pruebas, endpoints críticos, payloads y relaciones impactadas.',
  },
] as const;
