import { EndpointSeed } from './systems-ops.types.js';

export const CURATED_ENDPOINTS: EndpointSeed[] = [
  {
    code: 'GET_HEALTH',
    module: 'health',
    method: 'GET',
    fullPath: '/api/v1/health',
    routeName: 'Salud del backend',
    businessPurpose: 'Verificar disponibilidad técnica, conexión de base y estado mínimo del servicio antes de probar el portal.',
    businessAction: 'Retorna un estado de salud consumible por smoke tests, Render/Coolify y operadores internos.',
    expectedResponseSummary: 'Estado healthy/unhealthy, timestamp y señales técnicas sin exponer secretos.',
    expectedStatusCodes: [200, 503],
    requiresAuth: false,
    allowedRoles: [],
    riskLevel: 'LOW',
    isReadonly: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'POST_AUTH_LOGIN',
    module: 'auth',
    method: 'POST',
    fullPath: '/api/v1/auth/login',
    routeName: 'Login externo/plataforma',
    businessPurpose: 'Permitir acceso seguro a usuarios de plataforma con credenciales controladas.',
    businessAction: 'Valida credenciales, registra auditoría y emite tokens de acceso/refresco.',
    expectedResponseSummary: 'Tokens y perfil mínimo de sesión; nunca retorna hash de contraseña.',
    expectedStatusCodes: [200, 400, 401, 403, 423],
    minPayloadSchema: { email: 'string|required', password: 'string|required' },
    headersSchema: { 'x-request-id': 'optional' },
    requiresAuth: false,
    allowedRoles: [],
    containsPii: true,
    piiFields: ['email', 'password'],
    riskLevel: 'CRITICAL',
    requiresStressTest: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: false,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'POST_INTERNAL_AUTH_LOGIN',
    module: 'internal',
    method: 'POST',
    fullPath: '/api/v1/internal/auth/login',
    routeName: 'Login panel interno',
    businessPurpose: 'Permitir entrada al portal administrativo interno con RBAC.',
    businessAction: 'Valida credenciales del usuario interno, emite tokens y adjunta permisos/roles de sesión.',
    expectedResponseSummary: 'Sesión interna con permisos autorizados para pintar menús, acciones y vistas.',
    expectedStatusCodes: [200, 400, 401, 403, 423],
    minPayloadSchema: { email: 'pablo@atlas.internal', password: 'Atlas_Pablo#2026!' },
    requiresAuth: false,
    allowedRoles: [],
    containsPii: true,
    piiFields: ['email', 'password'],
    riskLevel: 'CRITICAL',
    requiresStressTest: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: false,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_SYSTEMS_DASHBOARD',
    module: 'systems',
    method: 'GET',
    fullPath: '/api/v1/systems/dashboard',
    routeName: 'Dashboard administrativo de sistemas',
    businessPurpose: 'Mostrar salud del catálogo técnico, endpoints, entidades, herramientas, pruebas y pendientes de gobierno.',
    businessAction: 'Agrega métricas de catálogo, cobertura QA, revisión pendiente y criticidad operativa.',
    expectedResponseSummary: 'KPIs agregados y listas resumidas para la portada del portal administrativo.',
    expectedStatusCodes: [200, 401, 403],
    allowedRoles: ['system_admin', 'platform_admin', 'qa_engineer', 'readonly_auditor'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_SYSTEMS_ENDPOINTS',
    module: 'systems',
    method: 'GET',
    fullPath: '/api/v1/systems/endpoints',
    routeName: 'Catálogo de endpoints',
    businessPurpose: 'Listar rutas, propósito de negocio, payload mínimo, respuesta esperada y estado de revisión.',
    businessAction: 'Alimenta la vista principal de documentación operativa del portal de sistemas.',
    expectedResponseSummary: 'Paginación de endpoints con filtros por módulo, riesgo, método, revisión y estado.',
    expectedStatusCodes: [200, 401, 403],
    queryParamsSchema: {
      module: 'optional',
      method: 'optional',
      riskLevel: 'optional',
      reviewStatus: 'optional',
      page: 'number',
      limit: 'number',
    },
    allowedRoles: ['system_admin', 'platform_admin', 'qa_engineer', 'readonly_auditor'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresStressTest: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_SYSTEMS_DATA_ENTITIES',
    module: 'systems',
    method: 'GET',
    fullPath: '/api/v1/systems/data-entities',
    routeName: 'Catálogo de entidades/tablas',
    businessPurpose: 'Mostrar cada tabla del backend, razón de negocio, dueño, clasificación y si afecta ML/riesgo/legal.',
    businessAction: 'Sirve para que sistemas documente la base sin abrir SQL manualmente.',
    expectedResponseSummary: 'Listado paginado de entidades con flags de PII, riesgo, auditoría y módulo.',
    expectedStatusCodes: [200, 401, 403],
    allowedRoles: ['system_admin', 'platform_admin', 'readonly_auditor'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_SYSTEMS_TOOLS',
    module: 'systems',
    method: 'GET',
    fullPath: '/api/v1/systems/tools',
    routeName: 'Catálogo de herramientas',
    businessPurpose:
      'Listar herramientas técnicas requeridas por endpoint: DB, Redis, JWT, BullMQ planificado, proveedores externos y testing.',
    businessAction: 'Permite al portal explicar dependencias técnicas y mocks necesarios antes de probar.',
    expectedResponseSummary: 'Herramientas con estado, variables ENV requeridas, criticidad y owner team.',
    expectedStatusCodes: [200, 401, 403],
    allowedRoles: ['system_admin', 'platform_admin', 'qa_engineer', 'readonly_auditor'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_SYSTEMS_REVIEW_QUEUE',
    module: 'systems',
    method: 'GET',
    fullPath: '/api/v1/systems/review-queue',
    routeName: 'Cola de revisión del catálogo',
    businessPurpose: 'Mostrar elementos técnicos que requieren aprobación o corrección de gobierno.',
    businessAction: 'Agrupa endpoints, entidades, herramientas e impactos no aprobados para revisión interna.',
    expectedResponseSummary: 'Cola consolidada de revisión por tipo de elemento, prioridad y riesgo.',
    expectedStatusCodes: [200, 401, 403],
    allowedRoles: ['system_admin', 'platform_admin'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_SYSTEMS_TEST_SUITES',
    module: 'systems',
    method: 'GET',
    fullPath: '/api/v1/systems/test-suites',
    routeName: 'Suites de prueba',
    businessPurpose: 'Listar pruebas smoke, integración y regresión configuradas desde el portal.',
    businessAction: 'Permite seleccionar suites para ejecutar contra endpoints con payload semilla.',
    expectedResponseSummary: 'Suites activas con pasos, ambiente, modo de ejecución y seguridad de producción.',
    expectedStatusCodes: [200, 401, 403],
    allowedRoles: ['system_admin', 'platform_admin', 'qa_engineer'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'POST_SYSTEMS_TEST_SUITE_RUN',
    module: 'systems',
    method: 'POST',
    fullPath: '/api/v1/systems/test-suites/:suiteId/run',
    routeName: 'Ejecutar suite de prueba',
    businessPurpose: 'Ejecutar desde el portal una suite contra endpoints internos con assertions controladas.',
    businessAction: 'Crea un test run, ejecuta pasos HTTP y guarda resultados sanitizados.',
    expectedResponseSummary: 'Run con estado, resumen, duración y fallas sanitizadas.',
    expectedStatusCodes: [200, 201, 400, 401, 403, 422],
    pathParamsSchema: { suiteId: 'positive integer|required' },
    minPayloadSchema: { environment: 'LOCAL|STAGING', variables: 'object|optional' },
    allowedRoles: ['system_admin', 'platform_admin', 'qa_engineer'],
    riskLevel: 'HIGH',
    isDestructive: false,
    isReadonly: false,
    idempotencyRequired: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_SYSTEMS_STRESS_PROFILES',
    module: 'systems',
    method: 'GET',
    fullPath: '/api/v1/systems/stress-profiles',
    routeName: 'Perfiles de stress',
    businessPurpose: 'Listar perfiles de carga segura para endpoints críticos del backend.',
    businessAction: 'Permite revisar RPS, concurrencia, p95 máximo y aprobación requerida antes de ejecutar carga.',
    expectedResponseSummary: 'Perfiles de stress por endpoint con límites y alcance de ambiente.',
    expectedStatusCodes: [200, 401, 403],
    allowedRoles: ['system_admin', 'platform_admin', 'qa_engineer'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'POST_CUSTOMER_ONBOARDING_START',
    module: 'customer_onboarding',
    method: 'POST',
    fullPath: '/api/v1/customer-onboarding/start',
    routeName: 'Inicio compuesto de onboarding',
    businessPurpose:
      'Crear el estado inicial del cliente, consentimiento base, dispositivo y flujo de onboarding sin guardar contactos crudos.',
    businessAction: 'Registra cliente demo, atributos iniciales, consentimiento, device link y flujo de onboarding.',
    expectedResponseSummary: 'Cliente, flujo de onboarding, estado de pasos y referencias seguras para continuar.',
    expectedStatusCodes: [201, 400, 409, 422],
    minPayloadSchema: { documentNumber: 'string|required', phone: 'string|required', acceptedConsents: 'array|required' },
    headersSchema: { 'x-tenant-id': 'required', 'x-idempotency-key': 'required' },
    containsPii: true,
    piiFields: ['documentNumber', 'phone', 'email'],
    riskLevel: 'CRITICAL',
    idempotencyRequired: true,
    requiresStressTest: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'POST_CUSTOMERS_BY_CUSTOMERID_RISK_ASSESSMENTS',
    module: 'risk',
    method: 'POST',
    fullPath: '/api/v1/customers/:customerId/risk-assessments',
    routeName: 'Evaluación de riesgo del cliente',
    businessPurpose: 'Ejecutar el motor de riesgo/scoring sobre datos gobernados del cliente.',
    businessAction: 'Construye paquete de decisión, calcula score, aplica reglas de política y abre revisión si corresponde.',
    expectedResponseSummary: 'Resultado de riesgo, score, razón de decisión, reglas disparadas y posible caso manual.',
    expectedStatusCodes: [201, 400, 403, 422],
    pathParamsSchema: { customerId: 'positive integer|required' },
    headersSchema: { 'x-tenant-id': 'required', 'x-idempotency-key': 'recommended' },
    containsPii: true,
    riskLevel: 'CRITICAL',
    idempotencyRequired: true,
    requiresStressTest: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_CUSTOMERS_BY_CUSTOMERID_ME',
    module: 'customers',
    method: 'GET',
    fullPath: '/api/v1/customers/:customerId/me',
    routeName: 'Perfil cliente demo',
    businessPurpose: 'Mostrar al frontend/app del consumidor la ficha mínima del cliente autenticado.',
    businessAction: 'Lee estado, perfil, consentimiento y datos de contacto sanitizados del cliente.',
    expectedResponseSummary: 'Cliente 1 demo con perfil, estado y datos mínimos seguros.',
    expectedStatusCodes: [200, 401, 403, 404],
    pathParamsSchema: { customerId: 'positive integer|required' },
    containsPii: true,
    piiFields: ['customerId', 'phoneMasked', 'emailMasked'],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_OPERATIONS_WORK_QUEUE',
    module: 'operations',
    method: 'GET',
    fullPath: '/api/v1/operations/work-queue',
    routeName: 'Cola de trabajo operativa',
    businessPurpose: 'Mostrar casos pendientes de revisión manual, fraude, sesiones anómalas y calidad para operaciones.',
    businessAction: 'Agrega casos abiertos y los ordena por severidad, fecha y SLA operativo.',
    expectedResponseSummary: 'Cola paginada de tareas con tipo, severidad, estado y referencias a cliente/caso.',
    expectedStatusCodes: [200, 401, 403],
    queryParamsSchema: { queue: 'all|risk|fraud|quality', page: 'number', limit: 'number' },
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresStressTest: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_OPERATIONS_CATALOGS',
    module: 'operations',
    method: 'GET',
    fullPath: '/api/v1/operations/catalogs',
    routeName: 'Catálogos funcionales',
    businessPurpose: 'Listar catálogos de negocio usados por formularios, scoring, datos maestros y gobierno.',
    businessAction: 'Devuelve catálogos publicados con versiones, items y estado de aprobación.',
    expectedResponseSummary: 'Catálogos activos listos para poblar selects y formularios del portal.',
    expectedStatusCodes: [200, 401, 403],
    riskLevel: 'MEDIUM',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_EXTERNAL_DATA_PROVIDERS_HEALTH',
    module: 'external_data',
    method: 'GET',
    fullPath: '/api/v1/external-data/providers/health',
    routeName: 'Salud proveedores externos',
    businessPurpose: 'Mostrar disponibilidad de SEGIP, burós, QR, bancos y proveedores mock/planificados.',
    businessAction: 'Lee health logs y configuración runtime para decidir si un proveedor puede usarse o debe bloquearse.',
    expectedResponseSummary: 'Estado por proveedor, modo mock/real, latencia, último error seguro y kill-switch.',
    expectedStatusCodes: [200, 401, 403],
    riskLevel: 'HIGH',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
  {
    code: 'GET_OPERATIONS_NOTIFICATIONS_TEMPLATES',
    module: 'notifications',
    method: 'GET',
    fullPath: '/api/v1/operations/notifications/templates',
    routeName: 'Plantillas de notificación',
    businessPurpose: 'Listar plantillas activas para onboarding, cobranza, revisión manual y alertas operativas.',
    businessAction: 'Permite que operaciones revise mensajes sin tocar código.',
    expectedResponseSummary: 'Plantillas por canal, idioma, versión y estado activo.',
    expectedStatusCodes: [200, 401, 403],
    riskLevel: 'MEDIUM',
    isReadonly: true,
    requiresIntegrationTest: true,
    isTestableFromPortal: true,
    reviewStatus: 'APPROVED',
    confidenceLevel: 'HIGH',
  },
];

export type StressProfileSeed = {
  method: string;
  path: string;
  name: string;
  targetRps: number;
  durationSeconds: number;
  concurrency: number;
  maxP95Ms?: number;
  maxErrorRate?: number;
};

export const STRESS_PROFILE_SEEDS: StressProfileSeed[] = [
  {
    method: 'GET',
    path: '/api/v1/health',
    name: 'Healthcheck concurrente',
    targetRps: 80,
    durationSeconds: 60,
    concurrency: 40,
    maxP95Ms: 400,
  },
  {
    method: 'POST',
    path: '/api/v1/auth/login',
    name: 'Login externo bajo carga controlada',
    targetRps: 25,
    durationSeconds: 60,
    concurrency: 20,
    maxP95Ms: 900,
  },
  {
    method: 'POST',
    path: '/api/v1/internal/auth/login',
    name: 'Login panel interno bajo carga',
    targetRps: 20,
    durationSeconds: 60,
    concurrency: 15,
    maxP95Ms: 900,
  },
  {
    method: 'POST',
    path: '/api/v1/customer-onboarding/start',
    name: 'Onboarding start bajo carga',
    targetRps: 10,
    durationSeconds: 60,
    concurrency: 10,
    maxP95Ms: 1500,
  },
  {
    method: 'POST',
    path: '/api/v1/customers/:customerId/risk-assessments',
    name: 'Risk assessment sintético',
    targetRps: 5,
    durationSeconds: 60,
    concurrency: 5,
    maxP95Ms: 1800,
  },
  {
    method: 'GET',
    path: '/api/v1/operations/work-queue',
    name: 'Work queue lectura concurrente',
    targetRps: 30,
    durationSeconds: 60,
    concurrency: 20,
    maxP95Ms: 900,
  },
  {
    method: 'GET',
    path: '/api/v1/systems/endpoints',
    name: 'Catálogo endpoints lectura concurrente',
    targetRps: 35,
    durationSeconds: 60,
    concurrency: 20,
    maxP95Ms: 900,
  },
  {
    method: 'GET',
    path: '/api/v1/systems/data-entities',
    name: 'Catálogo entidades lectura concurrente',
    targetRps: 25,
    durationSeconds: 60,
    concurrency: 15,
    maxP95Ms: 1000,
  },
  {
    method: 'GET',
    path: '/api/v1/operations/catalogs',
    name: 'Catálogos negocio lectura concurrente',
    targetRps: 25,
    durationSeconds: 60,
    concurrency: 15,
    maxP95Ms: 1000,
  },
  {
    method: 'GET',
    path: '/api/v1/external-data/providers/health',
    name: 'Salud proveedores lectura concurrente',
    targetRps: 20,
    durationSeconds: 60,
    concurrency: 10,
    maxP95Ms: 1000,
  },
];
