export type SystemRiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type SystemReviewStatus = 'AUTO_DETECTED' | 'NEEDS_REVIEW' | 'APPROVED' | 'REJECTED';
export type SystemConfidenceLevel = 'LOW' | 'MEDIUM' | 'HIGH';
export type SystemEnvironment = 'LOCAL' | 'STAGING' | 'PRODUCTION_READONLY';
export type SystemTestRunStatus = 'QUEUED' | 'RUNNING' | 'PASSED' | 'FAILED' | 'CANCELLED';
export type SystemTestStepRunStatus = 'QUEUED' | 'RUNNING' | 'PASSED' | 'FAILED' | 'SKIPPED';

export type EndpointSeed = {
  code: string;
  module: string;
  method: string;
  fullPath: string;
  routeName: string;
  businessPurpose: string;
  businessAction?: string;
  controllerName?: string | null;
  handlerName?: string | null;
  expectedResponseSummary?: string;
  expectedStatusCodes?: number[];
  minPayloadSchema?: Record<string, unknown>;
  queryParamsSchema?: Record<string, unknown>;
  pathParamsSchema?: Record<string, unknown>;
  headersSchema?: Record<string, unknown>;
  requiresAuth?: boolean;
  allowedRoles?: string[];
  containsPii?: boolean;
  piiFields?: string[];
  riskLevel?: SystemRiskLevel;
  isDestructive?: boolean;
  isReadonly?: boolean;
  idempotencyRequired?: boolean;
  requiresStressTest?: boolean;
  requiresIntegrationTest?: boolean;
  isTestableFromPortal?: boolean;
  testEnvironmentOnly?: boolean;
  ownerTeam?: string;
  status?: string;
  detectedFrom?: string;
  confidenceLevel?: SystemConfidenceLevel;
  reviewStatus?: SystemReviewStatus;
  sourceFile?: string | null;
  technicalPurpose?: string | null;
  businessValue?: string | null;
  auditStrategy?: string | null;
  decisionUseCases?: string[];
  inputPayloadContract?: Record<string, unknown>;
  outputContract?: Record<string, unknown>;
  payloadOriginSummary?: string | null;
  sideEffectsSummary?: string | null;
  metadataCompletenessScore?: number;
};

export type DataEntitySeed = {
  schemaName: string;
  tableName: string;
  modelName?: string | null;
  entityName: string;
  module: string;
  businessPurpose: string;
  containsPii: boolean;
  containsFinancialData: boolean;
  containsRiskData: boolean;
  containsLegalData: boolean;
  containsDeviceData: boolean;
  containsLocationData: boolean;
  isAuditCritical: boolean;
  detectedFrom: string;
  confidenceLevel: SystemConfidenceLevel;
  reviewStatus: SystemReviewStatus;
  description?: string | null;
  technicalPurpose?: string | null;
  businessProcess?: string | null;
  whyStore?: string | null;
  whoUses?: string[];
  auditUsage?: string | null;
  analysisUsage?: string | null;
  decisionUsage?: string | null;
  dataNature?: string;
  domainCode?: string | null;
  dataGrain?: string | null;
  sourceSystem?: string | null;
  operationalRulesJson?: unknown[];
  qualityRulesJson?: unknown[];
  keyRelationshipsSummary?: string | null;
  relationshipRationale?: string | null;
  internationalizationNotes?: string | null;
  dataOwner?: string;
  retentionPolicyCode?: string | null;
  status?: string;
};

export type ToolSeed = {
  code: string;
  name: string;
  type: string;
  provider?: string | null;
  purpose: string;
  requiredEnvVars?: string[];
  hasSandbox?: boolean;
  healthcheckRoute?: string | null;
  requiresCredentials?: boolean;
  isCritical?: boolean;
  status?: string;
  ownerTeam?: string;
  description?: string | null;
  businessValue?: string | null;
  technicalUsage?: string | null;
  auditNotes?: string | null;
  failureRisks?: string | null;
};
