/**
 * @file Proceso declarado en código: Ciclo contable del ERP (borrador, aprobación, publicación, reverso, factura AR, recibo y cierre).
 * @business Sin este ciclo Atlas no tiene libros: cada venta, cobro y ajuste tiene que acabar en un asiento cuadrado, publicado, inalterable y dentro de un período que se cierra con controles.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; el proceso vive entero en AtlasERPBackend (`src/modules/accounting/`) y el portal admin sólo lo observa.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const ACCOUNTING_DOCUMENTS_CYCLE: WorkflowDefinitionFixture = {
  processId: 'P-23',
  code: 'accounting_documents_cycle',
  version: 'v1',
  name: 'Ciclo contable: borrador → publicar → reversar, factura AR, recibo y cierre de período',
  description:
    'Cómo un documento contable nace en borrador en el ERP, pasa (si lo exige) por la aprobación de alguien distinto de quien lo creó, se publica con huella SHA-256, se reversa sin tocar el original, y cómo la factura AR, el recibo y el cierre de período generan y bloquean sus propios asientos.',
  processType: 'back_office',
  ownerDomain: 'finance',
  ownerRole: 'ERP:CFO',
  priority: 'P0',
  systems: ['ERP_BACKEND', 'DASHBOARDS'],
  narrative: {
    whyExists:
      'Cada venta, cobro y ajuste de Atlas tiene que terminar en un asiento de doble partida que cuadre, que no se pueda editar una vez publicado y que caiga en un período abierto; sin este ciclo no hay balance, ni resultado, ni cierre mensual que un auditor pueda aceptar.',
    whoStartsAndCloses:
      'Lo inicia el contable (rol ERP accountant, o admin/cfo) creando el borrador desde «Documentos contables» del ERP; lo cierra el CFO o un admin al cerrar el período. Si el borrador pide aprobación, decide un CFO o admin que NO sea quien lo creó (ATL-03, provisional hasta DEC-10).',
    startAndEnd:
      'Empieza con un documento DRAFT (POST /accounting/documents) y termina con el documento POSTED y el período cerrado (POST /accounting/closings/periods/close), que emite el aviso accounting.period.closed al buzón de salida; un reverso deja el original REVERSED y un borrador rechazado queda sin publicar.',
    whenItFails:
      'Un asiento descuadrado se rechaza al crear (UNBALANCED_JOURNAL); sin período abierto que cubra la fecha responde ACCOUNTING_PERIOD_NOT_RESOLVED; publicar un borrador pendiente da 409 ACCOUNTING_DOCUMENT_APPROVAL_REQUIRED; el cierre con borradores o controles en rojo da PERIOD_CLOSE_CONTROLS_FAILED. Los eventos que el trabajador del buzón no entrega quedan como «muertos» para que Finanzas los reenvíe.',
    healthIndicator:
      'Borradores DRAFT con más de un día, asientos descuadrados y documentos publicados sin asiento (los mide el tablero de Contabilidad), días desde el fin del último período abierto, y eventos muertos en el buzón contable (GET /accounting/outbox/events/dead) en cero.',
  },
  instanceEntity: {
    system: 'ERP_BACKEND',
    schema: 'atlas_accounting',
    table: 'accounting_document',
    idColumn: 'id',
    statusColumn: 'status',
    labelColumn: 'document_no',
    openStatuses: ['DRAFT'],
  },
  success: 'El documento queda POSTED con huella SHA-256, el período se cierra sin bloqueos y el evento contable sale del buzón.',
  failure: 'El borrador se rechaza (descuadre, período cerrado, aprobación pendiente o rechazada) o el cierre se bloquea por controles.',
  sources: [
    'AtlasERPBackend/docs/architecture/flows.md (Flujos del módulo contable y flujos endurecidos)',
    'AtlasERPBackend/src/modules/accounting/documents/controllers/accounting-documents.controller.ts',
    'AtlasERPBackend/src/modules/accounting/documents/domain/document-approval.ts',
    'AtlasERPBackend/src/modules/accounting/closing/controllers/closing.controller.ts',
    'AtlasERPBackend/src/modules/accounting/receipts/controllers/receipts.controller.ts',
    'AtlasERPBackend/src/modules/accounting/billing/controllers/billing.controller.ts',
    'AtlasERPBackend/src/modules/accounting/outbox/outbox-operations.controller.ts',
    'AtlasERPBackend/src/database/models/accounting_document.model.ts',
    'AtlasERPFrontend/services/accountingService.ts',
    'AtlasDashboardsBackend/src/modules/contabilidad/contabilidad.controller.ts',
    'memoria atlas-erp-contabilidad-deduce',
    'memoria atlas-erp-plan-de-cuentas-cargado',
    'memoria atlas-plan-produccion-siete-repos (ATL-03, DEC-10)',
  ],
  metadata: {
    approvalStatusColumn: 'approval_status',
    approvalStatuses: ['NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED'],
    gaps: [
      'El estado «PENDING_APPROVAL» del inventario no existe: la aprobación va en approval_status (NOT_REQUIRED/PENDING/APPROVED/REJECTED) con el documento en DRAFT.',
      'Aprobar y rechazar (PATCH :id/approve|reject) no tienen pantalla en el ERP: services/accountingService.ts no los llama.',
      'Las operaciones del buzón contable (status, dead, replay) no tienen pantalla en el ERP.',
      'DEC-10 (umbrales y quién aprueba) sigue abierta: hoy el cliente elige NOT_REQUIRED o PENDING al crear.',
    ],
  },
  stages: [
    {
      code: 'accounting_draft',
      name: 'Crear el borrador',
      description:
        'El contable registra el documento con sus líneas. El ERP deduce libro, período y cuentas cuando no se dan, exige doble partida y crea documento, asiento, líneas, auditoría y evento de salida en una transacción.',
      module: 'accounting.documents',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/contabilidad/documentos/crear',
      entry: true,
      roles: ['admin', 'accountant', 'cfo'],
      resultingStates: ['DRAFT'],
      steps: [
        {
          code: 'accounting.document_create',
          name: 'Crear el documento en borrador',
          description:
            'Valida el cuerpo, que cada línea tenga débito o crédito y que cuadre; deduce libro y período abierto por la fecha. approvalStatus sólo admite NOT_REQUIRED (por omisión) o PENDING.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/accounting/documents',
          roles: ['admin', 'accountant', 'cfo'],
          resultingStates: ['DRAFT'],
          input: {
            documentNo: 'string',
            legalEntityId: 'uuid',
            postingDate: 'date',
            approvalStatus: 'NOT_REQUIRED | PENDING',
            lines: 'JournalLine[]',
          },
          errors: [
            '422 ACCOUNTING_DOCUMENT_APPROVAL_NOT_CLIENT_SETTABLE',
            'UNBALANCED_JOURNAL',
            'ACCOUNTING_PERIOD_NOT_RESOLVED',
            'LEDGER_NOT_RESOLVED',
            'POSTING_DATE_OUTSIDE_PERIOD',
            'DIRECT_MANUAL_POSTING_TO_CONTROL_ACCOUNT_BLOCKED',
          ],
        },
        {
          code: 'accounting.document_create_bulk',
          name: 'Crear borradores en lote',
          description:
            'Hasta 50 documentos con sus asientos en una transacción, con la misma validación y un registro en la bitácora de negocio.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/accounting/documents/bulk',
          roles: ['admin', 'accountant', 'cfo'],
          optional: true,
          input: { items: 'CreateAccountingDocument[] (≤50)', batchExternalId: 'string?' },
        },
        {
          code: 'accounting.document_list',
          name: 'Listar documentos contables',
          description: 'La tabla de «Documentos contables», con su estado y su estado de aprobación.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/documents',
          roles: ['admin', 'accountant', 'cfo'],
        },
        {
          code: 'accounting.document_get',
          name: 'Leer un documento',
          description: 'Detalle del documento con su asiento y líneas.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/documents/:id',
          roles: ['admin', 'accountant', 'cfo'],
          errors: ['404 ACCOUNTING_DOCUMENT_NOT_FOUND'],
        },
      ],
    },
    {
      code: 'accounting_approval',
      name: 'Aprobar o rechazar el borrador',
      description:
        'Sólo para borradores creados con approvalStatus PENDING (ATL-03). Decide un CFO o admin distinto del creador; la carrera entre aprobar y rechazar la resuelve un UPDATE condicionado. Sin pantalla en el ERP.',
      module: 'accounting.documents',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      optional: true,
      roles: ['admin', 'cfo'],
      requiredStates: ['DRAFT'],
      steps: [
        {
          code: 'accounting.document_approve',
          name: 'Aprobar el borrador',
          description: 'Pasa approval_status de PENDING a APPROVED y registra approved_by; quien lo creó recibe 403.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/accounting/documents/:id/approve',
          roles: ['admin', 'cfo'],
          optional: true,
          requiredStates: ['DRAFT'],
          input: { reason: 'string?' },
          errors: ['403 ACCOUNTING_DOCUMENT_SELF_APPROVAL_FORBIDDEN', '409 ACCOUNTING_DOCUMENT_NOT_PENDING_APPROVAL'],
        },
        {
          code: 'accounting.document_reject',
          name: 'Rechazar el borrador',
          description: 'Pasa approval_status a REJECTED: terminal, el documento ya no se publica.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/accounting/documents/:id/reject',
          roles: ['admin', 'cfo'],
          optional: true,
          requiredStates: ['DRAFT'],
          input: { reason: 'string?' },
          errors: ['403 ACCOUNTING_DOCUMENT_SELF_APPROVAL_FORBIDDEN', '409 ACCOUNTING_DOCUMENT_NOT_PENDING_APPROVAL'],
        },
      ],
    },
    {
      code: 'accounting_posting',
      name: 'Publicar el documento',
      description:
        'Recalcula la cuadratura, valida período, libro, entidad y cuentas, calcula la huella SHA-256 y marca documento y asiento POSTED. Desde ahí los disparadores de la base bloquean la edición.',
      module: 'accounting.documents',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/contabilidad/documentos',
      roles: ['admin', 'accountant', 'cfo'],
      requiredStates: ['DRAFT'],
      resultingStates: ['POSTED'],
      steps: [
        {
          code: 'accounting.document_post',
          name: 'Publicar',
          description: 'Exige DRAFT y approval_status NOT_REQUIRED, o APPROVED con aprobador registrado.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/accounting/documents/:id/post',
          roles: ['admin', 'accountant', 'cfo'],
          requiredStates: ['DRAFT'],
          resultingStates: ['POSTED'],
          errors: ['409 ACCOUNTING_DOCUMENT_APPROVAL_REQUIRED', 'ACCOUNTING_PERIOD_CLOSED', 'UNBALANCED_JOURNAL'],
        },
      ],
    },
    {
      code: 'accounting_reversal',
      name: 'Reversar un documento publicado',
      description:
        'Nunca se edita un asiento publicado: se crea un documento reverso con débitos y créditos invertidos, se publica y el original queda REVERSED apuntando a él. Un segundo reverso se rechaza.',
      module: 'accounting.documents',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/contabilidad/documentos',
      optional: true,
      roles: ['admin', 'accountant', 'cfo'],
      requiredStates: ['POSTED'],
      resultingStates: ['REVERSED'],
      steps: [
        {
          code: 'accounting.document_reverse',
          name: 'Reversar',
          description: 'Bloquea el original con FOR UPDATE, comprueba que esté POSTED y sin reverso activo, crea y publica el reverso.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/accounting/documents/:id/reverse',
          roles: ['admin', 'accountant', 'cfo'],
          optional: true,
          requiredStates: ['POSTED'],
          resultingStates: ['REVERSED'],
          errors: ['ACCOUNTING_DOCUMENT_NOT_POSTED', 'ACCOUNTING_PERIOD_CLOSED'],
        },
      ],
    },
    {
      code: 'accounting_ar_invoice',
      name: 'Emitir la factura AR',
      description:
        'La factura a cobrar genera y publica su propio asiento en la misma transacción: debe CxC por el bruto, haber ingreso por el neto e IVA débito si aplica. La cuenta por cobrar y el IVA se deducen.',
      module: 'accounting.billing',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/contabilidad/factura-ar',
      optional: true,
      roles: ['admin', 'accountant'],
      steps: [
        {
          code: 'accounting.ar_invoice_create',
          name: 'Emitir factura AR',
          description:
            'Valida socio con rol CUSTOMER, MERCHANT o INTERCOMPANY, contrato si lo hay y datos fiscales; crea factura, líneas y asiento publicado.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/accounting/billing/ar-invoices',
          roles: ['admin', 'accountant'],
          optional: true,
          errors: ['PARTNER_DEFAULT_ACCOUNT_NOT_SET', 'TAX_CODE_NOT_RESOLVED', 'INVOICE_CONTRACT_MISMATCH', 'CONTRACT_NOT_ACTIVE'],
        },
        {
          code: 'accounting.ar_invoice_list',
          name: 'Listar facturas AR',
          description: 'Facturas emitidas con su saldo abierto.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/billing/ar-invoices',
          roles: ['admin', 'accountant'],
          optional: true,
        },
        {
          code: 'accounting.ar_invoice_get',
          name: 'Leer una factura AR',
          description: 'Detalle de la factura; también alimenta su PDF.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/billing/ar-invoices/:id',
          roles: ['admin', 'accountant'],
          optional: true,
          errors: ['404 AR_INVOICE_NOT_FOUND'],
        },
      ],
    },
    {
      code: 'accounting_receipt',
      name: 'Registrar el recibo',
      description:
        'El cobro se asigna a facturas AR abiertas del mismo pagador; cada factura se bloquea, se rechaza la sobreasignación y se genera el asiento banco contra CxC. La factura pasa a PARTIALLY_PAID o PAID.',
      module: 'accounting.receipts',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/contabilidad/recibos/crear',
      optional: true,
      roles: ['admin', 'accountant', 'treasury'],
      steps: [
        {
          code: 'accounting.receipt_create',
          name: 'Registrar recibo',
          description:
            'Crea recibo, asignaciones y asiento publicado; la cuenta del banco se deduce de la cuenta bancaria elegida o de la del banco de la casa.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/accounting/receipts',
          roles: ['admin', 'accountant', 'treasury'],
          optional: true,
          errors: [
            'RECEIPT_ALLOCATION_TOTAL_MISMATCH',
            'AR_INVOICE_ALLOCATION_EXCEEDS_OPEN_BALANCE',
            'AR_INVOICE_NOT_OPEN',
            'BANK_GL_ACCOUNT_NOT_RESOLVED',
          ],
        },
        {
          code: 'accounting.receipt_list',
          name: 'Listar recibos',
          description: 'La tabla de «Recibos».',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/receipts',
          roles: ['admin', 'accountant', 'treasury'],
          optional: true,
        },
      ],
    },
    {
      code: 'accounting_period_close',
      name: 'Cerrar el período',
      description:
        'El CFO o un admin pide el cierre: se calculan los controles (sin borradores, entre otros), se crea el close_run con su informe, el período queda cerrado y sale accounting.period.closed. Reabrir exige motivo.',
      module: 'accounting.closing',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/contabilidad/cierres',
      terminal: true,
      roles: ['admin', 'cfo'],
      steps: [
        {
          code: 'accounting.periods_list',
          name: 'Ver los períodos',
          description: 'Lista los períodos contables de la estructura financiera con su estado.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/financial-structure/periods',
        },
        {
          code: 'accounting.period_close',
          name: 'Cerrar período',
          description: 'Rechaza el cierre si algún control bloquea; si no, crea close_run con control_report_json y cierra.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/accounting/closings/periods/close',
          roles: ['admin', 'cfo'],
          input: { legalEntityId: 'uuid', periodId: 'uuid', closeType: 'MONTHLY | …' },
          errors: ['PERIOD_CLOSE_CONTROLS_FAILED', 'ACCOUNTING_PERIOD_ALREADY_CLOSED', 'ACCOUNTING_PERIOD_NOT_FOUND'],
        },
        {
          code: 'accounting.period_reopen',
          name: 'Reabrir período',
          description: 'Vuelve a abrir un período cerrado, con motivo obligatorio.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/accounting/closings/periods/reopen',
          roles: ['admin', 'cfo'],
          optional: true,
          input: { periodId: 'uuid', reason: 'string' },
          errors: ['ACCOUNTING_PERIOD_ALREADY_OPEN'],
        },
      ],
    },
    {
      code: 'accounting_outbox_delivery',
      name: 'Entregar los eventos contables',
      description:
        'Un trabajador separado del proceso web lee event_outbox sin publicar con FOR UPDATE SKIP LOCKED, los publica y marca published_at.',
      module: 'accounting.outbox',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'accounting.outbox_worker',
          name: 'Trabajador del buzón contable',
          description:
            'Proceso aparte (`npm run worker:outbox`) con apagado controlado; hoy la publicación sólo escribe en el log (memoria atlas-dashboards-plan).',
          kind: 'job',
          system: 'ERP_BACKEND',
          job: 'worker:outbox (src/workers/outbox/outbox.worker.ts)',
        },
      ],
    },
    {
      code: 'accounting_outbox_operations',
      name: 'Vigilar y reenviar eventos muertos',
      description: 'Finanzas mira el estado del buzón y reenvía los eventos que agotaron reintentos. Sin pantalla en el ERP.',
      module: 'accounting.outbox',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      optional: true,
      roles: ['ADMIN', 'CFO', 'FINANCE'],
      steps: [
        {
          code: 'accounting.outbox_status',
          name: 'Estado del buzón',
          description: 'Cuántos eventos esperan, cuántos se entregaron y cuántos murieron.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/outbox/status',
          roles: ['ADMIN', 'CFO', 'FINANCE'],
          optional: true,
        },
        {
          code: 'accounting.outbox_dead',
          name: 'Eventos muertos',
          description: 'Los eventos que el trabajador no pudo entregar.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/accounting/outbox/events/dead',
          roles: ['ADMIN', 'CFO', 'FINANCE'],
          optional: true,
        },
        {
          code: 'accounting.outbox_replay',
          name: 'Reenviar un evento',
          description: 'Vuelve a poner en cola un evento muerto por su clave.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/accounting/outbox/events/:eventKey/replay',
          roles: ['ADMIN', 'CFO', 'FINANCE'],
          optional: true,
          repeatable: true,
        },
      ],
    },
    {
      code: 'accounting_dashboards_reading',
      name: 'Leer los libros en el tablero de Contabilidad',
      description:
        'El tablero de Contabilidad lee el libro del ERP en sólo lectura: diario, mayor, balance, resultados y flujo de caja. No escribe nada en el ciclo; es donde se ven los descuadres.',
      module: 'dashboards.contabilidad',
      actor: 'internal_user',
      client: 'DASHBOARDS_PORTAL',
      screen: '/tableros/[slug]',
      optional: true,
      steps: [
        {
          code: 'accounting.dashboards_diario',
          name: 'Libro diario',
          description: 'Asientos publicados del período, leídos de la base del ERP.',
          system: 'DASHBOARDS',
          method: 'GET',
          path: '/contabilidad/diario',
          optional: true,
        },
        {
          code: 'accounting.dashboards_mayor',
          name: 'Libro mayor',
          description: 'Movimientos por cuenta.',
          system: 'DASHBOARDS',
          method: 'GET',
          path: '/contabilidad/mayor',
          optional: true,
        },
        {
          code: 'accounting.dashboards_balance',
          name: 'Balance por grupo',
          description: 'Balance según el árbol de grupos de cuenta; el signo se invierte en pasivo, patrimonio e ingresos.',
          system: 'DASHBOARDS',
          method: 'GET',
          path: '/contabilidad/balance',
          optional: true,
        },
        {
          code: 'accounting.dashboards_resultados',
          name: 'Estado de resultados',
          description: 'Resultado del ejercicio.',
          system: 'DASHBOARDS',
          method: 'GET',
          path: '/contabilidad/resultados',
          optional: true,
        },
      ],
    },
  ],
};
