/**
 * @file Proceso declarado en código: Alta de cuenta: de la primera pantalla a la sesión iniciada.
 * @business Sin cuenta verificada y sesión no hay cliente: este proceso crea la identidad digital de la persona, verifica que el correo y el teléfono son suyos y le entrega una sesión segura con la que recorre todo lo demás.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; portada de la siembra demo el 2026-09-26 sin perder pasos, transiciones ni dependencias.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const ACCOUNT_SIGNUP_TO_LOGIN: WorkflowDefinitionFixture = {
  processId: 'P-01',
  code: 'account_signup_to_login',
  version: 'v1',
  name: 'Alta de cuenta: de la primera pantalla a la sesión iniciada',
  description:
    'Qué endpoints recorre un usuario para crearse una cuenta y quedar logueado: textos legales, alta, verificación de contacto, consentimientos y login (con su segundo factor y su recuperación de acceso).',
  processType: 'customer_journey',
  ownerDomain: 'customer_onboarding',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Sin cuenta verificada y sesión no hay cliente: este proceso crea la identidad digital de la persona, verifica que el correo y el teléfono son suyos y le entrega una sesión segura con la que recorre todo lo demás.',
    whoStartsAndCloses:
      'Lo inicia el cliente al pulsar «Crear cuenta» en la app y lo cierra él mismo al iniciar sesión; el operador interno sólo interviene desde «Contactos pendientes» cuando la verificación no llega.',
    startAndEnd:
      'Empieza con el registro (POST /customer-onboarding/start) y termina con una sesión válida (login + refresh) y el estado de alta leído al entrar; el código OTP se pide al abrir la pantalla, no con un botón.',
    whenItFails:
      'Un correo o teléfono sin verificar deja al cliente en `registered` y aparece en la cola de contactos pendientes del portal; el 409 VERIFICATION_RATE_LIMITED no es un error sino un código ya enviado, y el login con credenciales inválidas responde 401 sin revelar cuál falló.',
    healthIndicator:
      'Tasa de registros que verifican contacto en 24 h y tasa de 429 en login; la primera sale de customers + contact verifications, la segunda del limitador de acceso.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'customer',
    table: 'customers',
    idColumn: '_id',
    statusColumn: 'lifecycle_status',
    labelColumn: 'customer_code',
    openStatuses: ['registered', 'onboarding_in_progress'],
  },
  success: 'El cliente existe, tiene contacto verificado y una sesión iniciada con token vigente.',
  failure: 'El alta queda sin credenciales, sin contacto verificado o el login se bloquea por intentos.',
  sources: ['src/database/seeders/demo/referencia.seed-data.ts'],
  stages: [
    {
      code: 'signup_legal_preview',
      name: 'Textos legales vigentes',
      description: 'La app muestra los términos y la política de privacidad ANTES de pedir un solo dato. Es público a propósito.',
      module: 'consents',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      steps: [
        {
          code: 'signup.consent_documents',
          name: 'Consultar los documentos legales vigentes',
          description: 'Devuelve la versión publicada de cada documento. La versión que se muestre es la que después hay que aceptar.',
          method: 'GET',
          path: '/consent-documents/active',
          auth: false,
          output: {
            documents: 'ConsentDocumentDto[]',
          },
        },
      ],
    },
    {
      code: 'signup_phone_trust',
      name: 'Confianza del teléfono (WhatsApp)',
      description: 'Verificación alternativa del teléfono con el proveedor externo. Opcional: refuerza la confianza del contacto.',
      module: 'external_data',
      actor: 'external_provider',
      client: 'BLOCK',
      parent: 'signup_contact_verification',
      optional: true,
      steps: [
        {
          code: 'signup.whatsapp_start',
          name: 'Enviar el código por WhatsApp',
          description: 'Pide al proveedor que envíe el código de verificación al número declarado.',
          method: 'POST',
          path: '/whatsapp/verification/start',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          input: {
            phone: 'string',
            customerId: 'string',
          },
          errors: ['424 PROVIDER_UNAVAILABLE', '429 RATE_LIMITED'],
          successStatus: [200, 202],
        },
        {
          code: 'signup.whatsapp_confirm',
          name: 'Confirmar el código de WhatsApp',
          description: 'Valida el código recibido y marca el teléfono como verificado por el proveedor.',
          method: 'POST',
          path: '/whatsapp/verification/confirm',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          input: {
            code: 'string',
            customerId: 'string',
          },
          errors: ['422 INVALID_CODE'],
        },
      ],
    },
    {
      code: 'signup_account_creation',
      name: 'Creación de la cuenta',
      description: 'Crea el cliente y su expediente de onboarding. A partir de aquí existe un customerId al que colgar todo lo demás.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      resultingStates: ['registered'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['NO_CREDENTIALS'],
      },
      steps: [
        {
          code: 'signup.start',
          name: 'Iniciar el alta',
          description:
            'Crea el cliente en estado registrado y abre su onboarding. Devuelve el customerId que usan todos los pasos siguientes.',
          method: 'POST',
          path: '/customer-onboarding/start',
          auth: false,
          idempotencyKey: true,
          resultingStates: ['registered'],
          input: {
            email: 'string',
            phone: 'string',
            channel: 'mobile_app | web',
            documentNumber: 'string',
          },
          output: {
            status: 'registered',
            customerId: 'string',
            onboardingId: 'string',
          },
          errors: ['409 CUSTOMER_ALREADY_EXISTS', '422 VALIDATION_ERROR'],
          events: [],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'signup_credentials',
      name: 'Provisión de credenciales',
      description: 'Alta de la credencial de acceso. No la ejecuta el cliente: es una operación de administración.',
      module: 'auth',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      optional: true,
      roles: ['admin', 'platform_admin'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['NO_CREDENTIALS'],
      },
      steps: [
        {
          code: 'signup.provision_credentials',
          name: 'Provisionar credenciales de acceso',
          description: 'Crea o repone la credencial del cliente. Requiere un token de administración: no es un endpoint de la app.',
          method: 'POST',
          path: '/auth/provision-credentials',
          roles: ['admin', 'platform_admin'],
          optional: true,
          input: {
            password: 'string (temporal)',
            customerId: 'string',
          },
          output: {
            provisioned: 'boolean',
          },
          errors: ['403 ROLE_NOT_AUTHORIZED', '404 CUSTOMER_NOT_FOUND'],
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'signup_contact_verification',
      name: 'Verificación de contacto',
      description: 'Registra correo y teléfono y comprueba que son del usuario con un código de un solo uso.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      completionRule: {
        type: 'onboarding_section',
        sectionCode: 'contact_verification',
      },
      steps: [
        {
          code: 'signup.contact_methods',
          name: 'Registrar los medios de contacto',
          description: 'Declara el correo y el teléfono del cliente sobre los que se hará la verificación.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-methods',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          input: {
            email: 'string',
            phone: 'string',
          },
          errors: ['409 CONTACT_ALREADY_VERIFIED', '422 VALIDATION_ERROR'],
          successStatus: [200, 201],
        },
        {
          code: 'signup.contact_request',
          name: 'Solicitar el código de verificación',
          description: 'Dispara el envío del código al medio elegido. Tiene límite de reintentos por ventana de tiempo.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-verification/request',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          input: {
            channel: 'email | sms',
          },
          errors: ['429 TOO_MANY_REQUESTS'],
          events: [],
          successStatus: [200, 202],
        },
        {
          code: 'signup.contact_submit',
          name: 'Enviar el código recibido',
          description: 'Valida el código. Con esto la sección de contacto queda completa y deja de bloquear el avance.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-verification/submit',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          input: {
            code: 'string',
            channel: 'email | sms',
          },
          errors: ['410 CODE_EXPIRED', '422 INVALID_CODE'],
          events: [],
        },
      ],
    },
    {
      code: 'signup_privacy_consents',
      name: 'Consentimientos de privacidad',
      description: 'Registra la aceptación de los documentos que se mostraron al principio. Sin esto el expediente queda bloqueado.',
      module: 'customer_privacy',
      actor: 'customer',
      client: 'CONSUMER_APP',
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['CONSENT_MISSING'],
      },
      steps: [
        {
          code: 'signup.consent_decisions',
          name: 'Registrar las decisiones de consentimiento',
          description: 'Acepta o rechaza cada documento, con la versión exacta que se mostró.',
          method: 'POST',
          path: '/customers/:customerId/privacy/consent-decisions',
          roles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
          input: {
            decisions: '[{ documentCode, version, accepted }]',
          },
          errors: ['409 CONSENT_VERSION_OUTDATED', '422 VALIDATION_ERROR'],
          events: [],
          successStatus: [200, 201],
        },
      ],
    },
    {
      code: 'signup_first_login',
      name: 'Primera sesión iniciada',
      description: 'El objetivo del recorrido: el usuario obtiene su token y la app confirma quién es.',
      module: 'auth',
      actor: 'customer',
      client: 'CONSUMER_APP',
      terminal: true,
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['NO_CREDENTIALS'],
      },
      steps: [
        {
          code: 'signup.login',
          name: 'Autenticarse con usuario y contraseña',
          description: 'Devuelve el token de acceso, o indica que hace falta un segundo factor.',
          method: 'POST',
          path: '/auth/login',
          auth: false,
          input: {
            deviceId: 'string',
            password: 'string',
            username: 'string',
          },
          output: {
            accessToken: 'string',
            mfaRequired: 'boolean',
            refreshToken: 'string',
          },
          errors: ['401 INVALID_CREDENTIALS', '423 ACCOUNT_LOCKED', '429 TOO_MANY_ATTEMPTS'],
          events: [],
        },
        {
          code: 'signup.mfa',
          name: 'Completar el segundo factor',
          description: 'Sólo cuando el login lo pide. Canjea el desafío por el token definitivo.',
          method: 'POST',
          path: '/auth/mfa',
          auth: false,
          optional: true,
          input: {
            code: 'string',
            challengeId: 'string',
          },
          output: {
            accessToken: 'string',
            refreshToken: 'string',
          },
          errors: ['401 INVALID_MFA_CODE', '410 CHALLENGE_EXPIRED'],
        },
        {
          code: 'signup.login_pin',
          name: 'Autenticarse con PIN',
          description: 'Camino alternativo para el dispositivo ya registrado: evita teclear la contraseña en cada apertura.',
          method: 'POST',
          path: '/auth/login/pin',
          auth: false,
          optional: true,
          input: {
            pin: 'string',
            deviceId: 'string',
            customerId: 'string',
          },
          errors: ['401 INVALID_PIN', '409 DEVICE_NOT_ENROLLED'],
        },
        {
          code: 'signup.me',
          name: 'Confirmar el actor autenticado',
          description: 'Cierra el recorrido: con el token en la mano, la app confirma identidad, rol y tenant.',
          method: 'GET',
          path: '/auth/me',
          output: {
            sub: 'string',
            role: 'string',
            tenantId: 'string',
            customerId: 'string',
          },
          errors: ['401 TOKEN_EXPIRED'],
        },
      ],
    },
    {
      code: 'signup_recovery',
      name: 'Recuperación de acceso',
      description: 'Rama de excepción: el usuario no logra entrar y restablece su contraseña antes de reintentar.',
      module: 'auth',
      actor: 'customer',
      client: 'CONSUMER_APP',
      optional: true,
      steps: [
        {
          code: 'signup.password_reset_request',
          name: 'Pedir el restablecimiento de contraseña',
          description: 'Envía el enlace o código de restablecimiento al medio verificado.',
          method: 'POST',
          path: '/auth/password-reset/request',
          auth: false,
          optional: true,
          input: {
            username: 'string',
          },
          errors: ['429 TOO_MANY_REQUESTS'],
          successStatus: [200, 202],
        },
        {
          code: 'signup.password_reset_confirm',
          name: 'Confirmar la nueva contraseña',
          description: 'Canjea el código por una contraseña nueva y devuelve al usuario al login.',
          method: 'POST',
          path: '/auth/password-reset/confirm',
          auth: false,
          optional: true,
          input: {
            token: 'string',
            newPassword: 'string',
          },
          errors: ['410 RESET_TOKEN_EXPIRED', '422 WEAK_PASSWORD'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'signup.entry',
      from: null,
      to: 'signup.consent_documents',
      condition: 'always',
      description: 'Entrada: la app muestra los textos legales antes de pedir datos.',
      isDefault: true,
    },
    {
      code: 'signup.docs_to_start',
      from: 'signup.consent_documents',
      to: 'signup.start',
      condition: 'on_success',
      description: 'Con los textos a la vista, el usuario inicia el alta.',
      isDefault: true,
    },
    {
      code: 'signup.start_to_contact',
      from: 'signup.start',
      to: 'signup.contact_methods',
      condition: 'on_success',
      description: 'Creado el cliente, se declaran sus medios de contacto.',
      isDefault: true,
    },
    {
      code: 'signup.start_to_credentials',
      from: 'signup.start',
      to: 'signup.provision_credentials',
      condition: 'conditional',
      expression: {
        credentialsProvisionedByOperator: true,
      },
      description: 'Alta asistida: un operador provisiona la credencial.',
    },
    {
      code: 'signup.contact_to_request',
      from: 'signup.contact_methods',
      to: 'signup.contact_request',
      condition: 'on_success',
      description: 'Declarado el medio, se pide el código.',
      isDefault: true,
    },
    {
      code: 'signup.request_to_submit',
      from: 'signup.contact_request',
      to: 'signup.contact_submit',
      condition: 'on_success',
      description: 'El usuario introduce el código recibido.',
      isDefault: true,
    },
    {
      code: 'signup.request_to_whatsapp',
      from: 'signup.contact_request',
      to: 'signup.whatsapp_start',
      condition: 'conditional',
      expression: {
        channel: 'whatsapp',
      },
      description: 'Verificación alternativa por WhatsApp.',
    },
    {
      code: 'signup.whatsapp_flow',
      from: 'signup.whatsapp_start',
      to: 'signup.whatsapp_confirm',
      condition: 'on_success',
      description: 'Enviado el código, el usuario lo confirma.',
    },
    {
      code: 'signup.submit_retry',
      from: 'signup.contact_submit',
      to: 'signup.contact_request',
      condition: 'on_error',
      description: 'Código vencido o incorrecto: se vuelve a pedir.',
    },
    {
      code: 'signup.submit_to_consents',
      from: 'signup.contact_submit',
      to: 'signup.consent_decisions',
      condition: 'on_success',
      description: 'Contacto verificado: se registran los consentimientos.',
      isDefault: true,
    },
    {
      code: 'signup.consents_to_login',
      from: 'signup.consent_decisions',
      to: 'signup.login',
      condition: 'on_success',
      description: 'Con el expediente abierto, el usuario inicia sesión.',
      isDefault: true,
    },
    {
      code: 'signup.login_to_mfa',
      from: 'signup.login',
      to: 'signup.mfa',
      condition: 'conditional',
      expression: {
        mfaRequired: true,
      },
      description: 'El login pidió segundo factor.',
    },
    {
      code: 'signup.login_to_me',
      from: 'signup.login',
      to: 'signup.me',
      condition: 'on_success',
      description: 'Sin segundo factor pendiente, la app confirma la identidad.',
      isDefault: true,
    },
    {
      code: 'signup.mfa_to_me',
      from: 'signup.mfa',
      to: 'signup.me',
      condition: 'on_success',
      description: 'Superado el segundo factor, se confirma la identidad.',
    },
    {
      code: 'signup.pin_to_me',
      from: 'signup.login_pin',
      to: 'signup.me',
      condition: 'on_success',
      description: 'Acceso por PIN en dispositivo ya registrado.',
    },
    {
      code: 'signup.login_to_recovery',
      from: 'signup.login',
      to: 'signup.password_reset_request',
      condition: 'on_error',
      description: 'Credenciales inválidas o cuenta bloqueada: recuperación de acceso.',
    },
    {
      code: 'signup.recovery_flow',
      from: 'signup.password_reset_request',
      to: 'signup.password_reset_confirm',
      condition: 'on_success',
      description: 'Con el código en el correo, se fija la contraseña nueva.',
    },
    {
      code: 'signup.recovery_to_login',
      from: 'signup.password_reset_confirm',
      to: 'signup.login',
      condition: 'on_success',
      description: 'Restablecida la contraseña, el usuario vuelve al login.',
    },
    {
      code: 'signup.exit',
      from: 'signup.me',
      to: null,
      condition: 'always',
      description: 'Salida: la sesión está iniciada y la app puede continuar.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'signup.contact_methods',
      dependsOn: 'signup.start',
      type: 'requires_data',
      description: 'Sin customerId no hay a quién colgarle el contacto.',
    },
    {
      step: 'signup.contact_request',
      dependsOn: 'signup.contact_methods',
      type: 'requires_completion',
      description: 'No se puede pedir código para un medio que no está declarado.',
    },
    {
      step: 'signup.contact_submit',
      dependsOn: 'signup.contact_request',
      type: 'requires_completion',
      description: 'El código a validar lo emite la solicitud anterior.',
    },
    {
      step: 'signup.consent_decisions',
      dependsOn: 'signup.consent_documents',
      type: 'requires_data',
      description: 'Se acepta la versión exacta que se mostró.',
    },
    {
      step: 'signup.login',
      dependsOn: 'signup.provision_credentials',
      type: 'soft',
      description: 'Sin credencial provisionada el login responde 401.',
    },
    {
      step: 'signup.whatsapp_confirm',
      dependsOn: 'signup.whatsapp_start',
      type: 'requires_completion',
      description: 'El código a confirmar lo envía el paso anterior.',
    },
    {
      step: 'signup.me',
      dependsOn: 'signup.login',
      type: 'requires_data',
      description: 'Necesita el token que devuelve el login.',
    },
  ],
};
