/**
 * @file Proceso declarado en código: Publicidad externa (ATLAS Ads): anunciante, perfil fiscal, campaña, moderación, entrega y facturación.
 * @business Atlas vende espacio publicitario a terceros: este proceso decide quién puede anunciar, qué anuncio se muestra y cuánto se le cobra, sin entregar ni facturar nada que no pasó moderación.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; el proceso vive entero en AtlasERPBackend (`src/modules/ads/`), con roles propios `ADS_*`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const ADS_ADVERTISERS: WorkflowDefinitionFixture = {
  processId: 'P-25',
  code: 'ads_advertisers',
  version: 'v1',
  name: 'Publicidad externa (ATLAS Ads): alta de anunciante, perfil fiscal, estado y moderación',
  description:
    'Del alta del anunciante en el ERP a la campaña activa, moderada, entregada y facturada: perfil fiscal obligatorio, envío a moderación, decisión del moderador, activación sólo con aprobación, eventos facturables contra presupuesto y cierre de facturación por período.',
  processType: 'back_office',
  ownerDomain: 'advertising',
  ownerRole: 'ERP:ADS_ADMIN_MANAGER',
  priority: 'P2',
  systems: ['ERP_BACKEND'],
  narrative: {
    whyExists:
      'Atlas vende espacio publicitario a anunciantes externos. Hace falta saber quién anuncia (con su NIT y perfil fiscal), qué anuncio pasó la moderación antes de mostrarse y cuánto se consumió del presupuesto, para no entregar ni cobrar publicidad que nadie aprobó.',
    whoStartsAndCloses:
      'Lo inicia un gestor de publicidad (rol ERP ADS_ADMIN_MANAGER) al dar de alta al anunciante en «Operaciones › Ads»; modera un ADS_MODERATOR o ADS_COMPLIANCE_ADMIN y lo cierra Finanzas de publicidad (ADS_FINANCE) al cerrar la facturación del período y registrar el pago.',
    startAndEnd:
      'Empieza con el anunciante en PENDING_REVIEW (POST /admin/ads/advertisers) y la campaña en DRAFT; termina con la campaña ACTIVE, PAUSED, ENDED o ARCHIVED tras pasar por moderación, y con la factura del período en PAID o PARTIALLY_PAID. Una campaña ENDED o ARCHIVED no vuelve a ACTIVE.',
    whenItFails:
      'Activar una campaña sin aprobación de moderación responde 409 CAMPAIGN_NOT_APPROVED; un anunciante REJECTED no pasa directo a ACTIVE; sin perfil fiscal activo no se cierra facturación; un evento con fraude por encima del umbral se guarda como no facturable. Cada cambio queda en la auditoría de publicidad con su severidad.',
    healthIndicator:
      'Cola de moderación sin casos viejos (GET /admin/ads/moderation/queue), tasa de eventos inválidos y alertas del tablero de publicidad (GET /admin/ads/dashboard), y facturas del período sin duplicar por anunciante, moneda y rango.',
  },
  instanceEntity: {
    system: 'ERP_BACKEND',
    schema: 'atlas_ads',
    table: 'ad_campaigns',
    idColumn: 'id',
    statusColumn: 'status',
    labelColumn: 'name',
    openStatuses: ['DRAFT', 'PENDING_REVIEW', 'APPROVED', 'ACTIVE', 'PAUSED'],
  },
  success: 'La campaña se entrega sólo tras moderación, consume presupuesto con eventos facturables y se factura y cobra por período.',
  failure:
    'La campaña queda REJECTED en moderación, el anunciante suspendido o bloqueado, o la facturación no cierra por falta de perfil fiscal.',
  sources: [
    'AtlasERPBackend/docs/architecture/flows.md (Flujos — ATLAS Ads)',
    'AtlasERPBackend/src/modules/ads/controllers/admin-ads.controller.ts',
    'AtlasERPBackend/src/modules/ads/controllers/admin-ads-authoring.controller.ts',
    'AtlasERPBackend/src/modules/ads/controllers/ads-delivery.controller.ts',
    'AtlasERPBackend/src/modules/ads/ads.enums.ts',
    'AtlasERPBackend/src/modules/ads/ads.campaign-transitions.ts',
    'AtlasERPBackend/src/modules/ads/services/moderation.service.ts',
    'AtlasERPBackend/src/modules/auth-gateway/role-mapping.ts',
    'AtlasERPBackend/src/database/migrations/20260708203000-create-atlas-ads-schema.sql',
    'AtlasERPFrontend/services/adsService.ts',
  ],
  metadata: {
    advertiserStatuses: ['PENDING_REVIEW', 'ACTIVE', 'SUSPENDED', 'REJECTED'],
    campaignStatuses: ['DRAFT', 'PENDING_REVIEW', 'APPROVED', 'ACTIVE', 'PAUSED', 'ENDED', 'REJECTED', 'ARCHIVED'],
    gaps: [
      'Enviar la campaña a moderación (POST /admin/ads/campaigns/:campaignId/submit) no tiene llamador en el ERP: sin él la cola de moderación no se llena desde la consola.',
      'La entrega y los eventos (/ads/delivery/select, /ads/events) los llama un servidor de anuncios con rol ADS_AD_SERVER; no se encontró llamador en AtlasBackend ni en la app, aunque el inventario lista CONSUMER_APP.',
      'El esquema atlas_ads no se declara en los modelos: resuelve por search_path (sequelize.module.ts).',
    ],
  },
  stages: [
    {
      code: 'ads_advertiser_creation',
      name: 'Alta del anunciante',
      description:
        'El gestor registra datos legales y fiscales mínimos; se rechaza el duplicado por país + NIT dentro de la transacción y el anunciante nace en PENDING_REVIEW con su auditoría CREATE_ADVERTISER.',
      module: 'ads.advertisers',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/anunciantes/crear',
      entry: true,
      roles: ['ADS_ADMIN_MANAGER'],
      resultingStates: ['PENDING_REVIEW'],
      steps: [
        {
          code: 'ads.advertiser_create',
          name: 'Dar de alta el anunciante',
          description: 'Crea ad_advertiser_accounts en PENDING_REVIEW y devuelve el anunciante con su auditId.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/advertisers',
          roles: ['ADS_ADMIN_MANAGER'],
          resultingStates: ['PENDING_REVIEW'],
        },
        {
          code: 'ads.advertiser_create_bulk',
          name: 'Alta de anunciantes en lote',
          description: 'Hasta 100 anunciantes con la misma validación de duplicado por país y NIT.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/advertisers/bulk',
          roles: ['ADS_ADMIN_MANAGER'],
          optional: true,
        },
      ],
    },
    {
      code: 'ads_billing_profile',
      name: 'Perfil fiscal del anunciante',
      description:
        'Razón social, NIT, país, moneda, correo y dirección fiscal. Es obligatorio antes de cerrar facturación real del anunciante.',
      module: 'ads.advertisers',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/anunciantes',
      roles: ['ADS_ADMIN_MANAGER', 'ADS_FINANCE'],
      steps: [
        {
          code: 'ads.billing_profile_create',
          name: 'Crear el perfil fiscal',
          description: 'Confirma que el anunciante existe y crea el perfil activo o inactivo; audita CREATE_BILLING_PROFILE.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/advertisers/:advertiserId/billing-profiles',
          roles: ['ADS_ADMIN_MANAGER', 'ADS_FINANCE'],
        },
      ],
    },
    {
      code: 'ads_advertiser_status',
      name: 'Estado del anunciante',
      description:
        'El gestor activa, suspende o rechaza con motivo obligatorio; REJECTED → ACTIVE directo está bloqueado. La auditoría guarda antes y después.',
      module: 'ads.advertisers',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/anunciantes',
      roles: ['ADS_ADMIN_MANAGER'],
      resultingStates: ['ACTIVE', 'SUSPENDED', 'REJECTED'],
      steps: [
        {
          code: 'ads.advertiser_status',
          name: 'Cambiar el estado del anunciante',
          description: 'Actualiza estado y riesgo con motivo; sólo un anunciante ACTIVE y no BLOCKED puede entregar anuncios.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/admin/ads/advertisers/:advertiserId/status',
          roles: ['ADS_ADMIN_MANAGER'],
          input: { status: 'PENDING_REVIEW | ACTIVE | SUSPENDED | REJECTED', reason: 'string' },
        },
      ],
    },
    {
      code: 'ads_campaign_authoring',
      name: 'Armar la campaña',
      description: 'Campaña con presupuesto y modelo de compra, conjuntos de anuncios, creatividades y anuncios. Todo nace en borrador.',
      module: 'ads.authoring',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/campanas',
      roles: ['ADS_ADMIN_MANAGER', 'ADS_ADMIN_OPERATOR'],
      resultingStates: ['DRAFT'],
      steps: [
        {
          code: 'ads.campaign_create',
          name: 'Crear la campaña',
          description: 'Campaña en DRAFT con objetivo, modelo de compra (CPM, CPC, CPA o FIXED) y presupuesto.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/campaigns',
          roles: ['ADS_ADMIN_MANAGER', 'ADS_ADMIN_OPERATOR'],
          resultingStates: ['DRAFT'],
        },
        {
          code: 'ads.ad_set_create',
          name: 'Crear un conjunto de anuncios',
          description: 'Segmento, ubicaciones y frecuencia del conjunto.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/campaigns/:campaignId/ad-sets',
          roles: ['ADS_ADMIN_MANAGER', 'ADS_ADMIN_OPERATOR'],
        },
        {
          code: 'ads.creative_create',
          name: 'Crear una creatividad',
          description: 'Imagen, video, carrusel o tarjeta de texto del anunciante.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/creatives',
          roles: ['ADS_ADMIN_MANAGER', 'ADS_ADMIN_OPERATOR'],
        },
        {
          code: 'ads.ad_create',
          name: 'Crear el anuncio',
          description: 'Une creatividad y conjunto.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/ad-sets/:adSetId/ads',
          roles: ['ADS_ADMIN_MANAGER', 'ADS_ADMIN_OPERATOR'],
        },
      ],
    },
    {
      code: 'ads_campaign_submit',
      name: 'Enviar a moderación',
      description:
        'Crea una revisión PENDING_REVIEW por cada anuncio de la campaña y deja la campaña PENDING_REVIEW con aprobación PENDING. Sin pantalla en el ERP.',
      module: 'ads.moderation',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      roles: ['ADS_ADMIN_MANAGER', 'ADS_ADMIN_OPERATOR'],
      requiredStates: ['DRAFT'],
      resultingStates: ['PENDING_REVIEW'],
      steps: [
        {
          code: 'ads.campaign_submit',
          name: 'Enviar la campaña a revisión',
          description: 'Es la pieza entre el alta y la revisión: sin ella ad_moderation_reviews no se llena y la cola sale vacía.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/campaigns/:campaignId/submit',
          roles: ['ADS_ADMIN_MANAGER', 'ADS_ADMIN_OPERATOR'],
          resultingStates: ['PENDING_REVIEW'],
        },
      ],
    },
    {
      code: 'ads_moderation',
      name: 'Moderar',
      description:
        'El moderador decide cada revisión pendiente; la decisión se propaga a campaña, anuncio y creatividad y se audita. No se aprueba una revisión ya rechazada sin crear una nueva.',
      module: 'ads.moderation',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/moderacion',
      roles: ['ADS_MODERATOR', 'ADS_COMPLIANCE_ADMIN'],
      requiredStates: ['PENDING_REVIEW'],
      resultingStates: ['APPROVED', 'REJECTED'],
      steps: [
        {
          code: 'ads.moderation_queue',
          name: 'Ver la cola de moderación',
          description: 'Revisiones en PENDING_REVIEW.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/admin/ads/moderation/queue',
          roles: ['ADS_ADMIN_VIEWER', 'ADS_MODERATOR', 'ADS_COMPLIANCE_ADMIN', 'ADS_AUDITOR'],
        },
        {
          code: 'ads.moderation_decide',
          name: 'Decidir la revisión',
          description: 'APPROVED, REJECTED, CHANGES_REQUESTED o ESCALATED; exige que la revisión siga en PENDING_REVIEW.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/moderation/:reviewId/decision',
          roles: ['ADS_MODERATOR', 'ADS_COMPLIANCE_ADMIN'],
        },
      ],
    },
    {
      code: 'ads_campaign_status',
      name: 'Activar, pausar, terminar o archivar',
      description:
        'La misma regla vale para la consola y para el portal del comercio: no se activa sin aprobación de moderación y una campaña ENDED o ARCHIVED no vuelve a ACTIVE.',
      module: 'ads.campaigns',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/campanas',
      roles: ['ADS_ADMIN_OPERATOR', 'ADS_ADMIN_MANAGER'],
      resultingStates: ['ACTIVE', 'PAUSED', 'ENDED', 'ARCHIVED'],
      steps: [
        {
          code: 'ads.campaign_status',
          name: 'Cambiar el estado de la campaña',
          description: 'Aplica assertCampaignTransition y audita con severidad alta al pausar, terminar, rechazar o archivar.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/admin/ads/campaigns/:campaignId/status',
          roles: ['ADS_ADMIN_OPERATOR', 'ADS_ADMIN_MANAGER'],
          resultingStates: ['ACTIVE', 'PAUSED', 'ENDED', 'ARCHIVED'],
          errors: ['409 CAMPAIGN_NOT_APPROVED', '409 INVALID_CAMPAIGN_TRANSITION'],
        },
      ],
    },
    {
      code: 'ads_delivery_and_events',
      name: 'Entregar el anuncio y contar eventos',
      description:
        'Un servidor de anuncios elige el anuncio elegible (anunciante activo, todo aprobado y vigente, presupuesto y frecuencia) y registra impresiones, clics y conversiones; los facturables reservan presupuesto y generan cargo en el libro de gasto.',
      module: 'ads.delivery',
      actor: 'system',
      client: 'BLOCK',
      requiredStates: ['ACTIVE'],
      steps: [
        {
          code: 'ads.delivery_select',
          name: 'Elegir el anuncio a mostrar',
          description:
            'Prioridad por puja por peso; guarda ad_delivery_decisions y devuelve la creatividad con sus direcciones de seguimiento.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/ads/delivery/select',
          roles: ['ADS_AD_SERVER'],
        },
        {
          code: 'ads.event_record',
          name: 'Registrar un evento',
          description:
            'Idempotente por decisión de entrega + tipo + requestId; con la campaña ya inactiva el evento facturable se rechaza.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/ads/events',
          roles: ['ADS_EVENT_TRACKER', 'ADS_AD_SERVER'],
          idempotencyKey: true,
          repeatable: true,
        },
      ],
    },
    {
      code: 'ads_billable_correction',
      name: 'Corregir si un evento es facturable',
      description:
        'Operaciones corrige con motivo; pasar a no facturable crea un crédito y libera presupuesto, al revés reserva presupuesto y crea un ajuste.',
      module: 'ads.delivery',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/delivery-monitor',
      optional: true,
      roles: ['ADS_ADMIN_OPERATOR', 'ADS_OPS_MONITOR'],
      steps: [
        {
          code: 'ads.event_billable_status',
          name: 'Cambiar el estado facturable',
          description: 'Genera auditoría de severidad alta; no crea ajustes si el estado no cambia.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/admin/ads/events/:eventId/billable-status',
          roles: ['ADS_ADMIN_OPERATOR', 'ADS_OPS_MONITOR'],
          optional: true,
        },
      ],
    },
    {
      code: 'ads_billing_close',
      name: 'Cerrar la facturación y cobrar',
      description:
        'Finanzas agrupa el libro de gasto por anunciante, moneda y campaña y crea una factura DRAFT por anunciante y moneda (nunca desde los eventos, nunca dos para el mismo período). Después registra los pagos.',
      module: 'ads.billing',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/ads/facturacion',
      terminal: true,
      roles: ['ADS_FINANCE'],
      steps: [
        {
          code: 'ads.billing_period_close',
          name: 'Cerrar el período de facturación',
          description: 'Exige perfil fiscal activo y rechaza el período ya cerrado para el mismo anunciante, moneda y rango.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/billing/period-close',
          roles: ['ADS_FINANCE'],
        },
        {
          code: 'ads.invoice_payment',
          name: 'Registrar un pago',
          description: 'Rechaza facturas VOID o PAID, moneda distinta y sobrepago; la factura pasa a PARTIALLY_PAID o PAID.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/ads/invoices/:invoiceId/payments',
          roles: ['ADS_FINANCE'],
          errors: ['INVOICE_PAYMENT_NOT_ALLOWED'],
        },
      ],
    },
  ],
};
