/**
 * @file Proceso declarado en código: Extracto bancario → capacidad de pago → recálculo de línea.
 * @business El cliente que quiere más línea sube su extracto y Atlas se compromete a responder en 24 horas: el Motor lee el PDF, mide la capacidad de pago y, si sirve, la línea se recalcula con ese dato real.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; escrita el 2026-09-26 desde `src/modules/credit/` y el worker de extractos del Motor (plan documentar procesos, P-07).
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const CUSTOMER_AND_STAFF = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];

export const BANK_STATEMENT_CAPACITY: WorkflowDefinitionFixture = {
  processId: 'P-07',
  code: 'bank_statement_capacity',
  version: 'v1',
  name: 'Extracto bancario → capacidad de pago → recálculo de línea',
  description:
    'El cliente sube el PDF de su extracto, un job lo manda al worker de extractos del Motor, y según el veredicto (analizado, rechazado, en revisión humana o Motor caído) la línea de crédito se recalcula con motivo `bank_statement`.',
  processType: 'integration',
  ownerDomain: 'credit',
  ownerRole: 'RISK_ANALYST',
  priority: 'P1',
  systems: ['ATLAS_BACKEND', 'DECISION_ENGINE'],
  narrative: {
    whyExists:
      'La línea calculada sólo con lo declarado en el alta no refleja lo que la persona gana y gasta de verdad. El extracto aporta ingresos, gastos, obligaciones y rechazos por fondos insuficientes, y con eso el Motor recalcula una capacidad de pago que la app promete revisar en 24 horas.',
    whoStartsAndCloses:
      'Lo inicia el cliente desde la pantalla «extracto bancario» de la app al subir el PDF. Lo cierra el job `process_bank_statement_reviews` con el veredicto del Motor; cuando el Motor duda, una persona analista lo resuelve en la pantalla de extractos del portal del Motor, que avisa a Atlas para que cierre la revisión.',
    startAndEnd:
      'Empieza con la revisión creada en `received` y un plazo comprometido (`promised_by`) de 24 horas; sólo cabe una revisión abierta por cliente. Termina en `applied` (capacidad aplicada y línea recalculada) o `rejected` (el Motor demostró que el documento no sirve y dice por qué).',
    whenItFails:
      'Motor caído o archivo ilegible del almacén: la revisión NO se rechaza, se queda en `received` y el siguiente barrido reintenta. Si el Motor la deriva a revisión, queda en `processing` con su motivo hasta que la persona del Motor la resuelve: el Motor avisa (`/internal/credit/bank-statement-review-callback`, con reintentos por su outbox) y, si el aviso se pierde, el mismo job relee en cada pasada las revisiones `processing` en el Motor. Un análisis aceptado sin capacidad utilizable se cierra como rechazado (normalmente por faltar meses), no se aparca. Los plazos por vencer sólo se anotan en el registro del job.',
    healthIndicator:
      'Revisiones abiertas (`received`/`processing`) con `promised_by` vencido o por vencer, proporción `applied` frente a `rejected` por `rejection_category`, y revisiones en `processing` más antiguas que una pasada del job (el aviso del Motor no llegó y la relectura tampoco pudo cerrarlas).',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'credit',
    table: 'bank_statement_reviews',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'institution_name',
    openStatuses: ['received', 'processing'],
  },
  success: 'La revisión queda `applied`, con la capacidad de pago del Motor guardada y una versión nueva de la línea de crédito.',
  failure: 'La revisión queda rechazada con un motivo que el cliente puede resolver, o abierta pasado el plazo de 24 horas.',
  sources: [
    'src/modules/credit/credit.controller.ts',
    'src/modules/credit/application/bank-statement.service.ts',
    'src/modules/credit/application/bank-statement-review.worker.ts',
    'src/modules/credit/application/bank-statement-human-review.sync.ts',
    'src/modules/credit/bank-statement-review-callback.controller.ts',
    'src/modules/credit/bank-statement.mapper.ts',
    'src/modules/credit/domain/statement-rejection.ts',
    'src/modules/decision-engine/bank-statement-engine.client.ts',
    'src/modules/customer-onboarding/customer-onboarding-profile.schemas.ts',
    'src/database/models/bank-statement-reviews.model.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts',
    'AtlasFrontend/apps/consumer-app/app/(app)/extracto-bancario.tsx',
    'AtlasFrontend/apps/consumer-app/src/api/endpoints/credit-line.ts',
    'AtlasDecisionEngineFrontend/src/features/workers/statement-review.api.ts',
    'memoria atlas-extracto-capacidad-pago',
    'memoria atlas-plan-promesas-reales',
    '_plan-promesas-reales-2026-09-14/PLAN.md (D1, D3)',
  ],
  stages: [
    {
      code: 'statement_upload',
      name: 'El cliente sube su extracto',
      description:
        'La app pide un permiso firmado, sube el PDF directo al almacén cifrado y registra la revisión. El servidor comprueba que el objeto es de ESTE cliente, existe y es un PDF.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      resultingStates: ['received'],
      steps: [
        {
          code: 'statement.upload_url',
          name: 'Pedir el permiso de subida',
          description:
            'Con `documentType: bank_statement` y `contentType: application/pdf`; el servidor decide la ruta y firma una URL temporal.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/documents/upload-url',
          roles: CUSTOMER_AND_STAFF,
          input: { documentType: 'bank_statement', contentType: 'application/pdf', sizeBytes: 'number' },
        },
        {
          code: 'statement.upload_bytes',
          name: 'Subir el PDF al almacén cifrado',
          description: 'La app envía los bytes a la URL firmada; el archivo no pasa por la API.',
          kind: 'external',
          reason: 'La subida va directa al almacén de evidencia con la URL firmada, no a una ruta de Atlas.',
        },
        {
          code: 'statement.submit',
          name: 'Registrar el extracto y arrancar el plazo',
          description: 'Crea la revisión en `received` con `promised_by` a 24 horas y cuelga el documento en el expediente del cliente.',
          method: 'POST',
          path: '/customers/:customerId/bank-statements',
          roles: CUSTOMER_AND_STAFF,
          input: { storageKey: 'string' },
          resultingStates: ['received'],
          errors: ['409 BANK_STATEMENT_REVIEW_ALREADY_OPEN'],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'statement_engine_analysis',
      name: 'El Motor lee el extracto',
      description:
        'Cada pasada del job toma las revisiones `received` más antiguas, descarga el PDF y lo manda al worker de extractos del Motor (tres compuertas: contenedor, contenido y emisor; tres meses completos). Luego sondea la ejecución.',
      module: 'credit',
      actor: 'system',
      client: 'BLOCK',
      requiredStates: ['received'],
      resultingStates: ['received', 'processing', 'rejected'],
      steps: [
        {
          code: 'statement.process_job',
          name: 'Barrer las revisiones pendientes',
          description:
            'Procesa por orden de llegada, relee en el Motor las revisiones que esperaban a una persona y cuenta las que tienen el plazo a punto de vencer.',
          kind: 'job',
          job: 'process_bank_statement_reviews',
          repeatable: true,
        },
        {
          code: 'statement.engine_run_create',
          name: 'Enviar el PDF al worker del Motor',
          description: 'Subida multipart; el Motor deduplica por huella, así que reintentar no repite trabajo.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/runs',
        },
        {
          code: 'statement.engine_run_poll',
          name: 'Consultar la ejecución',
          description: 'Sondea hasta analizado, rechazado (`PDF_INVALID`), revisión (`PENDING_REVIEW`/`IN_REVIEW`) o fallo.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/bank-statement/runs/:requestId',
          repeatable: true,
        },
      ],
    },
    {
      code: 'statement_motor_human_review',
      name: 'Revisión humana en el Motor',
      description:
        'Cuando el Motor duda, la revisión queda `processing` con `review_reason`. Una persona la toma y la resuelve en la pantalla de extractos del Motor, que encola un aviso de vuelta a Atlas.',
      module: 'credit',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/workers/bank-statement',
      link: '{MOTOR}/workers/bank-statement',
      optional: true,
      requiredStates: ['processing'],
      steps: [
        {
          code: 'statement.motor_reviews_list',
          name: 'Ver la cola de extractos en revisión',
          description: 'Lista de revisiones del worker de extractos, con sus categorías.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/bank-statement/reviews',
          optional: true,
        },
        {
          code: 'statement.motor_review_claim',
          name: 'Tomar una revisión',
          description: 'La persona se asigna el extracto.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/reviews/:requestId/claim',
          optional: true,
        },
        {
          code: 'statement.motor_review_resolve',
          name: 'Resolver la revisión',
          description: 'Cierra la revisión en el Motor y encola en su outbox el aviso de vuelta a Atlas, con reintentos.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/reviews/:requestId/resolve',
          optional: true,
        },
        {
          code: 'statement.motor_review_reprocess',
          name: 'Reprocesar el extracto',
          description: 'Vuelve a pasar el documento por el worker. No avisa: el desenlace lo recoge la relectura del job.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/reviews/:requestId/reprocess',
          optional: true,
        },
      ],
    },
    {
      code: 'statement_human_review_return',
      name: 'Vuelta de la revisión humana a Atlas',
      description:
        'Atlas relee la ejecución en el Motor con su propia llave y cierra la revisión: `applied` si hay capacidad utilizable, `rejected` con un motivo accionable si la persona la marcó no válida, la cerró sin resultado o faltan meses. Mientras el Motor siga con el caso no toca nada.',
      module: 'credit',
      actor: 'system',
      client: 'BLOCK',
      requiredStates: ['processing'],
      resultingStates: ['applied', 'rejected', 'processing'],
      steps: [
        {
          code: 'statement.review_callback',
          name: 'Recibir el aviso del Motor',
          description:
            'Autenticado con x-engine-callback-key (guard `EngineCallbackKeyGuard`), no con sesión. Sólo trae la referencia: sin revisión abierta para esa ejecución responde `applied: false`.',
          method: 'POST',
          path: '/internal/credit/bank-statement-review-callback',
          auth: false,
          requiredStates: ['processing'],
          resultingStates: ['applied', 'rejected', 'processing'],
          errors: ['400 Falta requestId', '401 Credencial de servicio invalida'],
        },
        {
          code: 'statement.review_reread',
          name: 'Releer la ejecución en el Motor',
          description:
            'La decisión sale de esta lectura, no del aviso. La misma relectura la hace el job en cada pasada por si el aviso se pierde.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/bank-statement/runs/:requestId',
          repeatable: true,
        },
      ],
    },
    {
      code: 'statement_apply_capacity',
      name: 'Aplicar la capacidad y recalcular la línea',
      description:
        'Con capacidad elegible, Atlas guarda ingresos, gastos, obligaciones, cuota máxima y rechazos por fondos insuficientes, y pide al Motor la línea nueva (motivo `bank_statement`). Si el Motor no recalcula, la revisión se queda `processing`.',
      module: 'credit',
      actor: 'system',
      client: 'BLOCK',
      requiredStates: ['received', 'processing'],
      resultingStates: ['applied', 'processing'],
      steps: [
        {
          code: 'statement.engine_line_recalculation',
          name: 'El Motor recalcula la línea',
          description: 'Ejecuta el artefacto de crédito con el recuento de rechazos por fondos insuficientes del extracto.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
        },
      ],
    },
    {
      code: 'statement_customer_status',
      name: 'El cliente ve el resultado',
      description:
        'La app enseña «lo estamos revisando» con la hora comprometida, el motivo del rechazo con una frase que la persona puede resolver, o la línea nueva con su historial.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      terminal: true,
      steps: [
        {
          code: 'statement.latest',
          name: 'Consultar el último extracto',
          description: 'Última revisión, o `null` si nunca subió ninguno.',
          method: 'GET',
          path: '/customers/:customerId/bank-statements/latest',
          roles: CUSTOMER_AND_STAFF,
          repeatable: true,
        },
        {
          code: 'statement.credit_line',
          name: 'Ver la línea recalculada',
          description: 'La línea vigente con su explicación.',
          method: 'GET',
          path: '/customers/:customerId/credit-line',
          roles: CUSTOMER_AND_STAFF,
          optional: true,
          errors: ['404 CREDIT_LINE_NOT_CALCULATED'],
        },
        {
          code: 'statement.credit_line_history',
          name: 'Ver qué movió la línea',
          description: 'Historial de versiones de la línea.',
          method: 'GET',
          path: '/customers/:customerId/credit-line/history',
          roles: CUSTOMER_AND_STAFF,
          optional: true,
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'statement.entry',
      from: null,
      to: 'statement.upload_url',
      condition: 'always',
      description: 'Entrada: el cliente elige su PDF.',
      isDefault: true,
    },
    {
      code: 'statement.url_to_bytes',
      from: 'statement.upload_url',
      to: 'statement.upload_bytes',
      condition: 'on_success',
      description: 'Con el permiso, se suben los bytes.',
      isDefault: true,
    },
    {
      code: 'statement.bytes_to_submit',
      from: 'statement.upload_bytes',
      to: 'statement.submit',
      condition: 'on_success',
      description: 'Subido, se registra la revisión.',
      isDefault: true,
    },
    {
      code: 'statement.submit_to_job',
      from: 'statement.submit',
      to: 'statement.process_job',
      condition: 'on_success',
      description: 'La revisión espera al siguiente barrido.',
      isDefault: true,
    },
    {
      code: 'statement.job_to_run',
      from: 'statement.process_job',
      to: 'statement.engine_run_create',
      condition: 'always',
      description: 'El job manda el PDF al Motor.',
      isDefault: true,
    },
    {
      code: 'statement.run_to_poll',
      from: 'statement.engine_run_create',
      to: 'statement.engine_run_poll',
      condition: 'on_success',
      description: 'Se sondea la ejecución.',
      isDefault: true,
    },
    {
      code: 'statement.poll_to_apply',
      from: 'statement.engine_run_poll',
      to: 'statement.engine_line_recalculation',
      condition: 'conditional',
      expression: { outcome: 'analyzed', affordabilityEligible: true },
      description: 'Analizado con capacidad utilizable: se recalcula la línea.',
      isDefault: true,
    },
    {
      code: 'statement.poll_to_review',
      from: 'statement.engine_run_poll',
      to: 'statement.motor_reviews_list',
      condition: 'conditional',
      expression: { outcome: 'review' },
      description: 'El Motor duda: revisión humana en su portal.',
    },
    {
      code: 'statement.poll_rejected',
      from: 'statement.engine_run_poll',
      to: 'statement.latest',
      condition: 'conditional',
      expression: { outcome: 'rejected' },
      description: 'Rechazado con motivo: el cliente lo ve y puede subir otro.',
    },
    {
      code: 'statement.poll_retry',
      from: 'statement.engine_run_poll',
      to: 'statement.process_job',
      condition: 'on_error',
      description: 'Motor caído o archivo no disponible: queda `received` y reintenta la pasada siguiente.',
    },
    {
      code: 'statement.claim_flow',
      from: 'statement.motor_reviews_list',
      to: 'statement.motor_review_claim',
      condition: 'on_success',
      description: 'La persona toma el caso.',
    },
    {
      code: 'statement.resolve_flow',
      from: 'statement.motor_review_claim',
      to: 'statement.motor_review_resolve',
      condition: 'on_success',
      description: 'Y lo resuelve en el Motor.',
    },
    {
      code: 'statement.resolve_to_callback',
      from: 'statement.motor_review_resolve',
      to: 'statement.review_callback',
      condition: 'on_success',
      description: 'El Motor avisa a Atlas (outbox, con reintentos).',
    },
    {
      code: 'statement.callback_to_reread',
      from: 'statement.review_callback',
      to: 'statement.review_reread',
      condition: 'on_success',
      description: 'Atlas relee la ejecución con su llave.',
    },
    {
      code: 'statement.reread_to_apply',
      from: 'statement.review_reread',
      to: 'statement.engine_line_recalculation',
      condition: 'conditional',
      expression: { outcome: 'analyzed', affordabilityEligible: true },
      description: 'Aprobada con capacidad utilizable: se recalcula la línea.',
    },
    {
      code: 'statement.reread_rejected',
      from: 'statement.review_reread',
      to: 'statement.latest',
      condition: 'conditional',
      expression: { outcome: 'rejected' },
      description: 'No válida, cerrada sin resultado o sin meses suficientes: el cliente ve el motivo y puede subir otro.',
    },
    {
      code: 'statement.job_rereads',
      from: 'statement.process_job',
      to: 'statement.review_reread',
      condition: 'always',
      description: 'Red del aviso: cada pasada relee las revisiones `processing` en el Motor.',
    },
    {
      code: 'statement.apply_to_status',
      from: 'statement.engine_line_recalculation',
      to: 'statement.latest',
      condition: 'on_success',
      description: 'Aplicada: el cliente ve el resultado.',
      isDefault: true,
    },
    {
      code: 'statement.exit',
      from: 'statement.latest',
      to: null,
      condition: 'always',
      description: 'Salida: revisión aplicada o rechazada.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'statement.review_reread',
      dependsOn: 'statement.engine_run_poll',
      type: 'requires_data',
      description: 'Sólo se relee una revisión que guardó la ejecución del Motor (`engine_request_id`).',
    },
    {
      step: 'statement.submit',
      dependsOn: 'statement.upload_bytes',
      type: 'requires_completion',
      description: 'El servidor comprueba que el objeto existe y es un PDF de este cliente.',
    },
    {
      step: 'statement.engine_run_create',
      dependsOn: 'statement.submit',
      type: 'requires_data',
      description: 'El job sólo toma revisiones registradas en `received`.',
    },
    {
      step: 'statement.engine_line_recalculation',
      dependsOn: 'statement.engine_run_poll',
      type: 'requires_data',
      description: 'La línea se recalcula con la capacidad que devolvió el worker.',
    },
  ],
};
