/**
 * @file Proceso declarado en código: Cobertura de CxC del comercio, barrido de mora, recuperación y conciliación.
 * @business Cuando un cliente no paga una cuota de una compra a plazos, Atlas le paga al comercio y después recupera ese dinero del cliente; este proceso detecta la mora, cubre la cuota con doble control, registra cada cobro de recuperación y concilia el período.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; ERP (`b2b/coverage/*`, `b2b/reconciliation/runs`, procesador `b2b.overdue-sweep`, `integration/core/events`, worker de outbox) y la proyección de AtlasBackend en `internal/integration/erp/events`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** `@Roles` de lectura de cobertura del ERP. */
const COVERAGE_READ = ['FINANCE', 'OPERATIONS', 'ADMIN'];
/** `@Roles` de las transiciones con dinero (liquidar, cancelar, resolver revisión). */
const COVERAGE_MONEY = ['FINANCE', 'ADMIN'];
/** `@Roles` de la aplicación de cobros de recuperación. */
const RECOVERY = ['FINANCE', 'COLLECTIONS', 'ADMIN'];

export const COVERAGE_AND_RECOVERY: WorkflowDefinitionFixture = {
  processId: 'P-21',
  code: 'coverage_and_recovery',
  version: 'v1',
  name: 'Cobertura de CxC del comercio, barrido de mora, recuperación y conciliación',
  description:
    'Un barrido horario del ERP marca en mora las cuotas vencidas sin pago confirmado y manda a revisión los avisos de pago que nadie confirmó a tiempo. Finanzas programa la cobertura (cuenta por pagar de Atlas al comercio) de la cuota impaga, una persona registra la liquidación y otra la aprueba; sólo entonces nace la cuenta por cobrar de recuperación contra el cliente y Core se entera. Cada cobro de recuperación es un movimiento reversible, y la conciliación del período cuadra lo cubierto, lo pagado y lo recuperado.',
  processType: 'system_job',
  ownerDomain: 'merchant_coverage',
  ownerRole: 'ERP:FINANCE',
  priority: 'P1',
  systems: ['ERP_BACKEND', 'ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Atlas garantiza al comercio el cobro de las cuotas que financia: si el cliente no paga, Atlas le paga al comercio y asume la deuda. Mover ese dinero exige prueba en cada transición —cuota realmente vencida e impaga, liquidación identificada confirmada por una segunda persona, cobro de recuperación con referencia única— para que nadie cubra dos veces ni recupere lo que no se pagó.',
    whoStartsAndCloses:
      'Lo inicia el sistema: el procesador b2b.overdue-sweep del ERP corre cada hora dentro de la API y marca la mora. Finanzas del ERP (FINANCE) programa la cobertura y registra la liquidación, OTRA persona de Finanzas la aprueba, Cobranza (COLLECTIONS) aplica los cobros de recuperación, y Finanzas u Operaciones cierra el período con la conciliación.',
    startAndEnd:
      'Empieza cuando una cuota SCHEDULED pasa su vencimiento sin pago confirmado y el barrido la marca OVERDUE (o manda el aviso de pago sin confirmar a la cola de revisión). La cobertura va SCHEDULED/DUE → PAID con la liquidación aprobada, la cuota a COVERED_BY_ATLAS y nace la recuperación OPEN, que avanza a PARTIALLY_RECOVERED y RECOVERED; termina con la conciliación en COMPLETED u OPEN_ITEMS.',
    whenItFails:
      'Lo ambiguo (aviso de pago sin confirmar, contrato no activo) no se cubre solo: va a la cola de revisión. Una segunda cobertura viva para la misma cuota se rechaza por índice único; la misma persona no puede registrar y aprobar una liquidación; un cobro repetido con la misma referencia no suma y uno que excede el saldo se rechaza. Si un tick del barrido falla, se registra y el siguiente reintenta.',
    healthIndicator:
      'Cuotas OVERDUE sin cobertura programada, elementos abiertos en la cola de revisión y su antigüedad, liquidaciones registradas sin aprobar, y los hallazgos de la conciliación: compras sin comisión, cuentas por cobrar vencidas, cuotas sin cuenta por pagar y coberturas pagadas sin recuperación.',
  },
  instanceEntity: {
    system: 'ERP_BACKEND',
    schema: 'atlas_sales',
    table: 'merchant_payables',
    idColumn: 'id',
    statusColumn: 'status',
    openStatuses: ['SCHEDULED', 'DUE', 'DISPUTED'],
  },
  success:
    'La cuota impaga queda cubierta con liquidación aprobada, la recuperación registrada contra el cliente y el período conciliado sin partidas abiertas.',
  failure: 'La mora no se detecta, la cobertura se queda en revisión o sin aprobar, o la conciliación cierra con partidas abiertas.',
  sources: [
    'AtlasERPBackend/docs/architecture/flows.md (Cobertura y recuperación, Conciliación)',
    'AtlasERPBackend/src/modules/b2b-sales-crm/controllers/coverage.controller.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-overdue-sweep.processor.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-overdue-sweep.service.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-coverage.service.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/coverage-review.service.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-reconciliation.service.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/b2b-sales-crm.enums.ts',
    'AtlasERPBackend/src/config/env.ts (BNPL_OVERDUE_SWEEP_ENABLED, BNPL_OVERDUE_SWEEP_INTERVAL_MS)',
    'src/modules/erp-integration/integration-envelope.schemas.ts (CONSUMED_ERP_TOPICS)',
    'src/modules/erp-integration/erp-event-inbox.service.ts',
    'AtlasERPFrontend/app/operaciones/crm/conciliacion-cobertura/page.tsx',
    '_plan-produccion-siete-repos-2026-09-24/04_DOMINIO_Y_AUTORIDAD.md (DEC-03, DEC-04, DEC-05)',
    '_plan-produccion-siete-repos-2026-09-24/contratos/propuestos/CTR-COVERAGE-SETTLEMENT.schema.json',
  ],
  metadata: {
    gaps: [
      'DEC-03 (autoridad de cuotas y pagos frente al ERP), DEC-04 (condiciones de la garantía) y DEC-05 (qué acredita una liquidación) siguen abiertas.',
      'POST /b2b/coverage/installments/sweep-overdue no tiene pantalla: el barrido real es el procesador en proceso b2b.overdue-sweep (cada hora por defecto, desactivable con BNPL_OVERDUE_SWEEP_ENABLED=false); la ruta sirve para lanzarlo a mano.',
      'Los estados del inventario (ELIGIBLE, INSTRUCTED, CONFIRMED, FAILED, RECOVERED) vienen del contrato propuesto CTR-COVERAGE-SETTLEMENT; los reales son los de merchant_payables (SCHEDULED, DUE, PAID, CANCELLED, DISPUTED) y consumer_recovery_receivables (OPEN, IN_COLLECTION, PARTIALLY_RECOVERED, RECOVERED, WRITTEN_OFF).',
      'El barrido no tiene cerrojo en base: la bandera running vive en memoria del proceso de la API.',
      'Ninguna pantalla del portal admin observa la cobertura; Core sólo la proyecta sobre la cuota.',
    ],
  },
  stages: [
    {
      code: 'cov_overdue_sweep',
      name: 'El barrido marca la mora',
      description:
        'Cada hora (y al arrancar) el ERP marca OVERDUE las cuotas vencidas sin pago confirmado según el día de negocio de Bolivia. Un aviso de pago REPORTED da 72 h de plazo; vencido, la cuota pasa a mora y el aviso a la cola de revisión.',
      module: 'b2b_sales_crm',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      resultingStates: ['OVERDUE'],
      steps: [
        {
          code: 'cov.core_payment_events',
          name: 'Recibir los avisos y confirmaciones de pago de Core',
          description: 'payment.reported, payment.confirmed y payment.rejected llegan una sola vez aunque Core reintente.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/integration/core/events',
          auth: false,
          consumes: ['payment.reported', 'payment.confirmed', 'payment.rejected'],
          errors: ['400 sobre inválido', '422 payload o tópico', '401 firma'],
        },
        {
          code: 'cov.overdue_sweep_job',
          name: 'Barrer las cuotas vencidas',
          kind: 'job',
          system: 'ERP_BACKEND',
          job: 'b2b.overdue-sweep',
          description:
            'Procesador en la API del ERP (setInterval, BNPL_OVERDUE_SWEEP_INTERVAL_MS = 1 h por defecto). Idempotente: no remarca una cuota ya OVERDUE ni duplica una revisión abierta.',
          resultingStates: ['OVERDUE'],
        },
        {
          code: 'cov.overdue_sweep_manual',
          name: 'Lanzar el barrido a mano',
          description: 'Misma pasada que el procesador; sin pantalla que la llame.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/coverage/installments/sweep-overdue',
          roles: COVERAGE_READ,
          optional: true,
        },
      ],
    },
    {
      code: 'cov_review_queue',
      name: 'Finanzas resuelve lo ambiguo',
      description:
        'Cuarta tabla de Cobertura y conciliación: las cuotas que el sistema no cubre solo (aviso de pago sin confirmar, contrato no activo) se resuelven desde su fila.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/conciliacion-cobertura',
      link: '{ERP}/operaciones/crm/conciliacion-cobertura',
      optional: true,
      roles: COVERAGE_MONEY,
      steps: [
        {
          code: 'cov.review_list',
          name: 'Ver la cola de revisión',
          description: 'Elementos OPEN con sus avisos pendientes y las acciones permitidas.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/coverage/review-queue',
          roles: COVERAGE_READ,
          optional: true,
        },
        {
          code: 'cov.review_resolve',
          name: 'Resolver un elemento de revisión',
          description: 'Confirma o descarta el aviso; quien abrió el elemento no lo resuelve.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/coverage/review-queue/:reviewItemId/resolve',
          roles: COVERAGE_MONEY,
          optional: true,
          resultingStates: ['RESOLVED'],
        },
      ],
    },
    {
      code: 'cov_schedule',
      name: 'Finanzas programa la cobertura',
      description:
        'Desde la fila de la cuota: sólo una cuota vencida, impaga y sin cobertura viva, por su saldo. Nace la cuenta por pagar de Atlas al comercio por esa cuota específica.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/conciliacion-cobertura',
      link: '{ERP}/operaciones/crm/conciliacion-cobertura',
      roles: COVERAGE_READ,
      requiredStates: ['OVERDUE'],
      resultingStates: ['SCHEDULED'],
      steps: [
        {
          code: 'cov.installments_list',
          name: 'Ver las cuotas',
          description: 'Cuotas BNPL con su estado y saldo.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/coverage/installments',
          roles: COVERAGE_READ,
        },
        {
          code: 'cov.payable_schedule',
          name: 'Programar la cobertura de la cuota',
          description: 'Cerrojo sobre la cuota; lo ambiguo va a revisión en vez de programarse.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/coverage/payables',
          roles: COVERAGE_READ,
          resultingStates: ['SCHEDULED'],
          errors: ['404 Cuota BNPL no encontrada', '409 Ya existe una CxP ATLAS→comercio vigente para esta cuota'],
        },
        {
          code: 'cov.payables_list',
          name: 'Ver las coberturas',
          description: 'Importe, estado, motivo, fecha programada y pagada.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/coverage/payables',
          roles: COVERAGE_READ,
          repeatable: true,
        },
        {
          code: 'cov.payable_cancel',
          name: 'Cancelar la cobertura',
          description: 'Antes de pagarla.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/coverage/payables/:payableId/cancel',
          roles: COVERAGE_MONEY,
          optional: true,
          resultingStates: ['CANCELLED'],
        },
      ],
    },
    {
      code: 'cov_settlement',
      name: 'Liquidación con doble control',
      description:
        'Una persona registra la liquidación identificada (referencia única, importe, moneda, beneficiario, fecha, evidencia) y OTRA la aprueba. Sólo al aprobar la cuenta por pagar pasa a PAID, la cuota a COVERED_BY_ATLAS y nace la recuperación, con su evento en el outbox, en una transacción.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/conciliacion-cobertura',
      link: '{ERP}/operaciones/crm/conciliacion-cobertura',
      roles: COVERAGE_MONEY,
      requiredStates: ['SCHEDULED', 'DUE'],
      resultingStates: ['PAID'],
      steps: [
        {
          code: 'cov.payable_paid',
          name: 'Registrar la liquidación al comercio',
          description: 'Primera persona: deja la liquidación esperando aprobación.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/coverage/payables/:payableId/paid',
          roles: COVERAGE_MONEY,
        },
        {
          code: 'cov.settlement_approve',
          name: 'Aprobar la liquidación',
          description: 'Segunda persona; repetir la confirmación devuelve el mismo resultado.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/coverage/payables/:payableId/settlement/approve',
          roles: COVERAGE_MONEY,
          resultingStates: ['PAID', 'COVERED_BY_ATLAS'],
          events: ['b2b.coverage.settled'],
        },
        {
          code: 'cov.settlement_reject',
          name: 'Rechazar la liquidación',
          description: 'La cobertura vuelve a esperar una liquidación válida.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/coverage/payables/:payableId/settlement/reject',
          roles: COVERAGE_MONEY,
          optional: true,
        },
      ],
    },
    {
      code: 'cov_core_projection',
      name: 'Core se entera de la cobertura y la recuperación',
      description:
        'El worker de outbox del ERP entrega firmados b2b.coverage.settled y los movimientos de recuperación a AtlasBackend, que los proyecta sobre la cuota.',
      module: 'erp_integration',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'cov.erp_outbox_deliver',
          name: 'Entregar los eventos de cobertura',
          kind: 'job',
          system: 'ERP_BACKEND',
          job: 'worker-outbox',
          description: 'Worker de outbox del ERP hacia OUTBOX_DELIVERY_URL.',
          consumes: ['b2b.coverage.settled', 'b2b.recovery.payment_applied', 'b2b.recovery.payment_reversed'],
        },
        {
          code: 'cov.core_erp_inbox',
          name: 'Proyectar la cobertura sobre la cuota',
          description: 'Receptor firmado; un movimiento de recuperación sólo avanza si su versión de agregado es mayor.',
          method: 'POST',
          path: '/internal/integration/erp/events',
          auth: false,
          consumes: ['b2b.coverage.settled', 'b2b.recovery.payment_applied', 'b2b.recovery.payment_reversed'],
        },
      ],
    },
    {
      code: 'cov_recovery',
      name: 'Cobranza registra la recuperación',
      description:
        'Cada cobro al cliente es un movimiento con referencia única contra la recuperación: repetirlo no suma, excederse se rechaza y el reverso compensa sin borrar.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/conciliacion-cobertura',
      link: '{ERP}/operaciones/crm/conciliacion-cobertura',
      roles: RECOVERY,
      requiredStates: ['OPEN'],
      resultingStates: ['PARTIALLY_RECOVERED', 'RECOVERED'],
      steps: [
        {
          code: 'cov.recoveries_list',
          name: 'Ver las recuperaciones',
          description: 'Cuentas por cobrar de recuperación contra el cliente.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/coverage/recoveries',
          roles: COVERAGE_READ,
        },
        {
          code: 'cov.recovery_apply',
          name: 'Aplicar un cobro de recuperación',
          description: 'Con referencia única; «ya estaba registrado» si se repite.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/coverage/recoveries/:recoveryId/apply-payment',
          roles: RECOVERY,
          idempotencyKey: true,
          resultingStates: ['PARTIALLY_RECOVERED', 'RECOVERED'],
          events: ['b2b.recovery.payment_applied'],
        },
        {
          code: 'cov.recovery_movements',
          name: 'Ver los cobros de una recuperación',
          description: 'Movimientos aplicados y revertidos.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/coverage/recoveries/:recoveryId/movements',
          roles: RECOVERY,
          optional: true,
        },
        {
          code: 'cov.recovery_reverse',
          name: 'Revertir un cobro equivocado',
          description: 'Compensa sin borrar el movimiento original.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/coverage/recoveries/:recoveryId/movements/:movementId/reverse',
          roles: COVERAGE_MONEY,
          optional: true,
          events: ['b2b.recovery.payment_reversed'],
        },
      ],
    },
    {
      code: 'cov_reconciliation',
      name: 'Conciliación del período',
      description:
        '«Ejecutar conciliación» en la barra: detecta compras sin comisión, cuentas por cobrar vencidas, cuotas sin cuenta por pagar y coberturas pagadas sin recuperación, y deja la corrida COMPLETED u OPEN_ITEMS.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/conciliacion-cobertura',
      link: '{ERP}/operaciones/crm/conciliacion-cobertura',
      terminal: true,
      roles: COVERAGE_READ,
      resultingStates: ['COMPLETED', 'OPEN_ITEMS'],
      steps: [
        {
          code: 'cov.reconciliation_run',
          name: 'Ejecutar la conciliación',
          description: 'Crea reconciliation_items por cada hallazgo entre dos fechas.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/reconciliation/runs',
          roles: COVERAGE_READ,
          input: { periodStart: 'date', periodEnd: 'date' },
          resultingStates: ['COMPLETED', 'OPEN_ITEMS'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'cov.entry',
      from: null,
      to: 'cov.overdue_sweep_job',
      condition: 'always',
      isDefault: true,
      description: 'Entrada: el barrido horario.',
    },
    {
      code: 'cov.events_to_sweep',
      from: 'cov.core_payment_events',
      to: 'cov.overdue_sweep_job',
      condition: 'always',
      description: 'Los pagos confirmados evitan la mora.',
    },
    {
      code: 'cov.sweep_to_review',
      from: 'cov.overdue_sweep_job',
      to: 'cov.review_resolve',
      condition: 'conditional',
      expression: { enRevision: '>0' },
      description: 'Avisos vencidos sin confirmar: revisión.',
    },
    {
      code: 'cov.sweep_to_schedule',
      from: 'cov.overdue_sweep_job',
      to: 'cov.payable_schedule',
      condition: 'on_success',
      isDefault: true,
      description: 'Cuotas en mora: se programa la cobertura.',
    },
    {
      code: 'cov.review_to_schedule',
      from: 'cov.review_resolve',
      to: 'cov.payable_schedule',
      condition: 'conditional',
      expression: { outcome: 'cubrir' },
      description: 'Resuelto a favor de cubrir.',
    },
    {
      code: 'cov.schedule_to_paid',
      from: 'cov.payable_schedule',
      to: 'cov.payable_paid',
      condition: 'on_success',
      isDefault: true,
      description: 'Se registra la liquidación.',
    },
    {
      code: 'cov.paid_to_approve',
      from: 'cov.payable_paid',
      to: 'cov.settlement_approve',
      condition: 'on_success',
      isDefault: true,
      description: 'Otra persona la aprueba.',
    },
    {
      code: 'cov.paid_to_reject',
      from: 'cov.payable_paid',
      to: 'cov.settlement_reject',
      condition: 'conditional',
      expression: { decision: 'reject' },
      description: 'Liquidación rechazada.',
    },
    {
      code: 'cov.reject_to_paid',
      from: 'cov.settlement_reject',
      to: 'cov.payable_paid',
      condition: 'on_success',
      description: 'Se registra una liquidación válida.',
    },
    {
      code: 'cov.approve_to_outbox',
      from: 'cov.settlement_approve',
      to: 'cov.erp_outbox_deliver',
      condition: 'on_success',
      isDefault: true,
      description: 'El evento sale por el outbox.',
    },
    {
      code: 'cov.outbox_to_core',
      from: 'cov.erp_outbox_deliver',
      to: 'cov.core_erp_inbox',
      condition: 'always',
      isDefault: true,
      description: 'Core proyecta.',
    },
    {
      code: 'cov.approve_to_recovery',
      from: 'cov.settlement_approve',
      to: 'cov.recovery_apply',
      condition: 'on_success',
      description: 'Nace la recuperación; Cobranza aplica cobros.',
    },
    {
      code: 'cov.recovery_reverse',
      from: 'cov.recovery_apply',
      to: 'cov.recovery_reverse',
      condition: 'conditional',
      expression: { wrongPayment: true },
      description: 'Cobro equivocado: se revierte.',
    },
    {
      code: 'cov.recovery_to_reconcile',
      from: 'cov.recovery_apply',
      to: 'cov.reconciliation_run',
      condition: 'always',
      isDefault: true,
      description: 'Cierre del período.',
    },
    {
      code: 'cov.exit',
      from: 'cov.reconciliation_run',
      to: null,
      condition: 'on_success',
      isDefault: true,
      description: 'Salida: período conciliado.',
    },
  ],
  dependencies: [
    {
      step: 'cov.payable_schedule',
      dependsOn: 'cov.overdue_sweep_job',
      type: 'requires_completion',
      description: 'Sólo se cubre una cuota vencida e impaga.',
    },
    {
      step: 'cov.settlement_approve',
      dependsOn: 'cov.payable_paid',
      type: 'requires_completion',
      description: 'Se aprueba una liquidación registrada por otra persona.',
    },
    {
      step: 'cov.recovery_apply',
      dependsOn: 'cov.settlement_approve',
      type: 'requires_data',
      description: 'La recuperación nace al aprobar la liquidación.',
    },
    {
      step: 'cov.core_erp_inbox',
      dependsOn: 'cov.erp_outbox_deliver',
      type: 'requires_completion',
      description: 'Core sólo ve lo que el ERP entrega.',
    },
    {
      step: 'cov.reconciliation_run',
      dependsOn: 'cov.payable_schedule',
      type: 'soft',
      description: 'La conciliación busca cuotas sin cuenta por pagar.',
    },
  ],
};
