/**
 * @file Proceso declarado en código: Línea de crédito, solicitud y decisión de crédito por el Motor.
 * @business Atlas sólo presta lo que la política aprobada del Motor sostiene: este proceso calcula cuánto puede gastar un cliente activo, recibe su solicitud, la hace decidir por el Motor (o por una persona cuando el Motor la deriva) y deja que el comercio diga si quiere la operación.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; escrita el 2026-09-26 desde `src/modules/credit/` (plan documentar procesos, P-06).
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const CUSTOMER_AND_STAFF = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const CREDIT_OPERATIONS = ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const MERCHANT_AND_STAFF = ['merchant', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const ERP_MERCHANT_ROLES = ['merchant', 'MERCHANT_ADMIN', 'MERCHANT_OPERATIONS', 'OPERATIONS', 'ADMIN'];

export const CREDIT_LINE_AND_APPLICATION: WorkflowDefinitionFixture = {
  processId: 'P-06',
  code: 'credit_line_and_application',
  version: 'v1',
  name: 'Línea de crédito, solicitud y decisión de crédito por el Motor',
  description:
    'Desde el catálogo de productos hasta la solicitud decidida y aceptada: línea calculada por el Motor, solicitud del cliente, decisión automática o revisión humana (en el Motor o en Atlas) y aceptación del comercio.',
  processType: 'customer_journey',
  ownerDomain: 'credit',
  ownerRole: 'RISK_MANAGER',
  priority: 'P0',
  systems: ['ATLAS_BACKEND', 'DECISION_ENGINE', 'ERP_BACKEND'],
  narrative: {
    whyExists:
      'Atlas no decide montos ni tasas a mano: la línea de crédito y cada solicitud se deciden con la política versionada y aprobada del Motor, para que cada «sí» o «no» sea explicable y medible, y para que el comercio decida si quiere la operación que el riesgo ya aceptó.',
    whoStartsAndCloses:
      'Lo inicia el cliente activo desde la app al pedir un crédito (normalmente en la caja de un comercio, tras leer su QR). Lo cierra el Motor con su decisión, una persona analista cuando la solicitud va a revisión, y el comercio desde «Gestión POS» del ERP al aceptar o rechazar la compra aprobada.',
    startAndEnd:
      'Empieza con la solicitud creada en estado `submitted` (sólo si la elegibilidad se reevalúa bien en el servidor). Termina cuando queda `approved` con la aceptación del negocio registrada, o `rejected` (por el Motor, por una persona o porque el comercio la declinó). El desembolso es el proceso siguiente (P-08).',
    whenItFails:
      'Si el Motor no responde, la solicitud NUNCA se rechaza: pasa a `under_review` con modo `engine_unavailable_manual` y Atlas abre su propio caso de revisión. Si el proceso muere antes de preguntar, el barrido de solicitudes `submitted` la vuelve a decidir. Si el Motor abrió caso, la persona lo resuelve en el portal del Motor y el aviso de vuelta mueve la solicitud; si no, hoy no hay pantalla en el portal interno para decidirla.',
    healthIndicator:
      'Proporción de solicitudes decididas con `decision_mode = decision_engine` frente a `engine_unavailable_manual` o `manual`, solicitudes que siguen `submitted` o `under_review` pasado el plazo de vigencia de la decisión, y aprobaciones con `business_acceptance = pending` sin respuesta del comercio.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'credit',
    table: 'credit_applications',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'application_code',
    openStatuses: ['submitted', 'under_review'],
  },
  success: 'La solicitud queda aprobada por el Motor (o por una persona con su motivo) y aceptada por el comercio, lista para desembolsar.',
  failure: 'La solicitud queda rechazada, o atascada en `submitted`/`under_review` sin nadie que pueda resolverla desde una pantalla.',
  sources: [
    'src/modules/credit/credit.controller.ts',
    'src/modules/credit/credit-operations.controller.ts',
    'src/modules/credit/merchant-credit.controller.ts',
    'src/modules/credit/credit-review-callback.controller.ts',
    'src/modules/credit/application/credit-underwriting.service.ts',
    'src/modules/credit/application/credit-decision.service.ts',
    'src/modules/credit/application/credit-submitted-reconciliation.service.ts',
    'src/modules/credit/application/credit-line-refresh.service.ts',
    'src/modules/credit/application/credit-decision-event-publisher.ts',
    'src/modules/credit/application/use-cases/submit-credit-application.use-case.ts',
    'src/modules/credit/credit-review-case.constants.ts',
    'src/modules/operations/manual-review-decision-guards.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts',
    'src/modules/runtime-jobs/scheduled-jobs.credit.ts',
    'src/modules/runtime-jobs/optional-jobs.catalog.ts',
    'AtlasDecisionEngineBackend/src/modules/manual-review/manual-review.service.ts (RUTA_DE_CALLBACK_POR_COLA)',
    'AtlasERPBackend/src/modules/partner-onboarding-gateway/merchant-credit-gateway.controller.ts',
    'AtlasERPFrontend/app/portal-comercio/gestion-pos/page.tsx',
    'AtlasFrontend/apps/consumer-app/src/api/endpoints/credit.ts',
    'memoria atlas-recorrido-signup-a-credito',
    'memoria atlas-plan-motor-decisiones-tasa',
    '_plan-motor-decisiones-tasa-2026-09-25/PLAN.md',
    '_plan-documentar-procesos-y-cableado-portal-2026-09-26/datos/cableado.json (categoría D)',
  ],
  stages: [
    {
      code: 'credit_catalog',
      name: 'Catálogo de productos crediticios',
      description:
        'Operaciones da de alta los productos (nacen en `draft`) y los activa, suspende o retira. No hay productos sembrados: montos, plazos y tasas son decisión de negocio. Hoy no existe pantalla en el portal interno.',
      module: 'credit',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/credit/products',
      roles: CREDIT_OPERATIONS,
      steps: [
        {
          code: 'credit.ops_products_list',
          name: 'Listar los productos del tenant',
          description: 'Vista de operaciones del catálogo, con todos los estados.',
          method: 'GET',
          path: '/operations/credit/products',
          roles: CREDIT_OPERATIONS,
        },
        {
          code: 'credit.ops_product_create',
          name: 'Crear un producto crediticio',
          description: 'El producto nace en `draft`: activarlo es una decisión aparte y auditable.',
          method: 'POST',
          path: '/operations/credit/products',
          roles: CREDIT_OPERATIONS,
          resultingStates: ['draft'],
          errors: ['409 CREDIT_PRODUCT_CODE_ALREADY_EXISTS'],
          successStatus: [201],
        },
        {
          code: 'credit.ops_product_status',
          name: 'Cambiar el estado de un producto',
          description: 'Activa, suspende o retira un producto; exige `reasonCode`.',
          method: 'PATCH',
          path: '/operations/credit/products/:productId/status',
          roles: CREDIT_OPERATIONS,
          input: { status: 'draft | active | suspended | retired', reasonCode: 'string' },
          errors: ['404 CREDIT_PRODUCT_NOT_FOUND'],
        },
      ],
    },
    {
      code: 'credit_line_calculation',
      name: 'Cálculo de la línea de crédito',
      description:
        'Un job pide al Motor la línea de los clientes `active` que no tienen línea o la tienen vieja; también la recalculan el extracto bancario (P-07) y el barrido de mora. Si el Motor no responde, la línea vigente no se toca.',
      module: 'credit',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      steps: [
        {
          code: 'credit.refresh_lines_job',
          name: 'Refrescar líneas ausentes o viejas',
          description: 'Barre clientes `active` sin línea (motivo `onboarding`) o con línea más vieja que el corte, con tope por pasada.',
          kind: 'job',
          job: 'refresh_credit_lines',
          repeatable: true,
        },
        {
          code: 'credit.engine_line_decision',
          name: 'El Motor calcula la línea',
          description:
            'Ejecuta el artefacto de crédito (`DECISION_ENGINE_CREDIT_ARTIFACT`, por omisión `ATLAS_BNPL_UNDERWRITING`) con propósito `credit_line`.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
          errors: ['503 DECISION_ENGINE_UNAVAILABLE (la línea vigente no cambia)'],
        },
      ],
    },
    {
      code: 'credit_line_manual_recalculation',
      name: 'Recálculo manual de la línea',
      description:
        'Operaciones puede pedir de nuevo la línea con el expediente de hoy. La ruta existe y no tiene llamador en ninguna pantalla del portal interno.',
      module: 'credit',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/customers/[customerId]/investigation-summary',
      optional: true,
      roles: CREDIT_OPERATIONS,
      steps: [
        {
          code: 'credit.ops_line_recalculate',
          name: 'Recalcular la línea de un cliente',
          description: 'Abre una versión nueva de la línea y cierra la anterior, dejando escrito qué la movió (motivo `manual`).',
          method: 'POST',
          path: '/operations/credit/customers/:customerId/credit-line/recalculate',
          roles: CREDIT_OPERATIONS,
          optional: true,
          repeatable: true,
          errors: ['503 DECISION_ENGINE_UNAVAILABLE'],
        },
      ],
    },
    {
      code: 'credit_line_view',
      name: 'El cliente ve su línea y su porqué',
      description: 'La app enseña cuánto puede gastar, con qué ingreso se calculó, los motivos de la política y el historial de versiones.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      steps: [
        {
          code: 'credit.customer_line',
          name: 'Consultar la línea vigente',
          description: 'Devuelve la línea decidida por el Motor con su explicación.',
          method: 'GET',
          path: '/customers/:customerId/credit-line',
          roles: CUSTOMER_AND_STAFF,
          errors: ['404 CREDIT_LINE_NOT_CALCULATED'],
        },
        {
          code: 'credit.customer_line_history',
          name: 'Consultar el historial de la línea',
          description: 'Versiones de la línea con lo que movió cada una: responde a «¿por qué me bajó?».',
          method: 'GET',
          path: '/customers/:customerId/credit-line/history',
          roles: CUSTOMER_AND_STAFF,
          optional: true,
        },
      ],
    },
    {
      code: 'credit_application_request',
      name: 'Solicitud de crédito del cliente',
      description:
        'El cliente ve los productos con su elegibilidad y pide monto y plazo; el comercio y la caja llegan resueltos por el lector de QR. El servidor reevalúa la elegibilidad y sólo entonces crea la solicitud.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      resultingStates: ['submitted'],
      steps: [
        {
          code: 'credit.customer_products',
          name: 'Ver productos y elegibilidad',
          description: '`canApply` refleja la elegibilidad real, con sus bloqueadores.',
          method: 'GET',
          path: '/customers/:customerId/credit-products',
          roles: CUSTOMER_AND_STAFF,
        },
        {
          code: 'credit.customer_application_create',
          name: 'Crear la solicitud',
          description:
            'Valida producto, monto y plazo, reevalúa la elegibilidad y persiste la solicitud en `submitted`; luego, fuera de la transacción, pide la decisión al Motor.',
          method: 'POST',
          path: '/customers/:customerId/credit-applications',
          roles: CUSTOMER_AND_STAFF,
          idempotencyKey: true,
          input: {
            productId: 'string',
            requestedAmount: 'decimal',
            requestedTermMonths: 'number',
            purposeCode: 'string?',
            partnerProfileId: 'string?',
            posTerminalId: 'string?',
          },
          resultingStates: ['submitted', 'approved', 'rejected', 'under_review'],
          errors: [
            '404 CREDIT_PRODUCT_NOT_FOUND',
            '409 CREDIT_APPLICATION_ALREADY_OPEN',
            '422 CUSTOMER_NOT_ELIGIBLE',
            '422 REQUESTED_AMOUNT_OUT_OF_RANGE',
            '422 REQUESTED_TERM_OUT_OF_RANGE',
          ],
          events: ['credit.application.submitted'],
          successStatus: [201],
        },
        {
          code: 'credit.customer_applications_list',
          name: 'Ver sus solicitudes',
          description: 'Solicitudes del cliente, más recientes primero; la app las usa para enseñar el estado.',
          method: 'GET',
          path: '/customers/:customerId/credit-applications',
          roles: CUSTOMER_AND_STAFF,
          repeatable: true,
        },
      ],
    },
    {
      code: 'credit_engine_underwriting',
      name: 'Decisión del Motor',
      description:
        'Atlas pregunta al Motor y traduce su desenlace: aprobado, rechazado, revisión (con caso del Motor o caso propio de Atlas `CR-<código>`), diferido si la base habilitante no llegó, o revisión humana si el Motor no respondió.',
      module: 'credit',
      actor: 'system',
      client: 'BLOCK',
      requiredStates: ['submitted'],
      resultingStates: ['approved', 'rejected', 'under_review', 'submitted'],
      steps: [
        {
          code: 'credit.engine_application_decision',
          name: 'El Motor decide la solicitud',
          description: 'Ejecuta el artefacto de crédito; el Motor deduplica por la clave de idempotencia de la solicitud.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
        },
        {
          code: 'credit.decision_recorded_event',
          name: 'Aviso de la decisión al ERP',
          description:
            'Sólo en una aprobación con banda de riesgo real: se escribe en el outbox en la misma transacción, para que el ERP case su MDR por banda.',
          kind: 'event',
          reason: 'Es un evento del outbox que se escribe al guardar la decisión; no lo dispara ninguna llamada propia.',
          optional: true,
          events: ['credit.decision.recorded'],
        },
      ],
    },
    {
      code: 'credit_engine_manual_review',
      name: 'Revisión humana en el Motor',
      description:
        'Cuando el Motor abre su propio caso (`manual_review_case_source = engine`), la persona analista lo asigna y resuelve en el portal del Motor. Atlas rechaza decidirla por su lado (`CREDIT_DECISION_DELEGADA_AL_MOTOR`).',
      module: 'credit',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/manual-reviews/[caseId]',
      link: '{MOTOR}/manual-reviews/{instanceId}',
      optional: true,
      requiredStates: ['under_review'],
      steps: [
        {
          code: 'credit.motor_review_assign',
          name: 'Tomar el caso en el Motor',
          description: 'La persona analista se asigna el caso de la cola CREDIT_REVIEW.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseCode/assign',
          optional: true,
        },
        {
          code: 'credit.motor_review_resolve',
          name: 'Resolver el caso en el Motor',
          description: 'APPROVE, DECLINE o CANCEL; el Motor avisa a Atlas por la ruta de vuelta de la cola CREDIT_REVIEW.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseCode/resolve',
          optional: true,
        },
      ],
    },
    {
      code: 'credit_engine_review_callback',
      name: 'La resolución del Motor vuelve a Atlas',
      description:
        'El Motor llama con clave compartida; APPROVE pasa la solicitud a `approved`, DECLINE a `rejected`; CANCEL la deja como está para que alguien la mire.',
      module: 'credit',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      requiredStates: ['under_review'],
      resultingStates: ['approved', 'rejected'],
      steps: [
        {
          code: 'credit.review_callback',
          name: 'Aplicar la resolución del Motor',
          description: 'Aplica la decisión a la solicitud por su `executionId`. Sin clave configurada responde 401.',
          method: 'POST',
          path: '/internal/credit/manual-review-callback',
          auth: false,
          optional: true,
          input: { executionId: 'string', decision: 'APPROVE | DECLINE | CANCEL', reason: 'string?', resolvedByInternalUserId: 'string?' },
          errors: ['400 Falta executionId', '401 clave de callback ausente o inválida'],
        },
      ],
    },
    {
      code: 'credit_atlas_manual_decision',
      name: 'Decisión humana en Atlas',
      description:
        'Cuando el Motor mandó a revisión sin abrir caso, o no respondió, Atlas abre el caso `CR-<código>` que aparece en la cola de trabajo; pero esa cola rechaza cerrarlo (`MANUAL_REVIEW_ES_DE_CREDITO`) y la decisión sobre la solicitud no tiene pantalla en el portal interno.',
      module: 'credit',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/credit/applications/[applicationId]',
      optional: true,
      roles: CREDIT_OPERATIONS,
      requiredStates: ['under_review', 'submitted'],
      resultingStates: ['approved', 'rejected', 'under_review'],
      steps: [
        {
          code: 'credit.ops_application_detail',
          name: 'Ver la solicitud con su historial',
          description: 'Solicitud y eventos, más recientes primero.',
          method: 'GET',
          path: '/operations/credit/applications/:applicationId',
          roles: CREDIT_OPERATIONS,
          optional: true,
        },
        {
          code: 'credit.ops_application_decision',
          name: 'Decidir la solicitud',
          description:
            'Aprueba, rechaza o pide más información (rechazar o pedir información exige nota). Queda como decisión humana (`decision_mode = manual`) y cierra el caso de crédito.',
          method: 'POST',
          path: '/operations/credit/applications/:applicationId/decision',
          roles: CREDIT_OPERATIONS,
          optional: true,
          input: { decision: 'approve | reject | request_more_information', reasonCode: 'string', notes: 'string?' },
          errors: ['404 CREDIT_APPLICATION_NOT_FOUND', '409 CREDIT_APPLICATION_ALREADY_DECIDED', '409 CREDIT_DECISION_DELEGADA_AL_MOTOR'],
        },
      ],
    },
    {
      code: 'credit_business_acceptance',
      name: 'Aceptación del comercio',
      description:
        'Una aprobación del Motor nace con `business_acceptance = pending`: el comercio, en «Gestión POS», acepta o rechaza (sin tocar importe ni calendario). Declinar exige motivo y deja la solicitud `rejected`.',
      module: 'credit',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/gestion-pos',
      terminal: true,
      roles: ERP_MERCHANT_ROLES,
      requiredStates: ['approved'],
      resultingStates: ['approved', 'rejected'],
      steps: [
        {
          code: 'credit.erp_merchant_applications',
          name: 'Ver las compras que esperan respuesta',
          description: 'El ERP reenvía al núcleo; la lista no incluye la identidad del solicitante.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant-credit/:partnerId/applications',
          roles: ERP_MERCHANT_ROLES,
        },
        {
          code: 'credit.merchant_applications',
          name: 'Solicitudes del comercio en el núcleo',
          description: 'Por defecto sólo las pendientes; comprueba que el expediente es de este comercio.',
          method: 'GET',
          path: '/merchant/partners/:partnerId/credit-applications',
          roles: MERCHANT_AND_STAFF,
          errors: ['403 el expediente no pertenece a este comercio'],
        },
        {
          code: 'credit.erp_merchant_acceptance',
          name: 'Aceptar o rechazar la compra',
          description: 'Cuerpo `{ accepted, reasonCode?, notes? }`: sin importe ni calendario.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/merchant-credit/:partnerId/applications/:applicationId/acceptance',
          roles: ERP_MERCHANT_ROLES,
        },
        {
          code: 'credit.merchant_acceptance',
          name: 'Registrar la aceptación en el núcleo',
          description: 'Escribe `business_acceptance` (accepted/declined); declinar deja la solicitud `rejected`.',
          method: 'POST',
          path: '/merchant/partners/:partnerId/credit-applications/:applicationId/acceptance',
          roles: MERCHANT_AND_STAFF,
          input: { accepted: 'boolean', reasonCode: 'string? (obligatorio al declinar)', notes: 'string?' },
          errors: [
            '403 la solicitud no nació en este comercio',
            '404 CREDIT_APPLICATION_NOT_FOUND',
            '409 CREDIT_BUSINESS_ACCEPTANCE_NOT_PENDING',
          ],
        },
      ],
    },
    {
      code: 'credit_business_acceptance_by_operations',
      name: 'Aceptación del negocio por operaciones',
      description:
        'Camino alternativo por la consola de operaciones para las aprobaciones del Motor pendientes. La ruta existe y no tiene pantalla en el portal interno.',
      module: 'credit',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/credit/applications/[applicationId]',
      optional: true,
      roles: CREDIT_OPERATIONS,
      requiredStates: ['approved'],
      steps: [
        {
          code: 'credit.ops_business_acceptance',
          name: 'Aceptar o declinar desde operaciones',
          description: 'Sólo para solicitudes aprobadas por el Motor y todavía pendientes; declinar exige motivo.',
          method: 'POST',
          path: '/operations/credit/applications/:applicationId/business-acceptance',
          roles: CREDIT_OPERATIONS,
          optional: true,
          errors: ['404 CREDIT_APPLICATION_NOT_FOUND', '409 CREDIT_BUSINESS_ACCEPTANCE_NOT_PENDING'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'credit.entry',
      from: null,
      to: 'credit.customer_products',
      condition: 'always',
      description: 'Entrada: el cliente activo mira qué puede pedir.',
      isDefault: true,
    },
    {
      code: 'credit.products_to_create',
      from: 'credit.customer_products',
      to: 'credit.customer_application_create',
      condition: 'on_success',
      description: 'Con `canApply`, el cliente pide monto y plazo.',
      isDefault: true,
    },
    {
      code: 'credit.create_to_engine',
      from: 'credit.customer_application_create',
      to: 'credit.engine_application_decision',
      condition: 'on_success',
      description: 'Creada en `submitted`, se pregunta al Motor fuera de la transacción.',
      isDefault: true,
    },
    {
      code: 'credit.engine_approved',
      from: 'credit.engine_application_decision',
      to: 'credit.decision_recorded_event',
      condition: 'conditional',
      expression: { status: 'approved', riskBand: 'present' },
      description: 'Aprobada con banda: aviso al ERP.',
    },
    {
      code: 'credit.event_to_merchant',
      from: 'credit.decision_recorded_event',
      to: 'credit.erp_merchant_applications',
      condition: 'on_success',
      description: 'La compra aprobada espera la respuesta del comercio.',
      isDefault: true,
    },
    {
      code: 'credit.engine_to_motor_review',
      from: 'credit.engine_application_decision',
      to: 'credit.motor_review_assign',
      condition: 'conditional',
      expression: { status: 'under_review', manualReviewCaseSource: 'engine' },
      description: 'El Motor abrió su caso: se resuelve en su portal.',
    },
    {
      code: 'credit.engine_to_atlas_review',
      from: 'credit.engine_application_decision',
      to: 'credit.ops_application_detail',
      condition: 'conditional',
      expression: { status: 'under_review', manualReviewCaseSource: 'atlas' },
      description: 'Revisión sin caso del Motor, o Motor caído: decide una persona en Atlas.',
    },
    {
      code: 'credit.motor_assign_to_resolve',
      from: 'credit.motor_review_assign',
      to: 'credit.motor_review_resolve',
      condition: 'on_success',
      description: 'Asignado, se resuelve.',
    },
    {
      code: 'credit.motor_resolve_to_callback',
      from: 'credit.motor_review_resolve',
      to: 'credit.review_callback',
      condition: 'on_success',
      description: 'El Motor devuelve la resolución a Atlas.',
    },
    {
      code: 'credit.callback_to_merchant',
      from: 'credit.review_callback',
      to: 'credit.erp_merchant_applications',
      condition: 'conditional',
      expression: { decision: 'APPROVE' },
      description: 'Aprobada por la persona del Motor: pasa al comercio.',
    },
    {
      code: 'credit.atlas_detail_to_decision',
      from: 'credit.ops_application_detail',
      to: 'credit.ops_application_decision',
      condition: 'on_success',
      description: 'Vista la solicitud, se decide.',
    },
    {
      code: 'credit.merchant_list_to_core',
      from: 'credit.erp_merchant_applications',
      to: 'credit.merchant_applications',
      condition: 'always',
      description: 'El ERP reenvía la consulta al núcleo.',
      isDefault: true,
    },
    {
      code: 'credit.merchant_list_to_accept',
      from: 'credit.merchant_applications',
      to: 'credit.erp_merchant_acceptance',
      condition: 'on_success',
      description: 'El comercio responde.',
      isDefault: true,
    },
    {
      code: 'credit.merchant_accept_to_core',
      from: 'credit.erp_merchant_acceptance',
      to: 'credit.merchant_acceptance',
      condition: 'always',
      description: 'El ERP reenvía la aceptación al núcleo.',
      isDefault: true,
    },
    {
      code: 'credit.exit',
      from: 'credit.merchant_acceptance',
      to: null,
      condition: 'always',
      description: 'Salida: aceptada, pasa a desembolso (P-08); declinada, queda rechazada.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'credit.customer_application_create',
      dependsOn: 'credit.ops_product_status',
      type: 'requires_data',
      description: 'Sin un producto `active` no hay nada que solicitar.',
    },
    {
      step: 'credit.customer_line',
      dependsOn: 'credit.engine_line_decision',
      type: 'requires_data',
      description: 'La línea la calcula el Motor; sin ella responde CREDIT_LINE_NOT_CALCULATED.',
    },
    {
      step: 'credit.review_callback',
      dependsOn: 'credit.motor_review_resolve',
      type: 'requires_completion',
      description: 'El aviso de vuelta lo emite la resolución en el Motor.',
    },
    {
      step: 'credit.merchant_acceptance',
      dependsOn: 'credit.engine_application_decision',
      type: 'requires_completion',
      description: 'Sólo una aprobación del Motor deja la aceptación pendiente.',
    },
  ],
};
