/**
 * @file Proceso declarado en código: Alta por fases y captura KYC del cliente.
 * @business Sin expediente completo no hay decisión de riesgo ni crédito: este proceso lleva al cliente, ya con cuenta, por las cuatro fases del alta (contacto, identidad, situación, hábitos) hasta dejar el paquete enviado a revisión.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; escrita el 2026-09-26 desde los controladores de `customer-onboarding`, `customer-privacy` y `operations`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const CUSTOMER_AND_INTERNAL = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const OPERATIONS_READERS = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'];
const EVIDENCE_VIEWERS = ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'];

export const CUSTOMER_ONBOARDING_KYC: WorkflowDefinitionFixture = {
  processId: 'P-02',
  code: 'customer_onboarding_kyc',
  version: 'v1',
  name: 'Alta por fases y captura KYC del cliente',
  description:
    'Registro progresivo del cliente con cuenta: carnet y selfie, datos personales, domicilio, situación económica, referencias, permisos del teléfono y encuesta de hábitos, con guardado parcial, hasta el envío del paquete a revisión. Incluye la mirada del equipo interno sobre el expediente.',
  processType: 'customer_journey',
  ownerDomain: 'customer_onboarding',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Para decidir si a una persona se le puede dar crédito hace falta saber quién es, dónde vive, de qué vive y a quién se puede llamar. Este proceso reúne esa evidencia en un solo expediente, en cuatro fases y con guardado parcial, para que la persona pueda dejarlo y retomarlo sin perder lo cargado.',
    whoStartsAndCloses:
      'Lo inicia el cliente desde el centro de registro de la app, una vez que ya tiene cuenta y contacto verificado, y lo cierra él mismo al pulsar «Enviar a revisión». El operador interno sólo mira: revisa el expediente, las imágenes del carnet y el resumen de investigación desde la cola de trabajo del portal.',
    startAndEnd:
      'Empieza cuando la app lee el estado del alta y encuentra la primera sección pendiente (el orden vive en ONBOARDING_SECTION_CODES: contacto, identidad, datos personales, domicilio, economía, referencias, permisos del teléfono y encuesta). Termina cuando el envío deja al cliente en under_review, cierra el flujo como completed y dispara la evaluación de riesgo.',
    whenItFails:
      'Si falta una sección, el envío responde 422 ONBOARDING_INCOMPLETE con la lista de secciones pendientes y el cliente sigue editando. Un envío repetido responde ONBOARDING_ALREADY_SUBMITTED. Quien deja el alta a medias no recibe aviso: el job mark_abandoned_onboardings marca el flujo como abandonado tras 30 días sin actividad, sin tocar el estado del cliente.',
    healthIndicator:
      'Tasa de flujos de alta cerrados como completed frente a abandoned en onboarding_flows (completion_status, total_duration_seconds) y tiempo por fase en onboarding_step_events; un aumento de 422 ONBOARDING_INCOMPLETE en el envío indica que la app deja pasar secciones incompletas.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'telemetry',
    table: 'onboarding_flows',
    idColumn: '_id',
    statusColumn: 'completion_status',
    labelColumn: 'customer_id',
    openStatuses: ['in_progress'],
  },
  success: 'El paquete del alta está completo y enviado: el cliente queda en under_review y el flujo de alta cerrado como completed.',
  failure: 'El alta se queda a medias (flujo abandoned tras 30 días sin actividad) o el envío se rechaza por secciones incompletas.',
  sources: [
    'src/modules/customer-onboarding/customer-onboarding-status.controller.ts',
    'src/modules/customer-onboarding/application/customer-onboarding-status.service.ts',
    'src/modules/customer-onboarding/customer-onboarding-profile.controller.ts',
    'src/modules/customer-onboarding/customer-packages.controller.ts',
    'src/modules/customer-onboarding/customer-supporting-evidence.controller.ts',
    'src/modules/customer-onboarding/consumer-survey/consumer-survey.controller.ts',
    'src/modules/customer-onboarding/customer-evidence-view.controller.ts',
    'src/modules/customer-onboarding/customer-verification.controller.ts',
    'src/modules/customer-onboarding/application/customer-compliance-screening.service.ts',
    'src/modules/customer-onboarding/application/onboarding-abandonment.service.ts',
    'src/modules/customers/customer-eligibility.constants.ts',
    'src/modules/operations/operations.controller.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts',
    'docs/architecture/onboarding-flujo-corregido.md',
    'AtlasFrontend/apps/consumer-app/src/api/endpoints/onboarding.ts',
    'AtlasAdminPortal/src/features/operations-cases/services.ts',
    'AtlasAdminPortal/src/features/operations-cases/identity-evidence-panel.tsx',
    'memoria atlas-alta-por-fases-y-bitacora',
    '_plan-alta-por-fases-y-bitacora-2026-09-17/PLAN.md',
    '_plan-documentar-procesos-y-cableado-portal-2026-09-26/datos/cableado.json',
  ],
  metadata: {
    handsOffTo: ['P-03 identity_verification (verificación del carnet)', 'P-04 onboarding_risk_assessment (al enviar)'],
    comesFrom: 'P-01 account_signup_to_login (cuenta y contacto verificado)',
  },
  stages: [
    {
      code: 'kyc_registration_center',
      name: 'Centro de registro',
      description:
        'La app lee el avance del alta y abre la primera sección pendiente. Es el punto de retorno cada vez que el cliente vuelve.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      steps: [
        {
          code: 'kyc.status',
          name: 'Consultar el avance del alta',
          description:
            'Devuelve secciones, porcentaje, bloqueadores y la siguiente sección; se calcula con la misma regla que la elegibilidad.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/status',
          roles: CUSTOMER_AND_INTERNAL,
          repeatable: true,
          output: { sections: 'OnboardingSection[]', nextStep: 'string', canSubmit: 'boolean', completionPercentage: 'number' },
        },
      ],
    },
    {
      code: 'kyc_identity_capture',
      name: 'Fase identidad: carnet y selfie',
      description:
        'El carnet va ANTES que los datos personales: el cliente sube anverso, reverso y selfie al almacén y registra el paquete. La verificación del carnet es el proceso P-03.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      completionRule: { type: 'onboarding_section', sectionCode: 'identity_documents' },
      steps: [
        {
          code: 'kyc.upload_url',
          name: 'Pedir permiso de subida',
          description: 'Devuelve una URL firmada para subir cada imagen al almacén de documentos.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/documents/upload-url',
          roles: CUSTOMER_AND_INTERNAL,
          repeatable: true,
          errors: ['422 PROFILE_NOT_EDITABLE_IN_STATUS', '422 EVIDENCE_OBJECT_TOO_LARGE', '503 DOCUMENT_STORAGE_NOT_CONFIGURED'],
          successStatus: [201],
        },
        {
          code: 'kyc.upload_object',
          name: 'Subir la imagen al almacén',
          description: 'La app hace el PUT directamente contra la URL firmada del almacén de objetos (MinIO).',
          kind: 'external',
          reason: 'La subida va del teléfono al almacén de objetos con la URL firmada; no pasa por la API de Atlas.',
          repeatable: true,
        },
        {
          code: 'kyc.identity_package',
          name: 'Registrar el paquete de identidad',
          description: 'Registra los documentos y la selfie ya subidos; el servidor comprueba que los objetos existen en el almacén.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-package',
          roles: CUSTOMER_AND_INTERNAL,
          idempotencyKey: true,
          errors: ['422 EVIDENCE_OBJECT_NOT_FOUND', '409 hash de evidencia repetido'],
        },
      ],
    },
    {
      code: 'kyc_personal_data',
      name: 'Datos personales',
      description: 'Nombre, apellido y fecha de nacimiento (18 a 100 años); guardado parcial.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      completionRule: { type: 'onboarding_section', sectionCode: 'personal_data' },
      steps: [
        {
          code: 'kyc.profile',
          name: 'Guardar los datos personales',
          description: 'Actualiza el perfil y devuelve la versión vigente.',
          method: 'PATCH',
          path: '/customer-onboarding/:customerId/profile',
          roles: CUSTOMER_AND_INTERNAL,
          repeatable: true,
          errors: ['422 PROFILE_NOT_EDITABLE_IN_STATUS'],
        },
      ],
    },
    {
      code: 'kyc_situation',
      name: 'Fase situación: domicilio, economía y referencias',
      description: 'Domicilio, seis atributos económicos obligatorios y al menos dos referencias personales.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      steps: [
        {
          code: 'kyc.address_package',
          name: 'Entregar el paquete de domicilio',
          description: 'Registra el domicilio del cliente como versión vigente.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/address-package',
          roles: CUSTOMER_AND_INTERNAL,
          idempotencyKey: true,
        },
        {
          code: 'kyc.financial_profile',
          name: 'Registrar la situación laboral y económica',
          description: 'Guarda los atributos económicos (situación laboral, antigüedad, ingresos, gastos, actividad y origen de fondos).',
          method: 'PUT',
          path: '/customer-onboarding/:customerId/financial-profile',
          roles: CUSTOMER_AND_INTERNAL,
          repeatable: true,
          errors: ['422 PROFILE_NOT_EDITABLE_IN_STATUS', '422 ATTRIBUTE_CATALOG_NOT_SEEDED'],
        },
        {
          code: 'kyc.references_add',
          name: 'Registrar referencias personales',
          description: 'Entre dos y cinco referencias; no puede ser el propio cliente.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/reference-contacts',
          roles: CUSTOMER_AND_INTERNAL,
          errors: ['409 REFERENCE_ALREADY_REGISTERED', '422 REFERENCE_LIMIT_EXCEEDED', '422 REFERENCE_CANNOT_BE_THE_CUSTOMER'],
          successStatus: [201],
        },
        {
          code: 'kyc.references_list',
          name: 'Listar las referencias',
          description: 'Devuelve las referencias sin nombre ni teléfono completo (sólo los últimos cuatro dígitos).',
          method: 'GET',
          path: '/customer-onboarding/:customerId/reference-contacts',
          roles: CUSTOMER_AND_INTERNAL,
        },
        {
          code: 'kyc.references_remove',
          name: 'Quitar una referencia',
          description: 'Borrado lógico. La app del cliente no la llama hoy: no aparece en sus llamadas.',
          method: 'DELETE',
          path: '/customer-onboarding/:customerId/reference-contacts/:referenceId',
          roles: CUSTOMER_AND_INTERNAL,
          optional: true,
          errors: ['404 REFERENCE_NOT_FOUND'],
        },
        {
          code: 'kyc.supporting_evidence',
          name: 'Aportar una evidencia de apoyo',
          description: 'QR de cobro, factura o audio de ocupación; queda pendiente de revisión.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/supporting-evidence',
          roles: ['customer'],
          optional: true,
          repeatable: true,
          successStatus: [201],
        },
      ],
    },
    {
      code: 'kyc_device_permissions',
      name: 'Permisos del teléfono',
      description:
        'La sección se cierra con una DECISIÓN (sí o no) sobre la agenda y la ubicación; con la agenda concedida la app envía un resumen agregado, nunca los contactos.',
      module: 'customer_privacy',
      actor: 'customer',
      client: 'CONSUMER_APP',
      completionRule: { type: 'onboarding_section', sectionCode: 'device_permissions' },
      steps: [
        {
          code: 'kyc.permission_decisions',
          name: 'Registrar la decisión sobre agenda y ubicación',
          description: 'Registra el consentimiento de las finalidades device_address_book y location_tracking, incluida la negativa.',
          method: 'POST',
          path: '/customers/:customerId/privacy/consent-decisions',
          roles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
        },
        {
          code: 'kyc.contacts_snapshot',
          name: 'Enviar el resumen agregado de la agenda',
          description: 'Sólo cuentas y medidas, sin contactos; lo analiza el artefacto de identidad del Motor.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contacts-snapshot',
          roles: CUSTOMER_AND_INTERNAL,
          optional: true,
          errors: ['400 snapshot incoherente'],
          successStatus: [202],
        },
      ],
    },
    {
      code: 'kyc_consumer_survey',
      name: 'Fase hábitos: encuesta de consumo',
      description: 'Seis preguntas de hábitos de consumo, con guardado parcial.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      completionRule: { type: 'onboarding_section', sectionCode: 'consumer_survey' },
      steps: [
        {
          code: 'kyc.survey_catalog',
          name: 'Leer el catálogo de la encuesta',
          description: 'Versión vigente de las preguntas y sus opciones.',
          method: 'GET',
          path: '/customer-onboarding/consumer-survey/catalog',
          roles: CUSTOMER_AND_INTERNAL,
        },
        {
          code: 'kyc.survey_state',
          name: 'Leer las respuestas guardadas',
          description: 'Estado de la encuesta del cliente para retomarla.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/consumer-survey',
          roles: CUSTOMER_AND_INTERNAL,
          optional: true,
        },
        {
          code: 'kyc.survey_save',
          name: 'Guardar las respuestas',
          description: 'Guarda respuestas parciales o completas; con las seis contestadas la sección queda completa.',
          method: 'PUT',
          path: '/customer-onboarding/:customerId/consumer-survey',
          roles: CUSTOMER_AND_INTERNAL,
          repeatable: true,
        },
      ],
    },
    {
      code: 'kyc_submission',
      name: 'Envío a revisión',
      description:
        'Único punto donde se valida la completitud. Pasa al cliente a under_review, cierra el flujo, dispara la evaluación de riesgo (P-04) y reevalúa la elegibilidad.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      requiredStates: ['onboarding_in_progress', 'observed'],
      resultingStates: ['under_review'],
      steps: [
        {
          code: 'kyc.submit',
          name: 'Enviar el paquete a revisión',
          description: 'Con acknowledgement: true. Si todas las secciones están completas, transiciona a under_review y cierra el flujo.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/submit',
          roles: CUSTOMER_AND_INTERNAL,
          idempotencyKey: true,
          requiredStates: ['onboarding_in_progress', 'observed'],
          resultingStates: ['under_review'],
          input: { acknowledgement: 'true' },
          errors: ['422 ONBOARDING_INCOMPLETE', '422 ONBOARDING_ALREADY_SUBMITTED', '422 ONBOARDING_NOT_SUBMITTABLE_IN_STATUS'],
          events: ['customer.lifecycle.under_review'],
        },
        {
          code: 'kyc.observations',
          name: 'Consultar las observaciones',
          description: 'Incidencias y casos abiertos visibles para el cliente, sin las notas internas del analista.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/observations',
          roles: CUSTOMER_AND_INTERNAL,
          optional: true,
          repeatable: true,
        },
      ],
    },
    {
      code: 'kyc_abandonment',
      name: 'Cierre de altas abandonadas',
      description: 'Marca como abandoned los flujos sin actividad en 30 días. Marca el flujo, no al cliente: puede volver y retomar.',
      module: 'customer_onboarding',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      terminal: true,
      steps: [
        {
          code: 'kyc.mark_abandoned_job',
          name: 'Marcar altas abandonadas',
          description: 'Job programado que cierra los flujos in_progress sin actividad reciente.',
          kind: 'job',
          job: 'mark_abandoned_onboardings',
          resultingStates: ['abandoned'],
        },
        {
          code: 'kyc.mark_abandoned_http',
          name: 'Marcar altas abandonadas a mano',
          description: 'La misma pasada expuesta por HTTP; el catálogo de jobs del portal la muestra.',
          method: 'POST',
          path: '/customer-onboarding/jobs/mark-abandoned',
          roles: ['admin', 'platform_admin', 'system'],
          optional: true,
        },
      ],
    },
    {
      code: 'kyc_back_office_review',
      name: 'Revisión del expediente por el equipo interno',
      description: 'El operador localiza al cliente en la cola de trabajo y abre su resumen de investigación con las imágenes del carnet.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/work-queue',
      roles: OPERATIONS_READERS,
      steps: [
        {
          code: 'kyc.ops_work_queue',
          name: 'Ver la cola de trabajo',
          description: 'Cola combinada de revisión manual y fraude.',
          method: 'GET',
          path: '/operations/work-queue',
          roles: OPERATIONS_READERS,
        },
      ],
    },
    {
      code: 'kyc_investigation_summary',
      name: 'Resumen de investigación del cliente',
      description: 'Expediente del cliente con sus documentos; desde aquí el operador puede resolver la identidad (P-03).',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      parent: 'kyc_back_office_review',
      screen: '/internal/operations/customers/[customerId]/investigation-summary',
      roles: OPERATIONS_READERS,
      steps: [
        {
          code: 'kyc.ops_investigation_summary',
          name: 'Abrir el resumen de investigación',
          description: 'Datos, casos, fraude, último intento de identidad y agenda del cliente.',
          method: 'GET',
          path: '/operations/customers/:customerId/investigation-summary',
          roles: OPERATIONS_READERS,
        },
        {
          code: 'kyc.ops_evidence_list',
          name: 'Listar los documentos del cliente',
          description: 'Documentos de identidad subidos por el cliente.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/evidence-documents',
          roles: EVIDENCE_VIEWERS,
        },
        {
          code: 'kyc.ops_evidence_content',
          name: 'Ver un documento',
          description: 'Los bytes del documento por descarga autenticada.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/evidence-documents/:documentId/content',
          roles: EVIDENCE_VIEWERS,
          repeatable: true,
        },
        {
          code: 'kyc.ops_behavior_summary',
          name: 'Ver el resumen de comportamiento del alta',
          description: 'Tiempos y toques por fase del alta. Sin llamador en el portal hoy (triaje D).',
          method: 'GET',
          path: '/operations/customers/:customerId/behavior-summary',
          roles: OPERATIONS_READERS,
          optional: true,
        },
      ],
    },
    {
      code: 'kyc_customer_file',
      name: 'Expediente de archivos del cliente',
      description: 'Vista de archivos del cliente en el portal, enlazada desde el resumen de investigación.',
      module: 'files',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      parent: 'kyc_back_office_review',
      screen: '/internal/files/cliente/[customerId]',
      optional: true,
      steps: [
        {
          code: 'kyc.ops_customer_file',
          name: 'Revisar el expediente de archivos',
          description: 'Consulta de los archivos del cliente desde el portal.',
          kind: 'manual',
          reason: 'Consulta humana del expediente en el portal; sus lecturas pertenecen al módulo de archivos, no a este proceso.',
          optional: true,
        },
      ],
    },
    {
      code: 'kyc_compliance_screening',
      name: 'Cribado de listas restrictivas',
      description:
        'Coteja por hash nombre, teléfono y correo contra las listas vigentes; una coincidencia bloquea la habilitación (COMPLIANCE_MATCH_PENDING). Hoy sólo existe por HTTP: sin pantalla y sin job que lo dispare.',
      module: 'customer_onboarding',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/customers/[customerId]/investigation-summary',
      optional: true,
      roles: ['compliance_analyst', 'risk_analyst', 'admin', 'platform_admin'],
      steps: [
        {
          code: 'kyc.ops_compliance_screening',
          name: 'Ejecutar el cribado',
          description: 'Idempotente; una coincidencia nueva lleva al cliente a under_review.',
          method: 'POST',
          path: '/operations/customers/:customerId/compliance/screening',
          roles: ['compliance_analyst', 'risk_analyst', 'admin', 'platform_admin', 'system'],
          optional: true,
        },
        {
          code: 'kyc.ops_compliance_clear',
          name: 'Descartar coincidencias',
          description: 'Cierra falsos positivos con código de razón y nota obligatorios.',
          method: 'POST',
          path: '/operations/customers/:customerId/compliance/clear-matches',
          roles: ['compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'kyc.entry',
      from: null,
      to: 'kyc.status',
      condition: 'always',
      description: 'Entrada: la app lee el avance del alta.',
      isDefault: true,
    },
    {
      code: 'kyc.status_to_identity',
      from: 'kyc.status',
      to: 'kyc.upload_url',
      condition: 'conditional',
      expression: { nextStep: 'identity_documents' },
      description: 'La primera sección pendiente es la identidad.',
      isDefault: true,
    },
    { code: 'kyc.upload_to_object', from: 'kyc.upload_url', to: 'kyc.upload_object', condition: 'on_success', isDefault: true },
    { code: 'kyc.object_to_package', from: 'kyc.upload_object', to: 'kyc.identity_package', condition: 'on_success', isDefault: true },
    { code: 'kyc.package_to_profile', from: 'kyc.identity_package', to: 'kyc.profile', condition: 'on_success', isDefault: true },
    { code: 'kyc.profile_to_address', from: 'kyc.profile', to: 'kyc.address_package', condition: 'on_success', isDefault: true },
    {
      code: 'kyc.address_to_financial',
      from: 'kyc.address_package',
      to: 'kyc.financial_profile',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'kyc.financial_to_references',
      from: 'kyc.financial_profile',
      to: 'kyc.references_add',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'kyc.references_to_permissions',
      from: 'kyc.references_add',
      to: 'kyc.permission_decisions',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'kyc.permissions_to_snapshot',
      from: 'kyc.permission_decisions',
      to: 'kyc.contacts_snapshot',
      condition: 'conditional',
      expression: { device_address_book: 'granted' },
      description: 'Con la agenda concedida se envía el resumen agregado.',
    },
    {
      code: 'kyc.permissions_to_survey',
      from: 'kyc.permission_decisions',
      to: 'kyc.survey_catalog',
      condition: 'on_success',
      isDefault: true,
    },
    { code: 'kyc.survey_catalog_to_save', from: 'kyc.survey_catalog', to: 'kyc.survey_save', condition: 'on_success', isDefault: true },
    { code: 'kyc.survey_to_submit', from: 'kyc.survey_save', to: 'kyc.submit', condition: 'on_success', isDefault: true },
    {
      code: 'kyc.submit_incomplete',
      from: 'kyc.submit',
      to: 'kyc.status',
      condition: 'on_error',
      description: '422 ONBOARDING_INCOMPLETE: vuelve al centro de registro con las secciones pendientes.',
    },
    {
      code: 'kyc.exit',
      from: 'kyc.submit',
      to: null,
      condition: 'on_success',
      description: 'Paquete enviado: sigue P-04.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'kyc.identity_package',
      dependsOn: 'kyc.upload_object',
      type: 'requires_completion',
      description: 'El paquete cita objetos que tienen que existir en el almacén.',
    },
    { step: 'kyc.upload_object', dependsOn: 'kyc.upload_url', type: 'requires_data', description: 'La subida usa la URL firmada.' },
    {
      step: 'kyc.contacts_snapshot',
      dependsOn: 'kyc.permission_decisions',
      type: 'soft',
      description: 'Sin permiso de agenda no hay resumen que enviar.',
    },
    {
      step: 'kyc.survey_save',
      dependsOn: 'kyc.survey_catalog',
      type: 'requires_data',
      description: 'Las respuestas citan la versión del catálogo.',
    },
    {
      step: 'kyc.submit',
      dependsOn: 'kyc.survey_save',
      type: 'requires_completion',
      description: 'El envío exige las ocho secciones completas.',
    },
    {
      step: 'kyc.ops_evidence_content',
      dependsOn: 'kyc.ops_evidence_list',
      type: 'requires_data',
      description: 'El documento se elige de la lista.',
    },
    {
      step: 'kyc.ops_compliance_clear',
      dependsOn: 'kyc.ops_compliance_screening',
      type: 'requires_completion',
      description: 'Sólo se descartan coincidencias que el cribado registró.',
    },
  ],
};
