/**
 * @file Proceso declarado en código: Soporte: casos, chat, mesa de ayuda, SLA y base de conocimiento.
 * @business Un cliente o un comercio con un problema necesita que alguien lo escuche, lo registre y lo resuelva a tiempo; este proceso convierte cada pedido de ayuda en un expediente trazable con motivo, responsable, plazo y código de resolución.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; rutas de `src/modules/support/*.controller.ts`, job `sweep_support_sla` y pantallas reales de la app, el portal de comercio y el portal admin.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** Roles de `@Roles` en `mobile-support.controller.ts`. */
const MOBILE_ROLES = ['customer', 'internal_operator', 'admin', 'platform_admin'];
/** Roles de `@Roles` en `support-chat.controller.ts` y `support-attachments.controller.ts`. */
const CHAT_ROLES = [
  'customer',
  'merchant',
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'fraud_analyst',
  'admin',
  'platform_admin',
];
/** Roles de `@Roles` en `internal-support.controller.ts`, `internal-support-desk.controller.ts` e `internal-support-catalog.controller.ts`. */
const DESK_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'];
/** Roles de `@Roles` en `support-knowledge-admin.controller.ts`. */
const KNOWLEDGE_ROLES = ['internal_operator', 'compliance_analyst', 'risk_analyst', 'admin', 'platform_admin'];
/** Rutas de supervisión de la mesa (`@Roles('admin', 'platform_admin')` a nivel de método). */
const SUPERVISOR_ROLES = ['admin', 'platform_admin'];

export const CUSTOMER_SUPPORT_CASE: WorkflowDefinitionFixture = {
  processId: 'P-12',
  code: 'customer_support_case',
  version: 'v1',
  name: 'Soporte: casos, chat, mesa de ayuda, SLA y base de conocimiento',
  description:
    'Del pedido de ayuda del cliente (app) o del comercio (portal de comercio) al caso resuelto con código de resolución y causa raíz, pasando por la mesa de soporte del portal admin, el chat, el escalado y el barrido de plazos (SLA).',
  processType: 'back_office',
  ownerDomain: 'support',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ATLAS_BACKEND', 'ERP_BACKEND'],
  narrative: {
    whyExists:
      'Un cliente o un comercio con un problema necesita que alguien lo escuche y lo resuelva a tiempo. El soporte convierte cada pedido en un expediente trazable: el caso es el expediente y el chat sólo un canal, así que cerrar la conversación no cierra el caso y cada resolución queda con motivo, código de resolución y causa raíz medibles.',
    whoStartsAndCloses:
      'Lo inicia el cliente desde «Soporte» en la app o el usuario del comercio desde /portal-comercio/soporte; lo toma un agente de soporte desde la mesa del portal admin (/internal/support), que lo resuelve y lo cierra. El cliente puede pedir el cierre, calificarlo o reabrirlo; un administrador da de alta a los agentes y el sistema vigila los plazos.',
    startAndEnd:
      'Empieza cuando se abre un canal de chat o un caso (estado NEW) y termina cuando el agente lo resuelve con código de resolución y causa raíz (RESOLVED) y lo cierra (CLOSED). CLOSED sólo sale hacia REOPENED; DUPLICATE y CANCELLED también cierran el expediente sin resolverlo.',
    whenItFails:
      'Sin catálogo de categorías sembrado toda apertura de caso falla con SUPPORT_CATEGORY_NOT_FOUND; un agente sin perfil en la mesa recibe 403 SUPPORT_AGENT_PROFILE_REQUIRED aunque sea administrador. Si el caso supera su plazo, el barrido programado sweep_support_sla lo marca y publica support.sla.breached; antes de que existiera ese job, los plazos vencían sin que nadie se enterara.',
    healthIndicator:
      'Porcentaje de casos resueltos dentro de su plazo (eventos support.sla.breached frente a casos resueltos), casos abiertos por estado en la mesa, proporción de canales con caso asociado (support_channels.case_id) y calificación del cliente tras el cierre.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'support',
    table: 'support_cases',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'case_number',
    openStatuses: [
      'NEW',
      'TRIAGED',
      'ASSIGNED',
      'IN_PROGRESS',
      'WAITING_CUSTOMER',
      'WAITING_INTERNAL',
      'WAITING_PARTNER',
      'ESCALATED',
      'ON_HOLD',
      'REOPENED',
    ],
  },
  success: 'El caso queda RESOLVED y luego CLOSED con código de resolución y causa raíz, dentro de su plazo, y el cliente lo califica.',
  failure: 'El caso no llega a abrirse (sin categoría), se queda sin agente, vence su plazo o se cierra sin resolución registrada.',
  sources: [
    'src/modules/support/README.md',
    'src/modules/support/support.constants.ts',
    'src/modules/support/mobile-support.controller.ts',
    'src/modules/support/merchant-support.controller.ts',
    'src/modules/support/support-chat.controller.ts',
    'src/modules/support/support-attachments.controller.ts',
    'src/modules/support/internal-support.controller.ts',
    'src/modules/support/internal-support-desk.controller.ts',
    'src/modules/support/internal-support-catalog.controller.ts',
    'src/modules/support/support-knowledge-admin.controller.ts',
    'src/modules/support/application/support-sla.service.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts (sweep_support_sla)',
    'src/database/models/support-cases.model.ts',
    'memoria atlas-soporte-reason-codes',
    '_auditoria-soporte-reason-codes-2026-09-04/HALLAZGOS.md',
    'AtlasAdminPortal/src/features/support/services.ts',
    'AtlasERPFrontend/components/screens/MerchantSupportScreen.tsx',
    'AtlasFrontend/apps/consumer-app/app/(app)/soporte/index.tsx',
  ],
  metadata: {
    gaps: [
      'La app abre un canal con categoría pero no llama POST /mobile/support/cases: el caso con motivo sólo nace desde el portal de comercio.',
      'La base de conocimiento (admin/support/knowledge/*) no tiene pantalla en el portal admin.',
      'GET internal/support/desk/channels/:channelId/integrity, POST internal/support/cases/:caseId/links y POST internal/support/desk/sla/sweep no tienen llamador.',
      'GET mobile/support/knowledge/articles/:articleKey y POST support/channels/:channelId/messages/:messageId/corrections: ninguna app los llama.',
      'El inventario nombra estados en minúscula (open, assigned…); los reales son SUPPORT_CASE_STATUSES en mayúscula.',
    ],
  },
  stages: [
    {
      code: 'support_self_service',
      name: 'Autoayuda en la app',
      description:
        'El cliente abre «Soporte» en la app: ve las preguntas frecuentes, los motivos disponibles y busca en la base de conocimiento antes de escribir a nadie.',
      module: 'support',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      steps: [
        {
          code: 'support.mobile_faq',
          name: 'Ver las preguntas frecuentes',
          description: 'Artículos destacados para la audiencia del cliente; la audiencia la deriva el servidor del actor.',
          method: 'GET',
          path: '/mobile/support/faq',
          roles: MOBILE_ROLES,
        },
        {
          code: 'support.mobile_categories',
          name: 'Listar los motivos de contacto',
          description: 'Categorías del catálogo con las que el cliente puede abrir su pedido. Sin siembra la lista viene vacía.',
          method: 'GET',
          path: '/mobile/support/categories',
          roles: MOBILE_ROLES,
        },
        {
          code: 'support.mobile_knowledge_search',
          name: 'Buscar en la base de conocimiento',
          description: 'Búsqueda de texto sobre los artículos publicados para el cliente.',
          method: 'GET',
          path: '/mobile/support/knowledge/search',
          roles: MOBILE_ROLES,
          optional: true,
          repeatable: true,
        },
        {
          code: 'support.mobile_knowledge_article',
          name: 'Leer un artículo por su clave',
          description: 'Existe en el servidor pero la app no lo llama (categoría E del triaje de cableado).',
          method: 'GET',
          path: '/mobile/support/knowledge/articles/:articleKey',
          roles: MOBILE_ROLES,
          optional: true,
        },
        {
          code: 'support.mobile_knowledge_feedback',
          name: 'Calificar si el artículo ayudó',
          description: 'El cliente dice si el artículo le sirvió; alimenta la calidad de la base de conocimiento.',
          method: 'POST',
          path: '/mobile/support/knowledge/articles/:articleId/feedback',
          roles: MOBILE_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'support_customer_contact',
      name: 'El cliente escribe a soporte',
      description:
        'Si la autoayuda no alcanza, la app abre un canal de chat (con categoría si el cliente eligió motivo), envía mensajes y adjuntos. El caso formal (POST /mobile/support/cases) existe pero la app no lo llama.',
      module: 'support',
      actor: 'customer',
      client: 'CONSUMER_APP',
      resultingStates: ['NEW'],
      steps: [
        {
          code: 'support.channel_open',
          name: 'Abrir el canal de chat',
          description: 'Crea o reutiliza el canal del cliente y lo encola para un agente disponible.',
          method: 'POST',
          path: '/support/channels',
          roles: CHAT_ROLES,
          input: { categoryCode: 'string?', caseId: 'string?' },
          output: { channelId: 'string', status: 'string', reused: 'boolean', agentsAvailable: 'number | null' },
          events: ['support.channel.opened'],
        },
        {
          code: 'support.case_open_mobile',
          name: 'Abrir un caso con motivo desde la app',
          description:
            'Crea el expediente con categoría y arranca sus relojes de plazo. El cliente HTTP de la app lo declara pero ninguna pantalla lo usa.',
          method: 'POST',
          path: '/mobile/support/cases',
          roles: MOBILE_ROLES,
          optional: true,
          idempotencyKey: true,
          resultingStates: ['NEW'],
          errors: ['404 SUPPORT_CATEGORY_NOT_FOUND'],
          events: ['support.case.created', 'support.complaint.created', 'support.security.escalated'],
        },
        {
          code: 'support.customer_message',
          name: 'Enviar un mensaje',
          description: 'Mensaje encadenado por hash; reintentar con el mismo clientMessageId no duplica.',
          method: 'POST',
          path: '/support/channels/:channelId/messages',
          roles: CHAT_ROLES,
          repeatable: true,
          events: ['support.message.created'],
        },
        {
          code: 'support.customer_attachment',
          name: 'Adjuntar una imagen',
          description: 'Pide un permiso de subida para adjuntar un archivo al canal.',
          method: 'POST',
          path: '/support/channels/:channelId/attachments/ticket',
          roles: CHAT_ROLES,
          optional: true,
          repeatable: true,
        },
        {
          code: 'support.customer_channel_close',
          name: 'Terminar la conversación',
          description: 'Cierra el canal (USER_ENDED). No cierra el caso: el expediente sobrevive al chat.',
          method: 'POST',
          path: '/support/channels/:channelId/close',
          roles: CHAT_ROLES,
          optional: true,
          events: ['support.channel.closed'],
        },
      ],
    },
    {
      code: 'support_merchant_contact',
      name: 'El comercio pide ayuda',
      description:
        'El usuario del comercio abre un caso con motivo o un chat desde el portal de comercio; el ERP lo reenvía a Atlas por su pasarela de soporte.',
      module: 'partner-onboarding-gateway',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/soporte',
      optional: true,
      resultingStates: ['NEW'],
      steps: [
        {
          code: 'support.merchant_categories',
          name: 'Listar los motivos del comercio',
          description: 'Motivos por los que este comercio puede abrir un caso.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant/support/categories',
        },
        {
          code: 'support.merchant_case_open',
          name: 'Abrir un caso con motivo',
          description: 'Crea el caso del comercio en Atlas con su categoría; es la única vía que hoy abre casos con motivo.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/merchant/support/cases',
          resultingStates: ['NEW'],
          errors: ['404 SUPPORT_CATEGORY_NOT_FOUND'],
        },
        {
          code: 'support.merchant_channel_open',
          name: 'Abrir el chat del comercio',
          description: 'Canal de conversación del comercio, opcionalmente atado al caso.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/support/channels',
          optional: true,
        },
        {
          code: 'support.merchant_message',
          name: 'Enviar un mensaje del comercio',
          description: 'Mensaje del comercio en el canal abierto.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/support/channels/:channelId/messages',
          optional: true,
          repeatable: true,
        },
      ],
    },
    {
      code: 'support_desk_intake',
      name: 'La mesa recibe el trabajo',
      description:
        'El agente se marca disponible, ve la cola de canales y casos y toma una conversación. Exige perfil de agente, también para supervisores.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/support',
      roles: DESK_ROLES,
      steps: [
        {
          code: 'support.desk_presence',
          name: 'Marcar disponibilidad',
          description: 'El agente declara su presencia para recibir canales.',
          method: 'POST',
          path: '/internal/support/desk/presence',
          roles: DESK_ROLES,
          errors: ['403 SUPPORT_AGENT_PROFILE_REQUIRED'],
        },
        {
          code: 'support.desk_queue',
          name: 'Ver la cola de trabajo',
          description: 'Canales en espera y casos asignados al agente.',
          method: 'GET',
          path: '/internal/support/desk/queue',
          roles: DESK_ROLES,
          errors: ['403 SUPPORT_AGENT_PROFILE_REQUIRED'],
        },
        {
          code: 'support.desk_cases_list',
          name: 'Listar casos',
          description: 'Lista de casos con filtros para la mesa.',
          method: 'GET',
          path: '/internal/support/cases',
          roles: DESK_ROLES,
        },
        {
          code: 'support.desk_channel_claim',
          name: 'Tomar un canal',
          description: 'El agente se asigna la conversación en espera.',
          method: 'POST',
          path: '/internal/support/desk/channels/:channelId/claim',
          roles: DESK_ROLES,
        },
      ],
    },
    {
      code: 'support_case_handling',
      name: 'Atención del caso',
      description:
        'En la ficha del caso el agente lo clasifica, se lo asigna o lo transfiere, deja notas internas, responde en el chat y escala si hace falta.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/support/cases/[caseId]',
      roles: DESK_ROLES,
      requiredStates: ['NEW', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'REOPENED'],
      resultingStates: ['TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'ESCALATED'],
      steps: [
        {
          code: 'support.case_detail',
          name: 'Abrir la ficha del caso',
          description: 'Lectura auditada del expediente.',
          method: 'GET',
          path: '/internal/support/cases/:caseId',
          roles: DESK_ROLES,
        },
        {
          code: 'support.case_timeline',
          name: 'Ver la historia del caso',
          description: 'Eventos encadenados del expediente, en orden.',
          method: 'GET',
          path: '/internal/support/cases/:caseId/timeline',
          roles: DESK_ROLES,
        },
        {
          code: 'support.case_categories',
          name: 'Consultar el catálogo de motivos y colas',
          description: 'Categorías para clasificar el caso; sin catálogo sembrado la lista viene vacía.',
          method: 'GET',
          path: '/internal/support/categories',
          roles: DESK_ROLES,
        },
        {
          code: 'support.case_queues',
          name: 'Consultar las colas',
          description: 'Colas a las que se puede transferir un caso.',
          method: 'GET',
          path: '/internal/support/queues',
          roles: DESK_ROLES,
          optional: true,
        },
        {
          code: 'support.case_triage',
          name: 'Clasificar el caso',
          description: 'Fija tipo, prioridad y categoría. Escribe CASE_TRIAGED en la historia; no publica evento de dominio.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/triage',
          roles: DESK_ROLES,
          requiredStates: ['NEW', 'REOPENED'],
          resultingStates: ['TRIAGED'],
        },
        {
          code: 'support.case_claim',
          name: 'Asignarse el caso',
          description: 'Un agente sólo puede asignarse a sí mismo; asignar a otro es de supervisores.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/claim',
          roles: DESK_ROLES,
          resultingStates: ['ASSIGNED'],
          events: ['support.case.assigned'],
        },
        {
          code: 'support.case_transfer',
          name: 'Transferir el caso',
          description: 'Pasa el caso a otro agente o cola con un resumen.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/transfer',
          roles: DESK_ROLES,
          optional: true,
        },
        {
          code: 'support.case_note',
          name: 'Dejar una nota interna',
          description: 'Nota que el cliente no ve.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/notes',
          roles: DESK_ROLES,
          optional: true,
          repeatable: true,
        },
        {
          code: 'support.case_link',
          name: 'Enlazar el caso con otro objeto',
          description: 'Relaciona el caso con otro caso o entidad. Ninguna pantalla lo llama (categoría D del triaje).',
          method: 'POST',
          path: '/internal/support/cases/:caseId/links',
          roles: DESK_ROLES,
          optional: true,
        },
        {
          code: 'support.agent_message',
          name: 'Responder en el chat',
          description: 'El agente escribe al cliente o al comercio en el canal del caso.',
          method: 'POST',
          path: '/support/channels/:channelId/messages',
          roles: CHAT_ROLES,
          repeatable: true,
          events: ['support.message.created'],
        },
        {
          code: 'support.case_escalate',
          name: 'Escalar el caso',
          description: 'Sube el caso de nivel; si es de seguridad publica el evento de seguridad en lugar del genérico.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/escalate',
          roles: DESK_ROLES,
          optional: true,
          resultingStates: ['ESCALATED'],
          events: ['support.case.escalated', 'support.security.escalated'],
        },
      ],
    },
    {
      code: 'support_sla_watch',
      name: 'Vigilancia de plazos',
      description:
        'Cada intervalo el sistema recorre los relojes de plazo: primero avisa de los que están por vencer (SLA_WARNING en la historia) y después marca los vencidos y publica support.sla.breached.',
      module: 'runtime-jobs',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'support.sla_sweep_job',
          name: 'Barrido programado de plazos',
          description: 'Job sweep_support_sla: sweepWarnings y luego sweepBreaches por tenant.',
          kind: 'job',
          job: 'sweep_support_sla',
          repeatable: true,
          events: ['support.sla.breached'],
        },
      ],
    },
    {
      code: 'support_sla_manual_sweep',
      name: 'Barrido de plazos a mano',
      description: 'Un administrador puede forzar el barrido de vencidos. Ninguna pantalla del portal lo ofrece.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      optional: true,
      roles: SUPERVISOR_ROLES,
      steps: [
        {
          code: 'support.sla_sweep_manual',
          name: 'Forzar el barrido de vencidos',
          description: 'Mismo barrido de incumplimientos que el job, a demanda.',
          method: 'POST',
          path: '/internal/support/desk/sla/sweep',
          roles: SUPERVISOR_ROLES,
          optional: true,
          events: ['support.sla.breached'],
        },
      ],
    },
    {
      code: 'support_resolution',
      name: 'Resolución y cierre',
      description:
        'El agente resuelve con código de resolución y causa raíz elegidos del catálogo, y luego cierra el caso. Los casos de seguridad, fraude, reclamo formal o privacidad no se cierran solos.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/support/cases/[caseId]',
      roles: DESK_ROLES,
      resultingStates: ['RESOLVED', 'CLOSED'],
      steps: [
        {
          code: 'support.resolution_codes',
          name: 'Consultar códigos de resolución y causa raíz',
          description: 'Catálogo de los 19 códigos de resolución y 13 de causa raíz para los selectores.',
          method: 'GET',
          path: '/internal/support/codes',
          roles: DESK_ROLES,
        },
        {
          code: 'support.case_resolve',
          name: 'Resolver el caso',
          description: 'Único sitio que escribe resolution_code y root_cause_code; avisa al cliente.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/resolve',
          roles: DESK_ROLES,
          requiredStates: ['IN_PROGRESS', 'WAITING_CUSTOMER', 'WAITING_INTERNAL', 'WAITING_PARTNER', 'ESCALATED'],
          resultingStates: ['RESOLVED'],
          input: { resolutionCode: 'SupportResolutionCode', rootCauseCode: 'SupportRootCauseCode' },
          events: ['support.case.resolved'],
        },
        {
          code: 'support.case_close',
          name: 'Cerrar el caso',
          description: 'Cierra el expediente; desde CLOSED sólo se puede reabrir.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/close',
          roles: DESK_ROLES,
          requiredStates: ['RESOLVED', 'WAITING_CUSTOMER', 'DUPLICATE'],
          resultingStates: ['CLOSED'],
          events: ['support.case.closed'],
        },
      ],
    },
    {
      code: 'support_customer_followup',
      name: 'El cliente cierra el ciclo',
      description:
        'Desde el detalle del caso en la app el cliente pide el cierre, califica la atención o reabre si el problema volvió. El comercio tiene los equivalentes en su portal.',
      module: 'support',
      actor: 'customer',
      client: 'CONSUMER_APP',
      terminal: true,
      steps: [
        {
          code: 'support.mobile_cases',
          name: 'Ver mis casos',
          description: 'Lista de casos del cliente con el estado traducido a lenguaje del cliente.',
          method: 'GET',
          path: '/mobile/support/cases',
          roles: MOBILE_ROLES,
        },
        {
          code: 'support.mobile_case_detail',
          name: 'Ver el detalle de un caso',
          description: 'Detalle del caso propio.',
          method: 'GET',
          path: '/mobile/support/cases/:caseId',
          roles: MOBILE_ROLES,
        },
        {
          code: 'support.mobile_close_request',
          name: 'Pedir el cierre',
          description: 'Registra la petición del cliente; el cierre lo hace el agente.',
          method: 'POST',
          path: '/mobile/support/cases/:caseId/close-request',
          roles: MOBILE_ROLES,
          optional: true,
        },
        {
          code: 'support.mobile_feedback',
          name: 'Calificar la atención',
          description: 'Encuesta de satisfacción tras la resolución.',
          method: 'POST',
          path: '/mobile/support/cases/:caseId/feedback',
          roles: MOBILE_ROLES,
          optional: true,
        },
        {
          code: 'support.mobile_reopen',
          name: 'Reabrir el caso',
          description: 'Reabre sin borrar el cierre anterior: incrementa el contador y deja evento.',
          method: 'POST',
          path: '/mobile/support/cases/:caseId/reopen',
          roles: MOBILE_ROLES,
          optional: true,
          requiredStates: ['RESOLVED', 'CLOSED', 'DUPLICATE', 'CANCELLED'],
          resultingStates: ['REOPENED'],
          events: ['support.case.reopened'],
        },
        {
          code: 'support.merchant_feedback',
          name: 'Calificar la atención (comercio)',
          description: 'Equivalente del comercio desde su portal.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/merchant/support/cases/:caseId/feedback',
          optional: true,
        },
      ],
    },
    {
      code: 'support_agent_admin',
      name: 'Alta de agentes de la mesa',
      description: 'Un administrador crea, lista y retira perfiles de agente; sin perfil nadie opera la mesa.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/support/agents',
      optional: true,
      roles: SUPERVISOR_ROLES,
      steps: [
        {
          code: 'support.agents_list',
          name: 'Listar agentes',
          description: 'Perfiles de agente con su capacidad.',
          method: 'GET',
          path: '/internal/support/desk/agents',
          roles: SUPERVISOR_ROLES,
        },
        {
          code: 'support.agents_create',
          name: 'Dar de alta un agente',
          description: 'Crea el perfil que exige la mesa, también para supervisores.',
          method: 'POST',
          path: '/internal/support/desk/agents',
          roles: SUPERVISOR_ROLES,
        },
        {
          code: 'support.agents_remove',
          name: 'Retirar un agente',
          description: 'Da de baja el perfil de agente.',
          method: 'DELETE',
          path: '/internal/support/desk/agents/:agentProfileId',
          roles: SUPERVISOR_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'support_knowledge_admin',
      name: 'Gestión de la base de conocimiento',
      description:
        'Crear artículos, versionarlos, pasarlos a revisión, aprobarlos y publicarlos. Hoy no hay pantalla en el portal admin: sólo por API.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      optional: true,
      roles: KNOWLEDGE_ROLES,
      steps: [
        {
          code: 'support.knowledge_article_create',
          name: 'Crear un artículo',
          description: 'Alta del artículo con su clave y audiencia.',
          method: 'POST',
          path: '/admin/support/knowledge/articles',
          roles: KNOWLEDGE_ROLES,
        },
        {
          code: 'support.knowledge_version_create',
          name: 'Redactar una versión',
          description: 'Nueva versión del contenido del artículo.',
          method: 'POST',
          path: '/admin/support/knowledge/articles/:articleId/versions',
          roles: KNOWLEDGE_ROLES,
        },
        {
          code: 'support.knowledge_submit_review',
          name: 'Enviar a revisión',
          description: 'La versión pasa a revisión.',
          method: 'POST',
          path: '/admin/support/knowledge/versions/:versionId/submit-review',
          roles: KNOWLEDGE_ROLES,
        },
        {
          code: 'support.knowledge_approve',
          name: 'Aprobar la versión',
          description: 'Aprobación de la versión revisada.',
          method: 'POST',
          path: '/admin/support/knowledge/versions/:versionId/approve',
          roles: KNOWLEDGE_ROLES,
        },
        {
          code: 'support.knowledge_publish',
          name: 'Publicar la versión',
          description: 'La versión aprobada queda visible para su audiencia.',
          method: 'POST',
          path: '/admin/support/knowledge/versions/:versionId/publish',
          roles: KNOWLEDGE_ROLES,
          events: ['support.knowledge.published'],
        },
      ],
    },
    {
      code: 'support_integrity_check',
      name: 'Verificación de la transcripción',
      description:
        'Recalcula la cadena de hashes de un canal y dice en qué posición dejó de cuadrar; un resultado inválido es un incidente de seguridad. Ninguna pantalla lo llama.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      optional: true,
      roles: DESK_ROLES,
      steps: [
        {
          code: 'support.channel_integrity',
          name: 'Verificar la integridad del canal',
          description: 'Comprueba que nadie alteró la transcripción sorteando los triggers.',
          method: 'GET',
          path: '/internal/support/desk/channels/:channelId/integrity',
          roles: DESK_ROLES,
          optional: true,
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'support.entry',
      from: null,
      to: 'support.mobile_faq',
      condition: 'always',
      description: 'Entrada: el cliente abre Soporte en la app.',
      isDefault: true,
    },
    {
      code: 'support.faq_to_channel',
      from: 'support.mobile_categories',
      to: 'support.channel_open',
      condition: 'on_success',
      description: 'La autoayuda no alcanzó: abre el chat.',
      isDefault: true,
    },
    {
      code: 'support.merchant_entry',
      from: null,
      to: 'support.merchant_case_open',
      condition: 'conditional',
      expression: { origin: 'merchant' },
      description: 'Entrada del comercio desde su portal.',
    },
    {
      code: 'support.channel_to_claim',
      from: 'support.channel_open',
      to: 'support.desk_channel_claim',
      condition: 'on_success',
      description: 'Un agente toma la conversación encolada.',
      isDefault: true,
    },
    {
      code: 'support.claim_to_case',
      from: 'support.desk_channel_claim',
      to: 'support.case_detail',
      condition: 'on_success',
      description: 'El agente trabaja el caso en su ficha.',
      isDefault: true,
    },
    {
      code: 'support.triage_to_assign',
      from: 'support.case_triage',
      to: 'support.case_claim',
      condition: 'on_success',
      description: 'Clasificado, el agente se lo asigna.',
      isDefault: true,
    },
    {
      code: 'support.claim_to_resolve',
      from: 'support.case_claim',
      to: 'support.case_resolve',
      condition: 'on_success',
      description: 'Atendido, se resuelve con código.',
      isDefault: true,
    },
    {
      code: 'support.claim_to_escalate',
      from: 'support.case_claim',
      to: 'support.case_escalate',
      condition: 'conditional',
      expression: { needsEscalation: true },
      description: 'Supera al agente: se escala.',
    },
    {
      code: 'support.escalate_to_resolve',
      from: 'support.case_escalate',
      to: 'support.case_resolve',
      condition: 'on_success',
      description: 'Tras el escalado, se resuelve.',
    },
    {
      code: 'support.resolve_to_close',
      from: 'support.case_resolve',
      to: 'support.case_close',
      condition: 'on_success',
      description: 'Resuelto, se cierra el expediente.',
      isDefault: true,
    },
    {
      code: 'support.close_to_feedback',
      from: 'support.case_close',
      to: 'support.mobile_feedback',
      condition: 'on_success',
      description: 'El cliente califica la atención.',
      isDefault: true,
    },
    {
      code: 'support.close_to_reopen',
      from: 'support.case_close',
      to: 'support.mobile_reopen',
      condition: 'conditional',
      expression: { problemReturned: true },
      description: 'El problema volvió: el cliente reabre.',
    },
    {
      code: 'support.reopen_to_triage',
      from: 'support.mobile_reopen',
      to: 'support.case_triage',
      condition: 'on_success',
      description: 'El caso reabierto vuelve a la mesa.',
    },
    {
      code: 'support.exit',
      from: 'support.mobile_feedback',
      to: null,
      condition: 'always',
      description: 'Salida: caso cerrado y calificado.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'support.desk_queue',
      dependsOn: 'support.agents_create',
      type: 'requires_data',
      description: 'Sin perfil de agente la mesa responde 403 SUPPORT_AGENT_PROFILE_REQUIRED.',
    },
    {
      step: 'support.case_resolve',
      dependsOn: 'support.resolution_codes',
      type: 'requires_data',
      description: 'El código de resolución y la causa raíz se eligen del catálogo.',
    },
    {
      step: 'support.case_close',
      dependsOn: 'support.case_resolve',
      type: 'requires_completion',
      description: 'Un caso no se cierra sin resolución registrada (salvo duplicado o espera del cliente).',
    },
    {
      step: 'support.merchant_case_open',
      dependsOn: 'support.merchant_categories',
      type: 'requires_data',
      description: 'Sin categoría sembrada la apertura falla con SUPPORT_CATEGORY_NOT_FOUND.',
    },
    {
      step: 'support.mobile_knowledge_search',
      dependsOn: 'support.knowledge_publish',
      type: 'soft',
      description: 'Sólo se encuentran artículos publicados.',
    },
  ],
};
