/**
 * @file Proceso declarado en código: Recorrido estándar del cliente hasta la decisión de crédito.
 * @business Es el recorrido estándar por el que una persona pasa de no conocer Atlas a tener una línea de crédito utilizable: une en un solo árbol el alta, la captura de datos, la revisión, la habilitación y la solicitud de crédito.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; portada de la siembra demo el 2026-09-26 sin perder pasos, transiciones ni dependencias.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const CUSTOMER_CREDIT_JOURNEY: WorkflowDefinitionFixture = {
  processId: 'C-01',
  code: 'customer_credit_journey',
  version: 'v1',
  name: 'Recorrido estándar del cliente hasta la decisión de crédito',
  description:
    'Árbol real de endpoints del proceso de Atlas: registro, captura KYC, evidencia externa, envío a revisión, evaluación de riesgo, decisiones de operaciones, habilitación crediticia, solicitud y decisión final. Cada paso corresponde a un endpoint implementado.',
  processType: 'customer_journey',
  ownerDomain: 'customer_lifecycle',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Es el recorrido estándar por el que una persona pasa de no conocer Atlas a tener una línea de crédito utilizable: une en un solo árbol el alta, la captura de datos, la revisión, la habilitación y la solicitud de crédito.',
    whoStartsAndCloses:
      'Lo inicia el cliente desde la app al crear su cuenta; lo cierran el operador interno (revisión y habilitación desde el portal admin) y el Motor de decisiones, que aprueba o rechaza la solicitud de crédito.',
    startAndEnd:
      'Empieza con POST /customer-onboarding/start y termina cuando el cliente queda `active` con una línea de crédito vigente, o en un estado terminal (`rejected`, `blocked`, `closed`) con su motivo registrado.',
    whenItFails:
      'Cada etapa deja al cliente en un estado del ciclo de vida con bloqueadores explícitos (evaluación de habilitación). Una revisión manual o un rechazo queda en la cola de trabajo del portal y el cliente ve el motivo en la app.',
    healthIndicator:
      'Porcentaje de altas que llegan a `active` en 7 días y tiempo medio en `under_review`; ambos se leen de customers.lifecycle_status y de la cola de revisión manual.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'customer',
    table: 'customers',
    idColumn: '_id',
    statusColumn: 'lifecycle_status',
    labelColumn: 'customer_code',
    openStatuses: ['registered', 'onboarding_in_progress', 'under_review', 'observed'],
  },
  success: 'El recorrido termina bien cuando una solicitud del cliente queda aprobada.',
  failure: 'Rechazo de habilitación, bloqueo por fraude/cumplimiento o rechazo de la solicitud.',
  sources: ['src/database/seeders/demo/referencia.seed-data.ts'],
  stages: [
    {
      code: 'credit_catalog',
      name: 'Catálogo de productos crediticios',
      description:
        'Prerrequisito operativo del crédito: sin al menos un producto activo, ningún cliente habilitado puede solicitar nada. El catálogo es dato de negocio, no código.',
      module: 'credit',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      optional: true,
      roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      steps: [
        {
          code: 'ops.credit_products_list',
          name: 'Listar los productos del tenant',
          description: 'Catálogo completo para administración, incluidos borradores y retirados.',
          method: 'GET',
          path: '/operations/credit/products',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
        },
        {
          code: 'ops.credit_product_create',
          name: 'Crear un producto crediticio',
          description: 'Nace en `draft`: activarlo es una decisión aparte y auditable.',
          method: 'POST',
          path: '/operations/credit/products',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          errors: ['409 CREDIT_PRODUCT_CODE_ALREADY_EXISTS', '422 INVALID_PRODUCT_RANGES'],
          successStatus: [201],
        },
        {
          code: 'ops.credit_product_status',
          name: 'Cambiar el estado de un producto',
          description: 'Activar, suspender o retirar. Solo los activos son ofrecibles.',
          method: 'PATCH',
          path: '/operations/credit/products/:productId/status',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          errors: ['404 CREDIT_PRODUCT_NOT_FOUND', '422 INVALID_PRODUCT_STATUS_TRANSITION'],
        },
      ],
    },
    {
      code: 'registration',
      name: 'Registro y acceso',
      description:
        'Crea el cliente, sus credenciales y el flujo de onboarding, y obtiene el token con el que se recorre el resto del proceso.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      resultingStates: ['registered'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['NO_CREDENTIALS'],
      },
      steps: [
        {
          code: 'registration.consent_documents',
          name: 'Consultar los documentos legales vigentes',
          description:
            'Versión publicada y vigente de los textos que el cliente debe aceptar. Es público a propósito: se muestra antes de registrarse.',
          method: 'GET',
          path: '/consent-documents/active',
          auth: false,
          optional: true,
          repeatable: true,
          output: {
            documents: 'ConsentDocumentDto[]',
          },
        },
        {
          code: 'registration.start',
          name: 'Iniciar el onboarding',
          description: 'Crea cliente, credenciales y flujo de onboarding de forma idempotente. Punto de entrada del recorrido completo.',
          method: 'POST',
          path: '/customer-onboarding/start',
          auth: false,
          idempotencyKey: true,
          resultingStates: ['registered'],
          input: {
            channel: 'phone|email',
            password: 'string',
            identifier: 'string',
            deviceFingerprint: 'string?',
          },
          output: {
            customerId: 'string',
            onboardingFlowId: 'string',
          },
          errors: ['409 CUSTOMER_ALREADY_EXISTS', '422 INVALID_IDENTIFIER', '429 THROTTLED'],
          events: ['customer.registered'],
          successStatus: [201],
        },
        {
          code: 'registration.login',
          name: 'Autenticarse',
          description: 'Devuelve el access token con el que se autorizan todos los pasos siguientes.',
          method: 'POST',
          path: '/auth/login',
          auth: false,
          input: {
            password: 'string',
            identifier: 'string',
          },
          output: {
            accessToken: 'string',
            mfaRequired: 'boolean',
            refreshToken: 'string',
          },
          errors: ['401 INVALID_CREDENTIALS', '429 THROTTLED'],
          events: ['auth.login_succeeded', 'auth.login_failed'],
        },
        {
          code: 'registration.mfa',
          name: 'Completar el segundo factor',
          description: 'Solo si el login respondió `mfaRequired`. Canjea el desafío por un token de sesión completo.',
          method: 'POST',
          path: '/auth/mfa',
          optional: true,
          input: {
            code: 'string',
            challengeId: 'string',
          },
          errors: ['401 INVALID_MFA_CODE', '410 MFA_CHALLENGE_EXPIRED'],
        },
        {
          code: 'registration.login_pin',
          name: 'Autenticarse con PIN',
          description: 'Alternativa de acceso para clientes que configuraron PIN. Sustituye a `registration.login`, no lo complementa.',
          method: 'POST',
          path: '/auth/login/pin',
          auth: false,
          optional: true,
          errors: ['401 INVALID_PIN', '429 THROTTLED'],
        },
        {
          code: 'registration.me',
          name: 'Consultar el actor autenticado',
          description: 'Identidad y rol del token vigente. La app la usa para decidir qué recorrido mostrar.',
          method: 'GET',
          path: '/auth/me',
          optional: true,
          repeatable: true,
        },
        {
          code: 'registration.refresh',
          name: 'Renovar el token de acceso',
          description: 'Mantiene viva la sesión durante un recorrido largo sin obligar a volver a autenticarse.',
          method: 'POST',
          path: '/auth/refresh',
          auth: false,
          optional: true,
          repeatable: true,
          errors: ['401 INVALID_REFRESH_TOKEN', '401 TOKEN_REVOKED'],
        },
        {
          code: 'registration.logout',
          name: 'Cerrar la sesión de acceso',
          description: 'Revoca el refresh token. Es el cierre del recorrido de acceso, no del proceso de negocio.',
          method: 'POST',
          path: '/auth/logout',
          auth: false,
          optional: true,
          successStatus: [200, 204],
        },
      ],
    },
    {
      code: 'contact_verification',
      name: 'Verificación de contacto',
      description: 'Alta del método de contacto y verificación por código de un solo uso. Solo se almacena el hash del código.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      parent: 'data_capture',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      resultingStates: ['onboarding_in_progress'],
      completionRule: {
        type: 'onboarding_section',
        sectionCode: 'contact_verification',
      },
      steps: [
        {
          code: 'contact.add_method',
          name: 'Registrar un método de contacto',
          description: 'Teléfono o correo sobre el que se hará la verificación.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-methods',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          input: {
            value: 'string',
            isPrimary: 'boolean?',
            contactType: 'phone|email',
          },
          errors: ['409 CONTACT_ALREADY_REGISTERED', '422 INVALID_CONTACT_VALUE'],
          successStatus: [201],
        },
        {
          code: 'contact.request_code',
          name: 'Solicitar el código de verificación',
          description: 'Emite un código real por el canal configurado, con cooldown por destino.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-verification/request',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          errors: ['429 VERIFICATION_COOLDOWN_ACTIVE', '404 CONTACT_METHOD_NOT_FOUND'],
          events: ['contact.verification_requested'],
          successStatus: [202, 200],
        },
        {
          code: 'contact.submit_code',
          name: 'Enviar el código recibido',
          description: 'Valida TTL, número de intentos y consumo único. No existe código de bypass.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/contact-verification/submit',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          resultingStates: ['onboarding_in_progress'],
          input: {
            code: 'string',
            contactMethodId: 'string',
          },
          errors: ['410 VERIFICATION_CODE_EXPIRED', '422 INVALID_VERIFICATION_CODE', '429 TOO_MANY_ATTEMPTS'],
          events: ['contact.verified'],
        },
      ],
    },
    {
      code: 'identity_decision',
      name: 'Decisión de identidad',
      description: 'Un analista acepta o rechaza la verificación de identidad y su evidencia.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      parent: 'back_office_review',
      roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
      requiredStates: ['under_review', 'observed'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['IDENTITY_NOT_VERIFIED', 'EVIDENCE_PENDING_REVIEW'],
      },
      steps: [
        {
          code: 'ops.identity_decision',
          name: 'Decidir la verificación de identidad',
          description: 'Registra la decisión y su motivo; el resultado alimenta la regla de habilitación.',
          method: 'POST',
          path: '/operations/customers/:customerId/identity-verification/decision',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          requiredStates: ['under_review', 'observed'],
          errors: ['404 CUSTOMER_NOT_FOUND', '422 INVALID_DECISION'],
          events: ['customer.identity_decision_recorded'],
        },
      ],
    },
    {
      code: 'session_bootstrap',
      name: 'Sesión y telemetría',
      description:
        'Abre la sesión observada y alimenta las señales anti-fraude. Es opcional para completar el trámite, pero su ausencia empobrece la evaluación de riesgo.',
      module: 'sessions',
      actor: 'customer',
      client: 'CONSUMER_APP',
      optional: true,
      roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin', 'system'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed', 'active'],
      steps: [
        {
          code: 'session.start',
          name: 'Abrir sesión',
          description: 'Registra dispositivo, GPS y contexto de la sesión del cliente.',
          method: 'POST',
          path: '/customers/:customerId/sessions/start',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed', 'active'],
          output: {
            sessionId: 'string',
          },
          events: ['session.started'],
          successStatus: [201],
        },
        {
          code: 'session.heartbeat',
          name: 'Mantener viva la sesión',
          description: 'Latido periódico con la posición y el estado del dispositivo.',
          method: 'POST',
          path: '/customers/:customerId/sessions/:sessionId/heartbeat',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          repeatable: true,
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed', 'active'],
        },
        {
          code: 'session.telemetry',
          name: 'Enviar telemetría de comportamiento',
          description: 'Lote validado y acotado de señales de interacción y dispositivo.',
          method: 'POST',
          path: '/customers/:customerId/telemetry/batch',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed', 'active'],
          successStatus: [202, 200],
        },
        {
          code: 'session.state',
          name: 'Consultar el estado de la sesión',
          description: 'Sesión vigente del cliente, si la hay.',
          method: 'GET',
          path: '/customers/:customerId/session-state',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed', 'active'],
        },
        {
          code: 'session.end',
          name: 'Cerrar sesión',
          description: 'Cierre explícito. Sin él, la sesión caduca por el job de expiración.',
          method: 'POST',
          path: '/customers/:customerId/sessions/:sessionId/end',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed', 'active'],
          events: ['session.ended'],
        },
      ],
    },
    {
      code: 'personal_data',
      name: 'Datos personales',
      description: 'Nombre, apellido y fecha de nacimiento. La edad se valida contra el rango operable.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      parent: 'data_capture',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: {
        type: 'onboarding_section',
        sectionCode: 'personal_data',
      },
      steps: [
        {
          code: 'profile.update',
          name: 'Guardar el perfil personal',
          description: 'Autoguardado parcial: valida formato, no obligatoriedad. La completitud se exige al enviar el paquete.',
          method: 'PATCH',
          path: '/customer-onboarding/:customerId/profile',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          input: {
            lastName: 'string?',
            birthDate: 'YYYY-MM-DD?',
            firstName: 'string?',
          },
          errors: ['422 INVALID_BIRTH_DATE'],
        },
      ],
    },
    {
      code: 'compliance_screening',
      name: 'Cribado de cumplimiento',
      description: 'Contraste contra listas de vigilancia y resolución de coincidencias.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      parent: 'back_office_review',
      roles: ['compliance_analyst', 'risk_analyst', 'admin', 'platform_admin', 'system'],
      requiredStates: ['under_review', 'observed'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['COMPLIANCE_MATCH_PENDING'],
      },
      steps: [
        {
          code: 'ops.compliance_screening',
          name: 'Ejecutar el cribado',
          description: 'Genera coincidencias contra listas; cada coincidencia bloquea la habilitación hasta resolverse.',
          method: 'POST',
          path: '/operations/customers/:customerId/compliance/screening',
          roles: ['compliance_analyst', 'risk_analyst', 'admin', 'platform_admin', 'system'],
          requiredStates: ['under_review', 'observed'],
          events: ['compliance.screening_completed'],
          successStatus: [200, 201],
        },
        {
          code: 'ops.compliance_clear',
          name: 'Resolver las coincidencias',
          description: 'Un analista de cumplimiento descarta o confirma cada coincidencia, con motivo registrado.',
          method: 'POST',
          path: '/operations/customers/:customerId/compliance/clear-matches',
          roles: ['compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          requiredStates: ['under_review', 'observed'],
          events: ['compliance.matches_cleared'],
        },
      ],
    },
    {
      code: 'data_capture',
      name: 'Captura de datos y evidencia (KYC)',
      description:
        'Las seis secciones obligatorias del onboarding más los consentimientos. Cada subetapa se da por cerrada con la MISMA regla que decide la habilitación crediticia.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      resultingStates: ['onboarding_in_progress'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: [
          'CONTACT_NOT_VERIFIED',
          'PROFILE_INCOMPLETE',
          'FINANCIAL_PROFILE_INCOMPLETE',
          'ADDRESS_MISSING',
          'IDENTITY_DOCUMENT_MISSING',
          'IDENTITY_DOCUMENT_EXPIRED',
          'REFERENCES_INSUFFICIENT',
          'CONSENT_MISSING',
        ],
      },
      steps: [
        {
          code: 'onboarding.status',
          name: 'Consultar el avance del onboarding',
          description: 'Secciones, porcentaje, `canSubmit`, `nextStep` y bloqueadores. Es el punto de reanudación del proceso.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/status',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          output: {
            blockers: 'EligibilityBlocker[]',
            nextStep: 'string',
            sections: 'OnboardingSection[]',
          },
        },
      ],
    },
    {
      code: 'financial_profile',
      name: 'Perfil económico',
      description: 'Los seis atributos económicos obligatorios, persistidos en el modelo EAV versionado de atributos del cliente.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      parent: 'data_capture',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: {
        type: 'onboarding_section',
        sectionCode: 'financial_profile',
      },
      steps: [
        {
          code: 'financial.update',
          name: 'Guardar el perfil económico',
          description: 'Situación laboral, antigüedad, ingresos, egresos, actividad económica y origen de fondos.',
          method: 'PUT',
          path: '/customer-onboarding/:customerId/financial-profile',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          input: {
            sourceOfFunds: 'enum',
            employmentStatus: 'enum',
            economicActivityCode: 'string',
            monthlyIncomeDeclared: 'number',
            monthlyExpensesDeclared: 'number',
            employmentSeniorityMonths: 'number',
          },
          errors: ['422 ATTRIBUTE_CATALOG_NOT_SEEDED', '422 INVALID_ATTRIBUTE_VALUE'],
        },
      ],
    },
    {
      code: 'manual_review',
      name: 'Revisión manual',
      description: 'Casos abiertos por reglas o por observaciones de calidad de datos.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      parent: 'back_office_review',
      optional: true,
      roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
      requiredStates: ['under_review', 'observed'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['OPEN_OBSERVATIONS'],
      },
      steps: [
        {
          code: 'ops.manual_cases',
          name: 'Listar casos de revisión manual',
          description: 'Casos abiertos con su prioridad y motivo.',
          method: 'GET',
          path: '/operations/manual-review-cases',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['under_review', 'observed'],
        },
        {
          code: 'ops.manual_decision',
          name: 'Decidir un caso de revisión manual',
          description: 'Aprobar, rechazar o pedir más información. Pedir información deja al cliente en `observed`.',
          method: 'POST',
          path: '/operations/manual-review-cases/:caseId/decision',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['under_review', 'observed'],
          resultingStates: ['observed', 'under_review'],
          events: ['manual_review.case_decided'],
        },
      ],
    },
    {
      code: 'address',
      name: 'Domicilio',
      description: 'Dirección declarada con su observación GPS asociada.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      parent: 'data_capture',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: {
        type: 'onboarding_section',
        sectionCode: 'address',
      },
      steps: [
        {
          code: 'address.package',
          name: 'Registrar el domicilio',
          description: 'Alta o reemplazo de la dirección vigente, versionada, con la evidencia de geolocalización.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/address-package',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          errors: ['422 INVALID_ADDRESS_PACKAGE'],
          events: ['customer.address_registered'],
          successStatus: [201, 200],
        },
      ],
    },
    {
      code: 'external_evidence',
      name: 'Evidencia externa',
      description:
        'Consulta controlada a proveedores externos (identidad, buró, telco, huella digital) con consentimiento, costo y resiliencia. Enriquece la decisión sin ser obligatoria para completar el trámite.',
      module: 'external_data',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin', 'system'],
      requiredStates: ['onboarding_in_progress', 'under_review', 'observed'],
      steps: [
        {
          code: 'external.consent',
          name: 'Registrar el consentimiento de consulta externa',
          description: 'Sin consentimiento vigente, la ejecución de la consulta se rechaza.',
          method: 'POST',
          path: '/external-data/consents',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          requiredStates: ['onboarding_in_progress', 'under_review', 'observed'],
          events: ['external_data.consent_granted'],
          successStatus: [201],
        },
        {
          code: 'external.preview',
          name: 'Previsualizar costo y elegibilidad de la consulta',
          description: 'Devuelve costo estimado, política aplicable y si la consulta puede ejecutarse, sin ejecutarla.',
          method: 'POST',
          path: '/external-data/requests/preview',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          requiredStates: ['onboarding_in_progress', 'under_review', 'observed'],
        },
        {
          code: 'external.request',
          name: 'Ejecutar la consulta externa',
          description: 'Ejecuta contra el proveedor con caché, circuit breaker y auditoría de la respuesta.',
          method: 'POST',
          path: '/external-data/requests',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          idempotencyKey: true,
          requiredStates: ['onboarding_in_progress', 'under_review', 'observed'],
          errors: ['403 EXTERNAL_DATA_CONSENT_MISSING', '503 PROVIDER_UNAVAILABLE', '429 PROVIDER_RATE_LIMITED'],
          events: ['external_data.request_completed'],
          successStatus: [200, 202],
        },
        {
          code: 'external.features',
          name: 'Consultar las variables derivadas',
          description: 'Variables construidas a partir de las respuestas externas, listas para el motor de riesgo.',
          method: 'GET',
          path: '/external-data/users/:customerId/features',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          repeatable: true,
          requiredStates: ['onboarding_in_progress', 'under_review', 'observed'],
        },
      ],
    },
    {
      code: 'fraud_review',
      name: 'Revisión de fraude',
      description: 'Casos de fraude abiertos. Un caso abierto bloquea la habilitación mientras dure.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      parent: 'back_office_review',
      optional: true,
      roles: ['fraud_analyst', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
      requiredStates: ['under_review', 'observed', 'active'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['FRAUD_CASE_OPEN'],
      },
      steps: [
        {
          code: 'ops.fraud_cases',
          name: 'Listar casos de fraude',
          description: 'Casos de fraude con su estado y prioridad.',
          method: 'GET',
          path: '/operations/fraud-cases',
          roles: ['fraud_analyst', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['under_review', 'observed', 'active'],
        },
        {
          code: 'ops.fraud_decision',
          name: 'Decidir un caso de fraude',
          description: 'Confirma o descarta el fraude; confirmar bloquea al cliente.',
          method: 'POST',
          path: '/operations/fraud-cases/:caseId/decision',
          roles: ['fraud_analyst', 'admin', 'platform_admin'],
          optional: true,
          idempotencyKey: true,
          requiredStates: ['under_review', 'observed', 'active'],
          resultingStates: ['blocked', 'under_review'],
          events: ['fraud.case_decided'],
        },
      ],
    },
    {
      code: 'identity_documents',
      name: 'Documentos de identidad',
      description: 'Carga del documento y verificación de identidad contra el proveedor configurado.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      parent: 'data_capture',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: {
        type: 'onboarding_section',
        sectionCode: 'identity_documents',
      },
      steps: [
        {
          code: 'identity.upload_url',
          name: 'Obtener URL firmada de carga',
          description: 'URL temporal para subir el archivo al almacenamiento sin que pase por el backend.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/documents/upload-url',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          output: {
            expiresAt: 'ISO-8601',
            objectKey: 'string',
            uploadUrl: 'string',
          },
          successStatus: [201, 200],
        },
        {
          code: 'identity.package',
          name: 'Registrar el documento de identidad',
          description: 'Tipo, número, vigencia y referencia a la evidencia cargada.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-package',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          errors: ['409 IDENTITY_DOCUMENT_ALREADY_REGISTERED', '422 IDENTITY_DOCUMENT_EXPIRED'],
          events: ['customer.identity_document_registered'],
          successStatus: [201, 200],
        },
        {
          code: 'identity.verification',
          name: 'Verificar la identidad',
          description: 'Contrasta el documento contra el proveedor de identidad y deja el intento registrado, favorable o no.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-verification',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          errors: ['422 IDENTITY_VERIFICATION_FAILED', '503 PROVIDER_UNAVAILABLE'],
          events: ['customer.identity_verification_attempted'],
        },
      ],
    },
    {
      code: 'submission',
      name: 'Envío a revisión',
      description:
        'Verifica la completitud del paquete y mueve al cliente a `under_review` con su evento de historial en la misma transacción.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      resultingStates: ['under_review'],
      completionRule: {
        type: 'lifecycle_status',
        statuses: ['under_review', 'active', 'suspended', 'rejected'],
      },
      steps: [
        {
          code: 'onboarding.submit',
          name: 'Enviar el paquete a revisión',
          description:
            'Reevalúa la completitud en el servidor; si falta algo responde `ONBOARDING_INCOMPLETE` con las secciones pendientes y no cambia nada.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/submit',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          resultingStates: ['under_review'],
          output: {
            blockers: 'EligibilityBlocker[]',
            eligible: 'boolean',
            nextStep: 'string',
            lifecycleStatus: 'string',
          },
          errors: ['422 ONBOARDING_INCOMPLETE', '422 ONBOARDING_ALREADY_SUBMITTED'],
          events: ['customer_onboarding.submitted', 'customer.status_changed'],
        },
        {
          code: 'onboarding.observations',
          name: 'Consultar las observaciones abiertas',
          description: 'Qué le están pidiendo al cliente, en su lenguaje. Es el camino de vuelta desde `observed`.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/observations',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['observed', 'under_review'],
        },
      ],
    },
    {
      code: 'reference_contacts',
      name: 'Referencias personales',
      description: 'Mínimo dos referencias personales; el máximo aceptado son cinco.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      parent: 'data_capture',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: {
        type: 'onboarding_section',
        sectionCode: 'reference_contacts',
      },
      steps: [
        {
          code: 'references.add',
          name: 'Agregar una referencia',
          description: 'Contacto de referencia con su relación declarada.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/reference-contacts',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          errors: ['422 TOO_MANY_REFERENCE_CONTACTS'],
          successStatus: [201],
        },
        {
          code: 'references.list',
          name: 'Listar las referencias cargadas',
          description: 'Referencias vigentes del cliente.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/reference-contacts',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
        },
        {
          code: 'references.remove',
          name: 'Eliminar una referencia',
          description: 'Corrección de una referencia cargada por error.',
          method: 'DELETE',
          path: '/customer-onboarding/:customerId/reference-contacts/:referenceId',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          errors: ['404 REFERENCE_CONTACT_NOT_FOUND'],
          successStatus: [200, 204],
        },
      ],
    },
    {
      code: 'risk_assessment',
      name: 'Evaluación de riesgo',
      description:
        'Calcula el score con la política vigente y deja la corrida explicable. Su recomendación es condición de la habilitación.',
      module: 'risk',
      actor: 'system',
      client: 'BLOCK',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'system', 'admin', 'platform_admin'],
      requiredStates: ['onboarding_in_progress', 'under_review', 'observed', 'active'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['RISK_NOT_APPROVED', 'RISK_ASSESSMENT_STALE'],
      },
      steps: [
        {
          code: 'risk.create_assessment',
          name: 'Ejecutar la evaluación de riesgo',
          description: 'Corre el ruleset activo y persiste corrida, reglas disparadas y contribuciones de cada variable.',
          method: 'POST',
          path: '/customers/:customerId/risk-assessments',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'system', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['onboarding_in_progress', 'under_review', 'observed', 'active'],
          output: {
            modelCode: 'string',
            rulesetVersion: 'string',
            recommendedAction: 'string',
            riskAssessmentRunId: 'string',
          },
          errors: ['422 RISK_RULESET_NOT_ACTIVE'],
          events: ['risk.assessment_completed'],
          successStatus: [201],
        },
        {
          code: 'risk.detail',
          name: 'Consultar la corrida de riesgo',
          description: 'Detalle de la corrida para operaciones.',
          method: 'GET',
          path: '/operations/risk-assessments/:riskAssessmentRunId',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['onboarding_in_progress', 'under_review', 'observed', 'active'],
        },
        {
          code: 'risk.explanation',
          name: 'Consultar la explicación del score',
          description: 'Reglas disparadas y contribución de cada variable. Es lo que hace defendible una decisión adversa.',
          method: 'GET',
          path: '/operations/risk-assessments/:riskAssessmentRunId/explanation',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['onboarding_in_progress', 'under_review', 'observed', 'active'],
        },
      ],
    },
    {
      code: 'privacy_consents',
      name: 'Consentimientos de privacidad',
      description: 'Decisiones del titular sobre cada finalidad de tratamiento, contra la versión legal vigente.',
      module: 'customer_privacy',
      actor: 'customer',
      client: 'CONSUMER_APP',
      parent: 'data_capture',
      roles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
      requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
      completionRule: {
        type: 'no_blockers',
        blockerCodes: ['CONSENT_MISSING'],
      },
      steps: [
        {
          code: 'consents.decisions',
          name: 'Registrar las decisiones de consentimiento',
          description: 'Otorga o revoca consentimientos contra el documento publicado vigente, dejando el evento inmutable.',
          method: 'POST',
          path: '/customers/:customerId/privacy/consent-decisions',
          roles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          errors: ['404 CONSENT_DOCUMENT_NOT_FOUND', '422 CONSENT_DOCUMENT_NOT_PUBLISHED'],
          events: ['privacy.consent_recorded'],
          successStatus: [201, 200],
        },
        {
          code: 'consents.data_subject_request',
          name: 'Ejercer un derecho del titular',
          description: 'Acceso, rectificación, portabilidad o supresión. No forma parte del camino feliz, pero sí del proceso.',
          method: 'POST',
          path: '/customers/:customerId/privacy/data-subject-requests',
          roles: ['customer', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          idempotencyKey: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'observed'],
          events: ['privacy.data_subject_request_created'],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'back_office_review',
      name: 'Revisión de operaciones',
      description:
        'Decisiones humanas sobre identidad, cumplimiento, observaciones y fraude. Sin señal automática de cierre: la resuelve un analista.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
      requiredStates: ['under_review', 'observed'],
      steps: [
        {
          code: 'ops.work_queue',
          name: 'Consultar la cola de trabajo',
          description: 'Casos pendientes de intervención humana, priorizados.',
          method: 'GET',
          path: '/operations/work-queue',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['under_review', 'observed'],
        },
        {
          code: 'ops.investigation_summary',
          name: 'Consultar el resumen de investigación del cliente',
          description: 'Vista consolidada de identidad, riesgo, dispositivos y casos abiertos del cliente.',
          method: 'GET',
          path: '/operations/customers/:customerId/investigation-summary',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['under_review', 'observed'],
        },
      ],
    },
    {
      code: 'eligibility',
      name: 'Habilitación crediticia',
      description:
        'Única puerta de entrada al crédito. Evalúa la regla vigente, deja evidencia y promueve a `active` cuando lo único que faltaba era el estado.',
      module: 'customers',
      actor: 'system',
      client: 'BLOCK',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'],
      requiredStates: ['under_review', 'observed', 'active', 'suspended'],
      resultingStates: ['active'],
      completionRule: {
        type: 'lifecycle_status',
        statuses: ['active'],
      },
      steps: [
        {
          code: 'eligibility.get',
          name: 'Evaluar y consultar la habilitación',
          description:
            'Calcula la regla, persiste la evaluación como evidencia con su versión y devuelve bloqueadores, secciones y siguiente paso.',
          method: 'GET',
          path: '/customers/:customerId/eligibility',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          requiredStates: ['registered', 'onboarding_in_progress', 'under_review', 'observed', 'active', 'suspended'],
          resultingStates: ['active'],
          output: {
            blockers: 'EligibilityBlocker[]',
            eligible: 'boolean',
            nextStep: 'string',
            sections: 'OnboardingSection[]',
            ruleVersion: 'string',
            completionPercentage: 'number',
          },
          errors: ['403 FORBIDDEN_OTHER_CUSTOMER', '404 CUSTOMER_NOT_FOUND'],
          events: ['customer.eligibility_evaluated'],
        },
        {
          code: 'ops.eligibility_decision',
          name: 'Decidir la habilitación (operaciones)',
          description: 'Aprueba, rechaza, observa, suspende o reincorpora. Aprobar con bloqueadores se registra como excepción autorizada.',
          method: 'POST',
          path: '/operations/customers/:customerId/eligibility/decision',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          requiredStates: ['under_review', 'observed', 'active', 'suspended', 'rejected', 'blocked'],
          resultingStates: ['active', 'observed', 'rejected', 'suspended', 'under_review'],
          errors: ['422 INVALID_STATUS_TRANSITION', '404 CUSTOMER_NOT_FOUND'],
          events: ['customer.status_changed', 'customer.eligibility_decided'],
        },
        {
          code: 'customer.me',
          name: 'Consultar el resumen del cliente',
          description: 'Perfil, contactos, onboarding y elegibilidad en una sola lectura para la pantalla principal de la app.',
          method: 'GET',
          path: '/customers/:customerId/me',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['under_review', 'observed', 'active', 'suspended'],
        },
      ],
    },
    {
      code: 'credit_application',
      name: 'Solicitud de crédito',
      description: 'El cliente habilitado elige producto, monto y plazo. El servidor reevalúa la elegibilidad antes de escribir nada.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['active'],
      steps: [
        {
          code: 'credit.list_products',
          name: 'Listar los productos disponibles para el cliente',
          description: '`canApply` refleja la elegibilidad real, de modo que el catálogo y la puerta de entrada no puedan discrepar.',
          method: 'GET',
          path: '/customers/:customerId/credit-products',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          repeatable: true,
          requiredStates: ['active'],
          output: {
            blockers: 'EligibilityBlocker[]',
            canApply: 'boolean',
            products: 'CreditProductDto[]',
          },
        },
        {
          code: 'credit.create_application',
          name: 'Crear la solicitud de crédito',
          description:
            'Revalida elegibilidad, rangos de monto y plazo, y congela el snapshot de la evaluación que la autorizó. Un cliente no puede tener dos solicitudes vivas.',
          method: 'POST',
          path: '/customers/:customerId/credit-applications',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['active'],
          input: {
            purposeCode: 'string?',
            creditProductId: 'string',
            requestedAmount: 'number',
            requestedTermMonths: 'number',
          },
          output: {
            status: 'submitted',
            applicationCode: 'string',
          },
          errors: [
            '404 CREDIT_PRODUCT_NOT_FOUND',
            '409 CREDIT_APPLICATION_ALREADY_OPEN',
            '422 CUSTOMER_NOT_ELIGIBLE',
            '422 REQUESTED_AMOUNT_OUT_OF_RANGE',
            '422 REQUESTED_TERM_OUT_OF_RANGE',
          ],
          events: ['credit.application_submitted'],
          successStatus: [201],
        },
        {
          code: 'credit.list_applications',
          name: 'Listar las solicitudes del cliente',
          description: 'Historial de solicitudes, más recientes primero.',
          method: 'GET',
          path: '/customers/:customerId/credit-applications',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['active'],
        },
      ],
    },
    {
      code: 'credit_decision',
      name: 'Decisión de crédito',
      description: 'Cierre del recorrido: operaciones aprueba o rechaza la solicitud y el evento queda en el historial inmutable.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      terminal: true,
      roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      requiredStates: ['active'],
      steps: [
        {
          code: 'ops.credit_application_detail',
          name: 'Consultar la solicitud',
          description: 'Detalle con la evidencia de elegibilidad congelada al momento de solicitar.',
          method: 'GET',
          path: '/operations/credit/applications/:applicationId',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          repeatable: true,
          requiredStates: ['active'],
        },
        {
          code: 'ops.credit_decision',
          name: 'Decidir la solicitud',
          description: 'Aprueba o rechaza con motivo. Genera el evento de la solicitud y cierra el recorrido.',
          method: 'POST',
          path: '/operations/credit/applications/:applicationId/decision',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          requiredStates: ['active'],
          errors: ['404 CREDIT_APPLICATION_NOT_FOUND', '422 INVALID_APPLICATION_STATUS_TRANSITION'],
          events: ['credit.application_decided'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'entry.start',
      from: null,
      to: 'registration.start',
      condition: 'always',
      description: 'Entrada del flujo: el recorrido empieza registrando al cliente.',
      isDefault: true,
    },
    {
      code: 'start.to_login',
      from: 'registration.start',
      to: 'registration.login',
      condition: 'on_success',
      description: 'Con el cliente creado se obtiene el token de acceso.',
      isDefault: true,
    },
    {
      code: 'start.to_login_pin',
      from: 'registration.start',
      to: 'registration.login_pin',
      condition: 'conditional',
      expression: {
        customerHasPin: true,
      },
      description: 'Camino alternativo de acceso para clientes con PIN configurado.',
    },
    {
      code: 'login.to_mfa',
      from: 'registration.login',
      to: 'registration.mfa',
      condition: 'conditional',
      expression: {
        field: 'mfaRequired',
        equals: true,
      },
      description: 'Solo si el login exigió segundo factor.',
    },
    {
      code: 'login.to_contact_method',
      from: 'registration.login',
      to: 'contact.add_method',
      condition: 'on_success',
      description: 'Autenticado, el cliente empieza la captura de datos por la verificación de contacto.',
      isDefault: true,
    },
    {
      code: 'login_pin.to_contact_method',
      from: 'registration.login_pin',
      to: 'contact.add_method',
      condition: 'on_success',
      description: 'Autenticado por PIN, el recorrido continúa igual que con contraseña.',
    },
    {
      code: 'contact_method.to_request',
      from: 'contact.add_method',
      to: 'contact.request_code',
      condition: 'on_success',
      description: 'Registrado el método, se pide el código.',
      isDefault: true,
    },
    {
      code: 'request.to_submit',
      from: 'contact.request_code',
      to: 'contact.submit_code',
      condition: 'on_success',
      description: 'Emitido el código, el cliente lo envía.',
      isDefault: true,
    },
    {
      code: 'submit_code.to_profile',
      from: 'contact.submit_code',
      to: 'profile.update',
      condition: 'on_success',
      description: 'Contacto verificado: sigue el perfil personal.',
      isDefault: true,
    },
    {
      code: 'profile.to_financial',
      from: 'profile.update',
      to: 'financial.update',
      condition: 'on_success',
      description: 'Perfil guardado: sigue el perfil económico.',
      isDefault: true,
    },
    {
      code: 'financial.to_address',
      from: 'financial.update',
      to: 'address.package',
      condition: 'on_success',
      description: 'Perfil económico guardado: sigue el domicilio.',
      isDefault: true,
    },
    {
      code: 'address.to_identity_upload',
      from: 'address.package',
      to: 'identity.upload_url',
      condition: 'on_success',
      description: 'Domicilio registrado: sigue la carga del documento de identidad.',
      isDefault: true,
    },
    {
      code: 'identity_upload.to_identity_package',
      from: 'identity.upload_url',
      to: 'identity.package',
      condition: 'on_success',
      description: 'Con el archivo cargado se registra el documento.',
      isDefault: true,
    },
    {
      code: 'identity_package.to_verification',
      from: 'identity.package',
      to: 'identity.verification',
      condition: 'on_success',
      description: 'Documento registrado: se verifica contra el proveedor.',
      isDefault: true,
    },
    {
      code: 'identity_verification.to_references',
      from: 'identity.verification',
      to: 'references.add',
      condition: 'on_success',
      description: 'Identidad verificada: siguen las referencias personales.',
      isDefault: true,
    },
    {
      code: 'identity_verification.to_external_request',
      from: 'identity.verification',
      to: 'external.request',
      condition: 'on_error',
      expression: {
        errorCodes: ['IDENTITY_VERIFICATION_FAILED', 'PROVIDER_UNAVAILABLE'],
      },
      description: 'Si el proveedor de identidad falla, se recurre a evidencia externa complementaria.',
    },
    {
      code: 'references.to_consents',
      from: 'references.add',
      to: 'consents.decisions',
      condition: 'on_success',
      description: 'Referencias cargadas: quedan los consentimientos.',
      isDefault: true,
    },
    {
      code: 'consents.to_submit',
      from: 'consents.decisions',
      to: 'onboarding.submit',
      condition: 'on_success',
      description: 'Paquete completo: se envía a revisión.',
      isDefault: true,
    },
    {
      code: 'submit.to_risk',
      from: 'onboarding.submit',
      to: 'risk.create_assessment',
      condition: 'on_state',
      expression: {
        lifecycleStatus: 'under_review',
      },
      description: 'En revisión: se ejecuta la evaluación de riesgo.',
      isDefault: true,
    },
    {
      code: 'submit.to_observations',
      from: 'onboarding.submit',
      to: 'onboarding.observations',
      condition: 'on_error',
      expression: {
        errorCodes: ['ONBOARDING_INCOMPLETE'],
      },
      description: 'Paquete incompleto: el cliente consulta qué le falta y vuelve a la captura.',
    },
    {
      code: 'risk.to_identity_decision',
      from: 'risk.create_assessment',
      to: 'ops.identity_decision',
      condition: 'on_success',
      description: 'Con el riesgo evaluado, operaciones decide sobre la identidad.',
      isDefault: true,
    },
    {
      code: 'identity_decision.to_screening',
      from: 'ops.identity_decision',
      to: 'ops.compliance_screening',
      condition: 'on_success',
      description: 'Identidad resuelta: se ejecuta el cribado de cumplimiento.',
      isDefault: true,
    },
    {
      code: 'screening.to_clear',
      from: 'ops.compliance_screening',
      to: 'ops.compliance_clear',
      condition: 'conditional',
      expression: {
        blockerCodes: ['COMPLIANCE_MATCH_PENDING'],
      },
      description: 'Si hubo coincidencias, hay que resolverlas antes de continuar.',
    },
    {
      code: 'screening.to_eligibility',
      from: 'ops.compliance_screening',
      to: 'eligibility.get',
      condition: 'on_success',
      description: 'Sin coincidencias pendientes: se evalúa la habilitación.',
      isDefault: true,
    },
    {
      code: 'clear.to_eligibility',
      from: 'ops.compliance_clear',
      to: 'eligibility.get',
      condition: 'on_success',
      description: 'Resueltas las coincidencias, se evalúa la habilitación.',
    },
    {
      code: 'manual_decision.to_observations',
      from: 'ops.manual_decision',
      to: 'onboarding.observations',
      condition: 'on_state',
      expression: {
        lifecycleStatus: 'observed',
      },
      description: 'Si el analista pide más información, el cliente vuelve al circuito de observaciones.',
    },
    {
      code: 'fraud_decision.to_eligibility',
      from: 'ops.fraud_decision',
      to: 'eligibility.get',
      condition: 'on_state',
      expression: {
        lifecycleStatus: 'under_review',
      },
      description: 'Descartado el fraude, el cliente vuelve a evaluarse.',
    },
    {
      code: 'eligibility.to_products',
      from: 'eligibility.get',
      to: 'credit.list_products',
      condition: 'on_state',
      expression: {
        eligible: true,
        lifecycleStatus: 'active',
      },
      description: 'Cliente habilitado: puede ver los productos que puede solicitar.',
      isDefault: true,
    },
    {
      code: 'eligibility.to_decision',
      from: 'eligibility.get',
      to: 'ops.eligibility_decision',
      condition: 'conditional',
      expression: {
        eligible: false,
      },
      description: 'Con bloqueadores vigentes, la habilitación pasa por una decisión humana.',
    },
    {
      code: 'eligibility_decision.to_eligibility',
      from: 'ops.eligibility_decision',
      to: 'eligibility.get',
      condition: 'on_success',
      description: 'Aplicada la decisión, se reevalúa para dejar la evidencia actualizada.',
    },
    {
      code: 'products.to_application',
      from: 'credit.list_products',
      to: 'credit.create_application',
      condition: 'on_success',
      description: 'Elegido el producto, se crea la solicitud.',
      isDefault: true,
    },
    {
      code: 'application.to_decision',
      from: 'credit.create_application',
      to: 'ops.credit_decision',
      condition: 'on_success',
      description: 'La solicitud entra en la cola de decisión de operaciones.',
      isDefault: true,
    },
    {
      code: 'exit.decision',
      from: 'ops.credit_decision',
      to: null,
      condition: 'always',
      description: 'Salida del flujo: la solicitud queda aprobada o rechazada.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'registration.login',
      dependsOn: 'registration.start',
      type: 'requires_completion',
      description: 'No hay credenciales que autenticar antes de crear el cliente.',
    },
    {
      step: 'contact.request_code',
      dependsOn: 'contact.add_method',
      type: 'requires_completion',
      description: 'El código se envía al método de contacto registrado.',
    },
    {
      step: 'contact.submit_code',
      dependsOn: 'contact.request_code',
      type: 'requires_completion',
      description: 'Sin código emitido no hay nada que validar.',
    },
    {
      step: 'identity.package',
      dependsOn: 'identity.upload_url',
      type: 'requires_data',
      description: 'El registro del documento referencia el objeto cargado con la URL firmada.',
    },
    {
      step: 'identity.verification',
      dependsOn: 'identity.package',
      type: 'requires_completion',
      description: 'La verificación contrasta el documento ya registrado.',
    },
    {
      step: 'onboarding.submit',
      dependsOn: 'contact.submit_code',
      type: 'requires_completion',
      description: 'Sección `contact_verification` obligatoria para enviar el paquete.',
    },
    {
      step: 'onboarding.submit',
      dependsOn: 'profile.update',
      type: 'requires_completion',
      description: 'Sección `personal_data` obligatoria para enviar el paquete.',
    },
    {
      step: 'onboarding.submit',
      dependsOn: 'financial.update',
      type: 'requires_completion',
      description: 'Sección `financial_profile` obligatoria para enviar el paquete.',
    },
    {
      step: 'onboarding.submit',
      dependsOn: 'address.package',
      type: 'requires_completion',
      description: 'Sección `address` obligatoria para enviar el paquete.',
    },
    {
      step: 'onboarding.submit',
      dependsOn: 'identity.package',
      type: 'requires_completion',
      description: 'Sección `identity_documents` obligatoria para enviar el paquete.',
    },
    {
      step: 'onboarding.submit',
      dependsOn: 'references.add',
      type: 'requires_completion',
      description: 'Sección `reference_contacts` obligatoria para enviar el paquete.',
    },
    {
      step: 'onboarding.submit',
      dependsOn: 'consents.decisions',
      type: 'requires_completion',
      description: 'Los consentimientos requeridos bloquean la habilitación mientras falten.',
    },
    {
      step: 'risk.create_assessment',
      dependsOn: 'onboarding.submit',
      type: 'requires_data',
      description: 'La evaluación de riesgo se apoya en el paquete completo enviado a revisión.',
    },
    {
      step: 'eligibility.get',
      dependsOn: 'risk.create_assessment',
      type: 'requires_data',
      description: 'Sin una corrida de riesgo favorable y vigente, la habilitación queda bloqueada.',
    },
    {
      step: 'credit.create_application',
      dependsOn: 'eligibility.get',
      type: 'requires_completion',
      description: 'Solo un cliente habilitado puede abrir una solicitud.',
    },
    {
      step: 'credit.create_application',
      dependsOn: 'credit.list_products',
      type: 'requires_data',
      description: 'La solicitud referencia un producto vigente del catálogo.',
    },
    {
      step: 'credit.create_application',
      dependsOn: 'ops.credit_product_status',
      type: 'soft',
      description: 'Sin al menos un producto activo no hay nada que solicitar.',
    },
    {
      step: 'ops.credit_decision',
      dependsOn: 'credit.create_application',
      type: 'requires_completion',
      description: 'No hay decisión sin solicitud.',
    },
  ],
};
