/**
 * @file Proceso declarado en código: Ejecución de una decisión en el Motor y revisión manual con aviso de vuelta a Atlas.
 * @business Crédito, identidad, riesgo y KYB se deciden en el Motor; cuando la política pide una persona, la solicitud del cliente sólo avanza si la resolución del analista vuelve a Atlas.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; la decisión y la cola viven en AtlasDecisionEngineBackend (runtime, manual-review) y el cierre en los tres callbacks `/internal/{identity,risk,credit}/manual-review-callback` de AtlasBackend.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const DECISION_EXECUTION_AND_MANUAL_REVIEW: WorkflowDefinitionFixture = {
  processId: 'P-27',
  code: 'decision_execution_and_manual_review',
  version: 'v1',
  name: 'Ejecución de una decisión y revisión manual en el Motor con callback a Atlas',
  description:
    'Atlas pide una decisión al Motor por código de artefacto con clave de idempotencia; el Motor resuelve el despliegue activo, ejecuta el compilado y guarda ejecución, variables, traza y razones en una transacción. Sólo si el grafo pasó por un nodo MANUAL_REVIEW se abre un caso con cola, prioridad y SLA; el analista lo toma y lo resuelve en el portal del Motor, y la resolución vuelve a Atlas por el callback de su cola.',
  processType: 'integration',
  ownerDomain: 'decisioning',
  ownerRole: 'MOTOR:RISK_ANALYST',
  priority: 'P0',
  systems: ['DECISION_ENGINE', 'ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Las decisiones de crédito, identidad, riesgo de alta y KYB de comercios se toman en el Motor con una política versionada y auditable. Cuando la política no puede decidir sola deriva a una persona, y esa resolución tiene que volver a Atlas: si no vuelve, el cliente se queda en revisión para siempre y no puede pedir crédito.',
    whoStartsAndCloses:
      'Lo inicia AtlasBackend, como sistema, al pedir la decisión (POST /v1/decisions/:artifactCode con la llave de ejecución). Si se abre un caso, lo toma y lo resuelve un analista del Motor (OPERATIONS, RISK_ANALYST o FRAUD_ANALYST) y lo cierra AtlasBackend al aplicar la resolución que le llega por el callback de la cola.',
    startAndEnd:
      'Empieza con la petición de decisión y termina con la ejecución SUCCEEDED, NO_DECISION o FAILED. Si hubo nodo MANUAL_REVIEW, sigue con el caso OPEN → ASSIGNED → RESOLVED_APPROVED, RESOLVED_DECLINED o CANCELLED y acaba cuando Atlas recibe el aviso en /internal/{identity,risk,credit}/manual-review-callback. Un rechazo directo no abre caso.',
    whenItFails:
      'Sin despliegue activo en el ambiente el Motor responde ACTIVE_DEPLOYMENT_NOT_FOUND; repetir la misma clave devuelve la misma ejecución y una clave con otro contenido da IDEMPOTENCY_PAYLOAD_MISMATCH. Si el aviso a Atlas falla, la resolución se mantiene y queda el evento MANUAL_REVIEW_CALLBACK_FAILED en la auditoría del Motor; sin ATLAS_BACKEND_BASE_URL o ENGINE_CALLBACK_API_KEY sólo se avisa en el registro.',
    healthIndicator:
      'Casos OPEN o ASSIGNED fuera de su SLA (due_at) en la cola del Motor, eventos MANUAL_REVIEW_CALLBACK_FAILED en cero, y solicitudes de Atlas en revisión cuya ejecución ya tiene caso resuelto (señal de un aviso perdido).',
  },
  instanceEntity: {
    system: 'DECISION_ENGINE',
    schema: 'public',
    table: 'decision_manual_review_case',
    idColumn: 'id',
    statusColumn: 'status',
    labelColumn: 'case_code',
    openStatuses: ['OPEN', 'ASSIGNED'],
  },
  success: 'La decisión se devuelve con sus razones y, si hubo revisión, la resolución del analista queda aplicada en Atlas.',
  failure:
    'La decisión falla (sin despliegue activo, idempotencia en conflicto) o la resolución no llega a Atlas y el caso de allá sigue en revisión.',
  sources: [
    'AtlasDecisionEngineBackend/docs/business/critical-workflows.md §2 y §4',
    'AtlasDecisionEngineBackend/src/modules/runtime/runtime.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/runtime/execution-writer.service.ts',
    'AtlasDecisionEngineBackend/src/modules/runtime/idempotency.service.ts',
    'AtlasDecisionEngineBackend/src/modules/manual-review/manual-review.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/manual-review/manual-review.service.ts',
    'AtlasDecisionEngineBackend/src/modules/manual-review/manual-review.dto.ts',
    'AtlasDecisionEngineBackend/prisma/schema.prisma (ExecutionStatus, ManualReviewStatus)',
    'src/modules/decision-engine/decision-engine.client.ts',
    'src/modules/credit/credit-review-callback.controller.ts',
    'src/modules/risk/risk-review-callback.controller.ts',
    'src/modules/customer-onboarding/identity-review-callback.controller.ts',
    'src/common/utils/auth/engine-callback-key.util.ts',
    'AtlasAdminPortal/src/shared/decision-engine/engine-links.ts',
    'memoria atlas-portal-motor-duplicacion (que DECIDA no implica que ABRA CASO)',
    'memoria atlas-identidad-cola-humana',
  ],
  metadata: {
    callbackByQueue: {
      IDENTIDAD: '/internal/identity/manual-review-callback',
      RIESGO_ONBOARDING: '/internal/risk/manual-review-callback',
      CREDIT_REVIEW: '/internal/credit/manual-review-callback',
      MERCHANT_KYB: 'sin callback: AtlasBackend lo lee por tirón (sync_partner_kyb_reviews)',
    },
    gaps: [
      'El artefacto de Flow Intelligence marca los tres callbacks como UNPROTECTED_WRITE: son @Public() respecto a la sesión pero exigen la cabecera x-engine-callback-key (assertEngineCallbackKey, 401 sin clave configurada). Falta declararlo en el artefacto.',
      'La regla «un RESULT no abre caso; sólo un nodo MANUAL_REVIEW» vivía sólo en memoria; queda aquí.',
      'Atlas sigue abriendo su caso local como ancla y rechaza resolverlo con MANUAL_REVIEW_DELEGADA_AL_MOTOR cuando el Motor abrió caso.',
    ],
  },
  stages: [
    {
      code: 'execution_decision_request',
      name: 'Pedir la decisión',
      description:
        'AtlasBackend llama al Motor con requestId, idempotencyKey, environmentCode y subjectReference. El Motor reserva la clave con un lease corto, resuelve el despliegue activo por decision_runtime_binding y resuelve las variables antes de abrir la transacción.',
      module: 'runtime',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      steps: [
        {
          code: 'execution.decide',
          name: 'Ejecutar el artefacto',
          description:
            'Reintentar con la misma clave devuelve la misma ejecución, no una decisión nueva. Si abrió caso, la respuesta trae manualReview.caseCode.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
          roles: ['DECISION_RUNTIME'],
          idempotencyKey: true,
          resultingStates: ['SUCCEEDED', 'NO_DECISION', 'FAILED'],
          input: {
            requestId: 'string',
            idempotencyKey: 'string',
            environmentCode: 'string?',
            subjectReference: 'string?',
            variables: 'object',
            context: 'object?',
          },
          output: { decision: 'string', reasons: 'Reason[]', executionId: 'string', manualReview: '{ caseCode } | null' },
          errors: ['ACTIVE_DEPLOYMENT_NOT_FOUND', 'IDEMPOTENCY_PAYLOAD_MISMATCH', 'IDEMPOTENCY_IN_PROGRESS', 'IDEMPOTENCY_CONTENDED'],
        },
      ],
    },
    {
      code: 'execution_persist_and_case',
      name: 'Guardar la ejecución y abrir el caso',
      description:
        'En una sola transacción se guardan ejecución, variables, traza y razones. Sólo si el grafo pasó por un nodo MANUAL_REVIEW se crea el caso con cola, prioridad, SLA y evidencia; un rechazo directo no lo abre.',
      module: 'runtime',
      actor: 'system',
      client: 'BLOCK',
      resultingStates: ['OPEN'],
      steps: [
        {
          code: 'execution.open_manual_review_case',
          name: 'Abrir el caso de revisión',
          description:
            'Crea decision_manual_review_case (execution_id único) con case_code, queue_code, prioridad y due_at = decisión + SLA.',
          kind: 'event',
          system: 'DECISION_ENGINE',
          reason: 'Ocurre dentro de la misma transacción que guarda la ejecución (execution-writer.service.ts); no es una llamada aparte.',
          optional: true,
          resultingStates: ['OPEN'],
        },
      ],
    },
    {
      code: 'execution_atlas_observes',
      name: 'Atlas ve la solicitud en su bandeja',
      description:
        'La bandeja de trabajo del portal admin muestra el caso local que ancla la solicitud; cuando el Motor abrió caso, resolver aquí está bloqueado y se enlaza al Motor (necesita NEXT_PUBLIC_DECISION_ENGINE_URL).',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/work-queue',
      link: '{MOTOR}/manual-reviews/{instanceId}',
      optional: true,
      steps: [
        {
          code: 'execution.atlas_work_queue',
          name: 'Bandeja de trabajo de Atlas',
          description: 'Sólo observa: la resolución de un caso delegado se hace en el Motor.',
          method: 'GET',
          path: '/operations/work-queue',
          optional: true,
        },
      ],
    },
    {
      code: 'execution_manual_review_triage',
      name: 'Tomar el caso',
      description: 'El analista mira la cola del Motor por prioridad y SLA y se asigna el caso para que dos personas no trabajen el mismo.',
      module: 'manual-review',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/manual-reviews',
      optional: true,
      roles: ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'],
      requiredStates: ['OPEN'],
      resultingStates: ['ASSIGNED'],
      steps: [
        {
          code: 'execution.manual_reviews_list',
          name: 'Cola de revisión',
          description: 'Casos por cola, estado y prioridad, con la ejecución resumida.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/manual-reviews',
          roles: ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'],
          optional: true,
        },
        {
          code: 'execution.manual_review_get',
          name: 'Leer el caso',
          description: 'Evidencia, razones y variables de la ejecución.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/manual-reviews/:caseId',
          roles: ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'],
          optional: true,
        },
        {
          code: 'execution.manual_review_assign',
          name: 'Asignarse el caso',
          description: 'Pasa el caso a ASSIGNED con su responsable.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/assign',
          roles: ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'],
          optional: true,
          requiredStates: ['OPEN'],
          resultingStates: ['ASSIGNED'],
        },
      ],
    },
    {
      code: 'execution_manual_review_resolve',
      name: 'Resolver el caso',
      description:
        'El analista aprueba, rechaza o cancela con motivo obligatorio. La resolución se confirma primero y el aviso a Atlas sale después, fuera de la transacción.',
      module: 'manual-review',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/manual-reviews/[caseId]',
      optional: true,
      roles: ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'],
      requiredStates: ['OPEN', 'ASSIGNED'],
      resultingStates: ['RESOLVED_APPROVED', 'RESOLVED_DECLINED', 'CANCELLED'],
      steps: [
        {
          code: 'execution.manual_review_resolve',
          name: 'Resolver',
          description: 'APPROVE → RESOLVED_APPROVED, DECLINE → RESOLVED_DECLINED, CANCEL → CANCELLED.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/resolve',
          roles: ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'],
          optional: true,
          input: { decision: 'APPROVE | DECLINE | CANCEL', reason: 'string' },
          resultingStates: ['RESOLVED_APPROVED', 'RESOLVED_DECLINED', 'CANCELLED'],
          events: ['MANUAL_REVIEW_CALLBACK_FAILED'],
        },
      ],
    },
    {
      code: 'execution_callback_to_atlas',
      name: 'Avisar a Atlas',
      description:
        'El Motor manda executionId, decisión, motivo y quién resolvió a la ruta de la cola, con x-tenant-id y x-engine-callback-key y 10 s de espera. Atlas localiza el intento, el caso de riesgo o la solicitud por la ejecución. CANCEL no se aplica: la solicitud queda como está.',
      module: 'manual-review',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      terminal: true,
      steps: [
        {
          code: 'execution.callback_identity',
          name: 'Callback de identidad',
          description: 'Cola IDENTIDAD: aplica la resolución al intento de verificación de identidad.',
          method: 'POST',
          path: '/internal/identity/manual-review-callback',
          auth: false,
          optional: true,
          errors: ['401 clave de callback ausente o inválida'],
        },
        {
          code: 'execution.callback_risk',
          name: 'Callback de riesgo de alta',
          description: 'Cola RIESGO_ONBOARDING: aplica la resolución al caso de riesgo del alta.',
          method: 'POST',
          path: '/internal/risk/manual-review-callback',
          auth: false,
          optional: true,
          errors: ['401 clave de callback ausente o inválida'],
        },
        {
          code: 'execution.callback_credit',
          name: 'Callback de crédito',
          description: 'Cola CREDIT_REVIEW: mueve la solicitud de crédito que seguía under_review.',
          method: 'POST',
          path: '/internal/credit/manual-review-callback',
          auth: false,
          optional: true,
          output: { applied: 'boolean', reason: 'DECISION_NO_APLICABLE (CANCEL)' },
          errors: ['400 Falta executionId.', '401 clave de callback ausente o inválida'],
        },
        {
          code: 'execution.kyb_pull',
          name: 'Tirón del KYB de comercios',
          description: 'La cola MERCHANT_KYB no tiene callback: Atlas lee el caso del Motor por su caseCode en un trabajo programado.',
          kind: 'job',
          job: 'sync_partner_kyb_reviews',
          optional: true,
        },
      ],
    },
  ],
};
