/**
 * @file Proceso declarado en código: Gobierno de artefactos del Motor (versión, compilación, suite bloqueante, firmas, despliegue y vínculo en Atlas).
 * @business Una política de crédito, identidad o riesgo decide sobre personas reales: ningún cambio llega a producción sin compilar, sin pasar su suite bloqueante y sin la firma de alguien distinto de su autor.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; casi todo ocurre en AtlasDecisionEngineBackend (artifacts, testing, governance, deployments) y el último paso lo da AtlasBackend al elegir qué artefacto decide cada cosa.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const DECISION_ARTIFACT_GOVERNANCE: WorkflowDefinitionFixture = {
  processId: 'P-26',
  code: 'decision_artifact_governance',
  version: 'v1',
  name: 'Gobierno de artefactos del Motor: versión, compilación, suite bloqueante, dos firmas, despliegue y binding',
  description:
    'Cómo una versión de un artefacto de decisión pasa de borrador a desplegada: edición del grafo, validación y compilación, suite de pruebas bloqueante, envío a revisión, pasos de aprobación en orden (QA y aprobador de riesgo, más cumplimiento si se pide) sin que el autor firme, despliegue por ambiente que crea el vínculo de ejecución, y la elección del artefacto en Atlas.',
  processType: 'back_office',
  ownerDomain: 'decisioning',
  ownerRole: 'MOTOR:RISK_APPROVER',
  priority: 'P1',
  systems: ['DECISION_ENGINE', 'ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Un artefacto del Motor es la política que aprueba o rechaza crédito, identidad y riesgo. Cambiarla sin control es cambiar a quién se le presta: por eso cada versión se compila, se prueba con una suite bloqueante y la firman personas distintas de su autor antes de desplegarse, y todo queda en la cadena de auditoría.',
    whoStartsAndCloses:
      'Lo inicia un analista de riesgo o de fraude del Motor al crear o clonar una versión; firman en orden un QA_ANALYST y un RISK_APPROVER (y COMPLIANCE si se pidió), nunca el autor; despliega un PLATFORM_ADMIN que tampoco sea el autor; y en Atlas un operador o analista de riesgo elige ese artefacto para su tipo de decisión.',
    startAndEnd:
      'Empieza con la versión en DRAFT (único estado editable) y termina con la versión DEPLOYED_TO_DEV, _TEST, _STAGING o _PROD, con su decision_runtime_binding apuntando al despliegue activo y el artefacto asignado en /internal/settings/decision-artifacts de Atlas. Sembrar una versión no es desplegarla.',
    whenItFails:
      'Enviar a revisión sin compilar da VERSION_NOT_REVIEWABLE; sin la suite bloqueante en verde, BLOCKING_TESTS_NOT_PASSED; si el autor firma o despliega, SEPARATION_OF_DUTIES_VIOLATION; un paso fuera de orden, APPROVAL_STEP_OUT_OF_ORDER. Un revisor puede pedir cambios (CHANGES_REQUESTED) o rechazar (REJECTED). Sin vínculo de ejecución, decidir responde ACTIVE_DEPLOYMENT_NOT_FOUND.',
    healthIndicator:
      'Solicitudes de aprobación abiertas y su antigüedad (GET /v1/approval-requests), versiones IN_REVIEW sin movimiento, y que cada tipo de decisión de Atlas apunte a un artefacto que el Motor publica y tiene desplegado en el ambiente (pantalla de artefactos activos del portal admin).',
  },
  instanceEntity: {
    system: 'DECISION_ENGINE',
    schema: 'public',
    table: 'decision_artifact_version',
    idColumn: 'id',
    statusColumn: 'status',
    labelColumn: 'semantic_version',
    openStatuses: ['DRAFT', 'VALIDATION_FAILED', 'VALIDATED', 'COMPILED', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED'],
  },
  success: 'La versión queda desplegada en su ambiente con vínculo de ejecución activo y Atlas la usa para su tipo de decisión.',
  failure: 'La versión queda en CHANGES_REQUESTED o REJECTED, o no se admite a revisión por no compilar o no pasar su suite bloqueante.',
  sources: [
    'AtlasDecisionEngineBackend/docs/business/critical-workflows.md §1 y §3',
    'AtlasDecisionEngineBackend/docs/governance/review-process.md',
    'AtlasDecisionEngineBackend/src/modules/artifacts/artifact.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/artifacts/version-state.service.ts',
    'AtlasDecisionEngineBackend/src/modules/governance/governance.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/governance/governance.service.ts',
    'AtlasDecisionEngineBackend/src/modules/testing/testing.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/testing/test-run-worker.service.ts',
    'AtlasDecisionEngineBackend/src/modules/deployments/deployment.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/deployments/deployment.service.ts',
    'AtlasDecisionEngineBackend/prisma/schema.prisma (VersionStatus, ApprovalRequestStatus, DeploymentStatus)',
    'src/modules/decision-engine/decision-artifact-binding.controller.ts',
    'AtlasAdminPortal/src/shared/decision-engine/engine-links.ts',
    'CLAUDE.md §5 (dos personas firman; sembrar no es desplegar)',
    'memoria atlas-motor-crear-artefacto',
  ],
  metadata: {
    approvalSteps: ['QA_ANALYST (1 aprobación)', 'RISK_APPROVER (1 aprobación)', 'COMPLIANCE (1, sólo con requireCompliance)'],
    gaps: [
      'La regla «sin suite BLOQUEANTE en verde no se admite a revisión» y el trabajador test-run que procesa las corridas no estaban escritos como proceso; quedan aquí.',
      'Los enlaces del portal admin al Motor no se pintan sin NEXT_PUBLIC_DECISION_ENGINE_URL.',
      'POST /v1/artifact-versions/:versionId/validate-and-compile no tiene llamador en el portal del Motor (usa validate y compile por separado).',
    ],
  },
  stages: [
    {
      code: 'governance_artifact_creation',
      name: 'Crear el artefacto o clonar una versión',
      description: 'El analista crea el artefacto con su primera versión, o clona una versión existente para abrir un borrador nuevo.',
      module: 'artifacts',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/artifacts',
      entry: true,
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
      resultingStates: ['DRAFT'],
      steps: [
        {
          code: 'governance.artifact_create',
          name: 'Crear el artefacto',
          description: 'Alta del artefacto con su versión inicial en DRAFT.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifacts',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
          resultingStates: ['DRAFT'],
        },
        {
          code: 'governance.version_clone',
          name: 'Clonar una versión',
          description: 'Abre un borrador nuevo a partir de otra versión; es el camino de vuelta tras CHANGES_REQUESTED.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifact-versions/:versionId/clone',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
          optional: true,
          resultingStates: ['DRAFT'],
        },
      ],
    },
    {
      code: 'governance_version_editing',
      name: 'Editar el grafo',
      description: 'Sólo un borrador es editable. El analista edita nodos y aristas, las notas y la base de tratamiento de datos.',
      module: 'artifacts',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/artifact-versions/[versionId]/graph',
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
      requiredStates: ['DRAFT'],
      steps: [
        {
          code: 'governance.version_graph_get',
          name: 'Leer el grafo',
          description: 'Nodos y aristas de la versión.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/artifact-versions/:versionId/graph',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'COMPLIANCE', 'AUDITOR'],
        },
        {
          code: 'governance.version_graph_put',
          name: 'Guardar el grafo',
          description: 'Reemplaza el grafo del borrador; fuera de DRAFT responde VERSION_IMMUTABLE.',
          system: 'DECISION_ENGINE',
          method: 'PUT',
          path: '/v1/artifact-versions/:versionId/graph',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
          repeatable: true,
          errors: ['VERSION_IMMUTABLE'],
        },
        {
          code: 'governance.version_notes',
          name: 'Notas de la versión',
          description: 'Describe el impacto de negocio del cambio, que el revisor lee antes de aprobar.',
          system: 'DECISION_ENGINE',
          method: 'PATCH',
          path: '/v1/artifact-versions/:versionId/notes',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
          optional: true,
        },
      ],
    },
    {
      code: 'governance_validate_compile',
      name: 'Validar y compilar',
      description:
        'Estructura, expresiones, determinismo y contrato de salida. Un fallo deja VALIDATION_FAILED con informe por nodo; si pasa, COMPILED con su compilado inmutable.',
      module: 'artifacts',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/artifact-versions/[versionId]/compile',
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST'],
      requiredStates: ['DRAFT'],
      resultingStates: ['VALIDATION_FAILED', 'VALIDATED', 'COMPILED'],
      steps: [
        {
          code: 'governance.version_validate',
          name: 'Validar',
          description: 'Informe de validación; deja VALIDATED o VALIDATION_FAILED.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifact-versions/:versionId/validate',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST'],
          resultingStates: ['VALIDATED', 'VALIDATION_FAILED'],
        },
        {
          code: 'governance.version_compile',
          name: 'Compilar',
          description: 'Genera el compilado que ejecutará el Motor; los campos calculados viajan congelados dentro.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifact-versions/:versionId/compile',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST'],
          requiredStates: ['VALIDATED'],
          resultingStates: ['COMPILED'],
        },
        {
          code: 'governance.version_validate_and_compile',
          name: 'Validar y compilar de una vez',
          description: 'Atajo de los dos pasos anteriores.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifact-versions/:versionId/validate-and-compile',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST'],
          optional: true,
          resultingStates: ['COMPILED', 'VALIDATION_FAILED'],
        },
      ],
    },
    {
      code: 'governance_blocking_suite',
      name: 'Suite de regresión bloqueante',
      description:
        'La versión necesita al menos una suite marcada bloqueante y en verde para admitirse a revisión. El analista o QA crea la suite, sus casos y lanza la corrida.',
      module: 'testing',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/artifact-versions/[versionId]/test-suites',
      roles: ['QA_ANALYST', 'RISK_ANALYST', 'FRAUD_ANALYST'],
      requiredStates: ['COMPILED'],
      steps: [
        {
          code: 'governance.test_suite_create',
          name: 'Crear la suite',
          description: 'Suite de la versión; isBlocking decide si cuenta para admitir la revisión.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifact-versions/:versionId/test-suites',
          roles: ['QA_ANALYST', 'RISK_ANALYST', 'FRAUD_ANALYST'],
        },
        {
          code: 'governance.test_cases_add',
          name: 'Añadir casos',
          description: 'Entradas y salida esperada; también se importan en lote (POST /v1/test-suites/:suiteId/cases/import).',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/test-suites/:suiteId/cases',
          roles: ['QA_ANALYST', 'RISK_ANALYST', 'FRAUD_ANALYST'],
          repeatable: true,
        },
        {
          code: 'governance.test_run_start',
          name: 'Lanzar la corrida',
          description: 'Encola la corrida y la anuncia con pg_notify en la misma transacción.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/test-suites/:suiteId/runs',
          roles: ['QA_ANALYST', 'RISK_ANALYST', 'FRAUD_ANALYST'],
          repeatable: true,
        },
        {
          code: 'governance.test_run_worker',
          name: 'Ejecutar la corrida',
          description: 'Trabajador con reclamo atómico, concurrencia acotada y leases que vencen; deja la corrida PASSED o FAILED.',
          kind: 'job',
          system: 'DECISION_ENGINE',
          job: 'test-run',
        },
        {
          code: 'governance.test_run_get',
          name: 'Ver el resultado',
          description: 'Estado y resultado caso por caso.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/test-runs/:runId',
          roles: ['QA_ANALYST', 'RISK_ANALYST', 'FRAUD_ANALYST', 'COMPLIANCE', 'AUDITOR'],
        },
      ],
    },
    {
      code: 'governance_submit_for_review',
      name: 'Enviar a revisión',
      description:
        'Crea la solicitud de aprobación con sus pasos (QA, aprobador de riesgo y, si se pide, cumplimiento), pasa la versión a IN_REVIEW y audita APPROVAL_REQUEST_CREATED en la misma transacción.',
      module: 'governance',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/reviews',
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
      requiredStates: ['COMPILED'],
      resultingStates: ['IN_REVIEW'],
      steps: [
        {
          code: 'governance.submit_for_review',
          name: 'Enviar la versión a revisión',
          description: 'Exige COMPILED con compilado exitoso y la suite bloqueante en verde.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifact-versions/:versionId/submit-for-review',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
          requiredStates: ['COMPILED'],
          resultingStates: ['IN_REVIEW'],
          input: { workflowCode: 'string?', requireCompliance: 'boolean', dueAt: 'date?' },
          errors: ['VERSION_NOT_REVIEWABLE', 'BLOCKING_TESTS_NOT_PASSED', 'APPROVAL_REQUEST_EXISTS'],
        },
      ],
    },
    {
      code: 'governance_approval',
      name: 'Firmar la aprobación',
      description:
        'Cada paso lo firma el rol exigido, en orden y nunca el autor. Aprobar el último paso deja la versión APPROVED; pedir cambios o rechazar cierra la solicitud. Las firmas son de personas desde el portal del Motor: no hay aprobadores de máquina.',
      module: 'governance',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/approval-requests/[requestId]',
      link: '{MOTOR}/reviews',
      roles: ['QA_ANALYST', 'RISK_APPROVER', 'COMPLIANCE'],
      requiredStates: ['IN_REVIEW'],
      resultingStates: ['APPROVED', 'CHANGES_REQUESTED', 'REJECTED'],
      steps: [
        {
          code: 'governance.approval_requests_list',
          name: 'Bandeja de solicitudes',
          description: 'Solicitudes de aprobación con su paso actual.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/approval-requests',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'RISK_APPROVER', 'COMPLIANCE', 'AUDITOR'],
        },
        {
          code: 'governance.approval_request_get',
          name: 'Leer la solicitud',
          description: 'Pasos, firmas y evidencia de la suite bloqueante.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/approval-requests/:requestId',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'RISK_APPROVER', 'COMPLIANCE', 'AUDITOR'],
        },
        {
          code: 'governance.approval_decision',
          name: 'Firmar el paso',
          description: 'APPROVE, REQUEST_CHANGES o REJECT; el voto y su evento de auditoría van en la misma transacción.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/approval-steps/:stepId/decisions',
          roles: ['QA_ANALYST', 'RISK_APPROVER', 'COMPLIANCE'],
          repeatable: true,
          input: { decision: 'APPROVE | REQUEST_CHANGES | REJECT', comments: 'string?', evidence: 'ApprovalEvidence[]' },
          errors: [
            '403 SEPARATION_OF_DUTIES_VIOLATION',
            'APPROVAL_STEP_OUT_OF_ORDER',
            'APPROVAL_ROLE_REQUIRED',
            'APPROVAL_STEP_CLOSED',
            '409 DUPLICATE_APPROVAL_DECISION',
          ],
        },
      ],
    },
    {
      code: 'governance_deployment',
      name: 'Desplegar por ambiente',
      description:
        'Un PLATFORM_ADMIN que no sea el autor despliega el compilado en un ambiente activo: el despliegue anterior queda SUPERSEDED, se escribe decision_runtime_binding y la versión pasa a DEPLOYED_TO_<ambiente>. Revertir y suspender quedan a mano.',
      module: 'deployments',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/deployments',
      roles: ['PLATFORM_ADMIN'],
      requiredStates: ['APPROVED'],
      resultingStates: ['DEPLOYED_TO_DEV', 'DEPLOYED_TO_TEST', 'DEPLOYED_TO_STAGING', 'DEPLOYED_TO_PROD', 'SUSPENDED'],
      steps: [
        {
          code: 'governance.environments_list',
          name: 'Ambientes',
          description: 'DEV, TEST, STAGING y PROD con su estado.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/environments',
          roles: ['PLATFORM_ADMIN', 'RISK_ANALYST', 'QA_ANALYST', 'AUDITOR'],
        },
        {
          code: 'governance.deploy',
          name: 'Desplegar la versión',
          description: 'Reparto de tráfico que suma 100; en producción exige contrato económico completo.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/artifact-versions/:versionId/deployments',
          roles: ['PLATFORM_ADMIN'],
          requiredStates: ['APPROVED'],
          resultingStates: ['DEPLOYED_TO_DEV', 'DEPLOYED_TO_TEST', 'DEPLOYED_TO_STAGING', 'DEPLOYED_TO_PROD'],
          errors: [
            '403 SEPARATION_OF_DUTIES_VIOLATION',
            '404 ENVIRONMENT_NOT_FOUND',
            '409 COMPILED_ARTIFACT_NOT_FOUND',
            'INVALID_TRAFFIC_PERCENTAGE',
            '409 ECONOMIC_CONTRACT_INCOMPLETE',
          ],
        },
        {
          code: 'governance.deployments_list',
          name: 'Despliegues',
          description: 'Despliegues activos y anteriores por ambiente.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/deployments',
          roles: ['PLATFORM_ADMIN', 'RISK_ANALYST', 'QA_ANALYST', 'COMPLIANCE', 'AUDITOR', 'OPERATIONS'],
        },
        {
          code: 'governance.deployment_rollback',
          name: 'Revertir',
          description: 'Reactiva el despliegue anterior, mueve el vínculo y devuelve la versión a APPROVED.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/deployments/:deploymentId/rollback',
          roles: ['PLATFORM_ADMIN'],
          optional: true,
          errors: ['ROLLBACK_TARGET_NOT_FOUND', 'DEPLOYMENT_NOT_ACTIVE'],
        },
        {
          code: 'governance.deployment_suspend',
          name: 'Suspender',
          description: 'Detiene un despliegue de producción: la versión pasa a SUSPENDED.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/deployments/:deploymentId/suspend',
          roles: ['PLATFORM_ADMIN'],
          optional: true,
          resultingStates: ['SUSPENDED'],
        },
      ],
    },
    {
      code: 'governance_atlas_binding',
      name: 'Elegir el artefacto en Atlas',
      description:
        'En el portal admin se elige qué artefacto (y versión fijada, si se quiere) decide cada tipo: crédito, identidad, riesgo. Atlas valida el código contra el catálogo que publica el Motor y rechaza el que no existe.',
      module: 'decision-engine',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/settings/decision-artifacts',
      terminal: true,
      roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      steps: [
        {
          code: 'governance.atlas_bindings_list',
          name: 'Ver la asignación vigente',
          description: 'Qué artefacto decide cada tipo y cuáles publica el Motor.',
          method: 'GET',
          path: '/internal/decision-artifacts',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
        },
        {
          code: 'governance.atlas_binding_assign',
          name: 'Asignar el artefacto',
          description: 'Guarda el código y la versión fijada, atribuidos a quien los eligió.',
          method: 'POST',
          path: '/internal/decision-artifacts',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          errors: ['422 DECISION_ARTIFACT_NOT_PUBLISHED'],
        },
        {
          code: 'governance.atlas_active_artifacts',
          name: 'Observar los artefactos activos',
          description:
            'Pantalla de sólo lectura del portal admin (/internal/systems/decision-engine/artifacts) con los despliegues activos y su reparto de tráfico.',
          method: 'GET',
          path: '/systems/decision-engine/artifacts',
          optional: true,
        },
      ],
    },
  ],
};
