/**
 * @file Proceso declarado en código: Calidad de decisiones: desenlaces observados, monitoreo de modelo y reclamaciones.
 * @business El Motor sólo sabe si acertó al aprobar o rechazar cuando le cuentan cómo terminó cada crédito: este proceso cierra ese bucle, mide la degradación de las políticas y permite responder a una reclamación con la decisión reproducida.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; AtlasBackend entrega créditos y desenlaces con dos jobs, AtlasDecisionEngineBackend los ingiere (outcome-ingestion), evalúa (model-monitoring) y audita (audit-query).
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const DECISION_QUALITY_AND_MONITORING: WorkflowDefinitionFixture = {
  processId: 'P-28',
  code: 'decision_quality_and_monitoring',
  version: 'v1',
  name: 'Calidad de decisiones: desenlaces observados, monitoreo de modelo y reclamaciones',
  description:
    'AtlasBackend registra en el Motor cada crédito desembolsado y, al vencer cada ventana, su desenlace (bueno, malo, rechazado que habría sido bueno…). El Motor cierra la ventana, calcula cosechas, cobertura, rendimiento, estabilidad e impacto adverso, evalúa cada 6 horas la degradación de lo desplegado, y deja reproducir una decisión concreta ante una reclamación.',
  processType: 'system_job',
  ownerDomain: 'decisioning',
  ownerRole: 'MOTOR:RISK_ANALYST',
  priority: 'P1',
  systems: ['ATLAS_BACKEND', 'DECISION_ENGINE'],
  narrative: {
    whyExists:
      'Una política de crédito puede degradarse sin que nadie lo note: el Motor sólo sabe si aprobar fue un acierto cuando le cuentan cómo terminó el crédito. Con esos desenlaces mide tasa de malos, estabilidad y discriminación, y ante una reclamación se puede recuperar y reproducir exactamente la decisión que se tomó.',
    whoStartsAndCloses:
      'Lo inician los trabajos de AtlasBackend register_engine_facilities y dispatch_loan_outcomes, como sistema; el Motor lo continúa con su evaluación periódica. Lo cierran personas del Motor: el analista de riesgo que revisa la calidad, cumplimiento o un aprobador de riesgo que mira el impacto adverso, y el auditor que responde a una reclamación.',
    startAndEnd:
      'Empieza cuando un crédito desembolsado se registra en el Motor (POST /v1/outcomes/facilities), que programa sus ventanas de observación, y cada desenlace entra por POST /v1/outcomes/batch cerrando su ventana. Termina con la evaluación de monitoreo guardada y, en una reclamación, con la ejecución recuperada y la cadena de auditoría verificada.',
    whenItFails:
      'Si la entrega al Motor falla, el lote entero no se marca enviado y se reintenta (el Motor deduplica por ejecución y ventana); tras seis intentos se deja de reintentar y se pide una mirada humana. Un desenlace para un crédito que el Motor no conoce se rechaza fila a fila. Sin desenlaces, la cobertura cae y la matriz de cosechas queda vacía.',
    healthIndicator:
      'Cobertura de desenlaces (GET /v1/model-monitoring/coverage) sin ventanas vencidas pendientes (GET /v1/outcomes/pending), estado de entrega de desenlaces al día en la cartera del portal admin, y evaluaciones de monitoreo sin alertas de deriva. Ojo: en local casi toda la población del Motor es siembra.',
  },
  instanceEntity: {
    system: 'DECISION_ENGINE',
    schema: 'public',
    table: 'decision_outcome_observation',
    idColumn: 'id',
    statusColumn: 'label',
    labelColumn: 'source',
  },
  success:
    'Cada crédito tiene sus desenlaces observados, las ventanas se cierran a tiempo y las métricas de calidad se calculan sobre población real.',
  failure: 'Los desenlaces no llegan (ventanas vencidas, cobertura en BREACH) o se calculan sobre población sembrada.',
  sources: [
    'AtlasDecisionEngineBackend/docs/business/critical-workflows.md §5',
    'AtlasDecisionEngineBackend/src/modules/outcome-ingestion/outcome-ingestion.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/model-monitoring/model-monitoring.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/model-monitoring/monitoring-evaluator.service.ts',
    'AtlasDecisionEngineBackend/src/modules/audit-query/audit-query.controller.ts',
    'AtlasDecisionEngineBackend/src/common/jobs/job-names.ts',
    'AtlasDecisionEngineBackend/prisma/schema.prisma (ObservedOutcomeLabel, OutcomeWindowSchedule)',
    'src/modules/decision-engine/outcome-dispatch.service.ts',
    'src/modules/decision-engine/decision-engine.client.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts',
    'AtlasAdminPortal/src/features/portfolio-operations/portfolio-delivery.tsx',
    'memoria atlas-datos-demo-en-base (métricas sobre siembra)',
    'memoria atlas-dashboards-plan (matriz de cosechas vacía)',
  ],
  metadata: {
    outcomeLabels: ['GOOD', 'BAD', 'REJECTED_WOULD_HAVE_BEEN_GOOD', 'REJECTED_CONFIRMED_BAD', '…'],
    gaps: [
      'El inventario da WOULD_HAVE_BEEN_GOOD; la etiqueta real es REJECTED_WOULD_HAVE_BEEN_GOOD (ObservedOutcomeLabel).',
      'Las ventanas pendientes (outcome_window_schedule) no tienen columna de estado: vencida sin observar = due_at pasado y observed_at nulo. Por eso la instancia es la observación (label), que nace ya cerrada.',
      'Casi toda la población del Motor local es siembra: las métricas son reales sobre datos inventados.',
      'POST /v1/model-monitoring/outcomes sigue en el cliente de AtlasBackend pero no cierra la ventana; el despacho usa /v1/outcomes/batch.',
    ],
  },
  stages: [
    {
      code: 'quality_facility_registration',
      name: 'Registrar los créditos desembolsados',
      description: 'AtlasBackend da de alta en el Motor cada crédito concedido; el Motor programa sus ventanas de observación.',
      module: 'decision-engine',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      steps: [
        {
          code: 'quality.register_facilities_job',
          name: 'Trabajo de registro de créditos',
          description: 'Va en su propio trabajo e intervalo, separado del despacho de desenlaces.',
          kind: 'job',
          job: 'register_engine_facilities',
        },
        {
          code: 'quality.facilities_register',
          name: 'Alta de créditos en el Motor',
          description: 'Devuelve el veredicto fila a fila y programa las ventanas de cada crédito.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/outcomes/facilities',
          roles: ['OPERATIONS', 'RISK_ANALYST'],
        },
      ],
    },
    {
      code: 'quality_outcome_dispatch',
      name: 'Entregar los desenlaces',
      description:
        'dispatch_loan_outcomes toma los desenlaces encolados por el libro de préstamos y los manda en lote; el lote es todo o nada al marcarlo y se reintenta hasta seis veces.',
      module: 'decision-engine',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'quality.dispatch_outcomes_job',
          name: 'Trabajo de despacho de desenlaces',
          description: 'Lee loan_outcome_reports pendientes y los entrega; tras MAX_ATTEMPTS pide mirada humana.',
          kind: 'job',
          job: 'dispatch_loan_outcomes',
        },
        {
          code: 'quality.outcomes_batch',
          name: 'Cargar desenlaces por crédito',
          description: 'Escribe la observación y marca la ventana como observada; responde el veredicto de cada fila.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/outcomes/batch',
          roles: ['OPERATIONS', 'RISK_ANALYST', 'COMPLIANCE'],
          repeatable: true,
        },
        {
          code: 'quality.outcomes_by_execution',
          name: 'Cargar desenlaces por ejecución (camino antiguo)',
          description: 'Guarda la observación por executionId pero no cierra la ventana; se mantiene por compatibilidad.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/model-monitoring/outcomes',
          roles: ['OPERATIONS', 'RISK_ANALYST', 'COMPLIANCE'],
          optional: true,
        },
      ],
    },
    {
      code: 'quality_monitoring_evaluation',
      name: 'Evaluar la degradación',
      description:
        'El Motor mide cada 6 horas (MONITORING_EVALUATION_INTERVAL_MS) la degradación de las versiones desplegadas y guarda su veredicto.',
      module: 'model-monitoring',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'quality.monitoring_evaluation_job',
          name: 'Evaluación periódica',
          description: 'Existe porque un cálculo que sólo ocurre cuando alguien pregunta es un cálculo que no ocurre.',
          kind: 'job',
          system: 'DECISION_ENGINE',
          job: 'monitoring-evaluation',
        },
      ],
    },
    {
      code: 'quality_admin_delivery_status',
      name: 'Atlas vigila la entrega',
      description:
        'La pantalla de cartera del portal admin dice si la entrega de desenlaces va al día y enlaza a «Calidad de decisiones» del Motor.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/portfolio',
      link: '{MOTOR}/decision-quality',
      optional: true,
      steps: [
        {
          code: 'quality.admin_outcome_status',
          name: 'Estado de entrega de desenlaces',
          description: 'Sustituye a los botones «Entregar desenlaces»: son trabajos, la pantalla sólo dice si van al día.',
          method: 'GET',
          path: '/operations/loans/outcome-status',
          optional: true,
        },
      ],
    },
    {
      code: 'quality_review',
      name: 'Revisar la calidad de las decisiones',
      description: 'El analista mira ventanas pendientes, cosechas, cobertura de desenlaces y el análisis de corte.',
      module: 'outcome-ingestion',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/decision-quality',
      roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER', 'OPERATIONS'],
      steps: [
        {
          code: 'quality.outcomes_pending',
          name: 'Ventanas pendientes',
          description: 'Créditos cuya ventana de observación venció sin desenlace.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/outcomes/pending',
          roles: ['OPERATIONS', 'RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
        },
        {
          code: 'quality.outcomes_vintage',
          name: 'Matriz de cosechas',
          description: 'Tasa de malos por mes de desembolso y antigüedad.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/outcomes/vintage',
          roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
        },
        {
          code: 'quality.monitoring_coverage',
          name: 'Cobertura de desenlaces',
          description: 'Qué parte de las decisiones tiene desenlace observado.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/model-monitoring/coverage',
          roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER', 'OPERATIONS'],
        },
        {
          code: 'quality.cutoff_analysis',
          name: 'Análisis de corte',
          description: 'Qué pasaría moviendo el umbral de aprobación.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/model-monitoring/cutoff-analysis',
          roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
          optional: true,
        },
      ],
    },
    {
      code: 'quality_model_monitoring',
      name: 'Monitoreo del modelo',
      description:
        'Rendimiento, estabilidad de la población, comparación A/B e impacto adverso por atributo protegido (los atributos los carga cumplimiento).',
      module: 'model-monitoring',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/model-monitoring',
      roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
      steps: [
        {
          code: 'quality.monitoring_performance',
          name: 'Rendimiento',
          description: 'Tasa de aprobación y de malos de la versión.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/model-monitoring/performance',
          roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
        },
        {
          code: 'quality.monitoring_stability',
          name: 'Estabilidad',
          description: 'Índice de estabilidad de la población (PSI) frente a la línea base.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/model-monitoring/stability',
          roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
        },
        {
          code: 'quality.monitoring_ab',
          name: 'Comparación A/B',
          description: 'Versiones que comparten tráfico en el mismo ambiente.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/model-monitoring/ab',
          roles: ['RISK_ANALYST', 'COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
          optional: true,
        },
        {
          code: 'quality.monitoring_attributes',
          name: 'Cargar atributos protegidos',
          description: 'Sólo cumplimiento: los atributos con los que se mide el impacto adverso.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/model-monitoring/attributes',
          roles: ['COMPLIANCE'],
          optional: true,
        },
        {
          code: 'quality.monitoring_adverse_impact',
          name: 'Impacto adverso',
          description: 'Razón de impacto adverso por atributo.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/model-monitoring/adverse-impact',
          roles: ['COMPLIANCE', 'AUDITOR', 'RISK_APPROVER'],
        },
      ],
    },
    {
      code: 'quality_claim_response',
      name: 'Responder a una reclamación',
      description:
        'Se localiza la ejecución por requestId o referencia del sujeto, se recuperan sus variables, la ruta recorrida y las razones, y se verifica la cadena de auditoría del tenant. El compilado es inmutable, así que la decisión se puede reproducir.',
      module: 'audit-query',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/executions/[executionId]',
      optional: true,
      terminal: true,
      roles: ['AUDITOR', 'COMPLIANCE', 'RISK_ANALYST', 'OPERATIONS'],
      steps: [
        {
          code: 'quality.audit_executions',
          name: 'Buscar la ejecución',
          description: 'Por requestId o referencia del sujeto.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/audit/executions',
          roles: ['AUDITOR', 'COMPLIANCE', 'RISK_ANALYST', 'OPERATIONS'],
          optional: true,
        },
        {
          code: 'quality.audit_execution_get',
          name: 'Recuperar la ejecución',
          description: 'Instantánea de variables, traza y razones.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/audit/executions/:executionId',
          roles: ['AUDITOR', 'COMPLIANCE', 'RISK_ANALYST', 'OPERATIONS'],
          optional: true,
        },
        {
          code: 'quality.audit_chain_verify',
          name: 'Verificar la cadena de auditoría',
          description: 'Comprueba que la cadena de eventos del tenant no se alteró.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/audit/chain/verify',
          roles: ['AUDITOR', 'COMPLIANCE', 'RISK_ANALYST', 'OPERATIONS'],
          optional: true,
        },
      ],
    },
  ],
};
