/**
 * @file Proceso declarado en código: Proveedores externos: salud, kill-switch, credenciales, auditorías y compuerta de producción.
 * @business Las consultas a terceros (identidad, buró, telco, pagos) cuestan dinero, llevan datos personales y pueden caerse; este proceso las vigila, permite cortarlas al instante, rota sus credenciales y decide si un proveedor está listo para producción.
 * @system fixture P-36 que `syncWorkflowCatalog` vuelca a `workflow_*`; `external-data.controller.ts` (`external-data` y `admin/external-providers`), `provider-auth.controller.ts` y `external-providers-dashboard.controller.ts`; en dev/test responde el mock de proveedores.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** Roles de clase de `admin/external-providers`. */
const PROVIDERS_ADMIN_READ = ['admin', 'platform_admin', 'risk_analyst', 'compliance_analyst'];
/** Acciones que cambian el runtime, la política de coste, las credenciales o aprueban una solicitud. */
const PROVIDERS_ADMIN_WRITE = ['admin', 'platform_admin'];
/** Roles de clase de `external-data`. */
const EXTERNAL_DATA = [
  'customer',
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'fraud_analyst',
  'admin',
  'platform_admin',
  'system',
];

export const EXTERNAL_PROVIDERS_OPERATIONS: WorkflowDefinitionFixture = {
  processId: 'P-36',
  code: 'external_providers_operations',
  version: 'v1',
  name: 'Proveedores externos: salud, kill-switch, credenciales, auditorías y compuerta de producción',
  description:
    'Operación de los proveedores de datos externos: una solicitud sale al proveedor (o al mock en dev/test), el administrador vigila salud, SLA y uso, ajusta el modo de cada proveedor, corta con el kill-switch, rota o revoca credenciales, atiende solicitudes que piden aprobación o reintento, y revisa las auditorías y la compuerta de producción.',
  processType: 'back_office',
  ownerDomain: 'platform',
  ownerRole: 'SYSTEMS_ADMIN',
  priority: 'P2',
  systems: ['ATLAS_BACKEND', 'EXTERNAL_PROVIDERS_MOCK'],
  narrative: {
    whyExists:
      'Las consultas a terceros de identidad, buró, telco, pagos o redes cuestan dinero, llevan datos personales y pueden caerse: hace falta ver su salud, poder cortarlas al instante, rotar sus credenciales, auditar idempotencia y saneamiento, y una compuerta que diga si un proveedor está listo para producción.',
    whoStartsAndCloses:
      'Lo inicia el sistema al pedir datos a un proveedor durante un proceso de cliente; lo opera un administrador (rol de sesión admin o platform_admin) o un analista de riesgo o cumplimiento en modo lectura, y lo cierra el administrador al aprobar, reintentar o dar por lista la compuerta de producción.',
    startAndEnd:
      'Empieza con una solicitud de datos externos por proveedor y termina con su respuesta registrada y el estado del proveedor (modo mock, sandbox o live, o cortado por kill-switch) al día, credenciales vigentes y la compuerta de producción revisada.',
    whenItFails:
      'Un proveedor caído o lento se ve en salud y SLA; el kill-switch lo corta sin desplegar; una solicitud que exige aprobación manual espera en «Solicitudes» y una fallida se reintenta o se reconstruyen sus rasgos. En dev y test responden nueve adaptadores de prueba a propósito, y el tablero llegó a mostrar «Responde · 0 ms» sin medir nada.',
    healthIndicator:
      'Proveedores sanos frente a degradados, cumplimiento de SLA, coste de uso, credenciales pendientes de rotación y el veredicto de la compuerta de producción; todo en «Proveedores externos» y sus pestañas de auditoría.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'integrations',
    table: 'data_providers',
    idColumn: '_id',
    statusColumn: 'provider_status',
    labelColumn: 'provider_code',
  },
  success:
    'Cada proveedor responde con su modo correcto, sus credenciales están vigentes y la compuerta de producción dice si puede pasar a live.',
  failure: 'Un proveedor caído o caro sigue recibiendo consultas, una credencial expira sin rotar, o se pasa a producción sin compuerta.',
  sources: [
    'src/modules/external-data/external-data.controller.ts',
    'src/modules/external-data/controllers/provider-auth.controller.ts',
    'src/modules/external-data/controllers/external-providers-dashboard.controller.ts',
    'src/database/models/data-providers.model.ts',
    'memoria atlas-conectores-externos-mock',
    'memoria atlas-mock-proveedores-externos',
    'memoria atlas-portal-tablero-proveedores',
    '_plan-documentar-procesos-y-cableado-portal-2026-09-26/datos/procesos.json (P-36)',
  ],
  stages: [
    {
      code: 'provider_request',
      name: 'Solicitud al proveedor',
      description: 'Un proceso de cliente pide datos externos; con consentimiento, la solicitud sale al proveedor (o al mock en dev/test).',
      module: 'external_data',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      roles: EXTERNAL_DATA,
      steps: [
        {
          code: 'providers.request_preview',
          name: 'Previsualizar la solicitud',
          description: 'Qué proveedores y qué coste tendría la consulta.',
          method: 'POST',
          path: '/external-data/requests/preview',
          roles: EXTERNAL_DATA,
          optional: true,
        },
        {
          code: 'providers.create_request',
          name: 'Crear la solicitud de datos',
          description: 'Registra la solicitud y la envía a cada proveedor según su modo.',
          method: 'POST',
          path: '/external-data/requests',
          roles: EXTERNAL_DATA,
        },
        {
          code: 'providers.provider_call',
          name: 'Llamada al proveedor',
          description: 'El adaptador llama al proveedor real o al mock; la URL del mock lleva /mock.',
          kind: 'external',
          system: 'EXTERNAL_PROVIDERS_MOCK',
          reason: 'Es la llamada saliente al tercero (o al repo AtlasExternalProvidersMock en dev/test), no una ruta de Atlas.',
        },
      ],
    },
    {
      code: 'provider_monitoring',
      name: 'Salud, SLA y uso',
      description: 'El administrador vigila el tablero de proveedores: salud, disponibilidad, SLA, uso y coste.',
      module: 'external_data',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/external-providers',
      roles: PROVIDERS_ADMIN_READ,
      steps: [
        {
          code: 'providers.dashboard',
          name: 'Ver el tablero',
          description: 'Resumen por proveedor.',
          method: 'GET',
          path: '/admin/external-providers/dashboard',
          roles: PROVIDERS_ADMIN_READ,
        },
        {
          code: 'providers.health',
          name: 'Ver la salud',
          description: 'Estado de cada proveedor.',
          method: 'GET',
          path: '/admin/external-providers/health',
          roles: PROVIDERS_ADMIN_READ,
        },
        {
          code: 'providers.sla',
          name: 'Ver el SLA',
          description: 'Cumplimiento de tiempos por proveedor.',
          method: 'GET',
          path: '/admin/external-providers/sla',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
        {
          code: 'providers.usage',
          name: 'Ver el uso',
          description: 'Consultas y coste por proveedor.',
          method: 'GET',
          path: '/admin/external-providers/usage',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
      ],
    },
    {
      code: 'provider_runtime_control',
      name: 'Modo y kill-switch',
      description: 'El administrador cambia el modo de un proveedor, lo prueba, ajusta su política de coste o lo corta con el kill-switch.',
      module: 'external_data',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/external-providers',
      roles: PROVIDERS_ADMIN_WRITE,
      steps: [
        {
          code: 'providers.update_runtime',
          name: 'Cambiar el modo del proveedor',
          description: 'mock, sandbox o live y demás parámetros de ejecución.',
          method: 'PATCH',
          path: '/admin/external-providers/:providerCode/runtime',
          roles: PROVIDERS_ADMIN_WRITE,
        },
        {
          code: 'providers.kill_switch',
          name: 'Cortar el proveedor',
          description:
            'Kill-switch: deja default_mode en disabled y provider_status en DISABLED al instante, sin desplegar; lo puede pulsar también un analista de riesgo o cumplimiento.',
          method: 'POST',
          path: '/admin/external-providers/:providerCode/kill-switch',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
          resultingStates: ['DISABLED'],
        },
        {
          code: 'providers.test',
          name: 'Probar el proveedor',
          description: 'Lanza una consulta de prueba.',
          method: 'POST',
          path: '/admin/external-providers/:providerCode/test',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
        {
          code: 'providers.cost_policy',
          name: 'Ajustar la política de coste',
          description: 'Límites de coste por tipo de consulta.',
          method: 'PATCH',
          path: '/admin/external-providers/:providerCode/cost-policy/:queryType',
          roles: PROVIDERS_ADMIN_WRITE,
          optional: true,
        },
      ],
    },
    {
      code: 'provider_credentials',
      name: 'Credenciales',
      description: 'El administrador ve qué credenciales están por rotar y las rota, revoca o invalida su token.',
      module: 'external_data',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/external-providers',
      optional: true,
      roles: PROVIDERS_ADMIN_WRITE,
      steps: [
        {
          code: 'providers.pending_rotation',
          name: 'Credenciales por rotar',
          description: 'Lista de credenciales vencidas o por vencer.',
          method: 'GET',
          path: '/admin/external-providers/credentials/pending-rotation',
          roles: PROVIDERS_ADMIN_READ,
        },
        {
          code: 'providers.rotate_credentials',
          name: 'Rotar credenciales',
          description: 'Sustituye la credencial del proveedor.',
          method: 'POST',
          path: '/admin/external-providers/:providerCode/credentials/rotate',
          roles: PROVIDERS_ADMIN_WRITE,
        },
        {
          code: 'providers.revoke_credentials',
          name: 'Revocar credenciales',
          description: 'Revoca la credencial vigente.',
          method: 'POST',
          path: '/admin/external-providers/:providerCode/credentials/revoke',
          roles: PROVIDERS_ADMIN_WRITE,
          optional: true,
        },
        {
          code: 'providers.invalidate_token',
          name: 'Invalidar el token',
          description: 'Fuerza a pedir un token nuevo.',
          method: 'POST',
          path: '/admin/external-providers/:providerCode/credentials/invalidate-token',
          roles: PROVIDERS_ADMIN_WRITE,
          optional: true,
        },
      ],
    },
    {
      code: 'provider_requests_follow_up',
      name: 'Solicitudes pendientes',
      description: 'El administrador aprueba las solicitudes que exigen aprobación manual y reintenta o reconstruye las fallidas.',
      module: 'external_data',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/external-providers/requests',
      optional: true,
      roles: PROVIDERS_ADMIN_READ,
      steps: [
        {
          code: 'providers.list_requests',
          name: 'Listar solicitudes',
          description: 'Solicitudes por proveedor y estado.',
          method: 'GET',
          path: '/admin/external-providers/requests',
          roles: PROVIDERS_ADMIN_READ,
        },
        {
          code: 'providers.approve_request',
          name: 'Aprobar una solicitud',
          description: 'Para proveedores con requires_manual_approval.',
          method: 'POST',
          path: '/admin/external-providers/requests/:requestId/approve',
          roles: PROVIDERS_ADMIN_WRITE,
          optional: true,
        },
        {
          code: 'providers.retry_request',
          name: 'Reintentar una solicitud',
          description: 'Vuelve a llamar al proveedor.',
          method: 'POST',
          path: '/admin/external-providers/requests/:requestId/retry',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
        {
          code: 'providers.rebuild_features',
          name: 'Reconstruir rasgos',
          description: 'Recalcula los rasgos derivados de la respuesta.',
          method: 'POST',
          path: '/admin/external-providers/requests/:requestId/rebuild-features',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
      ],
    },
    {
      code: 'provider_audits_and_gate',
      name: 'Auditorías y compuerta de producción',
      description:
        'El administrador revisa calidad, idempotencia y saneamiento y la compuerta que dice si un proveedor puede pasar a live.',
      module: 'external_data',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/external-providers/audits',
      terminal: true,
      roles: PROVIDERS_ADMIN_READ,
      steps: [
        {
          code: 'providers.quality_audit',
          name: 'Auditoría de calidad',
          description: 'Calidad de las respuestas por proveedor.',
          method: 'GET',
          path: '/admin/external-providers/quality-audit',
          roles: PROVIDERS_ADMIN_READ,
        },
        {
          code: 'providers.idempotency_audit',
          name: 'Auditoría de idempotencia',
          description: 'Solicitudes duplicadas o sin clave.',
          method: 'GET',
          path: '/admin/external-providers/idempotency-audit',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
        {
          code: 'providers.sanitization_audit',
          name: 'Auditoría de saneamiento',
          description: 'Datos personales que no deberían guardarse en claro.',
          method: 'GET',
          path: '/admin/external-providers/sanitization-audit',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
        {
          code: 'providers.readiness',
          name: 'Preparación por proveedor',
          description: 'Qué le falta a cada proveedor.',
          method: 'GET',
          path: '/admin/external-providers/readiness',
          roles: PROVIDERS_ADMIN_READ,
          optional: true,
        },
        {
          code: 'providers.production_gate',
          name: 'Compuerta de producción',
          description: 'Veredicto de si el proveedor puede operar en live.',
          method: 'GET',
          path: '/admin/external-providers/production-gate',
          roles: PROVIDERS_ADMIN_READ,
        },
      ],
    },
  ],
  metadata: {
    gaps: [
      'El inventario pone de dueño PLATFORM_ADMIN, que no es un rol interno; se usa SYSTEMS_ADMIN. El rol de sesión platform_admin no lo emite ningún usuario interno: en la práctica escribe «admin».',
      'Las 11 rutas admin/external-providers/* aparecen sin llamador en el artefacto porque el portal las construye con una constante BASE: falso positivo conocido.',
      'Pantallas sin gate de permiso.',
      'El inventario dice mock/sandbox/live/kill_switch; el código usa provider_status ACTIVE/DEGRADED/DISABLED/MOCK_ONLY/SANDBOX_ONLY más default_mode (el kill-switch deja DISABLED + disabled).',
    ],
  },
};
