/**
 * @file Proceso declarado en código: Verificación de identidad (carnet + selfie) con el Motor y arbitraje humano.
 * @business Sin saber que la persona es quien dice ser no se le puede prestar: este proceso compara su carnet con su selfie mediante una política versionada del Motor y, cuando la máquina duda, deja la última palabra a una persona.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; instancias en `customer.identity_verification_attempts`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const CUSTOMER_AND_INTERNAL = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const INVESTIGATION_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'];
const EVIDENCE_VIEW_ROLES = ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const MOTOR_REVIEW_ROLES = ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'];

export const IDENTITY_VERIFICATION: WorkflowDefinitionFixture = {
  processId: 'P-03',
  code: 'identity_verification',
  version: 'v1',
  name: 'Verificación de identidad (carnet + selfie) con el Motor y arbitraje humano',
  description:
    'La app registra el carnet y la selfie en el expediente y pregunta al Motor si la persona es quien dice ser. El artefacto IDENTIDAD_CARNET_MOVIL responde verificado, rechazado o revisión humana; en el último caso un analista resuelve en la cola IDENTIDAD del Motor y la resolución vuelve a Atlas por un aviso firmado con clave de servicio.',
  processType: 'integration',
  ownerDomain: 'customer_onboarding',
  ownerRole: 'RISK_ANALYST',
  priority: 'P0',
  systems: ['ATLAS_BACKEND', 'DECISION_ENGINE'],
  narrative: {
    whyExists:
      'Prestar a alguien que no es quien dice ser es la pérdida más directa del negocio. Una foto del carnet sola no prueba nada, así que la decisión cruza el documento, su autenticidad, el parecido con la selfie, el registro estatal, la agenda y cómo se hizo el alta, y la política que decide vive versionada en el Motor para poder cambiarla sin publicar la app.',
    whoStartsAndCloses:
      'Lo inicia el cliente desde la app al enviar anverso, dorso y selfie. Lo cierra el Motor de forma automática (verificado o rechazado) o, cuando deriva a revisión humana, un analista de riesgo, fraude u operaciones que resuelve el caso en la cola IDENTIDAD del portal del Motor; un analista interno de Atlas sólo decide intentos que el Motor no delegó.',
    startAndEnd:
      'Empieza cuando la app envía las imágenes y recibe un identificador con el estado PENDING (la respuesta no espera al veredicto). Termina cuando el intento queda VERIFIED o REJECTED: en el acto si decide el Motor, o cuando llega el aviso de la revisión humana, que además mueve al cliente a activo u observado. La app consulta el estado en bucle hasta ver un veredicto.',
    whenItFails:
      'Si el Motor no responde, el intento queda UNAVAILABLE, que no es un rechazo y la app no debe pintarlo como tal; sin Motor configurado la petición responde 503. Si el aviso de vuelta falla, la resolución del analista se conserva en el Motor y el fallo queda en su auditoría, pero el intento sigue IN_REVIEW en Atlas. El veredicto de una persona (callback del Motor o decisión interna) avisa al cliente con kyc.approved o kyc.rejected por el outbox; el que el Motor decide en el acto no emite aviso: la app lo ve al consultar el estado.',
    healthIndicator:
      'Reparto de final_result en identity_verification_attempts (VERIFIED, REJECTED, IN_REVIEW, UNAVAILABLE) y antigüedad de los intentos que siguen IN_REVIEW con executionId del Motor; un IN_REVIEW que envejece con el caso ya resuelto en el Motor delata un aviso perdido. La tasa de UNAVAILABLE mide la disponibilidad del Motor, no el fraude.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'customer',
    table: 'identity_verification_attempts',
    idColumn: '_id',
    statusColumn: 'final_result',
    labelColumn: 'customer_id',
    openStatuses: ['PENDING', 'IN_REVIEW', 'UNAVAILABLE', 'pending_review'],
  },
  success:
    'El intento de identidad queda VERIFIED (o REJECTED con motivo) y, si pasó por una persona, el expediente del cliente refleja su decisión.',
  failure:
    'El intento se queda en PENDING, UNAVAILABLE o IN_REVIEW sin que nadie lo resuelva, o la resolución del Motor no vuelve a Atlas.',
  sources: [
    'src/modules/mobile-identity/mobile-identity.controller.ts',
    'src/modules/mobile-identity/mobile-identity.service.ts',
    'src/modules/mobile-identity/mobile-identity.schemas.ts',
    'src/modules/customer-onboarding/identity-review-callback.controller.ts',
    'src/modules/customer-onboarding/application/identity-manual-review-outcome.service.ts',
    'src/modules/customer-onboarding/customer-verification.controller.ts',
    'src/modules/customer-onboarding/application/customer-verification.service.ts',
    'src/modules/customer-onboarding/customer-onboarding-profile.controller.ts',
    'src/modules/customer-onboarding/customer-onboarding.controller.ts',
    'src/modules/customer-onboarding/customer-evidence-view.controller.ts',
    'src/common/utils/identity/identity-result.util.ts',
    'src/modules/notifications/notification-rules.service.ts',
    'AtlasDecisionEngineBackend/src/modules/manual-review/manual-review.service.ts',
    'AtlasDecisionEngineBackend/docs/artifacts/identidad-carnet-movil.md',
    'AtlasAdminPortal/src/features/operations-cases/identity-evidence-panel.tsx',
    'AtlasFrontend/apps/consumer-app/src/api/endpoints/identity-engine.ts',
    'memoria atlas-identidad-cola-humana',
    'memoria atlas-escaner-carnet-implementado',
    'memoria atlas-fraude-documental-identidad',
    'memoria atlas-motor-imagenes-persistidas',
    'memoria atlas-motor-evidencia-obligatoria',
    '_plan-escaner-carnet-2026-09-26/plan.md',
  ],
  stages: [
    {
      code: 'identity_evidence_registration',
      name: 'Registro del carnet y la selfie en el expediente',
      description:
        'La app sube las imágenes al almacén con un permiso firmado y registra el paquete de identidad. Es el registro de la evidencia; todavía no pregunta si la persona es quien dice ser.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      steps: [
        {
          code: 'identity.upload_url',
          name: 'Pedir permiso de subida de cada imagen',
          description: 'Devuelve la clave y la URL firmada donde subir anverso, dorso o selfie.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/documents/upload-url',
          roles: CUSTOMER_AND_INTERNAL,
          repeatable: true,
          errors: ['422 PROFILE_NOT_EDITABLE_IN_STATUS', '422 EVIDENCE_OBJECT_TOO_LARGE', '503 DOCUMENT_STORAGE_NOT_CONFIGURED'],
          successStatus: [201],
        },
        {
          code: 'identity.package',
          name: 'Entregar el paquete de identidad',
          description:
            'Registra documentos y selfie con su origen de captura (cámara o escáner del sistema) y deja el documento en revisión.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-package',
          roles: CUSTOMER_AND_INTERNAL,
          idempotencyKey: true,
          errors: ['422 CUSTOMER_BLOCKED', '422 REQUIRED_EVIDENCE_MISSING', '422 REQUIRED_CONSENT_MISSING'],
          successStatus: [202],
        },
      ],
    },
    {
      code: 'identity_engine_request',
      name: 'Pregunta al Motor',
      description:
        'La app envía carnet y selfie para que el Motor decida. La respuesta llega enseguida con un identificador y estado PENDING: el veredicto se calcula después.',
      module: 'mobile_identity',
      actor: 'customer',
      client: 'CONSUMER_APP',
      steps: [
        {
          code: 'identity.mobile_start',
          name: 'Enviar carnet y selfie para verificar',
          description:
            'Crea el intento en PENDING y lanza la llamada al Motor sin esperarla. El cliente sale del token, no del cuerpo. Tope de cinco intentos por minuto.',
          method: 'POST',
          path: '/mobile/identity-verifications',
          roles: CUSTOMER_AND_INTERNAL,
          idempotencyKey: true,
          resultingStates: ['PENDING'],
          errors: ['400 VALIDATION_ERROR', '503 DECISION_ENGINE_NOT_CONFIGURED'],
          successStatus: [202],
        },
      ],
    },
    {
      code: 'identity_engine_decision',
      name: 'Decisión automática del Motor',
      description:
        'El artefacto de identidad asignado (IDENTIDAD_CARNET_MOVIL por omisión) llama al worker de identidad y aplica su política: VERIFICADO, RECHAZADO o REVISION_HUMANA, que abre un caso en la cola IDENTIDAD.',
      module: 'decision_engine',
      actor: 'system',
      client: 'BLOCK',
      link: '{MOTOR}/workers/identity-verification',
      resultingStates: ['VERIFIED', 'REJECTED', 'IN_REVIEW', 'UNAVAILABLE'],
      steps: [
        {
          code: 'identity.engine_execute',
          name: 'Ejecutar el artefacto de identidad',
          description:
            'Atlas manda las imágenes y las señales del registro estatal, la agenda y la bitácora del alta. Sin reintentos y con plazo propio; un fallo deja el intento UNAVAILABLE, nunca REJECTED.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
          resultingStates: ['VERIFIED', 'REJECTED', 'IN_REVIEW', 'UNAVAILABLE'],
        },
        {
          code: 'identity.engine_worker',
          name: 'Lectura, autenticidad y comparación de rostros',
          description:
            'El worker lee el carnet, comprueba que es un documento auténtico y compara su retrato con la selfie. Guarda las imágenes en el almacén del Motor como evidencia del caso.',
          kind: 'external',
          system: 'DECISION_ENGINE',
          reason: 'Lo invoca el propio grafo del artefacto dentro del Motor; Atlas no hace una llamada HTTP separada al worker.',
        },
      ],
    },
    {
      code: 'identity_result_polling',
      name: 'Consulta del resultado',
      description:
        'La app pregunta por el identificador hasta ver un veredicto. IN_REVIEW significa que lo mira una persona; UNAVAILABLE, que no se pudo preguntar al Motor.',
      module: 'mobile_identity',
      actor: 'customer',
      client: 'CONSUMER_APP',
      terminal: true,
      steps: [
        {
          code: 'identity.mobile_status',
          name: 'Consultar el estado de la verificación',
          description: 'Devuelve estado, motivo, parecido y los datos leídos del carnet para que la persona los confirme.',
          method: 'GET',
          path: '/mobile/identity-verifications/:verificationId',
          roles: CUSTOMER_AND_INTERNAL,
          repeatable: true,
          errors: ['404 IDENTITY_VERIFICATION_NOT_FOUND'],
        },
      ],
    },
    {
      code: 'identity_registry_check',
      name: 'Contraste con el registro estatal',
      description:
        'Camino del proveedor: consulta el registro estatal con los datos declarados. FOUND verifica, NOT_FOUND rechaza y devuelve al cliente a observado, y una coincidencia parcial o una caída del proveedor deja el intento pending_review para un analista.',
      module: 'customer_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      optional: true,
      steps: [
        {
          code: 'identity.registry_verify',
          name: 'Verificar la identidad contra el registro externo',
          description: 'El número de documento se usa para consultar y no se guarda; debe coincidir por huella con el del paquete.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-verification',
          roles: CUSTOMER_AND_INTERNAL,
          idempotencyKey: true,
          optional: true,
          resultingStates: ['verified', 'rejected', 'pending_review'],
          errors: [
            '422 IDENTITY_PACKAGE_REQUIRED',
            '422 IDENTITY_ALREADY_VERIFIED',
            '422 DOCUMENT_NUMBER_MISMATCH',
            '422 PROFILE_INCOMPLETE_FOR_VERIFICATION',
          ],
        },
      ],
    },
    {
      code: 'identity_motor_human_review',
      name: 'Revisión humana en la cola IDENTIDAD del Motor',
      description:
        'Un analista abre el caso, mira las imágenes guardadas y resuelve. Sólo la resolución de esta cola avisa a Atlas; la bandeja de revisiones del worker etiqueta el corpus pero no cierra el intento.',
      module: 'decision_engine',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      link: '{MOTOR}/manual-reviews',
      optional: true,
      roles: MOTOR_REVIEW_ROLES,
      requiredStates: ['IN_REVIEW'],
      steps: [
        {
          code: 'identity.motor_cases',
          name: 'Listar los casos abiertos',
          description: 'Cola de revisión del Motor, ordenada por prioridad y vencimiento; se filtra por la cola IDENTIDAD.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/manual-reviews',
          roles: MOTOR_REVIEW_ROLES,
        },
        {
          code: 'identity.motor_case_detail',
          name: 'Abrir el caso',
          description: 'Detalle del caso con la ejecución que lo abrió y su motivo.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/manual-reviews/:caseId',
          roles: MOTOR_REVIEW_ROLES,
        },
        {
          code: 'identity.motor_images',
          name: 'Ver las imágenes de la ejecución',
          description: 'Anverso, dorso y selfie servidos por el Motor con autorización por tenant y rol, sin URL prefirmada.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/identity-verification/runs/:requestId/images/:kind',
        },
        {
          code: 'identity.motor_assign',
          name: 'Tomar o asignar el caso',
          description: 'Sin destinatario el caso queda a nombre de quien llama; reasignar el de otro exige rol de supervisión.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/assign',
          roles: MOTOR_REVIEW_ROLES,
          errors: ['403 MANUAL_REVIEW_ASSIGN_FORBIDDEN'],
        },
        {
          code: 'identity.motor_resolve',
          name: 'Resolver el caso',
          description:
            'APPROVE o DECLINE del analista asignado (o supervisión). Tras confirmar, el Motor avisa a Atlas; CANCEL no se aplica.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/resolve',
          roles: MOTOR_REVIEW_ROLES,
        },
      ],
    },
    {
      code: 'identity_review_callback',
      name: 'Vuelta de la resolución a Atlas',
      description:
        'El Motor avisa con clave de servicio y el executionId; Atlas resuelve exactamente ese intento, su documento y todas sus evidencias pendientes, y mueve al cliente a activo u observado.',
      module: 'customer_onboarding',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      resultingStates: ['VERIFIED', 'REJECTED'],
      steps: [
        {
          code: 'identity.review_callback',
          name: 'Aplicar la resolución del Motor',
          description: 'Autenticado con x-engine-callback-key, no con sesión. Sin clave configurada responde 401 en vez de quedar abierto.',
          method: 'POST',
          path: '/internal/identity/manual-review-callback',
          auth: false,
          requiredStates: ['IN_REVIEW'],
          resultingStates: ['VERIFIED', 'REJECTED'],
          errors: [
            '400 Falta executionId',
            '401 Credencial de servicio invalida',
            '404 intento no encontrado',
            '422 IDENTITY_ATTEMPT_WITHOUT_CUSTOMER',
          ],
          events: ['kyc.approved', 'kyc.rejected'],
        },
      ],
    },
    {
      code: 'identity_atlas_review',
      name: 'Decisión de identidad desde el portal admin',
      description:
        'El analista interno mira las evidencias en el resumen de investigación del cliente y aprueba o rechaza en bloque. Sólo vale para intentos que el Motor no delegó: si el Motor abrió caso responde 409 y se resuelve allí.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/customers/[customerId]/investigation-summary',
      optional: true,
      roles: INVESTIGATION_ROLES,
      requiredStates: ['pending_review', 'UNAVAILABLE'],
      steps: [
        {
          code: 'identity.investigation_summary',
          name: 'Abrir el resumen de investigación',
          description: 'Expediente del cliente con su intento de identidad y bloqueadores.',
          method: 'GET',
          path: '/operations/customers/:customerId/investigation-summary',
          roles: INVESTIGATION_ROLES,
        },
        {
          code: 'identity.evidence_list',
          name: 'Listar las evidencias de identidad',
          description: 'Documentos de identidad subidos por el cliente.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/evidence-documents',
          roles: EVIDENCE_VIEW_ROLES,
        },
        {
          code: 'identity.evidence_content',
          name: 'Ver los bytes de una evidencia',
          description: 'Descarga autenticada de la imagen; un enlace directo no llevaría la credencial.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/evidence-documents/:documentId/content',
          roles: EVIDENCE_VIEW_ROLES,
        },
        {
          code: 'identity.admin_decision',
          name: 'Aprobar o rechazar la identidad',
          description:
            'Resuelve intento, documento y evidencias pendientes y reevalúa la elegibilidad en la misma transacción. Aprobar no habilita al cliente por sí solo.',
          method: 'POST',
          path: '/operations/customers/:customerId/identity-verification/decision',
          roles: INVESTIGATION_ROLES,
          resultingStates: ['verified', 'rejected'],
          errors: ['404 IDENTITY_VERIFICATION_ATTEMPT_NOT_FOUND', '409 IDENTITY_DECISION_DELEGADA_AL_MOTOR'],
          events: ['kyc.approved', 'kyc.rejected'],
        },
      ],
    },
    {
      code: 'identity_manual_apply',
      name: 'Aplicar a mano una resolución de revisión',
      description:
        'Ruta para que un analista aplique al expediente una decisión humana indicando quién la tomó. No la llama ninguna pantalla: el aviso del Motor la sustituyó en el día a día.',
      module: 'customer_onboarding',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      optional: true,
      roles: EVIDENCE_VIEW_ROLES,
      steps: [
        {
          code: 'identity.manual_review_apply',
          name: 'Aplicar la resolución manual de identidad',
          description: 'Resuelve el intento que espera decisión del cliente; excluye al rol cliente a propósito.',
          method: 'POST',
          path: '/customer-onboarding/:customerId/identity-manual-review',
          roles: EVIDENCE_VIEW_ROLES,
          optional: true,
          errors: ['403 ROLE_NOT_AUTHORIZED', '404 IDENTITY_ATTEMPT_NOT_FOUND'],
          events: ['kyc.approved', 'kyc.rejected'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'identity.entry',
      from: null,
      to: 'identity.upload_url',
      condition: 'always',
      description: 'La app pide dónde subir cada imagen.',
      isDefault: true,
    },
    {
      code: 'identity.upload_to_package',
      from: 'identity.upload_url',
      to: 'identity.package',
      condition: 'on_success',
      description: 'Subidas las imágenes, se registra el paquete.',
      isDefault: true,
    },
    {
      code: 'identity.package_to_mobile',
      from: 'identity.package',
      to: 'identity.mobile_start',
      condition: 'on_success',
      description: 'Registrada la evidencia, se pregunta al Motor.',
      isDefault: true,
    },
    {
      code: 'identity.mobile_to_execute',
      from: 'identity.mobile_start',
      to: 'identity.engine_execute',
      condition: 'on_success',
      description: 'Aceptado el intento, Atlas llama al Motor en segundo plano.',
      isDefault: true,
    },
    {
      code: 'identity.execute_to_worker',
      from: 'identity.engine_execute',
      to: 'identity.engine_worker',
      condition: 'always',
      description: 'El grafo del artefacto invoca al worker.',
      isDefault: true,
    },
    {
      code: 'identity.worker_to_status',
      from: 'identity.engine_worker',
      to: 'identity.mobile_status',
      condition: 'on_success',
      description: 'Con el veredicto escrito, la app lo lee.',
      isDefault: true,
    },
    {
      code: 'identity.execute_unavailable',
      from: 'identity.engine_execute',
      to: 'identity.mobile_status',
      condition: 'on_error',
      description: 'El Motor no respondió: el intento queda UNAVAILABLE y la app puede reintentar.',
    },
    {
      code: 'identity.status_to_motor_review',
      from: 'identity.mobile_status',
      to: 'identity.motor_cases',
      condition: 'conditional',
      expression: { status: 'IN_REVIEW' },
      description: 'El artefacto derivó a revisión humana en la cola IDENTIDAD.',
    },
    {
      code: 'identity.cases_to_detail',
      from: 'identity.motor_cases',
      to: 'identity.motor_case_detail',
      condition: 'on_success',
      description: 'El analista abre un caso.',
    },
    {
      code: 'identity.detail_to_images',
      from: 'identity.motor_case_detail',
      to: 'identity.motor_images',
      condition: 'on_success',
      description: 'Mira las imágenes de la ejecución.',
    },
    {
      code: 'identity.images_to_assign',
      from: 'identity.motor_images',
      to: 'identity.motor_assign',
      condition: 'on_success',
      description: 'Se lo asigna.',
    },
    {
      code: 'identity.assign_to_resolve',
      from: 'identity.motor_assign',
      to: 'identity.motor_resolve',
      condition: 'on_success',
      description: 'Resuelve el caso.',
    },
    {
      code: 'identity.resolve_to_callback',
      from: 'identity.motor_resolve',
      to: 'identity.review_callback',
      condition: 'on_success',
      description: 'El Motor avisa a Atlas con el executionId.',
    },
    {
      code: 'identity.callback_to_status',
      from: 'identity.review_callback',
      to: 'identity.mobile_status',
      condition: 'on_success',
      description: 'La app ve el veredicto final.',
    },
    {
      code: 'identity.package_to_registry',
      from: 'identity.package',
      to: 'identity.registry_verify',
      condition: 'conditional',
      expression: { path: 'registry' },
      description: 'Camino del proveedor: contraste con el registro estatal.',
    },
    {
      code: 'identity.registry_to_admin',
      from: 'identity.registry_verify',
      to: 'identity.investigation_summary',
      condition: 'conditional',
      expression: { finalResult: 'pending_review' },
      description: 'Coincidencia parcial o caída del proveedor: lo decide un analista de Atlas.',
    },
    {
      code: 'identity.summary_to_evidence',
      from: 'identity.investigation_summary',
      to: 'identity.evidence_list',
      condition: 'on_success',
      description: 'El analista abre las evidencias.',
    },
    {
      code: 'identity.evidence_to_content',
      from: 'identity.evidence_list',
      to: 'identity.evidence_content',
      condition: 'on_success',
      description: 'Mira cada imagen.',
    },
    {
      code: 'identity.content_to_decision',
      from: 'identity.evidence_content',
      to: 'identity.admin_decision',
      condition: 'on_success',
      description: 'Aprueba o rechaza en bloque.',
    },
    {
      code: 'identity.decision_delegated',
      from: 'identity.admin_decision',
      to: 'identity.motor_cases',
      condition: 'on_error',
      description: '409: el Motor abrió caso para este intento; se resuelve en su cola.',
    },
    {
      code: 'identity.exit',
      from: 'identity.mobile_status',
      to: null,
      condition: 'always',
      description: 'Salida: el intento tiene veredicto.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'identity.package',
      dependsOn: 'identity.upload_url',
      type: 'requires_data',
      description: 'El paquete cita las claves de almacén que devolvió el permiso de subida.',
    },
    {
      step: 'identity.mobile_status',
      dependsOn: 'identity.mobile_start',
      type: 'requires_data',
      description: 'Se consulta por el identificador que devuelve el envío.',
    },
    {
      step: 'identity.engine_execute',
      dependsOn: 'identity.mobile_start',
      type: 'requires_completion',
      description: 'La llamada al Motor sale del intento creado en PENDING.',
    },
    {
      step: 'identity.motor_resolve',
      dependsOn: 'identity.motor_assign',
      type: 'requires_completion',
      description: 'Sólo resuelve el analista asignado o supervisión.',
    },
    {
      step: 'identity.review_callback',
      dependsOn: 'identity.motor_resolve',
      type: 'requires_completion',
      description: 'El aviso lleva la decisión que tomó el analista.',
    },
    {
      step: 'identity.registry_verify',
      dependsOn: 'identity.package',
      type: 'requires_data',
      description: 'El número consultado debe coincidir con el del paquete.',
    },
    {
      step: 'identity.admin_decision',
      dependsOn: 'identity.evidence_content',
      type: 'soft',
      description: 'Decidir sin ver las imágenes era el defecto que cerró el panel de evidencias.',
    },
  ],
};
