/**
 * @file Proceso declarado en código: cartera — pagos, reversos, castigo, mora y calificación.
 * @business Un crédito desembolsado vive meses: este proceso mantiene sus cuotas al día (pagos y reversos), mide la mora, califica la deuda y al cliente, castiga lo incobrable y devuelve los desenlaces al Motor para que aprenda de lo que aprobó.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; rutas de `loans` y `credit-rating`, jobs `sweep_loan_delinquency`, `sweep_debt_ratings`, `register_engine_facilities` y `dispatch_loan_outcomes`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const CUSTOMER_READ_ROLES = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const RATING_READ_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'];
const RATING_WRITE_ROLES = ['risk_analyst', 'internal_operator', 'admin', 'platform_admin'];
const PAYMENT_ROLES = ['internal_operator', 'admin', 'platform_admin'];

export const LOAN_SERVICING_COLLECTIONS: WorkflowDefinitionFixture = {
  processId: 'P-10',
  code: 'loan_servicing_collections',
  version: 'v1',
  name: 'Cartera: pagos, reversos, castigo, mora y calificación',
  description:
    'Vida del préstamo activo: el cliente consulta sus cuotas, operaciones registra o revierte pagos y castiga lo incobrable, los barridos programados recalculan la mora y la calificación, y los desenlaces se entregan al Motor.',
  processType: 'back_office',
  ownerDomain: 'loan_servicing',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ATLAS_BACKEND', 'DECISION_ENGINE'],
  narrative: {
    whyExists:
      'Sin este proceso un préstamo vencido seguiría figurando al corriente: la mora se congelaba en el valor del día del desembolso, la cartera en mora era invisible, la línea de crédito no se enteraba y el Motor medía su acierto sobre una muestra congelada. Aquí la cuota, la mora, la calificación y el desenlace se mantienen solos.',
    whoStartsAndCloses:
      'Lo abre el desembolso de un préstamo (queda `active`). Lo mueven el cliente al pagar, operaciones al registrar o revertir un pago, los jobs de mora y calificación, y lo cierra el último pago (`paid_off`) o un administrador que castiga el préstamo (`written_off`).',
    startAndEnd:
      'Empieza con un préstamo `active` y cuotas `pending`. Cada barrido pasa a `overdue` las cuotas vencidas con saldo y mueve el tramo de mora; termina cuando todas las cuotas están pagadas (préstamo `paid_off`) o el préstamo se castiga y sus cuotas pasan a `written_off` conservando sus importes.',
    whenItFails:
      'Un pago sobre un préstamo no activo da 409 LOAN_NOT_COLLECTABLE y uno mayor que lo adeudado 422 PAYMENT_EXCEEDS_OUTSTANDING. Registrar, revertir, castigar y el barrido manual no tienen pantalla en el portal interno, así que hoy sólo se hacen con una llamada directa. Si la entrega al Motor se atasca, la pantalla de cartera enseña los desenlaces agotados.',
    healthIndicator:
      'Que la entrega de desenlaces al Motor vaya al día (estado y pendientes agotados en «Calificación de cartera») y la distribución de la cartera por categoría de riesgo y previsión; además, días de atraso y tramo de mora de `credit.loans` recalculados en cada barrido.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'credit',
    table: 'loans',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'loan_code',
    openStatuses: ['active'],
  },
  success: 'Las cuotas se cobran, la mora y la calificación reflejan la realidad y los desenlaces llegan al Motor.',
  failure: 'El préstamo se castiga, un pago se revierte o la entrega de desenlaces al Motor se agota sin que nadie la reintente.',
  sources: [
    'src/modules/loans/loan-payments.controller.ts',
    'src/modules/loans/loans-operations.controller.ts',
    'src/modules/loans/loans.controller.ts',
    'src/modules/loans/application/loan-payment.service.ts',
    'src/modules/loans/application/loan-writeoff.service.ts',
    'src/modules/loans/application/loan-delinquency.service.ts',
    'src/modules/credit-rating/credit-rating.controller.ts',
    'src/modules/credit-rating/credit-rating-operations.controller.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts',
    'src/modules/runtime-jobs/runtime-decision-jobs.controller.ts',
    'src/modules/decision-engine/decision-engine.client.ts',
    'src/database/migrations/20260811090000-create-loan-book.ts',
    'AtlasAdminPortal/src/features/portfolio-operations/portfolio-page.tsx',
    'AtlasAdminPortal/src/features/portfolio-operations/services.ts',
    'AtlasAdminPortal/src/features/runtime-jobs/runtime-job-catalog.ts',
    'AtlasFrontend/apps/consumer-app/src/features/use-credit-book.ts',
    'AtlasDecisionEngineFrontend/src/features/decision-quality/decision-quality.api.ts',
    '_plan-produccion-siete-repos-2026-09-24/06_PLAN_DAG_PRIORIDADES.md (DEC-21)',
    'memoria atlas-portal-motor-duplicacion-2',
  ],
  metadata: {
    openDecision:
      'DEC-21: tras reversar, ¿una cuota a cero queda partially_paid o vuelve a pending/overdue? Abierta en el plan de 7 repos.',
    inventoryStatesMismatch:
      'El inventario mezcla estados de préstamo y de cuota. Préstamo: pending_disbursement, active, paid_off, written_off, cancelled. Cuota: pending, partially_paid, paid, overdue, written_off.',
  },
  stages: [
    {
      code: 'servicing_customer_view',
      name: 'El cliente consulta sus créditos',
      description:
        'La app carga préstamos, gasto por categoría, calificación y calendario de pagos a la vez; una calificación ausente (cliente nuevo) no tumba la pantalla.',
      module: 'loans',
      actor: 'customer',
      client: 'CONSUMER_APP',
      screen: '/pagos',
      entry: true,
      steps: [
        {
          code: 'svc.list_loans',
          description: 'Devuelve los préstamos del cliente con su estado. Es la base de la pantalla de pagos de la app.',
          name: 'Listar los préstamos',
          method: 'GET',
          path: '/customers/:customerId/loans',
          roles: CUSTOMER_READ_ROLES,
        },
        {
          code: 'svc.loan_detail',
          description: 'Devuelve un préstamo con sus cuotas y lo pagado de cada una, para el detalle del crédito y de la cuota en la app.',
          name: 'Detalle del préstamo',
          method: 'GET',
          path: '/loans/:loanId',
          roles: CUSTOMER_READ_ROLES,
        },
        {
          code: 'svc.payment_calendar',
          name: 'Calendario de pagos',
          method: 'GET',
          path: '/customers/:customerId/payment-calendar',
          roles: CUSTOMER_READ_ROLES,
          description: 'Cada cuota como vencida, próxima, pagada o castigada, con el importe pendiente.',
        },
        {
          code: 'svc.spending',
          description: 'Agrupa lo comprado a crédito por categoría para el tablero de gastos del cliente.',
          name: 'Gasto por categoría',
          method: 'GET',
          path: '/customers/:customerId/spending-by-category',
          roles: CUSTOMER_READ_ROLES,
        },
        {
          code: 'svc.my_rating',
          description:
            'Devuelve la calificación vigente del propio cliente. Un cliente sin crédito calificado recibe 404 y la app lo trata como estado normal.',
          name: 'Mi calificación',
          method: 'GET',
          path: '/customers/:customerId/credit-rating',
          roles: ['customer', ...RATING_READ_ROLES],
          errors: ['404 sin calificación todavía (estado normal de un cliente nuevo)'],
        },
        {
          code: 'svc.delinquency_policy',
          name: 'Política de mora',
          method: 'GET',
          path: '/policies/delinquency',
          roles: CUSTOMER_READ_ROLES,
          optional: true,
          description: 'La lee la pantalla «Política de mora» de la app.',
        },
        {
          code: 'svc.spending_report',
          name: 'Informe de gasto en PDF',
          method: 'GET',
          path: '/customers/:customerId/spending-report.pdf',
          roles: CUSTOMER_READ_ROLES,
          optional: true,
          description: 'Ninguna app ni portal la llama hoy (triaje de cableado, categoría D).',
        },
      ],
    },
    {
      code: 'servicing_customer_payment',
      name: 'Pago de cuota por el cliente',
      description:
        'El camino normal de cobro es el aviso con comprobante que verifica el comercio (proceso P-09); al confirmarse, registra el pago aquí con idempotencia.',
      module: 'loan_payment_claims',
      actor: 'customer',
      client: 'CONSUMER_APP',
      screen: '/pagar/[installmentId]',
      steps: [
        {
          code: 'svc.customer_pays',
          description:
            'El cliente paga su cuota con el QR del comercio y avisa con comprobante; al verificarlo el comercio se registra el pago en el préstamo.',
          name: 'Pago con QR y comprobante (P-09)',
          kind: 'manual',
          reason: 'Lo recorre el proceso installment_payment_claims (P-09); aquí sólo se registra que es la entrada habitual de pagos.',
        },
      ],
    },
    {
      code: 'servicing_manual_payment',
      name: 'Registro y reverso de pagos por operaciones',
      description:
        'Operaciones registra un pago recibido por otro medio o revierte uno aplicado por error. Ninguna pantalla del portal interno llama a estas rutas.',
      module: 'loans',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/loans/[loanId]',
      optional: true,
      roles: PAYMENT_ROLES,
      steps: [
        {
          code: 'svc.register_payment',
          name: 'Registrar un pago',
          description:
            'Reparte el importe entre mora, interés y capital de las cuotas cobrables y deja la traza `payment_applied`; si todo queda saldado el préstamo pasa a `paid_off`.',
          method: 'POST',
          path: '/loans/:loanId/payments',
          roles: PAYMENT_ROLES,
          idempotencyKey: true,
          requiredStates: ['active'],
          input: {
            amount: 'string',
            currencyCode: 'string',
            paymentMethod: 'cash | bank_transfer | card | qr | wallet | direct_debit | other',
            externalReference: 'string?',
          },
          errors: ['404 LOAN_NOT_FOUND', '409 LOAN_NOT_COLLECTABLE', '422 CURRENCY_MISMATCH', '422 PAYMENT_EXCEEDS_OUTSTANDING'],
          optional: true,
        },
        {
          code: 'svc.reverse_payment',
          name: 'Revertir un pago',
          description:
            'Devuelve lo aplicado a cada cuota y deja la traza `payment_reversed`; un préstamo `paid_off` que deja de estar saldado vuelve a `active`. Qué estado toma una cuota que queda a cero es la decisión abierta DEC-21.',
          method: 'POST',
          path: '/loans/:loanId/payments/:paymentId/reversal',
          roles: PAYMENT_ROLES,
          input: { reasonCode: 'string', notes: 'string?' },
          errors: ['404 LOAN_PAYMENT_NOT_FOUND', '409 LOAN_PAYMENT_ALREADY_REVERSED'],
          optional: true,
        },
      ],
    },
    {
      code: 'servicing_delinquency',
      name: 'Barrido de mora',
      description:
        'Recalcula días de atraso, mueve el tramo (current → dpd_1_29 … dpd_90_plus), marca `overdue` las cuotas vencidas con saldo, recalcula la línea de crédito si el tramo empeora o mejora y encola los desenlaces de cosecha para el Motor.',
      module: 'loans',
      actor: 'system',
      client: 'BLOCK',
      resultingStates: ['overdue'],
      steps: [
        {
          code: 'svc.delinquency_job',
          description:
            'Cada intervalo recalcula días de atraso y tramo de mora, marca vencidas las cuotas con saldo, recalcula la línea si cambia el tramo y encola los desenlaces para el Motor.',
          name: 'Barrido de mora programado',
          kind: 'job',
          job: 'sweep_loan_delinquency',
        },
      ],
    },
    {
      code: 'servicing_delinquency_manual',
      name: 'Barrido de mora a mano',
      description:
        'La misma pasada, lanzada por una persona. No tiene pantalla: el portal quitó el botón y la pantalla de jobs no lo incluye.',
      module: 'loans',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/runtime-jobs',
      optional: true,
      roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      steps: [
        {
          code: 'svc.delinquency_manual',
          description:
            'Lanza a mano la misma pasada que el job de mora, sobre un número limitado de préstamos. Ninguna pantalla la llama hoy.',
          name: 'Lanzar el barrido de mora',
          method: 'POST',
          path: '/operations/loans/delinquency-sweep',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          input: { limit: 'number (≤ 1000, 200 por defecto)' },
          optional: true,
        },
      ],
    },
    {
      code: 'servicing_debt_rating',
      name: 'Calificación de la deuda y del cliente',
      description: 'La categoría de riesgo y la previsión se derivan de los días de atraso; corren solas cada intervalo del job.',
      module: 'credit_rating',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'svc.rating_job',
          description:
            'Cada intervalo recalcula la categoría de riesgo y la previsión de cada deuda y de su titular a partir de los días de atraso.',
          name: 'Barrido de calificación programado',
          kind: 'job',
          job: 'sweep_debt_ratings',
        },
      ],
    },
    {
      code: 'servicing_rating_review',
      name: 'Calificación de cartera en el portal',
      description:
        'Operaciones y riesgo ven la cartera por categoría y previsión, y recalifican a mano para adelantarse a un cierre (toda la cartera, un crédito o un cliente).',
      module: 'credit_rating',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/portfolio',
      roles: RATING_WRITE_ROLES,
      steps: [
        {
          code: 'svc.portfolio_summary',
          description:
            'Resume la cartera por categoría de riesgo con su previsión, que es lo que enseña la pantalla «Calificación de cartera».',
          name: 'Resumen de la cartera por categoría',
          method: 'GET',
          path: '/operations/credit-rating/portfolio-summary',
          roles: ['risk_analyst', 'internal_operator', 'compliance_analyst', 'admin', 'platform_admin'],
        },
        {
          code: 'svc.rating_sweep_manual',
          description: 'Recalifica toda la cartera a mano desde la pantalla, para adelantarse a un cierre sin esperar al job.',
          name: 'Recalificar la cartera',
          method: 'POST',
          path: '/operations/credit-rating/sweep',
          roles: RATING_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'svc.rate_loan',
          description: 'Recalifica un único crédito indicado por su identificador desde la pantalla de cartera.',
          name: 'Recalificar un crédito',
          method: 'POST',
          path: '/operations/credit-rating/loans/:loanId/rate',
          roles: RATING_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'svc.rate_customer',
          description: 'Recalifica a un único cliente indicado por su identificador desde la pantalla de cartera.',
          name: 'Recalificar un cliente',
          method: 'POST',
          path: '/operations/credit-rating/customers/:customerId/rate',
          roles: RATING_WRITE_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'servicing_rating_detail',
      name: 'Detalle e historia de la calificación',
      description:
        'Calificación vigente e historia de un crédito o un cliente, y la escala de categorías. Las rutas existen y nadie las llama: la pantalla de cartera sólo muestra el resumen.',
      module: 'credit_rating',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/loans/[loanId]',
      optional: true,
      roles: RATING_READ_ROLES,
      steps: [
        {
          code: 'svc.rating_scale',
          description: 'Devuelve la escala de categorías con sus tramos de atraso. Existe y ninguna pantalla la llama.',
          name: 'Escala de calificación',
          method: 'GET',
          path: '/operations/rating-scale',
          roles: RATING_READ_ROLES,
          optional: true,
        },
        {
          code: 'svc.loan_rating',
          description: 'Devuelve la calificación vigente de un crédito. Existe y ninguna pantalla la llama.',
          name: 'Calificación de un crédito',
          method: 'GET',
          path: '/operations/loans/:loanId/rating',
          roles: RATING_READ_ROLES,
          optional: true,
        },
        {
          code: 'svc.loan_rating_history',
          description:
            'Devuelve la historia de calificaciones de un crédito, para explicar cuándo y por qué cambió de categoría. Sin pantalla hoy.',
          name: 'Historia de calificación de un crédito',
          method: 'GET',
          path: '/operations/loans/:loanId/rating-history',
          roles: RATING_READ_ROLES,
          optional: true,
        },
        {
          code: 'svc.customer_rating',
          description: 'Devuelve la calificación vigente de un cliente para uso interno. Existe y ninguna pantalla la llama.',
          name: 'Calificación de un cliente',
          method: 'GET',
          path: '/operations/customers/:customerId/credit-rating',
          roles: RATING_READ_ROLES,
          optional: true,
        },
        {
          code: 'svc.customer_rating_history',
          description: 'Devuelve la historia de calificaciones de un cliente. Existe y ninguna pantalla la llama.',
          name: 'Historia de calificación de un cliente',
          method: 'GET',
          path: '/operations/customers/:customerId/credit-rating-history',
          roles: RATING_READ_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'servicing_outcome_delivery',
      name: 'Entrega de desenlaces al Motor',
      description:
        'Primero se da de alta cada crédito concedido en el Motor (sin alta no se le puede atribuir un desenlace); después se entregan en lote los desenlaces que encoló el barrido de mora.',
      module: 'decision_engine',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'svc.register_facilities_job',
          description:
            'Da de alta en el Motor los créditos concedidos que aún no lo están, porque sin alta el Motor no puede atribuirles un desenlace.',
          name: 'Alta de créditos en el Motor',
          kind: 'job',
          job: 'register_engine_facilities',
        },
        {
          code: 'svc.engine_facilities',
          description: 'El Motor registra cada crédito concedido para poder asociarle después sus desenlaces de cosecha.',
          name: 'El Motor registra los créditos',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/outcomes/facilities',
        },
        {
          code: 'svc.dispatch_outcomes_job',
          description: 'Entrega al Motor, en lote, los desenlaces que encoló el barrido de mora, con reintentos hasta agotarlos.',
          name: 'Despacho de desenlaces',
          kind: 'job',
          job: 'dispatch_loan_outcomes',
        },
        {
          code: 'svc.engine_outcomes_batch',
          name: 'El Motor recibe el lote de desenlaces',
          description: 'Escribe la observación y marca la ventana como observada; exige que el crédito ya esté dado de alta.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/outcomes/batch',
        },
      ],
    },
    {
      code: 'servicing_outcome_monitoring',
      name: 'Vigilancia de la entrega',
      description:
        'La pantalla de cartera dice si la entrega va al día y lista los desenlaces que agotaron sus reintentos; entregar a mano se hace desde la pantalla de jobs.',
      module: 'decision_engine',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/portfolio',
      steps: [
        {
          code: 'svc.outcome_status',
          description:
            'Dice si la entrega de desenlaces al Motor va al día. Lo muestra la pantalla de cartera en lugar del antiguo botón de entrega.',
          name: 'Estado de la entrega',
          method: 'GET',
          path: '/operations/loans/outcome-status',
          roles: ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
        },
        {
          code: 'svc.outcome_backlog',
          description: 'Lista los desenlaces que agotaron sus reintentos de entrega, para que una persona los revise.',
          name: 'Desenlaces agotados',
          method: 'GET',
          path: '/operations/loans/outcome-backlog',
          roles: ['risk_analyst', 'admin', 'platform_admin'],
        },
      ],
    },
    {
      code: 'servicing_jobs_manual',
      name: 'Adelantar jobs de cartera',
      description:
        'Desde «Jobs de ejecución» un administrador adelanta la entrega de desenlaces o la calificación sin esperar al intervalo.',
      module: 'runtime_jobs',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/runtime-jobs',
      optional: true,
      roles: ['admin', 'platform_admin'],
      steps: [
        {
          code: 'svc.run_dispatch_outcomes',
          description: 'Adelanta desde «Jobs de ejecución» la entrega de desenlaces al Motor sin esperar al intervalo del job.',
          name: 'Entregar desenlaces ahora',
          method: 'POST',
          path: '/operations/jobs/dispatch-loan-outcomes',
          roles: ['admin', 'platform_admin', 'system'],
          optional: true,
        },
        {
          code: 'svc.run_debt_ratings',
          description: 'Adelanta desde «Jobs de ejecución» la calificación de la cartera sin esperar al intervalo del job.',
          name: 'Calificar ahora',
          method: 'POST',
          path: '/operations/jobs/sweep-debt-ratings',
          roles: ['admin', 'platform_admin', 'system'],
          optional: true,
        },
      ],
    },
    {
      code: 'servicing_engine_quality',
      name: 'Medida del acierto en el Motor',
      description: 'Lo que se entrega se mide en el Motor: ventanas pendientes y matriz de cosechas en «Calidad de decisión».',
      module: 'decision_engine',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      link: '{MOTOR}/decision-quality',
      optional: true,
      steps: [
        {
          code: 'svc.engine_pending',
          description: 'El Motor lista las ventanas de observación que aún esperan su desenlace.',
          name: 'Ventanas pendientes de desenlace',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/outcomes/pending',
          optional: true,
        },
        {
          code: 'svc.engine_vintage',
          description: 'El Motor devuelve la matriz de cosechas con la que mide el acierto de lo que aprobó.',
          name: 'Matriz de cosechas',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/outcomes/vintage',
          optional: true,
        },
      ],
    },
    {
      code: 'servicing_write_off',
      name: 'Castigo del préstamo',
      description:
        'Un administrador castiga un préstamo activo incobrable: las cuotas pasan a `written_off` y dejan de ser cobrables, pero conservan sus importes. Sin pantalla en el portal interno.',
      module: 'loans',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/loans/[loanId]',
      optional: true,
      terminal: true,
      roles: ['admin', 'platform_admin'],
      resultingStates: ['written_off'],
      steps: [
        {
          code: 'svc.write_off',
          description:
            'Castiga un préstamo activo incobrable con motivo y notas: las cuotas dejan de ser cobrables y conservan sus importes. Deja la traza loan_written_off.',
          name: 'Castigar el préstamo',
          method: 'POST',
          path: '/loans/:loanId/write-off',
          roles: ['admin', 'platform_admin'],
          requiredStates: ['active'],
          resultingStates: ['written_off'],
          input: { reasonCode: 'string', notes: 'string (obligatorio)' },
          errors: ['404 LOAN_NOT_FOUND', '409 LOAN_ALREADY_WRITTEN_OFF', '409 LOAN_NOT_WRITE_OFF_ELIGIBLE'],
          optional: true,
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'svc.entry',
      from: null,
      to: 'svc.list_loans',
      condition: 'always',
      isDefault: true,
      description: 'Préstamo activo tras el desembolso.',
    },
    { code: 'svc.view_to_pay', from: 'svc.payment_calendar', to: 'svc.customer_pays', condition: 'on_success', isDefault: true },
    {
      code: 'svc.pay_to_delinquency',
      from: 'svc.customer_pays',
      to: 'svc.delinquency_job',
      condition: 'always',
      isDefault: true,
      description: 'Pague o no, el barrido recalcula la mora cada intervalo.',
    },
    {
      code: 'svc.manual_payment',
      from: 'svc.delinquency_job',
      to: 'svc.register_payment',
      condition: 'conditional',
      expression: { paymentReceivedOutsideApp: true },
      description: 'Pago recibido por otro medio: lo registra operaciones.',
    },
    {
      code: 'svc.payment_to_reversal',
      from: 'svc.register_payment',
      to: 'svc.reverse_payment',
      condition: 'conditional',
      expression: { appliedByMistake: true },
    },
    { code: 'svc.delinquency_to_rating', from: 'svc.delinquency_job', to: 'svc.rating_job', condition: 'on_success', isDefault: true },
    {
      code: 'svc.rating_to_facilities',
      from: 'svc.rating_job',
      to: 'svc.register_facilities_job',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'svc.facilities_to_engine',
      from: 'svc.register_facilities_job',
      to: 'svc.engine_facilities',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'svc.engine_to_dispatch',
      from: 'svc.engine_facilities',
      to: 'svc.dispatch_outcomes_job',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'svc.dispatch_to_batch',
      from: 'svc.dispatch_outcomes_job',
      to: 'svc.engine_outcomes_batch',
      condition: 'on_success',
      isDefault: true,
    },
    { code: 'svc.batch_to_monitor', from: 'svc.engine_outcomes_batch', to: 'svc.outcome_status', condition: 'always', isDefault: true },
    {
      code: 'svc.monitor_backlog',
      from: 'svc.outcome_status',
      to: 'svc.outcome_backlog',
      condition: 'conditional',
      expression: { exhausted: '>0' },
    },
    {
      code: 'svc.backlog_to_manual',
      from: 'svc.outcome_backlog',
      to: 'svc.run_dispatch_outcomes',
      condition: 'on_success',
      description: 'Adelantar la entrega desde «Jobs de ejecución».',
    },
    {
      code: 'svc.to_write_off',
      from: 'svc.delinquency_job',
      to: 'svc.write_off',
      condition: 'conditional',
      expression: { judgedUncollectible: true },
      description: 'Deuda que un administrador juzga incobrable: el código no fija un tramo que obligue a castigar.',
    },
    { code: 'svc.write_off_exit', from: 'svc.write_off', to: null, condition: 'on_success' },
    { code: 'svc.paid_off_exit', from: 'svc.payment_calendar', to: null, condition: 'conditional', expression: { loanStatus: 'paid_off' } },
  ],
  dependencies: [
    {
      step: 'svc.engine_outcomes_batch',
      dependsOn: 'svc.engine_facilities',
      type: 'requires_completion',
      description: 'El Motor rechaza el desenlace de un crédito que no está dado de alta.',
    },
    {
      step: 'svc.dispatch_outcomes_job',
      dependsOn: 'svc.delinquency_job',
      type: 'requires_data',
      description: 'Los desenlaces los encola el barrido de mora.',
    },
    {
      step: 'svc.rating_job',
      dependsOn: 'svc.delinquency_job',
      type: 'requires_data',
      description: 'La categoría se deriva de los días de atraso que mueve el barrido.',
    },
    {
      step: 'svc.reverse_payment',
      dependsOn: 'svc.register_payment',
      type: 'requires_data',
      description: 'Sólo se revierte un pago aplicado.',
    },
  ],
};
