/**
 * @file Proceso declarado en código: Usuarios del comercio: provisión por cola, acceso y recuperación de contraseña.
 * @business Las personas de un comercio entran al portal del comercio con una identidad que el ERP pide y Atlas concede; este proceso hace que ninguna identidad nazca sin petición, que quien pide no conceda, y que quien olvidó su contraseña pueda recuperarla solo.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; ERP (`b2b/onboarding/merchant-users`, `auth/merchant/*`) → AtlasBackend (`merchant/users/*`, `merchant/auth/*`, `auth/password-reset/*`) con el portal admin como pantalla de concesión.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** Roles internos que traen `merchant.users.read` (rutas sin `@Roles`: las gobierna el permiso). */
const USERS_READ = ['OPERATIONS_MANAGER', 'MERCHANT_OPERATIONS', 'AUDITOR_READONLY', 'SUPER_ADMIN'];
/** Roles internos que traen `merchant.users.manage`. */
const USERS_MANAGE = ['MERCHANT_OPERATIONS', 'SUPER_ADMIN'];
/** Roles internos que traen `merchant.users.request`. */
const USERS_REQUEST = ['OPERATIONS_MANAGER', 'SUPER_ADMIN'];
/** `@Roles` del ERP para acusar la identidad. */
const ERP_ACK = ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'];

export const MERCHANT_USERS_AND_ACCESS: WorkflowDefinitionFixture = {
  processId: 'P-18',
  code: 'merchant_users_and_access',
  version: 'v1',
  name: 'Usuarios del comercio: provisión por cola, acceso y recuperación de contraseña',
  description:
    'El ERP registra a una persona del comercio y encola su alta de identidad en Atlas; Operaciones de comercios la concede o rechaza desde el portal admin; el ERP acusa el resultado. La persona entra al portal del comercio con la sesión que emite Atlas por la pasarela del ERP y, si olvida la contraseña, la recupera sola.',
  processType: 'integration',
  ownerDomain: 'merchant_identity',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P1',
  systems: ['ERP_BACKEND', 'ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Antes el portal admin daba de alta usuarios de comercio a mano y nada los ataba con la fila del ERP: un carácter distinto en el correo dejaba a la persona con sesión y un 403 en el portal del comercio. Ahora la identidad sólo nace al conceder una petición que el ERP encoló, quien pide no concede, y la contraseña provisional la genera Atlas y viaja una sola vez.',
    whoStartsAndCloses:
      'Lo inicia un ejecutivo u Operaciones del ERP con «Dar acceso a una persona» en el caso de onboarding (rol Atlas OPERATIONS_MANAGER, permiso merchant.users.request); lo concede o rechaza Operaciones de comercios en el portal admin (MERCHANT_OPERATIONS, permiso merchant.users.manage); lo cierra el ERP al acusar el resultado, y la persona del comercio al iniciar sesión.',
    startAndEnd:
      'Empieza cuando el ERP crea el usuario en INVITED y encola la petición en pending (POST /b2b/onboarding/merchant-users). Termina cuando la petición queda provisioned con su identidad activa y el ERP la acusa (usuario ACTIVE con user_id), o rejected con motivo (usuario DISABLED). Después la identidad puede pasar a suspended o disabled desde el portal admin.',
    whenItFails:
      'Si Atlas rechaza la petición al encolarla (correo con otra pendiente: 409), la fila del ERP se deshace y el ejecutivo ve el motivo de Atlas. Conceder dos veces responde 409 ALREADY_DECIDED. Si el correo de credenciales falla, la concesión no se deshace. El login con identidad no activa responde 401; la recuperación responde siempre lo mismo y deja el motivo real sólo en el registro del servidor.',
    healthIndicator:
      'Peticiones en pending y su antigüedad en la cola del portal admin, usuarios del ERP en INVITED sin user_id (credenciales pedidas y no acusadas), y la proporción de logins de comercio con 401 frente a los correctos.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'iam',
    table: 'merchant_user_provisioning_requests',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'email',
    openStatuses: ['pending'],
  },
  success:
    'La petición queda provisioned, el usuario del ERP ACTIVE con su user_id acusado y la persona inicia sesión en el portal del comercio.',
  failure:
    'La petición se rechaza o se queda pending, el ERP no acusa y el usuario sigue INVITED, o la persona no logra entrar ni recuperar el acceso.',
  sources: [
    'src/modules/merchant-identity/merchant-users.controller.ts',
    'src/modules/merchant-identity/merchant-user-requests.service.ts',
    'src/modules/merchant-identity/merchant-auth.controller.ts',
    'src/modules/merchant-identity/merchant-identity.schemas.ts (MERCHANT_USER_STATUSES, MERCHANT_PROVISIONING_STATUSES)',
    'src/modules/auth/auth.controller.ts (password-reset)',
    'src/modules/internal-users/internal-rbac.permissions.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-onboarding.service.ts (createMerchantUser, syncMerchantUserIdentity, reconcileCaseIdentity)',
    'AtlasERPBackend/src/modules/auth-gateway/auth-gateway.controller.ts',
    'AtlasERPBackend/src/modules/auth-gateway/atlas-identity.client.ts',
    'AtlasAdminPortal/src/app/internal/merchant-users/page.tsx',
    'AtlasERPFrontend/app/recuperar-acceso',
    'memoria atlas-alta-comercio-por-cola',
    'memoria atlas-recuperar-contrasena-comercio',
    'memoria atlas-portal-comercio-cinco-entradas',
  ],
  metadata: {
    gaps: [
      'merchant/auth/* (login, refresh, logout, me) no tiene llamador directo: el ERP lo usa por su pasarela. Las tres primeras son públicas a propósito (la sesión aún no existe); login lleva freno de 10 intentos por minuto.',
      'PATCH /b2b/onboarding/merchant-users/:merchantUserId/identity y GET /merchant/users/:merchantUserId no tienen pantalla.',
      'Contradicción: el controlador dice que conceder crea la identidad en «invited»; el servicio la crea «active» y manda la contraseña provisional por correo en el mismo paso.',
      'La recuperación de contraseña del comercio no pasa por merchant/auth/*: el ERP manda actorType merchant_user al plano genérico /auth/password-reset/*.',
    ],
  },
  stages: [
    {
      code: 'mu_erp_request',
      name: 'El ERP pide el acceso',
      description:
        '«Dar acceso a una persona» en la fila del caso de onboarding. La fila del CRM y la petición en Atlas van juntas o no van: si Atlas rechaza, la fila se deshace.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      entry: true,
      roles: ['OPERATIONS', 'ADMIN'],
      resultingStates: ['pending'],
      steps: [
        {
          code: 'mu.erp_create_user',
          name: 'Registrar a la persona del comercio',
          description: 'Nace INVITED en atlas_sales.merchant_users; el caso abierto pasa a ALTA_PENDIENTE.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/merchant-users',
          roles: ['OPERATIONS', 'ADMIN'],
          input: { accountId: 'uuid', branchId: 'uuid?', email: 'string', fullName: 'string', roleCode: 'string' },
          errors: ['404 Cuenta B2B no encontrada', '409 Ya existe un usuario comercio con ese email en la cuenta', '400 VALIDATION_ERROR'],
        },
        {
          code: 'mu.core_enqueue',
          name: 'Encolar la petición de alta',
          description:
            'Idempotente por (tenant, source, externalReference). Un único pending por correo. Exige el permiso merchant.users.request; el tenant sale del token, nunca del cuerpo.',
          method: 'POST',
          path: '/merchant/users/provisioning-requests',
          roles: USERS_REQUEST,
          resultingStates: ['pending'],
          errors: ['409 MERCHANT_PROVISIONING_REQUEST_PENDING_FOR_EMAIL', '403 token sin tenant'],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'mu_portal_grant',
      name: 'El portal admin concede o rechaza',
      description:
        'Cola de peticiones en /internal/merchant-users: pendientes primero, la más antigua arriba. Conceder crea la identidad con los datos de la petición en una transacción con cerrojo y manda la contraseña provisional.',
      module: 'merchant_identity',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/merchant-users',
      roles: USERS_MANAGE,
      requiredStates: ['pending'],
      resultingStates: ['provisioned', 'rejected'],
      steps: [
        {
          code: 'mu.core_list_requests',
          name: 'Ver la cola de peticiones',
          description: 'Lista paginada; exige merchant.users.read.',
          method: 'GET',
          path: '/merchant/users/provisioning-requests',
          roles: USERS_READ,
          repeatable: true,
        },
        {
          code: 'mu.core_approve',
          name: 'Conceder el acceso',
          description:
            'Crea la identidad y cierra la petición como provisioned. La contraseña provisional viaja una sola vez en la respuesta; exige merchant.users.manage.',
          method: 'POST',
          path: '/merchant/users/provisioning-requests/:requestId/approve',
          roles: USERS_MANAGE,
          resultingStates: ['provisioned'],
          output: { request: 'MerchantUserProvisioningRequest', merchantUser: 'MerchantUser', temporaryPassword: 'string' },
          errors: ['409 MERCHANT_PROVISIONING_REQUEST_ALREADY_DECIDED', '409 MERCHANT_USER_EMAIL_TAKEN'],
          successStatus: [201],
        },
        {
          code: 'mu.mail_credentials',
          name: 'Enviar las credenciales iniciales',
          kind: 'external',
          reason:
            'Correo con la contraseña provisional (sendInitialCredentials) enviado después del commit; su fallo no deshace la concesión.',
          description: 'Sale por el transporte de correo configurado; a un dominio no entregable no se envía nada.',
        },
        {
          code: 'mu.core_reject',
          name: 'Rechazar la petición',
          description: 'Motivo obligatorio: es lo que el ERP lee para corregir.',
          method: 'POST',
          path: '/merchant/users/provisioning-requests/:requestId/reject',
          roles: USERS_MANAGE,
          optional: true,
          resultingStates: ['rejected'],
          errors: ['409 MERCHANT_PROVISIONING_REQUEST_ALREADY_DECIDED'],
        },
      ],
    },
    {
      code: 'mu_erp_acknowledge',
      name: 'El ERP acusa el resultado',
      description:
        'Atlas no llama de vuelta: el ERP pregunta por cada usuario con petición sin resolver. provisioned → usuario ACTIVE con user_id; rejected → DISABLED con el motivo, sin borrar la fila.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      roles: ERP_ACK,
      steps: [
        {
          code: 'mu.erp_reconcile_case',
          name: 'Acusar las credenciales del caso',
          description: 'Con todas resueltas y al menos una concedida, el caso pasa de ALTA_PENDIENTE a LISTO.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/identity/reconcile',
          roles: ERP_ACK,
          repeatable: true,
        },
        {
          code: 'mu.core_get_request',
          name: 'Consultar en qué quedó una petición',
          description: 'Estado y merchantUserId con el que enlazar; exige merchant.users.read.',
          method: 'GET',
          path: '/merchant/users/provisioning-requests/:requestId',
          roles: USERS_READ,
          errors: ['404 MERCHANT_PROVISIONING_REQUEST_NOT_FOUND'],
        },
        {
          code: 'mu.erp_sync_user_identity',
          name: 'Reconciliar una sola persona',
          description:
            'Lo mismo para un usuario suelto; 409 si se registró antes de que el alta pasara por la cola. Sin pantalla que lo llame.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/onboarding/merchant-users/:merchantUserId/identity',
          roles: ERP_ACK,
          optional: true,
          errors: ['404 Usuario de comercio no encontrado', '409 sin petición de acceso encolada'],
        },
      ],
    },
    {
      code: 'mu_merchant_login',
      name: 'La persona del comercio inicia sesión',
      description:
        'Pestaña «Comercio afiliado» del login del ERP. El ERP reenvía a Atlas, que autentica la identidad del comercio; el ERP reemite su propio token y resuelve el alcance sobre cuentas.',
      module: 'merchant_identity',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/login',
      link: '{ERP}/login',
      terminal: true,
      requiredStates: ['provisioned'],
      steps: [
        {
          code: 'mu.erp_login',
          name: 'Iniciar sesión (pasarela del ERP)',
          description: 'Público. Sin la cabecera Origin permitida por CORS responde 500 en el navegador.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/auth/merchant/login',
          auth: false,
          errors: ['401 Credenciales inválidas'],
        },
        {
          code: 'mu.core_login',
          name: 'Autenticar la identidad del comercio',
          description: 'Público; 10 intentos por minuto por IP. Los tokens viajan en cookies HttpOnly.',
          method: 'POST',
          path: '/merchant/auth/login',
          auth: false,
          errors: ['401 credenciales inválidas, identidad no activa o rol no admitido', '429 TOO_MANY_REQUESTS'],
        },
        {
          code: 'mu.erp_me',
          name: 'Confirmar quién entró (pasarela del ERP)',
          description: 'Perfil del usuario de comercio y su alcance.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/auth/merchant/me',
          roles: ['MERCHANT_ADMIN'],
        },
        {
          code: 'mu.core_me',
          name: 'Perfil de la identidad del comercio',
          description: 'Lo que el ERP lee para reemitir su token.',
          method: 'GET',
          path: '/merchant/auth/me',
        },
        {
          code: 'mu.erp_refresh',
          name: 'Renovar la sesión (pasarela del ERP)',
          description: 'Público: canjea el refresh token.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/auth/merchant/refresh',
          auth: false,
          repeatable: true,
        },
        {
          code: 'mu.core_refresh',
          name: 'Rotar el refresh token',
          description: 'Una identidad suspendida pierde la sesión en esta rotación.',
          method: 'POST',
          path: '/merchant/auth/refresh',
          auth: false,
          repeatable: true,
          errors: ['401 Falta el refresh token'],
        },
        {
          code: 'mu.erp_logout',
          name: 'Cerrar sesión (pasarela del ERP)',
          description: 'Público e idempotente.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/auth/merchant/logout',
          auth: false,
          optional: true,
        },
        {
          code: 'mu.core_logout',
          name: 'Revocar la sesión del comercio',
          description: 'Admite cerrar en todos los dispositivos.',
          method: 'POST',
          path: '/merchant/auth/logout',
          auth: false,
          optional: true,
        },
      ],
    },
    {
      code: 'mu_password_recovery',
      name: 'El comercio recupera su contraseña',
      description:
        'Enlace «Recuperar acceso» sólo en la pestaña del comercio. El ERP manda actorType merchant_user al plano genérico de Atlas, que ya tiene anti-enumeración, enfriamiento de 60 s y revocación de sesiones al confirmar.',
      module: 'auth',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/recuperar-acceso',
      link: '{ERP}/recuperar-acceso',
      optional: true,
      steps: [
        {
          code: 'mu.erp_reset_request',
          name: 'Pedir el código (pasarela del ERP)',
          description: 'Público; responde requested:true exista o no la cuenta.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/auth/merchant/password-reset/request',
          auth: false,
          optional: true,
          successStatus: [201],
        },
        {
          code: 'mu.core_reset_request',
          name: 'Emitir el código de un solo uso',
          description: 'Sin credencial, sin correo o en enfriamiento no crea nada y lo registra con el dominio, nunca el buzón.',
          method: 'POST',
          path: '/auth/password-reset/request',
          auth: false,
          optional: true,
        },
        {
          code: 'mu.erp_reset_confirm',
          name: 'Fijar la contraseña nueva (pasarela del ERP)',
          description: 'Público.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/auth/merchant/password-reset/confirm',
          auth: false,
          optional: true,
          errors: ['401 Código inválido o expirado'],
        },
        {
          code: 'mu.core_reset_confirm',
          name: 'Canjear el código y revocar sesiones',
          description: 'Cambia la credencial y revoca todas las sesiones abiertas.',
          method: 'POST',
          path: '/auth/password-reset/confirm',
          auth: false,
          optional: true,
        },
      ],
    },
    {
      code: 'mu_lifecycle',
      name: 'Operaciones de comercios gobierna el acceso',
      description:
        'Desde el portal admin se listan las identidades de comercio y se activan, suspenden o dan de baja. Suspender corta la sesión en la siguiente rotación del refresh token.',
      module: 'merchant_identity',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/merchant-users',
      optional: true,
      roles: USERS_MANAGE,
      resultingStates: ['active', 'suspended', 'disabled'],
      steps: [
        {
          code: 'mu.core_list_users',
          name: 'Listar identidades de comercio',
          description: 'Lista paginada del inquilino; exige merchant.users.read.',
          method: 'GET',
          path: '/merchant/users',
          roles: USERS_READ,
          optional: true,
        },
        {
          code: 'mu.core_get_user',
          name: 'Consultar una identidad',
          description: 'Sin pantalla que la llame hoy.',
          method: 'GET',
          path: '/merchant/users/:merchantUserId',
          roles: USERS_READ,
          optional: true,
          errors: ['404 MERCHANT_USER_NOT_FOUND'],
        },
        {
          code: 'mu.core_status',
          name: 'Activar, suspender o dar de baja',
          description: 'Exige merchant.users.manage.',
          method: 'PATCH',
          path: '/merchant/users/:merchantUserId/status',
          roles: USERS_MANAGE,
          optional: true,
          resultingStates: ['active', 'suspended', 'disabled'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'mu.entry',
      from: null,
      to: 'mu.erp_create_user',
      condition: 'always',
      isDefault: true,
      description: 'Entrada: el ERP pide el acceso.',
    },
    {
      code: 'mu.create_to_enqueue',
      from: 'mu.erp_create_user',
      to: 'mu.core_enqueue',
      condition: 'always',
      isDefault: true,
      description: 'La petición se encola dentro de la misma transacción.',
    },
    {
      code: 'mu.enqueue_to_approve',
      from: 'mu.core_enqueue',
      to: 'mu.core_approve',
      condition: 'on_success',
      isDefault: true,
      description: 'Operaciones de comercios concede.',
    },
    {
      code: 'mu.enqueue_to_reject',
      from: 'mu.core_enqueue',
      to: 'mu.core_reject',
      condition: 'conditional',
      expression: { decision: 'reject' },
      description: 'Operaciones de comercios rechaza con motivo.',
    },
    {
      code: 'mu.approve_to_mail',
      from: 'mu.core_approve',
      to: 'mu.mail_credentials',
      condition: 'on_success',
      isDefault: true,
      description: 'Tras el commit sale el correo.',
    },
    {
      code: 'mu.mail_to_ack',
      from: 'mu.mail_credentials',
      to: 'mu.erp_reconcile_case',
      condition: 'always',
      isDefault: true,
      description: 'El ERP acusa.',
    },
    {
      code: 'mu.reject_to_ack',
      from: 'mu.core_reject',
      to: 'mu.erp_reconcile_case',
      condition: 'on_success',
      description: 'El ERP lee el rechazo.',
    },
    {
      code: 'mu.ack_to_read',
      from: 'mu.erp_reconcile_case',
      to: 'mu.core_get_request',
      condition: 'always',
      isDefault: true,
      description: 'Por cada petición pendiente, el ERP pregunta.',
    },
    {
      code: 'mu.read_to_login',
      from: 'mu.core_get_request',
      to: 'mu.erp_login',
      condition: 'conditional',
      expression: { status: 'provisioned' },
      isDefault: true,
      description: 'Concedida: la persona ya puede entrar.',
    },
    {
      code: 'mu.login_to_core',
      from: 'mu.erp_login',
      to: 'mu.core_login',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía a Atlas.',
    },
    {
      code: 'mu.login_to_me',
      from: 'mu.core_login',
      to: 'mu.erp_me',
      condition: 'on_success',
      isDefault: true,
      description: 'Con sesión, el ERP confirma el perfil.',
    },
    {
      code: 'mu.login_to_recovery',
      from: 'mu.core_login',
      to: 'mu.erp_reset_request',
      condition: 'on_error',
      description: 'No logra entrar: recupera el acceso.',
    },
    {
      code: 'mu.reset_request_core',
      from: 'mu.erp_reset_request',
      to: 'mu.core_reset_request',
      condition: 'always',
      description: 'El ERP reenvía con actorType merchant_user.',
    },
    {
      code: 'mu.reset_to_confirm',
      from: 'mu.core_reset_request',
      to: 'mu.erp_reset_confirm',
      condition: 'on_success',
      description: 'Con el código, fija la contraseña.',
    },
    {
      code: 'mu.confirm_core',
      from: 'mu.erp_reset_confirm',
      to: 'mu.core_reset_confirm',
      condition: 'always',
      description: 'El ERP reenvía.',
    },
    {
      code: 'mu.recovery_to_login',
      from: 'mu.core_reset_confirm',
      to: 'mu.erp_login',
      condition: 'on_success',
      description: 'Vuelve al login.',
    },
    {
      code: 'mu.exit',
      from: 'mu.erp_me',
      to: null,
      condition: 'on_success',
      isDefault: true,
      description: 'Salida: la persona opera en el portal del comercio.',
    },
  ],
  dependencies: [
    { step: 'mu.core_approve', dependsOn: 'mu.core_enqueue', type: 'requires_data', description: 'Se concede una petición encolada.' },
    {
      step: 'mu.core_get_request',
      dependsOn: 'mu.core_enqueue',
      type: 'requires_data',
      description: 'El ERP guarda el identificador de la petición al encolarla.',
    },
    {
      step: 'mu.core_login',
      dependsOn: 'mu.core_approve',
      type: 'requires_completion',
      description: 'Sin identidad concedida el login responde 401.',
    },
    {
      step: 'mu.core_reset_confirm',
      dependsOn: 'mu.core_reset_request',
      type: 'requires_completion',
      description: 'El código lo emite la solicitud.',
    },
    { step: 'mu.core_me', dependsOn: 'mu.core_login', type: 'requires_data', description: 'Necesita el token del login.' },
  ],
};
