/**
 * @file Proceso declarado en código: Soporte al comercio desde el ERP (pasarela) hacia la mesa de Atlas.
 * @business Un comercio con un problema lo cuenta desde su propio portal y lo atiende la misma mesa de soporte que atiende a los clientes; este proceso lleva el caso del comercio por la pasarela del ERP hasta la mesa de Atlas y de vuelta, con valoración y cierre pedido por el comercio.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; pasarela `support-gateway.controller.ts` del ERP → `merchant-support.controller.ts`, `support-chat.controller.ts` e `internal-support.controller.ts` de AtlasBackend, con el job `sweep_support_sla`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** `@Roles(...COMERCIO)` de `support-gateway.controller.ts` del ERP. */
const ERP_MERCHANT = ['merchant', 'MERCHANT_ADMIN', 'MERCHANT_OPERATIONS', 'ADMIN'];
/** `@Roles` de clase de `merchant-support.controller.ts`. */
const CORE_MERCHANT = ['merchant', 'internal_operator', 'admin', 'platform_admin'];
/** `@Roles` de clase de `support-chat.controller.ts`. */
const CHAT_ROLES = [
  'customer',
  'merchant',
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'fraud_analyst',
  'admin',
  'platform_admin',
];
/** `@Roles` de clase de la mesa (`internal-support*.controller.ts`). */
const DESK_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'];

export const MERCHANT_SUPPORT: WorkflowDefinitionFixture = {
  processId: 'P-22',
  code: 'merchant_support',
  version: 'v1',
  name: 'Soporte al comercio desde el ERP (pasarela) hacia la mesa de Atlas',
  description:
    'El comercio consulta la ayuda y abre un caso con motivo o un chat desde «Soporte y tutoriales» de su portal; el ERP lo reenvía a AtlasBackend, donde el caso entra en la misma mesa que los de clientes. Un agente lo clasifica, lo toma, responde y lo resuelve; el comercio pide el cierre y lo valora.',
  processType: 'integration',
  ownerDomain: 'support',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P1',
  systems: ['ERP_BACKEND', 'ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'El comercio también necesita ayuda con su operación (cobros, cajas, su expediente) y no tiene por qué tener otro canal distinto del de los clientes. Su caso viaja por la pasarela del ERP a la misma mesa de soporte de Atlas, con el aislamiento entre comercios resuelto en el servidor: el identificador de comercio que llega en el cuerpo se comprueba contra el dueño del expediente, no se cree.',
    whoStartsAndCloses:
      'Lo inicia la persona del comercio desde /portal-comercio/soporte del ERP; lo atiende un agente de soporte de Atlas (rol SUPPORT_AGENT, con perfil de agente en la mesa) desde /internal/support, que lo resuelve con código de resolución y causa raíz; el comercio pide el cierre y lo valora, y el agente o el sistema lo cierran.',
    startAndEnd:
      'Empieza cuando el comercio abre un caso con motivo (POST /merchant/support/cases por la pasarela) y el caso nace en NEW; pasa por TRIAGED, ASSIGNED, IN_PROGRESS o WAITING_PARTNER; termina en RESOLVED y CLOSED. Pedir el cierre de un caso ya resuelto lo cierra de inmediato; en otro estado queda registrado como petición.',
    whenItFails:
      'Sin catálogo de categorías sembrado, abrir el caso falla con SUPPORT_CATEGORY_NOT_FOUND. Un comercio que pide un caso de otro comercio no lo ve. Valorar antes de la resolución responde 409 SUPPORT_FEEDBACK_TOO_EARLY. Si el caso supera su plazo, el barrido sweep_support_sla publica support.sla.breached. Si el ERP no reenvía, el comercio ve el error de la pasarela y el caso no existe en Atlas.',
    healthIndicator:
      'Casos abiertos de comercios por estado y antigüedad en la mesa, porcentaje resuelto dentro del plazo (support.sla.breached frente a resueltos), y la valoración del comercio tras el cierre.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'support',
    table: 'support_cases',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'case_number',
    openStatuses: [
      'NEW',
      'TRIAGED',
      'ASSIGNED',
      'IN_PROGRESS',
      'WAITING_CUSTOMER',
      'WAITING_INTERNAL',
      'WAITING_PARTNER',
      'ESCALATED',
      'ON_HOLD',
      'REOPENED',
    ],
  },
  success:
    'El caso del comercio queda RESOLVED y CLOSED con código de resolución y causa raíz, dentro de su plazo, y el comercio lo valora.',
  failure: 'El caso no llega a abrirse (sin categoría o sin pasarela), se queda sin agente, vence su plazo o se cierra sin resolución.',
  sources: [
    'AtlasERPBackend/src/modules/partner-onboarding-gateway/support-gateway.controller.ts',
    'src/modules/support/merchant-support.controller.ts',
    'src/modules/support/support-chat.controller.ts',
    'src/modules/support/internal-support.controller.ts',
    'src/modules/support/support.constants.ts (SUPPORT_CASE_STATUSES)',
    'src/modules/support/application/support-case-creation-events.service.ts',
    'src/modules/support/application/support-case-customer.service.ts',
    'src/modules/support/application/support-case-closure.service.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts (sweep_support_sla)',
    'src/modules/workflow-catalog/definitions/processes/customer-support-case.process.fixtures.ts (P-12)',
    'AtlasERPFrontend/components/screens/MerchantSupportScreen.tsx',
    'AtlasAdminPortal/src/app/internal/support/page.tsx',
    'AtlasAIService/docs/support/support-channel-map.md',
  ],
  metadata: {
    gaps: [
      'merchant/support/* de AtlasBackend no tiene llamador directo: el portal del comercio llega por la pasarela del ERP (se documentan los dos tramos).',
      'El inventario nombra estados en minúscula (open, assigned, waiting_customer…); los reales son SUPPORT_CASE_STATUSES en mayúscula, con WAITING_PARTNER para el comercio.',
      'La mesa, el SLA y la base de conocimiento son los del proceso P-12: aquí sólo se documenta el tramo del comercio.',
      'GET /support/attachments/:attachmentId/content del ERP no tiene pantalla que lo llame.',
    ],
  },
  stages: [
    {
      code: 'msup_self_help',
      name: 'El comercio busca ayuda escrita',
      description:
        'Pestaña «Soporte» de «Soporte y tutoriales»: preguntas frecuentes para comercios, motivos disponibles y búsqueda en la base de conocimiento, antes de escribir a nadie.',
      module: 'support',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/soporte',
      link: '{ERP}/portal-comercio/soporte',
      entry: true,
      roles: ERP_MERCHANT,
      steps: [
        {
          code: 'msup.gw_faq',
          name: 'Ver las preguntas frecuentes (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant/support/faq',
          roles: ERP_MERCHANT,
        },
        {
          code: 'msup.core_faq',
          name: 'Preguntas frecuentes para comercios',
          description: 'Artículos destacados para la audiencia del comercio.',
          method: 'GET',
          path: '/merchant/support/faq',
          roles: CORE_MERCHANT,
        },
        {
          code: 'msup.gw_categories',
          name: 'Ver los motivos (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant/support/categories',
          roles: ERP_MERCHANT,
        },
        {
          code: 'msup.core_categories',
          name: 'Motivos de contacto del comercio',
          description: 'Sin siembra de categorías la lista viene vacía.',
          method: 'GET',
          path: '/merchant/support/categories',
          roles: CORE_MERCHANT,
        },
        {
          code: 'msup.gw_search',
          name: 'Buscar en la ayuda (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant/support/knowledge/search',
          roles: ERP_MERCHANT,
          optional: true,
        },
        {
          code: 'msup.core_search',
          name: 'Buscar en la base de conocimiento',
          description: 'Artículos publicados para comercios.',
          method: 'GET',
          path: '/merchant/support/knowledge/search',
          roles: CORE_MERCHANT,
          optional: true,
        },
      ],
    },
    {
      code: 'msup_open',
      name: 'El comercio abre su caso o su chat',
      description:
        'El caso con motivo nace en Atlas con el comercio como parte; el partnerProfileId del cuerpo se comprueba contra el dueño del expediente. El chat es un canal opcional atado al caso.',
      module: 'support',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/soporte',
      link: '{ERP}/portal-comercio/soporte',
      roles: ERP_MERCHANT,
      resultingStates: ['NEW'],
      steps: [
        {
          code: 'msup.gw_case_open',
          name: 'Abrir un caso (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend con el token del comercio.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/merchant/support/cases',
          roles: ERP_MERCHANT,
        },
        {
          code: 'msup.core_case_open',
          name: 'Crear el caso del comercio',
          description: 'Nace NEW con su categoría; una queja o un tema de seguridad publican además su evento.',
          method: 'POST',
          path: '/merchant/support/cases',
          roles: CORE_MERCHANT,
          resultingStates: ['NEW'],
          errors: ['404 SUPPORT_CATEGORY_NOT_FOUND'],
          events: ['support.case.created', 'support.complaint.created', 'support.security.escalated'],
          successStatus: [201],
        },
        {
          code: 'msup.gw_channel_open',
          name: 'Abrir el chat (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/support/channels',
          roles: ERP_MERCHANT,
          optional: true,
        },
        {
          code: 'msup.core_channel_open',
          name: 'Abrir el canal de conversación',
          description: 'Canal del comercio con la mesa.',
          method: 'POST',
          path: '/support/channels',
          roles: CHAT_ROLES,
          optional: true,
          events: ['support.channel.opened'],
        },
        {
          code: 'msup.gw_message',
          name: 'Escribir en el chat (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/support/channels/:channelId/messages',
          roles: ERP_MERCHANT,
          optional: true,
          repeatable: true,
        },
        {
          code: 'msup.core_message',
          name: 'Registrar el mensaje del comercio',
          description: 'Mensaje en el canal abierto.',
          method: 'POST',
          path: '/support/channels/:channelId/messages',
          roles: CHAT_ROLES,
          optional: true,
          repeatable: true,
          events: ['support.message.created'],
        },
      ],
    },
    {
      code: 'msup_desk',
      name: 'La mesa de Atlas atiende el caso',
      description:
        'El caso del comercio aparece en /internal/support junto a los de clientes. El agente lo clasifica, lo toma, deja notas y lo resuelve con código de resolución y causa raíz; puede escalarlo. El detalle de la mesa está en el proceso P-12.',
      module: 'support',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/support',
      roles: DESK_ROLES,
      requiredStates: ['NEW'],
      resultingStates: ['RESOLVED'],
      steps: [
        {
          code: 'msup.desk_cases',
          name: 'Ver la cola de casos',
          description: 'Casos de clientes y comercios con filtros.',
          method: 'GET',
          path: '/internal/support/cases',
          roles: DESK_ROLES,
        },
        {
          code: 'msup.desk_case',
          name: 'Abrir la ficha del caso',
          description: 'Detalle del caso con sus partes.',
          method: 'GET',
          path: '/internal/support/cases/:caseId',
          roles: DESK_ROLES,
        },
        {
          code: 'msup.desk_triage',
          name: 'Clasificar el caso',
          description: 'Primera clasificación del caso en la mesa.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/triage',
          roles: DESK_ROLES,
          resultingStates: ['TRIAGED'],
        },
        {
          code: 'msup.desk_claim',
          name: 'Tomar el caso',
          description: 'Exige perfil de agente en la mesa.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/claim',
          roles: DESK_ROLES,
          resultingStates: ['ASSIGNED'],
          errors: ['403 SUPPORT_AGENT_PROFILE_REQUIRED'],
          events: ['support.case.assigned'],
        },
        {
          code: 'msup.desk_escalate',
          name: 'Escalar el caso',
          description: 'Cuando la mesa no puede resolverlo en su nivel.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/escalate',
          roles: DESK_ROLES,
          optional: true,
          resultingStates: ['ESCALATED'],
          events: ['support.case.escalated'],
        },
        {
          code: 'msup.desk_resolve',
          name: 'Resolver el caso',
          description: 'Con código de resolución y causa raíz.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/resolve',
          roles: DESK_ROLES,
          resultingStates: ['RESOLVED'],
          events: ['support.case.resolved'],
        },
      ],
    },
    {
      code: 'msup_sla',
      name: 'El sistema vigila el plazo',
      description: 'Barrido programado de plazos de la mesa: avisa de los casos por vencer, marca los vencidos y lo publica.',
      module: 'support',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      steps: [
        {
          code: 'msup.sla_sweep',
          name: 'Barrer los plazos de soporte',
          kind: 'job',
          job: 'sweep_support_sla',
          description:
            'Los casos por vencer publican support.sla.warning y los que superan su plazo, support.sla.breached; ambos llegan a operaciones como mensaje de bandeja.',
          events: ['support.sla.warning', 'support.sla.breached'],
        },
      ],
    },
    {
      code: 'msup_follow_and_close',
      name: 'El comercio sigue, cierra y valora',
      description:
        'El comercio ve sus casos y el detalle de cada uno, pide el cierre (inmediato si ya está resuelto) y valora la atención cuando está resuelto.',
      module: 'support',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/soporte',
      link: '{ERP}/portal-comercio/soporte',
      terminal: true,
      roles: ERP_MERCHANT,
      requiredStates: ['RESOLVED'],
      resultingStates: ['CLOSED'],
      steps: [
        {
          code: 'msup.gw_partner_cases',
          name: 'Ver mis casos (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant/support/partners/:partnerProfileId/cases',
          roles: ERP_MERCHANT,
          repeatable: true,
        },
        {
          code: 'msup.core_partner_cases',
          name: 'Casos del comercio',
          description: 'Sólo los del expediente del que el usuario es dueño.',
          method: 'GET',
          path: '/merchant/support/partners/:partnerProfileId/cases',
          roles: CORE_MERCHANT,
          repeatable: true,
        },
        {
          code: 'msup.gw_case',
          name: 'Ver un caso (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant/support/cases/:caseId',
          roles: ERP_MERCHANT,
        },
        {
          code: 'msup.core_case',
          name: 'Detalle del caso para el comercio',
          description: 'Lectura del caso, con el aislamiento entre comercios resuelto en el actor.',
          method: 'GET',
          path: '/merchant/support/cases/:caseId',
          roles: CORE_MERCHANT,
        },
        {
          code: 'msup.gw_close_request',
          name: 'Pedir el cierre (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/merchant/support/cases/:caseId/close-request',
          roles: ERP_MERCHANT,
        },
        {
          code: 'msup.core_close_request',
          name: 'Registrar la petición de cierre',
          description: 'Si el caso ya está resuelto, se cierra de inmediato (accepted:true, CLOSED); si no, queda registrada.',
          method: 'POST',
          path: '/merchant/support/cases/:caseId/close-request',
          roles: CORE_MERCHANT,
          resultingStates: ['CLOSED'],
        },
        {
          code: 'msup.gw_feedback',
          name: 'Valorar la atención (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/merchant/support/cases/:caseId/feedback',
          roles: ERP_MERCHANT,
          optional: true,
        },
        {
          code: 'msup.core_feedback',
          name: 'Registrar la valoración',
          description: 'Una sola por caso y sólo después de resuelto.',
          method: 'POST',
          path: '/merchant/support/cases/:caseId/feedback',
          roles: CORE_MERCHANT,
          optional: true,
          errors: ['409 SUPPORT_FEEDBACK_TOO_EARLY', '409 SUPPORT_FEEDBACK_ALREADY_SUBMITTED'],
        },
        {
          code: 'msup.desk_close',
          name: 'La mesa cierra el caso',
          description: 'Cierre por el agente cuando el comercio no lo pide.',
          method: 'POST',
          path: '/internal/support/cases/:caseId/close',
          roles: DESK_ROLES,
          optional: true,
          resultingStates: ['CLOSED'],
          events: ['support.case.closed'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'msup.entry',
      from: null,
      to: 'msup.gw_faq',
      condition: 'always',
      isDefault: true,
      description: 'Entrada: el comercio busca ayuda.',
    },
    {
      code: 'msup.faq_to_open',
      from: 'msup.gw_faq',
      to: 'msup.gw_case_open',
      condition: 'always',
      isDefault: true,
      description: 'Sin respuesta escrita, abre un caso.',
    },
    {
      code: 'msup.open_to_core',
      from: 'msup.gw_case_open',
      to: 'msup.core_case_open',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía.',
    },
    {
      code: 'msup.case_to_chat',
      from: 'msup.core_case_open',
      to: 'msup.gw_channel_open',
      condition: 'conditional',
      expression: { wantsChat: true },
      description: 'Además abre el chat.',
    },
    {
      code: 'msup.case_to_desk',
      from: 'msup.core_case_open',
      to: 'msup.desk_triage',
      condition: 'on_success',
      isDefault: true,
      description: 'El caso entra en la mesa.',
    },
    {
      code: 'msup.triage_to_claim',
      from: 'msup.desk_triage',
      to: 'msup.desk_claim',
      condition: 'on_success',
      isDefault: true,
      description: 'Un agente lo toma.',
    },
    {
      code: 'msup.claim_to_resolve',
      from: 'msup.desk_claim',
      to: 'msup.desk_resolve',
      condition: 'on_success',
      isDefault: true,
      description: 'Se resuelve.',
    },
    {
      code: 'msup.claim_to_escalate',
      from: 'msup.desk_claim',
      to: 'msup.desk_escalate',
      condition: 'conditional',
      expression: { needsEscalation: true },
      description: 'Hace falta otro nivel.',
    },
    {
      code: 'msup.escalate_to_resolve',
      from: 'msup.desk_escalate',
      to: 'msup.desk_resolve',
      condition: 'on_success',
      description: 'Resuelto tras escalar.',
    },
    {
      code: 'msup.resolve_to_close',
      from: 'msup.desk_resolve',
      to: 'msup.gw_close_request',
      condition: 'on_success',
      isDefault: true,
      description: 'El comercio pide el cierre.',
    },
    {
      code: 'msup.close_to_core',
      from: 'msup.gw_close_request',
      to: 'msup.core_close_request',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía.',
    },
    {
      code: 'msup.close_to_feedback',
      from: 'msup.core_close_request',
      to: 'msup.gw_feedback',
      condition: 'on_success',
      isDefault: true,
      description: 'El comercio valora.',
    },
    {
      code: 'msup.resolve_to_desk_close',
      from: 'msup.desk_resolve',
      to: 'msup.desk_close',
      condition: 'conditional',
      expression: { merchantSilent: true },
      description: 'La mesa cierra si el comercio no lo pide.',
    },
    {
      code: 'msup.exit',
      from: 'msup.gw_feedback',
      to: null,
      condition: 'always',
      isDefault: true,
      description: 'Salida: caso cerrado y valorado.',
    },
  ],
  dependencies: [
    {
      step: 'msup.core_case_open',
      dependsOn: 'msup.core_categories',
      type: 'requires_data',
      description: 'El caso se abre con una categoría del catálogo.',
    },
    { step: 'msup.desk_claim', dependsOn: 'msup.core_case_open', type: 'requires_data', description: 'Se toma un caso que existe.' },
    {
      step: 'msup.core_feedback',
      dependsOn: 'msup.desk_resolve',
      type: 'requires_completion',
      description: 'Sólo se valora un caso resuelto.',
    },
    {
      step: 'msup.core_close_request',
      dependsOn: 'msup.desk_resolve',
      type: 'soft',
      description: 'El cierre es inmediato sólo si ya está resuelto.',
    },
  ],
};
