/**
 * @file Proceso declarado en código: QR de cobro, sucursales, terminales POS y expediente del comercio.
 * @business Un cliente sólo transfiere a la cuenta que una persona de Atlas aprobó: este proceso lleva el QR de cobro del comercio, sus sucursales y cajas desde que el comercio los sube hasta que la app los enseña, dejando cada archivo en el expediente del comercio.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; cadena ERP (pasarela `partner-onboarding-gateway`) → AtlasBackend (`partner-commerce.controller.ts`, `partner-operations.controller.ts`, `merchant-qr.controller.ts`, `expedientes`) → app del cliente.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** `@Roles` de la pasarela `partner-onboarding-gateway.controller.ts` del ERP. */
const ERP_MERCHANT = ['merchant', 'MERCHANT_ADMIN', 'MERCHANT_OPERATIONS', 'ADMIN'];
/** `@Roles` de `partner-commerce.controller.ts` de AtlasBackend. */
const PARTNER_ROLES = ['merchant', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
/** `@Roles` de clase de `partner-operations.controller.ts`. */
const OPS_ROLES = ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
/** `@Roles` de `merchant-qr.controller.ts`. */
const QR_CONSUMER = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
/** `@Roles` de `mobile-payment-claims.controller.ts`. */
const MOBILE_CLAIMS = ['customer', 'internal_operator', 'admin', 'platform_admin'];
/** `@Roles` de clase de los controladores de `expedientes`. */
const FILES_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'];
/** `@Roles` de `onboarding.controller.ts` del ERP para las sucursales internas. */
const ERP_BRANCH_WRITE = ['OPERATIONS', 'ADMIN', 'MERCHANT_ADMIN'];

export const MERCHANT_QR_POS_AND_FILE: WorkflowDefinitionFixture = {
  processId: 'P-17',
  code: 'merchant_qr_pos_and_file',
  version: 'v1',
  name: 'QR de cobro, sucursales, terminales POS y expediente del comercio',
  description:
    'El comercio registra sus sucursales y cajas y sube su QR de cobro desde «Mi empresa» del portal del comercio; el ERP lo reenvía a AtlasBackend, que decodifica la imagen, la guarda en el expediente del comercio y la deja en pending_review. Una persona con partner.qr.review la aprueba o rechaza en el portal admin; sólo el QR activo llega a la app del cliente.',
  processType: 'back_office',
  ownerDomain: 'merchant_onboarding',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ERP_BACKEND', 'ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'El QR de cobro decide a qué cuenta transfiere el dinero un cliente, y la caja decide qué comercio vende a crédito. Sin una revisión humana del QR, cualquiera que controle el portal de un comercio podría desviar cobros; sin cajas activas, el QR de mostrador no resuelve. Además cada archivo que sube el comercio tiene que quedar en su expediente, visible para Operaciones.',
    whoStartsAndCloses:
      'Lo inicia la persona del comercio desde «Mi empresa» (pestañas «Mi QR de cobro» y «Sucursales») del portal del comercio; lo cierra una persona de Operaciones de comercios (rol MERCHANT_OPERATIONS, permiso partner.qr.review) al aprobar o rechazar el QR en el portal admin. El cliente final sólo consume el resultado desde la app.',
    startAndEnd:
      'Empieza cuando el comercio sube un QR y queda en pending_review (POST /partner-onboarding/:partnerId/qr-codes); termina cuando la revisión lo deja active con verified_at y revisor (el anterior del mismo ámbito pasa a replaced) o rejected con la nota que el comercio lee. La app sólo ve el QR active.',
    whenItFails:
      'Una imagen sin código se rechaza al subirla (QR_OBJECT_NOT_AN_IMAGE, QR_IMAGE_UNREADABLE); un expediente en under_review no admite QR nuevo (PARTNER_NOT_EDITABLE_IN_STATUS). Revisar un QR ya decidido responde 409 QR_NOT_PENDING_REVIEW. Una caja suspendida hace que el QR de mostrador responda 422 QR_EXPIRED y la app lo rechaza. Si nadie revisa, el QR queda en la cola del portal admin, el más antiguo primero.',
    healthIndicator:
      'Cantidad y antigüedad de los QR en pending_review (GET /operations/partners/qr-codes/pending), comercios aprobados sin QR bancario activo de empresa, y cajas activas que resuelven en /merchant-qr/resolve frente a las que responden QR_EXPIRED.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'partner',
    table: 'partner_qr_codes',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'qr_kind',
    openStatuses: ['pending_review'],
  },
  success:
    'El QR queda active con verified_at y revisor, las cajas del comercio están activas y la app del cliente enseña el QR bancario aprobado de la empresa.',
  failure:
    'El QR se rechaza al subirlo o en la revisión, se queda en pending_review sin nadie que lo mire, o la caja está suspendida y el QR de mostrador no resuelve.',
  sources: [
    'src/modules/partner-onboarding/partner-commerce.controller.ts',
    'src/modules/partner-onboarding/partner-operations.controller.ts',
    'src/modules/partner-onboarding/merchant-qr.controller.ts',
    'src/modules/partner-onboarding/application/partner-qr.service.ts',
    'src/modules/partner-onboarding/application/partner-qr-review.service.ts',
    'src/modules/partner-onboarding/partner-commercial-network.repository.ts',
    'src/modules/partner-onboarding/partner-onboarding.repository.ts (PAYMENT_QR_EDITABLE_STATUSES)',
    'src/modules/internal-users/internal-rbac.permissions.ts (partner.qr.review → MERCHANT_OPERATIONS)',
    'src/modules/expedientes/expedientes.controller.ts',
    'src/database/models/partner-qr-codes.model.ts',
    'AtlasERPBackend/src/modules/partner-onboarding-gateway/partner-onboarding-gateway.controller.ts',
    'AtlasERPFrontend/components/screens/PartnerDossierScreen.tsx',
    'AtlasERPFrontend/components/screens/MerchantStructureScreen.tsx',
    'AtlasAdminPortal/src/features/partner-decisions/partner-decisions-page.tsx',
    'AtlasFrontend/apps/consumer-app/src/api/endpoints/loans.ts',
    'AtlasFrontend/apps/consumer-app/src/api/endpoints/payment-claims.ts',
    'memoria atlas-expediente-del-comercio',
    'memoria atlas-portal-comercio-cinco-entradas',
    'memoria atlas-flujo-pago-qr-comprobante',
  ],
  metadata: {
    gaps: [
      'Las rutas de sucursales, terminales y QR de AtlasBackend no tienen llamador directo: el portal del comercio las usa por la pasarela del ERP (se documentan los dos tramos).',
      'Hay dos libros de sucursales: las del ERP (atlas_sales.merchant_branches, /portal/branches y /b2b/onboarding/branches) y las del expediente de Atlas (partner.partner_branches); «Sucursales» las enlaza a mano. GET /portal/branches no figura en la copia de endpoints del ERP.',
      'El expediente del comercio sólo existe para comercios dados de alta desde el 2026-09-17: el relleno histórico de Archivos sigue siendo sólo de clientes.',
      'Ni la suspensión de una caja ni la aprobación de un expediente tienen vuelta atrás por API.',
    ],
  },
  stages: [
    {
      code: 'qr_branches_and_pos',
      name: 'El comercio registra sus sucursales y cajas',
      description:
        'Pestaña «Sucursales» de «Mi empresa»: el comercio registra sus locales en el expediente, les da de alta cajas (terminales POS) y las suspende o reactiva desde la fila. Cada caja lleva su QR de mostrador.',
      module: 'partner_onboarding',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/expediente',
      link: '{ERP}/portal-comercio/expediente?tab=sucursales',
      entry: true,
      roles: ERP_MERCHANT,
      steps: [
        {
          code: 'qr.gw_branch_create',
          name: 'Registrar una sucursal (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend con el token del comercio.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/branches',
          roles: ERP_MERCHANT,
        },
        {
          code: 'qr.core_branch_create',
          name: 'Crear la sucursal del expediente',
          description: 'Admitido mientras el expediente está en trámite o aprobado.',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/branches',
          roles: PARTNER_ROLES,
        },
        {
          code: 'qr.gw_branch_update',
          name: 'Editar o enlazar una sucursal (pasarela del ERP)',
          description: 'También enlaza la sucursal del expediente con la del ERP.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/partner-onboarding/:partnerId/branches/:branchId',
          roles: ERP_MERCHANT,
          optional: true,
        },
        {
          code: 'qr.core_branch_update',
          name: 'Actualizar la sucursal del expediente',
          description: 'Datos de la sucursal en partner_branches.',
          method: 'PATCH',
          path: '/partner-onboarding/:partnerId/branches/:branchId',
          roles: PARTNER_ROLES,
          optional: true,
        },
        {
          code: 'qr.gw_branch_list',
          name: 'Ver las sucursales (pasarela del ERP)',
          description: 'Lista las sucursales del expediente.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/branches',
          roles: ERP_MERCHANT,
          repeatable: true,
        },
        {
          code: 'qr.core_branch_list',
          name: 'Listar las sucursales del expediente',
          description: 'Lectura de partner_branches.',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/branches',
          roles: PARTNER_ROLES,
          repeatable: true,
        },
        {
          code: 'qr.gw_pos_create',
          name: 'Registrar una caja (pasarela del ERP)',
          description: '«Registrar caja» en modal desde la fila de la sucursal.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/branches/:branchId/pos-terminals',
          roles: ERP_MERCHANT,
        },
        {
          code: 'qr.core_pos_create',
          name: 'Crear el terminal POS',
          description: 'Nace la caja con su serial; el serial es el contenido del QR de mostrador.',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/branches/:branchId/pos-terminals',
          roles: PARTNER_ROLES,
        },
        {
          code: 'qr.gw_pos_list',
          name: 'Ver las cajas (pasarela del ERP)',
          description: 'El QR de cada caja va en la tabla, una columna por fila.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/pos-terminals',
          roles: ERP_MERCHANT,
          repeatable: true,
        },
        {
          code: 'qr.core_pos_list',
          name: 'Listar los terminales POS',
          description: 'Lectura de partner_pos_terminals.',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/pos-terminals',
          roles: PARTNER_ROLES,
          repeatable: true,
        },
        {
          code: 'qr.gw_pos_status',
          name: 'Suspender o reactivar una caja (pasarela del ERP)',
          description: 'Desde la fila de la caja.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/partner-onboarding/:partnerId/pos-terminals/:terminalId',
          roles: ERP_MERCHANT,
          optional: true,
        },
        {
          code: 'qr.core_pos_status',
          name: 'Cambiar el estado del terminal',
          description: 'Una caja no active hace que su QR de mostrador responda QR_EXPIRED; no se puede volver a registered.',
          method: 'PATCH',
          path: '/partner-onboarding/:partnerId/pos-terminals/:terminalId',
          roles: PARTNER_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'qr_upload',
      name: 'El comercio sube su QR de cobro',
      description:
        'Pestaña «Mi QR de cobro»: la imagen va directa al almacén con una URL firmada (sin la credencial del portal) y después se registra; manda el servidor, que decodifica la imagen y rechaza la que no lleva código. Un QR no se edita: se reemplaza.',
      module: 'partner_onboarding',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/expediente',
      link: '{ERP}/portal-comercio/expediente?tab=qr',
      roles: ERP_MERCHANT,
      resultingStates: ['pending_review'],
      steps: [
        {
          code: 'qr.gw_upload_url',
          name: 'Pedir permiso de subida (pasarela del ERP)',
          description: 'Reenvío a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/qr-codes/upload-url',
          roles: ERP_MERCHANT,
        },
        {
          code: 'qr.core_upload_url',
          name: 'Emitir la URL firmada de subida',
          description: 'Sin almacén configurado responde 503 DOCUMENT_STORAGE_NOT_CONFIGURED.',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/qr-codes/upload-url',
          roles: PARTNER_ROLES,
          errors: ['503 DOCUMENT_STORAGE_NOT_CONFIGURED'],
        },
        {
          code: 'qr.storage_put',
          name: 'Subir la imagen al almacén',
          kind: 'external',
          reason:
            'El navegador sube los bytes directo a MinIO con la URL firmada; ni el ERP ni AtlasBackend están en medio de esa transferencia.',
          description: 'Va a /atlas-evidence; un 200 del almacén no prueba nada, lo prueba el registro siguiente.',
        },
        {
          code: 'qr.gw_register',
          name: 'Registrar el QR subido (pasarela del ERP)',
          description: 'Reenvío a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/qr-codes',
          roles: ERP_MERCHANT,
        },
        {
          code: 'qr.core_register',
          name: 'Registrar el QR y dejarlo en revisión',
          description:
            'Lee el objeto, comprueba que es una imagen con código y lo crea en pending_review. Admitido con el expediente editable o aprobado; nunca en under_review.',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/qr-codes',
          roles: PARTNER_ROLES,
          resultingStates: ['pending_review'],
          errors: [
            '422 QR_OBJECT_NOT_FOUND',
            '422 QR_OBJECT_NOT_AN_IMAGE',
            '422 QR_IMAGE_UNREADABLE',
            '422 QR_OBJECT_OUTSIDE_PARTNER_SCOPE',
            '422 PARTNER_NOT_EDITABLE_IN_STATUS',
          ],
        },
        {
          code: 'qr.file_hook',
          name: 'Guardar el QR en el expediente del comercio',
          kind: 'event',
          reason:
            'Gancho interno alRegistrarArchivoDelComercio dentro del registro del QR: no es una llamada HTTP ni un evento del outbox, y es tolerante a fallo.',
          description: 'Va a la carpeta «qr» con clase partner_qr_bank o partner_qr_business.',
        },
        {
          code: 'qr.gw_list',
          name: 'Ver mis QR (pasarela del ERP)',
          description: 'El comercio ve lo que hay, revisado o no.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/qr-codes',
          roles: ERP_MERCHANT,
          repeatable: true,
        },
        {
          code: 'qr.core_list',
          name: 'Listar los QR del expediente',
          description: 'Incluye los pending_review y los rechazados con su nota.',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/qr-codes',
          roles: PARTNER_ROLES,
          repeatable: true,
        },
        {
          code: 'qr.gw_content',
          name: 'Ver la imagen del QR (pasarela del ERP)',
          description: 'Bytes, no URL prefirmada; el ERP la trae como blob.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/qr-codes/:qrId/content',
          roles: ERP_MERCHANT,
          optional: true,
        },
        {
          code: 'qr.core_content',
          name: 'Servir la imagen del QR',
          description: 'StreamableFile con la imagen guardada.',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/qr-codes/:qrId/content',
          roles: PARTNER_ROLES,
          optional: true,
          errors: ['404 QR_NOT_FOUND', '404 QR_OBJECT_NOT_FOUND'],
        },
      ],
    },
    {
      code: 'qr_review',
      name: 'Operaciones de comercios revisa el QR',
      description:
        'Cola de QR en pending_review del portal admin, aparte de la de expedientes: un comercio ya aprobado cambia su QR cuando quiere y también pasa por una persona. Aprobar activa y archiva el anterior del mismo ámbito; rechazar exige nota.',
      module: 'partner_onboarding',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/partners',
      roles: ['MERCHANT_OPERATIONS', 'SUPER_ADMIN'],
      requiredStates: ['pending_review'],
      resultingStates: ['active', 'rejected'],
      steps: [
        {
          code: 'qr.core_pending',
          name: 'Ver la cola de QR por revisar',
          description: 'Todos los QR en pending_review del inquilino, el más antiguo primero, con su comercio.',
          method: 'GET',
          path: '/operations/partners/qr-codes/pending',
          roles: OPS_ROLES,
          repeatable: true,
        },
        {
          code: 'qr.core_review',
          name: 'Aprobar o rechazar el QR',
          description:
            'Además del rol exige el permiso partner.qr.review (MERCHANT_OPERATIONS): quien pide el alta no puede activar la cuenta a la que van los cobros. Es el único camino a active.',
          method: 'POST',
          path: '/operations/partners/:partnerId/qr-codes/:qrId/review',
          roles: OPS_ROLES,
          resultingStates: ['active', 'rejected', 'replaced'],
          input: { approved: 'boolean', note: 'string (obligatoria al rechazar)' },
          errors: ['404 QR_NOT_FOUND', '409 QR_NOT_PENDING_REVIEW', '403 partner.qr.review'],
        },
      ],
    },
    {
      code: 'qr_file_view',
      name: 'Operaciones consulta el expediente del comercio',
      description:
        'Operaciones › Archivos, con el filtro «Tipo» Comercio: carpetas qr, documentos y otros del comercio, con todo lo que subió.',
      module: 'expedientes',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/files',
      optional: true,
      roles: FILES_ROLES,
      steps: [
        {
          code: 'qr.files_list',
          name: 'Listar expedientes de comercios',
          description: 'Filtro subjectType=partner.',
          method: 'GET',
          path: '/expedientes',
          roles: FILES_ROLES,
          optional: true,
        },
        {
          code: 'qr.files_nodes',
          name: 'Ver las carpetas y archivos del comercio',
          description: 'Nodos del expediente: carpetas qr, documentos, otros.',
          method: 'GET',
          path: '/expedientes/:id/nodos',
          roles: FILES_ROLES,
          optional: true,
        },
        {
          code: 'qr.files_content',
          name: 'Abrir un archivo del comercio',
          description: 'Contenido del nodo (imagen del QR, poder notarial…).',
          method: 'GET',
          path: '/expedientes/:id/nodos/:nodoId/contenido',
          roles: FILES_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'qr_erp_branches',
      name: 'El ERP mantiene sus propias sucursales del comercio',
      description:
        'CRM › Sucursales del ERP: las sucursales comerciales de la cuenta B2B, cuya columna importante es can_originate_bnpl (se habilita al activar el comercio). Es el otro libro de sucursales.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/sucursales',
      link: '{ERP}/operaciones/crm/sucursales',
      optional: true,
      roles: ERP_BRANCH_WRITE,
      steps: [
        {
          code: 'qr.erp_branch_list',
          name: 'Listar las sucursales del ERP',
          system: 'ERP_BACKEND',
          description: 'Sucursales de atlas_sales.merchant_branches.',
          method: 'GET',
          path: '/b2b/onboarding/branches',
          roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_EXECUTIVE', 'COMMERCIAL_MANAGER', 'FINANCE'],
          optional: true,
        },
        {
          code: 'qr.erp_branch_create',
          name: 'Crear una sucursal en el ERP',
          system: 'ERP_BACKEND',
          description: 'Nace PENDING; pasa a ACTIVE al activar el comercio.',
          method: 'POST',
          path: '/b2b/onboarding/branches',
          roles: ERP_BRANCH_WRITE,
          optional: true,
        },
        {
          code: 'qr.erp_branch_status',
          name: 'Cambiar el estado de una sucursal del ERP',
          system: 'ERP_BACKEND',
          description: 'Activa, inactiva o suspende la sucursal comercial.',
          method: 'PATCH',
          path: '/b2b/onboarding/branches/:branchId/status',
          roles: ERP_BRANCH_WRITE,
          optional: true,
        },
      ],
    },
    {
      code: 'qr_consumer_sees',
      name: 'La app del cliente usa el QR aprobado',
      description:
        'El cliente escanea el QR de caja y la app lo resuelve al comercio verificado; para pagar una cuota la app recibe embebido el QR bancario activo de la empresa. Sólo lo active llega aquí.',
      module: 'partner_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      terminal: true,
      requiredStates: ['active'],
      steps: [
        {
          code: 'qr.app_resolve',
          name: 'Resolver el QR de caja',
          description: 'Caja active y expediente approved → comercio con verified:true.',
          method: 'POST',
          path: '/merchant-qr/resolve',
          roles: QR_CONSUMER,
          errors: ['404 QR_NOT_RECOGNIZED', '422 QR_EXPIRED', '422 QR_REVOKED'],
        },
        {
          code: 'qr.app_payment_qr',
          name: 'Obtener el QR bancario del comercio de una caja',
          description: 'El QR bancario aprobado del comercio al que pertenece una caja activa.',
          method: 'POST',
          path: '/merchant-qr/payment',
          roles: QR_CONSUMER,
          optional: true,
        },
        {
          code: 'qr.app_installment_instructions',
          name: 'Instrucciones de pago de una cuota',
          description: 'Incluye el QR bancario activo de la empresa (branchId nulo) como data: dentro del JSON.',
          method: 'GET',
          path: '/mobile/customers/:customerId/payment-claims/instructions/:installmentId',
          roles: MOBILE_CLAIMS,
          optional: true,
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'qr.entry',
      from: null,
      to: 'qr.gw_branch_create',
      condition: 'always',
      isDefault: true,
      description: 'Entrada: el comercio registra su estructura.',
    },
    {
      code: 'qr.branch_to_core',
      from: 'qr.gw_branch_create',
      to: 'qr.core_branch_create',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía.',
    },
    {
      code: 'qr.branch_to_pos',
      from: 'qr.core_branch_create',
      to: 'qr.gw_pos_create',
      condition: 'on_success',
      isDefault: true,
      description: 'Con sucursal, se registran cajas.',
    },
    {
      code: 'qr.pos_to_core',
      from: 'qr.gw_pos_create',
      to: 'qr.core_pos_create',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía.',
    },
    {
      code: 'qr.pos_to_upload',
      from: 'qr.core_pos_create',
      to: 'qr.gw_upload_url',
      condition: 'on_success',
      isDefault: true,
      description: 'Se sube el QR de cobro.',
    },
    {
      code: 'qr.url_to_core',
      from: 'qr.gw_upload_url',
      to: 'qr.core_upload_url',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía.',
    },
    {
      code: 'qr.url_to_put',
      from: 'qr.core_upload_url',
      to: 'qr.storage_put',
      condition: 'on_success',
      isDefault: true,
      description: 'El navegador sube la imagen.',
    },
    {
      code: 'qr.put_to_register',
      from: 'qr.storage_put',
      to: 'qr.gw_register',
      condition: 'on_success',
      isDefault: true,
      description: 'Se registra lo subido.',
    },
    {
      code: 'qr.register_to_core',
      from: 'qr.gw_register',
      to: 'qr.core_register',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía.',
    },
    {
      code: 'qr.register_retry',
      from: 'qr.core_register',
      to: 'qr.gw_upload_url',
      condition: 'on_error',
      description: 'Imagen sin código o ilegible: se vuelve a subir.',
    },
    {
      code: 'qr.register_to_file',
      from: 'qr.core_register',
      to: 'qr.file_hook',
      condition: 'on_success',
      isDefault: true,
      description: 'El archivo va al expediente.',
    },
    {
      code: 'qr.file_to_review',
      from: 'qr.file_hook',
      to: 'qr.core_review',
      condition: 'always',
      isDefault: true,
      description: 'Una persona lo revisa.',
    },
    {
      code: 'qr.review_rejected',
      from: 'qr.core_review',
      to: 'qr.gw_upload_url',
      condition: 'conditional',
      expression: { approved: false },
      description: 'Rechazado: el comercio lee la nota y sube otro.',
    },
    {
      code: 'qr.review_to_app',
      from: 'qr.core_review',
      to: 'qr.app_resolve',
      condition: 'conditional',
      expression: { approved: true },
      isDefault: true,
      description: 'Activo: la app ya lo usa.',
    },
    {
      code: 'qr.exit',
      from: 'qr.app_resolve',
      to: null,
      condition: 'on_success',
      isDefault: true,
      description: 'Salida: el cliente ve el comercio verificado.',
    },
  ],
  dependencies: [
    {
      step: 'qr.core_pos_create',
      dependsOn: 'qr.core_branch_create',
      type: 'requires_data',
      description: 'La caja cuelga de una sucursal.',
    },
    {
      step: 'qr.core_register',
      dependsOn: 'qr.storage_put',
      type: 'requires_completion',
      description: 'Se registra un objeto que ya está en el almacén.',
    },
    {
      step: 'qr.core_review',
      dependsOn: 'qr.core_register',
      type: 'requires_completion',
      description: 'Sólo se revisa lo que está en pending_review.',
    },
    {
      step: 'qr.app_resolve',
      dependsOn: 'qr.core_pos_status',
      type: 'soft',
      description: 'Con la caja suspendida el QR responde QR_EXPIRED.',
    },
    {
      step: 'qr.app_installment_instructions',
      dependsOn: 'qr.core_review',
      type: 'requires_completion',
      description: 'La app sólo enseña el QR active.',
    },
  ],
};
