/**
 * @file Proceso declarado en código: CRM del comercio: alta comercial, calificación, propuesta, pricing y contratación.
 * @business Antes de que un comercio pueda vender a crédito hay que pactar con él cuánto cobra Atlas por cada venta y bajo qué contrato; este proceso lleva la cuenta B2B de prospecto a cliente con una comisión aprobada y un contrato firmado.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; rutas del CRM del ERP (`b2b/accounts`, `b2b/opportunities`, `b2b/proposals`, `b2b/contracts`), la plantilla legal de AtlasBackend (`operations/partner-contract-templates`) y la proyección `merchant.mdr.updated` que Core recibe en `internal/integration/erp/events`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** `@Roles` de escritura de cuentas, oportunidades y propuestas del ERP. */
const SALES = ['COMMERCIAL_EXECUTIVE', 'COMMERCIAL_MANAGER', 'ADMIN'];
/** `@Roles` de las reglas MDR y de la decisión de aprobaciones. */
const PRICING = ['COMMERCIAL_MANAGER', 'FINANCE', 'ADMIN'];
/** `@Roles` de creación y firma de contratos. */
const LEGAL = ['LEGAL', 'COMMERCIAL_MANAGER', 'ADMIN'];
/** `@Roles` de clase de `partner-contract-templates.controller.ts`. */
const TEMPLATE_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'];

export const MERCHANT_CONTRACT_AND_PRICING: WorkflowDefinitionFixture = {
  processId: 'P-19',
  code: 'merchant_contract_and_pricing',
  version: 'v1',
  name: 'CRM del comercio: alta comercial, calificación, propuesta, pricing y contratación',
  description:
    'El ejecutivo comercial crea la cuenta B2B y la califica; arma la propuesta con su comisión por venta (MDR); si la comisión está por debajo del mínimo la aprueba Gerencia o Finanzas; Legal crea el contrato desde la propuesta aceptada y lo firma. Atlas publica el texto legal por defecto y recibe la comisión pactada para enseñarla en el portal del comercio.',
  processType: 'back_office',
  ownerDomain: 'b2b_sales_crm',
  ownerRole: 'ERP:COMMERCIAL_MANAGER',
  priority: 'P1',
  systems: ['ERP_BACKEND', 'ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'La comisión que Atlas cobra al comercio por cada venta a crédito es un término comercial: tiene que pactarse, aprobarse si baja del mínimo y quedar congelada en un contrato firmado. Sin esto una venta no sabría qué comisión aplicar y la misma pregunta tendría dos respuestas; por eso el porcentaje plano del portal admin se retiró y el ERP es la autoridad del término.',
    whoStartsAndCloses:
      'Lo inicia un ejecutivo comercial del ERP (COMMERCIAL_EXECUTIVE) al crear la cuenta B2B; aprueba las comisiones bajo el mínimo Gerencia comercial o Finanzas (COMMERCIAL_MANAGER, FINANCE); lo cierra Legal (LEGAL) al firmar y activar el contrato. El texto legal por defecto lo publica Operaciones de Atlas desde el portal admin.',
    startAndEnd:
      'Empieza con la cuenta en LEAD (POST /b2b/accounts) y pasa a QUALIFIED (o DISQUALIFIED con motivo); la propuesta va de DRAFT, con PENDING_APPROVAL si la comisión baja del mínimo, a SENT y ACCEPTED, y la oportunidad a CONTRACTING. Termina con el contrato y su versión en ACTIVE y la oportunidad en CLOSED_WON; la cuenta pasa a CUSTOMER al activar el onboarding.',
    whenItFails:
      'Una propuesta con aprobación pendiente no se puede enviar; una oportunidad no pasa a CONTRACTING sin propuesta aceptada; un contrato sin versión inicial no se firma (409). Una regla de comisión creada sobre el id del contrato en vez del de su versión devolvía 404 y listaba vacío: nunca se pudo pactar una comisión desde el ERP hasta que el listado empezó a devolver currentVersionId.',
    healthIndicator:
      'Propuestas en PENDING_APPROVAL y su antigüedad (GET /b2b/proposals/approvals), contratos firmados frente a propuestas aceptadas, y comercios con contrato activo cuya regla general de comisión llegó a Atlas (partner_profiles.mdr_rate_percent con fecha efectiva).',
  },
  instanceEntity: {
    system: 'ERP_BACKEND',
    schema: 'atlas_sales',
    table: 'b2b_accounts',
    idColumn: 'id',
    statusColumn: 'lifecycle_status',
    labelColumn: 'legal_name',
    openStatuses: ['LEAD', 'QUALIFIED'],
  },
  success: 'Contrato y versión ACTIVE con sus términos y reglas MDR, oportunidad CLOSED_WON y la comisión general proyectada en Atlas.',
  failure: 'La cuenta se descalifica, la propuesta se rechaza o su comisión no se aprueba, o el contrato no llega a firmarse.',
  sources: [
    'AtlasERPBackend/docs/architecture/flows.md (Alta comercial, Calificación, Propuesta y pricing, Contratación)',
    'AtlasERPBackend/src/modules/b2b-sales-crm/b2b-sales-crm.enums.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-pipeline.service.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-contracts.service.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/mdr-updated-publisher.support.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/controllers/b2b-accounts.controller.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/controllers/proposals.controller.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/controllers/contracts.controller.ts',
    'src/modules/partner-onboarding/partner-contract-templates.controller.ts',
    'src/modules/erp-integration/erp-event-inbox.service.ts (merchant.mdr.updated)',
    'AtlasAdminPortal/src/app/internal/settings/partner-contracts/page.tsx',
    'AtlasERPFrontend/app/operaciones/crm/contratos/page.tsx',
    '_plan-produccion-siete-repos-2026-09-24/04_DOMINIO_Y_AUTORIDAD.md (DEC-01)',
    'memoria atlas-erp-uuid-de-otra-entidad',
    'memoria atlas-onboarding-cadena-comercios',
    'memoria atlas-alta-comercio-por-cola',
  ],
  metadata: {
    gaps: [
      'DEC-01 (autoridad del contrato B2B, del MDR y de la factura de comisión) sigue abierta en el plan de los siete repos.',
      'El inventario nombraba CHURNED; los estados reales de la cuenta son LEAD, QUALIFIED, CUSTOMER, SUSPENDED, TERMINATED y DISQUALIFIED.',
      'Los PlantUML de julio (docs/source-models/diagrams/plantuml/05..07) no se contrastaron aquí con el código.',
      'La plantilla legal por defecto de Atlas y el contrato B2B del ERP son dos documentos distintos: el ERP sólo lee la plantilla, no la versiona.',
    ],
  },
  stages: [
    {
      code: 'crm_account',
      name: 'Alta comercial de la cuenta',
      description: 'El ejecutivo crea la cuenta B2B (valida duplicados por NIT o nombre) en LEAD con su contacto principal.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/cuentas/crear',
      link: '{ERP}/operaciones/crm/cuentas/crear',
      entry: true,
      roles: SALES,
      resultingStates: ['LEAD'],
      steps: [
        {
          code: 'crm.account_create',
          name: 'Crear la cuenta B2B',
          description: 'Nace en LEAD; también admite importación desde Excel en «Cuentas».',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/accounts',
          roles: SALES,
          resultingStates: ['LEAD'],
        },
        {
          code: 'crm.account_contact',
          name: 'Registrar el contacto principal',
          description: 'Persona de contacto de la cuenta.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/accounts/:accountId/contacts',
          roles: SALES,
        },
        {
          code: 'crm.account_list',
          name: 'Ver las cuentas',
          description: 'Directorio de cuentas B2B.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/accounts',
          roles: ['COMMERCIAL_EXECUTIVE', 'COMMERCIAL_MANAGER', 'FINANCE', 'LEGAL', 'OPERATIONS', 'ADMIN'],
          repeatable: true,
        },
      ],
    },
    {
      code: 'crm_qualify',
      name: 'Calificación y oportunidad',
      description:
        'Con fit, la cuenta pasa a QUALIFIED y opcionalmente abre una oportunidad en DISCOVERY; sin fit, DISQUALIFIED con motivo.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/cuentas/calificar',
      link: '{ERP}/operaciones/crm/cuentas/calificar',
      roles: SALES,
      requiredStates: ['LEAD'],
      resultingStates: ['QUALIFIED', 'DISQUALIFIED'],
      steps: [
        {
          code: 'crm.account_qualify',
          name: 'Calificar la cuenta',
          description: 'QUALIFIED o DISQUALIFIED conservando el motivo.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/accounts/:accountId/qualify',
          roles: SALES,
          resultingStates: ['QUALIFIED', 'DISQUALIFIED'],
        },
        {
          code: 'crm.opportunity_create',
          name: 'Abrir la oportunidad',
          description: 'Nace en DISCOVERY; no se abre sobre una cuenta DISQUALIFIED.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/opportunities',
          roles: SALES,
          optional: true,
        },
        {
          code: 'crm.opportunity_stage',
          name: 'Avanzar la oportunidad',
          description: 'No pasa a CONTRACTING sin propuesta aceptada.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/opportunities/:id/stage',
          roles: SALES,
          optional: true,
          repeatable: true,
          errors: ['409 La oportunidad no puede pasar a CONTRACTING sin propuesta aceptada'],
        },
      ],
    },
    {
      code: 'crm_proposal',
      name: 'Propuesta y pricing',
      description:
        'El ejecutivo arma la propuesta con líneas (MDR, suscripción, cargos). Si la comisión queda bajo el mínimo configurado nace una solicitud MDR_BELOW_MINIMUM y la propuesta no se puede enviar.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/propuestas',
      link: '{ERP}/operaciones/crm/propuestas',
      roles: SALES,
      requiredStates: ['QUALIFIED'],
      steps: [
        {
          code: 'crm.proposal_create',
          name: 'Crear la propuesta',
          description: 'Nace DRAFT, o PENDING_APPROVAL si la comisión baja del mínimo.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/proposals',
          roles: SALES,
          resultingStates: ['DRAFT', 'PENDING_APPROVAL'],
        },
        {
          code: 'crm.proposal_update',
          name: 'Editar la propuesta',
          description: 'Ajustar líneas antes de enviarla.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/proposals/:proposalId',
          roles: SALES,
          optional: true,
        },
        {
          code: 'crm.proposal_send',
          name: 'Enviar la propuesta',
          description: 'No se envía con aprobación pendiente.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/proposals/:proposalId/send',
          roles: SALES,
          resultingStates: ['SENT'],
        },
        {
          code: 'crm.proposal_accept',
          name: 'Registrar que el comercio acepta',
          description: 'Propuesta ACCEPTED y oportunidad a CONTRACTING.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/proposals/:proposalId/accept',
          roles: SALES,
          resultingStates: ['ACCEPTED'],
        },
        {
          code: 'crm.proposal_reject',
          name: 'Registrar que el comercio rechaza',
          description: 'Con motivo.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/proposals/:proposalId/reject',
          roles: SALES,
          optional: true,
          resultingStates: ['REJECTED'],
        },
      ],
    },
    {
      code: 'crm_pricing_approval',
      name: 'Aprobación de la comisión bajo el mínimo',
      description:
        'Una sola cola para propuestas y reglas de comisión bajo el mínimo. Aprobada, la propuesta vuelve a DRAFT y puede enviarse.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/aprobaciones',
      link: '{ERP}/operaciones/crm/aprobaciones',
      optional: true,
      roles: PRICING,
      requiredStates: ['PENDING_APPROVAL'],
      steps: [
        {
          code: 'crm.approvals_list',
          name: 'Ver las aprobaciones pendientes',
          description: 'Solicitudes MDR_BELOW_MINIMUM.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/proposals/approvals',
          roles: ['COMMERCIAL_MANAGER', 'FINANCE', 'LEGAL', 'ADMIN'],
          optional: true,
        },
        {
          code: 'crm.approval_decide',
          name: 'Aprobar o rechazar la excepción de comisión',
          description: 'APPROVED devuelve la propuesta a DRAFT; REJECTED la deja sin poder enviarse.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/proposals/approvals/:id/decision',
          roles: PRICING,
          optional: true,
          resultingStates: ['APPROVED', 'REJECTED'],
        },
      ],
    },
    {
      code: 'crm_contract',
      name: 'Contratación',
      description:
        'Legal crea el contrato desde la propuesta aceptada: nace b2b_contract con su versión inicial y las líneas se congelan como términos comerciales. Al firmar, contrato y versión pasan a ACTIVE y la oportunidad a CLOSED_WON.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/contratos',
      link: '{ERP}/operaciones/crm/contratos',
      roles: LEGAL,
      requiredStates: ['ACCEPTED'],
      resultingStates: ['ACTIVE'],
      steps: [
        {
          code: 'crm.contract_from_proposal',
          name: 'Crear el contrato desde la propuesta',
          description: 'Contrato y versión inicial con los términos congelados.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/contracts/from-proposal',
          roles: LEGAL,
        },
        {
          code: 'crm.contract_sign',
          name: 'Firmar y activar el contrato',
          description: 'Contrato y versión ACTIVE; publica la comisión general al outbox si la cuenta está enlazada a Atlas.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/contracts/:contractId/sign-and-activate',
          roles: LEGAL,
          resultingStates: ['ACTIVE'],
          errors: ['404 Contrato no encontrado', '409 El contrato no tiene versión contractual inicial'],
          events: ['merchant.mdr.updated'],
        },
        {
          code: 'crm.contract_list',
          name: 'Ver los contratos',
          description: 'Devuelve currentVersionId, que es el id que esperan las reglas de comisión.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/contracts',
          roles: ['COMMERCIAL_EXECUTIVE', 'COMMERCIAL_MANAGER', 'LEGAL', 'FINANCE', 'ADMIN'],
          repeatable: true,
        },
      ],
    },
    {
      code: 'crm_mdr_rules',
      name: 'Reglas de comisión por venta',
      description:
        '«Comisión por venta (MDR)» en CRM › Contratos: reglas por versión contractual, sucursal, categoría y segmento de riesgo. Bajo el mínimo piden motivo y aprobación.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/contratos',
      link: '{ERP}/operaciones/crm/contratos',
      roles: PRICING,
      steps: [
        {
          code: 'crm.mdr_list',
          name: 'Ver las reglas de comisión',
          description: 'Filtra por la versión contractual (no por el id del contrato).',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/contracts/mdr-rules',
          roles: PRICING,
        },
        {
          code: 'crm.mdr_create',
          name: 'Crear una regla de comisión',
          description: '404 si llega el id del contrato en vez del de la versión.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/contracts/mdr-rules',
          roles: PRICING,
          errors: ['404 Versión contractual no encontrada'],
          events: ['merchant.mdr.updated'],
        },
        {
          code: 'crm.mdr_update',
          name: 'Cambiar una regla de comisión',
          description: 'Mismo control de mínimo que al crearla.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/contracts/mdr-rules/:ruleId',
          roles: PRICING,
          optional: true,
          events: ['merchant.mdr.updated'],
        },
      ],
    },
    {
      code: 'crm_mdr_projection',
      name: 'Atlas recibe la comisión pactada',
      description:
        'El worker de outbox del ERP entrega merchant.mdr.updated firmado a AtlasBackend, que proyecta la regla general en partner_profiles.mdr_rate_percent: lo que ve el portal del comercio.',
      module: 'erp_integration',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'crm.erp_outbox_deliver',
          name: 'Entregar el evento a Atlas',
          kind: 'job',
          system: 'ERP_BACKEND',
          job: 'worker-outbox',
          description:
            'Worker de outbox del ERP (OUTBOX_DELIVERY_URL); publica sólo la regla general y sólo si la cuenta tiene partnerProfileId.',
          consumes: ['merchant.mdr.updated'],
        },
        {
          code: 'crm.core_erp_inbox',
          name: 'Recibir y proyectar la comisión',
          description: 'Receptor firmado; descarta avisos tardíos o repetidos por effectiveAt.',
          method: 'POST',
          path: '/internal/integration/erp/events',
          auth: false,
          consumes: ['merchant.mdr.updated'],
        },
      ],
    },
    {
      code: 'crm_legal_template',
      name: 'Atlas publica el contrato legal por defecto',
      description:
        'Ajustes › Contratos de comercio en el portal admin: cada publicación crea una versión y archiva la anterior; las archivadas no se ocultan porque prueban qué texto regía cada día.',
      module: 'partner_onboarding',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/settings/partner-contracts',
      optional: true,
      roles: TEMPLATE_ROLES,
      steps: [
        {
          code: 'crm.template_list',
          name: 'Ver las versiones del contrato',
          description: 'Vigentes y archivadas.',
          method: 'GET',
          path: '/operations/partner-contract-templates',
          roles: TEMPLATE_ROLES,
          optional: true,
        },
        {
          code: 'crm.template_publish',
          name: 'Publicar una versión nueva',
          description: 'El número de versión lo calcula el servidor.',
          method: 'POST',
          path: '/operations/partner-contract-templates',
          roles: TEMPLATE_ROLES,
          optional: true,
          successStatus: [201],
        },
        {
          code: 'crm.template_default',
          name: 'Marcar la versión predeterminada',
          description: 'Sólo una vigente; no revive un texto archivado.',
          method: 'PATCH',
          path: '/operations/partner-contract-templates/:templateId/default',
          roles: TEMPLATE_ROLES,
          optional: true,
          errors: ['404 PARTNER_CONTRACT_TEMPLATE_NOT_FOUND', '409 PARTNER_CONTRACT_TEMPLATE_ARCHIVED'],
        },
      ],
    },
    {
      code: 'crm_contract_to_onboarding',
      name: 'El contrato llega al alta del comercio',
      description:
        'En el caso de onboarding se enseña el texto legal por defecto de Atlas y se pacta la versión contractual vigente: sin ella la activación del comercio responde 409.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      terminal: true,
      roles: ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_MANAGER'],
      steps: [
        {
          code: 'crm.erp_legal_template',
          name: 'Leer el contrato legal por defecto',
          system: 'ERP_BACKEND',
          description: 'El ERP lo lee de Atlas en cada consulta.',
          method: 'GET',
          path: '/b2b/onboarding/legal-contract-template',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'],
        },
        {
          code: 'crm.core_default_template',
          name: 'Plantilla vigente de Atlas',
          description: 'template null si no hay ninguna publicada; el ERP entra con el permiso partner.kyb.request.',
          method: 'GET',
          path: '/operations/partner-contract-templates/default',
          roles: TEMPLATE_ROLES,
        },
        {
          code: 'crm.erp_case_contract',
          name: 'Pactar la versión contractual del alta',
          system: 'ERP_BACKEND',
          description: 'Versión del contrato de esta cuenta que rige el alta.',
          method: 'PATCH',
          path: '/b2b/onboarding/cases/:onboardingCaseId/contract',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_MANAGER'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'crm.entry',
      from: null,
      to: 'crm.account_create',
      condition: 'always',
      isDefault: true,
      description: 'Entrada: alta comercial.',
    },
    {
      code: 'crm.account_to_qualify',
      from: 'crm.account_create',
      to: 'crm.account_qualify',
      condition: 'on_success',
      isDefault: true,
      description: 'La cuenta se califica.',
    },
    {
      code: 'crm.qualify_to_proposal',
      from: 'crm.account_qualify',
      to: 'crm.proposal_create',
      condition: 'conditional',
      expression: { lifecycleStatus: 'QUALIFIED' },
      isDefault: true,
      description: 'Con fit, se arma la propuesta.',
    },
    {
      code: 'crm.qualify_exit',
      from: 'crm.account_qualify',
      to: null,
      condition: 'conditional',
      expression: { lifecycleStatus: 'DISQUALIFIED' },
      description: 'Sin fit, termina con motivo.',
    },
    {
      code: 'crm.proposal_needs_approval',
      from: 'crm.proposal_create',
      to: 'crm.approval_decide',
      condition: 'conditional',
      expression: { status: 'PENDING_APPROVAL' },
      description: 'Comisión bajo el mínimo: aprobación.',
    },
    {
      code: 'crm.approval_to_send',
      from: 'crm.approval_decide',
      to: 'crm.proposal_send',
      condition: 'conditional',
      expression: { decision: 'APPROVED' },
      description: 'Aprobada, vuelve a DRAFT y se envía.',
    },
    {
      code: 'crm.proposal_to_send',
      from: 'crm.proposal_create',
      to: 'crm.proposal_send',
      condition: 'on_success',
      isDefault: true,
      description: 'Sin excepción, se envía.',
    },
    {
      code: 'crm.send_to_accept',
      from: 'crm.proposal_send',
      to: 'crm.proposal_accept',
      condition: 'on_success',
      isDefault: true,
      description: 'El comercio acepta.',
    },
    {
      code: 'crm.send_to_reject',
      from: 'crm.proposal_send',
      to: 'crm.proposal_reject',
      condition: 'conditional',
      expression: { merchantAnswer: 'reject' },
      description: 'El comercio rechaza.',
    },
    {
      code: 'crm.accept_to_contract',
      from: 'crm.proposal_accept',
      to: 'crm.contract_from_proposal',
      condition: 'on_success',
      isDefault: true,
      description: 'Legal crea el contrato.',
    },
    {
      code: 'crm.contract_to_sign',
      from: 'crm.contract_from_proposal',
      to: 'crm.contract_sign',
      condition: 'on_success',
      isDefault: true,
      description: 'Se firma y activa.',
    },
    {
      code: 'crm.sign_to_mdr',
      from: 'crm.contract_sign',
      to: 'crm.mdr_create',
      condition: 'on_success',
      isDefault: true,
      description: 'Se pactan las reglas de comisión.',
    },
    {
      code: 'crm.mdr_to_projection',
      from: 'crm.mdr_create',
      to: 'crm.erp_outbox_deliver',
      condition: 'on_success',
      isDefault: true,
      description: 'La regla general viaja a Atlas.',
    },
    {
      code: 'crm.projection_to_inbox',
      from: 'crm.erp_outbox_deliver',
      to: 'crm.core_erp_inbox',
      condition: 'always',
      isDefault: true,
      description: 'Atlas la proyecta.',
    },
    {
      code: 'crm.inbox_to_onboarding',
      from: 'crm.core_erp_inbox',
      to: 'crm.erp_case_contract',
      condition: 'always',
      isDefault: true,
      description: 'El contrato se pacta en el alta.',
    },
    {
      code: 'crm.exit',
      from: 'crm.erp_case_contract',
      to: null,
      condition: 'on_success',
      isDefault: true,
      description: 'Salida: contrato vigente para activar al comercio.',
    },
  ],
  dependencies: [
    { step: 'crm.proposal_send', dependsOn: 'crm.approval_decide', type: 'soft', description: 'Con aprobación pendiente no se envía.' },
    {
      step: 'crm.contract_from_proposal',
      dependsOn: 'crm.proposal_accept',
      type: 'requires_completion',
      description: 'Sólo desde una propuesta aceptada.',
    },
    {
      step: 'crm.mdr_create',
      dependsOn: 'crm.contract_from_proposal',
      type: 'requires_data',
      description: 'La regla cuelga de la versión contractual.',
    },
    {
      step: 'crm.erp_case_contract',
      dependsOn: 'crm.contract_sign',
      type: 'requires_completion',
      description: 'La activación exige versión ACTIVE y vigente.',
    },
    {
      step: 'crm.core_erp_inbox',
      dependsOn: 'crm.erp_outbox_deliver',
      type: 'requires_completion',
      description: 'Atlas sólo proyecta lo que el ERP entrega.',
    },
  ],
};
