/**
 * @file Proceso declarado en código: Alta de comercio: ERP pide → Motor decide (KYB) → Portal concede → ERP acusa y opera.
 * @business Un comercio sólo puede vender a crédito con Atlas cuando está verificado, tiene personas con acceso y un contrato vigente; este proceso reparte ese trabajo entre cuatro sistemas sin que ninguno haga el del siguiente.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; rutas del ERP (`b2b/onboarding/*`, pasarela `partner-onboarding`), de AtlasBackend (`operations/partners`, `merchant/users`, `partner-onboarding`) y del Motor (`v1/decisions`, `v1/manual-reviews`), con el job `sync_partner_kyb_reviews`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** `@Roles` de `onboarding.controller.ts` del ERP para leer la cola. */
const ERP_CASE_READ = ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_EXECUTIVE'];
/** `@Roles` de la pasarela `partner-onboarding-gateway.controller.ts` del ERP. */
const ERP_MERCHANT = ['merchant', 'MERCHANT_ADMIN', 'MERCHANT_OPERATIONS', 'ADMIN'];
/** `@Roles` de `partner-onboarding.controller.ts` de AtlasBackend. */
const PARTNER_ROLES = ['merchant', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
/** `@Roles` de clase de `partner-operations.controller.ts`. */
const OPS_ROLES = ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
/** `@Roles` de clase de `partner-contract-templates.controller.ts`. */
const TEMPLATE_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'];
/** Roles internos que traen `merchant.users.manage` (conceder). */
const USERS_MANAGE = ['MERCHANT_OPERATIONS', 'SUPER_ADMIN'];
/** Roles internos que traen `merchant.users.read`. */
const USERS_READ = ['OPERATIONS_MANAGER', 'MERCHANT_OPERATIONS', 'AUDITOR_READONLY', 'SUPER_ADMIN'];
/** `@Roles` de `manual-review.controller.ts` del Motor. */
const MOTOR_REVIEW = ['OPERATIONS', 'RISK_ANALYST', 'FRAUD_ANALYST'];

export const MERCHANT_ONBOARDING_CHAIN: WorkflowDefinitionFixture = {
  processId: 'P-16',
  code: 'merchant_onboarding_chain',
  version: 'v1',
  name: 'Alta de comercio: ERP pide → Motor decide (KYB) → Portal concede → ERP acusa y opera',
  description:
    'La cadena completa del alta de un comercio: el ERP abre el caso y pide la verificación, AtlasBackend ejecuta PARTNER_KYB_REVIEW en el Motor, una persona del Motor resuelve lo dudoso, el portal admin concede las identidades que el ERP encoló, el ERP acusa las credenciales, pacta contrato y checklist, y activa el comercio.',
  processType: 'integration',
  ownerDomain: 'merchant_onboarding',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ERP_BACKEND', 'ATLAS_BACKEND', 'DECISION_ENGINE'],
  narrative: {
    whyExists:
      'Un comercio no puede vender a crédito con Atlas hasta estar verificado, tener personas con acceso y un contrato vigente. La cadena reparte ese trabajo con una regla fija: el ERP origina y pide, el Motor decide, el portal concede la identidad y el ERP recibe el acuse y opera; ningún tramo hace el trabajo del siguiente, así no existen dos orígenes de la misma decisión.',
    whoStartsAndCloses:
      'Lo inicia una persona de Operaciones del ERP al abrir el caso de onboarding de una cuenta B2B; el comercio completa su expediente desde «Mi empresa»; el Motor decide y, si hay señales, un analista del Motor resuelve en su cola; Operaciones de comercios (MERCHANT_OPERATIONS) concede los accesos en el portal admin; lo cierra Operaciones del ERP al activar el comercio.',
    startAndEnd:
      'Empieza con el caso en OPEN (POST /b2b/onboarding/cases) y avanza por EN_VERIFICACION, REVISION_MANUAL o RECHAZADO, VERIFICADO, ALTA_PENDIENTE y LISTO; termina en COMPLETED cuando la activación encuentra APROBADO del Motor, checklist completo y contrato vigente: la cuenta pasa a CUSTOMER y sus sucursales pendientes a ACTIVE con permiso de originar ventas a plazos.',
    whenItFails:
      'Con el Motor caído la verificación responde 503 DECISION_ENGINE_UNAVAILABLE y el caso vuelve a su estado anterior: nunca se aprueba solo. Sin expediente en Atlas la verificación responde 409 y el comercio debe abrirlo desde su portal. Sin APROBADO del Motor la activación responde 409 (compuerta dura). Un desenlace desconocido se trata como REVISION_MANUAL. La versión desplegada del artefacto (v470) no abre caso en su nodo REVISAR, así que REVISION_MANUAL llega sin caso que alguien mire.',
    healthIndicator:
      'El mini-tablero de la cola del ERP (GET /b2b/onboarding/cases/summary): abiertos, esperando Motor, revisión manual, esperando credenciales, listos para activar y activados, contados con la misma regla que la activación; y el tiempo entre OPEN y COMPLETED por caso. Un caso que se queda en REVISION_MANUAL sin código de caso del Motor es la señal de alarma.',
  },
  instanceEntity: {
    system: 'ERP_BACKEND',
    schema: 'atlas_sales',
    table: 'merchant_onboarding_cases',
    idColumn: 'id',
    statusColumn: 'status',
    openStatuses: [
      'OPEN',
      'IN_PROGRESS',
      'BLOCKED',
      'EN_VERIFICACION',
      'REVISION_MANUAL',
      'RECHAZADO',
      'VERIFICADO',
      'ALTA_PENDIENTE',
      'LISTO',
    ],
  },
  success:
    'Caso COMPLETED con decision_outcome APROBADO, credenciales concedidas y acusadas, contrato vigente pactado y la cuenta del comercio en CUSTOMER con sus sucursales activas.',
  failure:
    'El Motor rechaza o deja el expediente en revisión sin caso, el portal rechaza el acceso pedido, o la activación se bloquea por checklist pendiente o contrato no vigente.',
  sources: [
    'AtlasERPBackend/src/modules/b2b-sales-crm/domain/onboarding-lifecycle.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/services/b2b-onboarding.service.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/controllers/onboarding.controller.ts',
    'AtlasERPBackend/src/modules/partner-onboarding-gateway/partner-onboarding-gateway.controller.ts',
    'src/modules/partner-onboarding/partner-operations.controller.ts',
    'src/modules/partner-onboarding/partner-onboarding.controller.ts',
    'src/modules/partner-onboarding/application/partner-kyb-sync.service.ts',
    'src/modules/merchant-identity/merchant-users.controller.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts (sync_partner_kyb_reviews)',
    'AtlasDecisionEngineBackend/src/modules/runtime/runtime.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/manual-review/manual-review.controller.ts',
    'AtlasERPFrontend/app/operaciones/crm/onboarding/page.tsx',
    'AtlasAdminPortal/src/features/partner-decisions/partner-decisions-page.tsx',
    'AtlasAdminPortal/src/app/internal/merchant-users/page.tsx',
    'commit b4b979e (PARTNER_KYB_REVIEW portado como guion; v470 con REVISAR como RESULT)',
    'memoria atlas-onboarding-cadena-comercios',
    'memoria atlas-alta-comercio-por-cola',
    'memoria atlas-portal-motor-duplicacion-2',
    'memoria atlas-portal-comercio-cinco-entradas',
  ],
  metadata: {
    gaps: [
      'PARTNER_KYB_REVIEW v470 (desplegada) tiene REVISAR como nodo RESULT: REVISION_MANUAL no abre caso en el Motor y manualReviewCaseCode llega null. La v2 que lo corrige esperaba dos firmas humanas (QA_ANALYST y RISK_APPROVER); su estado tras b4b979e no está verificado aquí.',
      '/internal/operations/partners: el menú la ofrece a PARTNER_OPS pero la página usa RoleGate con INTERNAL_PORTAL_ROLE_LIST (más amplio).',
      'El ERP no tiene planificador: el acuse de credenciales y la sincronización del veredicto se lanzan desde la cola (POST /b2b/onboarding/cases/reconcile-pending), no solos.',
      'El inventario pedía estados de partner_profiles además de los del caso; aquí la instancia es el caso del ERP y el expediente (partner.partner_profiles.onboarding_status) se documenta por sus pasos.',
    ],
  },
  stages: [
    {
      code: 'onb_case_open',
      name: 'El ERP abre el caso de onboarding',
      description:
        'Operaciones del ERP abre el caso de una cuenta B2B con su checklist. Un caso COMPLETED no vuelve a la cola: la cola sólo muestra trabajo pendiente.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding/crear',
      link: '{ERP}/operaciones/crm/onboarding/crear',
      entry: true,
      roles: ['OPERATIONS', 'LEGAL', 'ADMIN'],
      resultingStates: ['OPEN'],
      steps: [
        {
          code: 'onb.erp_case_create',
          name: 'Abrir el caso de onboarding',
          description: 'Crea el caso en OPEN con su checklist. Responde 409 si la cuenta ya tiene un caso abierto.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/cases',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN'],
          resultingStates: ['OPEN'],
          errors: ['404 Cuenta B2B no encontrada', '409 La cuenta ya tiene un caso de onboarding abierto'],
          successStatus: [201],
        },
        {
          code: 'onb.erp_case_list',
          name: 'Ver la cola de casos',
          description: 'Lista por alcance (abiertos, historial, todos); abiertos es lo que queda por atender.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/onboarding/cases',
          roles: ERP_CASE_READ,
          repeatable: true,
        },
        {
          code: 'onb.erp_case_summary',
          name: 'Leer el mini-tablero de la cola',
          description: 'Cuenta con isReadyToActivate, la misma regla que aplica la activación.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/b2b/onboarding/cases/summary',
          roles: ERP_CASE_READ,
          repeatable: true,
        },
      ],
    },
    {
      code: 'onb_merchant_dossier',
      name: 'El comercio completa su expediente',
      description:
        'Desde «Mi empresa» del portal del comercio, el comercio abre su expediente en Atlas (vía la pasarela del ERP), carga representante, registro y ficha, y lo envía. Enviar dispara la misma verificación que pide el ERP.',
      module: 'partner_onboarding',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/expediente',
      link: '{ERP}/portal-comercio/expediente',
      roles: ERP_MERCHANT,
      steps: [
        {
          code: 'onb.gw_start',
          name: 'Abrir el expediente (pasarela del ERP)',
          description: 'El ERP reenvía a AtlasBackend con el token del comercio.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/partner-onboarding/start',
          roles: ERP_MERCHANT,
        },
        {
          code: 'onb.core_start',
          name: 'Crear el expediente del comercio',
          description: 'Nace partner_profiles (y su carpeta en Archivos). Es el único sitio donde nace un expediente de comercio.',
          method: 'POST',
          path: '/partner-onboarding/start',
          roles: PARTNER_ROLES,
          resultingStates: ['draft'],
        },
        {
          code: 'onb.gw_legal_representative',
          name: 'Declarar el representante legal',
          system: 'ERP_BACKEND',
          description: 'Se reenvía a AtlasBackend; el poder notarial va a la carpeta «documentos» del expediente.',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/legal-representative',
          roles: ERP_MERCHANT,
        },
        {
          code: 'onb.gw_commercial_registry',
          name: 'Registrar la matrícula de comercio',
          description: 'Datos del registro comercial del negocio, reenviados a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/commercial-registry',
          roles: ERP_MERCHANT,
        },
        {
          code: 'onb.gw_commercial_profile',
          name: 'Completar la ficha comercial',
          description: 'Rubro, nombre comercial y contacto del negocio.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/partner-onboarding/:partnerId/commercial-profile',
          roles: ERP_MERCHANT,
        },
        {
          code: 'onb.gw_status',
          name: 'Ver qué falta para enviar',
          description: 'Estado, requisitos pendientes, sucursales, QR y terminales del expediente.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/status',
          roles: ERP_MERCHANT,
          repeatable: true,
        },
        {
          code: 'onb.gw_submit',
          name: 'Enviar el expediente (pasarela del ERP)',
          description: 'Reenvío del envío a AtlasBackend.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/submit',
          roles: ERP_MERCHANT,
        },
        {
          code: 'onb.core_submit',
          name: 'Enviar el expediente a verificación',
          description:
            'Pasa el expediente a under_review y dispara la verificación KYB: la misma función que usa el ERP, para que no existan dos orígenes.',
          method: 'POST',
          path: '/partner-onboarding/:partnerId/submit',
          roles: PARTNER_ROLES,
          resultingStates: ['under_review'],
        },
      ],
    },
    {
      code: 'onb_erp_request_kyb',
      name: 'El ERP enlaza el expediente y pide la verificación',
      description:
        'El ERP busca el expediente del comercio por su cuenta o NIT, escribe el puente de una vía y pide la verificación. El caso queda EN_VERIFICACION mientras dura la llamada; si falla, vuelve a donde estaba.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER'],
      requiredStates: ['OPEN', 'IN_PROGRESS', 'BLOCKED', 'RECHAZADO', 'EN_VERIFICACION'],
      resultingStates: ['EN_VERIFICACION'],
      steps: [
        {
          code: 'onb.erp_partner_link',
          name: 'Enlazar el caso con el expediente de Atlas',
          description: 'Si no hay expediente responde linked:false con motivo SIN_EXPEDIENTE_EN_ATLAS (no es un error).',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/partner-link',
          roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER'],
        },
        {
          code: 'onb.core_find_partner',
          name: 'Buscar el expediente por cuenta del ERP o NIT',
          description: 'Sin coincidencias responde 200 con items vacío; 400 si no se manda ni erpAccountId ni taxId.',
          method: 'GET',
          path: '/operations/partners',
          roles: OPS_ROLES,
          errors: ['400 sin erpAccountId ni taxId'],
        },
        {
          code: 'onb.core_link_erp_account',
          name: 'Escribir el puente expediente → cuenta del ERP',
          description:
            'De una vía: si ya apunta a otra cuenta responde 409. Además del rol, exige el permiso interno partner.kyb.request (OPERATIONS_MANAGER), que es con el que entra el ERP.',
          method: 'PATCH',
          path: '/operations/partners/:partnerId/erp-account',
          roles: OPS_ROLES,
          errors: ['409 PARTNER_ERP_ACCOUNT_ALREADY_LINKED'],
        },
        {
          code: 'onb.erp_request_kyb',
          name: 'Pedir la verificación del comercio',
          description:
            'Sólo desde OPEN, IN_PROGRESS, BLOCKED, RECHAZADO o EN_VERIFICACION; si el caso no tiene expediente responde 409. El ERP nunca llama al Motor directo.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/kyb-review',
          roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER'],
          requiredStates: ['OPEN', 'IN_PROGRESS', 'BLOCKED', 'RECHAZADO', 'EN_VERIFICACION'],
          resultingStates: ['VERIFICADO', 'RECHAZADO', 'REVISION_MANUAL'],
          errors: ['409 caso en estado que no admite verificación', '409 comercio sin expediente en Atlas'],
        },
        {
          code: 'onb.core_kyb_review',
          name: 'Ejecutar la verificación KYB',
          description:
            'Ejecuta PARTNER_KYB_REVIEW y aplica su veredicto al expediente (decision_outcome, decision_execution_id, manual_review_case_code). Exige partner.kyb.request.',
          method: 'POST',
          path: '/operations/partners/:partnerId/kyb-review',
          roles: OPS_ROLES,
          idempotencyKey: true,
          output: { decision: '{ outcome, reason, executionId, artifactVersionId, manualReviewCaseCode, decidedAt }' },
          errors: ['409 PARTNER_NOT_UNDER_REVIEW', '503 DECISION_ENGINE_UNAVAILABLE'],
        },
      ],
    },
    {
      code: 'onb_motor_decision',
      name: 'El Motor decide',
      description:
        'AtlasBackend ejecuta el artefacto PARTNER_KYB_REVIEW contra el despliegue activo. Tres desenlaces: APROBADO, RECHAZADO o REVISION_MANUAL.',
      module: 'decision_engine',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'onb.motor_execute',
          name: 'Ejecutar PARTNER_KYB_REVIEW',
          description:
            'Ejecución idempotente por llave contra el despliegue activo; sin decision_runtime_binding responde ACTIVE_DEPLOYMENT_NOT_FOUND.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
          roles: ['DECISION_RUNTIME'],
          input: { artifactCode: 'PARTNER_KYB_REVIEW' },
          errors: ['ACTIVE_DEPLOYMENT_NOT_FOUND'],
        },
      ],
    },
    {
      code: 'onb_motor_manual_review',
      name: 'Un analista del Motor resuelve lo dudoso',
      description:
        'Cuando el Motor abre caso (cola MERCHANT_KYB), un analista lo toma y lo resuelve en el portal del Motor. El portal admin sólo enlaza: no decide.',
      module: 'decision_engine',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      link: '{MOTOR}/manual-reviews',
      optional: true,
      roles: MOTOR_REVIEW,
      requiredStates: ['REVISION_MANUAL'],
      steps: [
        {
          code: 'onb.motor_review_list',
          name: 'Ver la cola de revisión manual',
          system: 'DECISION_ENGINE',
          description: 'Casos abiertos del Motor, entre ellos los de verificación de comercios.',
          method: 'GET',
          path: '/v1/manual-reviews',
          roles: MOTOR_REVIEW,
          optional: true,
        },
        {
          code: 'onb.motor_review_assign',
          name: 'Tomar el caso',
          system: 'DECISION_ENGINE',
          description: 'El analista se asigna el caso antes de resolverlo.',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/assign',
          roles: MOTOR_REVIEW,
          optional: true,
        },
        {
          code: 'onb.motor_review_resolve',
          name: 'Resolver el caso',
          system: 'DECISION_ENGINE',
          description: 'Aprobar o declinar; CANCELLED no es un rechazo: devuelve el expediente a la decisión local.',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/resolve',
          roles: MOTOR_REVIEW,
          optional: true,
          resultingStates: ['RESOLVED_APPROVED', 'RESOLVED_DECLINED', 'CANCELLED'],
        },
      ],
    },
    {
      code: 'onb_verdict_sync',
      name: 'El veredicto vuelve al expediente y al caso',
      description:
        'Un job de AtlasBackend trae cada 5 minutos la resolución de los casos abiertos del Motor al expediente; el ERP la lee del estado del expediente al sincronizar.',
      module: 'partner_onboarding',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'onb.job_sync_kyb',
          name: 'Traer las resoluciones del Motor',
          kind: 'job',
          job: 'sync_partner_kyb_reviews',
          description: 'Consulta GET /v1/manual-reviews/:caseCode por cada expediente con caso abierto y aplica su veredicto.',
        },
        {
          code: 'onb.motor_review_read',
          name: 'Leer un caso del Motor',
          system: 'DECISION_ENGINE',
          description: 'Lo que consulta el job por cada expediente con caso abierto.',
          method: 'GET',
          path: '/v1/manual-reviews/:caseId',
          roles: MOTOR_REVIEW,
        },
        {
          code: 'onb.erp_kyb_sync',
          name: 'Sincronizar el veredicto en el caso del ERP',
          description: 'Aplica el desenlace vigente; un APROBADO tardío no retrocede un caso en ALTA_PENDIENTE o LISTO.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/kyb-review/sync',
          roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'],
          repeatable: true,
        },
        {
          code: 'onb.core_partner_status',
          name: 'Leer el estado del expediente',
          description: 'El bloque decision viaja dentro de profile.',
          method: 'GET',
          path: '/partner-onboarding/:partnerId/status',
        },
        {
          code: 'onb.erp_reconcile_pending',
          name: 'Acusar en lote los casos que esperan',
          description:
            'Recorre hasta 50 casos abiertos que esperan al Motor o al portal y acusa cada uno por separado. Lo lanza la cola: el ERP no tiene planificador.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/cases/reconcile-pending',
          roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'],
          repeatable: true,
        },
      ],
    },
    {
      code: 'onb_admin_observe',
      name: 'Operaciones de Atlas vigila la cola de expedientes',
      description:
        'La cola de expedientes en under_review, el más antiguo primero. Puede volver a pedir la verificación; decidir a mano es la degradación, sólo cuando el Motor no abrió caso.',
      module: 'partner_onboarding',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/partners',
      optional: true,
      roles: OPS_ROLES,
      steps: [
        {
          code: 'onb.core_queue',
          name: 'Ver la cola de expedientes en revisión',
          method: 'GET',
          path: '/operations/partners/queue',
          roles: OPS_ROLES,
          description: 'Expedientes en under_review, el más antiguo primero.',
        },
        {
          code: 'onb.core_decision_fallback',
          name: 'Decidir a mano (degradación)',
          description:
            'Sólo desde under_review y cuando el Motor no abrió caso; con caso abierto responde 409 PARTNER_DECISION_DELEGADA_AL_MOTOR. Rechazar exige motivo.',
          method: 'POST',
          path: '/operations/partners/:partnerId/decision',
          roles: OPS_ROLES,
          optional: true,
          errors: ['409 PARTNER_NOT_UNDER_REVIEW', '409 PARTNER_DECISION_DELEGADA_AL_MOTOR'],
        },
      ],
    },
    {
      code: 'onb_erp_request_access',
      name: 'El ERP pide el acceso de las personas del comercio',
      description:
        '«Dar acceso a una persona»: el ERP crea el usuario del comercio en INVITED y encola la petición en Atlas dentro de la misma transacción. Quien pide no concede.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      roles: ['OPERATIONS', 'ADMIN'],
      requiredStates: ['VERIFICADO'],
      resultingStates: ['ALTA_PENDIENTE'],
      steps: [
        {
          code: 'onb.erp_merchant_user',
          name: 'Dar acceso a una persona del comercio',
          description:
            'Nace INVITED en atlas_sales.merchant_users y el caso pasa a ALTA_PENDIENTE; 409 si el correo ya existe en la cuenta.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/merchant-users',
          roles: ['OPERATIONS', 'ADMIN'],
          resultingStates: ['ALTA_PENDIENTE'],
          errors: ['409 Ya existe un usuario comercio con ese email en la cuenta'],
        },
        {
          code: 'onb.core_enqueue_access',
          name: 'Encolar la petición de alta de identidad',
          description: 'Idempotente por externalReference: el reintento del ERP es el caso normal. Exige merchant.users.request.',
          method: 'POST',
          path: '/merchant/users/provisioning-requests',
          roles: ['OPERATIONS_MANAGER', 'SUPER_ADMIN'],
          resultingStates: ['pending'],
          errors: ['409 MERCHANT_PROVISIONING_REQUEST_PENDING_FOR_EMAIL'],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'onb_portal_grant',
      name: 'El portal admin concede el acceso',
      description:
        'Operaciones de comercios revisa la cola de peticiones y concede o rechaza. Conceder crea la identidad y manda la contraseña provisional una sola vez.',
      module: 'merchant_identity',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/merchant-users',
      roles: USERS_MANAGE,
      steps: [
        {
          code: 'onb.core_list_requests',
          name: 'Ver las peticiones de alta',
          description: 'Pendientes primero y, dentro, la más antigua arriba.',
          method: 'GET',
          path: '/merchant/users/provisioning-requests',
          roles: USERS_READ,
        },
        {
          code: 'onb.core_approve_request',
          name: 'Conceder el acceso',
          description:
            'Crea la identidad y cierra la petición como provisioned en una transacción con cerrojo. Exige merchant.users.manage.',
          method: 'POST',
          path: '/merchant/users/provisioning-requests/:requestId/approve',
          roles: USERS_MANAGE,
          resultingStates: ['provisioned'],
          errors: ['409 MERCHANT_PROVISIONING_REQUEST_ALREADY_DECIDED', '409 MERCHANT_USER_EMAIL_TAKEN'],
          successStatus: [201],
        },
        {
          code: 'onb.core_reject_request',
          name: 'Rechazar el acceso',
          description: 'El motivo es obligatorio: el ERP lo lee para corregir y volver a pedir.',
          method: 'POST',
          path: '/merchant/users/provisioning-requests/:requestId/reject',
          roles: USERS_MANAGE,
          optional: true,
          resultingStates: ['rejected'],
          errors: ['409 MERCHANT_PROVISIONING_REQUEST_ALREADY_DECIDED'],
        },
      ],
    },
    {
      code: 'onb_erp_acknowledge',
      name: 'El ERP acusa las credenciales',
      description:
        'AtlasBackend no llama de vuelta: el ERP pregunta en qué quedó cada petición y lo aplica. Con todas resueltas y al menos una concedida, el caso pasa a LISTO.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'],
      requiredStates: ['ALTA_PENDIENTE'],
      resultingStates: ['LISTO'],
      steps: [
        {
          code: 'onb.erp_identity_reconcile',
          name: 'Acusar las credenciales del caso',
          description: 'Idempotente; deja huella en business_action_logs sólo si algo cambió.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/identity/reconcile',
          roles: ['OPERATIONS', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'],
          resultingStates: ['LISTO'],
        },
        {
          code: 'onb.core_get_request',
          name: 'Consultar una petición de alta',
          description: 'Lo que el ERP lee por cada usuario pendiente: estado y merchantUserId con el que enlazar.',
          method: 'GET',
          path: '/merchant/users/provisioning-requests/:requestId',
          roles: USERS_READ,
          errors: ['404 MERCHANT_PROVISIONING_REQUEST_NOT_FOUND'],
        },
      ],
    },
    {
      code: 'onb_erp_contract_checklist',
      name: 'El ERP pacta contrato, comisión y checklist',
      description:
        'Operaciones y Legal eligen la versión contractual del comercio, pactan la comisión por venta y cierran el checklist con su evidencia. El texto legal por defecto lo publica Atlas.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      roles: ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_MANAGER'],
      steps: [
        {
          code: 'onb.erp_legal_template',
          name: 'Leer el contrato legal por defecto de Atlas',
          system: 'ERP_BACKEND',
          description: 'El ERP no guarda copia: lo lee de Atlas.',
          method: 'GET',
          path: '/b2b/onboarding/legal-contract-template',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'],
        },
        {
          code: 'onb.core_default_template',
          name: 'Plantilla legal vigente',
          description: 'Responde template null si el inquilino no publicó ninguna. El ERP entra con partner.kyb.request.',
          method: 'GET',
          path: '/operations/partner-contract-templates/default',
          roles: TEMPLATE_ROLES,
        },
        {
          code: 'onb.erp_contract_options',
          name: 'Ver las versiones de contrato del comercio',
          system: 'ERP_BACKEND',
          description: 'Versiones contractuales de la cuenta que se pueden pactar para este alta.',
          method: 'GET',
          path: '/b2b/onboarding/cases/:onboardingCaseId/contract-options',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_MANAGER', 'COMMERCIAL_EXECUTIVE'],
        },
        {
          code: 'onb.erp_assign_contract',
          name: 'Pactar la versión de contrato del alta',
          system: 'ERP_BACKEND',
          description: '404 si la versión no existe o no es de este comercio.',
          method: 'PATCH',
          path: '/b2b/onboarding/cases/:onboardingCaseId/contract',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN', 'COMMERCIAL_MANAGER'],
          errors: ['404 Esa versión de contrato no existe o no es de este comercio'],
        },
        {
          code: 'onb.erp_case_mdr',
          name: 'Pactar la comisión por venta del caso',
          system: 'ERP_BACKEND',
          description: 'Regla MDR colgada de la versión contractual pactada en el caso.',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/mdr-rules',
          roles: ['COMMERCIAL_MANAGER', 'FINANCE', 'ADMIN'],
          optional: true,
        },
        {
          code: 'onb.erp_evidence_upload_url',
          name: 'Pedir permiso para subir la evidencia',
          system: 'ERP_BACKEND',
          description: 'URL firmada al almacén a través de operations/erp-documents de Atlas.',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/checklist/:checklistItemId/evidence/upload-url',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN'],
          optional: true,
        },
        {
          code: 'onb.erp_evidence_attach',
          name: 'Adjuntar la evidencia del requisito',
          system: 'ERP_BACKEND',
          description: 'Lo legal y documental (LEGAL, NIT, MATRICULA, PODER, KYB, CONTRATO, FISCAL…) exige archivo para completarse.',
          method: 'POST',
          path: '/b2b/onboarding/cases/:onboardingCaseId/checklist/:checklistItemId/evidence',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN'],
          optional: true,
        },
        {
          code: 'onb.erp_checklist',
          name: 'Completar o dispensar un requisito',
          system: 'ERP_BACKEND',
          description: 'Cada ítem queda COMPLETED o WAIVED; sin eso no se activa.',
          method: 'PATCH',
          path: '/b2b/onboarding/cases/:onboardingCaseId/checklist',
          roles: ['OPERATIONS', 'LEGAL', 'ADMIN'],
          repeatable: true,
        },
      ],
    },
    {
      code: 'onb_erp_activate',
      name: 'El ERP activa el comercio',
      description:
        'La activación comprueba primero el APROBADO del Motor (compuerta dura), luego el checklist y el contrato vigente. Pasa la cuenta a CUSTOMER y las sucursales pendientes a ACTIVE.',
      module: 'b2b_sales_crm',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/onboarding',
      link: '{ERP}/operaciones/crm/onboarding',
      terminal: true,
      roles: ['OPERATIONS', 'ADMIN'],
      requiredStates: ['LISTO'],
      resultingStates: ['COMPLETED'],
      steps: [
        {
          code: 'onb.erp_activate',
          name: 'Activar el comercio',
          description: 'Transacción única: caso COMPLETED, cuenta CUSTOMER, sucursales ACTIVE con can_originate_bnpl.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/b2b/onboarding/cases/:onboardingCaseId/activate',
          roles: ['OPERATIONS', 'ADMIN'],
          resultingStates: ['COMPLETED'],
          errors: [
            '409 El comercio ya está activado',
            '409 Falta la verificación del Motor / el Motor no aprobó',
            '409 checklist pendiente o bloqueado',
            '409 sin contrato activo',
          ],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'onb.entry',
      from: null,
      to: 'onb.erp_case_create',
      condition: 'always',
      isDefault: true,
      description: 'Entrada: el ERP abre el caso.',
    },
    {
      code: 'onb.case_to_link',
      from: 'onb.erp_case_create',
      to: 'onb.erp_partner_link',
      condition: 'on_success',
      isDefault: true,
      description: 'Con el caso abierto, se busca el expediente del comercio.',
    },
    {
      code: 'onb.link_no_dossier',
      from: 'onb.erp_partner_link',
      to: 'onb.gw_start',
      condition: 'conditional',
      expression: { linked: false },
      description: 'Sin expediente en Atlas: el comercio lo abre desde su portal.',
    },
    {
      code: 'onb.submit_to_kyb',
      from: 'onb.core_submit',
      to: 'onb.motor_execute',
      condition: 'on_success',
      description: 'Enviar el expediente dispara la misma verificación.',
    },
    {
      code: 'onb.link_to_request',
      from: 'onb.erp_partner_link',
      to: 'onb.erp_request_kyb',
      condition: 'on_success',
      isDefault: true,
      description: 'Enlazado, el ERP pide la verificación.',
    },
    {
      code: 'onb.request_to_core',
      from: 'onb.erp_request_kyb',
      to: 'onb.core_kyb_review',
      condition: 'always',
      isDefault: true,
      description: 'El ERP reenvía a AtlasBackend.',
    },
    {
      code: 'onb.core_to_motor',
      from: 'onb.core_kyb_review',
      to: 'onb.motor_execute',
      condition: 'always',
      isDefault: true,
      description: 'AtlasBackend ejecuta el artefacto en el Motor.',
    },
    {
      code: 'onb.motor_manual',
      from: 'onb.motor_execute',
      to: 'onb.motor_review_assign',
      condition: 'conditional',
      expression: { outcome: 'REVISION_MANUAL' },
      description: 'El Motor abrió caso: lo resuelve un analista.',
    },
    {
      code: 'onb.motor_rejected',
      from: 'onb.motor_execute',
      to: 'onb.erp_request_kyb',
      condition: 'conditional',
      expression: { outcome: 'RECHAZADO' },
      description: 'Rechazado: se corrige el requisito y se vuelve a pedir.',
    },
    {
      code: 'onb.motor_approved',
      from: 'onb.motor_execute',
      to: 'onb.erp_merchant_user',
      condition: 'conditional',
      expression: { outcome: 'APROBADO' },
      isDefault: true,
      description: 'Verificado: el ERP pide los accesos.',
    },
    {
      code: 'onb.assign_to_resolve',
      from: 'onb.motor_review_assign',
      to: 'onb.motor_review_resolve',
      condition: 'on_success',
      description: 'El analista resuelve el caso que tomó.',
    },
    {
      code: 'onb.resolve_to_job',
      from: 'onb.motor_review_resolve',
      to: 'onb.job_sync_kyb',
      condition: 'always',
      description: 'El job trae la resolución al expediente.',
    },
    {
      code: 'onb.job_to_erp_sync',
      from: 'onb.job_sync_kyb',
      to: 'onb.erp_kyb_sync',
      condition: 'on_success',
      description: 'El ERP sincroniza el veredicto en su caso.',
    },
    {
      code: 'onb.sync_to_access',
      from: 'onb.erp_kyb_sync',
      to: 'onb.erp_merchant_user',
      condition: 'conditional',
      expression: { decisionOutcome: 'APROBADO' },
      description: 'Aprobado tras la revisión: se piden los accesos.',
    },
    {
      code: 'onb.access_to_enqueue',
      from: 'onb.erp_merchant_user',
      to: 'onb.core_enqueue_access',
      condition: 'always',
      isDefault: true,
      description: 'La petición se encola en Atlas en la misma transacción.',
    },
    {
      code: 'onb.enqueue_to_approve',
      from: 'onb.core_enqueue_access',
      to: 'onb.core_approve_request',
      condition: 'on_success',
      isDefault: true,
      description: 'El portal concede.',
    },
    {
      code: 'onb.enqueue_to_reject',
      from: 'onb.core_enqueue_access',
      to: 'onb.core_reject_request',
      condition: 'conditional',
      expression: { decision: 'reject' },
      description: 'El portal rechaza con motivo.',
    },
    {
      code: 'onb.approve_to_ack',
      from: 'onb.core_approve_request',
      to: 'onb.erp_identity_reconcile',
      condition: 'on_success',
      isDefault: true,
      description: 'El ERP acusa las credenciales.',
    },
    {
      code: 'onb.reject_to_ack',
      from: 'onb.core_reject_request',
      to: 'onb.erp_identity_reconcile',
      condition: 'on_success',
      description: 'El ERP lee el rechazo y su motivo.',
    },
    {
      code: 'onb.ack_to_contract',
      from: 'onb.erp_identity_reconcile',
      to: 'onb.erp_assign_contract',
      condition: 'on_success',
      isDefault: true,
      description: 'Con credenciales acusadas, se pacta el contrato.',
    },
    {
      code: 'onb.contract_to_checklist',
      from: 'onb.erp_assign_contract',
      to: 'onb.erp_checklist',
      condition: 'on_success',
      isDefault: true,
      description: 'Se cierra el checklist.',
    },
    {
      code: 'onb.checklist_to_activate',
      from: 'onb.erp_checklist',
      to: 'onb.erp_activate',
      condition: 'on_success',
      isDefault: true,
      description: 'Todo listo: se activa.',
    },
    {
      code: 'onb.exit',
      from: 'onb.erp_activate',
      to: null,
      condition: 'on_success',
      isDefault: true,
      description: 'Salida: comercio activo.',
    },
  ],
  dependencies: [
    {
      step: 'onb.erp_request_kyb',
      dependsOn: 'onb.core_start',
      type: 'requires_data',
      description: 'Sin expediente en Atlas no hay nada que verificar (409).',
    },
    {
      step: 'onb.core_kyb_review',
      dependsOn: 'onb.core_link_erp_account',
      type: 'soft',
      description: 'El puente permite al ERP encontrar el expediente la próxima vez.',
    },
    {
      step: 'onb.erp_kyb_sync',
      dependsOn: 'onb.job_sync_kyb',
      type: 'soft',
      description: 'Sin el job, un APROBADO del analista no llega al expediente.',
    },
    {
      step: 'onb.erp_identity_reconcile',
      dependsOn: 'onb.core_enqueue_access',
      type: 'requires_data',
      description: 'Se acusa lo que se encoló.',
    },
    {
      step: 'onb.erp_activate',
      dependsOn: 'onb.erp_request_kyb',
      type: 'requires_completion',
      description: 'Compuerta dura: sin APROBADO del Motor no se activa.',
    },
    {
      step: 'onb.erp_activate',
      dependsOn: 'onb.erp_assign_contract',
      type: 'requires_completion',
      description: 'Sin contrato vigente no se activa.',
    },
    {
      step: 'onb.erp_activate',
      dependsOn: 'onb.erp_checklist',
      type: 'requires_completion',
      description: 'Sin checklist completo no se activa.',
    },
  ],
};
