/**
 * @file Proceso declarado en código: Workers del Motor (identidad, extracto bancario, análisis semántico, PDF y audio).
 * @business Leer una cédula, convertir un extracto, clasificar un gasto, imprimir un PDF o sintetizar un audio son trabajos lentos y con evidencia: se encolan, se procesan fuera de la petición y, cuando dudan, esperan a una persona.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; todo vive en AtlasDecisionEngineBackend (`src/modules/workers/`, ADR-0026) salvo el render de PDF, que corre en el contenedor aparte `pdf-worker` compartido con el ERP.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const MOTOR_WORKERS: WorkflowDefinitionFixture = {
  processId: 'P-29',
  code: 'motor_workers',
  version: 'v1',
  name: 'Workers del Motor: identidad, extracto, semántico, PDF y audio',
  description:
    'Ciclo de vida común de una corrida de worker en el Motor: se encola (QUEUED) por petición o desde el grafo, un trabajador de fondo la reclama y la procesa (RUNNING), termina en SUCCEEDED, SUCCEEDED_WITH_WARNINGS, FAILED, CANCELLED o un rechazo terminal, o queda esperando a una persona (PENDING_REVIEW → IN_REVIEW) en la cola de revisión de identidad o de extractos. Cada original se guarda en el almacén con su huella SHA-256.',
  processType: 'system_job',
  ownerDomain: 'decisioning',
  ownerRole: 'MOTOR:PLATFORM_ADMIN',
  priority: 'P1',
  systems: ['DECISION_ENGINE'],
  narrative: {
    whyExists:
      'Verificar una identidad con documento y selfie, convertir un extracto bancario, clasificar un gasto, imprimir un PDF o sintetizar un audio son tareas lentas que no caben en una petición y que dejan evidencia: el Motor las encola, las procesa en segundo plano y guarda cada original con su huella para poder demostrar después qué se vio.',
    whoStartsAndCloses:
      'Las inician AtlasBackend como sistema (extractos, audio de bienvenida, referencias del expediente), el ERP (PDF) o un analista desde el portal del Motor; las procesan los trabajadores de fondo del Motor. Cuando el resultado es dudoso, la cierra un analista del Motor (RISK_ANALYST, FRAUD_ANALYST u OPERATIONS) que la reclama y la resuelve en la cola de revisión.',
    startAndEnd:
      'Empieza con la corrida en QUEUED (POST /v1/workers/<worker>/runs) y termina en un estado terminal: SUCCEEDED, SUCCEEDED_WITH_WARNINGS, FAILED, CANCELLED, PDF_INVALID o DOCUMENT_REJECTED; o pasa por PENDING_REVIEW e IN_REVIEW hasta que una persona la resuelve. Un veredicto de identidad REVIEW_REQUIRED va a la cola, no a un estado terminal.',
    whenItFails:
      'Sin almacén configurado el Motor no arranca (IDENTITY_IMAGE_RETENTION_REQUIRED) y una subida real se rechaza con 503 antes de crear la fila (IDENTITY_IMAGE_STORAGE_NOT_CONFIGURED, STATEMENT_FILE_STORAGE_NOT_CONFIGURED). Un documento que no es del tipo esperado termina en PDF_INVALID o DOCUMENT_REJECTED y nunca entra a la cola. Sin el contenedor pdf-worker generar un PDF da 502.',
    healthIndicator:
      'Métricas por worker (GET /v1/workers/:code/metrics): corridas FAILED y tiempo en QUEUED, casos PENDING_REVIEW sin reclamar en las colas de identidad y extractos, clasificaciones semánticas sin resolver (GET /v1/workers/semantic-analysis/unresolved/count) y originales con su huella SHA-256 guardada.',
  },
  instanceEntity: {
    system: 'DECISION_ENGINE',
    schema: 'public',
    table: 'decision_identity_verification_run',
    idColumn: 'id',
    statusColumn: 'status',
    labelColumn: 'request_id',
    openStatuses: ['QUEUED', 'RUNNING', 'PENDING_REVIEW', 'IN_REVIEW'],
  },
  success: 'La corrida termina con resultado y su evidencia en el almacén, o la persona que la revisó deja su resolución registrada.',
  failure: 'La corrida termina FAILED, se cancela, o queda en revisión sin que nadie la reclame.',
  sources: [
    'AtlasDecisionEngineBackend/src/modules/workers/workers.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/identity-verification/identity-verification.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/identity-verification/review/identity-review.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/bank-statement/bank-statement.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/bank-statement/review/statement-review.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/semantic-analysis/semantic-analysis.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/semantic-analysis/unresolved-classification.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/audio-tts/audio-tts.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/storage-references.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/workers/worker-service-invoker.service.ts',
    'AtlasDecisionEngineBackend/src/common/jobs/job-names.ts',
    'AtlasDecisionEngineBackend/prisma/schema.prisma (WorkerRunStatus)',
    'src/modules/decision-engine/bank-statement-engine.client.ts',
    'src/modules/mobile-welcome-audio/engine-audio.client.ts',
    'src/modules/expedientes/application/object-ref-counter.service.ts',
    'AtlasERPBackend/src/modules/documents/documents.service.ts',
    'memoria atlas-motor-evidencia-obligatoria',
    'memoria atlas-identidad-cola-humana',
    'memoria atlas-semantico-transformer-arm',
    'memoria atlas-pdf-worker-compartido',
  ],
  metadata: {
    runTables: [
      'decision_identity_verification_run',
      'decision_bank_statement_run',
      'decision_semantic_analysis_run',
      'decision_audio_tts_run',
    ],
    jobs: ['identity-verification', 'bank-statement', 'semantic-analysis', 'semantic-retention', 'audio-tts'],
    gaps: [
      'El inventario da seis estados; WorkerRunStatus tiene además PENDING_REVIEW, IN_REVIEW, PDF_INVALID y DOCUMENT_REJECTED.',
      'No se encontró llamador en AtlasBackend de POST /v1/workers/identity-verification/runs ni de /v1/workers/semantic-analysis/runs: las corridas por HTTP las lanza el portal del Motor; desde el grafo, el nodo WORKER invoca el núcleo sin pasar por la cola.',
      'El worker semántico va apagado por omisión (sin SEMANTIC_ANALYSIS_PROVIDER ni siquiera se registra) y su codificador no tiene imagen arm64.',
      'El PDF lo renderiza el contenedor pdf-worker, compartido con el ERP; en dev no está desplegado (memoria). La ruta /pdf/generate del Motor sin Chromium responde 502.',
      '66 rutas de workers, 29 sin llamador según el artefacto (varias son de máquina); aquí sólo se declara el ciclo de vida.',
    ],
  },
  stages: [
    {
      code: 'workers_catalog',
      name: 'Catálogo y salud de los workers',
      description: 'Qué workers están disponibles en esta instalación y sus métricas: corridas por estado y tiempos.',
      module: 'workers',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/workers',
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
      steps: [
        {
          code: 'workers.list',
          name: 'Listar workers',
          description: 'Workers registrados; uno sin proveedor configurado se declara no disponible.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
        },
        {
          code: 'workers.metrics',
          name: 'Métricas de un worker',
          description: 'Corridas por estado y latencia del worker.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/:code/metrics',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
        },
      ],
    },
    {
      code: 'workers_identity_run',
      name: 'Verificar una identidad',
      description:
        'Documento (anverso y reverso) y selfie: el worker compara, decide el estado por el veredicto y guarda cada original en el almacén con su huella. REVIEW_REQUIRED pasa a PENDING_REVIEW con motivo y prioridad; NOT_VERIFIED e INCONCLUSIVE son terminales.',
      module: 'workers.identity-verification',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/workers/identity-verification',
      entry: true,
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
      resultingStates: ['QUEUED'],
      steps: [
        {
          code: 'workers.identity_run_create',
          name: 'Encolar la verificación',
          description:
            'Una subida real sin almacén se rechaza antes de crear la fila; los escenarios de prueba (fixtureCode) generan sus imágenes.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/identity-verification/runs',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          resultingStates: ['QUEUED'],
          errors: ['503 IDENTITY_IMAGE_STORAGE_NOT_CONFIGURED'],
        },
        {
          code: 'workers.identity_job',
          name: 'Procesar la verificación',
          description: 'Documento, selfie y decisión; termina en estado terminal o en PENDING_REVIEW.',
          kind: 'job',
          system: 'DECISION_ENGINE',
          job: 'identity-verification',
          resultingStates: ['RUNNING', 'SUCCEEDED', 'SUCCEEDED_WITH_WARNINGS', 'FAILED', 'DOCUMENT_REJECTED', 'PENDING_REVIEW'],
        },
        {
          code: 'workers.identity_run_get',
          name: 'Leer la corrida',
          description: 'Estado, veredicto y parecido.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/identity-verification/runs/:requestId',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
        },
        {
          code: 'workers.identity_run_image',
          name: 'Ver una imagen original',
          description: 'Documento, reverso o selfie, servidos desde el almacén; nunca con URL pública.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/identity-verification/runs/:requestId/images/:kind',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
          optional: true,
        },
        {
          code: 'workers.identity_run_cancel',
          name: 'Cancelar la corrida',
          description: 'Sólo mientras no haya terminado.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/identity-verification/runs/:requestId/cancel',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
          resultingStates: ['CANCELLED'],
        },
      ],
    },
    {
      code: 'workers_identity_review',
      name: 'Revisar una identidad dudosa',
      description:
        'El analista reclama el caso (IN_REVIEW) para que nadie más lo trabaje y lo resuelve. Un caso de la puerta de documentos se resuelve con CONFIRM_DOCUMENT/REJECT_DOCUMENT; uno del veredicto con CONFIRM_IDENTITY/DENY_IDENTITY (409 si se cruzan). La decisión humana se guarda aparte, sin pisar la del worker.',
      module: 'workers.identity-verification',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/workers/identity-verification',
      optional: true,
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
      requiredStates: ['PENDING_REVIEW'],
      resultingStates: ['IN_REVIEW'],
      steps: [
        {
          code: 'workers.identity_reviews_list',
          name: 'Cola de revisión de identidad',
          description: 'Casos PENDING_REVIEW e IN_REVIEW por prioridad y motivo.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/identity-verification/reviews',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
          optional: true,
        },
        {
          code: 'workers.identity_review_claim',
          name: 'Reclamar el caso',
          description: 'Pasa a IN_REVIEW con el analista como responsable.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/identity-verification/reviews/:requestId/claim',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
          resultingStates: ['IN_REVIEW'],
        },
        {
          code: 'workers.identity_review_resolve',
          name: 'Resolver el caso',
          description: 'Registra human_decision; con similarity_score forma una fila del corpus.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/identity-verification/reviews/:requestId/resolve',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
          input: {
            action: 'CONFIRM_DOCUMENT | REJECT_DOCUMENT | CONFIRM_IDENTITY | DENY_IDENTITY',
            documentType: 'BOLIVIA_CI | PASSPORT | DRIVER_LICENSE ?',
          },
          errors: ['409 resolución de la otra familia'],
        },
      ],
    },
    {
      code: 'workers_statement_run',
      name: 'Convertir un extracto bancario',
      description:
        'AtlasBackend sube el extracto del cliente y consulta el resultado; el worker lo convierte en movimientos. Si duda (tiempo agotado, formato raro) queda PENDING_REVIEW con su motivo; si no es un extracto, PDF_INVALID.',
      module: 'workers.bank-statement',
      actor: 'system',
      client: 'BLOCK',
      resultingStates: ['QUEUED'],
      steps: [
        {
          code: 'workers.statement_run_create',
          name: 'Encolar el extracto',
          description: 'Sin almacén configurado se rechaza antes de crear la fila.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/runs',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          resultingStates: ['QUEUED'],
          errors: ['503 STATEMENT_FILE_STORAGE_NOT_CONFIGURED'],
        },
        {
          code: 'workers.statement_job',
          name: 'Procesar el extracto',
          description: 'Reclama la corrida y la convierte; el mismo núcleo lo usa el nodo WORKER del grafo en línea.',
          kind: 'job',
          system: 'DECISION_ENGINE',
          job: 'bank-statement',
          resultingStates: ['RUNNING', 'SUCCEEDED', 'SUCCEEDED_WITH_WARNINGS', 'FAILED', 'PDF_INVALID', 'PENDING_REVIEW'],
        },
        {
          code: 'workers.statement_run_get',
          name: 'Leer el resultado',
          description: 'AtlasBackend consulta la corrida por su requestId.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/bank-statement/runs/:requestId',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
        },
        {
          code: 'workers.statement_run_download',
          name: 'Descargar la conversión',
          description: 'Movimientos convertidos en el formato pedido.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/bank-statement/runs/:requestId/download',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
          optional: true,
        },
      ],
    },
    {
      code: 'workers_statement_review',
      name: 'Revisar un extracto dudoso',
      description: 'El analista reclama el extracto, lo resuelve con las categorías de revisión o pide reprocesarlo.',
      module: 'workers.bank-statement',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/workers/bank-statement',
      optional: true,
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
      requiredStates: ['PENDING_REVIEW'],
      steps: [
        {
          code: 'workers.statement_reviews_list',
          name: 'Cola de revisión de extractos',
          description: 'Extractos que esperan a una persona, con su motivo.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/bank-statement/reviews',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
          optional: true,
        },
        {
          code: 'workers.statement_review_claim',
          name: 'Reclamar el extracto',
          description: 'Pasa a IN_REVIEW para que dos analistas no trabajen el mismo.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/reviews/:requestId/claim',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
          resultingStates: ['IN_REVIEW'],
        },
        {
          code: 'workers.statement_review_resolve',
          name: 'Resolver el extracto',
          description: 'Cierra la revisión con su resolución.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/reviews/:requestId/resolve',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
        },
        {
          code: 'workers.statement_review_reprocess',
          name: 'Reprocesar',
          description: 'Vuelve a encolar el extracto.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/bank-statement/reviews/:requestId/reprocess',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
          resultingStates: ['QUEUED'],
        },
      ],
    },
    {
      code: 'workers_semantic',
      name: 'Clasificar textos (análisis semántico)',
      description:
        'Clasifica glosas y gastos por reglas o por el codificador; lo que no alcanza el suelo de similitud queda sin resolver para una persona. Un trabajo aparte minimiza y purga el texto vencido. Apagado por omisión.',
      module: 'workers.semantic-analysis',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/workers/semantic-analysis',
      optional: true,
      roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
      steps: [
        {
          code: 'workers.semantic_run_create',
          name: 'Encolar un texto',
          description: 'Una corrida por texto; también en lote (POST /v1/workers/semantic-analysis/runs/batch).',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/semantic-analysis/runs',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
          resultingStates: ['QUEUED'],
        },
        {
          code: 'workers.semantic_job',
          name: 'Clasificar',
          description: 'Reclama y clasifica los textos encolados.',
          kind: 'job',
          system: 'DECISION_ENGINE',
          job: 'semantic-analysis',
          optional: true,
        },
        {
          code: 'workers.semantic_unresolved',
          name: 'Clasificaciones sin resolver',
          description: 'Lo que el modelo no pudo decidir.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/semantic-analysis/unresolved',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'OPERATIONS'],
          optional: true,
        },
        {
          code: 'workers.semantic_unresolved_resolve',
          name: 'Resolver una clasificación',
          description: 'La persona elige la categoría.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/semantic-analysis/unresolved/:id/resolve',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST'],
          optional: true,
        },
        {
          code: 'workers.semantic_retention_job',
          name: 'Purgar el texto vencido',
          description: 'Minimiza y purga el texto analizado una vez vencido su plazo.',
          kind: 'job',
          system: 'DECISION_ENGINE',
          job: 'semantic-retention',
          optional: true,
        },
      ],
    },
    {
      code: 'workers_audio',
      name: 'Sintetizar audio',
      description: 'AtlasBackend pide el audio de bienvenida de la app; el worker lo sintetiza a partir de una plantilla y lo sirve.',
      module: 'workers.audio-tts',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      steps: [
        {
          code: 'workers.audio_run_create',
          name: 'Encolar el audio',
          description: 'Texto o plantilla a sintetizar.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/workers/audio-tts/runs',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'OPERATIONS'],
          optional: true,
          resultingStates: ['QUEUED'],
        },
        {
          code: 'workers.audio_job',
          name: 'Sintetizar',
          description: 'Reclama y sintetiza los textos encolados.',
          kind: 'job',
          system: 'DECISION_ENGINE',
          job: 'audio-tts',
          optional: true,
        },
        {
          code: 'workers.audio_get',
          name: 'Descargar el audio',
          description: 'El archivo de audio de la corrida terminada.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/audio-tts/runs/:requestId/audio',
          roles: ['RISK_ANALYST', 'FRAUD_ANALYST', 'QA_ANALYST', 'OPERATIONS', 'COMPLIANCE', 'AUDITOR'],
          optional: true,
        },
      ],
    },
    {
      code: 'workers_pdf',
      name: 'Imprimir un PDF',
      description:
        'El Motor y las dos caras del ERP imprimen con la plantilla generic-result-report en el contenedor pdf-worker (Chromium sólo vive ahí). La cabecera es x-pdf-service-key, no la llave del Motor.',
      module: 'pdf',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      steps: [
        {
          code: 'workers.pdf_generate',
          name: 'Generar el PDF',
          description: 'El ERP (documents.service.ts) llama a /pdf/generate del worker; la API del Motor sin Chromium responde 502.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/pdf/generate',
          optional: true,
          errors: ['502 el navegador no está disponible'],
        },
      ],
    },
    {
      code: 'workers_evidence_references',
      name: 'Referencias al almacén',
      description:
        'AtlasBackend pregunta qué originales del almacén siguen referenciados antes de tocar el expediente de un cliente; la evidencia no se borra mientras algo la use.',
      module: 'workers.storage',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      terminal: true,
      steps: [
        {
          code: 'workers.storage_references',
          name: 'Contar referencias',
          description: 'Llave de ejecución (DECISION_RUNTIME), no de persona.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/workers/storage/references',
          roles: ['DECISION_RUNTIME'],
          optional: true,
        },
      ],
    },
  ],
};
