/**
 * @file Proceso declarado en código: Notificaciones transaccionales y campañas masivas.
 * @business Este proceso hace que el cliente se entere a tiempo de lo que pasa con su crédito (verificación de la cuenta, pago confirmado o rechazado) y que operaciones pueda enviar campañas a un segmento, sabiendo por canal y proveedor qué llegó y qué no.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; sale de `src/modules/notifications/` (reglas, orquestador, callbacks y `campaigns/`), del job `run_notification_campaigns` y de la pasarela `admin/notification-campaigns` del ERP.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const CUSTOMER_ROLES = ['customer', 'internal_operator', 'admin', 'platform_admin', 'system'];
const OPS_READ_ROLES = [
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'fraud_analyst',
  'readonly_auditor',
  'admin',
  'platform_admin',
  'system',
];
const POLICY_READ_ROLES = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'readonly_auditor', 'admin', 'platform_admin'];
const POLICY_WRITE_ROLES = ['admin', 'platform_admin'];
const OPS_ACT_ROLES = ['admin', 'platform_admin', 'system', 'internal_operator'];
const CAMPAIGN_READ_ROLES = ['internal_operator', 'admin', 'platform_admin', 'system'];
const CAMPAIGN_WRITE_ROLES = ['admin', 'platform_admin'];
const ERP_READ_ROLES = ['ADMIN', 'OPERATIONS', 'COMMERCIAL_MANAGER', 'AUDITOR'];
const ERP_WRITE_ROLES = ['ADMIN'];
const INTERNAL_SELF_SERVICE_ROLES = [
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'fraud_analyst',
  'qa_engineer',
  'readonly_auditor',
  'admin',
  'platform_admin',
  'system',
];

export const NOTIFICATIONS_AND_CAMPAIGNS: WorkflowDefinitionFixture = {
  processId: 'P-13',
  code: 'notifications_and_campaigns',
  version: 'v1',
  name: 'Notificaciones transaccionales y campañas masivas',
  description:
    'Del hecho de negocio (cuenta verificada, pago confirmado) o de la campaña programada en el ERP hasta la entrega por canal (in-app, push, correo, SMS, WhatsApp) y el estado que devuelve cada proveedor.',
  processType: 'back_office',
  ownerDomain: 'notifications',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P1',
  systems: ['ATLAS_BACKEND', 'ERP_BACKEND'],
  narrative: {
    whyExists:
      'El cliente tiene que enterarse de lo que pasa con su crédito sin abrir la app a buscarlo: cuenta verificada, identidad aprobada o rechazada, pago reportado, confirmado o rechazado. Hoy NO se avisa de la mora ni de los vencimientos (nadie publica esos eventos: es una decisión de producto y regulatoria sin tomar). Y operaciones necesita avisar a un segmento de clientes (como una campaña de anuncios: fecha, duración y audiencia) sabiendo cuántos lo recibieron y por qué canal.',
    whoStartsAndCloses:
      'Los avisos transaccionales los inicia el sistema al ocurrir un hecho de negocio y los cierra el proveedor (Twilio, SendGrid, Brevo, Firebase) al confirmar la entrega. Las campañas las crea y programa un administrador del ERP desde Control › Notificaciones masivas y las cierra el planificador al agotar la audiencia o la ventana.',
    startAndEnd:
      'Empieza con un evento de dominio que tiene canales en las reglas de avisos, o con una campaña que pasa de borrador a programada. Termina cuando cada entrega llega a un estado final por proveedor (entregado, rebotado, fallido, leído) y la campaña queda completada, cancelada o fallida.',
    whenItFails:
      'Un envío que el proveedor rechaza queda fallido con su código, y operaciones lo reintenta o cancela desde Notificaciones del portal; los atascados los reintenta un job. Ojo: Brevo acepta un SMS sin crédito con 201 y lo descarta sin avisar, por eso se consulta el saldo antes y sin saldo se responde BREVO_SMS_NO_CREDITS. Una campaña que revienta queda «failed» con su último error.',
    healthIndicator:
      'Proporción de entregas en estado final entregado frente a fallido por canal y proveedor (notification_deliveries), cantidad de mensajes atascados que recoge el reintento, y campañas completadas frente a fallidas con su conteo de destinatarios alcanzados frente a creados.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'messaging',
    table: 'notification_campaigns',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'name',
    openStatuses: ['draft', 'scheduled', 'running', 'paused'],
  },
  success:
    'El aviso llegó al cliente por el canal permitido por sus preferencias y el proveedor confirmó la entrega; la campaña terminó completada.',
  failure: 'La entrega quedó fallida o atascada, el proveedor la descartó sin avisar, o la campaña terminó cancelada o fallida.',
  sources: [
    'src/modules/notifications/notification-rules.service.ts',
    'src/modules/notifications/notification-provider-callbacks.controller.ts',
    'src/modules/notifications/notifications.controller.ts',
    'src/modules/notifications/customer-notifications.controller.ts',
    'src/modules/notifications/notification-broadcast.controller.ts',
    'src/modules/notifications/notification-templates.controller.ts',
    'src/modules/notifications/notification-policies-operations.controller.ts',
    'src/modules/notifications/campaigns/notification-campaigns.controller.ts',
    'src/modules/notifications/campaigns/notification-campaigns.schemas.ts',
    'src/modules/notifications/campaigns/notification-campaign-runner.service.ts',
    'src/modules/notifications/campaigns/notification-audience-segments.controller.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts',
    'AtlasERPBackend/src/modules/notification-campaigns-gateway/notification-campaigns-gateway.controller.ts',
    'AtlasERPFrontend/app/operaciones/admin/notificaciones/page.tsx',
    'AtlasAdminPortal/src/features/notifications/services.ts',
    'memoria atlas-campanas-notificacion',
    'memoria atlas-twilio-sendgrid-envio-y-callbacks',
    'memoria atlas-brevo-sms-whatsapp',
    'memoria atlas-brevo-sms-sin-credito',
  ],
  metadata: {
    gaps: [
      'El portal admin observa y pausa/reanuda/cancela campañas (/internal/notifications/campaigns), pero crearlas y programarlas sólo se hace desde el ERP.',
      'La pantalla del ERP /operaciones/admin/notificaciones está oculta del menú desde el 2026-09-26 (NOTIFICACIONES_MASIVAS_VISIBLE = false, memoria atlas-campanas-notificacion).',
      'Los eventos notification.* están en event-registry.ts pero ningún código los emite.',
      'No se avisa al deudor de la mora ni de los vencimientos: los eventos installment.* y otros 15 de las reglas antiguas no los publica nadie (LoanDelinquencyService.sweep no emite nada) y sus reglas se retiraron el 2026-09-29. Qué avisar y cuándo es una decisión de producto y regulatoria sin tomar; la pantalla de avisos del cliente ya no ofrece cuota_por_vencer ni cuota_vencida.',
      'WhatsApp por Brevo no tiene webhook de estado: se queda en «sent».',
      'deliver_pending_notifications sólo existe con NOTIFICATIONS_DELIVERY_MODE=deferred (optional-jobs.catalog.ts); por defecto la entrega es en línea.',
    ],
  },
  stages: [
    {
      code: 'notif_domain_trigger',
      name: 'Hecho de negocio que genera el aviso',
      description:
        'El consumidor de eventos aplica las reglas (notification-rules.service.ts): cada evento con canales (payment.confirmed, kyc.approved, support.sla.warning…) crea el mensaje para el cliente o para operaciones. Sólo tienen regla los eventos que alguien publica; un guardián de pruebas lo comprueba.',
      module: 'notifications',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      steps: [
        {
          code: 'notif.process_events',
          name: 'Convertir eventos de dominio en mensajes',
          description:
            'El job consume el outbox de eventos; los que tienen canales en las reglas se convierten en mensajes con sus canales. De soporte sólo generan mensaje los avisos de plazo (support.sla.warning y support.sla.breached, bandeja interna de operaciones); el resto de eventos de soporte no tienen canales.',
          kind: 'job',
          job: 'process_events',
        },
      ],
    },
    {
      code: 'notif_delivery',
      name: 'Entrega por canal y proveedor',
      description:
        'El orquestador elige el adaptador del canal (push FCM/APNs, correo SendGrid, SMS Twilio o Brevo, WhatsApp Brevo) y registra la entrega; los atascados los recoge un job.',
      module: 'notifications',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'notif.provider_send',
          name: 'Enviar al proveedor del canal',
          description:
            'Llamada saliente al proveedor. Con Brevo se consulta antes el saldo de SMS: sin crédito responde BREVO_SMS_NO_CREDITS en vez de fiarse del 201.',
          kind: 'external',
          reason:
            'Es una llamada saliente de Atlas al proveedor externo (Twilio, SendGrid, Brevo, Firebase, APNs), no una ruta que Atlas sirva.',
          errors: ['BREVO_SMS_NO_CREDITS', 'APNS_NOT_CONFIGURED', 'PUSH_PROVIDER_DISABLED'],
        },
        {
          code: 'notif.retry_stuck',
          name: 'Reintentar mensajes atascados',
          description: 'Reintenta los mensajes que llevan demasiado tiempo sin salir; excluye los de campaña y los programados a futuro.',
          kind: 'job',
          job: 'retry_stuck_notifications',
          repeatable: true,
        },
      ],
    },
    {
      code: 'notif_provider_callbacks',
      name: 'Estado de entrega que devuelve el proveedor',
      description:
        'Twilio, Brevo y SendGrid avisan cómo terminó cada mensaje. Se protegen por firma (Twilio, SendGrid) o por secreto en la ruta (Brevo); gana el primer estado terminal.',
      module: 'notifications',
      actor: 'external_provider',
      client: 'BLOCK',
      steps: [
        {
          code: 'notif.twilio_status',
          name: 'Recibir el estado de un SMS de Twilio',
          description: 'Verifica la firma sobre la URL configurada y aplica el estado a la entrega.',
          method: 'POST',
          path: '/internal/notifications/twilio-status',
          auth: false,
          repeatable: true,
          errors: ['401 CALLBACK_TWILIO_NO_CONFIGURADO', '401 FIRMA_TWILIO_INVALIDA'],
          successStatus: [200],
        },
        {
          code: 'notif.brevo_sms_events',
          name: 'Recibir el estado de un SMS de Brevo',
          description: 'Brevo no firma: la credencial es el secreto de la ruta. soft_bounce no es terminal.',
          method: 'POST',
          path: '/internal/notifications/brevo-sms-events/:secreto',
          auth: false,
          repeatable: true,
          errors: ['401 CALLBACK_BREVO_NO_AUTORIZADO'],
          successStatus: [200],
        },
        {
          code: 'notif.sendgrid_events',
          name: 'Recibir el lote de eventos de correo de SendGrid',
          description: 'Verifica la firma sobre el cuerpo crudo y aplica cada evento (entregado, rebotado, abierto).',
          method: 'POST',
          path: '/internal/notifications/sendgrid-events',
          auth: false,
          repeatable: true,
          errors: ['401 CALLBACK_SENDGRID_NO_CONFIGURADO', '401 FIRMA_SENDGRID_INVALIDA', '401 CUERPO_CRUDO_NO_DISPONIBLE'],
          successStatus: [200],
        },
      ],
    },
    {
      code: 'notif_customer_inbox',
      name: 'El cliente recibe, lee y elige canales',
      description: 'Bandeja de avisos de la app, contador de no leídos, preferencias por canal y registro del dispositivo para push.',
      module: 'notifications',
      actor: 'customer',
      client: 'CONSUMER_APP',
      steps: [
        {
          code: 'notif.device_token_register',
          name: 'Registrar el dispositivo para avisos push',
          description: 'La app guarda el token de Firebase o APNs del teléfono; sin él no hay canal push.',
          method: 'POST',
          path: '/customers/:customerId/device-tokens',
          roles: CUSTOMER_ROLES,
        },
        {
          code: 'notif.device_token_delete',
          name: 'Quitar el dispositivo',
          description: 'Da de baja el token del dispositivo (cierre de sesión o avisos desactivados).',
          method: 'DELETE',
          path: '/customers/:customerId/device-tokens/:deviceTokenId',
          roles: CUSTOMER_ROLES,
          optional: true,
        },
        {
          code: 'notif.customer_list',
          name: 'Ver la bandeja de avisos',
          description: 'Lista los avisos in-app del cliente.',
          method: 'GET',
          path: '/customers/:customerId/notifications',
          roles: CUSTOMER_ROLES,
        },
        {
          code: 'notif.customer_unread',
          name: 'Contar avisos sin leer',
          description: 'Alimenta el indicador de la campana de la app.',
          method: 'GET',
          path: '/customers/:customerId/notifications/unread-count',
          roles: CUSTOMER_ROLES,
          repeatable: true,
        },
        {
          code: 'notif.customer_read',
          name: 'Marcar un aviso como leído',
          description: 'El estado leído no se degrada después.',
          method: 'POST',
          path: '/customers/:customerId/notifications/:notificationId/read',
          roles: CUSTOMER_ROLES,
        },
        {
          code: 'notif.customer_read_all',
          name: 'Marcar todos como leídos',
          description: 'Vacía el contador de no leídos.',
          method: 'POST',
          path: '/customers/:customerId/notifications/read-all',
          roles: CUSTOMER_ROLES,
          optional: true,
        },
        {
          code: 'notif.customer_preferences_get',
          name: 'Consultar preferencias de avisos',
          description: 'Qué canales acepta el cliente para cada tipo de aviso.',
          method: 'GET',
          path: '/customers/:customerId/notification-preferences',
          roles: CUSTOMER_ROLES,
          optional: true,
        },
        {
          code: 'notif.customer_preferences_update',
          name: 'Cambiar preferencias de avisos',
          description: 'El cliente activa o apaga canales; el consentimiento comercial filtra también las campañas.',
          method: 'PATCH',
          path: '/customers/:customerId/notification-preferences',
          roles: CUSTOMER_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'notif_ops_messages',
      name: 'Operaciones sigue, reintenta o cancela mensajes',
      description:
        'Desde Notificaciones del portal admin: cola de mensajes con su entrega por proveedor, reintento o cancelación, plantillas, preferencias de un cliente y aviso in-app a muchos (broadcast).',
      module: 'notifications',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/notifications',
      roles: OPS_READ_ROLES,
      steps: [
        {
          code: 'notif.ops_list_messages',
          name: 'Listar mensajes',
          description: 'Cola de mensajes con estado, canal y destinatario.',
          method: 'GET',
          path: '/operations/notifications/messages',
          roles: OPS_READ_ROLES,
        },
        {
          code: 'notif.ops_get_message',
          name: 'Ver un mensaje y sus entregas',
          description: 'Detalle con las entregas por canal y el código de error del proveedor.',
          method: 'GET',
          path: '/operations/notifications/messages/:messageId',
          roles: OPS_READ_ROLES,
        },
        {
          code: 'notif.ops_retry_message',
          name: 'Reintentar un mensaje fallido',
          description: 'Vuelve a entregar el mensaje por sus canales.',
          method: 'POST',
          path: '/operations/notifications/messages/:messageId/retry',
          roles: OPS_ACT_ROLES,
          optional: true,
        },
        {
          code: 'notif.ops_cancel_message',
          name: 'Cancelar un mensaje',
          description: 'Anula un mensaje que todavía no salió.',
          method: 'POST',
          path: '/operations/notifications/messages/:messageId/cancel',
          roles: OPS_ACT_ROLES,
          optional: true,
        },
        {
          code: 'notif.ops_list_templates',
          name: 'Consultar plantillas',
          description: 'Plantillas por evento y canal con las que se redacta cada aviso.',
          method: 'GET',
          path: '/operations/notifications/templates',
          roles: OPS_READ_ROLES,
          optional: true,
        },
        {
          code: 'notif.ops_create_template',
          name: 'Crear una plantilla',
          description: 'Alta de plantilla para un evento y canal.',
          method: 'POST',
          path: '/operations/notifications/templates',
          roles: ['admin', 'platform_admin', 'system'],
          optional: true,
        },
        {
          code: 'notif.ops_update_template',
          name: 'Editar una plantilla',
          description: 'Cambia el texto o desactiva la plantilla.',
          method: 'PATCH',
          path: '/operations/notifications/templates/:templateId',
          roles: ['admin', 'platform_admin', 'system'],
          optional: true,
        },
        {
          code: 'notif.ops_get_preferences',
          name: 'Ver las preferencias de un cliente',
          description: 'Para explicar por qué un cliente no recibió un aviso por un canal.',
          method: 'GET',
          path: '/operations/notifications/preferences/:customerId',
          roles: OPS_READ_ROLES,
          optional: true,
        },
        {
          code: 'notif.ops_update_preferences',
          name: 'Cambiar las preferencias de un cliente',
          description: 'Ajuste de canales a pedido del cliente.',
          method: 'PATCH',
          path: '/operations/notifications/preferences/:customerId',
          roles: OPS_ACT_ROLES,
          optional: true,
        },
        {
          code: 'notif.ops_broadcast',
          name: 'Enviar un aviso in-app a muchos',
          description:
            'Crea avisos in-app para clientes y/o usuarios internos (todos los activos si no se indican). No usa correo, SMS ni push. Exige clave de idempotencia.',
          method: 'POST',
          path: '/operations/notifications/broadcast',
          roles: ['admin', 'platform_admin', 'system'],
          optional: true,
          idempotencyKey: true,
          successStatus: [202],
        },
      ],
    },
    {
      code: 'notif_ops_policies',
      name: 'Políticas de notificación',
      description: 'Operaciones consulta y ajusta las políticas que gobiernan los avisos desde Ajustes › Políticas de notificación.',
      module: 'notifications',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/settings/notification-policies',
      optional: true,
      roles: POLICY_READ_ROLES,
      steps: [
        {
          code: 'notif.policies_get',
          name: 'Consultar las políticas',
          description: 'Lista las políticas de notificación vigentes.',
          method: 'GET',
          path: '/operations/notification-policies',
          roles: POLICY_READ_ROLES,
          optional: true,
        },
        {
          code: 'notif.policies_put',
          name: 'Guardar las políticas',
          description: 'Reemplaza las políticas de notificación.',
          method: 'PUT',
          path: '/operations/notification-policies',
          roles: POLICY_WRITE_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'notif_internal_inbox',
      name: 'Avisos a personas internas',
      description:
        'Los eventos de operaciones (p. ej. risk.alert.created) llegan in-app a los usuarios internos, que los leen en Mis notificaciones.',
      module: 'notifications',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/my-notifications',
      optional: true,
      roles: INTERNAL_SELF_SERVICE_ROLES,
      steps: [
        {
          code: 'notif.internal_list',
          name: 'Ver mis avisos',
          description: 'Bandeja del usuario interno.',
          method: 'GET',
          path: '/internal-users/me/notifications',
          roles: INTERNAL_SELF_SERVICE_ROLES,
          optional: true,
        },
        {
          code: 'notif.internal_unread',
          name: 'Contar mis avisos sin leer',
          description: 'Indicador de la campana del portal.',
          method: 'GET',
          path: '/internal-users/me/notifications/unread-count',
          roles: INTERNAL_SELF_SERVICE_ROLES,
          optional: true,
        },
        {
          code: 'notif.internal_read',
          name: 'Marcar un aviso como leído',
          description: 'Marca un aviso interno.',
          method: 'POST',
          path: '/internal-users/me/notifications/:notificationId/read',
          roles: INTERNAL_SELF_SERVICE_ROLES,
          optional: true,
        },
        {
          code: 'notif.internal_read_all',
          name: 'Marcar todos como leídos',
          description: 'Vacía el contador del usuario interno.',
          method: 'POST',
          path: '/internal-users/me/notifications/read-all',
          roles: INTERNAL_SELF_SERVICE_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'campaign_authoring',
      name: 'Armar y programar la campaña en el ERP',
      description:
        'En ERP › Control › Notificaciones masivas: segmento de audiencia, contenido, canales y ventana; estimación de alcance, envío de prueba y programación. El ERP reenvía a Atlas con el token del actor.',
      module: 'notification_campaigns',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/admin/notificaciones',
      roles: ['ERP:ADMIN'],
      resultingStates: ['draft', 'scheduled'],
      steps: [
        {
          code: 'campaign.erp_list_segments',
          name: 'Consultar segmentos de audiencia',
          description: 'Segmentos guardados con su tamaño bruto.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/admin/notification-campaigns/segments',
          roles: ERP_READ_ROLES,
        },
        {
          code: 'campaign.erp_create_segment',
          name: 'Crear un segmento',
          description: 'Define una audiencia reutilizable.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/notification-campaigns/segments',
          roles: ERP_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'campaign.erp_update_segment',
          name: 'Editar un segmento',
          description: 'Cambia la definición de la audiencia.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/admin/notification-campaigns/segments/:segmentId',
          roles: ERP_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'campaign.erp_create',
          name: 'Crear la campaña en borrador',
          description: 'Contenido, canales, segmento y ventana; nace en borrador.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/notification-campaigns',
          roles: ERP_WRITE_ROLES,
          idempotencyKey: true,
          resultingStates: ['draft'],
        },
        {
          code: 'campaign.erp_estimate',
          name: 'Estimar el alcance',
          description: 'Cuántos clientes recibirían la campaña, ya descontado el consentimiento.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/notification-campaigns/audience/estimate',
          roles: ERP_READ_ROLES,
        },
        {
          code: 'campaign.erp_update',
          name: 'Editar la campaña',
          description: 'Editar una campaña programada la devuelve a borrador.',
          system: 'ERP_BACKEND',
          method: 'PATCH',
          path: '/admin/notification-campaigns/:campaignId',
          roles: ERP_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'campaign.erp_action',
          name: 'Probar, programar, pausar, reanudar, cancelar o duplicar',
          description:
            'Una ruta por verbo (schedule, unschedule, pause, resume, cancel, duplicate, test-send) que el ERP reenvía a Atlas. Programar congela la audiencia y exige que no esté vacía.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/admin/notification-campaigns/:campaignId/:action',
          roles: ERP_WRITE_ROLES,
          repeatable: true,
          resultingStates: ['scheduled', 'draft', 'paused', 'running', 'cancelled'],
        },
      ],
    },
    {
      code: 'campaign_upstream',
      name: 'Atlas valida y guarda la campaña',
      description:
        'Rutas de Atlas a las que la pasarela del ERP reenvía: aquí se validan audiencia, ventana y transiciones. Ninguna pantalla del portal admin las llama.',
      module: 'notifications',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'campaign.list_segments',
          name: 'Listar segmentos',
          description: 'Destino de la pasarela para leer segmentos.',
          method: 'GET',
          path: '/operations/notifications/audience-segments',
          roles: ['internal_operator', 'admin', 'platform_admin', 'system'],
        },
        {
          code: 'campaign.create_segment',
          name: 'Crear segmento',
          description: 'Guarda el tamaño bruto; el descuento por consentimiento se hace al estimar.',
          method: 'POST',
          path: '/operations/notifications/audience-segments',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'campaign.update_segment',
          name: 'Editar segmento',
          description: 'Actualiza la definición de audiencia.',
          method: 'PATCH',
          path: '/operations/notifications/audience-segments/:segmentId',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'campaign.create',
          name: 'Crear campaña',
          description: 'Alta en borrador; exige clave de idempotencia.',
          method: 'POST',
          path: '/operations/notifications/campaigns',
          roles: CAMPAIGN_WRITE_ROLES,
          idempotencyKey: true,
          resultingStates: ['draft'],
        },
        {
          code: 'campaign.estimate',
          name: 'Estimar audiencia',
          description: 'Resuelve la audiencia por el puerto de Clientes, sin leer tablas de otro dominio.',
          method: 'POST',
          path: '/operations/notifications/campaigns/audience/estimate',
          roles: CAMPAIGN_READ_ROLES,
        },
        {
          code: 'campaign.update',
          name: 'Editar campaña',
          description: 'Si estaba programada vuelve a borrador.',
          method: 'PATCH',
          path: '/operations/notifications/campaigns/:campaignId',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'campaign.test_send',
          name: 'Envío de prueba a un cliente',
          description: 'Entrega en el acto y devuelve el resultado por canal.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/test-send',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
        },
        {
          code: 'campaign.schedule',
          name: 'Programar',
          description: 'Congela la audiencia y exige que no esté vacía.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/schedule',
          roles: CAMPAIGN_WRITE_ROLES,
          idempotencyKey: true,
          requiredStates: ['draft'],
          resultingStates: ['scheduled'],
          errors: ['409 NOTIFICATION_CAMPAIGN_STATUS_CHANGED', '409 NOTIFICATION_CAMPAIGN_INVALID_TRANSITION'],
        },
        {
          code: 'campaign.unschedule',
          name: 'Desprogramar',
          description: 'Devuelve a borrador una campaña programada que aún no empezó.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/unschedule',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          requiredStates: ['scheduled'],
          resultingStates: ['draft'],
        },
        {
          code: 'campaign.pause',
          name: 'Pausar',
          description: 'Detiene una campaña en curso.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/pause',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          requiredStates: ['running'],
          resultingStates: ['paused'],
        },
        {
          code: 'campaign.resume',
          name: 'Reanudar',
          description: 'Retoma una campaña pausada.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/resume',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          requiredStates: ['paused'],
          resultingStates: ['running'],
        },
        {
          code: 'campaign.cancel',
          name: 'Cancelar',
          description: 'Anula los avisos que aún no salieron; exige un motivo.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/cancel',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          resultingStates: ['cancelled'],
        },
        {
          code: 'campaign.duplicate',
          name: 'Duplicar',
          description: 'Copia la campaña como borrador nuevo.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/duplicate',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          idempotencyKey: true,
          resultingStates: ['draft'],
        },
      ],
    },
    {
      code: 'campaign_run',
      name: 'El planificador ejecuta la campaña',
      description:
        'Cada tick arranca las campañas programadas cuya hora llegó, materializa la audiencia por tandas a la cadencia configurada y entrega; al agotar la audiencia la marca completada, y si revienta, fallida con su último error.',
      module: 'notifications',
      actor: 'system',
      client: 'BLOCK',
      requiredStates: ['scheduled', 'running'],
      resultingStates: ['running', 'completed', 'failed'],
      steps: [
        {
          code: 'campaign.run_tick',
          name: 'Avanzar las campañas en curso',
          description: 'scheduled → running al llegar su hora; running → completed al terminar; running → failed ante un error.',
          kind: 'job',
          job: 'run_notification_campaigns',
          repeatable: true,
          resultingStates: ['running', 'completed', 'failed'],
        },
      ],
    },
    {
      code: 'campaign_follow_up',
      name: 'Seguimiento de resultados en el ERP',
      description: 'El ERP muestra la lista de campañas, su detalle y los mensajes por canal con su estado.',
      module: 'notification_campaigns',
      actor: 'internal_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/admin/notificaciones',
      roles: ['ERP:ADMIN', 'ERP:OPERATIONS', 'ERP:COMMERCIAL_MANAGER', 'ERP:AUDITOR'],
      terminal: true,
      steps: [
        {
          code: 'campaign.erp_list',
          name: 'Listar campañas',
          description: 'Lista con filtros por estado, canal y texto.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/admin/notification-campaigns',
          roles: ERP_READ_ROLES,
        },
        {
          code: 'campaign.erp_get',
          name: 'Ver una campaña',
          description: 'Detalle con destinatarios alcanzados y creados.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/admin/notification-campaigns/:campaignId',
          roles: ERP_READ_ROLES,
        },
        {
          code: 'campaign.erp_messages',
          name: 'Ver los mensajes de la campaña',
          description: 'Mensajes por canal con su estado de entrega.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/admin/notification-campaigns/:campaignId/messages',
          roles: ERP_READ_ROLES,
        },
      ],
    },
    {
      code: 'campaign_admin_observation',
      name: 'Operaciones observa campañas desde el portal admin',
      description:
        'La sección Campañas del portal admin lista las campañas y sus segmentos, abre el detalle con los mensajes por canal y deja pausar, reanudar o cancelar (esto último sólo admin y platform_admin). Crear y programar sigue en el ERP.',
      module: 'notifications',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/notifications/campaigns',
      optional: true,
      roles: CAMPAIGN_READ_ROLES,
      steps: [
        {
          code: 'campaign.list',
          name: 'Listar campañas',
          description: 'Lista paginada con filtro por estado.',
          method: 'GET',
          path: '/operations/notifications/campaigns',
          roles: CAMPAIGN_READ_ROLES,
          optional: true,
        },
        {
          code: 'campaign.get',
          name: 'Ver una campaña',
          description: 'Detalle con contadores de destinatarios.',
          method: 'GET',
          path: '/operations/notifications/campaigns/:campaignId',
          roles: CAMPAIGN_READ_ROLES,
          optional: true,
        },
        {
          code: 'campaign.messages',
          name: 'Ver los mensajes de la campaña',
          description: 'Mensajes y su estado por canal.',
          method: 'GET',
          path: '/operations/notifications/campaigns/:campaignId/messages',
          roles: CAMPAIGN_READ_ROLES,
          optional: true,
        },
        {
          code: 'campaign.admin_segments',
          name: 'Ver los segmentos de audiencia',
          description: 'Lista de segmentos guardados, sólo lectura.',
          method: 'GET',
          path: '/operations/notifications/audience-segments',
          roles: CAMPAIGN_READ_ROLES,
          optional: true,
        },
        {
          code: 'campaign.admin_pause',
          name: 'Pausar desde el portal',
          description: 'Detiene una campaña en curso; pide confirmación.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/pause',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          requiredStates: ['running'],
          resultingStates: ['paused'],
        },
        {
          code: 'campaign.admin_resume',
          name: 'Reanudar desde el portal',
          description: 'Retoma una campaña pausada.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/resume',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          requiredStates: ['paused'],
          resultingStates: ['running'],
        },
        {
          code: 'campaign.admin_cancel',
          name: 'Cancelar desde el portal',
          description: 'Anula los avisos que aún no salieron; exige un motivo.',
          method: 'POST',
          path: '/operations/notifications/campaigns/:campaignId/cancel',
          roles: CAMPAIGN_WRITE_ROLES,
          optional: true,
          resultingStates: ['cancelled'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'notif.entry_transactional',
      from: null,
      to: 'notif.process_events',
      condition: 'always',
      description: 'Rama transaccional: un evento de dominio con canales.',
      isDefault: true,
    },
    {
      code: 'notif.entry_campaign',
      from: null,
      to: 'campaign.erp_create',
      condition: 'conditional',
      expression: { origin: 'campaign' },
      description: 'Rama de campaña: un administrador del ERP la crea.',
    },
    {
      code: 'notif.events_to_send',
      from: 'notif.process_events',
      to: 'notif.provider_send',
      condition: 'on_success',
      description: 'El mensaje creado sale por sus canales.',
      isDefault: true,
    },
    {
      code: 'notif.send_to_callback',
      from: 'notif.provider_send',
      to: 'notif.twilio_status',
      condition: 'conditional',
      expression: { channel: 'sms', provider: 'twilio' },
      description: 'El proveedor avisa el estado final.',
    },
    {
      code: 'notif.send_to_brevo',
      from: 'notif.provider_send',
      to: 'notif.brevo_sms_events',
      condition: 'conditional',
      expression: { channel: 'sms', provider: 'brevo' },
      description: 'Brevo avisa el estado del SMS por la URL con secreto.',
    },
    {
      code: 'notif.send_to_sendgrid',
      from: 'notif.provider_send',
      to: 'notif.sendgrid_events',
      condition: 'conditional',
      expression: { channel: 'email' },
      description: 'SendGrid entrega el lote de eventos de correo.',
    },
    {
      code: 'notif.send_to_inbox',
      from: 'notif.provider_send',
      to: 'notif.customer_list',
      condition: 'conditional',
      expression: { channel: 'in_app' },
      description: 'El aviso in-app aparece en la bandeja del cliente.',
      isDefault: true,
    },
    {
      code: 'notif.send_failed',
      from: 'notif.provider_send',
      to: 'notif.retry_stuck',
      condition: 'on_error',
      description: 'Envío atascado: lo recoge el job de reintentos.',
    },
    {
      code: 'notif.ops_retry',
      from: 'notif.ops_get_message',
      to: 'notif.ops_retry_message',
      condition: 'conditional',
      expression: { status: 'failed' },
      description: 'Operaciones reintenta un mensaje fallido.',
    },
    {
      code: 'campaign.create_to_estimate',
      from: 'campaign.erp_create',
      to: 'campaign.erp_estimate',
      condition: 'on_success',
      description: 'Con el borrador creado se estima el alcance.',
      isDefault: true,
    },
    {
      code: 'campaign.estimate_to_action',
      from: 'campaign.erp_estimate',
      to: 'campaign.erp_action',
      condition: 'on_success',
      description: 'Prueba y programación.',
      isDefault: true,
    },
    {
      code: 'campaign.action_to_run',
      from: 'campaign.erp_action',
      to: 'campaign.run_tick',
      condition: 'conditional',
      expression: { action: 'schedule' },
      description: 'Programada, la toma el planificador a su hora.',
      isDefault: true,
    },
    {
      code: 'campaign.run_to_send',
      from: 'campaign.run_tick',
      to: 'notif.provider_send',
      condition: 'on_success',
      description: 'Cada tanda de la audiencia sale por sus canales.',
    },
    {
      code: 'campaign.run_to_follow',
      from: 'campaign.run_tick',
      to: 'campaign.erp_get',
      condition: 'always',
      description: 'El administrador sigue el resultado.',
      isDefault: true,
    },
    {
      code: 'campaign.exit',
      from: 'campaign.erp_messages',
      to: null,
      condition: 'always',
      description: 'Salida: la campaña terminó y sus mensajes tienen estado.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'campaign.erp_estimate',
      dependsOn: 'campaign.erp_create',
      type: 'requires_data',
      description: 'Se estima el alcance de una campaña existente.',
    },
    {
      step: 'campaign.run_tick',
      dependsOn: 'campaign.erp_action',
      type: 'requires_completion',
      description: 'El planificador sólo arranca campañas programadas.',
    },
    {
      step: 'notif.provider_send',
      dependsOn: 'notif.process_events',
      type: 'requires_data',
      description: 'Sin mensaje creado no hay nada que entregar.',
    },
    {
      step: 'notif.twilio_status',
      dependsOn: 'notif.provider_send',
      type: 'requires_completion',
      description: 'El estado se refiere a un envío ya aceptado por el proveedor.',
    },
    {
      step: 'notif.ops_retry_message',
      dependsOn: 'notif.ops_get_message',
      type: 'soft',
      description: 'Se reintenta tras ver por qué falló.',
    },
  ],
};
