/**
 * @file Proceso declarado en código: Evaluación de riesgo del alta (Motor → ruleset local → heurística).
 * @business Ningún cliente se habilita sin una evaluación de riesgo aprobada y de menos de 90 días: este proceso la produce al enviar el alta, deja escrito de qué escalón salió la decisión y, si hace falta, la pone en manos de una persona.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; escrita el 2026-09-26 desde `risk/`, `operations/`, `decision-engine/` y el Motor.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const RISK_READERS = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'];
const OPERATIONS_READERS = ['internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'];
const MOTOR_REVIEWERS = ['MOTOR:OPERATIONS', 'MOTOR:RISK_ANALYST', 'MOTOR:FRAUD_ANALYST'];

export const ONBOARDING_RISK_ASSESSMENT: WorkflowDefinitionFixture = {
  processId: 'P-04',
  code: 'onboarding_risk_assessment',
  version: 'v1',
  name: 'Evaluación de riesgo del alta (Motor → ruleset local → heurística)',
  description:
    'Al enviar el alta se calcula el riesgo del cliente por una cadena de tres escalones —Motor de decisiones, ruleset local versionado y heurística v0—, se guarda de cuál salió la decisión y, si no es «sigue adelante», se abre un caso de revisión manual que resuelve una persona en el portal o en el Motor.',
  processType: 'integration',
  ownerDomain: 'risk',
  ownerRole: 'RISK_ANALYST',
  priority: 'P0',
  systems: ['ATLAS_BACKEND', 'DECISION_ENGINE'],
  narrative: {
    whyExists:
      'La habilitación del cliente exige una evaluación de riesgo aprobada y vigente (bloqueadores RISK_NOT_APPROVED y RISK_ASSESSMENT_STALE, 90 días). Antes nada la disparaba y el cliente quedaba en under_review para siempre; este proceso la calcula sola al enviar el alta y deja trazado qué escalón decidió.',
    whoStartsAndCloses:
      'Lo inicia el sistema cuando el cliente envía el alta (no hay botón). Lo cierra el propio cálculo si la decisión es approved_for_next_step; si no, lo cierra una persona: un analista desde la cola de trabajo del portal, o desde la bandeja del Motor cuando fue el Motor quien abrió el caso y avisa de vuelta.',
    startAndEnd:
      'Empieza con el envío del alta, que llama a la evaluación con assessmentType onboarding_initial antes de pasar al cliente a under_review. Termina con una fila en risk_assessment_runs con su decision_source y, si hizo falta, con el caso de manual_review_cases cerrado como approved o rejected y la elegibilidad reevaluada.',
    whenItFails:
      'Si el Motor no responde se baja de escalón (ruleset y luego heurística) sin bloquear el alta. Si la evaluación entera falla, el envío sigue y el cliente queda con RISK_NOT_APPROVED hasta que se recalcule; sólo lo deja en el registro del servidor. Un caso delegado al Motor no se puede cerrar desde el portal (MANUAL_REVIEW_DELEGADA_AL_MOTOR).',
    healthIndicator:
      'Reparto de risk_assessment_runs.decision_source entre decision_engine, engine_no_decision, ruleset y heuristic_v0 (hoy el Motor no ha decidido ningún riesgo de onboarding), y número y antigüedad de casos risk_assessment_review abiertos en manual_review_cases.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'case_management',
    table: 'manual_review_cases',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'case_code',
    openStatuses: ['open', 'in_review', 'pending', 'escalated'],
  },
  success:
    'El cliente tiene una evaluación de riesgo approved_for_next_step (automática o tras revisión humana) y la elegibilidad reevaluada.',
  failure: 'La evaluación no se pudo calcular o quedó en manual_review_required con un caso abierto que nadie resuelve.',
  sources: [
    'src/modules/customer-onboarding/application/onboarding-risk-trigger.service.ts',
    'src/modules/customer-onboarding/application/customer-onboarding-status.service.ts',
    'src/modules/risk/risk.controller.ts',
    'src/modules/risk/risk.service.ts',
    'src/modules/risk/application/risk-policy-decision.service.ts',
    'src/modules/risk/application/risk-assessment-persistence.ts',
    'src/modules/risk/application/risk-manual-review-outcome.service.ts',
    'src/modules/risk/risk-review-callback.controller.ts',
    'src/modules/decision-engine/risk-decision-engine.service.ts',
    'src/modules/decision-engine/decision-engine.client.ts',
    'src/modules/operations/operations.controller.ts',
    'src/modules/operations/operations.service.ts',
    'src/modules/operations/manual-review-decision-guards.ts',
    'src/modules/catalog-management/catalog-governance.controller.ts',
    'src/modules/customers/customer-eligibility.constants.ts',
    'AtlasDecisionEngineBackend/src/modules/runtime/runtime.controller.ts',
    'AtlasDecisionEngineBackend/src/modules/manual-review/manual-review.controller.ts',
    'AtlasAdminPortal/src/features/operations-cases/work-queue-page.tsx',
    'AtlasAdminPortal/src/features/risk-policy/current-risk-policy-page.tsx',
    'memoria atlas-portal-motor-duplicacion',
    'memoria atlas-plan-promesas-reales',
    'memoria atlas-plan-motor-decisiones-tasa',
    '_plan-promesas-reales-2026-09-14/PLAN.md',
    '_plan-motor-decisiones-tasa-2026-09-25/PLAN.md',
  ],
  metadata: {
    comesFrom: 'P-02 customer_onboarding_kyc (envío del alta)',
    handsOffTo: 'P-05 customer_eligibility_lifecycle (reevaluación de elegibilidad)',
    decisionSources: ['decision_engine', 'engine_no_decision', 'ruleset', 'heuristic_v0', 'manual_decision'],
  },
  stages: [
    {
      code: 'risk_trigger',
      name: 'Disparo al enviar el alta',
      description: 'El envío del alta pide la evaluación con el dispositivo que el servidor ya conoce. Una avería no tumba el envío.',
      module: 'risk',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      requiredStates: ['onboarding_in_progress', 'observed'],
      steps: [
        {
          code: 'risk.onboarding_trigger',
          name: 'Pedir la evaluación desde el envío',
          description:
            'OnboardingRiskTriggerService llama al servicio de riesgo con assessmentType onboarding_initial y una clave de idempotencia derivada.',
          kind: 'event',
          reason: 'Lo dispara el envío del alta dentro del mismo proceso (puerto ONBOARDING_RISK_PORT); no hay llamada HTTP.',
        },
        {
          code: 'risk.create_assessment',
          name: 'Crear una evaluación de riesgo por HTTP',
          description: 'La misma evaluación expuesta por HTTP, útil para recalcular. Sin llamador en ningún portal (triaje D).',
          method: 'POST',
          path: '/customers/:customerId/risk-assessments',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'system', 'admin', 'platform_admin'],
          optional: true,
          idempotencyKey: true,
          errors: ['404 cliente no encontrado', '422 CUSTOMER_BLOCKED_FOR_RISK_ASSESSMENT', '422 REQUIRED_CONSENT_MISSING'],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'risk_engine_decision',
      name: 'Decisión del Motor',
      description:
        'Primer escalón: el artefacto de riesgo asignado al inquilino (o DECISION_ENGINE_RISK_ARTIFACT). Cualquier desenlace que no sea «sigue» va a revisión; el riesgo no rechaza.',
      module: 'decision_engine',
      actor: 'system',
      client: 'BLOCK',
      link: '{MOTOR}/executions/{instanceId}',
      steps: [
        {
          code: 'risk.engine_execute',
          name: 'Ejecutar el artefacto de riesgo',
          description:
            'Devuelve desenlace, motivos, versión del artefacto, ejecución y, si abrió uno, el código del caso manual del Motor.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
          idempotencyKey: true,
          output: { status: 'string', outcome: 'string', executionId: 'string', manualReview: '{ caseCode } | null' },
        },
      ],
    },
    {
      code: 'risk_local_fallback',
      name: 'Política local de respaldo',
      description: 'Si el Motor no está configurado o no respondió: ruleset activo versionado y, sin él, la heurística v0.',
      module: 'risk',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      steps: [
        {
          code: 'risk.local_policy',
          name: 'Evaluar el ruleset local o la heurística v0',
          description: 'Guarda decision_source ruleset o heuristic_v0 en risk_assessment_runs.',
          kind: 'event',
          reason: 'Escalón interno de RiskPolicyDecisionService cuando el Motor no devolvió decisión; no hay llamada HTTP.',
        },
      ],
    },
    {
      code: 'risk_anchor_case',
      name: 'Caso de revisión manual (ancla)',
      description:
        'Con decisión distinta de approved_for_next_step se abre un caso risk_assessment_review en Atlas. Si el Motor abrió su propio caso, el de Atlas nace delegado (decision_execution_id).',
      module: 'risk',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      steps: [
        {
          code: 'risk.open_manual_case',
          name: 'Abrir el caso ancla',
          description: 'Prioridad high con riesgo alto, medium en otro caso; queda en status open.',
          kind: 'event',
          reason: 'Lo escribe la misma transacción de la evaluación (openManualReviewCase); no hay llamada HTTP.',
          resultingStates: ['open'],
        },
      ],
    },
    {
      code: 'risk_portal_review',
      name: 'Revisión en la cola de trabajo del portal',
      description:
        'El analista decide los casos NO delegados al Motor; la decisión corrige el resultado de riesgo y puede mover al cliente de estado.',
      module: 'operations',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/work-queue',
      optional: true,
      roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
      steps: [
        {
          code: 'risk.ops_work_queue',
          name: 'Ver la cola de trabajo',
          description: 'Cola combinada de revisión manual y fraude.',
          method: 'GET',
          path: '/operations/work-queue',
          roles: OPERATIONS_READERS,
        },
        {
          code: 'risk.ops_manual_cases',
          name: 'Listar los casos de revisión manual',
          description: 'Lista paginada por cursor. Sin llamador en el portal: la pantalla usa la cola combinada.',
          method: 'GET',
          path: '/operations/manual-review-cases',
          roles: OPERATIONS_READERS,
          optional: true,
        },
        {
          code: 'risk.ops_manual_decision',
          name: 'Decidir el caso',
          description:
            'approved, rejected, request_more_information, escalated_to_fraud o no_action; rechazar o pedir información exige nota.',
          method: 'POST',
          path: '/operations/manual-review-cases/:caseId/decision',
          roles: ['internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['open'],
          resultingStates: ['closed'],
          errors: [
            '409 CASE_ALREADY_CLOSED',
            '409 MANUAL_REVIEW_DELEGADA_AL_MOTOR',
            '409 MANUAL_REVIEW_ES_DE_CREDITO',
            '422 DECISION_REASON_REQUIRED',
          ],
        },
      ],
    },
    {
      code: 'risk_assessment_detail',
      name: 'Detalle y explicación de la evaluación',
      description: 'Muestra quién decidió (decision_source) antes de explicar reglas y contribuciones.',
      module: 'risk',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/risk-assessments/[riskAssessmentRunId]',
      optional: true,
      roles: RISK_READERS,
      steps: [
        {
          code: 'risk.ops_detail',
          name: 'Ver la evaluación',
          description: 'Ejecución, resultado, escalón que decidió y caso abierto.',
          method: 'GET',
          path: '/operations/risk-assessments/:riskAssessmentRunId',
          roles: RISK_READERS,
        },
        {
          code: 'risk.ops_explanation',
          name: 'Ver la explicación',
          description: 'Reglas disparadas y contribuciones; con el Motor como fuente, es contexto y no explicación.',
          method: 'GET',
          path: '/operations/risk-assessments/:riskAssessmentRunId/explanation',
          roles: RISK_READERS,
        },
      ],
    },
    {
      code: 'risk_policy_view',
      name: 'Política de riesgo vigente',
      description: 'El ruleset local que actúa de respaldo. La página pide lineage.read y el menú operations.riskPolicy.read.',
      module: 'catalog_management',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/risk-policy/current',
      optional: true,
      roles: OPERATIONS_READERS,
      steps: [
        {
          code: 'risk.ops_policy_current',
          name: 'Ver la política vigente',
          description: 'Ruleset activo y su versión.',
          method: 'GET',
          path: '/operations/risk-policy/current',
          roles: OPERATIONS_READERS,
        },
      ],
    },
    {
      code: 'risk_motor_review',
      name: 'Revisión en la bandeja del Motor',
      description: 'Cuando el Motor abrió su caso, lo asigna y lo resuelve una persona en el portal del Motor.',
      module: 'decision_engine',
      actor: 'internal_user',
      client: 'MOTOR_PORTAL',
      screen: '/manual-reviews/[caseId]',
      link: '{MOTOR}/manual-reviews/{instanceId}',
      optional: true,
      roles: MOTOR_REVIEWERS,
      steps: [
        {
          code: 'risk.motor_case',
          name: 'Abrir el caso en el Motor',
          description: 'Expediente del caso de revisión del Motor.',
          system: 'DECISION_ENGINE',
          method: 'GET',
          path: '/v1/manual-reviews/:caseId',
          roles: MOTOR_REVIEWERS,
        },
        {
          code: 'risk.motor_assign',
          name: 'Asignarse el caso',
          description: 'Toma el caso para resolverlo.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/assign',
          roles: MOTOR_REVIEWERS,
          optional: true,
        },
        {
          code: 'risk.motor_resolve',
          name: 'Resolver el caso',
          description: 'APPROVE o DECLINE; el Motor avisa a Atlas por el callback.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/manual-reviews/:caseId/resolve',
          roles: MOTOR_REVIEWERS,
        },
      ],
    },
    {
      code: 'risk_motor_callback',
      name: 'Aviso de vuelta del Motor',
      description:
        'En una transacción: cierra el caso ancla, corrige el resultado de riesgo y reevalúa la elegibilidad, que puede activar al cliente sola.',
      module: 'risk',
      actor: 'system',
      client: 'BLOCK',
      optional: true,
      terminal: true,
      steps: [
        {
          code: 'risk.motor_callback',
          name: 'Aplicar la resolución del Motor',
          description: 'Autenticado por clave compartida (sin clave configurada responde 401). Sólo APPROVE y DECLINE se aplican.',
          method: 'POST',
          path: '/internal/risk/manual-review-callback',
          auth: false,
          input: { executionId: 'string', decision: 'APPROVE | DECLINE', reason: 'string', resolvedByInternalUserId: 'string?' },
          output: { applied: 'boolean', caseId: 'string', resolution: 'approved | rejected', lifecycleStatus: 'string' },
          errors: ['400 Falta executionId', '401 clave de callback ausente o inválida', '404 ningún caso nació de la ejecución'],
          resultingStates: ['closed'],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'risk.entry',
      from: null,
      to: 'risk.onboarding_trigger',
      condition: 'always',
      description: 'El envío del alta pide la evaluación.',
      isDefault: true,
    },
    {
      code: 'risk.trigger_to_engine',
      from: 'risk.onboarding_trigger',
      to: 'risk.engine_execute',
      condition: 'always',
      description: 'Primer escalón: el Motor.',
      isDefault: true,
    },
    {
      code: 'risk.engine_to_fallback',
      from: 'risk.engine_execute',
      to: 'risk.local_policy',
      condition: 'on_error',
      description: 'Sin artefacto, sin respuesta o sin estado completado: se baja a la política local.',
    },
    {
      code: 'risk.engine_approved',
      from: 'risk.engine_execute',
      to: null,
      condition: 'conditional',
      expression: { decision: 'approved_for_next_step' },
      description: 'El Motor dijo «sigue»: no se abre caso.',
      isDefault: true,
    },
    {
      code: 'risk.engine_to_case',
      from: 'risk.engine_execute',
      to: 'risk.open_manual_case',
      condition: 'conditional',
      expression: { decision: 'manual_review_required' },
      description: 'Cualquier otro desenlace (incluido NO_DECISION) va a revisión.',
    },
    {
      code: 'risk.fallback_to_case',
      from: 'risk.local_policy',
      to: 'risk.open_manual_case',
      condition: 'conditional',
      expression: { decision: 'manual_review_required' },
    },
    {
      code: 'risk.case_to_portal',
      from: 'risk.open_manual_case',
      to: 'risk.ops_work_queue',
      condition: 'conditional',
      expression: { decisionExecutionId: null },
      description: 'Caso no delegado: lo resuelve el portal.',
      isDefault: true,
    },
    {
      code: 'risk.case_to_motor',
      from: 'risk.open_manual_case',
      to: 'risk.motor_case',
      condition: 'conditional',
      expression: { motorAbrioCaso: true },
      description: 'Caso delegado: lo resuelve la bandeja del Motor.',
    },
    {
      code: 'risk.queue_to_decision',
      from: 'risk.ops_work_queue',
      to: 'risk.ops_manual_decision',
      condition: 'on_success',
      isDefault: true,
    },
    { code: 'risk.motor_case_to_resolve', from: 'risk.motor_case', to: 'risk.motor_resolve', condition: 'on_success', isDefault: true },
    {
      code: 'risk.motor_resolve_to_callback',
      from: 'risk.motor_resolve',
      to: 'risk.motor_callback',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'risk.portal_exit',
      from: 'risk.ops_manual_decision',
      to: null,
      condition: 'on_success',
      description: 'Caso cerrado desde el portal.',
    },
    {
      code: 'risk.motor_exit',
      from: 'risk.motor_callback',
      to: null,
      condition: 'on_success',
      description: 'Caso cerrado por el Motor; elegibilidad reevaluada.',
    },
  ],
  dependencies: [
    { step: 'risk.engine_execute', dependsOn: 'risk.onboarding_trigger', type: 'requires_completion' },
    {
      step: 'risk.ops_manual_decision',
      dependsOn: 'risk.open_manual_case',
      type: 'requires_data',
      description: 'Sólo se decide un caso que existe y no está delegado.',
    },
    {
      step: 'risk.motor_callback',
      dependsOn: 'risk.motor_resolve',
      type: 'requires_completion',
      description: 'El aviso lleva la ejecución de la que nació el caso.',
    },
    { step: 'risk.ops_explanation', dependsOn: 'risk.ops_detail', type: 'soft' },
  ],
};
