/**
 * @file Proceso declarado en código: De la sesión iniciada a la primera pantalla.
 * @business Decide qué ve el cliente justo después de iniciar sesión según dónde va en su alta: evita que la app tenga su propia copia de las reglas de habilitación y que dos pantallas digan cosas distintas.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; portada de la siembra demo el 2026-09-26 sin perder pasos, transiciones ni dependencias.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

export const POST_LOGIN_FIRST_SCREEN: WorkflowDefinitionFixture = {
  processId: 'C-02',
  code: 'post_login_first_screen',
  version: 'v1',
  name: 'De la sesión iniciada a la primera pantalla',
  description:
    'El arranque de la app, llamada por llamada: abrir sesión, resolver identidad y perfil, decidir por la compuerta de onboarding si va a inicio o a completar el alta, y traer los datos que la pantalla principal muestra.',
  processType: 'customer_journey',
  ownerDomain: 'sessions',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P1',
  systems: ['ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'Decide qué ve el cliente justo después de iniciar sesión según dónde va en su alta: evita que la app tenga su propia copia de las reglas de habilitación y que dos pantallas digan cosas distintas.',
    whoStartsAndCloses:
      'Lo dispara la app al recibir la sesión y lo cierra el Backend al devolver el estado y la pantalla que corresponde; ninguna persona interna interviene.',
    startAndEnd:
      'Empieza con la primera lectura autenticada tras el login y termina cuando la app pinta la pantalla de destino (continuar alta, esperar revisión, inicio con crédito).',
    whenItFails:
      'Si la lectura tarda más de 20 s la app muestra «sin conexión» (timeout, no caída); si el cliente está bloqueado recibe la pantalla de estado con su motivo, no un error.',
    healthIndicator:
      'Latencia p95 de la primera lectura tras el login por debajo de 2 s y cero pantallas de destino desconocidas en los registros de la app.',
  },
  success: 'Sesión abierta, identidad resuelta y pantalla principal con sus datos.',
  failure: 'La sesión no abre, el token no renueva o el expediente incompleto desvía al onboarding.',
  sources: ['src/database/seeders/demo/referencia.seed-data.ts'],
  stages: [
    {
      code: 'first_screen_session',
      name: 'Apertura de sesión',
      description: 'Abre la sesión de negocio (distinta del token): es la que sostiene la trazabilidad de todo lo que el usuario haga.',
      module: 'sessions',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin', 'system'],
      steps: [
        {
          code: 'first_screen.session_start',
          name: 'Abrir la sesión',
          description: 'Registra dispositivo, canal y contexto. Devuelve el sessionId que acompaña al resto de llamadas.',
          method: 'POST',
          path: '/customers/:customerId/sessions/start',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          idempotencyKey: true,
          input: {
            channel: 'mobile_app | web',
            deviceId: 'string',
            appVersion: 'string',
          },
          output: {
            sessionId: 'string',
            startedAt: 'ISO-8601',
          },
          errors: ['401 TOKEN_EXPIRED', '409 SESSION_ALREADY_OPEN'],
          events: ['session.started'],
          successStatus: [200, 201],
        },
        {
          code: 'first_screen.session_state',
          name: 'Consultar el estado de la sesión',
          description: 'Confirma que la sesión sigue viva y trae el contexto que la pantalla necesita para decidir qué mostrar.',
          method: 'GET',
          path: '/customers/:customerId/session-state',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          output: {
            status: 'active | expired',
            sessionId: 'string',
            lastSeenAt: 'ISO-8601',
          },
        },
        {
          code: 'first_screen.session_heartbeat',
          name: 'Mantener viva la sesión',
          description: 'Latido periódico mientras la pantalla está abierta. Sin él, la sesión caduca y el trabajo se pierde.',
          method: 'POST',
          path: '/customers/:customerId/sessions/:sessionId/heartbeat',
          roles: [
            'customer',
            'internal_operator',
            'risk_analyst',
            'compliance_analyst',
            'fraud_analyst',
            'admin',
            'platform_admin',
            'system',
          ],
          optional: true,
          repeatable: true,
          errors: ['404 SESSION_NOT_FOUND', '410 SESSION_EXPIRED'],
          successStatus: [200, 204],
        },
      ],
    },
    {
      code: 'first_screen_identity',
      name: 'Identidad y perfil',
      description: 'Quién es el usuario y qué puede hacer. Determina el saludo, el menú y los permisos de la pantalla.',
      module: 'customers',
      actor: 'customer',
      client: 'CONSUMER_APP',
      steps: [
        {
          code: 'first_screen.auth_me',
          name: 'Confirmar el actor autenticado',
          description: 'Rol, tenant y customerId del token. Es lo que decide qué app se pinta.',
          method: 'GET',
          path: '/auth/me',
          output: {
            sub: 'string',
            role: 'string',
            tenantId: 'string',
            customerId: 'string',
          },
          errors: ['401 TOKEN_EXPIRED'],
        },
        {
          code: 'first_screen.customer_me',
          name: 'Traer el perfil del cliente',
          description: 'Nombre, estado del ciclo de vida y datos de cabecera que la pantalla muestra.',
          method: 'GET',
          path: '/customers/:customerId/me',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'admin', 'platform_admin'],
          output: {
            fullName: 'string',
            customerId: 'string',
            lifecycleStatus: 'string',
          },
          errors: ['403 CUSTOMER_ACCESS_DENIED', '404 CUSTOMER_NOT_FOUND'],
        },
        {
          code: 'first_screen.token_refresh',
          name: 'Renovar el token de acceso',
          description: 'Rama de excepción: si el token venció durante el arranque, se renueva y se reintenta sin echar al usuario.',
          method: 'POST',
          path: '/auth/refresh',
          auth: false,
          optional: true,
          input: {
            refreshToken: 'string',
          },
          errors: ['401 REFRESH_TOKEN_INVALID'],
        },
      ],
    },
    {
      code: 'first_screen_gate',
      name: 'Compuerta de onboarding',
      description: 'La bifurcación que decide la primera pantalla: expediente completo va a inicio; incompleto va a terminar el alta.',
      module: 'customer_onboarding',
      actor: 'system',
      client: 'BLOCK',
      completionRule: {
        type: 'lifecycle_status',
        statuses: ['active', 'under_review'],
      },
      steps: [
        {
          code: 'first_screen.onboarding_status',
          name: 'Consultar el avance del onboarding',
          description: 'Secciones completas, porcentaje y próximo paso. Es la fuente de la decisión, no una heurística del cliente.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/status',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          output: {
            status: 'string',
            nextStep: 'string',
            sections: 'SectionStatus[]',
            completionPercentage: 'number',
          },
        },
        {
          code: 'first_screen.observations',
          name: 'Consultar las observaciones abiertas',
          description:
            'Si el back office devolvió el expediente, aquí está QUÉ hay que corregir: es lo que la pantalla debe mostrar primero.',
          method: 'GET',
          path: '/customer-onboarding/:customerId/observations',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          output: {
            observations: 'Observation[]',
          },
        },
        {
          code: 'first_screen.eligibility',
          name: 'Consultar la elegibilidad',
          description: 'Qué tiene habilitado el cliente y qué bloqueadores le quedan. Decide qué acciones se pintan activas.',
          method: 'GET',
          path: '/customers/:customerId/eligibility',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'compliance_analyst', 'fraud_analyst', 'admin', 'platform_admin'],
          output: {
            blockers: 'BlockerCode[]',
            eligible: 'boolean',
          },
        },
      ],
    },
    {
      code: 'first_screen_home',
      name: 'Datos de la primera pantalla',
      description: 'Lo que se pinta: productos disponibles, solicitudes en curso y avisos. Con esto la pantalla ya es útil.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      terminal: true,
      steps: [
        {
          code: 'first_screen.credit_products',
          name: 'Listar los productos disponibles',
          description: 'Catálogo vigente para ese cliente: es el cuerpo de la pantalla principal.',
          method: 'GET',
          path: '/customers/:customerId/credit-products',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          output: {
            products: 'CreditProductDto[]',
          },
        },
        {
          code: 'first_screen.credit_applications',
          name: 'Listar las solicitudes en curso',
          description: 'Si el cliente ya pidió algo, la pantalla muestra su estado en vez del catálogo vacío.',
          method: 'GET',
          path: '/customers/:customerId/credit-applications',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          output: {
            applications: 'CreditApplicationDto[]',
          },
        },
        {
          code: 'first_screen.unread_count',
          name: 'Contar las notificaciones sin leer',
          description: 'El punto rojo de la campana. Se pide siempre porque es barato y cambia a menudo.',
          method: 'GET',
          path: '/customers/:customerId/notifications/unread-count',
          roles: ['customer', 'internal_operator', 'admin', 'platform_admin'],
          output: {
            unreadCount: 'number',
          },
        },
        {
          code: 'first_screen.notifications',
          name: 'Listar las notificaciones',
          description: 'El detalle de los avisos, ya con la pantalla pintada.',
          method: 'GET',
          path: '/customers/:customerId/notifications',
          roles: ['customer', 'internal_operator', 'admin', 'platform_admin'],
          optional: true,
          output: {
            items: 'NotificationDto[]',
            total: 'number',
          },
        },
        {
          code: 'first_screen.device_token',
          name: 'Registrar el token de notificaciones push',
          description: 'Registra el dispositivo para avisos push. Opcional: sólo si el usuario dio permiso.',
          method: 'POST',
          path: '/customers/:customerId/device-tokens',
          roles: ['customer', 'internal_operator', 'admin', 'platform_admin'],
          optional: true,
          input: {
            token: 'string',
            platform: 'ios | android',
          },
          successStatus: [200, 201],
        },
        {
          code: 'first_screen.telemetry',
          name: 'Enviar la telemetría de la pantalla',
          description: 'Cierra el recorrido: reporta que la pantalla se pintó y cuánto tardó.',
          method: 'POST',
          path: '/customers/:customerId/telemetry/batch',
          roles: ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'],
          optional: true,
          input: {
            events: '[{ name, occurredAt, payload }]',
          },
          successStatus: [200, 202],
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'first_screen.entry',
      from: null,
      to: 'first_screen.session_start',
      condition: 'always',
      description: 'Entrada: con el token en la mano, la app abre su sesión de negocio.',
      isDefault: true,
    },
    {
      code: 'first_screen.start_to_state',
      from: 'first_screen.session_start',
      to: 'first_screen.session_state',
      condition: 'on_success',
      description: 'Abierta la sesión, se lee su estado.',
      isDefault: true,
    },
    {
      code: 'first_screen.state_to_heartbeat',
      from: 'first_screen.session_state',
      to: 'first_screen.session_heartbeat',
      condition: 'conditional',
      expression: {
        screenVisible: true,
      },
      description: 'Mientras la pantalla esté abierta, se late.',
    },
    {
      code: 'first_screen.state_to_me',
      from: 'first_screen.session_state',
      to: 'first_screen.auth_me',
      condition: 'on_success',
      description: 'Sesión viva: se resuelve quién es el usuario.',
      isDefault: true,
    },
    {
      code: 'first_screen.me_to_refresh',
      from: 'first_screen.auth_me',
      to: 'first_screen.token_refresh',
      condition: 'on_error',
      description: 'Token vencido durante el arranque: se renueva en vez de echar al usuario.',
    },
    {
      code: 'first_screen.refresh_to_me',
      from: 'first_screen.token_refresh',
      to: 'first_screen.auth_me',
      condition: 'on_success',
      description: 'Renovado el token, se reintenta la identidad.',
    },
    {
      code: 'first_screen.me_to_profile',
      from: 'first_screen.auth_me',
      to: 'first_screen.customer_me',
      condition: 'on_success',
      description: 'Con el customerId se trae el perfil de cabecera.',
      isDefault: true,
    },
    {
      code: 'first_screen.profile_to_status',
      from: 'first_screen.customer_me',
      to: 'first_screen.onboarding_status',
      condition: 'on_success',
      description: 'Compuerta: se mira el avance del expediente.',
      isDefault: true,
    },
    {
      code: 'first_screen.status_to_observations',
      from: 'first_screen.onboarding_status',
      to: 'first_screen.observations',
      condition: 'on_state',
      expression: {
        lifecycleStatus: ['registered', 'in_progress', 'observed'],
      },
      description: 'Expediente incompleto o devuelto: la primera pantalla es la de corregir.',
    },
    {
      code: 'first_screen.status_to_eligibility',
      from: 'first_screen.onboarding_status',
      to: 'first_screen.eligibility',
      condition: 'on_state',
      expression: {
        lifecycleStatus: ['active', 'under_review'],
      },
      description: 'Expediente completo: se resuelve qué tiene habilitado.',
      isDefault: true,
    },
    {
      code: 'first_screen.eligibility_to_products',
      from: 'first_screen.eligibility',
      to: 'first_screen.credit_products',
      condition: 'on_success',
      description: 'Se pinta el catálogo filtrado por su elegibilidad.',
      isDefault: true,
    },
    {
      code: 'first_screen.products_to_applications',
      from: 'first_screen.credit_products',
      to: 'first_screen.credit_applications',
      condition: 'on_success',
      description: 'Y las solicitudes que ya tenga en curso.',
      isDefault: true,
    },
    {
      code: 'first_screen.applications_to_unread',
      from: 'first_screen.credit_applications',
      to: 'first_screen.unread_count',
      condition: 'on_success',
      description: 'El contador de la campana.',
      isDefault: true,
    },
    {
      code: 'first_screen.unread_to_list',
      from: 'first_screen.unread_count',
      to: 'first_screen.notifications',
      condition: 'conditional',
      expression: {
        unreadCount: '> 0',
      },
      description: 'Si hay avisos, se trae el detalle.',
    },
    {
      code: 'first_screen.unread_to_device',
      from: 'first_screen.unread_count',
      to: 'first_screen.device_token',
      condition: 'conditional',
      expression: {
        pushPermissionGranted: true,
      },
      description: 'Si el usuario dio permiso, se registra el dispositivo para push.',
    },
    {
      code: 'first_screen.to_telemetry',
      from: 'first_screen.unread_count',
      to: 'first_screen.telemetry',
      condition: 'on_success',
      description: 'Pantalla pintada: se reporta la telemetría de arranque.',
      isDefault: true,
    },
    {
      code: 'first_screen.exit',
      from: 'first_screen.telemetry',
      to: null,
      condition: 'always',
      description: 'Salida: el usuario ya está en la primera pantalla, operativa.',
      isDefault: true,
    },
  ],
  dependencies: [
    {
      step: 'first_screen.session_state',
      dependsOn: 'first_screen.session_start',
      type: 'requires_data',
      description: 'Necesita el sessionId que devuelve la apertura.',
    },
    {
      step: 'first_screen.session_heartbeat',
      dependsOn: 'first_screen.session_start',
      type: 'requires_data',
      description: 'El latido va contra un sessionId concreto.',
    },
    {
      step: 'first_screen.customer_me',
      dependsOn: 'first_screen.auth_me',
      type: 'requires_data',
      description: 'El customerId sale del token resuelto.',
    },
    {
      step: 'first_screen.onboarding_status',
      dependsOn: 'first_screen.customer_me',
      type: 'requires_data',
      description: 'Se consulta el avance del cliente identificado.',
    },
    {
      step: 'first_screen.credit_products',
      dependsOn: 'first_screen.eligibility',
      type: 'requires_completion',
      description: 'El catálogo se filtra por lo que el cliente tiene habilitado.',
    },
    {
      step: 'first_screen.telemetry',
      dependsOn: 'first_screen.credit_products',
      type: 'soft',
      description: 'Se reporta cuando la pantalla ya tiene contenido.',
    },
  ],
};
