/**
 * @file Proceso declarado en código: Compra con QR del comercio y desembolso del préstamo.
 * @business La compra a plazos es el producto: el cliente escanea el QR de la caja, el Motor decide el crédito, el comercio confirma la venta y Atlas convierte la aprobación en un préstamo con cuotas que el comercio ve en su cartera.
 * @system fixture que `syncWorkflowCatalog` vuelca a `workflow_*`; escrita el 2026-09-26 contra el código de AtlasBackend, AtlasERPBackend, AtlasERPFrontend y la app del cliente.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

const CUSTOMER_AND_STAFF = ['customer', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const MERCHANT_AND_STAFF = ['merchant', 'internal_operator', 'risk_analyst', 'admin', 'platform_admin'];
const ERP_MERCHANT_ROLES = ['merchant', 'MERCHANT_ADMIN', 'MERCHANT_OPERATIONS', 'OPERATIONS', 'ADMIN'];

export const PURCHASE_AND_DISBURSEMENT: WorkflowDefinitionFixture = {
  processId: 'P-08',
  code: 'purchase_and_disbursement',
  version: 'v1',
  name: 'Compra con QR del comercio y desembolso del préstamo',
  description:
    'Del escaneo del QR de caja a un préstamo activo: resolución del comercio, solicitud de crédito decidida por el Motor, aceptación del comercio desde el ERP, desembolso con cronograma y la venta visible en la cartera del comercio.',
  processType: 'customer_journey',
  ownerDomain: 'credit',
  ownerRole: 'OPERATIONS_MANAGER',
  priority: 'P0',
  systems: ['ATLAS_BACKEND', 'DECISION_ENGINE', 'ERP_BACKEND'],
  narrative: {
    whyExists:
      'Es el momento en que Atlas gana dinero y asume riesgo: una compra en un comercio verificado se financia con una aprobación del Motor, el comercio confirma la venta y el desembolso crea el préstamo y sus cuotas en una sola transacción, heredando qué ejecución del Motor lo decidió para poder medir su desenlace.',
    whoStartsAndCloses:
      'Lo inicia el cliente al escanear en la app el QR de la caja y fijar el monto; el comercio responde sí o no desde «Gestión POS» del portal del comercio; el desembolso sólo lo puede ejecutar un operador interno (internal_operator, admin o platform_admin) y hoy no existe ninguna pantalla ni proceso automático que lo llame.',
    startAndEnd:
      'Empieza con la resolución del token del QR (POST /merchant-qr/resolve) y la solicitud de crédito con el comercio y la caja; termina cuando POST /credit-applications/:applicationId/disbursement crea el préstamo en estado active con sus cuotas y consume el cupo reservado, y el comercio lo ve en «Mi cartera».',
    whenItFails:
      'Un QR ajeno, revocado o vencido se rechaza con QR_NOT_RECOGNIZED, QR_REVOKED o QR_EXPIRED; si el comercio declina, la solicitud no se desembolsa (CREDIT_BUSINESS_ACCEPTANCE_DECLINED); el desembolso aborta con 409 si la decisión venció (CREDIT_DECISION_EXPIRED), si el cliente retiró un consentimiento o si el importe ya no cabe en el cupo. Nadie recibe aviso: el cliente sólo ve la orden esperando.',
    healthIndicator:
      'Solicitudes aprobadas con aceptación del comercio que tienen préstamo en credit.loans (aprobado ≠ originado), tiempo entre aceptación y desembolso, y préstamos desembolsados que el job register_engine_facilities ya dio de alta en el Motor; hoy la primera cifra depende de un desembolso sin llamador.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'credit',
    table: 'loans',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'loan_code',
    openStatuses: ['active'],
  },
  success: 'El préstamo existe en estado active con sus cuotas, el cupo reservado quedó consumido y el comercio ve la venta en su cartera.',
  failure:
    'La compra queda aprobada y aceptada sin préstamo, el comercio la declina o el desembolso aborta por decisión vencida, consentimiento retirado o cupo insuficiente.',
  sources: [
    'AtlasFrontend/apps/consumer-app/docs/flujo-cliente-final.md §4.2–4.4, §9 y §10',
    'AtlasFrontend/apps/consumer-app/src/api/config.ts (EXPO_PUBLIC_ATLAS_PURCHASE_SOURCE, sandbox por omisión)',
    'AtlasFrontend/apps/consumer-app/app/(app)/(tabs)/escanear.tsx',
    'AtlasFrontend/apps/consumer-app/src/features/credit-evaluation.ts',
    'AtlasFrontend/apps/consumer-app/src/sandbox/store.tsx (sondeo de businessAcceptance)',
    'src/modules/partner-onboarding/merchant-qr.controller.ts',
    'src/modules/credit/credit.controller.ts',
    'src/modules/credit/merchant-credit.controller.ts',
    'src/modules/credit/application/credit-application.service.ts',
    'src/modules/credit/application/credit-business-acceptance.service.ts',
    'src/modules/credit/application/credit-decision-event-publisher.ts',
    'src/modules/loans/loans.controller.ts',
    'src/modules/loans/application/loan-disbursement.service.ts',
    'src/modules/loan-payment-claims/merchant-payment-claims.controller.ts',
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts (register_engine_facilities, sync_engine_consents)',
    'src/modules/runtime-jobs/optional-jobs.catalog.ts (deliver_erp_events)',
    'src/platform/events/outbound-subscriptions.ts',
    'src/database/migrations/20260811090000-create-loan-book.ts (CHECK de loans.status)',
    'AtlasERPBackend/src/modules/partner-onboarding-gateway/merchant-credit-gateway.controller.ts',
    'AtlasERPBackend/src/modules/b2b-sales-crm/controllers/bnpl.controller.ts',
    'AtlasERPFrontend/app/portal-comercio/gestion-pos/page.tsx (MerchantRequestsScreen)',
    'AtlasERPFrontend/app/portal-comercio/cartera/page.tsx',
    'AtlasERPFrontend/app/operaciones/crm/conciliacion-cobertura/page.tsx',
    'memoria atlas-flujo-pago-qr-comprobante',
    'memoria atlas-camara-emulador-y-qr',
    'memoria atlas-recorrido-signup-a-credito',
    'memoria atlas-erp-consumo-facturacion',
    '_plan-documentar-procesos-y-cableado-portal-2026-09-26/datos/procesos.json (P-08)',
  ],
  metadata: {
    purchaseDomainInApp:
      'Orden, commitment, calendario de la compra e instrucción del inicial corren en el sandbox local de la app (EXPO_PUBLIC_ATLAS_PURCHASE_SOURCE=sandbox en los tres perfiles de eas.json); sólo el QR, la decisión de crédito y la aceptación del comercio son reales.',
    disbursementCaller: 'Ninguno: POST /credit-applications/:applicationId/disbursement sólo lo llama test/e2e/loans/loan-book.spec.ts.',
  },
  stages: [
    {
      code: 'purchase_scan',
      name: 'Escanear el QR de la caja',
      description:
        'El cliente apunta al QR interno de Atlas del comercio. Lleva un token opaco: el servidor resuelve comercio, sucursal y caja; fotografiar un QR ajeno no cambia a quién se le paga.',
      module: 'partner_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      entry: true,
      steps: [
        {
          code: 'purchase.resolve_qr',
          name: 'Resolver el QR al comercio que lo emitió',
          description:
            'Devuelve expediente, sucursal, caja, nombre y rubro del comercio verificado. La app reenvía un QR rechazado cada 1,5 s mientras siga en cuadro.',
          method: 'POST',
          path: '/merchant-qr/resolve',
          roles: CUSTOMER_AND_STAFF,
          input: { token: 'string' },
          output: { partnerProfileId: 'string', branchId: 'string', posTerminalId: 'string', displayName: 'string', verified: 'true' },
          errors: ['QR_NOT_RECOGNIZED', 'QR_REVOKED', 'QR_EXPIRED'],
        },
      ],
    },
    {
      code: 'purchase_credit_request',
      name: 'Monto y solicitud de crédito',
      description:
        'El cliente fija el monto bruto; la app muestra el plan (60 % inicial, 40 % financiado en cuotas) como previsualización y pide el crédito por lo financiado, enlazado al comercio y a la caja.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      steps: [
        {
          code: 'purchase.credit_products',
          name: 'Elegir el producto que admite el importe',
          description:
            'Lista los productos activos; la app elige el que admite lo financiado o responde NO_PRODUCT_FOR_AMOUNT sin pedir nada.',
          method: 'GET',
          path: '/customers/:customerId/credit-products',
          roles: CUSTOMER_AND_STAFF,
        },
        {
          code: 'purchase.credit_application',
          name: 'Presentar la solicitud de crédito de la compra',
          description:
            'Crea la solicitud con purposeCode bnpl_purchase, partnerProfileId y posTerminalId (sólo si son ids reales). Tras confirmar la transacción consulta al Motor y devuelve la solicitud ya decidida.',
          method: 'POST',
          path: '/customers/:customerId/credit-applications',
          roles: CUSTOMER_AND_STAFF,
          idempotencyKey: true,
          resultingStates: ['submitted', 'approved', 'rejected', 'under_review'],
          input: {
            productId: 'string',
            requestedAmount: 'number',
            requestedTermMonths: 'number',
            purposeCode: 'bnpl_purchase',
            partnerProfileId: 'string?',
            posTerminalId: 'string?',
          },
          output: { applicationId: 'string', status: 'string', decisionMode: 'string | null', executionId: 'string | null' },
          events: ['credit.application.submitted'],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'purchase_engine_decision',
      name: 'Decisión del Motor',
      description:
        'Atlas llama al artefacto de crédito del Motor con las features del cliente. Una aprobación del Motor deja businessAcceptance = pending: falta la palabra del comercio. El detalle de la decisión vive en P-06.',
      module: 'decision_engine',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'purchase.engine_decide',
          name: 'Ejecutar el artefacto de crédito',
          description: 'Llamada de Atlas al Motor; la solicitud guarda la ejecución que la decidió y el préstamo la hereda.',
          system: 'DECISION_ENGINE',
          method: 'POST',
          path: '/v1/decisions/:artifactCode',
        },
        {
          code: 'purchase.decision_event',
          name: 'Avisar al ERP la banda de riesgo aprobada',
          description:
            'Una aprobación con banda real escribe credit.decision.recorded en el outbox en la misma transacción; se entrega firmado al ERP para su regla de MDR por banda.',
          kind: 'event',
          reason:
            'Evento del outbox suscrito a atlas-erp; lo entrega el job opcional deliver_erp_events, que sólo corre si ERP_EVENTS_DELIVERY_URL y su secreto están configurados.',
          events: ['credit.decision.recorded'],
        },
        {
          code: 'purchase.erp_receives_decision',
          name: 'El ERP recibe el evento de Core',
          description: 'El ERP guarda la última banda de riesgo del cliente en atlas_sales.customer_risk_tiers.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/integration/core/events',
          optional: true,
        },
      ],
    },
    {
      code: 'purchase_merchant_acceptance',
      name: 'El comercio acepta o rechaza la venta',
      description:
        'El comercio ve en «Gestión POS» las solicitudes que esperan su respuesta y sólo puede decir sí o no: no edita importe ni calendario. Aceptar reserva el cupo del cliente hasta que venza la decisión.',
      module: 'credit',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/gestion-pos',
      requiredStates: ['approved'],
      steps: [
        {
          code: 'purchase.merchant_list_erp',
          name: 'Solicitudes pendientes del comercio (ERP)',
          description: 'El ERP reenvía la consulta a Atlas sin validar el dominio: la evidencia vive en Atlas.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant-credit/:partnerId/applications',
          roles: ERP_MERCHANT_ROLES,
        },
        {
          code: 'purchase.merchant_list',
          name: 'Solicitudes pendientes del comercio (Atlas)',
          description: 'Por defecto sólo las que esperan su respuesta, y sólo las nacidas en este comercio.',
          method: 'GET',
          path: '/merchant/partners/:partnerId/credit-applications',
          roles: MERCHANT_AND_STAFF,
        },
        {
          code: 'purchase.merchant_accept_erp',
          name: 'Aceptar o rechazar (ERP)',
          description: 'Cuerpo { accepted, reasonCode?, notes? }; se reenvía tal cual a Atlas.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/merchant-credit/:partnerId/applications/:applicationId/acceptance',
          roles: ERP_MERCHANT_ROLES,
        },
        {
          code: 'purchase.merchant_accept',
          name: 'Registrar la aceptación del comercio',
          description:
            'Sólo sobre una solicitud con businessAcceptance pending; deja business_acceptance_recorded en el historial de la solicitud y, si acepta, reserva el cupo.',
          method: 'POST',
          path: '/merchant/partners/:partnerId/credit-applications/:applicationId/acceptance',
          roles: MERCHANT_AND_STAFF,
          input: { accepted: 'boolean', reasonCode: 'string?', notes: 'string?' },
        },
      ],
    },
    {
      code: 'purchase_customer_waits',
      name: 'El cliente espera la respuesta del comercio',
      description:
        'La orden queda en «esperando comercio» y el pago del inicial bloqueado; la app sondea sus solicitudes hasta leer accepted o declined.',
      module: 'credit',
      actor: 'customer',
      client: 'CONSUMER_APP',
      steps: [
        {
          code: 'purchase.poll_applications',
          name: 'Leer el estado de la aceptación',
          description: 'Sondeo periódico sin pantalla propia; una lectura fallida no cambia nada y se reintenta.',
          method: 'GET',
          path: '/customers/:customerId/credit-applications',
          roles: CUSTOMER_AND_STAFF,
          repeatable: true,
          output: { applications: '[{ applicationId, status, businessAcceptance }]' },
        },
      ],
    },
    {
      code: 'purchase_initial_payment',
      name: 'Commitment y pago del inicial',
      description:
        'Con la venta aceptada, la app confirma la compra y muestra el QR bancario del comercio para el 60 % inicial. El reporte y la verificación del pago siguen en P-09.',
      module: 'partner_onboarding',
      actor: 'customer',
      client: 'CONSUMER_APP',
      optional: true,
      steps: [
        {
          code: 'purchase.commit_local',
          name: 'Confirmar la compra y generar el calendario',
          description: 'Revalida orden, hash aceptado, decisión y reserva, y genera el calendario de la compra.',
          kind: 'manual',
          reason:
            'Lo ejecuta el sandbox local de la app (commitPurchase): AtlasBackend todavía no tiene purchase_order, purchase_commitment ni payment_schedule.',
        },
        {
          code: 'purchase.payment_qr',
          name: 'Obtener el QR bancario del comercio',
          description: 'La imagen bancaria vigente de la empresa dueña de la caja activa; es un snapshot del beneficiario.',
          method: 'POST',
          path: '/merchant-qr/payment',
          roles: CUSTOMER_AND_STAFF,
          optional: true,
          input: { partnerProfileId: 'string', posTerminalId: 'string' },
        },
      ],
    },
    {
      code: 'purchase_disbursement',
      name: 'Desembolso del préstamo',
      description:
        'Convierte la solicitud aprobada y aceptada en préstamo active con cronograma, en una transacción que revalida vigencia de la decisión, consentimientos y cupo, y consume la reserva. No hay pantalla en el portal admin ni job que lo dispare.',
      module: 'loans',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/customers/[customerId]/investigation-summary',
      roles: ['internal_operator', 'admin', 'platform_admin'],
      requiredStates: ['approved'],
      resultingStates: ['active'],
      steps: [
        {
          code: 'purchase.disburse',
          name: 'Desembolsar la solicitud aprobada',
          description:
            'Crea loans + loan_installments + loan_events (loan_disbursed) y consume la reserva. Reintentar con la misma clave devuelve el préstamo existente. Una tasa distinta a la decidida exige credit.loan_disbursement.override_rate y motivo.',
          method: 'POST',
          path: '/credit-applications/:applicationId/disbursement',
          roles: ['internal_operator', 'admin', 'platform_admin'],
          idempotencyKey: true,
          requiredStates: ['approved'],
          resultingStates: ['active'],
          errors: [
            '404 CREDIT_APPLICATION_NOT_FOUND',
            '409 CREDIT_APPLICATION_NOT_APPROVED',
            '409 CREDIT_BUSINESS_ACCEPTANCE_PENDING',
            '409 CREDIT_BUSINESS_ACCEPTANCE_DECLINED',
            '409 CREDIT_DECISION_EXPIRED',
          ],
          successStatus: [201],
        },
      ],
    },
    {
      code: 'purchase_engine_registration',
      name: 'Alta del crédito en el Motor',
      description:
        'El libro de préstamos no llama al Motor: un job registra después los créditos nuevos para que sus desenlaces se atribuyan a la versión del artefacto que los decidió.',
      module: 'loans',
      actor: 'system',
      client: 'BLOCK',
      steps: [
        {
          code: 'purchase.sync_consents',
          name: 'Replicar consentimientos al Motor',
          description: 'Réplica duradera del consentimiento; una revocación sin acusar bloquea el desembolso.',
          kind: 'job',
          job: 'sync_engine_consents',
        },
        {
          code: 'purchase.register_facility',
          name: 'Registrar el crédito desembolsado en el Motor',
          description: 'Da de alta los recién desembolsados para que la cosecha joven entre en la matriz del Motor.',
          kind: 'job',
          job: 'register_engine_facilities',
        },
      ],
    },
    {
      code: 'purchase_customer_loan',
      name: 'El cliente ve su préstamo',
      description: 'El préstamo aparece en la app con el comercio donde nació y su calendario de cuotas.',
      module: 'loans',
      actor: 'customer',
      client: 'CONSUMER_APP',
      terminal: true,
      steps: [
        {
          code: 'purchase.customer_loans',
          name: 'Préstamos del cliente',
          description: 'Lista los préstamos con el comercio de origen.',
          method: 'GET',
          path: '/customers/:customerId/loans',
          roles: CUSTOMER_AND_STAFF,
        },
        {
          code: 'purchase.loan_detail',
          name: 'Detalle del préstamo',
          description: 'Saldos, cuotas y estado del préstamo.',
          method: 'GET',
          path: '/loans/:loanId',
          roles: CUSTOMER_AND_STAFF,
        },
        {
          code: 'purchase.payment_calendar',
          name: 'Calendario de pagos',
          description: 'Qué vence y cuándo, para «qué me vence primero» en el inicio.',
          method: 'GET',
          path: '/customers/:customerId/payment-calendar',
          roles: CUSTOMER_AND_STAFF,
        },
      ],
    },
    {
      code: 'purchase_merchant_portfolio',
      name: 'El comercio ve la venta en su cartera',
      description:
        '«Mi cartera» lee de Atlas los préstamos y cobros del expediente. Hoy se queda con el primer expediente del usuario sin avisar.',
      module: 'loan_payment_claims',
      actor: 'merchant_user',
      client: 'ERP_PORTAL',
      screen: '/portal-comercio/cartera',
      terminal: true,
      steps: [
        {
          code: 'purchase.merchant_portfolio_erp',
          name: 'Cartera del comercio (ERP)',
          description: 'El ERP sólo reenvía a Atlas.',
          system: 'ERP_BACKEND',
          method: 'GET',
          path: '/merchant-credit/:partnerId/portfolio',
          roles: ERP_MERCHANT_ROLES,
        },
        {
          code: 'purchase.merchant_portfolio',
          name: 'Cartera del comercio (Atlas)',
          description: 'Préstamos y cobros del expediente, identificados por partner_profiles.',
          method: 'GET',
          path: '/merchant/partners/:partnerId/payment-claims/portfolio',
          roles: ['merchant', 'internal_operator', 'admin', 'platform_admin'],
        },
      ],
    },
    {
      code: 'purchase_erp_sale_registration',
      name: 'Registro de la venta a plazos en el ERP',
      description:
        'Libro propio del ERP (atlas_sales) para el MDR y la cobertura. No se alimenta del desembolso: lo registra a mano un operador del ERP o el comercio, con coreLoanRef opcional para enlazarlo al préstamo de Atlas.',
      module: 'b2b_sales_crm',
      actor: 'platform_user',
      client: 'ERP_PORTAL',
      screen: '/operaciones/crm/conciliacion-cobertura',
      optional: true,
      roles: ['ERP:MERCHANT_ADMIN', 'ERP:OPERATIONS', 'ERP:ADMIN'],
      steps: [
        {
          code: 'purchase.erp_register_sale',
          name: 'Registrar la compra BNPL',
          description:
            'Entrada 60 %, financiado y cuotas; la banda de riesgo la resuelve el ERP desde credit.decision.recorded. Sin coreLoanRef los avisos de pago de esas cuotas quedan como excepción de integración.',
          system: 'ERP_BACKEND',
          method: 'POST',
          path: '/b2b/bnpl/purchases',
          roles: ['MERCHANT_ADMIN', 'OPERATIONS', 'ADMIN'],
          optional: true,
        },
      ],
    },
  ],
  transitions: [
    {
      code: 'purchase.entry',
      from: null,
      to: 'purchase.resolve_qr',
      condition: 'always',
      description: 'El cliente escanea el QR de la caja.',
      isDefault: true,
    },
    {
      code: 'purchase.qr_to_products',
      from: 'purchase.resolve_qr',
      to: 'purchase.credit_products',
      condition: 'on_success',
      description: 'Comercio verificado: se fija el monto.',
      isDefault: true,
    },
    {
      code: 'purchase.qr_rejected',
      from: 'purchase.resolve_qr',
      to: null,
      condition: 'on_error',
      description: 'QR no reconocido, revocado o vencido: no se abre sesión de compra.',
    },
    {
      code: 'purchase.products_to_application',
      from: 'purchase.credit_products',
      to: 'purchase.credit_application',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'purchase.application_to_engine',
      from: 'purchase.credit_application',
      to: 'purchase.engine_decide',
      condition: 'on_success',
      description: 'Solicitud en submitted: se consulta al Motor.',
      isDefault: true,
    },
    {
      code: 'purchase.engine_to_event',
      from: 'purchase.engine_decide',
      to: 'purchase.decision_event',
      condition: 'conditional',
      expression: { status: 'approved', riskBand: 'present' },
      description: 'Aprobación con banda real.',
    },
    { code: 'purchase.event_to_erp', from: 'purchase.decision_event', to: 'purchase.erp_receives_decision', condition: 'on_success' },
    {
      code: 'purchase.engine_to_merchant',
      from: 'purchase.engine_decide',
      to: 'purchase.merchant_list_erp',
      condition: 'conditional',
      expression: { status: 'approved', businessAcceptance: 'pending' },
      isDefault: true,
    },
    {
      code: 'purchase.engine_rejected',
      from: 'purchase.engine_decide',
      to: null,
      condition: 'conditional',
      expression: { status: 'rejected' },
      description: 'Crédito rechazado: no hay venta.',
    },
    { code: 'purchase.merchant_list_proxy', from: 'purchase.merchant_list_erp', to: 'purchase.merchant_list', condition: 'always' },
    {
      code: 'purchase.merchant_to_accept',
      from: 'purchase.merchant_list',
      to: 'purchase.merchant_accept_erp',
      condition: 'on_success',
      isDefault: true,
    },
    { code: 'purchase.accept_proxy', from: 'purchase.merchant_accept_erp', to: 'purchase.merchant_accept', condition: 'always' },
    {
      code: 'purchase.accept_to_poll',
      from: 'purchase.merchant_accept',
      to: 'purchase.poll_applications',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'purchase.poll_to_commit',
      from: 'purchase.poll_applications',
      to: 'purchase.commit_local',
      condition: 'conditional',
      expression: { businessAcceptance: 'accepted' },
      isDefault: true,
    },
    {
      code: 'purchase.poll_declined',
      from: 'purchase.poll_applications',
      to: null,
      condition: 'conditional',
      expression: { businessAcceptance: 'declined' },
      description: 'El comercio rechazó: la orden se marca rechazada y no se cobra nada.',
    },
    { code: 'purchase.commit_to_qr', from: 'purchase.commit_local', to: 'purchase.payment_qr', condition: 'on_success', isDefault: true },
    {
      code: 'purchase.qr_to_disburse',
      from: 'purchase.payment_qr',
      to: 'purchase.disburse',
      condition: 'conditional',
      expression: { businessAcceptance: 'accepted', triggeredBy: 'internal_operator' },
      description: 'Nadie dispara hoy el desembolso: ni la app, ni un job, ni una pantalla.',
      isDefault: true,
    },
    {
      code: 'purchase.disburse_to_register',
      from: 'purchase.disburse',
      to: 'purchase.register_facility',
      condition: 'on_success',
      isDefault: true,
    },
    {
      code: 'purchase.register_to_customer',
      from: 'purchase.register_facility',
      to: 'purchase.customer_loans',
      condition: 'always',
      isDefault: true,
    },
    { code: 'purchase.customer_detail', from: 'purchase.customer_loans', to: 'purchase.loan_detail', condition: 'on_success' },
    { code: 'purchase.customer_calendar', from: 'purchase.loan_detail', to: 'purchase.payment_calendar', condition: 'on_success' },
    { code: 'purchase.disburse_to_portfolio', from: 'purchase.disburse', to: 'purchase.merchant_portfolio_erp', condition: 'on_success' },
    { code: 'purchase.portfolio_proxy', from: 'purchase.merchant_portfolio_erp', to: 'purchase.merchant_portfolio', condition: 'always' },
    {
      code: 'purchase.disburse_to_erp_sale',
      from: 'purchase.disburse',
      to: 'purchase.erp_register_sale',
      condition: 'conditional',
      expression: { registeredBy: 'erp_operator_or_merchant' },
      description: 'Registro manual en el libro del ERP, con coreLoanRef si se conoce el préstamo.',
    },
    { code: 'purchase.exit', from: 'purchase.payment_calendar', to: null, condition: 'always', isDefault: true },
  ],
  dependencies: [
    {
      step: 'purchase.credit_application',
      dependsOn: 'purchase.resolve_qr',
      type: 'requires_data',
      description: 'partnerProfileId y posTerminalId salen del QR resuelto.',
    },
    {
      step: 'purchase.merchant_accept',
      dependsOn: 'purchase.engine_decide',
      type: 'requires_completion',
      description: 'Sólo se acepta una solicitud aprobada con businessAcceptance pending.',
    },
    {
      step: 'purchase.disburse',
      dependsOn: 'purchase.merchant_accept',
      type: 'requires_completion',
      description: 'pending o declined bloquean el desembolso; aceptar reservó el cupo que el desembolso consume.',
    },
    {
      step: 'purchase.disburse',
      dependsOn: 'purchase.sync_consents',
      type: 'soft',
      description: 'El desembolso revalida que el cliente no retiró un consentimiento del que dependía la decisión.',
    },
    {
      step: 'purchase.register_facility',
      dependsOn: 'purchase.disburse',
      type: 'requires_data',
      description: 'Necesita el préstamo con decisionExecutionId.',
    },
    {
      step: 'purchase.merchant_portfolio',
      dependsOn: 'purchase.disburse',
      type: 'requires_data',
      description: 'La cartera lee credit.loans.',
    },
  ],
};
