/**
 * @file Proceso declarado en código: Trabajos programados (20) y sus corridas.
 * @business Hay promesas de negocio que sólo se cumplen si algo corre solo: expirar sesiones, aplicar la retención de datos personales, marcar la mora, cerrar el circuito del KYB o del extracto bancario; este proceso las ejecuta con cadencia y deja rastro de cada corrida.
 * @system fixture P-33 que `syncWorkflowCatalog` vuelca a `workflow_*`; `RuntimeJobsSchedulerService` (setInterval + lock Redis) sobre `scheduled-jobs.catalog.ts`, disparo manual en `runtime-jobs.controller.ts` y corridas en `system_job_runs`.
 */
import type { WorkflowDefinitionFixture } from '../workflow-definition.types.js';

/** Roles de clase de `RuntimeJobsController` y `RuntimeDecisionJobsController`. */
const JOBS_ROLES = ['admin', 'platform_admin', 'system'];
/** `INTERNAL_PORTAL_ROLES` de `internal-portal.controller.ts`. */
const PORTAL = [
  'internal_operator',
  'risk_analyst',
  'compliance_analyst',
  'admin',
  'platform_admin',
  'system_admin',
  'qa_engineer',
  'devops',
  'readonly_auditor',
];

export const RUNTIME_JOBS: WorkflowDefinitionFixture = {
  processId: 'P-33',
  code: 'runtime_jobs',
  version: 'v1',
  name: 'Trabajos programados (20) y sus corridas',
  description:
    'Los veinte trabajos de fondo que el planificador corre solo, cada uno con su intervalo, con un único líder por lock de Redis, guarda contra solapamiento y registro de cada corrida en system_job_runs; el administrador puede dispararlos a mano (por defecto en simulación) y consultar las corridas.',
  processType: 'system_job',
  ownerDomain: 'platform',
  ownerRole: 'SYSTEMS_ADMIN',
  priority: 'P2',
  systems: ['ATLAS_BACKEND'],
  narrative: {
    whyExists:
      'La auditoría del 2026-07-30 encontró que los jobs sólo existían como rutas HTTP que nadie llamaba: el outbox no se despachaba, las sesiones no expiraban y la retención de datos personales nunca se aplicaba. La mora, el SLA de soporte y el KYB tuvieron el mismo defecto. El planificador hace que corran solos.',
    whoStartsAndCloses:
      'Lo inicia el planificador del contenedor worker (APP_ROLE=worker exige RUNTIME_JOBS_SCHEDULER_ENABLED=true) con el actor runtime-jobs-scheduler; un administrador puede dispararlo a mano desde «Trabajos de fondo». Lo cierra el propio job al registrar su corrida como completed o failed.',
    startAndEnd:
      'Cada tick empieza al vencer el intervalo del job, si esa instancia gana el lock de liderazgo y la tanda anterior terminó; termina con una fila en system_job_runs en completed con su resultado, o en failed con el error. El disparo manual llega en simulación salvo que se pida lo contrario.',
    whenItFails:
      'Una corrida que falla queda en failed con su mensaje y se reintenta en el siguiente tick; una tanda más lenta que RUNTIME_JOBS_TICK_TIMEOUT_MS se marca ATASCADA en métricas y log y no se repite hasta terminar. Sin Redis en producción el planificador no corre salvo RUNTIME_JOBS_ALLOW_WITHOUT_LOCK.',
    healthIndicator:
      'Última corrida completed por job dentro de su intervalo, corridas en failed y jobs atascados en las métricas del planificador; lo consulta el administrador en «Corridas de jobs» y la preparación de salida cuenta las corridas registradas.',
  },
  instanceEntity: {
    system: 'ATLAS_BACKEND',
    schema: 'platform_ops',
    table: 'system_job_runs',
    idColumn: '_id',
    statusColumn: 'status',
    labelColumn: 'job_code',
    openStatuses: ['running'],
  },
  success: 'Cada job corre con su cadencia y su corrida queda registrada como completed.',
  failure: 'Un job no corre, se atasca o falla repetidamente y la promesa de negocio que sostiene deja de cumplirse sin aviso.',
  sources: [
    'src/modules/runtime-jobs/scheduled-jobs.catalog.ts',
    'src/modules/runtime-jobs/runtime-jobs-scheduler.service.ts',
    'src/modules/runtime-jobs/job-run-recorder.service.ts',
    'src/modules/runtime-jobs/runtime-jobs.controller.ts',
    'src/modules/runtime-jobs/runtime-decision-jobs.controller.ts',
    'src/modules/internal-portal/internal-portal.controller.ts',
    'src/config/env-cross-checks.ts',
    '_plan-documentar-procesos-y-cableado-portal-2026-09-26/datos/procesos.json (P-33)',
  ],
  stages: [
    {
      code: 'jobs_scheduler_tick',
      name: 'Tick del planificador',
      description:
        'El planificador del worker corre cada job de scheduled-jobs.catalog.ts con su intervalo; los opcionales (optional-jobs.catalog.ts) sólo con su bandera.',
      module: 'runtime_jobs',
      actor: 'system',
      client: 'BLOCK',
      entry: true,
      resultingStates: ['running', 'completed', 'failed'],
      steps: [
        {
          code: 'jobs.process_outbox',
          name: 'Drenar el outbox',
          description: 'Eventos fuera del registro (ver P-32).',
          kind: 'job',
          job: 'process_outbox',
        },
        {
          code: 'jobs.process_events',
          name: 'Despachar eventos registrados',
          description: 'Relay del outbox con inbox (ver P-32).',
          kind: 'job',
          job: 'process_events',
        },
        {
          code: 'jobs.expire_stale_sessions',
          name: 'Expirar sesiones inactivas',
          description: 'Cierra las sesiones por encima de RUNTIME_JOBS_SESSION_MAX_IDLE_MINUTES.',
          kind: 'job',
          job: 'expire_stale_sessions',
        },
        {
          code: 'jobs.apply_retention_policies',
          name: 'Aplicar la retención de datos',
          description: 'Aplica las políticas de retención de datos personales.',
          kind: 'job',
          job: 'apply_retention_policies',
        },
        {
          code: 'jobs.retry_stuck_notifications',
          name: 'Reintentar notificaciones atascadas',
          description: 'Reintenta avisos pendientes más viejos que el umbral.',
          kind: 'job',
          job: 'retry_stuck_notifications',
        },
        {
          code: 'jobs.purge_idempotency_keys',
          name: 'Purgar claves de idempotencia',
          description: 'Borra claves pasado su período de retención.',
          kind: 'job',
          job: 'purge_idempotency_keys',
        },
        {
          code: 'jobs.purge_processed_outbox',
          name: 'Purgar el outbox procesado',
          description: 'Borra filas processed pasada su retención (ver P-32).',
          kind: 'job',
          job: 'purge_processed_outbox',
        },
        {
          code: 'jobs.mark_abandoned_onboardings',
          name: 'Marcar altas abandonadas',
          description: 'Cierra los flujos de alta sin avance; sin él no existía la tasa de abandono.',
          kind: 'job',
          job: 'mark_abandoned_onboardings',
        },
        {
          code: 'jobs.recalculate_data_quality',
          name: 'Recalcular la calidad de datos',
          description: 'Evalúa las reglas de calidad y abre incidencias (ver P-37).',
          kind: 'job',
          job: 'recalculate_data_quality',
        },
        {
          code: 'jobs.sweep_support_sla',
          name: 'Barrer el SLA de soporte',
          description: 'Primero avisos de plazo inminente, luego incumplimientos.',
          kind: 'job',
          job: 'sweep_support_sla',
        },
        {
          code: 'jobs.sweep_loan_delinquency',
          name: 'Barrer la mora',
          description: 'Recalcula días de atraso, tramo y cuotas vencidas, y encola desenlaces.',
          kind: 'job',
          job: 'sweep_loan_delinquency',
        },
        {
          code: 'jobs.dispatch_loan_outcomes',
          name: 'Entregar desenlaces al Motor',
          description: 'Entrega los desenlaces encolados por el barrido de mora.',
          kind: 'job',
          job: 'dispatch_loan_outcomes',
        },
        {
          code: 'jobs.register_engine_facilities',
          name: 'Registrar créditos en el Motor',
          description: 'Alta de cada crédito en el Motor para poder atribuirle un desenlace.',
          kind: 'job',
          job: 'register_engine_facilities',
        },
        {
          code: 'jobs.sync_engine_consents',
          name: 'Replicar consentimientos al Motor',
          description: 'Una revocación sin acusar bloquea el desembolso.',
          kind: 'job',
          job: 'sync_engine_consents',
        },
        {
          code: 'jobs.sweep_debt_ratings',
          name: 'Recalificar la cartera',
          description: 'Categoría de riesgo y previsión derivadas de los días de atraso.',
          kind: 'job',
          job: 'sweep_debt_ratings',
        },
        {
          code: 'jobs.sync_partner_kyb_reviews',
          name: 'Traer las decisiones de KYB',
          description: 'Vuelta del circuito de verificación de comercios desde el Motor (P-16).',
          kind: 'job',
          job: 'sync_partner_kyb_reviews',
        },
        {
          code: 'jobs.refresh_credit_lines',
          name: 'Refrescar líneas de crédito',
          description: 'Pide línea a quien nunca la tuvo y refresca las demasiado viejas.',
          kind: 'job',
          job: 'refresh_credit_lines',
        },
        {
          code: 'jobs.process_bank_statement_reviews',
          name: 'Revisar extractos bancarios',
          description: 'Cumple el compromiso de 24 h del extracto; corre cada 15 minutos.',
          kind: 'job',
          job: 'process_bank_statement_reviews',
        },
        {
          code: 'jobs.reclaim_stuck_events',
          name: 'Rescatar eventos atascados',
          description: 'Devuelve a pending lo que quedó en processing (ver P-32).',
          kind: 'job',
          job: 'reclaim_stuck_events',
        },
        {
          code: 'jobs.run_notification_campaigns',
          name: 'Correr campañas de notificación',
          description: 'Tick de las campañas masivas programadas.',
          kind: 'job',
          job: 'run_notification_campaigns',
        },
      ],
    },
    {
      code: 'jobs_manual_trigger',
      name: 'Disparo manual',
      description:
        'El administrador dispara un job desde «Trabajos de fondo»; los DTO llegan con dryRun en true por defecto para proteger el disparo manual.',
      module: 'runtime_jobs',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/operations/runtime-jobs',
      optional: true,
      roles: JOBS_ROLES,
      steps: [
        {
          code: 'jobs.trigger_process_outbox',
          name: 'Disparar el drenado del outbox',
          description: 'Corre process_outbox a mano.',
          method: 'POST',
          path: '/operations/jobs/process-outbox',
          roles: JOBS_ROLES,
        },
        {
          code: 'jobs.trigger_process_events',
          name: 'Disparar el despacho de eventos',
          description: 'Corre process_events a mano.',
          method: 'POST',
          path: '/operations/jobs/process-events',
          roles: JOBS_ROLES,
          optional: true,
        },
        {
          code: 'jobs.trigger_expire_sessions',
          name: 'Disparar la expiración de sesiones',
          description: 'Corre expire_stale_sessions a mano.',
          method: 'POST',
          path: '/operations/jobs/expire-stale-sessions',
          roles: JOBS_ROLES,
          optional: true,
        },
        {
          code: 'jobs.trigger_retention',
          name: 'Disparar la retención',
          description: 'Corre apply_retention_policies a mano.',
          method: 'POST',
          path: '/operations/jobs/apply-retention-policies',
          roles: JOBS_ROLES,
          optional: true,
        },
        {
          code: 'jobs.trigger_data_quality',
          name: 'Disparar la calidad de datos',
          description: 'Corre recalculate_data_quality a mano.',
          method: 'POST',
          path: '/operations/jobs/recalculate-data-quality',
          roles: JOBS_ROLES,
          optional: true,
        },
        {
          code: 'jobs.trigger_reclaim_events',
          name: 'Disparar el rescate de eventos',
          description: 'Corre reclaim_stuck_events a mano.',
          method: 'POST',
          path: '/operations/jobs/reclaim-stuck-events',
          roles: JOBS_ROLES,
          optional: true,
        },
        {
          code: 'jobs.trigger_loan_outcomes',
          name: 'Disparar la entrega de desenlaces',
          description: 'Corre dispatch_loan_outcomes a mano.',
          method: 'POST',
          path: '/operations/jobs/dispatch-loan-outcomes',
          roles: JOBS_ROLES,
          optional: true,
        },
        {
          code: 'jobs.trigger_debt_ratings',
          name: 'Disparar la recalificación',
          description: 'Corre sweep_debt_ratings a mano.',
          method: 'POST',
          path: '/operations/jobs/sweep-debt-ratings',
          roles: JOBS_ROLES,
          optional: true,
        },
      ],
    },
    {
      code: 'jobs_run_history',
      name: 'Corridas registradas',
      description: 'El administrador consulta las corridas de system_job_runs del tenant de su token.',
      module: 'internal_portal',
      actor: 'internal_user',
      client: 'ADMIN_PORTAL',
      screen: '/internal/jobs',
      terminal: true,
      roles: PORTAL,
      steps: [
        {
          code: 'jobs.list_runs',
          name: 'Listar corridas',
          description: 'Corridas por job y estado, acotadas al tenant.',
          method: 'GET',
          path: '/internal/jobs',
          roles: PORTAL,
        },
        {
          code: 'jobs.run_detail',
          name: 'Ver una corrida',
          description: 'Entrada, resultado, error y quién la disparó.',
          method: 'GET',
          path: '/internal/jobs/:jobRunId',
          roles: PORTAL,
        },
      ],
    },
  ],
  metadata: {
    gaps: [
      'El inventario dice queued/running/succeeded/failed; job-run-recorder escribe running/completed/failed.',
      'Ningún job declara el proceso de negocio que cierra (p. ej. sync_partner_kyb_reviews → P-16).',
      'Los jobs opcionales (deliver_pending_notifications, retry_deferred_underwriting, consume_systems_stress_runs, deliver_erp_events, consume_qa_journey_runs) viven en optional-jobs.catalog.ts, que el gate de pasos no lee.',
      'FND-CORE-01 (RUNTIME_JOBS_STRESS_CONSUMER_ENABLED=false encendía el consumidor) ya está corregido en esta rama con booleanEnvSchema.',
    ],
  },
};
