import { QueryInterface, Transaction } from 'sequelize';

type SeedContext = { context: QueryInterface };
type SeedRow = Record<string, unknown>;
type SeedTable = { tableName: string; rows: SeedRow[] };

const CREATED_AT = new Date('2026-01-01T00:00:00.000Z');
const jsonb = (value: unknown): string => JSON.stringify(value);

const RETENTION_ROWS: SeedRow[] = [
  {
    _id: 101,
    policy_code: 'pii-core-1095d',
    applies_to: 'customer_core_pii',
    retention_days: 1095,
    post_retention_action: 'anonymize',
    legal_basis: 'explicit_consent_and_contract_preparation',
    description: 'PII principal de cliente para onboarding, soporte y decisiones crediticias del MVP.',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 102,
    policy_code: 'risk-features-730d',
    applies_to: 'risk_features_and_score_inputs',
    retention_days: 730,
    post_retention_action: 'aggregate_then_delete',
    legal_basis: 'risk_management_and_model_monitoring',
    description: 'Features, observaciones y señales usadas para scoring y auditoría de modelo.',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 103,
    policy_code: 'audit-logs-1825d',
    applies_to: 'audit_and_security_logs',
    retention_days: 1825,
    post_retention_action: 'archive',
    legal_basis: 'security_and_legal_defense',
    description: 'Logs de auditoría, acciones internas y eventos de seguridad.',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 104,
    policy_code: 'external-provider-365d',
    applies_to: 'external_provider_payloads',
    retention_days: 365,
    post_retention_action: 'redact_payload_keep_hash',
    legal_basis: 'explicit_consent_and_provider_audit',
    description: 'Payloads normalizados o redactados de SEGIP, buró, QR, bancos y mocks.',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 105,
    policy_code: 'notification-540d',
    applies_to: 'notifications_and_delivery_evidence',
    retention_days: 540,
    post_retention_action: 'delete_body_keep_delivery_metadata',
    legal_basis: 'customer_service_and_operational_evidence',
    description: 'Mensajes enviados, entregas, preferencias y evidencias de contacto.',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
];

const PURPOSE_ROWS: SeedRow[] = [
  {
    _id: 101,
    purpose_code: 'customer_onboarding',
    purpose_name: 'Onboarding del cliente',
    legal_basis: 'explicit_consent',
    description: 'Crear y completar el alta del cliente para evaluar elegibilidad BNPL.',
    requires_explicit_consent: true,
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 102,
    purpose_code: 'credit_scoring',
    purpose_name: 'Scoring crediticio BNPL',
    legal_basis: 'explicit_consent',
    description: 'Calcular score, risk band, razón de decisión y recomendación operacional.',
    requires_explicit_consent: true,
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 103,
    purpose_code: 'kyc_identity_verification',
    purpose_name: 'Verificación de identidad KYC',
    legal_basis: 'explicit_consent',
    description: 'Validar identidad/documento con datos propios y proveedores autorizados.',
    requires_explicit_consent: true,
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 104,
    purpose_code: 'external_bureau_query',
    purpose_name: 'Consulta buró/proveedor externo',
    legal_basis: 'explicit_consent',
    description: 'Consultar burós/proveedores solamente cuando la política lo permita.',
    requires_explicit_consent: true,
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 105,
    purpose_code: 'customer_notifications',
    purpose_name: 'Notificaciones al cliente',
    legal_basis: 'explicit_consent_or_service_notice',
    description: 'Enviar OTP, recordatorios, estados de solicitud, cobranza y mensajes operativos.',
    requires_explicit_consent: true,
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
];

const CLASSIFICATION_ROWS: SeedRow[] = [
  {
    _id: 101,
    classification_code: 'PUBLIC_BUSINESS',
    classification_name: 'Público de negocio',
    sensitivity_level: 'LOW',
    allowed_storage_modes_json: jsonb(['plain']),
    default_storage_mode: 'plain',
    default_retention_policy_id: 103,
    encryption_required: false,
    hashing_required: false,
    raw_storage_allowed: true,
    description: 'Catálogos públicos y metadatos de bajo riesgo.',
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 102,
    classification_code: 'INTERNAL_OPERATIONAL',
    classification_name: 'Interno operacional',
    sensitivity_level: 'MEDIUM',
    allowed_storage_modes_json: jsonb(['plain', 'redacted']),
    default_storage_mode: 'plain',
    default_retention_policy_id: 103,
    encryption_required: false,
    hashing_required: false,
    raw_storage_allowed: true,
    description: 'Datos internos del portal, auditoría y QA sin PII directa.',
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 103,
    classification_code: 'PII_HASHED',
    classification_name: 'PII hash irreversible',
    sensitivity_level: 'HIGH',
    allowed_storage_modes_json: jsonb(['hash']),
    default_storage_mode: 'hash',
    default_retention_policy_id: 101,
    encryption_required: false,
    hashing_required: true,
    raw_storage_allowed: false,
    description: 'Documento, teléfono, correo o device fingerprint guardados como hash.',
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 104,
    classification_code: 'PII_ENCRYPTED',
    classification_name: 'PII cifrada',
    sensitivity_level: 'HIGH',
    allowed_storage_modes_json: jsonb(['encrypted', 'redacted']),
    default_storage_mode: 'encrypted',
    default_retention_policy_id: 101,
    encryption_required: true,
    hashing_required: false,
    raw_storage_allowed: false,
    description: 'PII recuperable solo con cifrado por necesidad operativa.',
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 105,
    classification_code: 'RISK_SENSITIVE',
    classification_name: 'Riesgo y scoring sensible',
    sensitivity_level: 'HIGH',
    allowed_storage_modes_json: jsonb(['plain', 'redacted', 'aggregate']),
    default_storage_mode: 'redacted',
    default_retention_policy_id: 102,
    encryption_required: false,
    hashing_required: false,
    raw_storage_allowed: false,
    description: 'Features, scores, reglas, razones y señales de fraude.',
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 106,
    classification_code: 'EXTERNAL_PROVIDER_PAYLOAD',
    classification_name: 'Payload proveedor externo',
    sensitivity_level: 'CRITICAL',
    allowed_storage_modes_json: jsonb(['redacted', 'encrypted', 'hash']),
    default_storage_mode: 'redacted',
    default_retention_policy_id: 104,
    encryption_required: true,
    hashing_required: true,
    raw_storage_allowed: false,
    description: 'Respuestas y evidencias de proveedores externos, preferentemente redactadas.',
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
];

const CATALOGS: SeedRow[] = [
  {
    _id: 101,
    catalog_code: 'city_zones_scz',
    catalog_name: 'Zonas Santa Cruz de la Sierra',
    domain: 'geography',
    description: 'Zonas urbanas para formularios, análisis de riesgo y operaciones.',
    owner_team: 'risk_operations',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 102,
    catalog_code: 'occupation_categories_bo',
    catalog_name: 'Categorías ocupacionales Bolivia',
    domain: 'employment',
    description: 'Segmentación laboral para perfilamiento inicial y features.',
    owner_team: 'risk',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 103,
    catalog_code: 'income_bands_bob',
    catalog_name: 'Bandas de ingreso mensual BOB',
    domain: 'income',
    description: 'Bandas no exactas para reducir sensibilidad y facilitar scorecard.',
    owner_team: 'risk',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 104,
    catalog_code: 'document_types_bo',
    catalog_name: 'Tipos de documento Bolivia',
    domain: 'kyc',
    description: 'Documentos aceptados para identidad/KYC.',
    owner_team: 'compliance',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 105,
    catalog_code: 'risk_reason_codes',
    catalog_name: 'Reason codes de riesgo',
    domain: 'risk',
    description: 'Razones explicables para score, revisión manual y rechazo.',
    owner_team: 'risk',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 106,
    catalog_code: 'payment_channels_bo',
    catalog_name: 'Canales de pago Bolivia',
    domain: 'payments',
    description: 'Canales de pago esperados: QR BCB, transferencia, Tigo Money y efectivo comercio.',
    owner_team: 'operations',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 107,
    catalog_code: 'merchant_categories',
    catalog_name: 'Categorías de comercio',
    domain: 'merchant',
    description: 'Categorías comerciales para BNPL y análisis de cohortes.',
    owner_team: 'merchant_ops',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
  {
    _id: 108,
    catalog_code: 'onboarding_steps',
    catalog_name: 'Pasos de onboarding',
    domain: 'onboarding',
    description: 'Pasos requeridos para validar flujo de registro y pruebas frontend.',
    owner_team: 'product',
    is_active: true,
    _created_at: CREATED_AT,
    _updated_at: CREATED_AT,
  },
];

const CATALOG_VERSIONS: SeedRow[] = CATALOGS.map((catalog) => ({
  _id: catalog._id,
  catalog_id: catalog._id,
  version_code: 'v1-seed',
  status: 'published',
  valid_from: '2026-01-01',
  valid_until: null,
  created_by_type: 'seed',
  created_by_platform_user_id: 1,
  approved_by_type: 'seed',
  approved_by_platform_user_id: 1,
  approved_at: CREATED_AT,
  notes: 'Versión semilla para arrancar portal administrativo y formularios.',
  _created_at: CREATED_AT,
}));

const CONTEXT_ITEMS: SeedRow[] = [
  [1001, 101, 'scz_centro', 'Centro', 'zone', { riskSegment: 'urban_core', displayOrder: 1 }],
  [1002, 101, 'scz_norte', 'Norte', 'zone', { riskSegment: 'urban_growth', displayOrder: 2 }],
  [1003, 101, 'scz_sud', 'Sur / Palmasola', 'zone', { riskSegment: 'urban_south', displayOrder: 3 }],
  [1004, 101, 'scz_plan_3000', 'Plan 3000 / Ciudadela Andrés Ibáñez', 'zone', { riskSegment: 'high_density', displayOrder: 4 }],
  [1005, 101, 'scz_equipetrol_urubo', 'Equipetrol / Urubó', 'zone', { riskSegment: 'affluent', displayOrder: 5 }],
  [1011, 102, 'employee_private', 'Empleado dependiente privado', 'occupation', { incomeStability: 'medium_high' }],
  [1012, 102, 'employee_public', 'Empleado público', 'occupation', { incomeStability: 'high' }],
  [1013, 102, 'independent_worker', 'Trabajador independiente', 'occupation', { incomeStability: 'variable' }],
  [1014, 102, 'student', 'Estudiante', 'occupation', { incomeStability: 'support_required' }],
  [1015, 102, 'retail_transport', 'Comercio minorista / transporte', 'occupation', { incomeStability: 'cashflow_based' }],
  [1021, 103, 'income_0_2000', '0 a 2.000 Bs', 'income_band', { min: 0, max: 2000 }],
  [1022, 103, 'income_2001_5000', '2.001 a 5.000 Bs', 'income_band', { min: 2001, max: 5000 }],
  [1023, 103, 'income_5001_10000', '5.001 a 10.000 Bs', 'income_band', { min: 5001, max: 10000 }],
  [1024, 103, 'income_10001_plus', 'Más de 10.000 Bs', 'income_band', { min: 10001, max: null }],
  [1031, 104, 'ci_bo', 'Cédula de identidad Bolivia', 'document_type', { requiresComplement: true }],
  [1032, 104, 'passport', 'Pasaporte', 'document_type', { foreignAllowed: true }],
  [1033, 104, 'nit', 'NIT', 'document_type', { businessUse: true }],
  [1041, 105, 'LOW_DEVICE_RISK', 'Bajo riesgo de dispositivo', 'reason_code', { polarity: 'positive' }],
  [1042, 105, 'HIGH_DEVICE_REUSE', 'Dispositivo usado en múltiples clientes', 'reason_code', { polarity: 'negative' }],
  [1043, 105, 'BUREAU_HIT_NEGATIVE', 'Historial negativo en buró', 'reason_code', { polarity: 'negative' }],
  [1044, 105, 'MISSING_REQUIRED_CONSENT', 'Consentimiento requerido faltante', 'reason_code', { polarity: 'blocker' }],
  [1045, 105, 'GOOD_CONTACTABILITY', 'Buena contactabilidad', 'reason_code', { polarity: 'positive' }],
  [1046, 105, 'GPS_DECLARED_ADDRESS_MISMATCH', 'GPS no coincide con dirección declarada', 'reason_code', { polarity: 'negative' }],
  [1051, 106, 'qr_bcb', 'QR BCB', 'payment_channel', { online: true, verification: 'provider_or_manual' }],
  [1052, 106, 'bank_transfer', 'Transferencia bancaria', 'payment_channel', { online: true, verification: 'bank_statement' }],
  [1053, 106, 'tigo_money', 'Tigo Money', 'payment_channel', { online: true, verification: 'provider_or_receipt' }],
  [1054, 106, 'cash_merchant', 'Efectivo al comercio', 'payment_channel', { online: false, verification: 'merchant_receipt' }],
  [1061, 107, 'electronics', 'Electrónica', 'merchant_category', { averageTicketRisk: 'medium_high' }],
  [1062, 107, 'home_appliances', 'Electrodomésticos', 'merchant_category', { averageTicketRisk: 'medium' }],
  [1063, 107, 'clothing', 'Ropa y calzados', 'merchant_category', { averageTicketRisk: 'low_medium' }],
  [1064, 107, 'mobile_phones', 'Celulares', 'merchant_category', { averageTicketRisk: 'high_fraud_sensitive' }],
  [1071, 108, 'phone_verification', 'Verificación de teléfono', 'onboarding_step', { order: 1, required: true }],
  [1072, 108, 'identity_document', 'Documento de identidad', 'onboarding_step', { order: 2, required: true }],
  [1073, 108, 'consents', 'Consentimientos', 'onboarding_step', { order: 3, required: true }],
  [1074, 108, 'device_signals', 'Señales de dispositivo', 'onboarding_step', { order: 4, required: true }],
  [1075, 108, 'risk_scoring', 'Evaluación de riesgo', 'onboarding_step', { order: 5, required: true }],
].map(([id, versionId, code, name, type, attrs]) => ({
  _id: id,
  catalog_version_id: versionId,
  item_code: code,
  item_name: name,
  item_type: type,
  attributes_json: jsonb(attrs),
  source_id: 101,
  confidence_score: '95.00',
  is_active: true,
  _created_at: CREATED_AT,
  _updated_at: CREATED_AT,
}));

const DEFINITIONS: SeedTable[] = [
  {
    tableName: 'observation_definitions',
    rows: [
      [
        101,
        'device_fingerprint_hash',
        'Hash de huella de dispositivo',
        'string',
        'device',
        'onboarding',
        'MVP',
        'PII_HASHED',
        'fraud',
        true,
        true,
        true,
      ],
      [
        102,
        'sim_count',
        'Cantidad de SIM observadas',
        'number',
        'device',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        'fraud',
        true,
        true,
        true,
      ],
      [
        103,
        'gps_distance_from_declared_address_m',
        'Distancia GPS vs dirección declarada',
        'number',
        'location',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        'consistency',
        true,
        true,
        true,
      ],
      [
        104,
        'bureau_days_past_due_max_12m',
        'Máximo atraso buró 12 meses',
        'number',
        'bureau',
        'scoring',
        'MVP',
        'EXTERNAL_PROVIDER_PAYLOAD',
        'credit',
        true,
        true,
        false,
      ],
      [
        105,
        'contactability_score_raw',
        'Score crudo de contactabilidad',
        'number',
        'communication',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        'contactability',
        true,
        true,
        true,
      ],
      [
        106,
        'on_device_contacts_score',
        'Puntaje on-device sin guardar agenda',
        'number',
        'on_device',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        'fraud',
        true,
        true,
        true,
      ],
      [
        107,
        'kyc_document_match',
        'Coincidencia documento KYC',
        'boolean',
        'identity',
        'kyc',
        'MVP',
        'PII_HASHED',
        'identity',
        true,
        true,
        true,
      ],
      [
        108,
        'qr_payment_verified',
        'Pago inicial QR verificado',
        'boolean',
        'payments',
        'purchase',
        'MVP',
        'RISK_SENSITIVE',
        'payment',
        false,
        true,
        false,
      ],
    ].map(([id, code, name, dataType, sourceGroup, stage, phase, classification, dimension, consent, credit, fraud]) => ({
      _id: id,
      observation_code: code,
      observation_name: name,
      data_type: dataType,
      source_group: sourceGroup,
      expected_availability_stage: stage,
      build_phase: phase,
      data_classification_code: classification,
      risk_dimension: dimension,
      requires_consent: consent,
      allowed_for_credit_decision: credit,
      allowed_for_fraud_decision: fraud,
      legal_review_status: 'approved_for_mvp_seed',
      prohibited_reason_code: null,
      fairness_review_required: dimension === 'identity' || dimension === 'location',
      retention_policy_id: 102,
      is_active: true,
      _created_at: CREATED_AT,
      _updated_at: CREATED_AT,
    })),
  },
  {
    tableName: 'attribute_definitions',
    rows: [
      [
        101,
        'age_years',
        'Edad en años',
        'customer',
        'number',
        'demographic',
        'profile',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        true,
        true,
        true,
        false,
      ],
      [
        102,
        'city_zone_code',
        'Zona declarada',
        'customer',
        'string',
        'location',
        'catalog',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        true,
        true,
        true,
        true,
      ],
      [
        103,
        'occupation_category_code',
        'Categoría ocupacional',
        'customer',
        'string',
        'employment',
        'catalog',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        true,
        true,
        true,
        false,
      ],
      [
        104,
        'income_band_code',
        'Banda de ingreso declarada',
        'customer',
        'string',
        'income',
        'catalog',
        'onboarding',
        'MVP',
        'RISK_SENSITIVE',
        true,
        true,
        true,
        false,
      ],
      [
        105,
        'document_type_code',
        'Tipo de documento',
        'customer',
        'string',
        'identity',
        'catalog',
        'kyc',
        'MVP',
        'PII_HASHED',
        true,
        true,
        true,
        false,
      ],
      [
        106,
        'device_trust_tier',
        'Tier de confianza de dispositivo',
        'device',
        'string',
        'fraud',
        'computed',
        'scoring',
        'MVP',
        'RISK_SENSITIVE',
        true,
        true,
        true,
        false,
      ],
      [
        107,
        'merchant_category_code',
        'Categoría de comercio',
        'purchase',
        'string',
        'merchant',
        'catalog',
        'purchase',
        'MVP',
        'INTERNAL_OPERATIONAL',
        false,
        true,
        false,
        false,
      ],
      [
        108,
        'payment_channel_code',
        'Canal de pago',
        'payment',
        'string',
        'payment',
        'catalog',
        'purchase',
        'MVP',
        'INTERNAL_OPERATIONAL',
        false,
        true,
        false,
        false,
      ],
    ].map(([id, code, name, scope, dataType, dimension, sourceType, stage, phase, classification, consent, credit, fraud, fairness]) => ({
      _id: id,
      attribute_code: code,
      attribute_name: name,
      entity_scope: scope,
      data_type: dataType,
      risk_dimension: dimension,
      source_type: sourceType,
      availability_stage: stage,
      build_phase: phase,
      data_classification_code: classification,
      requires_consent: consent,
      is_sensitive: classification !== 'INTERNAL_OPERATIONAL',
      is_model_candidate: true,
      allowed_for_credit_decision: credit,
      allowed_for_fraud_decision: fraud,
      legal_review_status: 'approved_for_mvp_seed',
      prohibited_reason_code: null,
      fairness_review_required: fairness,
      retention_policy_id: 102,
      is_active: true,
      _created_at: CREATED_AT,
      _updated_at: CREATED_AT,
    })),
  },
  {
    tableName: 'feature_definitions',
    rows: [
      [101, 'feat_age_years', 'Edad en años', 'demographic', 'demographic', 'number'],
      [102, 'feat_device_reuse_count', 'Cantidad de clientes por dispositivo', 'device', 'fraud', 'number'],
      [103, 'feat_failed_login_count_7d', 'Intentos fallidos 7 días', 'security', 'fraud', 'number'],
      [104, 'feat_contactability_score', 'Score de contactabilidad', 'contactability', 'contactability', 'number'],
      [105, 'feat_bureau_dpd_max_12m', 'Máximo DPD buró 12 meses', 'bureau', 'credit', 'number'],
      [106, 'feat_gps_consistency_score', 'Consistencia GPS/dirección', 'location', 'consistency', 'number'],
      [107, 'feat_on_device_contacts_score', 'Puntaje agenda on-device', 'on_device', 'fraud', 'number'],
      [108, 'feat_income_band_points', 'Puntos por banda de ingreso', 'income', 'capacity', 'number'],
      [109, 'feat_kyc_match_score', 'Score de coincidencia KYC', 'identity', 'identity', 'number'],
      [110, 'feat_watchlist_hits', 'Coincidencias watchlist', 'fraud', 'fraud', 'number'],
      [111, 'feat_qr_payment_verified', 'Pago QR verificado', 'payment', 'payment', 'boolean'],
      [112, 'feat_manual_review_count', 'Histórico revisión manual', 'operations', 'operations', 'number'],
    ].map(([id, code, name, family, dimension, dataType]) => ({
      _id: id,
      feature_code: code,
      feature_name: name,
      feature_family: family,
      risk_dimension: dimension,
      data_type: dataType,
      availability_tier: 'mvp_seed',
      build_phase: 'MVP',
      data_classification_code: 'RISK_SENSITIVE',
      calculation_kind: 'deterministic_seed_or_rule',
      default_missing_strategy: 'neutral_points_and_review_if_critical',
      is_model_input: true,
      is_policy_rule_input: true,
      is_sensitive: true,
      allowed_for_credit_decision: true,
      allowed_for_fraud_decision: true,
      legal_review_status: 'approved_for_mvp_seed',
      prohibited_reason_code: null,
      fairness_review_required: dimension === 'demographic' || dimension === 'location',
      retention_policy_id: 102,
      owner_team: 'risk',
      is_active: true,
      _created_at: CREATED_AT,
      _updated_at: CREATED_AT,
    })),
  },
];

const RISK_TABLES: SeedTable[] = [
  {
    tableName: 'risk_model_versions',
    rows: [
      {
        _id: 101,
        model_code: 'atlas_bnpl_application_score',
        version_code: 'v1-seed',
        model_type: 'scorecard_placeholder',
        assessment_type: 'onboarding_credit',
        status: 'active',
        effective_from: CREATED_AT,
        effective_until: null,
        approved_by_platform_user_id: 1,
        approved_at: CREATED_AT,
        artifact_url: 'seed://risk/atlas_bnpl_application_score/v1',
        artifact_hash: 'seed-artifact-hash-v1',
        _created_at: CREATED_AT,
      },
    ],
  },
  {
    tableName: 'risk_ruleset_versions',
    rows: [
      {
        _id: 101,
        ruleset_code: 'atlas_mvp_onboarding_ruleset',
        version_code: 'v1-seed',
        assessment_type: 'onboarding_credit',
        status: 'active',
        effective_from: CREATED_AT,
        effective_until: null,
        approved_by_platform_user_id: 1,
        approved_at: CREATED_AT,
        _created_at: CREATED_AT,
      },
    ],
  },
  {
    tableName: 'risk_policy_rules',
    rows: [
      [
        101,
        'block_missing_required_consent',
        'Bloquear si falta consentimiento requerido',
        'legal',
        'hard_stop',
        'critical',
        { all: [{ field: 'hasRequiredConsent', equals: false }] },
        'BLOCK',
        'MISSING_REQUIRED_CONSENT',
        true,
      ],
      [
        102,
        'manual_review_device_reuse_high',
        'Revisión si el dispositivo se reutiliza demasiado',
        'fraud',
        'manual_review',
        'high',
        { any: [{ field: 'feat_device_reuse_count', gte: 3 }] },
        'MANUAL_REVIEW',
        'HIGH_DEVICE_REUSE',
        false,
      ],
      [
        103,
        'manual_review_gps_mismatch',
        'Revisión si GPS difiere de dirección declarada',
        'consistency',
        'manual_review',
        'medium',
        { any: [{ field: 'feat_gps_consistency_score', lt: 40 }] },
        'MANUAL_REVIEW',
        'GPS_DECLARED_ADDRESS_MISMATCH',
        false,
      ],
      [
        104,
        'block_negative_bureau_hit',
        'Bloquear si buró reporta mora grave',
        'credit',
        'hard_stop',
        'critical',
        { any: [{ field: 'feat_bureau_dpd_max_12m', gte: 90 }] },
        'BLOCK',
        'BUREAU_HIT_NEGATIVE',
        true,
      ],
      [
        105,
        'approve_good_contactability',
        'Aprobar si score y contactabilidad son suficientes',
        'contactability',
        'approve_rule',
        'low',
        {
          all: [
            { field: 'score_total', gte: 75 },
            { field: 'feat_contactability_score', gte: 70 },
          ],
        },
        'APPROVE',
        'GOOD_CONTACTABILITY',
        false,
      ],
      [
        106,
        'cap_line_low_income_band',
        'Limitar línea inicial por banda de ingreso baja',
        'capacity',
        'line_cap',
        'medium',
        { any: [{ field: 'income_band_code', equals: 'income_0_2000' }] },
        'CAP_CREDIT_LINE',
        'LOW_INCOME_BAND',
        false,
      ],
    ].map(([id, code, name, dimension, type, severity, expr, action, reason, hardStop]) => ({
      _id: id,
      ruleset_version_id: 101,
      rule_code: code,
      rule_name: name,
      risk_dimension: dimension,
      rule_type: type,
      severity,
      expression_json: jsonb(expr),
      action_code: action,
      reason_code: reason,
      is_hard_stop: hardStop,
      _created_at: CREATED_AT,
    })),
  },
  {
    tableName: 'risk_signal_seeds',
    rows: [
      [
        101,
        'signal_device_reuse',
        'Reuso de dispositivo',
        'feature',
        'devices',
        'feat_device_reuse_count',
        'fraud',
        'HIGH',
        'higher_is_riskier',
        { value: 3 },
      ],
      [
        102,
        'signal_contactability',
        'Contactabilidad',
        'feature',
        'customer_contact_methods',
        'feat_contactability_score',
        'contactability',
        'HIGH',
        'higher_is_better',
        { value: 82 },
      ],
      [
        103,
        'signal_bureau_dpd',
        'Mora máxima en buró',
        'feature',
        'data_provider_responses',
        'feat_bureau_dpd_max_12m',
        'credit',
        'HIGH',
        'higher_is_riskier',
        { value: 0 },
      ],
      [
        104,
        'signal_gps_consistency',
        'Consistencia geográfica',
        'feature',
        'address_gps_observations',
        'feat_gps_consistency_score',
        'consistency',
        'MEDIUM',
        'higher_is_better',
        { value: 88 },
      ],
      [
        105,
        'signal_kyc_match',
        'Coincidencia KYC',
        'feature',
        'customer_identity_documents',
        'feat_kyc_match_score',
        'identity',
        'HIGH',
        'higher_is_better',
        { value: 95 },
      ],
    ].map(([id, code, name, type, source, target, dimension, priority, direction, example]) => ({
      _id: id,
      signal_code: code,
      signal_name: name,
      signal_type: type,
      source_entity: source,
      target_definition_code: target,
      risk_dimension: dimension,
      build_phase: 'MVP',
      priority,
      expected_direction: direction,
      example_value_json: jsonb(example),
      rationale: 'Señal semilla para explicar al portal qué datos se catalogan y cómo alimentan scoring/riesgo.',
      is_active: true,
      _created_at: CREATED_AT,
      _updated_at: CREATED_AT,
    })),
  },
];

const GOVERNANCE_TABLES: SeedTable[] = [
  {
    tableName: 'sensitive_field_rules',
    rows: [
      [101, 'customers', 'primary_phone_hash', 'PII_HASHED', 'hash', 'exact_hash', 'last4_mask', 'risk_ops_need_to_know', 101],
      [102, 'customers', 'email_hash', 'PII_HASHED', 'hash', 'exact_hash', 'masked_email', 'risk_ops_need_to_know', 101],
      [
        103,
        'customer_identity_documents',
        'document_number_hash',
        'PII_HASHED',
        'hash',
        'exact_hash',
        'document_mask',
        'compliance_only',
        101,
      ],
      [
        104,
        'customer_contact_methods',
        'contact_value_encrypted',
        'PII_ENCRYPTED',
        'encrypted',
        'hash_lookup',
        'contact_mask',
        'customer_service_limited',
        101,
      ],
      [105, 'auth_credentials', 'password_hash', 'PII_HASHED', 'hash', 'no_search', 'never_show', 'security_only', 103],
      [
        106,
        'device_tokens',
        'token_encrypted',
        'PII_ENCRYPTED',
        'encrypted',
        'hash_lookup',
        'never_show',
        'notification_service_only',
        105,
      ],
      [
        107,
        'data_provider_responses',
        'response_payload_json',
        'EXTERNAL_PROVIDER_PAYLOAD',
        'redacted',
        'hash_lookup',
        'redacted_json',
        'compliance_and_risk',
        104,
      ],
    ].map(([id, table, field, classification, storage, search, mask, policy, retention]) => ({
      _id: id,
      table_name: table,
      field_name: field,
      classification_code: classification,
      storage_mode: storage,
      search_strategy: search,
      masking_strategy: mask,
      access_policy_code: policy,
      retention_policy_id: retention,
      is_active: true,
      _created_at: CREATED_AT,
      _updated_at: CREATED_AT,
    })),
  },
  {
    tableName: 'data_quality_rules',
    rows: [
      [
        101,
        'customer_requires_phone_hash',
        'Cliente debe tener teléfono hasheado',
        'customers',
        'primary_phone_hash',
        'critical',
        { required: true },
        'block_onboarding_completion',
      ],
      [
        102,
        'identity_document_hash_required',
        'Documento debe guardarse hasheado',
        'customer_identity_documents',
        'document_number_hash',
        'critical',
        { required: true, rawStorageForbidden: true },
        'block_kyc_completion',
      ],
      [
        103,
        'risk_result_has_reason_codes',
        'Resultado de riesgo debe tener reason codes',
        'risk_assessment_results',
        'reason_codes_json',
        'high',
        { required: true, minItems: 1 },
        'send_to_manual_review',
      ],
      [
        104,
        'provider_response_must_be_redacted_or_hash',
        'Respuesta proveedor debe tener payload redactado/hash',
        'data_provider_responses',
        'redacted_payload_json',
        'high',
        { required: true },
        'quarantine_provider_payload',
      ],
      [
        105,
        'endpoint_business_purpose_required',
        'Endpoint debe tener propósito de negocio',
        'system_endpoint_catalog',
        'business_purpose',
        'medium',
        { required: true, minLength: 20 },
        'send_to_systems_review_queue',
      ],
    ].map(([id, code, name, table, field, severity, expr, action]) => ({
      _id: id,
      rule_code: code,
      rule_name: name,
      target_table: table,
      target_field: field,
      severity,
      expression_json: jsonb(expr),
      expected_action: action,
      build_phase: 'MVP',
      is_active: true,
      _created_at: CREATED_AT,
      _updated_at: CREATED_AT,
    })),
  },
  {
    tableName: 'data_quality_issues',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        quality_rule_id: 103,
        target_table: 'risk_assessment_results',
        target_record_id: '1',
        issue_status: 'open',
        detected_at: CREATED_AT,
        resolved_at: null,
        resolution_notes: 'Issue demo para que la vista de calidad no cargue vacía.',
        _created_at: CREATED_AT,
      },
      {
        _id: 102,
        _tenant_id: 1,
        quality_rule_id: 105,
        target_table: 'system_endpoint_catalog',
        target_record_id: 'auto',
        issue_status: 'open',
        detected_at: CREATED_AT,
        resolved_at: null,
        resolution_notes: 'Revisar endpoints auto-detectados antes de pasar a producción.',
        _created_at: CREATED_AT,
      },
    ],
  },
];

const NOTIFICATION_TABLES: SeedTable[] = [
  {
    tableName: 'notification_templates',
    rows: [
      [
        101,
        'onboarding_welcome',
        'in_app',
        'es-BO',
        'Bienvenido a Atlas',
        'Bienvenido a Atlas',
        'Hola {{firstName}}, tu registro fue iniciado correctamente.',
      ],
      [
        102,
        'payment_reminder_48h',
        'whatsapp',
        'es-BO',
        'Recordatorio de cuota',
        null,
        'Hola {{firstName}}, recuerda revisar tu próxima cuota Atlas.',
      ],
      [
        103,
        'manual_review_opened',
        'email',
        'es-BO',
        'Revisión manual abierta',
        'Caso requiere revisión',
        'El cliente {{customerId}} requiere revisión manual por {{reasonCode}}.',
      ],
      [104, 'risk_decision_ready', 'in_app', 'es-BO', 'Resultado disponible', null, 'Tu evaluación Atlas ya tiene resultado.'],
      [
        105,
        'provider_failure_alert',
        'email',
        'es-BO',
        'Proveedor con error',
        'Proveedor externo con error',
        'El proveedor {{providerCode}} reportó error seguro: {{errorCode}}.',
      ],
    ].map(([id, code, channel, locale, title, subject, body]) => ({
      _id: id,
      _tenant_id: 1,
      code,
      channel,
      locale,
      title_template: title,
      subject_template: subject,
      body_template: body,
      payload_schema_json: jsonb({
        firstName: 'string|optional',
        customerId: 'number|optional',
        reasonCode: 'string|optional',
        providerCode: 'string|optional',
        errorCode: 'string|optional',
      }),
      is_active: true,
      version: 1,
      _created_at: CREATED_AT,
      _updated_at: CREATED_AT,
    })),
  },
  {
    tableName: 'outbox_events',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        aggregate_type: 'customer',
        aggregate_id: '1',
        event_code: 'customer_onboarding_started',
        event_payload_json: jsonb({ customerId: 1, source: 'seed' }),
        event_family: 'customer',
        event_version: 1,
        metadata_json: jsonb({ seed: true }),
        status: 'pending',
        priority: 5,
        attempts: 0,
        max_attempts: 3,
        locked_at: null,
        locked_by: null,
        available_at: CREATED_AT,
        processed_at: null,
        failed_at: null,
        error_code: null,
        last_error: null,
        correlation_id: 'seed-corr-101',
        idempotency_key: 'seed-outbox-101',
        causation_id: null,
        source_module: 'onboarding',
        source_action: 'seed',
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
      {
        _id: 102,
        _tenant_id: 1,
        aggregate_type: 'risk',
        aggregate_id: '1',
        event_code: 'risk_assessment_completed',
        event_payload_json: jsonb({ customerId: 1, riskRunId: 1 }),
        event_family: 'risk',
        event_version: 1,
        metadata_json: jsonb({ seed: true }),
        status: 'processed',
        priority: 4,
        attempts: 1,
        max_attempts: 3,
        locked_at: null,
        locked_by: null,
        available_at: CREATED_AT,
        processed_at: CREATED_AT,
        failed_at: null,
        error_code: null,
        last_error: null,
        correlation_id: 'seed-corr-102',
        idempotency_key: 'seed-outbox-102',
        causation_id: 'seed-corr-101',
        source_module: 'risk',
        source_action: 'seed',
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
      {
        _id: 103,
        _tenant_id: 1,
        aggregate_type: 'provider',
        aggregate_id: 'INFOCENTER',
        event_code: 'provider_request_completed',
        event_payload_json: jsonb({ providerCode: 'INFOCENTER', mode: 'mock_local' }),
        event_family: 'external_data',
        event_version: 1,
        metadata_json: jsonb({ seed: true }),
        status: 'pending',
        priority: 3,
        attempts: 0,
        max_attempts: 3,
        locked_at: null,
        locked_by: null,
        available_at: CREATED_AT,
        processed_at: null,
        failed_at: null,
        error_code: null,
        last_error: null,
        correlation_id: 'seed-corr-103',
        idempotency_key: 'seed-outbox-103',
        causation_id: null,
        source_module: 'external_data',
        source_action: 'seed',
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
    ],
  },
  {
    tableName: 'notification_messages',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        outbox_event_id: 101,
        recipient_type: 'customer',
        recipient_id: '1',
        channel: 'in_app',
        template_code: 'onboarding_welcome',
        subject: null,
        title: 'Bienvenido a Atlas',
        body: 'Hola Cliente Demo, tu registro fue iniciado correctamente.',
        payload_json: jsonb({ firstName: 'Cliente Demo' }),
        delivery_targets_json: jsonb([{ type: 'in_app', customerId: 1 }]),
        status: 'queued',
        priority: 5,
        scheduled_at: CREATED_AT,
        queued_at: CREATED_AT,
        sent_at: null,
        delivered_at: null,
        read_at: null,
        failed_at: null,
        cancelled_at: null,
        idempotency_key: 'seed-notification-101',
        correlation_id: 'seed-corr-101',
        causation_id: null,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
      {
        _id: 102,
        _tenant_id: 1,
        outbox_event_id: 103,
        recipient_type: 'internal_user',
        recipient_id: '1',
        channel: 'email',
        template_code: 'provider_failure_alert',
        subject: 'Proveedor externo con error',
        title: 'Proveedor con error',
        body: 'El proveedor INFOCENTER está en modo mock para pruebas.',
        payload_json: jsonb({ providerCode: 'INFOCENTER', errorCode: 'MOCK_MODE' }),
        delivery_targets_json: jsonb([{ type: 'email', masked: 'pa***@atlas.internal' }]),
        status: 'sent',
        priority: 3,
        scheduled_at: CREATED_AT,
        queued_at: CREATED_AT,
        sent_at: CREATED_AT,
        delivered_at: CREATED_AT,
        read_at: null,
        failed_at: null,
        cancelled_at: null,
        idempotency_key: 'seed-notification-102',
        correlation_id: 'seed-corr-103',
        causation_id: null,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
    ],
  },
  {
    tableName: 'notification_deliveries',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        notification_message_id: 101,
        channel: 'in_app',
        provider: 'internal',
        provider_message_id: 'seed-inapp-101',
        status: 'queued',
        attempt_number: 1,
        error_code: null,
        error_message: null,
        request_payload_json: jsonb({ seed: true }),
        response_payload_json: jsonb({ accepted: true }),
        sent_at: null,
        delivered_at: null,
        failed_at: null,
        _created_at: CREATED_AT,
      },
      {
        _id: 102,
        _tenant_id: 1,
        notification_message_id: 102,
        channel: 'email',
        provider: 'webhook_mock',
        provider_message_id: 'seed-email-102',
        status: 'delivered',
        attempt_number: 1,
        error_code: null,
        error_message: null,
        request_payload_json: jsonb({ seed: true }),
        response_payload_json: jsonb({ delivered: true }),
        sent_at: CREATED_AT,
        delivered_at: CREATED_AT,
        failed_at: null,
        _created_at: CREATED_AT,
      },
    ],
  },
  {
    tableName: 'user_notification_preferences',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        customer_id: 1,
        event_code: 'payment_reminder_48h',
        channel: 'whatsapp',
        is_enabled: true,
        is_required: false,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
      {
        _id: 102,
        _tenant_id: 1,
        customer_id: 1,
        event_code: 'risk_decision_ready',
        channel: 'in_app',
        is_enabled: true,
        is_required: true,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
    ],
  },
];

const SEED_TABLES: SeedTable[] = [
  { tableName: 'retention_policies', rows: RETENTION_ROWS },
  { tableName: 'privacy_processing_purposes', rows: PURPOSE_ROWS },
  { tableName: 'data_classification_policies', rows: CLASSIFICATION_ROWS },
  {
    tableName: 'context_sources',
    rows: [
      {
        _id: 101,
        source_code: 'atlas_seed_manual',
        source_name: 'Atlas Seed Manual',
        source_type: 'manual_seed',
        reliability_score: '95.00',
        refresh_frequency: 'on_seed',
        notes: 'Fuente semilla controlada para arrancar portal y catálogos.',
        is_active: true,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
    ],
  },
  { tableName: 'context_catalogs', rows: CATALOGS },
  { tableName: 'context_catalog_versions', rows: CATALOG_VERSIONS },
  { tableName: 'context_items', rows: CONTEXT_ITEMS },
  {
    tableName: 'context_item_aliases',
    rows: [
      {
        _id: 101,
        context_item_id: 1001,
        alias_value: 'centro scz',
        alias_type: 'normalized',
        normalized_alias: 'centro scz',
        confidence_score: '98.00',
        _created_at: CREATED_AT,
      },
      {
        _id: 102,
        context_item_id: 1004,
        alias_value: 'plan tres mil',
        alias_type: 'normalized',
        normalized_alias: 'plan tres mil',
        confidence_score: '98.00',
        _created_at: CREATED_AT,
      },
      {
        _id: 103,
        context_item_id: 1051,
        alias_value: 'qr',
        alias_type: 'short_label',
        normalized_alias: 'qr',
        confidence_score: '99.00',
        _created_at: CREATED_AT,
      },
    ],
  },
  {
    tableName: 'context_risk_mappings',
    rows: [
      {
        _id: 101,
        context_item_id: 1042,
        risk_dimension: 'fraud',
        risk_band: 'high',
        score_points_suggested: '-35.00',
        reason_code: 'HIGH_DEVICE_REUSE',
        explanation: 'Dispositivo observado en varios clientes aumenta riesgo de fraude.',
        model_usage: 'policy_and_scorecard_seed',
        valid_from: '2026-01-01',
        valid_until: null,
        _created_at: CREATED_AT,
      },
      {
        _id: 102,
        context_item_id: 1045,
        risk_dimension: 'contactability',
        risk_band: 'low',
        score_points_suggested: '15.00',
        reason_code: 'GOOD_CONTACTABILITY',
        explanation: 'Contacto confirmado reduce incertidumbre operativa.',
        model_usage: 'policy_and_scorecard_seed',
        valid_from: '2026-01-01',
        valid_until: null,
        _created_at: CREATED_AT,
      },
      {
        _id: 103,
        context_item_id: 1046,
        risk_dimension: 'consistency',
        risk_band: 'medium_high',
        score_points_suggested: '-20.00',
        reason_code: 'GPS_DECLARED_ADDRESS_MISMATCH',
        explanation: 'Inconsistencia entre GPS y dirección requiere revisión.',
        model_usage: 'policy_and_scorecard_seed',
        valid_from: '2026-01-01',
        valid_until: null,
        _created_at: CREATED_AT,
      },
    ],
  },
  ...DEFINITIONS,
  {
    tableName: 'event_definitions',
    rows: [
      {
        _id: 101,
        event_code: 'customer_onboarding_started',
        event_name: 'Onboarding iniciado',
        event_family: 'customer',
        source_package: 'customer-onboarding',
        target_tables_json: jsonb(['customers', 'onboarding_flows']),
        expected_payload_schema_json: jsonb({ customerId: 'number' }),
        risk_dimension: 'lifecycle',
        build_phase: 'MVP',
        data_classification_code: 'INTERNAL_OPERATIONAL',
        retention_policy_id: 103,
        is_high_volume: true,
        is_active: true,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
      {
        _id: 102,
        event_code: 'risk_assessment_completed',
        event_name: 'Evaluación de riesgo completada',
        event_family: 'risk',
        source_package: 'risk',
        target_tables_json: jsonb(['risk_assessment_runs', 'risk_assessment_results']),
        expected_payload_schema_json: jsonb({ customerId: 'number', runId: 'number' }),
        risk_dimension: 'credit',
        build_phase: 'MVP',
        data_classification_code: 'RISK_SENSITIVE',
        retention_policy_id: 102,
        is_high_volume: true,
        is_active: true,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
      {
        _id: 103,
        event_code: 'manual_review_opened',
        event_name: 'Revisión manual abierta',
        event_family: 'operations',
        source_package: 'risk',
        target_tables_json: jsonb(['manual_review_cases']),
        expected_payload_schema_json: jsonb({ caseId: 'number' }),
        risk_dimension: 'operations',
        build_phase: 'MVP',
        data_classification_code: 'INTERNAL_OPERATIONAL',
        retention_policy_id: 103,
        is_high_volume: false,
        is_active: true,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
      {
        _id: 104,
        event_code: 'provider_request_completed',
        event_name: 'Proveedor externo completado',
        event_family: 'external_data',
        source_package: 'external-data',
        target_tables_json: jsonb(['data_provider_requests', 'data_provider_responses']),
        expected_payload_schema_json: jsonb({ providerCode: 'string', mode: 'string' }),
        risk_dimension: 'external_provider',
        build_phase: 'MVP',
        data_classification_code: 'EXTERNAL_PROVIDER_PAYLOAD',
        retention_policy_id: 104,
        is_high_volume: false,
        is_active: true,
        _created_at: CREATED_AT,
        _updated_at: CREATED_AT,
      },
    ],
  },
  ...RISK_TABLES,
  ...GOVERNANCE_TABLES,
  {
    tableName: 'feature_computation_runs',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        subject_type: 'customer',
        subject_id: 1,
        customer_id: 1,
        session_id: 1,
        onboarding_flow_id: 1,
        device_id: 1,
        run_reason: 'seed_portal_demo',
        trigger_source: 'system_seed',
        idempotency_key: 'seed-feature-run-101',
        feature_set_version: 'v1-seed',
        code_version: 'seed',
        computed_by: 'system_seed',
        retry_count: 0,
        started_at: CREATED_AT,
        finished_at: CREATED_AT,
        status: 'completed',
        error_message: null,
        _created_at: CREATED_AT,
      },
    ],
  },
  {
    tableName: 'feature_values',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        computation_run_id: 101,
        feature_definition_id: 104,
        subject_type: 'customer',
        subject_id: 1,
        customer_id: 1,
        session_id: 1,
        onboarding_flow_id: 1,
        device_id: 1,
        value_text: null,
        value_number: '82.0000',
        value_boolean: null,
        value_json: jsonb({ band: 'good' }),
        confidence_score: '90.00',
        derivation_method: 'seed_rule',
        derivation_version: 'v1-seed',
        valid_from: CREATED_AT,
        valid_until: null,
        _created_at: CREATED_AT,
      },
      {
        _id: 102,
        _tenant_id: 1,
        computation_run_id: 101,
        feature_definition_id: 102,
        subject_type: 'device',
        subject_id: 1,
        customer_id: 1,
        session_id: 1,
        onboarding_flow_id: 1,
        device_id: 1,
        value_text: null,
        value_number: '1.0000',
        value_boolean: null,
        value_json: jsonb({ band: 'low' }),
        confidence_score: '90.00',
        derivation_method: 'seed_rule',
        derivation_version: 'v1-seed',
        valid_from: CREATED_AT,
        valid_until: null,
        _created_at: CREATED_AT,
      },
      {
        _id: 103,
        _tenant_id: 1,
        computation_run_id: 101,
        feature_definition_id: 105,
        subject_type: 'customer',
        subject_id: 1,
        customer_id: 1,
        session_id: 1,
        onboarding_flow_id: 1,
        device_id: 1,
        value_text: null,
        value_number: '0.0000',
        value_boolean: null,
        value_json: jsonb({ bureau: 'mock_clean' }),
        confidence_score: '80.00',
        derivation_method: 'provider_mock',
        derivation_version: 'v1-seed',
        valid_from: CREATED_AT,
        valid_until: null,
        _created_at: CREATED_AT,
      },
    ],
  },
  ...NOTIFICATION_TABLES,
  {
    tableName: 'system_job_runs',
    rows: [
      {
        _id: 101,
        _tenant_id: 1,
        job_code: 'process_outbox_seed_demo',
        status: 'completed',
        started_at: CREATED_AT,
        completed_at: CREATED_AT,
        input_json: jsonb({ batchSize: 50 }),
        result_json: jsonb({ processed: 1, pending: 2 }),
        error_message: null,
        triggered_by_type: 'seed',
        triggered_by_id: 'system_seed',
        _created_at: CREATED_AT,
      },
      {
        _id: 102,
        _tenant_id: 1,
        job_code: 'recalculate_data_quality_seed_demo',
        status: 'completed',
        started_at: CREATED_AT,
        completed_at: CREATED_AT,
        input_json: jsonb({ scope: 'seed' }),
        result_json: jsonb({ openIssues: 2 }),
        error_message: null,
        triggered_by_type: 'seed',
        triggered_by_id: 'system_seed',
        _created_at: CREATED_AT,
      },
    ],
  },

  {
    tableName: 'system_action_logs',
    rows: [
      {
        _id: 101,
        request_id: 'seed-req-dashboard-101',
        correlation_id: 'seed-corr-dashboard-101',
        endpoint_catalog_id: null,
        actor_user_id: '1',
        actor_type: 'internal_user',
        actor_role: 'atlas_super_admin',
        actor_internal_user_id: 1,
        actor_platform_user_id: 1,
        method: 'GET',
        route_template: '/api/v1/systems/dashboard',
        resolved_url_sanitized: '/api/v1/systems/dashboard',
        module: 'systems',
        action_name: 'dashboard_read',
        ip_address: '127.0.0.1',
        user_agent: 'atlas-seed-smoke',
        target_type: 'dashboard',
        target_id: 'systems-dashboard',
        merchant_id: null,
        customer_id: null,
        request_payload_sanitized: jsonb({ query: {}, body: null }),
        request_payload_hash: 'seed-dashboard-hash',
        response_status_code: 200,
        response_summary_sanitized: jsonb({ status: 'ok', source: 'seed', purpose: 'evitar_tabla_vacia' }),
        error_code: null,
        error_message: null,
        duration_ms: 42,
        idempotency_key_hash: null,
        idempotency_key_last4: null,
        risk_level: 'LOW',
        contains_pii: false,
        occurred_at: CREATED_AT,
        _created_at: CREATED_AT,
      },
      {
        _id: 102,
        request_id: 'seed-req-data-quality-102',
        correlation_id: 'seed-corr-data-quality-102',
        endpoint_catalog_id: null,
        actor_user_id: '1',
        actor_type: 'internal_user',
        actor_role: 'atlas_super_admin',
        actor_internal_user_id: 1,
        actor_platform_user_id: 1,
        method: 'GET',
        route_template: '/api/v1/internal/data-quality/rules',
        resolved_url_sanitized: '/api/v1/internal/data-quality/rules?page=1&limit=20',
        module: 'internal-portal',
        action_name: 'data_quality_rules_read',
        ip_address: '127.0.0.1',
        user_agent: 'atlas-seed-smoke',
        target_type: 'data_quality_rules',
        target_id: 'all',
        merchant_id: null,
        customer_id: null,
        request_payload_sanitized: jsonb({ query: { page: 1, limit: 20 }, body: null }),
        request_payload_hash: 'seed-dq-hash',
        response_status_code: 200,
        response_summary_sanitized: jsonb({ status: 'ok', items: 5, source: 'seed' }),
        error_code: null,
        error_message: null,
        duration_ms: 56,
        idempotency_key_hash: null,
        idempotency_key_last4: null,
        risk_level: 'MEDIUM',
        contains_pii: false,
        occurred_at: CREATED_AT,
        _created_at: CREATED_AT,
      },
      {
        _id: 103,
        request_id: 'seed-req-governance-103',
        correlation_id: 'seed-corr-governance-103',
        endpoint_catalog_id: null,
        actor_user_id: '1',
        actor_type: 'internal_user',
        actor_role: 'atlas_super_admin',
        actor_internal_user_id: 1,
        actor_platform_user_id: 1,
        method: 'GET',
        route_template: '/api/v1/operations/data-governance/policies',
        resolved_url_sanitized: '/api/v1/operations/data-governance/policies',
        module: 'governance',
        action_name: 'governance_policy_inventory_read',
        ip_address: '127.0.0.1',
        user_agent: 'atlas-seed-smoke',
        target_type: 'governance_policy',
        target_id: 'all',
        merchant_id: null,
        customer_id: null,
        request_payload_sanitized: jsonb({ query: {}, body: null }),
        request_payload_hash: 'seed-governance-hash',
        response_status_code: 200,
        response_summary_sanitized: jsonb({ status: 'ok', source: 'seed', policyFamilies: 5 }),
        error_code: null,
        error_message: null,
        duration_ms: 61,
        idempotency_key_hash: null,
        idempotency_key_last4: null,
        risk_level: 'MEDIUM',
        contains_pii: false,
        occurred_at: CREATED_AT,
        _created_at: CREATED_AT,
      },
    ],
  },
];

async function resetSequence(queryInterface: QueryInterface, tableName: string, transaction: Transaction): Promise<void> {
  await queryInterface.sequelize.query(
    `SELECT setval(pg_get_serial_sequence('${tableName}', '_id'), COALESCE((SELECT MAX(_id) FROM ${tableName}), 1), true);`,
    { transaction },
  );
}

async function insertTable(queryInterface: QueryInterface, table: SeedTable, transaction: Transaction): Promise<void> {
  if (table.rows.length === 0) return;
  await queryInterface.bulkInsert(table.tableName, table.rows, { transaction });
  await resetSequence(queryInterface, table.tableName, transaction);
}

async function deleteSeedRows(queryInterface: QueryInterface, transaction: Transaction): Promise<void> {
  for (const table of [...SEED_TABLES].reverse()) {
    const ids = table.rows.map((row) => row._id).filter((id): id is number => typeof id === 'number');
    if (ids.length === 0) continue;
    await queryInterface.sequelize.query(`DELETE FROM ${table.tableName} WHERE _id IN (:ids);`, { replacements: { ids }, transaction });
  }
  await queryInterface.sequelize.query(`DELETE FROM provider_health_logs WHERE metadata_json->>'seed' = 'portal_runtime_demo';`, {
    transaction,
  });
}

async function seedProviderHealth(queryInterface: QueryInterface, transaction: Transaction): Promise<void> {
  await queryInterface.sequelize.query(
    `INSERT INTO provider_health_logs (provider_id, status, mode_checked, latency_ms, checked_at, error_code, error_message_safe, metadata_json)
     SELECT _id,
       CASE WHEN provider_code IN ('SEGIP', 'INFOCENTER') THEN 'healthy' ELSE 'mock_only' END,
       default_mode,
       CASE WHEN provider_code = 'INFOCENTER' THEN 420 ELSE 160 END,
       :createdAt,
       NULL,
       NULL,
       '{"seed":"portal_runtime_demo"}'::jsonb
     FROM data_providers
     WHERE provider_code IN ('SEGIP','INFOCENTER','QR_GENERIC','BANKING_GENERIC','TELCO_GENERIC','WHATSAPP_GENERIC','DIGITAL_TRUST_GENERIC');`,
    { replacements: { createdAt: CREATED_AT }, transaction },
  );
}

export async function up({ context: queryInterface }: SeedContext): Promise<void> {
  await queryInterface.sequelize.transaction(async (transaction) => {
    await deleteSeedRows(queryInterface, transaction);
    for (const table of SEED_TABLES) await insertTable(queryInterface, table, transaction);
    await seedProviderHealth(queryInterface, transaction);
  });
}

export async function down({ context: queryInterface }: SeedContext): Promise<void> {
  await queryInterface.sequelize.transaction(async (transaction) => {
    await deleteSeedRows(queryInterface, transaction);
  });
}
